### ISSUE TITLE
No Option to Boot from LiveUSB

### ISSUE THREAD

**Issue by BryanCuneo** [BlackArch/blackarch#1007]
I am attempting to install BlackArch from a LiveUSB, but when I get to the boot menu there is no way to boot to the live environment. The options available are existing OS, memtest, hardware info, reboot, and shutdown.

I attempted to boot it by selecting memtest, hitting Tab, and running the following command:
`./linux boot/i686/vmlinuz archisobasedir=arch archisolabel=BLACKARCH_201601 initrd=boot/i686/archiso.img`

This proceeded to work and it did some stuff. Eventually this happened:
`losetup: /run/archiso/bootmnt/arch/i686/airootfs.sfs: failed to set up loop device: No such file or directory`
`:: Mounting '' to '/run/archiso/sfs/airootfs'`
`Waiting 30 seconds for device ...`
`ERROR: '' device did not show up after 30 seconds...`

It drops me into a root shell and I attempted to mount the USB drive and use the airootfs.sfs file from there, but that didn't work. Here's what I did:
`mkdir /mnt`
`mount /dev/sdb1 /mnt`
`losetup /run/archiso/sfs/airootfs/ /mnt/blackarch/i686/airootfs.sfs`

I received this error:
`losetup: /mnt/blackarch/i686/airootfs.sfs: failed to set up loop device: Inappropriate ioctl for device`

I'm out of ideas as to where to go from here. The missing packages issue prevents me from installing on top of an existing Arch install and now I can't install from the LiveISO either. What's the next step in trying to get this installed?

**Comment by noptrix** [comment]
hi. thx for reporting. this still seems the same issue about "i686 live-iso"-boot-ups. we will fix it soon. maybe you should stick with x86_64 instead. i will close this issue as it went to a well-known issue and we are working on it :)

**Comment by BryanCuneo** [comment]
Alright, thank you. I will await a fix as the laptop I was attempting to install on is using a 32bit processor.
