### ISSUE TITLE
Problem installing Backarch on existing Arch

### ISSUE THREAD

**Issue by oliverstone30** [BlackArch/blackarch#1009]
So basically I am new with Arch and I'm also trying to install Blackarch. Unluckily I can't find the solution to my problem. Using blackman, which I think is the fastest way to install it, I get an error when using root as it follows:

[root@archlinux ~]# sudo blackman -a
--==[ blackman - BlackArch ]==--
[+] Installing blackarch group
[+] Installing fusil package
[+] BlackArch dependencies detected - Installing...
[-] CRITICAL: blackman must not be run as root
[-] CRITICAL: blackman must not be run as root

And of course when not in Root, I get the error that it doesn't have the privileges to build folders and dependencies.

And going the long way using Pacman -S blackarch after it finishes downloading all the pkg and when it has to start installing them I get this message
failed to commits transaction (unexpected error)
no packages were upgrade.

For this problem I tried a lot of possible things, for example chaging mirrors multiple times following the comand pacman -Syu and then re trying. And still nothing.
I also tried updating multiple times the keyrings and checking them and I have no errors with them. I also tried   chmod +x strap.sh     before runnging the command   sudo ./strap.sh    and still nothing.
I am going to make a quick premise. I am running Arch i686 on vmware workstation 10 if that matters and the partition is being done with dos and not gpt.
Can please someone help me to solve this problem? it's been already 5 days I am trying to get ahead of this situation.
Thanks for your time and help.
If I have to provide you something else just tell me and I'll do.

**Comment by noptrix** [comment]
hey. can you please install your arch linux and add our repository on top of it by doing so: https://www.blackarch.org/downloads.html#install-repo (ignore the blackman part). so: 1. run strap.sh 2. run pacman -Syy and 3rd install blackarch, or groups or single packages.

**Comment by noptrix** [comment]
please use: pacman -Syyu --force --needed blackarch

**Comment by narutowindy** [comment]
no way im gonna install all the packages in blackarch..... i just want a single package from blackarch repo..the problem exist using blackman.........
