### ISSUE TITLE
Package Install Issues

### ISSUE THREAD

**Issue by Chronos664** [BlackArch/blackarch#1012]
I have been trying to do a fresh install of the latest version of blackarch x86 (pc specs attached). However whenever i try to do a full install with pacman -Syyu blackarch, 11 packages fail to be retrieved with a 404.

I have tried multiple mirrors and still no luck currently.

Also attached are my pacman.conf and the output from the install.

[pcinfo.txt](https://github.com/BlackArch/blackarch/files/109574/pcinfo.txt)
[errors.txt](https://github.com/BlackArch/blackarch/files/109575/errors.txt)
[pacman.conf.txt](https://github.com/BlackArch/blackarch/files/109578/pacman.conf.txt)

**Comment by noptrix** [comment]
thx for reporting, will be fixed

**Comment by noptrix** [comment]
should be fixed now.

**Comment by noptrix** [comment]
please re-run: pacman -Scc ; pacman -Syyu --force --needed blackarch

**Comment by Chronos664** [comment]
Hi, i hve just tried that, now with only one package failing: ruby-record-0.0.1-2 with a 404

**Comment by noptrix** [comment]
ok, simply ignore the jigsaw package, which depends on ruby-record, e.g.: pacman -Syyu --force --ignore jigsaw --needed blackarch
