### ISSUE TITLE
testssl is missing dnsutils dependency

### ISSUE THREAD

**Issue by xpac1985** [BlackArch/blackarch#1017]
When using blackarch on a minimal arch linux install (following the beginners guide on the wiki), and after installing blackarch repo using strap.sh, I installed testssl.

However, testssl reported "Fatal error: no IPv4 address for $domain.tld available" with any kind of domain, also basic IP connectivity and domain name resolution on the system works fine.

After installing "dnsutils", testssl works fine.

As I am rather new to Arch Linux (and Linux in general), I might have missed something, but in my understanding dnsutils should be a required dependency on the testssl package, right?

Thanks for your work!

**Comment by noptrix** [comment]
Hi, thank you for reporting this issue. Will be fixed

**Comment by noptrix** [comment]
Btw, you probably meant 'bind-tools'

**Comment by noptrix** [comment]
fixed and released.
