### ISSUE TITLE
vega should depend on webkitgtk2 and not on webkitgtk

### ISSUE THREAD

**Issue by bardo** [BlackArch/blackarch#1023]
With the current dependencies launching `vega` fails with the following error:
`org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]`

As specified [here](http://www.eclipse.org/swt/faq.php#browserlinux), the SWT browser links to GTK2, provided by `webkitgtk2`, and not to GTK3, which is provided by the current `webkitgtk` dependency.

Changing the package dependency will solve the issue.

**Comment by noptrix** [comment]
thanks for reporting. fixed and released.
