### ISSUE TITLE
Problem with Pacman and Blackarch .sig

### ISSUE THREAD

**Issue by ContactLeft** [BlackArch/blackarch#1029]
I am experiencing an issue with pacman while installing or upgrading packages.

It is usually fixed temporarily buy issuing a pacman-key --populate, but I am struggling to put this to bed, especially that i now autimate system upgrades across my servers.

[user0@Arch ~]$ sudo pacman-key --populate blackarch
==> Appending keys from blackarch.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key CBA3C7D4798912702DCF568E67D8BDF42AD93F4E...
  -> Locally signing key A0917C4147A37007CB54C1CFD295AA940EFDDF62...
  -> Locally signing key 8F9A9793CB8591147C2EC70566E0CDBD1E01F333...
  -> Locally signing key 4345771566D76038C7FEB43863EC0ADBEA87E4E3...
==> Importing owner trust values...
==> Updating trust database...
gpg: next trustdb check due at 2016-06-03

While issuing a pacman -Syu i get:

error: blackarch: key "7533BAFE69A25079" is unknown

when asked to import  (y/n) i get:

error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is unknown trust
error: failed to update blackarch (invalid or corrupted database (PGP signature))
error: database 'blackarch' is not valid (invalid or corrupted database (PGP signature))

I added the blackarch repo over an existing Arch install, via strap.sh (https://blackarch.org/strap.sh)

Any help is appreciated, after sifting though the wiki I am no further forward, and get redirected toward Siglevels.

below is my pacman.conf

# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

#
# GENERAL OPTIONS
#
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
HoldPkg     = pacman glibc
#XferCommand = /usr/bin/curl -C - -f %u > %o
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
#UseDelta    = 0.7
Architecture = auto

# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Misc options
#UseSyslog
Color
#TotalDownload
CheckSpace
#VerbosePkgLists

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

# NOTE: You must run `pacman-key --init` before first using pacman; the local
# keyring can then be populated with the keys of all official Arch Linux
# packagers with `pacman-key --populate archlinux`.

#
# REPOSITORIES
#   - can be defined here or included from another file
#   - pacman will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages
#     have identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#   - URLs will have $arch replaced by the name of the architecture
#
# Repository entries are of the format:
#       [repo-name]
#       Server = ServerName
#       Include = IncludePath
#
# The header [repo-name] is crucial - it must be present and
# uncommented to enable the repo.
#

# The testing repositories are disabled by default. To enable, uncomment the
# repo name header and Include lines. You can add preferred servers immediately
# after the header, and they will be used before the default mirrors.

#[testing]
#Include = /etc/pacman.d/mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

#[community-testing]
#Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

# If you want to run 32 bit applications on your x86_64 system,
# enable the multilib repositories as required here.

#[multilib-testing]
#Include = /etc/pacman.d/mirrorlist

#[multilib]
#Include = /etc/pacman.d/mirrorlist

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs
[blackarch]
Server = http://mirror.team-cymru.org/blackarch/$repo/os/$arch
#[pipelight]
#Server = http://repos.fds-team.de/stable/arch/$arch

Any help would be much appreciated.

**Comment by noptrix** [comment]
stop by irc

**Comment by noptrix** [comment]
if irc not possible do this: run: `pacman -Rscn $(pacman -Qtdq)
pacman-optimize
updatedb
sync
pkgfile -u
pacman -Scc --noconfirm
pacman-key --populate`
then run strap.sh again and perform: pacman -Syyu --needed blackarch --force

**Comment by noptrix** [comment]
23:10:36 < ContactLeft> noptrix: works great, thank you

**Comment by ContactLeft** [comment]
Thank you very much, i was stuck with this one.

**Comment by LevMasaev** [comment]
Hi there.
I have same problem,downloaded Blackarch and I can't update.
First after fresh install I had some issues with 3 packages. sqlmap and some others...
...says its corrupted, do you want to remove and doesn't matter what I choose Y/N still it stops update.
Then after some -Syyu commands with pacman came new error ->
=== error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is unknown trust
error: database 'blackarch' is not valid (invalid or corrupted database (PGP signature))

And its everywhere. I Have no tools and I can't download them.
No commands with pacman doesn't help.If I type /etc/pacman.conf says ''bash permission denied'' but I'm as root.
Command ''pacman -Rscn $(pacman -Qtdq) pacman-optimize updatedb sync pkgfile -u pacman -Scc --noconfirm pacman-key --populate'' says: pacman unrecognized option --populate.
I have no idea and no hope to fix the updates. Blackarch are completely empty with no tools at all,fresh.
Thank you, If you could help me out by reply here or in email: masaev@tutamail.com
I would be really grateful. I don't know what to do, delete blackarch or try struggle more.

**Comment by NovaCygni** [comment]
Follow this manjaro guide and simply replace "manjaro" with blackarch... this is a basic Archlinux issue not a Bug with Blackarch itself.. you should really brush up on using Archlinux before dabbling in Pentesting :\
https://forum.manjaro.org/t/how-to-solve-keyring-issues-in-manjaro/4020

**Comment by LevMasaev** [comment]
im not new in pen testing, its just first time on other disribution after backtrack and Kali, that are debian based so that was easy.

**Comment by LevMasaev** [comment]
i give up on this

**Comment by NovaCygni** [comment]
Ahh in that case, carry on ;o but yeh you really shouldve put those commands in the right order or if you wanted to bunch them all together throw in some && ;o id suggest brushing up on your bash :)

**Comment by LevMasaev** [comment]
and those commands complete errors ''could not find'' https://forum.manjaro.org/t/how-to-solve-keyring-issues-in-manjaro/4020 I'm telling you, its impossible to fix blackarch. 3 days I've been sleeping it terminal and forums, nothing.

**Comment by NovaCygni** [comment]
Well for a starter the "Fix commands" listed above, are numerous commands that yourve tried throwing into a single line.. which can be done if you put && between each command... then theres the whole "The output kinda tells you what the problem is, and logic would dictate somethings wrong with the way your inputting the command".... 
` pacman -Rscn $(pacman -Qtdq) && pacman-optimize updatedb sync pkgfile -u && pacman -Scc --noconfirm && pacman-key --populate
`

Though the Manjaro guide pretty much, Step by step, also spoonfeeds the answer...

**Comment by LevMasaev** [comment]
[ blackarch ~ ]# pacman -Rscn $(pacman -Qtdq) && pacman-optimize updatedb sync pkgfile -u && pacman -Scc --noconfirm && pacman-key --populate
error: blackarch: key "7533BAFE69A25079" is unknown

error: key "7533BAFE69A25079" could not be looked up remotely
error: blackarch: key "7533BAFE69A25079" is unknown
error: key "7533BAFE69A25079" could not be looked up remotely
error: no targets specified (use -h for help)
 That's all i get... I'm cursed maybe I need an exorcism lol 
 All I do lately - complete disaster.
 Thank you anyways NovaCygni, appreciate your help but I think I'll just shut my pc and won't open it again. Early retirement being 24 years old and unable to update my distro lol its just hilarious. 
Happy Monthers Day by the way :)

**Comment by ikstream** [comment]
for me it worked if i followed the commands in this post: 
https://www.archlinux.org/news/gnupg-21-and-the-pacman-keyring/

`pacman -Syu haveged`
`systemctl start haveged`
`systemctl enable haveged`

`rm -fr /etc/pacman.d/gnupg`
`pacman-key --init`
`pacman-key --populate archlinux`

**Comment by noraj1337** [comment]
The problem seems still here:

```
$ sudo pacman -Syy                                                                                                                                                                                                
error: blackarch: key "7533BAFE69A25079" is unknown
error: key "7533BAFE69A25079" could not be looked up remotely
:: Synchronizing package databases...
 core                                                                                                 140,6 KiB   233K/s 00:01 [#############################################################################] 100%
 extra                                                                                               1758,1 KiB   239K/s 00:07 [#############################################################################] 100%
 community                                                                                              4,4 MiB   230K/s 00:20 [#############################################################################] 100%
 multilib                                                                                             175,3 KiB   240K/s 00:01 [#############################################################################] 100%
 blackarch                                                                                           2032,2 KiB   231K/s 00:09 [#############################################################################] 100%
 blackarch.sig                                                                                        566,0   B  0,00B/s 00:00 [#############################################################################] 100%
error: blackarch: key "7533BAFE69A25079" is unknown
error: key "7533BAFE69A25079" could not be looked up remotely
error: failed to update blackarch (invalid or corrupted database (PGP signature))
 archstrike                                                                                           828,7 KiB   243K/s 00:03 [#############################################################################] 100%
error: database 'blackarch' is not valid (invalid or corrupted database (PGP signature))
```

I already tried : 

```
sudo pacman -Sy archlinux-keyring manjaro-keyring
sudo pacman-key --populate archlinux manjaro
sudo pacman-key --refresh-keys
```

Also removing `\etc\pacman.d\gnupg`, updating repo with `pacman -Syy` and re-initializing the gpg keyrings doesn't change anything. PS : I'm using Manjaro.

**Comment by sipaktli** [comment]
> if irc not possible do this: run: `pacman -Rscn $(pacman -Qtdq) pacman-optimize updatedb sync pkgfile -u pacman -Scc --noconfirm pacman-key --populate`
> then run strap.sh again and perform: pacman -Syyu --needed blackarch --force

Are you serious? What most of that has anything to do with this issue? and "--force"? Never use that.

Just do this:
pacman -Syyu archlinux-keyring blackarch-keyring ; pacman-key --init ; pacman-key --refresh-keys ; pacman-key -u ; pacman-key --populate archlinux blackarch
