### ISSUE TITLE
Issue Installing On Existing Arch

### ISSUE THREAD

**Issue by BryanCuneo** [BlackArch/blackarch#1030]
I'm still unable to install via the Live ISO, so I gave the "install on a preexisting Arch installation" option another try. This time it was a bit more successful. I did, however, run into a bunch of "exists in filesystem" errors with the following packages:

gitrob
kitty
python2-ptp (a dependency of owtf)
ssfr-proxy

I was able to get the rest of the packages to install with the following command:
pacman -S --ignore gitrob,kitty,ssrf-proxy,owtf blackarch

While you can get around it, it's quite inconvenient. I assume this is a packaging error of some kind. If, however, it's an issue on my end, how do I fix it?

**Comment by noptrix** [comment]
use --force: pacman -Syyu --force --needed blackarch
