### ISSUE TITLE
finding the tools...

### ISSUE THREAD

**Issue by Piisawesome** [BlackArch/blackarch#1034]
hello
i have recently tried installing blackarch onto my arch linux system, and everything worked fine.
however i cannot access the blackarch tools from my plasma 5 desktop.
i have also tried using fluxbox, but whenever i try to start fluxbox from my sddm login screen, it would always load plasma, no matter which environment i choose.
so how can i get access to the blackarch tools?
i appreciate your help.

**Comment by devil1995** [comment]
Can u teach me how to install it ...thks...

**Comment by Piisawesome** [comment]
you just do 
$: sudo pacman -S blackarch --force

**Comment by Piisawesome** [comment]
but before you have to do this:
$ curl -O https://blackarch.org/strap.sh 

# The SHA1 sum should match: 86eb4efb68918dbfdd1e22862a48fda20a8145ff 
$ sha1sum strap.sh 

# Set execute bit 
$ chmod +x strap.sh 

# Run strap.sh 
$ sudo ./strap.sh

**Comment by devil1995** [comment]
......

**Comment by devil1995** [comment]
thks......but I steal dear not to setup it ....kali is better to people like me that the tech is not so good ..
