### ISSUE TITLE
Bunny the Fuzzer (DEPRECATED) afl-fuzz

### ISSUE THREAD

**Issue by necrose99** [BlackArch/blackarch#1035]
https://github.com/arisada/afl-fuzz

instrumented C code security fuzzer (DEPRECATED)

Bunny the Fuzzer (DEPRECATED)

IMPORTANT: This project is superseded by American Fuzzy Lop, which performs considerably better and uses a much less complicated approach to instrumenting the fuzzed code. The following content is kept for historical purposes only.

**Comment by noptrix** [comment]
thank you for the hint.
