### ISSUE TITLE
mitmproxy doesn't work with the current python2-h2 release

### ISSUE THREAD

**Issue by bardo** [BlackArch/blackarch#1037]
The `mitmproxy` package depends on the `python2-h2` 2.1.x series, while the currently packaged version is 2.2.1.

By the way, `[community]` contains the very same mitmproxy package at the same version. I don't know BlackArch's policy on duplicated package, anyway it suffers from the same problem: https://bugs.archlinux.org/task/48751

**Comment by noptrix** [comment]
thx for reporting. please message the community since we directly push the community's version.
