### ISSUE TITLE
Can you take care of the beginners ..it is to hard for us to install

### ISSUE THREAD

**Issue by devil1995** [BlackArch/blackarch#1039]
about above ,the black arch is too hard for us beginners to install to the hard disk ...and the guid is not complete........at lease ,you should open the door to the normal as kali do ,so i think that the users of Black Arch will be more..

**Comment by kurobeats** [comment]
What are you having trouble with specifically? Have you had a chat to anyone on the IRC channel?

**Comment by seytz** [comment]
Hum .. The hard part is the ArchLinux installation. Install strap.sh is easy.

**Comment by seytz** [comment]
Hum .. The hard part is the ArchLinux installation. Install strap.sh is easy.

**Comment by seytz** [comment]
Hum .. The hard part is the ArchLinux installation. Install strap.sh is easy.

**Comment by seytz** [comment]
Hum .. The hard part is the ArchLinux installation. Install strap.sh is easy.

**Comment by seytz** [comment]
Hum .. The hard part is the ArchLinux installation. Install strap.sh is easy.

**Comment by seytz** [comment]
Hum .. The hard part is the ArchLinux installation. Install strap.sh is easy.

**Comment by seytz** [comment]
Hum .. The hard part is the ArchLinux installation. Install strap.sh is easy.

**Comment by seytz** [comment]
Hum .. The hard part is the ArchLinux installation. Install strap.sh is easy.

**Comment by ChrisFernandez** [comment]
@seytz  lol how many times did you press enter? :100:  I can try to help you... come to our [hispagatos mattermost chat room](https://chat.binaryfreedom.info/signup_user_complete/?id=ksdnq7dmribjfnnmsjewj7di1r)  we have a few people that that uses arch including myself and I can help you with any questions unofficially since is not a chat related to the project, is our DefCon415 group

**Comment by seytz** [comment]
Wow sorry my qutebrowser is very buggy

**Comment by noptrix** [comment]
@devil1995 please use the new installer. it fixed the well-known issues and you really have nothing to do than pressing enter only.

**Comment by devil1995** [comment]
thanks for the community care my problem so much,and as u know,the China empire not allowe. their citizens connect to many website aboard,so. can somebody just tell the clear steps to install blackarch to my harddisk. ..I. can only use my livecd now...beside, I. can install arch,but. the strap.sh seams have many problems ,I started it for an hour and it really did nothing,so i closed it and  got here last time....is  I should install arch at first?

**Comment by devil1995** [comment]
@ChrisFernandez my email can't recieve the mails from.the site....so. I can't chat.with u...I am.so.sad...beside,my mail is of 163.com,located in China.....

**Comment by devil1995** [comment]
@kurobeats sorry,,I almost can't contact to the irc server....China empire....u know

**Comment by noptrix** [comment]
@devil1995 https://www.blackarch.org/blackarch-install.html
