### ISSUE TITLE
Metasploit Issue

### ISSUE THREAD

**Issue by sparta3407** [BlackArch/blackarch#1042]
hi everyone, i've problems with metasploit , after i do bundle install , nokorgiri -v 1.6.7.2 won't installed!!

**Comment by nil0x42** [comment]
Hi @sparta3407 , nokogiri is actually stupid, and your problem might be the same than the one i encountered past year:
https://github.com/BlackArch/blackarch/issues/875

**Comment by Sirman** [comment]
i've problems with metasploit,  
Gem::RemoteFetcher :: UnknownHostError (https://rubygems.org/gems/rake-10.4.2.gem)
can you help me?

**Comment by Jeeppler** [comment]
I get the following error:

~~~
[user@blackarch ~]$ msfconsole

[!] There was an error parsing `Gemfile`: There was a Errno::ENOENT while loading metasploit-framework.gemspec: 
No such file or directory - git from
  /usr/share/metasploit/metasploit-framework.gemspec:27:in ``'
. Bundler cannot continue.

 #  from /usr/share/metasploit/Gemfile:4
 #  -------------------------------------------
 #  #   spec.add_runtime_dependency '<name>', [<version requirements>]
 >  gemspec name: 'metasploit-framework'
 #  
 #  -------------------------------------------
~~~

**Comment by noptrix** [comment]
what"s up now? Did you guys performed a pacman -Syyu?

**Comment by Jeeppler** [comment]
@noptrix is this fixed or just closed? 

I installed BlackArch on top of an existing Archlinux and than tried to start Metasploit. The packages should have been updated to the newest version at this time.
