### ISSUE TITLE
Cannot run strap.sh for install blackarch tool

### ISSUE THREAD

**Issue by noptx** [BlackArch/blackarch#1047]
i try step in http://blackarch.org/downloads.html
after i run sudo ./strap.sh appear:
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
Anyone can solved this problem?

**Comment by ironlota** [comment]
yes, i had the same problem. i think this pgp key (4345771566D76038C7FEB43863EC0ADBEA87E4E3) is invalid

**Comment by noptx** [comment]
so,we have a same problem too xD

**Comment by noptx** [comment]
What is function for pgp key?it is importantm

**Comment by noptrix** [comment]
run strap.sh with sudo sh -x strap.sh and paste the whole output here

**Comment by noptx** [comment]
On Sat, Apr 30, 2016 at 4:12 AM, noptrix <notifications@github.com> wrote:

> run strap.sh with sudo sh -x strap.sh and paste the whole output here
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BlackArch/blackarch/issues/1047#issuecomment-215883062>
>

[1m[32m[+] installing blackarch keyring...(B[m

**Comment by noptrix** [comment]
?

**Comment by noptx** [comment]
+ MIRROR=http://www.mirrorservice.org/sites/blackarch.org/blackarch/
+ blackarch_setup
+ check_priv
+ '[' 0 -ne 0 ']'
+ msg 'installing blackarch keyring...'
++ tput bold
++ tput setaf 2
++ tput sgr0
+ echo '[+] installing blackarch keyring...'
[+] installing blackarch keyring...
+ make_tmp_dir
++ mktemp -d /tmp/blackarch_strap.XXXXXXXX
+ tmp=/tmp/blackarch_strap.Asd0wmn0
+ trap 'rm -rf /tmp/blackarch_strap.Asd0wmn0' EXIT
+ cd /tmp/blackarch_strap.Asd0wmn0
+ fetch_keyring
+ curl -s -O 'http://blackarch.org/keyring/blackarch-keyring.pkg.tar.xz{,.sig}'
+ verify_keyring
+ gpg --keyserver hkp://pgp.mit.edu --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3
+ gpg --keyserver-options no-auto-key-retrieve --with-fingerprint blackarch-keyring.pkg.tar.xz.sig
+ err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
++ tput bold
++ tput setaf 1
++ tput sgr0
+ echo '[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch'
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
+ exit 1337
+ rm -rf /tmp/blackarch_strap.Asd0wmn0

**Comment by noptx** [comment]
- MIRROR=http://www.mirrorservice.org/sites/blackarch.org/blackarch/
   - blackarch_setup
   - check_priv
   - '[' 0 -ne 0 ']'
   - msg 'installing blackarch keyring...' ++ tput bold ++ tput setaf 2 ++
   tput sgr0
   - echo '[+] installing blackarch keyring...' [+] installing blackarch
   keyring...
   - make_tmp_dir ++ mktemp -d /tmp/blackarch_strap.XXXXXXXX
   - tmp=/tmp/blackarch_strap.Asd0wmn0
   - trap 'rm -rf /tmp/blackarch_strap.Asd0wmn0' EXIT
   - cd /tmp/blackarch_strap.Asd0wmn0
   - fetch_keyring
   - curl -s -O '
   http://blackarch.org/keyring/blackarch-keyring.pkg.tar.xz{,.sig}'
   - verify_keyring
   - gpg --keyserver hkp://pgp.mit.edu --recv-keys
   4345771566D76038C7FEB43863EC0ADBEA87E4E3
   - gpg --keyserver-options no-auto-key-retrieve --with-fingerprint
   blackarch-keyring.pkg.tar.xz.sig
   - err 'invalid keyring signature. please stop by
   irc.freenode.net/blackarch' ++ tput bold ++ tput setaf 1 ++ tput sgr0
   - echo '[-] ERROR: invalid keyring signature. please stop by
   irc.freenode.net/blackarch' [-] ERROR: invalid keyring signature. please
   stop by irc.freenode.net/blackarch
   - exit 1337
   - rm -rf /tmp/blackarch_strap.Asd0wmn0

**Comment by hack-er** [comment]
change `- gpg --keyserver hkp://pgp.mit.edu --recv-keys`
to 
`- gpg --keyserver http://pgp.mit.edu --recv-keys`

did this today, and it's working now.

**Comment by noptx** [comment]
ok this is work for instal blackarch tools,thanks.
Closed

**Comment by noptrix** [comment]
thx @hack-er

**Comment by noptx** [comment]
thanks to @hack-er

**Comment by aremai** [comment]
Hi,
unfortunately this didn't fix it for me :(

I still run into this problem...please see the below output:

`+ MIRROR=http://www.mirrorservice.org/sites/blackarch.org/blackarch/
+ blackarch_setup
+ check_priv
+ '[' 0 -ne 0 ']'
+ msg 'installing blackarch keyring...'
++ tput bold
++ tput setaf 2
++ tput sgr0
+ echo '[+] installing blackarch keyring...'
[+] installing blackarch keyring...
+ make_tmp_dir
++ mktemp -d /tmp/blackarch_strap.XXXXXXXX
+ tmp=/tmp/blackarch_strap.AkqE9bDI
+ trap 'rm -rf /tmp/blackarch_strap.AkqE9bDI' EXIT
+ cd /tmp/blackarch_strap.AkqE9bDI
+ fetch_keyring
+ curl -s -O 'http://blackarch.org/keyring/blackarch-keyring.pkg.tar.xz{,.sig}'
+ verify_keyring
+ gpg --keyserver http://pgp.mit.edu --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3
+ gpg --keyserver-options no-auto-key-retrieve --with-fingerprint blackarch-keyring.pkg.tar.xz.sig
+ err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
++ tput bold
++ tput setaf 1
++ tput sgr0
+ echo '[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch'
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
+ exit 1337
+ rm -rf /tmp/blackarch_strap.AkqE9bDI
`

**Comment by pe3t77e3r** [comment]
I tryed to install Blackarch on top of Arch Linux and had the same issue. After i set the $GNUPGHOME Variable to /home/.../.gnupg/ in one of my startupfiles: /home/.../.bashrc, it worked

**Comment by aremai** [comment]
thanks @pe3t77e3r !!! this worked like a charm, i've been looking for months to get this working! 
this fixed it for me too :) :+1:

**Comment by scrigoose** [comment]
Worked for me as well. I'm just not sure if putting this to .bashrc (or other _rc_ file, depending on the shell you use) is necessary.
Just
```
export  $GNUPGHOME=/home/<user>/.gnupg/
```
for installation time should be enough (unless you have a different config location for [GnuPG](https://wiki.archlinux.org/index.php/GnuPG#Configuration))
Remember also about -E switch for _sudo_ to preserve this environment variable.

**Comment by Zhidomasson** [comment]
It doesn't work for me. Any ideas, please?

**Comment by BornioP** [comment]
It is not working for me. I am using a updated fresh instal of Manjaro KDE Edition (17.0.1)
I manualy searched http://pgp.mit.edu for the keys ant they are not there. Am I missing something?
`
# verify the keyring signature
# note: this is pointless if you do not verify the key fingerprint
verify_keyring()
{
    gpg \
        --keyserver http://pgp.mit.edu \
        --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3 > /dev/null 2>&1

    if ! gpg \
        --keyserver-options no-auto-key-retrieve \
        --with-fingerprint blackarch-keyring.pkg.tar.xz.sig > /dev/null 2>&1
    then
        err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
    fi
}
`

**Comment by BruceLEO1969** [comment]
Just delete the line:

> --keyserver http://pgp.mit.edu \

everything goes OK.

**Comment by LucasEsposito** [comment]
I'm trying to install blackarch on manjaro too.

I changed gpg --keyserver http://pgp.mit.edu --recv-keys
to - gpg --keyserver hkp://pgp.mit.edu --recv-keys

And it worked!
I changed http to hkp instead of hkp to http as was said in previous comments.

**Comment by PedroSFreitas** [comment]
The issue was already addressed in another Pull Request, a new `strap.sh` will be replaced soon fixing this issue.
Any discussion, issues, or suggestion should be posted in https://github.com/BlackArch/blackarch-site/pull/72

@noptrix I'd suggest locking the conversation to avoid bumping dead threads.

**Comment by klebertiko** [comment]
I just changed:

verify_keyring()
{
    gpg \
        --keyserver pgp.mit.edu \
        --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3 > /dev/null 2>&1

    if ! gpg \
        --keyserver-options no-auto-key-retrieve \
        --with-fingerprint blackarch-keyring.pkg.tar.xz.sig > /dev/null 2>&1
    then
        err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
    fi
}

To:

verify_keyring()
{
    gpg \
        --keyserver https://pgp.mit.edu \
        --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3 > /dev/null 2>&1

    if ! gpg \
        --keyserver-options no-auto-key-retrieve \
        --with-fingerprint blackarch-keyring.pkg.tar.xz.sig > /dev/null 2>&1
    then
        err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
    fi
}

**Comment by KiritoAsuna7** [comment]
I am also getting the same error. How do I solve it ?

**Comment by PedroSFreitas** [comment]
@KiritoAsuna7 
https://blackarch.org/faq.html "Why do I get invalid keyring signature?"

**Comment by KiritoAsuna7** [comment]
Yh ! I tried everything. It is not working.

**Comment by ThinkerQAQ** [comment]
I solve it just set a proxy and run this sh again!!!!
such as:
export http_proxy=your proxy server
export https_proxy=your proxy server

**Comment by AwaisAfzal1** [comment]
will any one help me how to resolve 
ERROR: keyring installation failed
in ubuntu
please

**Comment by AwaisAfzal1** [comment]
> change `- gpg --keyserver hkp://pgp.mit.edu --recv-keys`
> to
> `- gpg --keyserver http://pgp.mit.edu --recv-keys`
> 
> did this today, and it's working now.

will you guide me how to change gpg server

**Comment by ikstream** [comment]
strap.sh is intended to be used on arch linux systems and will not work on ubuntu.
