### ISSUE TITLE
any plan to release vagrant box?

### ISSUE THREAD

**Issue by naijim** [BlackArch/blackarch#1055]

**Comment by noptrix** [comment]
no, not yet.

**Comment by aurelien-git** [comment]
You can get it from AUR https://aur.archlinux.org/packages/?O=0&K=vagrant

**Comment by Sliim** [comment]
:+1:
If there is a vagrant box available I will be happy to add it in https://github.com/Sliim/pentest-env :)
Otherwise I can create one.
@aurelien-git your link is to search for vagrant keywork on AUR repos right?

**Comment by aurelien-git** [comment]
@Sliim right because it offer you a git version, a layer, and otto-bin https://aur.archlinux.org/packages/otto-bin/ which is considered as its successor!
