### ISSUE TITLE
blackarch site is down or very very slow

### ISSUE THREAD

**Issue by cybernet** [BlackArch/blackarch#1057]
blackarch site is down or very very slow

probably due to latest release

**Comment by noptrix** [comment]
up and running

**Comment by ShalokShalom** [comment]
Same happens to me now, as i got redirected from another page. I loaded for 10 minutes, no success.

**Comment by ikstream** [comment]
https://blackarch.org/ appears up and running with no delay to me.

**Comment by ShalokShalom** [comment]
Yeah, to me then as well.
