### ISSUE TITLE
GPG key invalid

### ISSUE THREAD

**Issue by Dawnflash** [BlackArch/blackarch#1059]
It seems that a key here became invalid and pacman can't proceed as a result. Maybe remove the key for the time being. The only viable client solution is disabling key checking in pacman.conf. Not exactly a secure solution.

pacman debug print:
key: F9A6E68A711354D84A9B91637533BAFE69A25079, Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>, owner_trust unknown, disabled 0
signature is not valid

**Comment by noptrix** [comment]
23:48:20 <@noptrix> rm -rf /etc/pacman.d/gnupg && curl -s -O https://blackarch.org/strap.sh && 
                    chmod a+x strap.sh && sudo ./strap.sh
23:48:22 <@noptrix> then:
23:48:27 <@noptrix> pacman -Scc ; pacman -Syyu
23:48:31 <@noptrix> that's it
23:48:50 <@noptrix> but it can be that the mirror is not up-to-date so you better switch to 
                    the mainsite temporary

**Comment by Dawnflash** [comment]
The refreshing doesn't help, I'll just temporarily disable key verification for blackarch.

**Comment by noptrix** [comment]
can you switch to blackarch.org main site in your pacman.conf and simply pacman -Scc and then pacman -Syyu?

**Comment by Dawnflash** [comment]
Perfect, it must be an out-of-date mirror then. Cheers!

**Comment by noptrix** [comment]
yeah. well the mirror you have: they sync every 4 or 6hours.
