### ISSUE TITLE
Install completely borked

### ISSUE THREAD

**Issue by GreyRabbit2** [BlackArch/blackarch#1062]
I'm new to Arch but not new to kali. 
I'm currently trying to install BA on Oracle. There are 0 tuts out there on how to install with the new installer. Following the tuts for using the old installer break many things. 
I really do appreciate people putting time into OS's for linux, mad creds to linux devs. However if users have no idea how to install the OS then what good does it do?
This is one tutorial I tried using:
https://404.zone/2015/02/installing-blackarch-from-the-live-iso-in-virtualbox/
this is another:
https://www.youtube.com/watch?v=YW0Fqm81EAw

both failed and I'm staring at a booting screen:

Booting...
_

I'd love to be able to use this for work and to have another os other than kali but until there is a clear way on how to install it I'm stuck with kali. 

The only instructions on the main site stop after 
`sudo pacman -S blackarch - installer`
and then
`sudo blackarch-install`

**Comment by sahakkhotsanyan** [comment]
try to remove and reinstall 
# Install blackarch-install-scripts package
$ sudo pacman -S blackarch-install-scripts
# Now, you can run and follow the instructions
$ sudo blackarch-install

thank you!

**Comment by ainsophical** [comment]
> However if users have no idea how to install the OS then what good does it do?

i think the general consensus is that if you cant install the os, you probably shouldnt be using it. there is nothing too difficult in the install that a pen-tester shouldnt be able to figure out him/herself on the fly.

**Comment by noptrix** [comment]
install using the new installer: blackarch-installer. also you can use this tutorial now: https://www.blackarch.org/blackarch-install.html
