### ISSUE TITLE
Install on top of arch through unofficial user repository for armv7 errors

### ISSUE THREAD

**Issue by Simbaclaws** [BlackArch/blackarch#1063]
So basically I'm getting a lot of errors when trying to install the armv7 packages of blackarch through pacman (using option 2). My errors shows things like /usr/sbin already exists in filesystem.

I can't transfer the pacman.log file from my phone right now but I'll post it here as soon as I can.

Can I ignore the errors and continue with --force and --needed in pacman? Or is it because of broken packages and I shouldn't force the installation?

I'm installing blackarch on my android phone through linux deploy and vnc viewer.

**Comment by noptrix** [comment]
yes, --force and --needed

**Comment by Simbaclaws** [comment]
thanks, it seems to be going through with the installation. I think this issue can be set to solved.
