### ISSUE TITLE
New Tool

### ISSUE THREAD

**Issue by sahakkhotsanyan** [BlackArch/blackarch#1065]
A new admin finder tool... with good results,please add it to blackarch!
https://github.com/sahakkhotsanyan/adfind
for questions email me with this address sahakjab@gmail.com

**Comment by noptrix** [comment]
barev sahak...
thank you, we will add it.

**Comment by sahakkhotsanyan** [comment]
Noptrix?? Հայ ես Ապէ՞

**Comment by noptrix** [comment]
ha, hay em :)

**Comment by sahakkhotsanyan** [comment]
pastoren hayeric el kan blackarchi mej :) dzec axpers... tenc sharunaki :) vonc gtnem qez ba? fb mb ka?

**Comment by sahakkhotsanyan** [comment]
lav ba erb kavelacneq?

**Comment by noptrix** [comment]
es kes im jabbern em talis... im hayeren lav chgitem. ari angleren xosang.

**Comment by noptrix** [comment]
indz email gri es qes jabbern ktam

**Comment by sahakkhotsanyan** [comment]
ok!

**Comment by sahakkhotsanyan** [comment]
noptrix when i update my programm in git,is it updates in blackarch?

**Comment by noptrix** [comment]
no, as i said it's getting updated frequently from our side. every week or few days.
