### ISSUE TITLE
metasploit error message

### ISSUE THREAD

**Issue by c0r3dump3d** [BlackArch/blackarch#1067]
Hi, I have installed metasploit with pacman -S metasploit. All it's seem working but I have this error when I launch the msfconsole command:

fatal: Not a git repository (or any of the parent directories): .git

**Comment by sahakkhotsanyan** [comment]
it's error of not BlackArch! It's error of Metasploit

**Comment by noptrix** [comment]
hey, we can close this issue: we have separated the metasploit package in two packages: **metasploit** and **metasploit-msfupdate**. The latter one can be used to update (git pull) via msfupdate. Therefore we've removed the .git/ directory in the default 'metasploit' package. So either ignore the 'error' message or install **metasploit-msfupdate**.

**Comment by ChrisFernandez** [comment]
@noptrix actually this brings up a question, I did notice this package split, good idea btw, now my question is if you need to install both? I notice the msfupdate package is big.. so prob not? thanks!

**Comment by noptrix** [comment]
no need to use msfupdate as we frequently update metasploit at least once per week. if you can't stay with this install otherwise we don't recommend :)

**Comment by ChrisFernandez** [comment]
@noptrix thanks for the clarification, I appreciate it.

**Comment by noptrix** [comment]
@ChrisFernandez no problem, you are welcome

**Comment by c0r3dump3d** [comment]
Ok thank you very much for the information.
