### ISSUE TITLE
perl-io-socket mismatch after perl update (IO.c)

### ISSUE THREAD

**Issue by jnbrains** [BlackArch/blackarch#1072]
Hello everybody,

  I have arch box with blackarch repository enabled, with most of the packages 
installed. After updating to perl version to 5.24.0, I started getting:

`IO.c: loadable library and perl binaries are mismatched...`

unable to build software (automake complained due to the issue).

  A bit research revealed it's due to restructuring in the new perl version, some
(if not most) perl modules needs to be rebuild against the new version to start
working again. I did that, but it didn't solve the issue entirely - kept receiving the
errors.

 This is my workaround for the problem (got the list from pacman -Ql perl-io-socket):
```
mv /usr/lib/perl5/vendor_perl/IO.pm /usr/lib/perl5/vendor_perl/IO.pm.0
mv /usr/lib/perl5/vendor_perl/IO /usr/lib/perl5/vendor_perl/IO.0
mv /usr/lib/perl5/vendor_perl/auto/IO /usr/lib/perl5/vendor_perl/auto/IO.0

```
as I couldn't just remove the perl-io-socket package due to the large 
dependancies list.

Cheers,
JNB

**Comment by null0x0** [comment]
the latest perl-io-socket version 1.36_01-1 already solved the issue.
