### ISSUE TITLE
Black Arch Install problem

### ISSUE THREAD

**Issue by MichalGyurkovsky** [BlackArch/blackarch#1073]
Hello community,
I am having issues installing Black Arch to laptop and PC. Everytime I boot up to Live ISO then run pacman -Sy; pacman -S blackarch-install-scripts and then blackarch-install and follow every step. Everything seems to be OK no error but when installation ends and I reboot PC/Laptop nothing boots up. I ve tryed many diferent steps via youtube and wiki but nothing helped me yet. Thanks for response

**Comment by noptrix** [comment]
please use the new installer: pacman -S 'blackarch-installer' and not the old one: 'blackarch-install-scripts'.

**Comment by MichalGyurkovsky** [comment]
will try it then I will write if I suceed or not :) thank you for response

**Comment by noptrix** [comment]
ok. just make sure to choose DOS as MBR partition. if you go with GPT then make sure to have a separate partition for that. and you will need to format/choose 'fat32' during the installation. many ppl don't know that and make a mistake here. we will update the code somehow to tell 'unix-beginners' how to deal with this situation

**Comment by MichalGyurkovsky** [comment]
Oh maybe thats the problem since I always choose GPT format then made partitions and formated them as ext4 ! Thanks going to try it :)

**Comment by MichalGyurkovsky** [comment]
So if Iam not misstaken with DOS partition I can make ext4 format and with GPT i can make only Fat32? :)

**Comment by noptrix** [comment]
correct. but also make sure to choose as partition type "Efi 64 ..." something like that in cfdisk when you  use 'type'.

**Comment by MichalGyurkovsky** [comment]
Okey :) will try to install on pc aswell on laptop to compare errors

**Comment by MichalGyurkovsky** [comment]
Okey I made it up now Arch is booting but GUI isnt show up its just Console said "blackarchlinux login :"
and after I log in nothing happens , any way to fix it?

**Comment by Technohacker** [comment]
Just trying to help
If blackarch is loaded using grub, try modifying the boot commandline and replace init=/sbin/init with /bin/bash to reach a recovery root shell :)

**Comment by noptrix** [comment]
@MichalGyurkovsky btw, there is a new quick-guide for installation, you can find it here: https://www.blackarch.org/blackarch-install.html

**Comment by mackzwell123** [comment]
please help me this is what happen when I start installing Black arch linux

Probing EDD (edd=off to disable). . . ok
: : running early hook [udev]
starting version 232
: : triggering uevents . . .
: : running hook [memdisk]
: : running hook [archiso]
: : running hook [archiso_loop_mnt]
: : running hook [archiso_pxe_common]
: : running hook [arhciso_pxe_nbd]
: : running hook [arhciso_pxe_http]
: : running hook [arhciso_pxe_nfs]
: : mounting '/dev/disk/by-label/BLACKARCH_2' to ' /run/archiso/bootmnt'
: : Device '/dev/disk/by-Label/BLACKARCH_2' mounted successfully.
: : Mounting '/dev/loop0' to '/run/archiso/sfs/airootfs'
mount: wrong fs type, bad opting, bad superblock on /dev/loop0,
            missing codepage or helper program, or order error

            In some cases useful info is found is syslog- try
            dmesg | tail or so.
ERROR; Failed to mount '/dev/loop0'
       Falling back to interactive prompt
       You can try to fix the probelm manually, log out when you are finished
sh: can't access tty; jon control turned off
[root fs   ]

**Comment by redcorpshell** [comment]
mackzwell123,same here bro..it shows when i boot up live usb after writing usb bootable using poweriso in Ram Write method!!

**Comment by laymon92** [comment]
please help me please

Failed to write disk label

**Comment by ikstream** [comment]
@laymon92 please open a new issue with your problem and provide some more information like what did you try to do, which iso did you use, is there anything special about your system, are there any errors or failed messages before.

**Comment by Clow3nSec** [comment]
Everytime i install it using live iso its successful i also use dos for partitioning but when i reboot nothing is there

**Comment by ikstream** [comment]
Please open a new issue, describing your problem and providing information like install decision you made (encrypted etc.), Installer version etc.
Did you update the installer before the process?
