### ISSUE TITLE
Using Rufus 2.9 Portable to burn ISO to USB.

### ISSUE THREAD

**Issue by a-Qbyte** [BlackArch/blackarch#1075]
Hello Everyone, 

I was wondering if Rufus 2.9 Portable would properly burn the ISO to my USB?

Any assistance will greatly be appreciated!

Thanks

EDIT: Here is their website for further information --->  http://rufus.akeo.ie/

**Comment by a-Qbyte** [comment]
I used Rufus 2.9 Portable to burn the ISO to my USB, and it has worked fine.

**Comment by averyfreeman** [comment]
Rufus 3.0 defaulted to NTFS when I opened the BlackArch ISO, which seems obviously wrong.  I'm trying with Fat32 (the only other option) which I think should work fine.

**Comment by noraj** [comment]
@averyfreeman Don't use rufus, use SUSE Image Writer or use `dð`. You can refer to https://wiki.archlinux.org/index.php/USB_flash_installation_media
