### ISSUE TITLE
crackmapexec: deprecated PKGBUILD

### ISSUE THREAD

**Issue by nil0x42** [BlackArch/blackarch#1076]
### Issue
```$ crackmapexec```
```
python2: can't open file 'crackmapexec.py': [Errno 2] No such file or directory
```

#### 1 - Two dependencies are missing in the PKGBUILD (according to package's setup.py):
```
python2-pyopenssl
python2-requests
```

#### 2 - The launcher is completely deprecated:
As the package has been developped to be installed via setup.py,
we still can simulate same behavior by launching it with:
```
exec python2 -c "import cme.crackmapexec; cme.crackmapexec.main()"
```

**Comment by noptrix** [comment]
thx, will be fixed
