### ISSUE TITLE
Kernel Modules Failing To Load

### ISSUE THREAD

**Issue by a-Qbyte** [BlackArch/blackarch#1080]
I cannot use my track pad on my laptop, however the touchscreen still works(?). What could be the cause of this. 

Any help will greatly be appreciated. 

I'm attempting to boot using a live iso with usb.

**Comment by ChrisFernandez** [comment]
Curious enough I'm having the same/similar issue, never had that problem with blackarch before, but I got a new laptop today and first time I used the new installer... the live cd did not detect my touchpad at all such is ok I don't need it.. managed to open a window and do the install, after that I reboot boot into blackarch fluxbox and touchpad works but is not working right.. not sure how to explain in English but is like mapped to the screen if I click on left botton mouse pointer appears on left botton of the screen so can't really move windows around etc..  This is a **Lenovo X1 Carbon.**

**Comment by noptrix** [comment]
@a-Qbyte please use: synclient TouchpadOff=0 and let me know if it works
