### ISSUE TITLE
Unable to boot blackarch-netinst.iso from usb

### ISSUE THREAD

**Issue by cneud** [BlackArch/blackarch#1081]
Having more or less the same issue here as #990 - I am trying to install blackarch x86 from usb-stick, using the `blackarchlinux-netinst-2016.04.28-i686.iso`. Steps I took:
1. Format usb-stick as FAT
   `mkfs.vfat /dev/sdb1`
2. Write iso to usb
   `dd bs=512M if=blackarchlinux-netinst-2016.04.28-i686.iso of=/dev/sdb status=progress && sync`
3. Change BIOS boot order to boot from USB

The target installation system is an Asus EEE PC (32-bit, no UEFI). The usb will not boot, instead after a few seconds, my OpenBSD is booted from HDD. The usb is labelled "BLACKARCH_201604" and contains 4 directories: `blackarch`, `EFI`, `isolinux`, `loader`.

**Comment by dg7abl** [comment]
And another mistake to Boot the Live CD from USB 

"Failed to load  ldlinux.c32"

**Comment by cneud** [comment]
Got the usb to boot now, but booting the first menu entry to start BlackArch install fails with
`Loading boot/i686/vmlinuz... failed: No such file or directory`

**Comment by heichblatt** [comment]
Are you still getting the same error with the [current ISOs](https://blackarch.org/downloads.html)? Also, the `mkfs.vfat` should not be necessary.

**Comment by cneud** [comment]
Thx for following up! Meanwhile I have reverted to just using vanilla Arch though, which installed flawless on the EEE. But I will try the current BlackArch ISOs over the weekend and report back here.

**Comment by sunilolo** [comment]
I use to have the same problem - boot blackarch.iso from usb --   and i try Rufus  utility and its  work now .. 
Rufus  utility >> https://rufus.akeo.ie/?locale=en_US 
i choose this one Rufus 2.11 (916 KB)
The utility will ask to download  --  ldlinux.sys -- and  -- ldlinux.bss -- and it will do it Automatically
and i use this Image
http://www.mirrorservice.org/sites/blackarch.org/blackarch/iso/blackarchlinux-live-2016.08.31-x86_64.iso
  And this one too
http://www.mirrorservice.org/sites/blackarch.org/blackarch/iso/blackarchlinux-netinst-2016.08.31-i686.iso
the user name is : root  and the password is : blackarch
Goodluck

**Comment by shellfire32** [comment]
Try adding the bootable flag to your USB drive
