### ISSUE TITLE
BlackArch tools on Kali Linux

### ISSUE THREAD

**Issue by PerryMok** [BlackArch/blackarch#1084]
Dear Sir/Madam,

I am quite interested in the tools of BlackArch Linux. However, I don't want to install the third OS. I want to install BlackArch Linux tools on Kali Linux, is there any ways?

Thank you for reading this question, I hope I will get answers from you soon!

User

**Comment by ChrisFernandez** [comment]
why will you want to do that? kali has the same tools and the ones missing will be 1000 times easier to just compile yourself on kali or create your own debian packages.. is it possible to port blarckarch tools? technically yes, but is it worth all the trouble? no. Learn Linux nost just kali and you will figure out why what you asking is silly.

**Comment by Anyon3** [comment]
The answer of Chris is right, nothing to add.

Eventually you could use virtualbox in your kali system for blackarch.

**Comment by lllBarcodeslll** [comment]
I add IN repos AUR arch linux work tell my if you have idea for adding black arch tool option
