### ISSUE TITLE
Suggestion: Alternative GSA Theme

### ISSUE THREAD

**Issue by kurobeats** [BlackArch/blackarch#1086]
I totally reckon we should use this as the default openvas theme https://github.com/domarques/gsa-domarques-theme

I'm running it and it's flawless

**Comment by ChrisFernandez** [comment]
looks cool, we could always change the colors to red/black to match blackarch :+1:

**Comment by heichblatt** [comment]
Hello @kurobeats,

while the mentioned theme is indeed quiet nice and would fit into our overall colour scheme, I guess the Arch Linux [principle of simplicity](https://wiki.archlinux.org/index.php/Arch_Linux#Simplicity) takes precedence here:

> Arch Linux defines simplicity as without unnecessary additions or modifications. It ships software as released by the original developers (upstream) with minimal distribution-specific (downstream) changes: patches not accepted by upstream are avoided,

That said, I encourage you to contribute a PKGBUILD for the theme, that way it would be only a `yaourt -S ...` away. :)

Cheers,
heichblatt
