### ISSUE TITLE
Please update packages guys

### ISSUE THREAD

**Issue by ItsBananaPie** [BlackArch/blackarch#1096]
warning: package-query: local (1.8-2) is newer than blackarch (1.8-1)
warning: yaourt: local (1.8.1-1) is newer than blackarch (1.8-1)
Thank you!

**Comment by noptrix** [comment]
you used the packages from AUR rather than from the blackarch repository. the software versios itself are not outdated.

**Comment by noptrix** [comment]
they have just different pkgrel versions (internal thing) nothing to do with the softwar.e so either remove them and install again via blackarch or ignore th ewarnings.
