### ISSUE TITLE
cannot connect to net

### ISSUE THREAD

**Issue by kuja2** [BlackArch/blackarch#1106]
please i need to set up eth0 with blackarch , i cannot use net it only shows wlan0 and not eth0 i tried to follow arch form solve but not working please i need solve about this

**Comment by heichblatt** [comment]
Hi @kuja2,

can you get the interface to work with other Linux distros (e.g. Arch)?
Also, please post the output of `lspci` and `lsusb`.

Cheers.

**Comment by heichblatt** [comment]
I guess we can close this one.
