### ISSUE TITLE
[Tool request] angr-management

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#1109]
https://github.com/angr/angr-management

**Comment by noptrix** [comment]
thx will be added

**Comment by PedroSFreitas** [comment]
**I've tried.**
Not sure what is going on here, maybe it's something (issue) on upstream.

![image](https://user-images.githubusercontent.com/12863160/29795754-f955e294-8c23-11e7-9a74-930a9b39bfd7.png)

![image](https://user-images.githubusercontent.com/12863160/29795768-0cfeb94c-8c24-11e7-97f9-58c38fb976ad.png)

**Comment by noptrix** [comment]
added and fixed.
