### ISSUE TITLE
sha1sum not match

### ISSUE THREAD

**Issue by All3xJ** [BlackArch/blackarch#1120]
the sha1sum of strap.sh in your site is: 86eb4efb68918dbfdd1e22862a48fda20a8145ff
but after downloading in my pc, it is c7012b890bb6043a2b39ca749cf0dbb9daac606c

**Comment by noptrix** [comment]
thx for reporting. the sha1sum of the file is correct, though. we will update the website.

**Comment by noptrix** [comment]
done
