### ISSUE TITLE
bettercap doesn't start

### ISSUE THREAD

**Issue by All3xJ** [BlackArch/blackarch#1121]
I advice you to put ettercap in dependencies of bettercap. In fact, I've installed bettercap and once I opened it, it raises an error. But after I've installed ettercap, bettercap opens.

**Comment by noptrix** [comment]
can you please simply reinstall bettercap?

**Comment by noptrix** [comment]
it doesn't have the deps of ettercap at all. all is handled via rubygems btw. please let us know if it works after a reinstall.
