### ISSUE TITLE
strap.sh creates "pacman.confe" without any notification

### ISSUE THREAD

**Issue by hexcat** [BlackArch/blackarch#1126]
If you install BlackArch with strap.sh, you end up having "pacman.confe" besides usual "pacman.conf". The file is created with "update_pacman_conf()" procedure by sed utility:
```
# delete blackarch related entries if existing
sed -ie '/blackarch/{N;d}' /etc/pacman.conf
```

Shouldn't we have a note about it in terminal or in instructions on how to install?

**Comment by heichblatt** [comment]
Hi @hexcat ,

strap.sh is part of the [BlackArch/blackarch-site](https://github.com/BlackArch/blackarch-site) repo. I've created a PR with a fix [there](https://github.com/BlackArch/blackarch-site/pull/35).

Cheers.

**Comment by hexcat** [comment]
I see. Thanks!
