### ISSUE TITLE
BlackArch VMware Tools

### ISSUE THREAD

**Issue by cyrus104** [BlackArch/blackarch#1128]
I tried to follow the Arch VMware Tools instructions and for some reason on BlackArch they did not work. Everything looked like it completed properly and when I rebooted nothing changed, tried to start the service manually, they looked to start but video resolution and other tools did not work.

**Comment by noptrix** [comment]
have you installed arch linux and added our repository on top of it or did you install blackarch via an ISO? also, have you loaded the modules correctly?

**Comment by cyrus104** [comment]
I did the install via a blackarch iso reaching out to the repository. I thought I had loaded the modules correct, they work on my other arch install but I'm not going to use that one for blackarch.

**Comment by heichblatt** [comment]
Are you having this problem?
