### ISSUE TITLE
New repo: blackarch-images

### ISSUE THREAD

**Issue by heichblatt** [BlackArch/blackarch#1132]
Hello all,

@noptrix and I already talked about this on IRC. To keep the Docker ([and maybe VDI/VMDK/...](https://github.com/BlackArch/blackarch/issues/1124)) separate from the main repo, a separate `blackarch-images` would be preferable.
If you think so, too, please create one. I'll migrate the first scripts myself. I suggest the following structure:

    root
    ├── docker
    │   ├── README
    │   ├── build.sh
    │   └── Dockerfile
    ├── packer
    │   ├── vagrant
    │   │   ├── README
    │   │   ├── build.sh
    │   │   ├── template.json
    │   │   └── ...
    │   ├── vdi
    │   │   ├── README
    │   │   ├── build.sh
    │   │   ├── template.json
    │   │   └── ...
    │   ├── vmdk
    │   │   ├── README
    │   │   ├── build.sh
    │   │   ├── template.json
    │   │   └── ...
    ...

Cheers.

**Comment by noptrix** [comment]
aight. will create the repo. thanks a lot for your job.

**Comment by noptrix** [comment]
I've created this: https://github.com/BlackArch/blackarch-virtualization There we can have qemu/ virtualbox/ docker/ etc.
