### ISSUE TITLE
gef dependency issues

### ISSUE THREAD

**Issue by kurobeats** [BlackArch/blackarch#1133]
» gdb
gef loaded, 'gef help' to start, 'gef config' to configure
31 commands loaded (21 sub-commands), using Python engine 3.5
[] 6 commands could not be loaded, run 'gef missing' to know why.
gef➤  gef missing
[] Command 'assemble' is missing, reason  →  'Missing Python 'keystone' package. '
[] Command 'set-permission' is missing, reason  →  'Missing Python 'keystone-engine' package. '
[] Command 'unicorn-emulate' is missing, reason  →  'This command requires the following packages: 'unicorn' and 'capstone'.'
[] Command 'retdec' is missing, reason  →  'Missing Python 'retdec-python' package. '
[] Command 'ropgadget' is missing, reason  →  'Missing Python 'ropgadget' package. '
[] Command 'ropper' is missing, reason  →  'Missing Python 'ropper' package.

**Comment by noptrix** [comment]
thx, will be fixed.

**Comment by noptrix** [comment]
should be fixed now. if not, reopen this issue, please

**Comment by kurobeats** [comment]
hey, looks like we have one left:

36 commands loaded (21 sub-commands), using Python engine 3.5
[] 1 commands could not be loaded, run 'gef missing' to know why.
gef➤  gef missing
[] Command 'unicorn-emulate' is missing, reason  →  'This command requires the following packages: 'unicorn' and 'capstone'.'
