### ISSUE TITLE
trinity  sig-key error

### ISSUE THREAD

**Issue by pencil3mark** [BlackArch/blackarch#1139]
when i upgrade my arch by :pacman -Syu
i get an error with trinity
            invalid or corrupted package (PGP signature)
i try ：pacman-key  --refresh-key
but nothing  worked.

**Comment by dfstorm** [comment]
Same here. More details:

blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid

**Comment by ChrisFernandez** [comment]
same here

**Comment by noptrix** [comment]
guys, which mirror do you use? also did you perform a clean: pacman -Scc and -Syyu afterwards?

**Comment by ChrisFernandez** [comment]
@noptrix let me try to run that.

**Comment by ChrisFernandez** [comment]
@noptrix that seems to work.. thank you. <3

**Comment by noptrix** [comment]
yup. you guys probably worked with your cache ;)
