### ISSUE TITLE
Failed blackman -a on archlinux

### ISSUE THREAD

**Issue by brianezequielfiszman** [BlackArch/blackarch#1145]
This is the error I get:
CRITICAL: Package not found in repository 'blackarch-keyring.install'

**Comment by heichblatt** [comment]
Hi @brianezequielfiszman,

please post the output of `bash -x blackman -a`.

Cheers

**Comment by noptrix** [comment]
@brianezequielfiszman can you please post a the output of what @heichblatt said? and createa new issue on BlackArch/blackman/ rather than here. i will close this issue
