### ISSUE TITLE
waidps startup IOerror

### ISSUE THREAD

**Issue by samtech09** [BlackArch/blackarch#1147]
waidps is giving following error

[i]   File Not found in /.SYWorks/WAIDPS/waidps
[i]   Copy file from [/root/waidps] to [/.SYWorks/WAIDPS/waidps ]
Traceback (most recent call last):
  File "/usr/bin/waidps", line 18755, in <module>
    Main()
  File "/usr/bin/waidps", line 15164, in Main
    CheckAppLocation()
  File "/usr/bin/waidps", line 9154, in CheckAppLocation
    shutil.copy2(CurFileLocation, AppFileLocation)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/root/waidps'

I am using arch linux instead of blackarch.

**Comment by samtech09** [comment]
Is there anything i could do to fix that error and run waidps ?

**Comment by heichblatt** [comment]
Hi @samtech09,

I'm getting the same output. Please file a bug [upstream](https://github.com/SYWorks/waidps). The script creates a directory `/.SYWorks/WAIDPS/waidps` directly under `/`, which is against the Filesystem Hierarchy Standard (`man 7 hier`), to say the least.

Cheers,
heichblatt

**Comment by samtech09** [comment]
Hi @heichblatt ,
It looks it is not the upstream bug!
After going through the source of waidps.py, i found that it requires the binary should be in /.SYWorks/WAIDPS/   [ hard coded ]

So, I did following
`sudo cp /usr/bin/waidps /.SYWorks/WAIDPS/`

Now it started working.
I guess you need to update pacakage script to do same.

**Comment by samtech09** [comment]
Or simple create a link to /usr/bin/waidps into that folder.
`sudo ln -s /usr/bin/waidps /.SYWorks/WAIDPS/waidps`

**Comment by heichblatt** [comment]
Hi @samtech09,

> It looks it is not the upstream bug!
> After going through the source of waidps.py, i found that it requires the binary should be in /.SYWorks/WAIDPS/ [ hard coded ]

Then it is, in fact, an upstream bug, unless one considers breaking the [Filesystem Hierarchy Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) normal behaviour. `/.SYWorks` is not created by [the PKGBUILD](https://github.com/BlackArch/blackarch/blob/master/packages/waidps/PKGBUILD), but by the upstream software. Requiring binaries to be in (even absurdly) non-standard directories is a bug, as it goes against [Arch policy](https://wiki.archlinux.org/index.php/arch_filesystem_hierarchy).
