### ISSUE TITLE
[Tool request] PANDA

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#1148]
https://github.com/panda-re/panda

**Comment by konfou** [comment]
The link given points to a deprecated repo (PANDA 1.0). Development has been moved to [panda-re/panda](/panda-re/panda). Build instructions for Ubuntu/Debian can be found as a script easily convertable to a PKGBUILD at https://github.com/panda-re/panda/commit/f8a86e9568a2e06ed7f5d074f0e4577afc6ef6af.

**Comment by Edu4rdSHL** [comment]
Closing because it needs a deprecated version of wireshark. https://github.com/panda-re/panda#dependencies

**Comment by vdun** [comment]
I guess it should work: https://github.com/panda-re/panda/pull/364
