### ISSUE TITLE
UEFI X64 USB boot

### ISSUE THREAD

**Issue by blazefade** [BlackArch/blackarch#1154]
Upon first boot the isn gives issues involving in able to mount the usb

**Comment by Tazmain** [comment]
Not sure I follow. Does the live usb not boot?

**Comment by blazefade** [comment]
![photo aug 31 3 59 09 pm](https://cloud.githubusercontent.com/assets/21372725/18150586/f32bfa38-6f9c-11e6-89d1-bf417e6d1070.jpg)
This is Where unit starts from a USB boot on a UEFI intel I3 Skylake Processor windows 10 computer. From here it wont let me perform command line install or even going to the UEFI Shell it doesn't go anywhere.
Currently just tried the netboot ISO with it being hardwired and receive the same issue.

**Comment by Tazmain** [comment]
Have you tried dd ? rufus also seems to work but you need to filled with the settings. This is not a blackarch issue, its your liveboot

**Comment by blazefade** [comment]
I'm stuck on Windows. Don't have a very viable dd option on Windows. That was currently with Rufus as recommended, also tried LILO. Rufus was using the settings of both mbr and UEFI option, unless there is one I missed let me know.

**Comment by heichblatt** [comment]
Looks like @Tazmain is correct. You could use (another) live medium to boot, then use the `dd` from that medium to write your BlackArch stick.

**Comment by blazefade** [comment]
I'll give it a shot. I'll post results within 24 hours.

**Comment by Tazmain** [comment]
If you are running windows 10 just activate bash.

**Comment by blazefade** [comment]
I didn't know Windows 10 finally supported bash. That's a bonus thanks for the helpful tip Tazmain

**Comment by heichblatt** [comment]
@blazefade, there's also http://www.chrysocome.net/dd
