### ISSUE TITLE
cloudflare-scrape: multiple issues / broken package

### ISSUE THREAD

**Issue by nil0x42** [BlackArch/blackarch#1156]
## issue 1: package name
as the package is a python2 library and not a tool, it might be relevant to rename it `python2-cfscrape`

## issue 2: unsatisfied dependency
the library now depends on js2py instead of python2-pyexecjs

**proof:**
```py
>>> import cfscrape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/cfscrape/__init__.py", line 7, in <module>
    import js2py
ImportError: No module named js2py
````

## suggestions:
* rename package name into `python2-cfscrape`
* create new package library `python2-js2py`
* in **PKGBUILD**, change `python2-pyexecjs` dependency to `python2-js2py`
* upgrade `cloudget`'s **PKGBUILD** to set new cfscrape package name (if changed)

**Comment by noptrix** [comment]
thanks a lot @nil0x42 - will be fixed with your suggestions

**Comment by noptrix** [comment]
done and released. thx again for the report.
