### ISSUE TITLE
[Tool Request] idb

### ISSUE THREAD

**Issue by GeneralZero** [BlackArch/blackarch#1157]
https://github.com/dmayer/idb

**Comment by noptrix** [comment]
thx, will be added.

**Comment by noptrix** [comment]
the package is almost done, though the ruby qtbindings has still errors on arch linux.

**Comment by noptrix** [comment]
still errors with qtbindings. can't be compiled.

**Comment by NovaCygni** [comment]
Sup Noptrix... https://github.com/Homebrew/homebrew-core/issues/6232 Once Qt4 has been bound the program should work fine: though, additionally the fix at the bottom of https://github.com/dmayer/idb/issues/79 will be required aswell.

**Comment by dmayer** [comment]
hey, I'm the author of idb. What can I do to help for packaging idb?

**Comment by noptrix** [comment]
@dmayer we can't build/install 'qtbindings 4.8.6.2'. Here are the PKGBUILD and install file for 'idb' for ArchLinux/BlackArch: http://sprunge.us/gJJP and http://sprunge.us/ZKfK

**Comment by dmayer** [comment]
Thanks @noptrix.What is the best way for me to test this? I think using the gem version of idb may be easier. Happy to try to debug.

**Comment by noptrix** [comment]
@dmayer Oh, didn't know that gem for idb is available. Well, that should be easier then...I will give a try now and let you know.

**Comment by noptrix** [comment]
@dmayer ok that worked!

**Comment by dmayer** [comment]
oh sweet. i was just trying to compile it from source :) Nice. Let me know if I can help further!

**Comment by noptrix** [comment]
@dmayer thanks. @GeneralZero going to release idb now. closing this issue.
