### ISSUE TITLE
[Tool Request] evilmaid

### ISSUE THREAD

**Issue by mrdc** [BlackArch/blackarch#1158]
Hello,

Package evilmaid is missing as source (http://invisiblethingslab.com/resources/evilmaid/evilmaidusb-${pkgver}.img") is not available anymore.

**Comment by heichblatt** [comment]
Hello @mrdc,

I wrote to Invisible Things Labs to ask if they still have the image. I'll get back to you as soon as I hear anythin.

Cheers

**Comment by noptrix** [comment]
thx, will be added

**Comment by noptrix** [comment]
@heichblatt any response from them?

**Comment by heichblatt** [comment]
Unfortunately not, it's a shame though..

**Comment by noptrix** [comment]
thanks for the follow-up @heichblatt

**Comment by noptrix** [comment]
Oh, i just saw that we have evilmaid already included. The image file is located in /usr/share/evilmaid/ respectively @heichblatt @mrdc

**Comment by heichblatt** [comment]
You don't have the image lying around, by any chance @noptrix?

**Comment by noptrix** [comment]
evilmaid is packaged with the image. you can get it with pacman -S evilmaid. i myself have it in /usr/share/evilmaid/*.img

**Comment by Stephanie8887** [comment]
Hello, how can I build this on Debian 9? Forgive me for this question, I'm a beginner!

**Comment by ikstream** [comment]
This is the Blackarch Linux repository, for questions about evilmaid on Debian you will have to look at some other channels
