### ISSUE TITLE
Install problems - invalid keyring signature.

### ISSUE THREAD

**Issue by Wit4r7** [BlackArch/blackarch#1160]
Hey, i want to use blacharch on my existing arch. 

I followed the introdution on blackarch.org. 
After "sudo ./strap.sh" i get the following error: 
`[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch`

I tryed to delete the gnupg folder, refresh the keys and so on. Still get the same error. 
This i get by sudo sh -xe 
`
+ MIRROR=https://www.mirrorservice.org/sites/blackarch.org/blackarch/
+ blackarch_setup
+ check_priv
+ '[' 0 -ne 0 ']'
+ msg 'installing blackarch keyring...'
++ tput bold
++ tput setaf 2
++ tput sgr0
+ echo '[+] installing blackarch keyring...'
[+] installing blackarch keyring...
+ make_tmp_dir
++ mktemp -d /tmp/blackarch_strap.XXXXXXXX
+ tmp=/tmp/blackarch_strap.65o2edIw
+ trap 'rm -rf /tmp/blackarch_strap.65o2edIw' EXIT
+ cd /tmp/blackarch_strap.65o2edIw
+ fetch_keyring
+ curl -s -O 'https://www.blackarch.org/keyring/blackarch-keyring.pkg.tar.xz{,.sig}'
+ verify_keyring
+ gpg --keyserver http://pgp.mit.edu --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3
+ gpg --keyserver-options no-auto-key-retrieve --with-fingerprint blackarch-keyring.pkg.tar.xz.sig
+ err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
++ tput bold
++ tput setaf 1
++ tput sgr0
+ echo '[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch'
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
+ exit 1337
+ rm -rf /tmp/blackarch_strap.65o2edIw
`

Have no idea what could i do.

**Comment by noptrix** [comment]
remove please /etc/pacman.d/gnupg and simply re-run strap.sh.

**Comment by cLn73** [comment]
Hello ... I have found a solution for the strap.sh script error ...

Edit the file "/etc/pacman.d/gnupg/gpg.conf" and replace "hkp: // server" for "http://pgp.mit.edu" without the quotes and execute the script, at least it has worked in my case. .

**Comment by dehein** [comment]
Found a solution. Replace the mit gpg server with this one: http://pool.sks-keyservers.net

**Comment by jmg87** [comment]
I had this same issue. My configured key server was hkp://pool.sks-keyservers.net , replacing it for http://pgp.mit.edu worked.
