### ISSUE TITLE
"Command not found" after installing Java

### ISSUE THREAD

**Issue by gdfhgjhjk** [BlackArch/blackarch#1161]
I install last Java into blackarch. After this all apps from blackarch menu are not working. Error message appears `bash: *cmd_name*: command not found`
How can I fix it?

**Comment by heichblatt** [comment]
Hi @gdfhgjhjk ,

how exactly did you install Java? Do you have any relevant output you could post?

Cheers

**Comment by gdfhgjhjk** [comment]
I install via `pacman -S jre8-openjdk` as described in https://wiki.archlinux.org/index.php/Java
What output could I post?

**Comment by gdfhgjhjk** [comment]
Pacman exit without errors. Of course, blackarch tools also can't be run from a terminal, same as from menu.

**Comment by heichblatt** [comment]
Can you install one of the tools you actually used before the Java installation and try to run it?

**Comment by gdfhgjhjk** [comment]
I install ~5 tools after installing Java and all of them correctly works (sqlmap, etc.).

**Comment by gdfhgjhjk** [comment]
Any updates?
