### ISSUE TITLE
wifi pumpkin issues

### ISSUE THREAD

**Issue by kurobeats** [BlackArch/blackarch#1168]
When launching wifi-pumpkin, you get a blank box and the follow errors:

```
» whoami
root
» wifi-pumpkin 
Loading GUI...
which: no driftnet in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
WiFi-Pumpkin Running!
X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x15f
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 5 (X_ShmCreatePixmap)
  Resource id:  0x106
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x1600019
```

**Comment by futsoulja** [comment]
I'm having the same issue. Have you found a solution?

**Comment by noptrix** [comment]
ok thx for reporting. will take a look

**Comment by ikstream** [comment]
see BlackArch/blackarch#1533

**Comment by E3V3A** [comment]
`sudo QT_X11_NO_MITSHM=1 wifi-pumpkin`

**Comment by becare** [comment]
sudo nano /etc/environment

Add this line:
`QT_X11_NO_MITSHM=1`

Enjoy!

**Comment by 999jay999** [comment]
I have followed the instructions mentioned by both @E3V3A and @becare , however, neither seem to work for me.

I am trying this in VMWare. Also to note, the environment file had nothing in it all, so `QT_X11_NO_MITSHM=1` is now the only code in the file. I don't know if this matters.

Can anyone provide any further advice?

Thanks

**Comment by PedroSFreitas** [comment]
@kurobeats are you still facing this issue?

Did you check the link provide to another threat? That then points to an upstream Issue?
If everything is working for you now, please consider closing this issue.

**Comment by ikstream** [comment]
As there was no update since September I'm closing this issue. If you think this is an error, please provide some information on @PedroSFreitas questions.

**Comment by MrityunjayGoswami** [comment]
> sudo nano /etc/environment
> 
> Add this line:
> `QT_X11_NO_MITSHM=1`
> 
> Enjoy!

yes this is worked for me
