### ISSUE TITLE
NEED HELP - BLACKARCH IN VM

### ISSUE THREAD

**Issue by M1k43lS** [BlackArch/blackarch#1171]
Please, i need help with a ¿fail? 
I tried boot the blackarch from a .iso in a virtual machine (virtual box) and this charge, but in one moment the screen puts black and no change more. 
In this link i have put a record video(1min) of the process.
https://drive.google.com/file/d/0BzJMkUfSUzpZSFRybjN6MXF3Nm8/view?usp=drive_web
Anybody can say me something? 
Tanks for all.

**Comment by aancw** [comment]
Can you post log from `/var/log/Xorg.0.log` ? Maybe we can identify what problem is
