### ISSUE TITLE
Instaling blackarch repositories on top of Manjaro (ArchBased) get keyring fails

### ISSUE THREAD

**Issue by ryukinix** [BlackArch/blackarch#1175]
I got several seconds running the `strap.sh` as described on the [official guide](https://blackarch.org/downloads.html#install-repo) just doesn't works. Anyone can give me some help? Maybe can be some legacy code after the update.

Thanks for the attention.

**Comment by ldionmarcil** [comment]
Some debug info would be required for anyone to help you there… this is quite vague. Do you get no output from running the script at all?

**Comment by ryukinix** [comment]
Yes, I'll paste here, sorry. I was working in another thing. (the script takes about 500 seconds to finish and get the error)

**Comment by ryukinix** [comment]
```
❯ sudo ./strap.sh 
[sudo] password for lerax: 
[+] installing blackarch keyring...
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
                                                                                
   515s
❯ 
```

**Comment by heichblatt** [comment]
Does [this](https://github.com/BlackArch/blackarch/issues/1160#issuecomment-245672693) fix the issue for you?

**Comment by ArchTrack** [comment]
I have the same problem. I tried from arch (I can't even execute strap.sh so I can't call pacman -S blackarch) and I tried from the official ISO. The same problem; why?
Deleting /etc/pacman.d/gnupg change nothing
`[arch@localhost ~]$ sudo bash -x strap.sh 
+ MIRROR=https://www.mirrorservice.org/sites/blackarch.org/blackarch/
+ blackarch_setup
+ check_priv
+ '[' 0 -ne 0 ']'
+ msg 'installing blackarch keyring...'
++ tput bold
++ tput setaf 2
++ tput sgr0
+ echo '[+] installing blackarch keyring...'
[+] installing blackarch keyring...
+ make_tmp_dir
++ mktemp -d /tmp/blackarch_strap.XXXXXXXX
+ tmp=/tmp/blackarch_strap.1SCkxT51
+ trap 'rm -rf /tmp/blackarch_strap.1SCkxT51' EXIT
+ cd /tmp/blackarch_strap.1SCkxT51
+ fetch_keyring
+ curl -s -O 'https://www.blackarch.org/keyring/blackarch-keyring.pkg.tar.xz{,.sig}'
+ verify_keyring
+ gpg --keyserver http://pgp.mit.edu --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3
+ gpg --keyserver-options no-auto-key-retrieve --with-fingerprint blackarch-keyring.pkg.tar.xz.sig
+ err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
++ tput bold
++ tput setaf 1
++ tput sgr0
+ echo '[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch'
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
+ exit 1337
+ rm -rf /tmp/blackarch_strap.1SCkxT51
[arch@localhost ~]$ 

`

**Comment by ryukinix** [comment]
Yes, deleting the gnupg change nothing here too. Why²?

**Comment by dehein** [comment]
Solution was for me to change the keyserver to something like: http://pool.sks-keyservers.net in the strap.sh

**Comment by 0DARKer** [comment]
I solved the problem. 
just put the same keyserver between strap.sh and gpg.conf ,usually dont change gpg.conf
