### ISSUE TITLE
please help.i am a new user

### ISSUE THREAD

**Issue by michaelchihoko** [BlackArch/blackarch#1189]

**Comment by michaelchihoko** [comment]
![wp_20161008_001 1](https://cloud.githubusercontent.com/assets/22577855/19212799/329e30da-8d0e-11e6-8cb9-d7ecfa1ec5e0.jpg)

**Comment by heichblatt** [comment]
Please post the output of the command mentioned in the last line of your photo.

**Comment by michaelchihoko** [comment]
this is my problem above .forgive me for not presenting my issue very well.i am a new user.help please .i followed the instructions verywell when installing

**Comment by michaelchihoko** [comment]
should i do  that using the live disk

**Comment by noptrix** [comment]
which iso did you use?
