### ISSUE TITLE
Network ethernet/wifi auto disconnect

### ISSUE THREAD

**Issue by DokiTeeX** [BlackArch/blackarch#1196]
Hi
Im a new user and im trying to install blackarch with the complete iso but when I have to configure my network via wicd-gtk. It correctly detect my wired and wireless network but when I try to connect to mine it says  (at the bottom) Connection Established... and 2second after that it disconnect automaticaly !

Hope you'll help me thanks in advance

**Comment by noptrix** [comment]
what have you done exactly? do you have logfiles/screenshots so we can see what was going on? did you check the running services such as dhcpcd wicd etc.? also, you should refer to arch linux wiki/documentation...
