### ISSUE TITLE
New Mirror

### ISSUE THREAD

**Issue by bolvarak** [BlackArch/blackarch#1208]
Domain: mirrors.tuxns.net
Country: US
Protocols: rsync, http, https
Bandwidth: 1gbps
IPv4: 63.141.252.178
IPv6: 2604:4300:a:3::178
URLs:
rsync://mirrors.tuxns.net/blackarch
http://mirrors.tuxns.net/blackarch
https://mirrors.tuxns.net/blackarch
Email: travis.brown@cdndepo.com

**Comment by noptrix** [comment]
thank you! we will add it.

**Comment by noptrix** [comment]
thanks. added and announced
