### ISSUE TITLE
[Update pakage] Katana

### ISSUE THREAD

**Issue by RedToor** [BlackArch/blackarch#1216]
please u can update pakage

 https://github.com/BlackArch/blackarch/blob/master/packages/katana/PKGBUILD

pkgname='katanaFramework'
pkgver='0.0.1.0'

source=("http://downloads.sourceforge.net/project/katanas/katana_${pkgver}%28BUILD%200065%29.zip")

local tools="ktf.console ktf.run ktf.update ktf.gui ktf.ktf"

change /usr/share/doc/katana/ -> /usr/share/KatanaFramework

Thanks so much

**Comment by noptrix** [comment]
updated

**Comment by RedToor** [comment]
Thanks !
