### ISSUE TITLE
[Tool request] python-evtx

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#1217]
https://github.com/williballenthin/python-evtx

**Comment by noptrix** [comment]
added and released as: python-python-evtx and python2-python-extx

**Comment by vdun** [comment]
Can you please include the folder 'scripts':
https://github.com/williballenthin/python-evtx/tree/master/scripts

**Comment by noptrix** [comment]
ok. thx.

**Comment by noptrix** [comment]
they have been installed now to /usr/share/python[2]-python-evtx/scripts/

**Comment by vdun** [comment]
thx
