### ISSUE TITLE
[Tool request] plaso

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#1218]
https://github.com/log2timeline/plaso

**Comment by osospeed** [comment]
This package requires python2 and a list of [dependencies](https://github.com/log2timeline/plaso/blob/master/requirements.txt).
I'm listing here only the missing packages from BlackArch and [Arch](https://www.archlinux.org/packages/) as TODOs :

Available in @ArchStrike :
- [ ] artifacts
- [ ] hachoir-metadata
- [ ] libesedb-python
- [ ] libevt-python
- [ ] libevtx-python
- [ ] libfsntfs-python
- [ ] libfwnt-python
- [ ] libfwsi-python
- [ ] liblnk-python
- [ ] libmsiecf-python
- [ ] libolecf-python
- [ ] libqcow-python
- [ ] libsmraw-python
- [ ] libvhdi-python
- [ ] libvmdk-python
- [ ] libvslvm-python

Available in AUR :
- [ ] libewf-python
- [ ] libfvde-python
- [ ] libscca-python

No available :
- [ ] biplist
- [ ] dtfabric

**Comment by osospeed** [comment]
@vdun: Thanks. Added.
