### ISSUE TITLE
[Tool request] Windows Credentials Editor (WCE)

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#1221]
http://www.ampliasecurity.com/research/windows-credentials-editor/

**Comment by noptrix** [comment]
would be nice if you can also provide PKGBUILDs. we can review/update/adjust/fix the PKGBUILDs of course. that way it would be faster to add the tools. ;)

**Comment by vdun** [comment]
True. I just add the stuff here as a TODO for me and the community. Personally, i'll try to be more active ...
Thumbs up for your great efforts 👍

**Comment by noptrix** [comment]
ok :)

**Comment by noptrix** [comment]
added and released
