### ISSUE TITLE
[Request] Create un-privileged user apart from root 

### ISSUE THREAD

**Issue by RamexKumar** [BlackArch/blackarch#1223]
Create an un-privileged user by default in the distribution. Few tools can be run without root privilege to reduce security risk. sudo can be used, if root rights are needed. For eg. wireshark can be run as normal user, after setting setuid to dumpcap.

**Comment by i3-Arch** [comment]
@RamexKumar This is a pentesting distribution. That being said, you shouldn't be using blackarch to do everyday tasks (ie: using it as your primary/personal os) it should be used to perform penetration tests/analysis/etc.  In my opinion I don't see a need to create an un-privileged account by default to call tools via sudo.

**Comment by RamexKumar** [comment]
Thank you for your feedback. However, my view is to always run with minimum required privilege even an pentest distribution. It may or may not be correct for BlackArch, as each distro is unique and differnt. Let me mark this as closed.
