### ISSUE TITLE
wcc's wsh segmentation fault / crash

### ISSUE THREAD

**Issue by nbaer** [BlackArch/blackarch#1226]
Using the blackarch repo on top of an Arch install.

After installation, running wsh on any executable/shared library results in the following segmentation fault:

```
$ wsh /bin/sh

[SIGSEGV]	Read	000000000017        (address not mapped to object)
	000042009ce4    wsh(scan_sections+0x91)
	000042009dfd    wsh(shdr_callback+0x60)
	7f0d176f25a4    /usr/lib/libc.so.6(dl_iterate_phdr+0xf4)
	00004200cd41    wsh(reload_elfs+0x2f8)
	00004201de40    wsh(main+0x67)
	7f0d175f4291    /usr/lib/libc.so.6(__libc_start_main+0xf1)
	0000420078fa    wsh(_start+0x2a)
Segmentation fault

**Comment by nbaer** [comment]
No! I apologize, I just tested again very recently and forgot to come back and close the ticket.

Everything is working just fine with wcc through the blackarch repo (64-bit arch linux).

**Comment by PedroSFreitas** [comment]
Thanks @nbaer
