### ISSUE TITLE
Login Service don't start

### ISSUE THREAD

**Issue by TatsuCoder** [BlackArch/blackarch#1228]
Installed the system usually h
Using the ISO downloaded from the official site, however
After the installation finishes the system is I try to start I get a message "failed to start service login systemctl. logind. service," I tried to reinstall the systemctl or even apply the "mask" but solves nothing.

**Comment by pantuts** [comment]
Can this be opened again? I also have same issue.
Version: 2017.03.01

**Comment by ikstream** [comment]
This is a know open bug (see BlackArch/blackarch#1618 and BlackArch/blackarch-iso#19)
If you can, please use the repository install for now.

**Comment by pantuts** [comment]
@ikstream got it thanks.
