### ISSUE TITLE
ARM64 repository

### ISSUE THREAD

**Issue by mdilai** [BlackArch/blackarch#1230]
Hello,
BlackArch repositories are missing arm64 architecture what make impossible to use it on Raspberry Pi 3, ODroid-C2 etc. Kali Linux builds for this platform already exist so most software should be compatible.

**Comment by noptrix** [comment]
yeah. was our next step to do. thanks for reporting anyway. we will soon release arm64 packages

**Comment by mdilai** [comment]
Nice to hear that! Generally, armv7h binaries should be fully backward
compatible but pacman doesn't support custom add-on architectures, like apt
do. Maybe you know a workaround or so?

27 лист. 2016 р. 19:39 "noptrix" <notifications@github.com> пише:

yeah. was our next step to do. thanks for reporting anyway. we will soon
release arm64 packages

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BlackArch/blackarch/issues/1230#issuecomment-263135563>,
or mute the thread

**Comment by noptrix** [comment]
@mdilai https://blackarch.org/blackarch/blackarch/os/aarch64/ aarch64 available now. still needs updates and tools to be added though. but almost 1k tools. enjoy
