### ISSUE TITLE
blackarch.db: Unrecognized archive format

### ISSUE THREAD

**Issue by divercarlos7** [BlackArch/blackarch#1235]
Hello. I have the same problem, but i don´t know how success 
in:
` ➜  ~ sudo pacman -Ss bettercap`
output:
`error : could not open file /var/lib/pacman/sync/blackarch.db: Unrecognized archive format`

I don´t know what I have to do.
I´m from colombia forgive my english. Any help is welcome.

**Comment by noptrix** [comment]
can you re-run: pacman -Syyu please and then re-try?

**Comment by divercarlos7** [comment]
Now it is working, but I Don't know how. 
I have reverted all about of Blackarch install, then I used the official guide. I saw that the Blackarch site was not working yesterday. Thanks
