### ISSUE TITLE
[Tool Update] - Username Anarchy

### ISSUE THREAD

**Issue by silverly** [BlackArch/blackarch#1240]
Hi Blackarch Team,

Im wondering if you can update username-anarchy, the current version is 0.2 but there is a 0.5 version in the repositiory (https://github.com/urbanadventurer/username-anarchy). I wasn't sure how to pull an update since the tool (username-anarchy) hasn't done a release as per the PKGBUILD (blackarch/packages/username-anarchy/PKGBUILD ). 

Thanks

**Comment by noptrix** [comment]
thanks for reporting. we've updated and released it. we now use the git upstream version.

**Comment by silverly** [comment]
Thank you for doing that so quickly!
