### ISSUE TITLE
Systemctl issue

### ISSUE THREAD

**Issue by smashgen** [BlackArch/blackarch#1246]
I follow the instructions to installing Blackarch from live Iso as a main OS on my computer. I followed all the instructions to a tee but run into a problem when trying to boot for the first time. 
The message I get is "failed: failed to start login service. see 'systemctl status systemd-logind.service' for details" 

After this message is shown on boot the terminal just hangs, no longer displaying messages.

**Comment by noptrix** [comment]
please use the new ISOs and re-open this ticket if still fails.
