### ISSUE TITLE
sha1sum of strap.sh is not correct in blackarch-guide-en.pdf

### ISSUE THREAD

**Issue by desdic** [BlackArch/blackarch#1249]
Hi,

Sha1sum differs from the documentation section 2.1.1. The one I get is 

34b1a3698a4c971807fb1fe41463b9d25e1a4a09  strap.sh

**Comment by sighbr** [comment]
Hopefully should be updated soon, noticed this and thought something was amiss but looks to be updated in https://blackarch.org/downloads.html

**Comment by noptrix** [comment]
yeah, it's updated in downloads.html. we will update it in the guide. the guide will be upgraded in general, soon...
