### ISSUE TITLE
strap.sh ERROR: invalid keyring signature

### ISSUE THREAD

**Issue by sloogy** [BlackArch/blackarch#1255]
how do i solve this i deleted pacman.d/gnupg
same issue as before

 $ sudo sh -x strap.sh                                                                                                                                      [18:32:04]
+ MIRROR=https://www.mirrorservice.org/sites/blackarch.org/blackarch/
+ blackarch_setup
+ check_priv
+ '[' 0 -ne 0 ']'
+ msg 'installing blackarch keyring...'
++ tput bold
++ tput setaf 2
++ tput sgr0
+ echo '[+] installing blackarch keyring...'
[+] installing blackarch keyring...
+ make_tmp_dir
++ mktemp -d /tmp/blackarch_strap.XXXXXXXX
+ tmp=/tmp/blackarch_strap.N3bF9If7
+ trap 'rm -rf /tmp/blackarch_strap.N3bF9If7' EXIT
+ cd /tmp/blackarch_strap.N3bF9If7
+ fetch_keyring
+ curl -s -O 'https://www.blackarch.org/keyring/blackarch-keyring.pkg.tar.xz{,.sig}'
+ verify_keyring
+ gpg --keyserver http://pgp.mit.edu --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3
+ gpg --keyserver-options no-auto-key-retrieve --with-fingerprint blackarch-keyring.pkg.tar.xz.sig
+ err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
++ tput bold
++ tput setaf 1
++ tput sgr0
+ echo '[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch'
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
+ exit 1337
+ rm -rf /tmp/blackarch_strap.N3bF9If7

**Comment by noptrix** [comment]
there is a bug with gnupg. you have to wait until archlinux releases the bugfix or switch to [testing] and update your gnupg and re-run strap.sh

**Comment by sloogy** [comment]
ive updated gnupg to version 2.1.17-3 same problem should i regenerate the keys?

**Comment by noptrix** [comment]
you should do a restart. then yes or maybe: rm -rf /etc/pacman.d/gnupg and then re-run strap.sh
