### ISSUE TITLE
Problem in installing

### ISSUE THREAD

**Issue by mackzwell123** [BlackArch/blackarch#1256]
Sirs please help me this is what happen when I install Blackarch linux on my laptop

please help me this is what happen when I start installing Black arch linux

Probing EDD (edd=off to disable). . . ok
: : running early hook [udev]
starting version 232
: : triggering uevents . . .
: : running hook [memdisk]
: : running hook [archiso]
: : running hook [archiso_loop_mnt]
: : running hook [archiso_pxe_common]
: : running hook [arhciso_pxe_nbd]
: : running hook [arhciso_pxe_http]
: : running hook [arhciso_pxe_nfs]
: : mounting '/dev/disk/by-label/BLACKARCH_2' to ' /run/archiso/bootmnt'
: : Device '/dev/disk/by-Label/BLACKARCH_2' mounted successfully.
: : Mounting '/dev/loop0' to '/run/archiso/sfs/airootfs'
mount: wrong fs type, bad opting, bad superblock on /dev/loop0,
missing codepage or helper program, or order error

        In some cases useful info is found is syslog- try
        dmesg | tail or so.
ERROR; Failed to mount '/dev/loop0'
Falling back to interactive prompt
You can try to fix the probelm manually, log out when you are finished
sh: can't access tty; jon control turned off
[root fs ]

**Comment by xdindanx** [comment]
Hi, had the same problem, for me it was a bad iso burn to USB, try to run dd another time

**Comment by heichblatt** [comment]
Sounds like @xdindanx is right, did you try to re-`dd` your flash drive?
