### ISSUE TITLE
Permit SSH root login (password auth) by default

### ISSUE THREAD

**Issue by CaledoniaProject** [BlackArch/blackarch#1260]
Can you change the default sshd configuration, and allow root to login with password by default?
It's not very convenient in VMWare.

**Comment by noptrix** [comment]
sure. was also in the TODO. we will change it.

**Comment by ldionmarcil** [comment]
This seems awfully careless and I'm pretty sure most users won't be aware of this/won't want this, leaving them vulnerable…

**Comment by ChrisFernandez** [comment]
I agree, root login should *never* be allowed by default, no matter what.
