### ISSUE TITLE
Beef Error.

### ISSUE THREAD

**Issue by Fly34567** [BlackArch/blackarch#1262]
![img_0071](https://cloud.githubusercontent.com/assets/15278051/21541481/c023b108-cd84-11e6-89ab-7aa5f228f733.JPG)
![img_0072](https://cloud.githubusercontent.com/assets/15278051/21541571/8aac48f4-cd85-11e6-8ae4-3b113fc3fffc.JPG)

**Comment by Fly34567** [comment]
API Fire Error: invalid byte sequence in US-ASCII in {:owner=>BeEF::Extension::AdminUI::API::Handler,  :id=>16.mount_handler()

**Comment by noptrix** [comment]
should be fixed now
