### ISSUE TITLE
[Tool request] HERCULES

### ISSUE THREAD

**Issue by EgeBalci** [BlackArch/blackarch#1263]
https://github.com/EgeBalci/HERCULES

**Comment by noptrix** [comment]
hi, rather than forcing people to execute the binaries Setup Update etc., can you instead drop a 'build.sh' to build from source or something similar please? We wil add it immediately then

**Comment by EgeBalci** [comment]
I have adjusted the setup according to your requests, now with running `go run Setup.go` command, go script will automatically install the dependencies and compile the tool from source code.

**Comment by noptrix** [comment]
perfect, tsk. will be added shortly. :)

**Comment by noptrix** [comment]
added and released.

**Comment by noptrix** [comment]
just for your informatipon, we announced your tool on twitter as well: https://twitter.com/blackarchlinux/status/828221811687096320 - ppl liked it including myself. good stuff...

**Comment by EgeBalci** [comment]
Thanks a lot, happy to contribute :)

2017-02-05 23:07 GMT+03:00 noptrix <notifications@github.com>:
