### ISSUE TITLE
Failed to retrieving file "blackarch.db"

### ISSUE THREAD

**Issue by bhavin23** [BlackArch/blackarch#1264]
New webie!
I'm getting this error when try to sync

```
`[ blackarch ~ ]# pacman -Syy
:: Synchronizing package databases...
 core                                                                      122.8 KiB   246K/s 00:01 [##########################################################] 100%
 extra                                                                    1751.7 KiB   500K/s 00:04 [##########################################################] 100%
 community                                                                   3.7 MiB   426K/s 00:09 [##########################################################] 100%

error: failed retrieving file 'blackarch.db' from mirror.adversec.com : The requested URL returned error: 404

error: failed to update blackarch (unexpected error)
[ blackarch ~ ]# `
```

I have removed 'mirror.adversec.com' from the repo. But still I'm getting this error. 
I wish to install it on metal but this error is on VBox. 

Please refer to the attached screenshot: [https://db.tt/spT6Dy5IK2](url)

**Comment by noptrix** [comment]
use another mirror

**Comment by bhavin23** [comment]
Thanks for replying!
But the problem is this domain is not in my systems mirror list.
`[ blackarch ~ ]# cat /etc/pacman.d/mirrorlist
###############################################################################
################# Arch Linux mirrorlist generated by Reflector #################
################################################################################

# With:       reflector --verbose --latest 5 --sort rate --save /etc/pacman.d/mirrorlist
# When:       2016-12-31 16:33:08 UTC
# From:       https://www.archlinux.org/mirrors/status/json/
# Retrieved:  2016-12-31 16:32:59 UTC
# Last Check: 2016-12-31 15:40:46 UTC


#ftp://mirror.tillo.ch/blackarch/$repo/os/$arch|tillo
Server = http://mirror.js-webcoding.de/pub/archlinux/$repo/os/$arch
Server = http://mirror.pseudoform.org/$repo/os/$arch
Server = https://mirror.js-webcoding.de/pub/archlinux/$repo/os/$arch
Server = https://mirror.pseudoform.org/$repo/os/$arch
Server = rsync://mirror.pseudoform.org/packages/$repo/os/$arch
[ blackarch ~ ]# `

Blackarch-mirrorlist
`[ blackarch ~ ]# cat /etc/pacman.d/blackarch-mirrorlist 
##
##  BlackArch repository mirrorlist
##  Generated: 2015-05-29
##

#Australia
#Server = http://blackarch.mirror.digitalpacific.com.au/$repo/os/$arch
#Server = rsync://mirror.digitalpacific.com.au/blackarch/$repo/os/$arch

#Austria
#Server = http://mirror.easyname.at/blackarch/$repo/os/$arch
#Server = ftp://mirror.easyname.at/blackarch/$repo/os/$arch
#Server = rsync://mirror.easyname.at/blackarch/$repo/os/$arch

#Belgium
#Server = http://mirror.alexiobash.com/blackarch/$repo/os/$arch

#Canada
#Server = http://mirror.clibre.uqam.ca/blackarch/$repo/os/$arch
#Server = http://blackarch.dropswitch.net/blackarch/$repo/os/$arch

#China
#Server = http://mirrors.hustunique.com/blackarch/$repo/os/$arch
#Server = https://mirrors.ustc.edu.cn/blackarch/$repo/os/$arch

#Denmark
#Server = http://mirrors.dotsrc.org/blackarch/$repo/os/$arch
#Server = ftp://mirrors.dotsrc.org/blackarch/$repo/os/$arch

#Ecuador
#Server = http://mirror.uta.edu.ec/blackarch/$repo/os/$arch
#Server = ftp://mirror.uta.edu.ec/blackarch/$repo/os/$arch
#Server = rsync://mirror.uta.edu.ec/blackarch/$repo/os/$arch
#Server = http://mirror.cedia.org.ec/blackarch/$repo/os/$arch
#Server = http://mirror.espoch.edu.ec/blackarch/$repo/os/$arch

#France
#Server = http://www.blackarch.org/blackarch/$repo/os/$arch
#Server = http://blackarch.tamcore.eu/$repo/os/$arch
#Server = https://blackarch.tamcore.eu/$repo/os/$arch
#Server = rsync://blackarch.tamcore.eu/blackarch/$repo/os/$arch
#Server = http://blackarch.leneveu.fr/blackarch/$repo/os/$arch
#Server = http://blackarch.pi3rrot.net/blackarch/$repo/os/$arch
#Server = http://blackarch.uteditor.de/$repo/os/$arch

#Germany
Server = http://blackarch.nullsecurity.net/blackarch/$repo/os/$arch
Server = http://blackarch1.curesec.com/blackarch/$repo/os/$arch
Server = http://blackarch2.curesec.com/blackarch/$repo/os/$arch

#Greece
#Server = http://ftp.cc.uoc.gr/mirrors/linux/blackarch/$repo/os/$arch
#Server = ftp://ftp.cc.uoc.gr/mirrors/linux/blackarch/$repo/os/$arch
#Server = rsync://blackarch@blackarch.org/blackarch$repo/os/$arch

#Great Britain
#Server = http://www.mirrorservice.org/sites/blackarch.org/blackarch/$repo/os/$arch
#Server = ftp://ftp.mirrorservice.org/sites/blackarch.org/blackarch/$repo/os/$arch
#Server = rsync://rsync.mirrorservice.org/blackarch.org/blackarch/$repo/os/$arch

#Ireland
#Server = http://blackarch.org/ftp.heanet.ie/mirrors/blackarch/$repo/os/$arch

#Italy
#Server = http://blackarch.mirror.garr.it/mirrors/blackarch/$repo/os/$arch
#Server = rsync://blackarch.mirror.garr.it/blackarch/$repo/os/$arch

#Japan
Server = http://www.ftp.ne.jp/Linux/packages/blackarch/$repo/os/$arch
Server = ftp://ftp.kddilabs.jp/Linux/packages/blackarch/$repo/os/$arch

#Netherlands
Server = http://blackarch.pr0s3c.nl/blackarch/$repo/os/$arch
Server = https://blackarch.pr0s3c.nl/blackarch/$repo/os/$arch

#Poland
#Server = http://ftp.icm.edu.pl/pub/Linux/dist/blackarch/$repo/os/$arch
#Server = ftp://ftp.icm.edu.pl/pub/Linux/dist/blackarch/$repo/os/$arch
#Server = rsync://ftp.icm.edu.pl/pub/Linux/dist/blackarch/$repo/os/$arch
#Server = gopher://ftp.icm.edu.pl/1/pub/Linux/dist/blackarch/$repo/os/$arch

#Russia
#Server = http://mirror.yandex.ru/mirrors/blackarch/$repo/os/$arch
#Server = ftp://mirror.yandex.ru/mirrors/blackarch/$repo/os/$arch
#Server = rsync://mirror.yandex.ru/mirrors/blackarch/$repo/os/$arch

#South Africa
#Server = http://blackarch.co.za/blackarch/$repo/os/$arch

#Spain
#Server = http://blackarch.smartdefence.cl/blackarch/$repo/os/$arch

#Sweden
#Server = http://mirror.zetup.net/blackarch/$repo/os/$arch

#Switzerland
#Server = http://mirror.easyname.ch/blackarch/$repo/os/$arch
#Server = ftp://mirror.easyname.ch/blackarch/$repo/os/$arch
#Server = rsync://mirror.easyname.ch/blackarch/$repo/os/$arch
#Server = https://mirror.tillo.ch/ftp/blackarch/$repo/os/$arch
#Server = http://mirror.tillo.ch/ftp/blackarch/$repo/os/$arch
#Server = ftpes://mirror.tillo.ch/blackarch/$repo/os/$arch
#Server = ftp://mirror.tillo.ch/blackarch/$repo/os/$arch
#Server = rsync://mirror.tillo.ch/blackarch/$repo/os/$arch

#Turkey
#Server = http://ftp.linux.org.tr/blackarch/$repo/os/$arch
#Server = ftp://ftp.linux.org.tr/blackarch/$repo/os/$arch
#Server = rsync://rsync.linux.org.tr/blackarch/$repo/os/$arch

#Taiwan
#Server = http://blackarch.cs.nctu.edu.tw/$repo/os/$arch
#Server = rsync://blackarch.cs.nctu.edu.tw/blackarch/$repo/os/$arch
#Server = http://ftp.yzu.edu.tw/Linux/blackarch/$repo/os/$arch
#Server = ftp://ftp.yzu.edu.tw/Linux/blackarch/$repo/os/$arch
#Server = rsync://ftp.yzu.edu.tw/Linux/blackarch/$repo/os/$arch

#USA
#Server = http://mirror2.tscinc.co/blackarch/$repo/os/$arch
#Server = rsync://mirror2.tscinc.co/blackarch$repo/os/$arch
#Server = https://blackarch.cdndepo.com/$repo/os/$arch
#Server = http://blackarch.cdndepo.com/$repo/os/$arch
#Server = rsync://blackarch.cdndepo.com/$repo/os/$arch
#Server = https://blackarch.mirror.packetfire.org/$repo/os/$arch
#Server = http://blackarch.mirror.packetfire.org/$repo/os/$arch
#Server = rsync://blackarch.mirror.packetfire.org/$repo/os/$arch
#Server = https://deadbeef.ninja/blackarch/$repo/os/$arch
Server = http://mirror.team-cymru.org/blackarch/$repo/os/$arch
#Server = ftp://mirror.team-cymru.org/blackarch/$repo/os/$arch
#Server = rsync://mirror.team-cymru.org/blackarch/$repo/os/$arch
#Server = http://mirror.jmu.edu/blackarch/$repo/os/$arch
#Server = ftp://mirror.jmu.edu/blackarch/$repo/os/$arch
#Server = rsync://mirror.jmu.edu/blackarch/$repo/os/$arch
#Server = http://mirror.oss.maxcdn.com/blackarch/$repo/os/$arch
#Server = ftp://mirror.oss.maxcdn.com/blackarch/$repo/os/$arch
#Server = rsync://mirror.oss.maxcdn.com/mirrors/blackarch/$repo/os/$arch
#Server = http://arch.localmsp.org/blackarch/$repo/os/$arch
[ blackarch ~ ]# `

Please advice!

**Comment by Rick0202020** [comment]
I don't know how but this blackarch-mirrorlist is working 

# Ecuador
Server = http://mirror.uta.edu.ec/blackarch/$repo/os/$arch      Server = https://mirror.uta.edu.ec/blackarch/$repo/os/$arch
Server = ftp://mirror.uta.edu.ec/blackarch/$repo/os/$arch       Server = http://mirror.cedia.org.ec/blackarch/$repo/os/$arch
Server = https://mirror.cedia.org.ec/blackarch/$repo/os/$arch   
# France                                                        Server = http://blackarch.tamcore.eu/blackarch/$repo/os/$arch
Server = https://blackarch.tamcore.eu/blackarch/$repo/os/$arch  Server = http://blackarch.leneveu.fr/blackarch/$repo/os/$arch
Server = http://blackarch.pi3rrot.net/blackarch/$repo/os/$arch  Server = http://mirror.cyberbits.eu/blackarch/$repo/os/$arch
Server = https://mirror.cyberbits.eu/blackarch/$repo/os/$arch

# Germany
Server = https://www.blackarch.org/blackarch/blackarch/$repo/os/$arch
Server = http://www.blackarch.org/blackarch/$repo/os/$arch
Server = https://mirrors.dr460nf1r3.org/repos/blackarch/$repo/os/$arch
Server = http://ftp.halifax.rwth-aachen.de/blackarch/$repo/os/$arch
Server = https://ftp.halifax.rwth-aachen.de/blackarch/$repo/os/$arch
Server = ftp://ftp.halifax.rwth-aachen.de/blackarch/$repo/os/$arch
Server = http://blackarch.unixpeople.org/$repo/os/$arch
Server = https://blackarch.unixpeople.org/$repo/os/$arch
Server = http://mirror.undisclose.de/blackarch/$repo/os/$arch
Server = https://mirror.undisclose.de/blackarch/$repo/os/$arch

# Greece
Server = http://ftp.cc.uoc.gr/mirrors/linux/blackarch/$repo/os/$arch
Server = ftp://ftp.cc.uoc.gr/mirrors/linux/blackarch/$repo/os/$arch

# Great Britain
Server = http://www.mirrorservice.org/sites/blackarch.org/blackarch/$repo/os/$arch
Server = https://www.mirrorservice.org/sites/blackarch.org/blackarch/$repo/os/$arch
Server = http://mirrors.gethosted.online/blackarch/blackarch/$repo/os/$arch
Server = https://mirrors.gethosted.online/blackarch/blackarch/$repo/os/$arch

# Iran
Server = http://mirror.blackrepo.com/$repo/os/$arch

# Italy
Server = http://blackarch.mirror.garr.it/mirrors/blackarch/$repo/os/$arch

# Japan
Server = http://www.ftp.ne.jp/Linux/packages/blackarch/$repo/os/$arch
Server = https://www.ftp.ne.jp/Linux/packages/blackarch/$repo/os/$arch
Server = http://ftp.kddilabs.jp/Linux/packages/blackarch/$repo/os/$arch
Server = https://ftp.kddilabs.jp/Linux/packages/blackarch/$repo/os/$arch

# Netherlands
Server = http://mirror.serverion.com/blackarch/$repo/os/$arch
Server = https://mirror.serverion.com/blackarch/$repo/os/$arch
Server = http://mirror.neostrada.nl/blackarch/$repo/os/$arch
Server = https://mirror.neostrada.nl/blackarch/$repo/os/$arch
Server = ftp://mirror.neostrada.nl/blackarch/$repo/os/$arch

# New Zealand
Server = http://nz-mirror.intergrid.com.au/blackarch/$repo/os/$arch

# Poland
Server = http://ftp.icm.edu.pl/pub/Linux/dist/blackarch/$repo/os/$arch
Server = https://ftp.icm.edu.pl/pub/Linux/dist/blackarch/$repo/os/$arch
Server = ftp://ftp.icm.edu.pl/pub/Linux/dist/blackarch/$repo/os/$arch
Server = gopher://ftp.icm.edu.pl/1/pub/Linux/dist/blackarch/$repo/os/$arch

# Russia
Server = http://mirror.surf/blackarch/$repo/os/$arch
Server = https://mirror.surf/blackarch/$repo/os/$arch
Server = http://mirror.truenetwork.ru/blackarch/$repo/os/$arch
Server = ftp://mirror.truenetwork.ru/blackarch/$repo/os/$arch
Server = http://mirror.yandex.ru/mirrors/blackarch/$repo/os/$arch
Server = ftp://mirror.yandex.ru/mirrors/blackarch/$repo/os/$arch

# Singapore
Server = http://download.nus.edu.sg/mirror/blackarch/$repo/os/$arch
Server = https://download.nus.edu.sg/mirror/blackarch/$repo/os/$arch

# Sweden
Server = http://mirror.zetup.net/blackarch/$repo/os/$arch
Server = https://mirror.zetup.net/blackarch/$repo/os/$arch

# Switzerland
Server = http://mirror.easyname.ch/blackarch/$repo/os/$arch
Server = ftp://mirror.easyname.ch/blackarch/$repo/os/$arch
Server = https://mirror.tillo.ch/ftp/blackarch/$repo/os/$arch
Server = http://mirror.tillo.ch/ftp/blackarch/$repo/os/$arch
Server = ftpes://mirror.tillo.ch/blackarch/$repo/os/$arch
Server = ftp://mirror.tillo.ch/blackarch/$repo/os/$arch

# Turkey
Server = http://ftp.linux.org.tr/blackarch/$repo/os/$arch
Server = https://ftp.linux.org.tr/blackarch/$repo/os/$arch
Server = ftp://ftp.linux.org.tr/blackarch/$repo/os/$arch

# Taiwan
Server = http://blackarch.cs.nctu.edu.tw/$repo/os/$arch

# UK
Server = http://mirrors.gethosted.online/blackarch/$repo/os/$arch
Server = https://mirrors.gethosted.online/blackarch/$repo/os/$arch

# USA
Server = http://blackarch.pr0s3c.nl/blackarch/$repo/os/$arch
Server = https://blackarch.pr0s3c.nl/blackarch/$repo/os/$arch
Server = http://mirror.math.princeton.edu/pub/blackarch/$repo/os/$arch
Server = http://distro.ibiblio.org/blackarch/$repo/os/$arch
Server = ftp://distro.ibiblio.org/blackarch/$repo/os/$arch
Server = https://deadbeef.ninja/blackarch/$repo/os/$arch
Server = http://mirror.team-cymru.com/blackarch/$repo/os/$arch
Server = ftp://mirror.team-cymru.com/blackarch/$repo/os/$arch

**Comment by Rick0202020** [comment]
> I don't know how but this blackarch-mirrorlist is working
> 
> # Ecuador
> Server = http://mirror.uta.edu.ec/blackarch/$repo/os/$arch Server = https://mirror.uta.edu.ec/blackarch/$repo/os/$arch Server = ftp://mirror.uta.edu.ec/blackarch/$repo/os/$arch Server = http://mirror.cedia.org.ec/blackarch/$repo/os/$arch Server = https://mirror.cedia.org.ec/blackarch/$repo/os/$arch
> 
> # France Server = http://blackarch.tamcore.eu/blackarch/$repo/os/$arch
> Server = https://blackarch.tamcore.eu/blackarch/$repo/os/$arch Server = http://blackarch.leneveu.fr/blackarch/$repo/os/$arch Server = http://blackarch.pi3rrot.net/blackarch/$repo/os/$arch Server = http://mirror.cyberbits.eu/blackarch/$repo/os/$arch Server = https://mirror.cyberbits.eu/blackarch/$repo/os/$arch
> 
> # Germany
> Server = https://www.blackarch.org/blackarch/blackarch/$repo/os/$arch Server = http://www.blackarch.org/blackarch/$repo/os/$arch Server = https://mirrors.dr460nf1r3.org/repos/blackarch/$repo/os/$arch Server = http://ftp.halifax.rwth-aachen.de/blackarch/$repo/os/$arch Server = https://ftp.halifax.rwth-aachen.de/blackarch/$repo/os/$arch Server = ftp://ftp.halifax.rwth-aachen.de/blackarch/$repo/os/$arch Server = http://blackarch.unixpeople.org/$repo/os/$arch Server = https://blackarch.unixpeople.org/$repo/os/$arch Server = http://mirror.undisclose.de/blackarch/$repo/os/$arch Server = https://mirror.undisclose.de/blackarch/$repo/os/$arch
> 
> # Greece
> Server = http://ftp.cc.uoc.gr/mirrors/linux/blackarch/$repo/os/$arch Server = ftp://ftp.cc.uoc.gr/mirrors/linux/blackarch/$repo/os/$arch
> 
> # Great Britain
> Server = http://www.mirrorservice.org/sites/blackarch.org/blackarch/$repo/os/$arch Server = https://www.mirrorservice.org/sites/blackarch.org/blackarch/$repo/os/$arch Server = http://mirrors.gethosted.online/blackarch/blackarch/$repo/os/$arch Server = https://mirrors.gethosted.online/blackarch/blackarch/$repo/os/$arch
> 
> # Iran
> Server = http://mirror.blackrepo.com/$repo/os/$arch
> 
> # Italy
> Server = http://blackarch.mirror.garr.it/mirrors/blackarch/$repo/os/$arch
> 
> # Japan
> Server = http://www.ftp.ne.jp/Linux/packages/blackarch/$repo/os/$arch Server = https://www.ftp.ne.jp/Linux/packages/blackarch/$repo/os/$arch Server = http://ftp.kddilabs.jp/Linux/packages/blackarch/$repo/os/$arch Server = https://ftp.kddilabs.jp/Linux/packages/blackarch/$repo/os/$arch
> 
> # Netherlands
> Server = http://mirror.serverion.com/blackarch/$repo/os/$arch Server = https://mirror.serverion.com/blackarch/$repo/os/$arch Server = http://mirror.neostrada.nl/blackarch/$repo/os/$arch Server = https://mirror.neostrada.nl/blackarch/$repo/os/$arch Server = ftp://mirror.neostrada.nl/blackarch/$repo/os/$arch
> 
> # New Zealand
> Server = http://nz-mirror.intergrid.com.au/blackarch/$repo/os/$arch
> 
> # Poland
> Server = http://ftp.icm.edu.pl/pub/Linux/dist/blackarch/$repo/os/$arch Server = https://ftp.icm.edu.pl/pub/Linux/dist/blackarch/$repo/os/$arch Server = ftp://ftp.icm.edu.pl/pub/Linux/dist/blackarch/$repo/os/$arch Server = gopher://ftp.icm.edu.pl/1/pub/Linux/dist/blackarch/$repo/os/$arch
> 
> # Russia
> Server = http://mirror.surf/blackarch/$repo/os/$arch Server = https://mirror.surf/blackarch/$repo/os/$arch Server = http://mirror.truenetwork.ru/blackarch/$repo/os/$arch Server = ftp://mirror.truenetwork.ru/blackarch/$repo/os/$arch Server = http://mirror.yandex.ru/mirrors/blackarch/$repo/os/$arch Server = ftp://mirror.yandex.ru/mirrors/blackarch/$repo/os/$arch
> 
> # Singapore
> Server = http://download.nus.edu.sg/mirror/blackarch/$repo/os/$arch Server = https://download.nus.edu.sg/mirror/blackarch/$repo/os/$arch
> 
> # Sweden
> Server = http://mirror.zetup.net/blackarch/$repo/os/$arch Server = https://mirror.zetup.net/blackarch/$repo/os/$arch
> 
> # Switzerland
> Server = http://mirror.easyname.ch/blackarch/$repo/os/$arch Server = ftp://mirror.easyname.ch/blackarch/$repo/os/$arch Server = https://mirror.tillo.ch/ftp/blackarch/$repo/os/$arch Server = http://mirror.tillo.ch/ftp/blackarch/$repo/os/$arch Server = ftpes://mirror.tillo.ch/blackarch/$repo/os/$arch Server = ftp://mirror.tillo.ch/blackarch/$repo/os/$arch
> 
> # Turkey
> Server = http://ftp.linux.org.tr/blackarch/$repo/os/$arch Server = https://ftp.linux.org.tr/blackarch/$repo/os/$arch Server = ftp://ftp.linux.org.tr/blackarch/$repo/os/$arch
> 
> # Taiwan
> Server = http://blackarch.cs.nctu.edu.tw/$repo/os/$arch
> 
> # UK
> Server = http://mirrors.gethosted.online/blackarch/$repo/os/$arch Server = https://mirrors.gethosted.online/blackarch/$repo/os/$arch
> 
> # USA
> Server = http://blackarch.pr0s3c.nl/blackarch/$repo/os/$arch Server = https://blackarch.pr0s3c.nl/blackarch/$repo/os/$arch Server = http://mirror.math.princeton.edu/pub/blackarch/$repo/os/$arch Server = http://distro.ibiblio.org/blackarch/$repo/os/$arch Server = ftp://distro.ibiblio.org/blackarch/$repo/os/$arch Server = https://deadbeef.ninja/blackarch/$repo/os/$arch Server = http://mirror.team-cymru.com/blackarch/$repo/os/$arch Server = ftp://mirror.team-cymru.com/blackarch/$repo/os/$arch

note: this is just the raw file unfiltered I.e just not sure which one is most responsive one, gonna try more testing and if affirmatively successful, gonna reply ASAP

**Comment by ikstream** [comment]
Reflector uses the Arch mirrorlist only. Use rank-mirrors instead.
