### ISSUE TITLE
[Tool request] airgeddon

### ISSUE THREAD

**Issue by OscarAkaElvis** [BlackArch/blackarch#1265]
https://github.com/v1s1t0r1sh3r3/airgeddon

**Comment by noptrix** [comment]
thanks ; added and released.

**Comment by OscarAkaElvis** [comment]
Hi, I downloaded the newest 2017.01.28 version and I can't see airgeddon on menues... after some searching, I saw is available using cli on its version 5.14. So thanks.

Anyway, new 6.0 airgeddon version with BeEF integrated was released recently. Maybe could be nice to update it for future versions.

I tried to run BeEF only for curiosity and it seems is not working on 2017.01.28 version ran as a Live. After launch beef command it says "Could not find gem 'therubyracer (= 0.11.3)' in any of the gem sources listed in your Gemfile. Ohh, I know ruby gems are a "pain in the ass", I'm only informing. This should be nice to have for airgeddon 6.0 in the future.

Thank you for your effort.

**Comment by noptrix** [comment]
hi. thx for this. we will bump airgeddon to 6.0. and for beef on the live iso, try this: get connected to internet and then go to /usr/share/beef and run 'bundle update'

**Comment by OscarAkaElvis** [comment]
Nice! thank you.

One last thing... starting airgeddon, the tools check shows there is an optional tool not included in BlackArch. Is for the `unbuffer` command. It is included in a package called `expect` or `expect-dev` (not sure now, one of these two for Arch). It would be nice to have all the needed tools installed directly, not sure if this is possible.

Thanks again!

**Comment by OscarAkaElvis** [comment]
Hi. Version 6.1 of airgeddon was released. The script was getting too big and it was splitted into different files, so there is file structure changes. I saw your PKGBUILD file and must be updated for v6.1.

There a new markdown file "CONTRIBUTING.md" maybe you want to handle in the same way like LICENSE.md and airgeddon.sh now needs to work language_strings.sh and optionally known_pins.db.

Anyway, airgeddon validates everything and download from github necessary files to work. But could be good idea to add them directly for v6.1

P.S. Tell me if you want this thread to talk about this or about any airgeddon change or if you prefer mail. 

Thank you.

**Comment by OscarAkaElvis** [comment]
Hi, airveddon v6.2 was released and it has a new folder for packages/binaries for some distros. It has a kali .deb package and an AUR file for Arch. I think you can remove that folder after the git clone because they will take some size and in the future will be larger (it keeps legacy installers too). If you agree, I can do the needed pull requests to maintain airgeddon package updated deleting new possible unneeded files and that kind of stuff. What do you think?

Very soon v7 is incoming, no structural changes but it will have very good new stuff! thanks.
