### ISSUE TITLE
veil ??

### ISSUE THREAD

**Issue by lexlutorr** [BlackArch/blackarch#1268]
whats the poing of having veil evasion when it doesnt have support && doesnt work ?

**Comment by lsfxz** [comment]
If you feel adventurous, feel free to try the veil from my PR #1271, or try the prebuilt package from [my repo](https://github.com/lsfxz/blackarch-ruby), and tell me about things that still need to be fixed.

**Comment by noptrix** [comment]
@lexlutorr veil has been fixed now thanks to @lsfxz. please run -Syyu to get the updated the version.
