### ISSUE TITLE
Xplico new update required in a few days

### ISSUE THREAD

**Issue by M0Rf30** [BlackArch/blackarch#1278]
not to criticize, but could I suggest my PKGBUILD? I'm following the development of xplico project for years and now xplico.install and PKGBUILD require some changes.
An example:

geoip-citydata it's not an existing optdep
It's clear that I don't want quotes or honours, but for a truly spirit of partecipation. Take a look here https://github.com/M0Rf30/PKGBUILD/tree/master/xplico

**Comment by noptrix** [comment]
thank you. we will review your pkgbuild and stick to it :)

**Comment by noptrix** [comment]
ok, so we've included your xplico.install and adjusted the PKGBUILD according to yours. should be fine now :)
