### ISSUE TITLE
warning: cannot resolve "ruby<2.4", a dependency of "metasploit"

### ISSUE THREAD

**Issue by mindrunner** [BlackArch/blackarch#1283]
Hey Folks
I am trying to install blackarch (my first time). Many packages depend on metasploit, which depends on ruby<2.4. However, Ruby was updated to 2.4 in December. I did not find an open issue for this here. I think, the whole installation is broken at the moment (or maybe I am overlooking something).

Installing ruby2.3 package does not help.

Installing metasploit-git (which uses ruby 2.4) does not help either.

Is there any workarounds? How can we get this running again?

**Comment by noptrix** [comment]
we've to wait for upstream to fix this issue. both, ruby and msf are not handbled by us. what you can try (i didn't try it yet): install ruby < 2.4 and then pacman -Syyu --needed --force blackarch --ignore ruby. another option would be to ignore metasploit and its dependencies and install the rest.

**Comment by noptrix** [comment]
also, maybe it would be good idea to open this ticket @ ArchLinux ;)

**Comment by noptrix** [comment]
13:06:23 <@paraxor> it's already been flagged as out of date
13:06:25 <@paraxor> yesterday
-> https://www.archlinux.org/packages/?q=metasploit
so i think one or two days they should fix it ;)

**Comment by mindrunner** [comment]
> install ruby < 2.4 

how exactly can I do that? I am little new to arch. (coming from gentoo). As far as I can see, there is nothing like slots for packages. I can only see ruby2.3 package?

**Comment by noptrix** [comment]
@mindrunner just ignore now everything and wait until archlinux released new metasploit package. you can follow it here: https://www.archlinux.org/packages/?q=metasploit

**Comment by mindrunner** [comment]
Cool, I will just wait. Thanks for quick help!

**Comment by noptrix** [comment]
no problem. yeah should be updated today/tomorrow ... not in weeks or months ;)

**Comment by mindrunner** [comment]
Looks like something bigger...

https://bugs.archlinux.org/task/52519?project=5&cat%5B0%5D=33&string=metasploit
https://github.com/rapid7/metasploit-framework/issues/7814
https://github.com/rapid7/metasploit-framework/pull/7819

**Comment by ChrisFernandez** [comment]
yeah this has to come from upstream rapid7

**Comment by cyberchinya** [comment]
Hi! 
./msfconsole 
/usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
/usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:124:in `block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError)
	from /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /usr/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	 ... 4682 levels...
	from /root/git/metasploit-framework/lib/metasploit/framework/command/base.rb:69:in `parsed_options'
	from /root/git/metasploit-framework/lib/metasploit/framework/command/base.rb:47:in `require_environment!'
	from /root/git/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
	from ./msfconsole:48:in `<main>'

How to fix it????

**Comment by mindrunner** [comment]
Looks better today. Problem seems to be solved. :)
