### ISSUE TITLE
[Tool Request] pacaur instead of yaourt

### ISSUE THREAD

**Issue by kcolford** [BlackArch/blackarch#1286]
`yaourt` sources arbitrary `PKGBUILD`s whereas `pacaur` uses the aur metadata, to improve security pacaur should be made available and yaourt removed (users of yaourt can still update from the AUR)

**Comment by noptrix** [comment]
yeah, i use pacaur as well. i wanted to add it. thanks for reminding. will be added.

**Comment by ChrisFernandez** [comment]
+1

**Comment by NovaCygni** [comment]
Suggestion: Remove nothing and just ADD pacaur for the people who wish to use it, some of us prefer yaourt (* after some tinkering :) *)

**Comment by PedroSFreitas** [comment]
I'm with @NovaCygni on this and removing anything sounds like a bad idea. Let's leave both and users can choose what they want.

**Comment by ChrisFernandez** [comment]
@PedroSFreitas @noptrix @NovaCygni I agree, just add both.. I think the pain is to have to install either of them after the main blackarch install, to have it available from the start is a relieve.
