### ISSUE TITLE
Create metapackages in addition to groups

### ISSUE THREAD

**Issue by kcolford** [BlackArch/blackarch#1291]
Rather than just installing by group, add metapackages so that new packages automatically get installed.

You can have packages that are just the group name suffixed with `-meta`, that way you can also easily add scripts to generate theses packages.

**Comment by noptrix** [comment]
very good point. thanks and we will working on this.

**Comment by Edu4rdSHL** [comment]
I want to know what exactly is the advantage using metapackages in addition to groups, if you want new tools installed just use `pacman -Syu --overwrite='*' blackarch` or install the group where the package was installed.
