### ISSUE TITLE
Duplicated databases entry

### ISSUE THREAD

**Issue by MarianoPrz** [BlackArch/blackarch#1294]
Hi! im getting this error...

[ blackarch ~ ]# pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 blackarch                                                                                1694.4 KiB  94.3K/s 00:18 [######################################################################] 100%
 blackarch.sig                                                                             566.0   B  0.00B/s 00:00 [######################################################################] 100%
 multilib is up to date
:: Starting full system upgrade...
error: duplicated database entry 'pacman-mirrorlist'
error: duplicated database entry 'libutil-linux'
error: duplicated database entry 'sqlite'
error: duplicated database entry 'xz'
error: duplicated database entry 'flex'
error: duplicated database entry 'm4'
error: duplicated database entry 'lz4'
error: duplicated database entry 'gmp'
error: duplicated database entry 'libnftnl'
error: duplicated database entry 'dhcpcd'
error: duplicated database entry 'sudo'
error: duplicated database entry 'libtool'
error: duplicated database entry 'mpfr'
error: duplicated database entry 'zlib'
error: duplicated database entry 'systemd-sysvcompat'
error: duplicated database entry 'libarchive'
error: duplicated database entry 'systemd'
error: duplicated database entry 'libgpg-error'
error: duplicated database entry 'curl'
error: duplicated database entry 'libelf'
error: duplicated database entry 'archlinux-keyring'
error: duplicated database entry 'nano'
error: duplicated database entry 'libsystemd'
error: duplicated database entry 'gnutls'
error: duplicated database entry 'libldap'
error: duplicated database entry 'util-linux'
error: duplicated database entry 'sed'
warning: python-editdistance: local (0.3.1-2) is newer than extra (0.3.1-1)
resolving dependencies...
looking for conflicting packages...

------------------------
 including ruby 2.4 issue, i cant resolve this, in the arch forums i havent found a solution and i tried most , anyone have the same issue? i did a fresh install and the problem persists

**Comment by lsfxz** [comment]
I vaguely remember having this problem when setting up BlackArch from the BlackArch ISO and installing offline, ie. not pulling the packages from the repos.
I totally forgot about it so never investigated further. If you installed "offline", you might try doing a fresh online-install –  if that fixes the duplicate database entry issues you might want to open an issue on BlackArch/blackarch-installer.

Might be totally unrelated, of course – sorry I can't help more.

**Comment by MarianoPrz** [comment]
thanks for replying!, i never installed it offline, because if you haven't connection to internet the installer doesn't allow you to continue... hopefully someone have resolved it, i visited all archlinux forums and in each thread no one have a solution, thanks again fo replying, greetings

**Comment by heichblatt** [comment]
Does this help you?
https://mayankjohri.wordpress.com/2014/10/06/tips-arch-linux-how-to-resolve-error-duplicated-database-entry-error-message/
