### ISSUE TITLE
Key could not be looked up remotely

### ISSUE THREAD

**Issue by MatheusViGo** [BlackArch/blackarch#1295]
When i try update system with -Syyu appear that key 77193F152BDBE6A6 is missing.

**Comment by MatheusViGo** [comment]
![virtualbox_blackarch linux_18_01_2017_14_11_33](https://cloud.githubusercontent.com/assets/17281717/22072000/0eb3c30e-dd88-11e6-8049-fe2393582fc6.png)

**Comment by ikstream** [comment]
Have you tried to reinstall archlinux-keyring or refreshing your keyring

**Comment by MatheusViGo** [comment]
Yes and still not working

**Comment by MatheusViGo** [comment]
I already reinstall archlinux and blackarch keyring, gnupg, try pacman-key init, refresh and not work

**Comment by ikstream** [comment]
you could try to use 
> \# pacman-key -r 77193F152BDBE6A6

if this does not work you could try to change your keyserver

**Comment by MatheusViGo** [comment]
I reinstalled the system using OVA image and update with pacman -Syyu --needed --force blackarch and works.

**Comment by noptrix** [comment]
kewl! thanks for the info
