### ISSUE TITLE
Live install fails at error:failed to mount /dev/loop0

### ISSUE THREAD

**Issue by redcorpshell** [BlackArch/blackarch#1296]
Tell me how to make a live boot usb.I did with many tools,changed to many flash drives no way.
If you have any suggestions regarding usb making pls tell me.
One of the thing i've encountered is that while seeing rufus log 'airootfs.sfs' named file under live iso "\blackarch\x86_64\", while writing blackarch linux on to usb,this file is encountered with a problem of replication because 6.2Gb is splitted to 4.0Gb and 2.1Gb respectively while it is being written on usb by rufus and eventually they are replaced by one another.This is happening while on most of Usb boot maker tools.
I hope anyone would let me know how to prepare a bootable live usb for booting blackarch linux without any errors.thanks in advance.

**Comment by mikeybro** [comment]
can't use rufus , have to use another linux distro to mount ISO with the "#
Example Image writing
$ sudo dd bs=512M if=file.iso of=/dev/sdx

*Ubuntu worked as well as fedora, I am sure you have a usable linux machine
in handy... Right?*

*References:*
*1. https://www.blackarch.org/downloads.html
<https://www.blackarch.org/downloads.html>*

**Comment by redcorpshell** [comment]
Thanks Bro, I'll check it and see the results as soon as possible. Yeah..i'd have an Ubuntu Mate linux installed on another system.thanks for your cooment.
