### ISSUE TITLE
[Tool request] DependencyCheck

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#1299]
https://github.com/jeremylong/DependencyCheck

**Comment by noraj** [comment]
@Edu4rdSHL What are all the issue from 2017 that you tagged as WIP?

**Comment by Edu4rdSHL** [comment]
@noraj WIP = Work In Progress, mean that the tool will be added to BA.

**Comment by noraj** [comment]
@Edu4rdSHL Yeah, I know WIP stands for Work In Progress, but I thought you were working on it since 2017. So if nobody is actually working on it I'd rather tag them as tool request.

**Comment by Edu4rdSHL** [comment]
The label was added in Jul 28 of it year and I'm working on it, please don't removed the label.

**Comment by noraj** [comment]
@Edu4rdSHL Oops sorry I misunderstood you

**Comment by noptrix** [comment]
added thanks to @osmanercelik
