### ISSUE TITLE
Add an uninstall option for blackman

### ISSUE THREAD

**Issue by dehein** [BlackArch/blackarch#1301]
Blackman has no option to remove the installed packages. Would be great to know how to easily remove a cluttered installation on my standard arch linux.

**Comment by karlguy** [comment]
I think the easiest was to do this as of now is to do pacman -Qm to list all packages not installed from a repository, which includes blacman packages and aur packages, and save the output to a text file, where you can edit out all the packages you want to keep. Then you can pipe that text file into pacman -Rsn to remove all the packages on the list.

So it would look like:
`pacman -Qm > packages.txt`
`#remove the packages from the list that you want to keep (ie yaourt)`
`cat packages.txt | cut -f 1 -d " " | xargs sudo pacman --no-confirm -Rsn`

**Comment by noptrix** [comment]
we will work on a new blackman version. rewrite it completely.
