### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by gloopers** [BlackArch/blackarch#1305]
when I try to pacman -Syu I get the following error

> error: could not extract /usr/lib/libgfortran.so.3.0.0 (Write failed)
error: could not extract /usr/lib/llibcilkrts.so.5.0.0 (Write failed)
error: could not extract /usr/lib/llibatomic.so.1.2.0 (Write failed)
error: could not extract /usr/lib/llibgcc_s.so (Write failed)
error: could not extract /usr/lib/libgcc_s.so.1 (Write failed)
error: could not extract /usr/share/locale/de/LC_MESSAGES/libstdc++.mo (Write failed)
error: could not extract /usr/share/locale/fr/LC_MESSAGES/libstdc++.mo (Write failed)
error: could not extract /usr/share/info/libgomp.info.gz (Write failed)
error: could not extract /usr/share/info/libitm.info.gz (Write failed)
error: could not extract /usr/share/info/libquadmath.info.gz (Write failed)
error: could not extract /usr/share/licenses/gcc-libs/RUNTIME.LIBRARY.EXCEPTION (Write failed)
error: problem occurred while upgrading gcc-libs
error: could not commit transaction
error: failed to commit transaction (transaction aborted)
Errors occurred, no packages were upgraded.

**Comment by heichblatt** [comment]
Seems your disk or filesystem are full or damaged. What's the output of `df -h /usr/lib/`?
