### ISSUE TITLE
[Bug] python2-pefile package cannot parse the default userdb.txt

### ISSUE THREAD

**Issue by straumer** [BlackArch/blackarch#1311]
I installed the packerid package and there was a problem with parsing the signatures database, in effect making it unusable with the default PEiD database. Tracked down the problem to a code section in python2-pefile package which is fixed in https://github.com/erocarrera/pefile.

**Comment by m73** [comment]
Actually. This seems to be a bigger issue of the /usr/share/packerid/userdb.txt having many new non-hex characters in the bytes and that pefile has not kept up with those. Updating the package won't fully solve this then I believe.

**Comment by m73** [comment]
Ok, the conclusion is that the default userdb.txt file is malformed or requires some more advanced parsing mechanism than packerid can handle. I took the userdb.txt from Remnux and it worked fine. So: just switch the file out for a new one in the packerid package. :)

**Comment by noptrix** [comment]
again please, whats' needed to change here?

**Comment by m73** [comment]
The default file /usr/share/packerid/userdb.txt needs to change. I know the one Remnux uses works.

**Comment by m73** [comment]
Essentially, the program crashes when no alternative db is chosen.

**Comment by noptrix** [comment]
should be fixed
