### ISSUE TITLE
can't install on top of arch linux 

### ISSUE THREAD

**Issue by ashishbishnoi** [BlackArch/blackarch#1313]
error: failed retrieving file 'machinae-63.0d73101-2-any.pkg.tar.xz' from www.mirrorservice.org : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed retrieving file 'mitmap-1:0.1-2-any.pkg.tar.xz' from www.mirrorservice.org : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed retrieving file 'proctal-186.0b7d13a-1-x86_64.pkg.tar.xz' from www.mirrorservice.org : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed retrieving file 'voltron-571.8723d32-1-any.pkg.tar.xz' from www.mirrorservice.org : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed retrieving file 'xssya-1:12.abe1aec-3-any.pkg.tar.xz' from www.mirrorservice.org : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.

**Comment by noptrix** [comment]
see irc ...
