### ISSUE TITLE
Installation wifi error.

### ISSUE THREAD

**Issue by Xerdnapn** [BlackArch/blackarch#1314]
I've been trying to follow the instructions [here](https://blackarch.org/blackarch-install.html) in order to install black arch as the main OS for a small netbook (Gateway LT2805u). Everything boots from the USB pretty well until I'm at the step where I'm required to connect to a network in order for Pacman to get to the repos. 

Like DokiTeeX in issue #1196 , my connection will stay stable for a second before disconnecting.  As you can guess this kind of stops the whole installation process.  

Any assistance here would be greatly appreciated.

**Comment by heichblatt** [comment]
Any logs, any details? What does `dmesg` tell you?

**Comment by Xerdnapn** [comment]
I have some screenshots describing the output on `dmesg`  and `lspci -k' but` they are numerous as I had to use my phone. Is there a specific line you were looking for?

I know the wireless card for this laptop is a mini Atheros. I checked the Arch Linux wiki, and have been trying to follow along with `netctl` and wifi radar to no avail.

**Comment by mikeybro** [comment]
Would this help? 
https://wiki.archlinux.org/index.php/dhcpcd

Sent mobile tracking device

**Comment by heichblatt** [comment]
Anything related to networking from dmesg or journalctl for netctl would help. I'm not looking for anything specific, just trying to localize the exact problem.

**Comment by Xerdnapn** [comment]
I've tried a direct connection via ethernet, as well as via usb connection with an ALFA long range adapter with the same results. Mikeybro I will attempt `dhcpcd` today, do you know if it has any configurations specifically for mini atheros chips?

**Comment by NovaCygni** [comment]
Your wireless device likely is using the wrong/bad drivers, please find out which chipset your wireless device is using, ie, if its the ALFA AC series USB wireless devices, itll be the 8812au drivers in the AUR, yourll be wanting the "Monitor mode drivers" version of it... install the drivers then `sudo modprobe 8812au` and you should be good to go.
