### ISSUE TITLE
how to make live bootable usb of blackarch linux

### ISSUE THREAD

**Issue by hp040** [BlackArch/blackarch#1318]
Here in this video you can learn how to make **live bootable usb of blackarch linux (HACKING OS)** or any other linux in 5 min easily https://youtu.be/OC6fBgmA_zI

**Comment by heichblatt** [comment]
Hi hp040,

thanks for letting us know, but since this doesn't represent a problem you have with BlackArch, I'm closing this issue.

Cheers

**Comment by Beyarz** [comment]
The video is down.
