### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by dusanjolovic** [BlackArch/blackarch#1323]
Every command I try to run is not found.
[ blackarch Desktop ]# msfconsole
bash: msfconsole: command not found
Please don't close and resplond me.

**Comment by heichblatt** [comment]
Did you install the package providing the command?

**Comment by dusanjolovic** [comment]
I'm not sure ... Can I fix this now , after installing ?

**Comment by heichblatt** [comment]
Install metasploit, which provides the command.

`yaourt -Sy metasploit`
