### ISSUE TITLE
[Tool request] FruityWifi

### ISSUE THREAD

**Issue by helspa** [BlackArch/blackarch#1355]
https://github.com/xtr4nge/FruityWifi

**Comment by Edu4rdSHL** [comment]
Thanks, I'm working on it and will be added today.

**Comment by noraj** [comment]
@Edu4rdSHL Did you release this one?

**Comment by kinggx9** [comment]
> Cảm ơn, tôi đang làm việc với nó và sẽ được thêm vào ngày hôm nay.

I am very interested in what you do.
Thanks for your effort.
