### ISSUE TITLE
[Tool request] DeepViolet

### ISSUE THREAD

**Issue by helspa** [BlackArch/blackarch#1359]
https://github.com/spoofzu/DeepViolet

**Comment by Edu4rdSHL** [comment]
THIS PROJECT IS NOT BEING ACTIVELY MAINTAINED. I DON'T RECOMMEND THE IT BE USED FOR ANYTHING IMPORTANT; HOWEVER, IT REMAINS AVAIABLE FOR ARCHIVAL PURPOSES. THIS PROJECT WAS A FUN EXPERIMENT AND IT WAS EXCITING TO SHARE IT WITH EVERYONE. AT THIS TIME, I'M PLACING MY TIME AND ENERGY INTO OTHER AREAS. JUN 27, 2019 --MILTON

From https://github.com/spoofzu/DeepViolet/blob/master/README.md
