### ISSUE TITLE
[Tool request] FakeNet-NG

### ISSUE THREAD

**Issue by helspa** [BlackArch/blackarch#1361]
https://github.com/fireeye/flare-fakenet-ng

**Comment by PedroSFreitas** [comment]
@helspa 
**From the README:**
> FakeNet-NG is a next generation dynamic network analysis tool for malware analysts and penetration testers. It is open source and designed for the latest versions of Windows (and Linux, for certain modes of operation).

Which modes are we talking about on Linux?

**Comment by mrsmith0x00** [comment]
@helspa already added, thanks!
