### ISSUE TITLE
A lot of the tools in the repository don't work

### ISSUE THREAD

**Issue by karlguy** [BlackArch/blackarch#1530]
When trying to install on top of arch, a huge number of packages have broken dependencies (mostly python and ruby), making them not work. Did I do something wrong, or there just work that needs to be done on it?

**Comment by MatheusViGo** [comment]
Be more specific, however I think that more work is really needed as well.

**Comment by karlguy** [comment]
Yeah sorry, when I get the time I will try to document some of the issues, but I just wanted to make sure I wasn't missing something.

**Comment by noptrix** [comment]
@karlguy please use the '--force' option
