### ISSUE TITLE
[Error] Package Mitmf 

### ISSUE THREAD

**Issue by MatheusViGo** [BlackArch/blackarch#1536]
When executed show this error message:
"""Traceback (most recent call last):
  File "mitmf.py", line 170, in <module>
    from core.servers.DNS import DNSChef
  File "/usr/share/mitmf/core/servers/DNS.py", line 45, in <module>
    from dnslib import *
ImportError: No module named dnslib"""

#Repository updated and all dependencies satisfated

**Comment by noptrix** [comment]
thanks. fixed and released

**Comment by MatheusViGo** [comment]
Cool, thanks !
