### ISSUE TITLE
[OutOfDate] Package Lynis 

### ISSUE THREAD

**Issue by MatheusViGo** [BlackArch/blackarch#1537]
Version in repository is 2.4.2 and have already released versions 2.4.3 and 2.4.4
https://github.com/CISOfy/lynis/releases

**Comment by noptrix** [comment]
it's maintained by upstream/arch linux not by us. sorry. maybe do a 'out of date'-flag at archlinux.org. they will bump version

**Comment by MatheusViGo** [comment]
Ok.

**Comment by MatheusViGo** [comment]
I will report.
