### ISSUE TITLE
[OutOfDate] Package Metasploit 

### ISSUE THREAD

**Issue by MatheusViGo** [BlackArch/blackarch#1546]
The version in the repository is 4.13.22 and the latest version is 4.14, and has already released the earlier versions 4.13.23, 4.13.24, 4.13.25 and 4.13.26.

#https://github.com/rapid7/metasploit-framework/releases

**Comment by nil0x42** [comment]
metasploit package maintenance is now owned by community repository

**Comment by MatheusViGo** [comment]
Ok !
