### ISSUE TITLE
[Error] Hercules-payload

### ISSUE THREAD

**Issue by Y0lan** [BlackArch/blackarch#1548]
Apparently it miss the file:
 `/usr/bin/hercules-payload: line 3: /usr/share/hercules-payload/SOURCE/HERCULES: No such file or directory`

Tried adding directly from the github page the following:

`#!/bin/bash

cd $HERCULES_PATH
cd SOURCE
./HERCULES`

in `/usr/bin/hercules-payload/SOURCE/` but it didn't work, i guess it need to be adapted to arch. Or I don't know.

Cordially,

yolan

**Comment by noptrix** [comment]
thx for reporting. this is fixed now.
