### ISSUE TITLE
Dual Boot Blackarch and Windows

### ISSUE THREAD

**Issue by sreerajsiva** [BlackArch/blackarch#1550]
Please provide. Instructions to install blackarch after a windows installation . My windows won't. Boot up after I tried the black arch install

**Comment by fnk0c** [comment]
Have you read the [Arch Linux wiki](https://wiki.archlinux.org/index.php/Dual_boot_with_Windows)?

**Comment by sreerajsiva** [comment]
i think there is no option to dual boot blackarch along with windows versions especially in my case uefi

**Comment by cryptocohen** [comment]
this helped me figure it out...

https://gist.github.com/mattiaslundberg/8620837

you have to scroll down in the comments to find this:

grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=grub

you will know when you get to it.
