### ISSUE TITLE
[Error] Package Xerosploit

### ISSUE THREAD

**Issue by MatheusViGo** [BlackArch/blackarch#1558]
When executed show this error message: 
"""Traceback (most recent call last):
  File "xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables"""

#Repository updated and all dependencies satisfated

**Comment by noptrix** [comment]
thanks for reporting this!. added missing dependencies and released the fixed version.

**Comment by MatheusViGo** [comment]
Ok, thanks !
