### ISSUE TITLE
a start job is running during boot

### ISSUE THREAD

**Issue by mikeybro** [BlackArch/blackarch#1564]
I have tried to figure out what this issue is, searching the arch wiki and using google.  During the start up:

**Started Load/Save RF Kill Switch Status
Started Initializes Pacman keyring
A start job is running for sys-subsytem-net-devices-en\x2dany.device( __s /1min 30s)**

Since I am unsure as to how to go about resolving this can someone point in the right direction, Noob here sorry.

I've tried looking for any boot config files, and tried to better understand the boot process:
 
1. https://wiki.archlinux.org/index.php/Arch_boot_process
2. https://bbs.archlinux.org/viewtopic.php?id=166104
3.  Google searched : arch boot keyring/arch started initializes pacman keyring

Can't seem to understand.

**Comment by ikstream** [comment]
Have you tried
'grep -ir <interface> /etc/systemd/*' 
From the link you posted?
Interface would be en for you.
This looks to me like a systemd file has a wrong interface name in it? What is the name of your Ethernet device?

**Comment by mikeybro** [comment]
I opened up /etc/systemd/system.netctl@dhcp1.service

```
1.  .include /usr/lib/systemd/system/netctl@.service
2.
3.[Unit]
4.Description=Connection to router via enp0s25 "Which is  my interface"
5.BindsTo=sys-substem-net-devices-en\x2dany.device
6.After=sys-subsystem-net-devices-en\x2dany.device
```

**Comment by ikstream** [comment]
i am not sure with the "\x2dany.device". I'm not using netctl so i am not sure how this should be set.
Do you use or have you tried `netctl-ifplugd@enp0s25.service` for auto dhcp on connection?
Does `systemctl --failed` show something?

**Comment by mikeybro** [comment]
I solved the problem, I am not sure if this was the correct way and I also have no idea what effect this will have,
I simply removed the file "system.netctl@dhcp1.service" from : 
/etc/systemd/system 
   

And the machine boots up almost instantly, I just moved that file to my desktop for the moment and can replace it back into the directory, any idea if this is a good permanent fix? I think I am going to take a break from the arch wiki's for now. Here are some references:
https://freedesktop.org/wiki/Software/systemd/Debugging/#shutdowncompleteseventually
https://wiki.archlinux.org/index.php/systemd#Investigating_systemd_errors
https://bbs.archlinux.org/viewtopic.php?id=170944
https://bbs.archlinux.org/viewtopic.php?id=163957
And of course this source

**Comment by ikstream** [comment]
Do you use something else for dhcp now?
Is systemctl --failed showing this unit as missing?
