### ISSUE TITLE
Vinetto error

### ISSUE THREAD

**Issue by noraj1337** [BlackArch/blackarch#1574]
I guess that vinetto crash when there is an unrecognized header. It seems to do it with every Thumbs.db files. I can't open an issue on vinetto as [the project](http://vinetto.sourceforge.net/) is dead.

```
$ vinetto Thumbs.db
Traceback (most recent call last):
  File "/usr/bin/vinetto", line 114, in <module>
    tDBfname, outputdir, htmlrep, utf8encoding, symlinks = getargs()
  File "/usr/bin/vinetto", line 77, in getargs
    os.system("mkdir " + opts.outputdir + "/" + NUMBERED_THUMBS_DIR)
TypeError: cannot concatenate 'str' and 'NoneType' objects

$ vinetto -o /tmp/test Thumbs.db
mkdir: cannot create directory ‘/tmp/test/.thumbs’: No such file or directory
Note:  /tmp/test  was created

 Root Entry modify timestamp : Wed Jan 25 01:08:05 2017

 ------------------------------------------------------

 *** Err: unrecognized header in stream 1
```

**Comment by jose1711** [comment]
works for me

**Comment by noraj1337** [comment]
Maybe this can help:

```
Python 2.7.13 (default, Dec 21 2016, 07:16:46) 
[GCC 6.2.1 20160830] on linux2
```

**Comment by jose1711** [comment]
can you make that Thumbs.db file public?

**Comment by aancw** [comment]
This is telling you that some of string is not str type. So python can't concate str and NoneType. You can make change with `str(name_of_string)` and try again. If this work, you can PR to original repository.

```
$ vinetto Thumbs.db
Traceback (most recent call last):
  File "/usr/bin/vinetto", line 114, in <module>
    tDBfname, outputdir, htmlrep, utf8encoding, symlinks = getargs()
  File "/usr/bin/vinetto", line 77, in getargs
    os.system("mkdir " + opts.outputdir + "/" + NUMBERED_THUMBS_DIR)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

CMIIW

**Comment by noraj1337** [comment]
@jose1711 : I can't. But I tried with multiple different Thumbs.db available publicly.

@aancw : I replaced `os.system("mkdir " + opts.outputdir + "/" + NUMBERED_THUMBS_DIR)` with `os.system("mkdir " + str(opts.outputdir) + "/" + NUMBERED_THUMBS_DIR)`, and the normal behaviour occured:

```
 Root Entry modify timestamp : Wed Jan 25 01:08:05 2017

 ------------------------------------------------------

 *** Err: unrecognized header in stream 1
```

However I the initial project at [Sourceforge](https://sourceforge.net/projects/vinetto/)  seems dead since 2008.

**Comment by jose1711** [comment]
please test and report results back with this file: https://freeshell.de/~jose1711/donotdelete/Thumbs.db

**Comment by noraj1337** [comment]
I opened a bug on vinetto sourceforge anyway : https://sourceforge.net/p/vinetto/bugs/9/

**Comment by noraj1337** [comment]
@jose1711 with https://freeshell.de/%7Ejose1711/donotdelete/Thumbs.db : 

```
$ vinetto Thumbs.db                                                                                                                                                                                               
mkdir: cannot create directory ‘None/.thumbs’: No such file or directory

 Root Entry modify timestamp : Fri Dec 22 17:36:03 2006

 ------------------------------------------------------

 0001   Fri Dec 22 17:35:55 2006   {A42CD7B6-E9B9-4D02-B7A6-288B71AD28BA}

 ------------------------------------------------------
```

**Comment by jose1711** [comment]
ok, hence success. well.. apparently the format of Thumbs.db changed - I may have only files generated by WinXP locally

**Comment by aancw** [comment]
Hm.... is that mean need new Thumbs.db file @jose1711 ?

**Comment by aancw** [comment]
Hi guys, i think this is because outputdir is None.

```
$ vinetto Thumbs.db
Traceback (most recent call last):
  File "/usr/bin/vinetto", line 114, in <module>
    tDBfname, outputdir, htmlrep, utf8encoding, symlinks = getargs()
  File "/usr/bin/vinetto", line 77, in getargs
    os.system("mkdir " + opts.outputdir + "/" + NUMBERED_THUMBS_DIR)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

It's already str if outputdir not empty. But if we forced to str will be `None`

```
$ vinetto Thumbs.db                                                                                                                                                                                               
mkdir: cannot create directory ‘None/.thumbs’: No such file or directory

 Root Entry modify timestamp : Fri Dec 22 17:36:03 2006

 ------------------------------------------------------

 0001   Fri Dec 22 17:35:55 2006   {A42CD7B6-E9B9-4D02-B7A6-288B71AD28BA}

 ------------------------------------------------------
```

You just need add `-o` parameter for output directory:

```
[root@localhost vinetto-beta-0.07]# mkdir tes
[root@localhost vinetto-beta-0.07]# nano /usr/bin/vinetto -o tes
[root@localhost vinetto-beta-0.07]# vinetto Thumbs.db -o tes

 ** Warning: Cannot find "Image" module.
             Vinetto will only extract Type 2 thumbnails.


 Root Entry modify timestamp : Fri Dec 22 23:36:03 2006

 ------------------------------------------------------

 0001   Fri Dec 22 23:35:55 2006   {A42CD7B6-E9B9-4D02-B7A6-288B71AD28BA}

 ------------------------------------------------------

1 Type 2 thumbnails extracted to tes/
```

**Comment by noraj1337** [comment]
Of course this works with `-o` but vinetto must also works without args.

**Comment by jose1711** [comment]
i may have misunderstood the whole thing. when you use the `-o` switch - are the files created or not?

**Comment by noraj1337** [comment]
@jose1711 :
When using `-o` I get this error because this may be a Thumb.db from Win7 or Win8 or Win10 (newer than WinXP) so vinetto does't understand the hearder. But the issue was about having the python convertion error when using no arguments.
But if you have a way to solve this second issue I will be pleased.

**Comment by jose1711** [comment]
if you think it's supposed to extract into a current directory, you can try this supersimple patch:
```
--- vinetto.orig	2017-03-20 20:38:20.000000000 +0100
+++ vinetto	2017-03-20 20:57:55.442588565 +0100
@@ -74,6 +74,8 @@
         
     if (opts.outputdir == None) and (opts.htmlrep == True):
         parser.error("-H option requires -o with a directory name")
+    if opts.outputdir is None:
+        opts.outputdir = '.'
     os.system("mkdir " + opts.outputdir + "/" + NUMBERED_THUMBS_DIR)
     return (pargs[0], opts.outputdir, opts.htmlrep, opts.encoding, opts.symlinks) 
```

**Comment by aancw** [comment]
Nah you can use patch from @jose1711, i'm just explain how vinetto work with `outputdir` and `-o` parameter.

**Comment by noraj1337** [comment]
@jose1711 I also add you solution to the issue: https://sourceforge.net/p/vinetto/bugs/9/

I open a new issue for `unrecognized header`: https://sourceforge.net/p/vinetto/bugs/10/

**Comment by aancw** [comment]
I think this project is discontinue because Last Update: 2013-04-24
