### ISSUE TITLE
[DEAD PACKAGE] MultiInjector

### ISSUE THREAD

**Issue by aancw** [BlackArch/blackarch#1582]
Hey guys, link for MultiInjector.py(http://www.hybridsec.com/tools/multinjector/MultiInjector.py) is dead for MultiInjector package https://github.com/BlackArch/blackarch/blob/master/packages/multiinjector/PKGBUILD

Thanks

cc @noptrix

**Comment by noptrix** [comment]
thanks for reporting! we've added the py-file to the repository.
