### ISSUE TITLE
[faraday package] Beware! Faraday doesn't support CouchDB 2.0, use CouchDB 1.6!

### ISSUE THREAD

**Issue by nil0x42** [BlackArch/blackarch#1590]
In a recent pull request, i added some missing dependencies on faraday package, therefore, couchdb server still didn't run.
after looking at online documentation, i finally found what seems to cause the issue:
https://github.com/infobyte/faraday/wiki/Installation-Server

that page says:
    Beware! Faraday doesn't support CouchDB 2.0, use CouchDB 1.6!

now i m sad because blackarch's couchdb is already in version 2.0, so we'll need to wait for faraday to support this version, or perhaps someone was able to launche faraday server correctly, if so i'd like to know how, and package should be upgraded if there is some workaround

thanks

**Comment by konfou** [comment]
Actually couchdb is on Arch's community repo. Maybe add a couchdb1.6 package?

**Comment by nil0x42** [comment]
yes it would be very nice

**Comment by noptrix** [comment]
@nil0x42 is cdb-2.0 supported by faraday now? i didn't have the chance to look about this issue. totally missed it. sorry for the delay :)

**Comment by noraj** [comment]
#2360 PR opened for those who want to help
