### ISSUE TITLE
[request] timestamp file in repo root

### ISSUE THREAD

**Issue by fhdk** [BlackArch/blackarch#1601]
I am porting Manjaros pacman-mirrors for use with Blackarch but I miss a central validation point.

Something like the `lastupdate` file in Arch repo - a file with a timestamp in the repo root which can be compared to masterrepo at blackarch.org and thus decide if a mirror-repo is up-to-date.

**Comment by fhdk** [comment]
Have a look at it https://github.com/fhdk/blackman-mirrors

**Comment by noptrix** [comment]
cheers @fhdk - will address this and let you know

**Comment by mrsmith0x00** [comment]
@fhdk any update on this? :)

**Comment by fhdk** [comment]
Nope - I have heard zilch
