### ISSUE TITLE
Issue Services Pls Help!!!

### ISSUE THREAD

**Issue by TheGangALA** [BlackArch/blackarch#1602]
![capture](https://cloud.githubusercontent.com/assets/27391115/24986546/b52f441a-1faf-11e7-907a-44077d297394.PNG)
![capture](https://cloud.githubusercontent.com/assets/27391115/24986589/f69832cc-1faf-11e7-9648-76933085f173.PNG)

**Comment by ikstream** [comment]
What does journalctl tell you about the dhcp service?
what's the output of `systemctl status dhcpcd@ens32.service`?

**Comment by noptrix** [comment]
@ikstream Thanks a lot for the follow-ups, btw :) :+1:
