### ISSUE TITLE
Issue Root Access

### ISSUE THREAD

**Issue by TheGangALA** [BlackArch/blackarch#1603]
How can i get the root access?

![1](https://cloud.githubusercontent.com/assets/27391115/25023923/b5abde84-2050-11e7-951d-522ac4447ec8.PNG)
![capture](https://cloud.githubusercontent.com/assets/27391115/25023931/bd30921c-2050-11e7-8e31-d33644756e37.PNG)

**Comment by noahholley** [comment]
https://blackarch.org/blackarch-install.html

when you install the operating system you should set the root and user account with a password you specify.
