### ISSUE TITLE
[Tool request] rev.ng

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#1610]
https://rev.ng

**Comment by mrsmith0x00** [comment]
@vdun very good tool... But:
1. It require a lot of time for compiling (~18 GB).
2. If we build revamb without patches and specific version (3.8) of clang, it raise errors while compiling.
3. If we compile clang too, we should support two versions: one vanilla and two for rev.ng (same with qemu).

I apologize... Use it in Docker ;)
