### ISSUE TITLE
[Tool request] python-factordb-pycli

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#1615]
https://github.com/ryosan-470/factordb-pycli

**Comment by mrsmith0x00** [comment]
@vdun good stuff, but isn't pentesing tool.

**Comment by vdun** [comment]
It helps testing weak RSA keys.
Example: http://dann.com.br/alexctf2k17-crypto200-poor_rsa/

**Comment by mrsmith0x00** [comment]
@vdun sorry, now it's added, thanks a lot! ;)
