### ISSUE TITLE
Error failed to commit

### ISSUE THREAD

**Issue by Fly34567** [BlackArch/blackarch#1616]
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
What should I do I will attempting to install on antergos Linux.

**Comment by NovaCygni** [comment]
yaourt -S blackarch --force

**Comment by Fly34567** [comment]
Ok worked but not all tools display on menu.

**Comment by Fly34567** [comment]
Ok I say it worked altough some tools have some problem not all of them display on the menu.

**Comment by NovaCygni** [comment]
Thats nothing to do with the tool thats simply your install itself, feel free to add things to the Menu manually yourself.

**Comment by Fly34567** [comment]
Ok.

**Comment by gnuhurd93** [comment]
in arch display this error for me and me use this command from FAQ  about fetch/install the latest update available
pacman -Syyu --needed --overwrite '*' blackarch
after this 
pacman -Syyu blackarch
thanks friends
