### ISSUE TITLE
Error updating keyring

### ISSUE THREAD

**Issue by FabioNevesRezende** [BlackArch/blackarch#1617]
Hello. I ran `sudo pacman-key --refresh-keys` but it is failing with an error that says 

>  ERROR: A specified local key could not be updated from a keyserver.

The error seems to happen right after refreshing key from noptrix:

> gpg: key 67D8BDF42AD93F4E: "Levon 'noptrix' Kayan (BlackArch Master) <noptrix@nullsecurity.net>" not changed
gpg: Total number processed: 111
gpg:              unchanged: 80
gpg:         new signatures: 622
gpg: [don't know]: invalid packet (ctb=15)
gpg: keyring_get_keyblock: read error: Invalid packet
gpg: keydb_get_keyblock failed: Invalid keyring
gpg: keydb_search failed: Invalid keyring
gpg: Ohhhh jeeee: ... this is a bug (getkey.c:3284:merge_selfsigs)
/usr/bin/pacman-key: line 643:  1295 Aborted                 (core dumped) "${GPG_PACMAN[@]}" --refresh-keys "$@"
==> ERROR: A specified local key could not be updated from a keyserver.

What could be happening?

**Comment by ikstream** [comment]
have a look at BlackArch/blackarch#883

**Comment by bezoris** [comment]
@ikstream > same issue and that worked for me. Many thanks!
`sudo pacman -Syyu blackarch`

**Comment by noptrix** [comment]
@ikstream thanks. @FabioNevesRezende see solution iks pointed to
