### ISSUE TITLE
Failed to start Login Service -> boot after install

### ISSUE THREAD

**Issue by scojopa** [BlackArch/blackarch#1618]
systemctl status systems-logind.service for details
this is after new install off ISO

how do I access systemctl for more info to rectify?

I had the same issue w. Failed to start logon service when I created a virtual machine.

**Comment by scojopa** [comment]
I am a n00b but is that a joke at the end of the installation when it says hey noob backdooring your system now

**Comment by ikstream** [comment]
which iso did you use, so i can try to recreate you problem?

**Comment by scojopa** [comment]
http://ftp.halifax.rwth-aachen.de/blackarch/iso/blackarchlinux-live-2017.03.01-x86_64.iso
&
https://mirror.lps.rocks/blackarch/iso/blackarchlinux-live-2017.03.01-x86_64.iso

**Comment by ikstream** [comment]
I tried it several times on VM and could not recreate your problem.
-Did you encrypt your root partition?
-Did you install from repo or from iso?
-Did you install X11?
-Any additional information?

**Comment by ikstream** [comment]
Did you follow https://blackarch.org/blackarch-install.html?

**Comment by scojopa** [comment]
Yes I followed below. 
I did encrypt /
I installed from ISO -> option 2?
Noticed this but not once did it ask me to install X11

**Comment by ikstream** [comment]
This seems to be only a problem if you install from iso. If you have internet available during install i would recommend install from repo.

**Comment by scojopa** [comment]
Question. I have linux mint installed on sda
/dev/sda
  /dev/sda1 -> /boot
 /dev/sda2 -> /
  /dev/sda3 -> linux swap

when using the ISO to install blackarch. if I create a /dev/sda4 -> blackarch / 
Can I specify the boot and swap partition already in use?

**Comment by scojopa** [comment]
I tried installing via repo
When it gets to hard drives setup, it does not allow for partition assignment or view existing partitions
It only presents the entire drive sda it does not recognize existing partitions.

**Comment by ikstream** [comment]
Start the live iso and edit the blackarch-install script you can use `vim /bin/blackarch-install`.
Remove the highlighted part and you can go on in the install script and use your existing partitions if you answer no to creating new ones.
![snip_2017-05-01-00 31 17](https://cloud.githubusercontent.com/assets/5787845/25568559/b3b8a1f8-2e05-11e7-8632-cd0aa3c3b2f9.jpg)

**Comment by scojopa** [comment]
Thanks. Last question.
I don't want this installation to touch my /boot will update grub from main OS after installation. 
I can now see my partitions but it wants me to assign a boot drive and will not let me skip it.
I just want to assign / and swap to specific partitions.

Thanks,

**Comment by ikstream** [comment]
I haven't tested this, as i have no time atm, but you could try to remove/comment out the highlighted line.
![snip_2017-05-01-09 35 31](https://cloud.githubusercontent.com/assets/5787845/25574824/ee41cbc8-2e51-11e7-9ee5-695de7b44753.jpg)

**Comment by scojopa** [comment]
I commented out both section it still requires a /boot config

**Comment by ikstream** [comment]
in make_partitions() is a call to make_boot_partition, if you comment it out as well, your /boot should not be formatted, you will be asked for boot partition nevertheless

**Comment by PedroSFreitas** [comment]
@scojopa The Offline installation requires some changes.
We'll be working on it.

**Comment by ikstream** [comment]
This problem should be fixed by now.
