### ISSUE TITLE
Can not load kernel or start login service

### ISSUE THREAD

**Issue by Fly34567** [BlackArch/blackarch#1619]
After installing the latest Blackarch it said it failed to start those two.

**Comment by ikstream** [comment]
how did you install arch?
-netiso or liveiso
-from repository or from iso?

**Comment by Fly34567** [comment]
live ISO, iso

**Comment by ikstream** [comment]
This seems to be the same problem as BlackArch/blackarch#1618
I would recommend to use the repo install for now, as only the iso install seems to have this problem.

**Comment by loayN** [comment]
i have the same problem 
i downloaded the Live ISO and i install from the ISO and still get the same message "failed to start the log in service", so as @ikstream if i install from repo there will be no problem ?! 
that what i also read in the "black arch install instructio" - this option mentioned as recommended.

**Comment by PedroSFreitas** [comment]
Closing this as duplicate of https://github.com/BlackArch/blackarch/issues/1618.
