### ISSUE TITLE
[peepdf] PyV8 missing

### ISSUE THREAD

**Issue by noraj1337** [BlackArch/blackarch#1622]
When wanting to analyse JS I have an error:

```
PPDF> js_analyse object 149

*** Error: PyV8 is not installed!!
```

`PyV8` dependency is missing

**Comment by noraj1337** [comment]
https://github.com/jesparza/peepdf

**Comment by noptrix** [comment]
thanks. will be fixed

**Comment by PedroSFreitas** [comment]
https://github.com/BlackArch/blackarch/blob/master/packages/peepdf/PKGBUILD#L12

> `depends=('python2' 'python2-jsbeautifier' 'python2-pylibemu' 'python2-pyv8')`

added.
closing.
