### ISSUE TITLE
Booting from USB issues

### ISSUE THREAD

**Issue by Kneekoli** [BlackArch/blackarch#1624]
I just put blackarch on my USB using PowerISO. When I load from USB after turning my computer back on for some reason it doesnt read or recognize the image. I followed directions exact. I am using an HP Pavilion wint intel core 5 and windows 10

**Comment by ikstream** [comment]
Have you checked if he sha1sum is correct?
Have you tried a different tool to make a bootable usb stick?

If you don't know any tools have a look at http://www.makeuseof.com/tag/10-tools-make-bootable-usb-iso-file/

**Comment by G0dlyLuck** [comment]
Use Rufus to burn the image to USB using DD flashing technique not ISO (will be asked once you press start). If you run a hybrid GPU setup (i.e. most gaming laptops with nvidia) disable nouveau by typing "e" on the bootloader and then type at the end of the appearing line "nouveau.modeset=0" . Also be sure that the USB is formatted in the format your laptop supports. If your laptop supports UEFI make sure the usb has a GPT partition table. If its Legacy use MBR.

**Comment by PedroSFreitas** [comment]
Closing this issue due inactivity of OP.
If you think this is a mistake, please feel free to reopen and provide further information; so we can help to troubleshoot any problem.
