### ISSUE TITLE
[Error] Wifi-Pumpkin 

### ISSUE THREAD

**Issue by MatheusViGo** [BlackArch/blackarch#1628]
When executed show this error message:
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 39, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/wifi-pumpkin/core/loaders/checker/networkmanager.py", line 4, in <module>
    from core.main import Initialize
  File "/usr/share/wifi-pumpkin/core/main.py", line 31, in <module>
    from core.widgets.tabmodels import (
  File "/usr/share/wifi-pumpkin/core/widgets/tabmodels.py", line 7, in <module>
    from core.utility.threads import ThreadPopen
  File "/usr/share/wifi-pumpkin/core/utility/threads.py", line 19, in <module>
    from core.servers.proxy.http.controller.handler import MasterHandler
  File "/usr/share/wifi-pumpkin/core/servers/proxy/http/controller/handler.py", line 1, in <module>
    from plugins.extension import *
  File "/usr/share/wifi-pumpkin/plugins/extension/shakepage.py", line 1, in <module>
    from mitmproxy.models import decoded
ImportError: No module named mitmproxy.models

**Comment by theoneandonly-vector** [comment]
same here

**Comment by theoneandonly-vector** [comment]
pip2 install mitmproxy is not fixing it for me.

**Comment by brandontict** [comment]
Same here , 

Latest version of Wifi-Pumpkin 

Fully updated Kali Rolling distro . 

Post back if I come to conclusion

**Comment by ikstream** [comment]
could you check which version of mitmproxy you installed?
As it seems, wifi-pumpkin needs version 0.18.2

**Comment by mab122** [comment]
@ikstream wifi-pumpkin needs older (python2) version of mitmproxy and packaged one is newer.

**Comment by ikstream** [comment]
yes, i know. This is the reason i am asking for the version, as he mentioned installing mitmproxy with pip2.
The requirements.txt in wifi pumpkin states explicitly version 0.18.2 is required

**Comment by MatheusViGo** [comment]
The problem persist with me, even with package of blackarch repository mitmproxy 2.0.2 installed.

**Comment by rootsina** [comment]
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.0.0->brotlipy<0.7,>=0.5.1->mitmproxy==0.18.2->-r requirements.txt (line 19))
----------------------------------------
[=] checking dependencies  
----[✔]----[+] hostapd Installed
----------------------------------------
[+] Distribution Name: Kali
----------------------------------------
[=]  Install WiFi-Pumpkin 
[✔] binary::/usr/bin/
[✔] wifi-pumpkin installed with success
[✔] execute  sudo wifi-pumpkin in terminal
[+] P0cL4bs Team CopyRight 2015-2017
[+] Enjoy
but after when i try to start
 wifi-pumpkin
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 35, in <module>
    from core.loaders.checker.depedences import check_dep_pumpkin
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/depedences.py", line 2, in <module>
    from core.utility.collection import SettingsINI
  File "/usr/share/WiFi-Pumpkin/core/utility/collection.py", line 2, in <module>
    from PyQt4.QtCore import QSettings
ImportError: No module named PyQt4.QtCore
help!!

**Comment by MatheusViGo** [comment]
I already tried install with pip and pip2, but persist the error.

**Comment by mrsmith0x00** [comment]
@MatheusViGo @theoneandonly-vector now, it seems to work without errors, can you confirm?
