### ISSUE TITLE
iso of blackarch 64bit 6gb has error when installing 

### ISSUE THREAD

**Issue by islamux** [BlackArch/blackarch#1629]
hi sorry my language not well  i want to install blackarch 6gb 64bit in my computer not in vbox or other like qemu but in driver beside fedora partition but when i start install i see some message like this
 
`
  cp: error writing '/mnt/opt/android-ndk/toolchains/x86-4.9/prebuilt/linux-x86_6$ cp: error writing '/mnt/opt/android-ndk/toolchains/x86-4.9/prebuilt/linux-x86_6$ cp: error writing '/mnt/opt/android-ndk/toolchains/x86-4.9/prebuilt/linux-x86_6$ cp: error writing '/mnt/opt/android-ndk/toolchains/x86-4.9/prebuilt/linux-x86_6$ cp: error writing '/mnt/opt/android-ndk/toolchains/x86-4.9/prebuilt/linux-x86_6$ $-x86_64/bin/i686-linux-android-g++': No space left on device `

i made iso in usb by dd bs=512M if=/balckarch.iso of=/dev/sdb
the installation continue until the end but nothing install in the partition
the iso torrent  download it from blackarch site
what's the problem why i can't install it

i'm using now manjaro , fedora25 , linuxmint18 in the same labtop and i want to add blackarch also ^_^ 
can you help me
the iso more than 6gb and net price in my country expensive

this is my hardware info 
```

inxi -F
System:    Host: islamux-pc Kernel: 4.9.20-1-MANJARO x86_64 (64 bit) Desktop: KDE Plasma 5.9.4
           Distro: Manjaro Linux                                                                                             
Machine:   Device: laptop System: LENOVO product: 2347AY1 v: ThinkPad T430                                                   
           Mobo: LENOVO model: 2347AY1 UEFI [Legacy]: LENOVO v: G1ET92WW (2.52 ) date: 02/14/2013                            
Battery    BAT0: charge: 18.1 Wh 37.2% condition: 48.6/56.2 Wh (87%)                                                         
CPU:       Dual core Intel Core i5-3320M (-HT-MCP-) cache: 3072 KB                                                           
           clock speeds: max: 3300 MHz 1: 1982 MHz 2: 1780 MHz 3: 1954 MHz 4: 1987 MHz                                       
Graphics:  Card: Intel 3rd Gen Core processor Graphics Controller                                                            
           Display Server: X.Org 1.19.3 driver: intel Resolution: 1600x900@60.01hz                                           
           GLX Renderer: Mesa DRI Intel Ivybridge Mobile GLX Version: 3.0 Mesa 17.0.2
Audio:     Card Intel 7 Series/C216 Family High Definition Audio Controller driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.9.20-1-MANJARO
Network:   Card-1: Intel 82579LM Gigabit Network Connection driver: e1000e
           IF: enp0s25 state: down mac: 28:d2:44:08:5b:df
           Card-2: Intel Centrino Advanced-N 6205 [Taylor Peak] driver: iwlwifi
           IF: wlp3s0 state: up mac: 6c:88:14:3d:e5:04
Drives:    HDD Total Size: 500.1GB (37.3% used)
           ID-1: /dev/sda model: WDC_WD5000BPVT size: 500.1GB
Partition: ID-1: / size: 29G used: 8.4G (31%) fs: ext4 dev: /dev/sda1
Sensors:   System Temperatures: cpu: 52.0C mobo: N/A
           Fan Speeds (in rpm): cpu: 3631
Info:      Processes: 175 Uptime: 1:39 Memory: 1152.1/3639.5MB Client: Shell (bash) inxi: 2.3.8




lsblk -f
NAME   FSTYPE LABEL     UUID                                 MOUNTPOINT
sda                                                          
├─sda1 ext4             39af1e63-8a94-4a10-bb04-10313a3e034e /
├─sda2 ext4   Mint18    87efb0c4-9e7a-446a-9f62-e4ea7736d020 
├─sda3                                                       
├─sda4 ext4   KaliLinux 8ef7635c-06e8-451a-a39d-ba0d3d1d47cb /run/media/islamux/KaliLinux
├─sda5 ext4   Fedora25  e7a46c0d-aea4-4ee6-9b3c-ce185078fa6e 
├─sda6 ntfs   Library   006A7D4918B37999                     /run/media/islamux/Library
├─sda7 ntfs   variety   54E1903D2AE0D83E                     
├─sda8 ntfs   Media     265B5289E434C690                     /run/media/islamux/Media
└─sda9 swap             00afac27-d08e-4d87-90f5-859855ad5cc7 
```

**Comment by ikstream** [comment]
Hi @islamux the  `No space left on device` tells you, that your partition, you are trying to install black arch to is to small.
You could checkout installing blackarch on top of existing arch linux, as it should work with manjaro as well and reduce the overhead.

**Comment by islamux** [comment]
@ikstream thanx for helping.
i resolved the problem by change the network interface, strang...  but i did it. then the install continue untile the end.
i choiced the boot in the same partiton` sda4 ext4` like above.
the boot in sda1 the palce of manjaro .
i updat-grub from manjaro, blackarch dispaly in the process, but when in reboot i didn't find it in boot whith other distro like fedora & mint18.

**Comment by islamux** [comment]
if there aren't another solution i replace manjaro whith blackarch but in the begining i didn't want that.
thanx ^_^

**Comment by ikstream** [comment]
You don't have to replace manjaro, you can use the blackarch repository in manjaro. 32G should be enough.
You can see 
`Installing on top of ArchLinux` at https://blackarch.org/downloads.html for instructions how to do it.

**Comment by islamux** [comment]
but i have the hole iso 6Gb. 
how can i use the iso like a repo?

**Comment by Mr-Virtuoso** [comment]
I have same problem, i download 7G (6.7) but when i try to install with ISO-Live option in blackarch-install script i can't install it and i have error after rebooting :)

**Comment by ikstream** [comment]
Can you please try the new ISO?
Do you still encounter this problem?

**Comment by PedroSFreitas** [comment]
> i solved the problem by change the network interface, Strange!!!

@ikstream i'm closing this issue since he wrote the above and he didn't reply to your last comment. :/
