### ISSUE TITLE
msfupdate command NOT found

### ISSUE THREAD

**Issue by 3rso** [BlackArch/blackarch#1631]
Hi, 

im using arch linux, and installed the blackarch repository, then i installed metasploit and metasploit-msfupdate but if i type msfupdate it say "sudo: msfupdate: command not found"

How can i execute the msfupdate?

Ty

**Comment by noptrix** [comment]
@3rso metasploit is not maintained by us. it is done by arch linux community. please open any issues related to msf on arch linux
