### ISSUE TITLE
Error when running blackarch-install

### ISSUE THREAD

**Issue by jackruder** [BlackArch/blackarch#1652]
At the downloading and executing strap.sh step, I receive the error:
[-] ERROR: Wrong SHA1 sum for strap.sh (orig: 34b1a3698a4c971807fb1fe41463b9d25e1a4a09). Aborting!

This wasn't the original in the first place, so this needs to be fixed.  The site provides this sum: 4826a0f271696a127b67e7fe7205cc960c9eef1b

**Comment by ikstream** [comment]
Have you tried to download strap.sh again?
The checksum provided at blackarch.org is.
34b1a3698a4c971807fb1fe41463b9d25e1a4a09

If I run `curl -O https://blackarch.org/strap.sh`
and `$ sha1sum strap.sh` I get this checksum. 
What do you mean with "This wasn't the original in the first place"

**Comment by osxdos** [comment]
[+] Downloading and executing strap.sh

sha1sum: /tmp/strap.sh: No such file or directory
[-] ERROR: Wrong SHA1 sum for strap.sh:  (orig: 6f152b79419491db92c1fdde3fad2d445f09aae3). Aborting!
[ blackarch ~ ]

**Comment by osxdos** [comment]
i am having this same issue

**Comment by osxdos** [comment]
also im getting a connection refused to blackarch.org, fix your shit

**Comment by PedroSFreitas** [comment]
@osxdos 
**First**: we would be glad to fix anything if they're broken.
**Second** you don't need to send 10000 comments, put all you need in a single one.
**Third** don't bump old threats, make a new one and reference it with details of what seems similar.
You didn't provide any useful information, besides the output. Not sure what hardware you're trying, what distro (Arch, Manjaro or anything based on Arch), etc.

_Watch your language._

locking.
