### ISSUE TITLE
Nothing works after fresh install

### ISSUE THREAD

**Issue by seemsindie** [BlackArch/blackarch#1663]
Hello guys, i downloaded netinstall and installed, encrypted and installed tools.
After installation when i log in nothing works from the menu, then i tried switching tty and executing commands, and all of commands are `not found`.

Did i screw something up, any idea how to fix it?

**Comment by ikstream** [comment]
does this only happen to your user, or root as well. have you checked if the tools you want to use are installed?

**Comment by noptrix** [comment]
@seemsindie you likely didn't install the tools successfully. if your system is installed simply manually install all tools like this: `pacman -Syyu --force --needed blackarch`
