### ISSUE TITLE
[Tool request] intrigue-core

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#1671]
https://github.com/intrigueio/intrigue-core

**Comment by marianomarciello** [comment]
Since 1 November 2021 this is no longer maintained: [https://github.com/intrigueio/intrigue-core#notice](https://github.com/intrigueio/intrigue-core#notice).
Is a good idea add this tools ?

**Comment by noraj** [comment]
Anyway it's installable as a VM and would be impossible to package in a PKGBUILD.
