### ISSUE TITLE
whichcdn Error

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#1677]
# whichcdn http://example.org

     __      __.__    .__       .__    _________ ________    _______
    /  \    /  \  |__ |__| ____ |  |__ \_   ___ \\______ \   \      \
    \   \/\/   /  |  \|  |/ ___\|  |  \/    \  \/ |    |  \  /   |   \
     \        /|   Y  \  \  \___|   Y  \     \____|    `   \/    |    \
      \__/\  / |___|  /__|\___  >___|  /\______  /_______  /\____|__  /
           \/       \/        \/     \/        \/        \/         \/

Traceback (most recent call last):
  File "/usr/bin/whichcdn", line 75, in <module>
    for module in loader.getPlugins():
  File "/usr/lib/python2.7/site-packages/utils/loader.py", line 15, in getPlugins
    pluginList = os.listdir(PluginFolder)
OSError: [Errno 2] No such file or directory: './plugins'

**Comment by noptrix** [comment]
fixed. their fuckin setup.py is not correct...copied to /usr/share/whichcdn and made a joint script.
