### ISSUE TITLE
ZapProxy fonts are screw up if opening with the bash wrapper

### ISSUE THREAD

**Issue by ChrisFernandez** [BlackArch/blackarch#1698]
https://github.com/zaproxy/zaproxy/issues/3051
Above are the details.
also fonts are nice and good when I open directly from the instalation directory.

**Comment by ikstream** [comment]
The zaproxy package is in the archlinux community repository by now

**Comment by ChrisFernandez** [comment]
@ikstream so blackarch does not have its own? ok I guess I will try to post this somewhere.. if is community not sure where to ask for this... lot of us that refuse to use burp because is closed source and move to blackarch find this very negative to the eye.. works perfectly well on debian base distros. :/

**Comment by ChrisFernandez** [comment]
@ikstream ok found a place https://bugs.archlinux.org/task/54551  but I will doub they will do anything about it I am sure this has to do with the java/PATH/env since is a java app..(I hate java) lol

**Comment by ikstream** [comment]
@ChrisFernandez there is no more zaproxy package in blackarch. If nothing happens you could try to contact the maintainer of the package or try to fix it by your self.
https://www.archlinux.org/packages/community/any/zaproxy/

it has been a long time since i used java, heard it isn't as bad as it used to be^^.

**Comment by ChrisFernandez** [comment]
@iknite yeah I am not a fan of java... whats the reason is not maintained on blackarch? is the only opensource option we have as a http proxy/scanner.. do you need maintainers?

**Comment by ikstream** [comment]
@ChrisFernandez As far as i know, as soon a package is in the main repository, it is no longer maintained in blackarch. Why have a second package, if it already in a repository you use anyways?

**Comment by ikstream** [comment]
@ChrisFernandez are there any news on this issue?

**Comment by ChrisFernandez** [comment]
@ikstream hey thanks for checking in, I been busy with blue team stuff but I have another pentest coming in September so I will def use ZAP and will confirm, but last time I used it.. it does was giving me the font issues... I hate java only reason I use ZAP is because is ethically better than BURP I wish there was a good option to ZAP/BURP in GO for example.

**Comment by saltasatelites** [comment]
I've this in my /etc/environment:
_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=lcd'
and font looks better..

**Comment by ChrisFernandez** [comment]
yeah I figure that one a week or two a go and posted it on zapproxy mailing list and issue I had opened long time a go so this is resolved manually. will be nice to add this setting to the PKGBUILD file but blackarch does not control this, I think it comes from upstream if not I will just do it myself

**Comment by PedroSFreitas** [comment]
Unfortunately it's a mirror of community/zaproxy. Not sure if we can do something about it.
https://www.archlinux.org/packages/community/any/zaproxy/

**Comment by ChrisFernandez** [comment]
We may be able to submit a change to community ...  maybe get in contact with the person creating the pkgbuild 

> Last Packager: | Levente Polyak

**Comment by saltasatelites** [comment]
I´m not sure if we are talking about the same. If you have java installed, you´ll have a file called environment in /etc. Edit /etc/environment and that is. Nothing related to zaproxy. That´s for all java apps

**Comment by PedroSFreitas** [comment]
@saltasatelites 
> I´m not sure if we are talking about the same. If you have java installed, you´ll have a file called environment in /etc. Edit /etc/environment and that is. Nothing related to zaproxy. That´s for all java apps

True.
But I can understand the idea of changing it via PKGBUILD (package). Because if other Java applications work as expected, i.e. without font rendering issues, and only happening within Zaproxy then some small patch provide by the package itself sounds okay from my humble opinion.
Anyway, you have a good point too. S... I have no idea what can be done exactly.

Maybe we should close this issue, since it's not related to BlackArch itself?

**Comment by ChrisFernandez** [comment]
@saltasatelites  ya but the pkbbuild can add this entry on the /etc/enviroment since zap seems like is the only app that is affected, and cant hurt the other java apps..

**Comment by saltasatelites** [comment]
That solutions works for me with zaproxy, burpsuite, paros, webscarab... In any case, as @PedroSFreitas says we should close this issue, is only related to java.
Thanks for your time!!

**Comment by ChrisFernandez** [comment]
closing since this is fixed but needs permanent fix upstream for zap. but if we want all java apps to look good I suggest we do someting about it here in blackarch.. maybe add that as default in the install

**Comment by PedroSFreitas** [comment]
@ChrisFernandez
> but if we want all java apps to look good I suggest we do someting about it here in blackarch

True... I'll try to bounce it through other members. But it looks like something that could be easily done.

**Comment by saltasatelites** [comment]
That sounds good, but java is ...java. I don't think that exist "the only" or "the best" solution. My environment config works for me, but there are other solutions to the same problem maybe better for other users. From the arch wiki: https://wiki.archlinux.org/index.php/Java_Runtime_Environment_fonts

This sounds important too: 
> Note: Suggestions in this section are applicable to all applications, using explicitly installed (external) Java runtime. Some applications are bundled with own (private) runtime or use own mechanics for GUI, font rendering, etc., so none of written below is guaranteed to work.

So a solution for a whole distro seems imposible, and maybe could ended becoming a headache for all the devs

**Comment by PedroSFreitas** [comment]
True. But...
Do you believe that introducing one line of setting to `/etc/environment` could cause great problems in the future? It doesn't look like having any side effects. And could improve BlackArch a little, even reducing the numbers of possible Issues; at least regarding Java.


> That sounds good, but java is ...java.

I laughed.
