### ISSUE TITLE
[-] CRITICAL: Package not found in repository 'blackarch-config-awesome.install'

### ISSUE THREAD

**Issue by pourfallah** [BlackArch/blackarch#1713]
hi
I installed fresh archlinux, and now i want to install blackarch tools on it.
I tried to install all blackarch tools with "blackman -a" command, but it's give and error:
```
[+] Installing blackarch group
[+] Installing python2-speechrecognition package
[+] Package python2-speechrecognition already installed
[+] Package python2-speechrecognition up to date (v3.5.0) 
   ** reinstall with -f arg
[+] Installing blackarch-config-awesome.install package
[-] CRITICAL: Package not found in repository 'blackarch-config-awesome.install'
```
My window manager is: i3, and system is up to date.
Please help me to install all blackarch tools.
Thanks

**Comment by pourfallah** [comment]
i found an answer in my try:
just copy `"blackarch-config-awesome"`  recursively to "blackarch-config-awesome.install" folder, and it's fixed.

`this folder can found in blackarch packages folder "~/.blackarch/packages".`

**Comment by heichblatt** [comment]
The package name seems to be`blackarch-config-awesome`, without the `.install`.
