### ISSUE TITLE
[Tool Request] Belati

### ISSUE THREAD

**Issue by aancw** [BlackArch/blackarch#1718]
Hi, I'm the author of Belati( https://github.com/aancw/Belati )

> Belati - The Traditional Swiss Army Knife For OSINT

> Belati is tool for Collecting Public Data & Public Document from Website and other service for OSINT purpose. This tools is inspired by Foca and Datasploit for OSINT :)

I'm want suggest this tool in BlackArch repository :)

Thanks!

**Comment by noptrix** [comment]
released!
