### ISSUE TITLE
[Tool request] OpenVas 9

### ISSUE THREAD

**Issue by narutowindy** [BlackArch/blackarch#1719]
this is not even available on arch linux, please provide PKGBUILD !!

**Comment by ikstream** [comment]
As openvas is in the community repository, you could flag the relevant packages outdated.

**Comment by narutowindy** [comment]
yes , but they are not providing the latest version, they are just sticking with the version 8?? i was thinking of making a PKGBUILD but im still noob for that!

**Comment by narutowindy** [comment]
@ikstream are you the developer of "blackman" tool ??  its still working??

**Comment by ikstream** [comment]
@narutowindy no, i am not, but it should work as far as i know. If you encounter any problems and there is no open issue so far, you could  open one.

Give them some time to uodate it. Most of them spend their free time to maintain the packages

**Comment by PedroSFreitas** [comment]
I vote for **closing this Issue**, the package is already marked as out of date in Community (https://www.archlinux.org/packages/?sort=&repo=Community&q=openvas&maintainer=&flagged=).
And **in my humble opinion**, there is no reason to work on something that is already maintained by others.

**Comment by narutowindy** [comment]
Yeah but its been marked outdated for almost 4 times , still no updated version ...

**Comment by lsfxz** [comment]
In the meantime: I've made some PKGBUILDS a few months ago (with minimal effort, I didn't think it would take so long for the official packages to follow and didn't intend to release them). I've just added them to https://github.com/lsfxz/blackarch-ruby . Feel free to  play around with those. There are also prebuild packages from some time ago here: https://github.com/lsfxz/blackarch-ruby/releases/tag/20170501
