### ISSUE TITLE
X does not properly start in a Hyper-V virtual machine

### ISSUE THREAD

**Issue by pv2b** [BlackArch/blackarch#1725]
When trying to run the BlackArch LiveCD on a Hyper-V VM, X won't start. Only the following can be seen on screen, with a flicker every 5 seconds or so:

![2017_07_10_14_29_31_blackarch_live_on_xxxx_virtual_machine_connection](https://user-images.githubusercontent.com/7115238/28020053-551f8138-6583-11e7-9f3b-c304610dbff5.png)

journalctl shows lxdm continually failing as per below:

```
Jul 10 12:06:31 blackarch systemd[1]: Started LXDE Display Manager.
Jul 10 12:06:36 blackarch systemd[1]: lxdm.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 12:06:36 blackarch systemd[1]: lxdm.service: Unit entered failed state.
Jul 10 12:06:36 blackarch systemd[1]: lxdm.service: Failed with result 'exit-code'.
Jul 10 12:06:37 blackarch systemd[1]: lxdm.service: Service hold-off time over, scheduling restart.
Jul 10 12:06:37 blackarch systemd[1]: Stopped LXDE Display Manager.
Jul 10 12:06:37 blackarch systemd[1]: Started LXDE Display Manager.
Jul 10 12:06:42 blackarch systemd[1]: lxdm.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 12:06:42 blackarch systemd[1]: lxdm.service: Unit entered failed state.
Jul 10 12:06:42 blackarch systemd[1]: lxdm.service: Failed with result 'exit-code'.
Jul 10 12:06:42 blackarch systemd[1]: lxdm.service: Service hold-off time over, scheduling restart.
Jul 10 12:06:42 blackarch systemd[1]: Stopped LXDE Display Manager.
```

Investigating the failed kernel modules, they do not seem to be important, they are VirtualBox related.

After reviewing [this mailing list post](http://driverdev.linuxdriverproject.org/pipermail/driverdev-devel/2013-August/040327.html), I added a new file to my system as per below:

```
[ blackarch ~ ]# cat /etc/X11/xorg.conf.d/30-hyperv.conf
Section "Device"
    Identifier  "HYPER-V Framebuffer"
    Driver      "fbdev"
EndSection
[ blackarch ~ ]#
```

This seems to have resolved the issue for me. Now, I'm not sure if this fix will break X for everyone else or not, I'll leave that to you guys to figure out instead of sending in a pull request. :)

Find attached to the issue also the [output of journalctl](https://github.com/BlackArch/blackarch/files/1135613/journalctl.txt) and the contents of 
[/var/log/Xorg.0.log](https://github.com/BlackArch/blackarch/files/1135621/Xorg.0.log.txt).

Thank you to jdz on IRC for helping me out to troubleshoot this.

**Comment by PedroSFreitas** [comment]
@pv2b Thanks for sharing your solution.

@noptrix close.
