### ISSUE TITLE
menu (terminal,network,browsers ) are not coming up

### ISSUE THREAD

**Issue by ellipizle** [BlackArch/blackarch#1728]
I followed the instructions for install blackarch twice, using the repo as recommended on the site.
my system boots and when i login to the default desktop. a message pop up

> fbsetbg: I cant' find an app to set the wallpaper with, you can install one in manymany ways but  will give you some simple advice: install Eterm and you're set. Eterm provides Esetroot and thats a great wallpaper setter. I recommend you install the package provided by your distro.

right-clicking to open the terminal, network, browser etc. does do anything.

note: I followed and did everything on the install guide page. the only thing i did different was that on the second trial i did not install the blackarch tool.

**Comment by ikstream** [comment]
Please check if eterm is installed, if so, please check feh and nitrogen as well

**Comment by ellipizle** [comment]
@ikstream, i did install eterm and nitrogen using yaourt, but the issue still persist

**Comment by saltasatelites** [comment]
> I followed the instructions for install blackarch twice, using the repo as recommended on the site.
my system boots and when i login to the default desktop. a message pop up 

I understand you're trying on an previous ArchLinux install that works fine?

**Comment by ikstream** [comment]
Are there any "failed" messages during startup or in your journal?

**Comment by easytouse2016r** [comment]
I install system again on virtual machine BlackArch Linux 32 bit Live ISO (You choose which version you want 32 or 64) - blackacrh-install, with the options (3) from the source, and I did not set the encryption, cfdisk (dos) 1GB Bot* (ext4), 2GB Swap, 37GB Rot(ext4). I added a regular user, (flux) manager. I did not install any tools during installation. I install grub, after finish reboot after start system, I used (tty) ctr+alt+f2 and I am log in {root and pasword} after {systemctl start dhcpcd@enp0s3.service} after {pacman -Syyu --force --needed blackacrh} notification {install all tools(default/all) 1-1705} after {pacman -Syyu --force --needed blackacrh} notification {install all tools(default/all) 1707-18..reste} after {pacman -Syyu --force --needed blackacrh} notification {install all tools(default/all) 1-1705} after {pacman -Syyu --force --needed blackacrh} notification {install all tools(default/all) 1707-18..reste} and reboot everything works *(problem with the program, veil(1706) package mono adin 1.1-1 , that blocks install all tools in one moment used (all)) 

before (blackarch-install) i connected to the internet (during install-network setup -> 3. Skip (use this if you are already connected)

**Comment by easytouse2016r** [comment]
If you do not want to install the system again. just try it :::{{{ after start system, I used (tty) ctr+alt+f2 and I am log in {root and pasword} after {systemctl start dhcpcd@enp0s3.service} after {pacman -Syyu --force --needed blackacrh} notification {install all tools(default/all) 1-1705} after {pacman -Syyu --force --needed blackacrh} notification {install all tools(default/all) 1707-18..reste} after {pacman -Syyu --force --needed blackacrh} notification {install all tools(default/all) 1-1705} after {pacman -Syyu --force --needed blackacrh} notification {install all tools(default/all) 1707-18..reste} and reboot everything works *(problem with the program, veil(1706) package mono adin 1.1-1 , that blocks install all tools in one moment used (all))

**Comment by easytouse2016r** [comment]
*pacman -Syyu --force --needed blackarch

**Comment by ikstream** [comment]
@easytouse2016r you commented on two issues with mostly the same text.
Could you please tell us, what your exact problem is and provide some condensed information.
In case something is not starting, please check `systemctl --failed` and `systemctl status <failed service>`
If your issue is not present in the issue tracker here on github, please open a new one, with the problem as name and the condensed information.

**Comment by saltasatelites** [comment]
Install cwallpaper (aur)

**Comment by saltasatelites** [comment]
In any case, @ellipizle still have any interest about this? This issue is from july and his/her last comment too.
I'm not really sure of what we are talking about here...

**Comment by PedroSFreitas** [comment]
I think we can close this Issue since OP haven't replied to the comments above.

If @ellipizle think it's mistake, please re-open it and provide further information.

**Comment by DharmeshDcruz** [comment]
i have a same problem. tools not pop up wmen i click that

**Comment by ikstream** [comment]
@DharmeshDcruz have you tried the recommended steps?
