### ISSUE TITLE
bbqsql ¿warning? : Namespace(c=None)

### ISSUE THREAD

**Issue by saltasatelites** [BlackArch/blackarch#1733]
Hello everyone:
In the last days I have detected that when I run bbqsql this message appears: "Namespace (c = None)" and a very huge free space until the menu. 
The app works as always, runnning on Archlinux64, so I'm sorry but this is all the info that I can apport..no logs or similars
I've been googling and I've found that is related with python, but I have no enough knowledges (big mistake..)t o find a solution by myself. Maybe the python experts from here could give me some help...
Thanks in advance
P.D Someone else have detected this??

**Comment by noptrix** [comment]
unfortunately we can't update anything related to bbqsql. bbqsql is using gevent.coros which is deprecated. and coros is not available anymore in gevent-1.2.3
