### ISSUE TITLE
[Tool request] D-TECT

### ISSUE THREAD

**Issue by Beyarz** [BlackArch/blackarch#1735]
###Description: D-TECT is an All-In-One Tool for Penetration Testing. This is specially programmed for Penetration Testers and Security Researchers to make their job easier, instead of launching different tools for performing different task. D-TECT provides multiple features and detection features which gather target information and finds different flaws in it.

###Features:
Sub-domain Scanning
Port Scanning
Wordpress Scanning
Wordpress Username Enumeration
Wordpress Backup Grabbing
Sensitive File Detection
Same-Site Scripting Scanning
Click Jacking Detection
Powerful XSS vulnerability scanning
SQL Injection vulnerability scanning

https://github.com/shawarkhanethicalhacker/D-TECT

**Comment by noptrix** [comment]
added.
