### ISSUE TITLE
Android sdk version

### ISSUE THREAD

**Issue by pipriles** [BlackArch/blackarch#1736]
I have installed `android-sdk` trough the AUR. But when i do `pacman -Syu` it shows this warning:

```sh
warning: android-sdk: local (25.2.5-2) is newer than blackarch (r24.4.1-1)
warning: android-sdk-build-tools: local (r25.0.2-1) is newer than blackarch (r23.0.1-1)
warning: android-sdk-platform-tools: local (r25.0.4-1) is newer than blackarch (r23.0.1-1)
```

So maybe the package in blackarch is not up to date? Any ideas to get rid of this ugly message?

**Comment by noptrix** [comment]
we updated the android sdk tools to the latest version now. but you should remove all android sdk packages and then reinstall blackarch-versions. you probably installed the AUR versions before.
