### ISSUE TITLE
strap.sh don't work due signature problems

### ISSUE THREAD

**Issue by saltasatelites** [BlackArch/blackarch#1738]
Hi guys.
I think is a problem with one or more signatures.
Output of sh -x strap.sh:

> <+ MIRROR=https://www.mirrorservice.org/sites/blackarch.org/blackarch/
+ blackarch_setup
+ check_priv
+ '[' 0 -ne 0 ']'
+ msg 'installing blackarch keyring...'
++ tput bold
++ tput setaf 2
++ tput sgr0
+ echo '[+] installing blackarch keyring...'
[+] installing blackarch keyring...
+ make_tmp_dir
++ mktemp -d /tmp/blackarch_strap.XXXXXXXX
+ tmp=/tmp/blackarch_strap.JsiDcDNL
+ trap 'rm -rf /tmp/blackarch_strap.JsiDcDNL' EXIT
+ cd /tmp/blackarch_strap.JsiDcDNL
+ fetch_keyring
+ curl -s -O 'https://www.blackarch.org/keyring/blackarch-keyring.pkg.tar.xz{,.sig}'
+ verify_keyring
+ gpg --keyserver http://pgp.mit.edu --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3
+ gpg --keyserver-options no-auto-key-retrieve --with-fingerprint blackarch-keyring.pkg.tar.xz.sig
+ err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
++ tput bold
++ tput setaf 1
++ tput sgr0
+ echo '[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch'
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
+ exit 1337
+ rm -rf /tmp/blackarch_strap.JsiDcDNL`>> `

I've change `hkp://pool.sks-keyservers.net`  to `keyserver hkp://pgp.mit.edu:11371` but th same result.

**Comment by saltasatelites** [comment]
More info. As the output shows, the problem is with Mr Evan Teitelman signature.

**Comment by Murcott** [comment]
Run:
`sed -i 's/http\:\/\/pgp.mit.edu/pgp.mit.edu/g' strap.sh`

[The key is valid](https://pgp.mit.edu/pks/lookup?op=get&search=0x63EC0ADBEA87E4E3), but you can't call the server with HTTP(S).

**Comment by saltasatelites** [comment]
OMG I feel absolutely stupid. I haven't done a fresh install for a long time, and some things have changed I also read something on the web about https servers, but I gave no importance

**Comment by PedroSFreitas** [comment]
I wish I had seen this `Issue` before I fired an Archlinux installation in a virtualbox just to test the `strap.sh`.
Anyway: https://github.com/BlackArch/blackarch-site/pull/72
