### ISSUE TITLE
Infitesimally Small Fonts 

### ISSUE THREAD

**Issue by G0dlyLuck** [BlackArch/blackarch#1745]
So after tinkering with BlackArch in Virtualbox I wanted to install on my laptop. I got an MSI laptop with a 4k screen and by god, are those fonts small. I need to have my face 5cm from the screen in order to read the text which is far from ideal when using a laptop as one may figure. Tried to setfont different fonts but to no avail. I can't read the TTY properly due to this extremely small text. Kind of a shame! Any way to fix this? 

edit: since its an msi with hybrid gpu i had to disable nouveau but i dont think that matters a lot.

**Comment by ikstream** [comment]
Check out https://wiki.archlinux.org/index.php/Fonts#Console_fonts

You should be able to set your font size woth the `setfont` command. 
I dont know how it looks, as I don't want to tinker with mine, as it works fine.

You could try the tips from https://unix.stackexchange.com/questions/320387/how-to-change-the-resolution-after-booting-arch-linux-installation-mediumas well.

**Comment by PedroSFreitas** [comment]
Fonts are really a terrible thing to mess with.
In addition to what @ikstream said, I'd also check out the followings:

- https://wiki.archlinux.org/index.php/Font_configuration
- https://www.reddit.com/r/archlinux/comments/5r5ep8/make_your_arch_fonts_beautiful_easily/

As far as I can tell those are necessary because BlackArch uses the same default font configuration as Arch.

**Comment by G0dlyLuck** [comment]
Thanks for the information! I will check it out and let you know if it works.

**Comment by PedroSFreitas** [comment]
@G0dlyLuck any luck?

**Comment by G0dlyLuck** [comment]
Not a lot I am afraid. It seems to work on my other laptops though. Maybe its just the MSI that is giving me problems. Wouldn't know why it behaves like this.

**Comment by PedroSFreitas** [comment]
Are you for sure using the right DPI? https://en.wikipedia.org/wiki/Dots_per_inch

**Comment by noptrix** [comment]
@G0dlyLuck This is not related to BlackArch. BlackArch is just a simple repository for ArchLinux based systems apart from the BlackArch ISO images. Consider opening such tickets @ ArchLinux forum/bugtracker systems, please. Closing this ticket now.
