### ISSUE TITLE
Can't update file datebase

### ISSUE THREAD

**Issue by 745275633** [BlackArch/blackarch#1746]
```
$ sudo LANG=c pacman -Fy
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 archlinuxcn is up to date
 blackarch                                           4.8 MiB  1176K/s 00:04 [-------------------------------------------] 100%
 blackarch.sig                                     543.0   B  0.00B/s 00:00 [-------------------------------------------] 100%
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid
error: failed to update blackarch (invalid or corrupted database (PGP signature))
```
But package database can update

**Comment by noptrix** [comment]
@745275633 Run this script and let us know: http://sprunge.us/hYFJ - Also, which mirror do you use for BlackArch?

**Comment by 745275633** [comment]
When run
```
gpg \
        --keyserver http://pgp.mit.edu \
        --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3`
```
It said
```
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```
----
I try both of these mirror:
```
https://mirrors.ustc.edu.cn/blackarch/
https://mirrors.tnua.tsinghua.edu.cn/blackarch/
```

**Comment by PedroSFreitas** [comment]
@745275633 
> When run
> 
> gpg \
>         --keyserver http://pgp.mit.edu \
>         --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3`

try removing "http://", please

**and**



> **noptrix commented**
> @745275633 Run this script and let us know: http://sprunge.us/hYFJ - Also, which mirror do you use for BlackArch?

Did you try this?

**Comment by 745275633** [comment]
gpg: keyserver receive failed: Connection timed out

----
Yes, fail in this script `sh strap.sh`

**Comment by PedroSFreitas** [comment]
> Yes, fail in this script sh strap.sh

I believe so.
First of all, try to `curl` this `strap.sh` : https://raw.githubusercontent.com/PedroSFreitas/blackarch-site/strap-sh-patch/strap.sh

And then run the script noptrix linked: http://sprunge.us/hYFJ

Here you can see more info about it: https://github.com/BlackArch/blackarch-site/pull/72

**Comment by 745275633** [comment]
I run this script and `pacman -Fy` also fail

**Comment by PedroSFreitas** [comment]
@745275633 
I'm check on that and get back to you soon.

**Comment by PedroSFreitas** [comment]
After checking everything, we narrowed it down to what we believe is a `work in progress` by Archlinux.
As you can see here [Wiki pacman/Package signing](https://wiki.archlinux.org/index.php/Pacman/Package_signing#Configuring_pacman).

Not much we can do for now.
If you have any further question or suggestion, let's us know.

Thanks.
