### ISSUE TITLE
[Tool request] Stegdetect

### ISSUE THREAD

**Issue by fullmooninu** [BlackArch/blackarch#1752]
Stegdetect is an automated tool for detecting steganographic content in images. 

I successfully compiled in ubuntu 16.04 from this repo:

https://github.com/redNixon/stegdetect

(use blackarch as vm)

**Comment by noptrix** [comment]
added and released.

**Comment by fullmooninu** [comment]
what does "added and released" mean? it's in the repo or it's going to be in the next blackarch version?

**Comment by ikstream** [comment]
if you update and look for stegdetect you will see, that you can install now from repo
