### ISSUE TITLE
[Tool Update] Yersinia new version

### ISSUE THREAD

**Issue by aoshiken** [BlackArch/blackarch#1754]
Hi,
I think you probably want to know that a new Yersinia version has been recently released with a *lot* of bugfixes (mainly GTK ones).

The version is available on the [Yersinia GitHub repository](https://www.github.com/tomac/yersinia)

IMHO it's preferable to download and compiling the code fom the master branch instead of the latest tarball release because the master one includes the fix for a command line bug usage.

Regards

**Comment by noptrix** [comment]
thanks @aoshiken. we've updated it to 0.8.2.
