### ISSUE TITLE
Install Driver TP-LINK TL-WN725N Nano USB Wireless en Blackarch

### ISSUE THREAD

**Issue by humildadever** [BlackArch/blackarch#1765]
Hi! I install natively BlackArch in one laptop but i don t had Wireless because  try many thinks to install the drivers but i can t. Someone can help me?

https://starmasked.blogspot.pt/2014/06/instalar-driver-tp-link-tl-wn725n-nano.html

**Comment by PedroSFreitas** [comment]
It's not in the scope of this project.
Either way: https://bbs.archlinux.org/viewtopic.php?pid=1203587#p1203587

> It uses a Realtek chipset, the kernel rtl8192cu driver has support for it, so it should work out-of-the-box.
