### ISSUE TITLE
(Out of date) Sqlmap

### ISSUE THREAD

**Issue by MatheusViGo** [BlackArch/blackarch#1766]
The current version is 1.1.9 and in blackarch repository is 1.1.8

#https://github.com/sqlmapproject/sqlmap/releases/tag/1.1.9

**Comment by PedroSFreitas** [comment]
`sqlmap` is on Archlinux's Community Repository. We don't provide PKGBUILD for it.
For more info: https://www.archlinux.org/packages/?sort=&q=sqlmap&maintainer=&flagged=
