### ISSUE TITLE
(Out of date) Lynis

### ISSUE THREAD

**Issue by MatheusViGo** [BlackArch/blackarch#1767]
The current version is 2.5.5 and in blackarch repository is 2.5.3

#https://github.com/CISOfy/lynis/releases

**Comment by PedroSFreitas** [comment]
`lynis` is on Archlinux's Community Repository. We don't provide PKGBUILD for it.
For more info: https://www.archlinux.org/packages/?sort=&q=lynis&maintainer=&flagged=

**Comment by MatheusViGo** [comment]
Certo. Sou brasileiro também, legal saber que há brasileiros no projeto.

**Comment by PedroSFreitas** [comment]
> @MatheusViGo commented:
> Certo. Sou brasileiro também, legal saber que há brasileiros no projeto.

Opa legal.
Sou o único aqui :)
