### ISSUE TITLE
Failed to install BlackArch within Hyper-V

### ISSUE THREAD

**Issue by enginespot** [BlackArch/blackarch#1768]
BlackArch version:blackarchlinux-live-2017.08.30-x86_64

when I tried to clean install BlackArch within Hyper-V , there are errors , so please check

![blackarch-hyper-v](https://user-images.githubusercontent.com/1422439/30262470-9f1d917e-9703-11e7-8063-59212c816ee3.png)

**Comment by meatballcoder** [comment]
I too have this.  I went into single user mode from Grub.  Xorg.0.log.old (non-old was empty) ends with EE no screens fount(EE).  After a lot of searching (and learning much, btw.) I found this,

https://wiki.archlinux.org/index.php/Hyper-V

I ran,

pacman -S  xf86-video-fbdev

and rebooted and everything worked.  I am using BlackArch, Windows10, and Hyper-V.

**Comment by PedroSFreitas** [comment]
@meatballcoder 
Thanks for this.

Going to close this issue since a solution was provided and the OP haven't said anything else regarding this.

@enginespot If you still have any problem, just reopen this and provide further information.

Thanks.

**Comment by noptrix** [comment]
thanks @PedroSFreitas
