### ISSUE TITLE
OVA file does not import into VMWare Workstation

### ISSUE THREAD

**Issue by millerbryan** [BlackArch/blackarch#1769]
What was used to create the current OVA file?  I am not able to import it into VMWare Workstation 10 running on Windows or on Linux.  Here is the error message:
"
The configuration file "D:\vmware\BlackArch\blackarch-linux-2017.06.18-x86_64.vmx" was created by a VMware product that is incompatible with this version of VMware Workstation and cannot be used.

Cannot open the configuration file D:\vmware\BlackArch\blackarch-linux-2017.06.18-x86_64.vmx.
"

Thanks!

**Comment by millerbryan** [comment]
I was able to change the virtualhw.version setting from 11 to 10 and it now starts.   I am unable to get the screen resolution large enough to work with.  If I find a solution I will post it here for other users in the same situation.

**Comment by PedroSFreitas** [comment]
@millerbryan 
> I was able to change the virtualhw.version setting from 11 to 10 and it now starts

:+1: 




> I am unable to get the screen resolution large enough to work with. If I find a solution I will post it here for other users in the same situation.

Thanks.

I'm closing this issue then, since you already found your solution. If you disagree, just re-open it. Thanks again.
