### ISSUE TITLE
[Tool request] Metasploit db_autopwn

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#1772]
https://github.com/hahwul/metasploit-db_autopwn

**Comment by 0xicl33n** [comment]
no one uses autopwn anymore because of how much network traffic it makes, thats why its no longer included in metaspoit. if you want it you can install it yourself. its not needed at all though.

**Comment by mrsmith0x00** [comment]
I completely agree with @0xicl33n, but during pentest anything happens - can will carry and will not be IDS/IPS ;)
