### ISSUE TITLE
[Tool request] Lazy Script

### ISSUE THREAD

**Issue by MatheusViGo** [BlackArch/blackarch#1779]
What is this

This is a script for that automates many procedures about wifi penetration and hacking.
![image](https://user-images.githubusercontent.com/17281717/30784944-bc933b88-a134-11e7-9177-632614eba8dc.png)
![image](https://user-images.githubusercontent.com/17281717/30784947-c6566ba4-a134-11e7-8f3b-77c22e05ecf4.png)
![image](https://user-images.githubusercontent.com/17281717/30784948-cb8875d6-a134-11e7-8c6a-6849bad5f103.png)

https://github.com/arismelachroinos/lscript

**Comment by NotANormie** [comment]
As a lazy person myself, this would be a great addition.

**Comment by MatheusViGo** [comment]
;)
