### ISSUE TITLE
invalid keyring on raspberry pi 3

### ISSUE THREAD

**Issue by gufkl** [BlackArch/blackarch#1781]
hi, may i ask?
I tried to install blackarch on top of arch linux on my raspberry pi 3
i followed the tutorial on the website [https://blackarch.org/downloads.html#install-repo](url)
but the result is like this 
`Arch~]$ curl -O https://blackarch.org/strap.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3898  100  3898    0     0   3898      0  0:00:01  0:00:01 --:--:--  2336

Arch ~]$ sha1sum strap.sh
6f152b79419491db92c1fdde3fad2d445f09aae3  strap.sh
Arch ~]$ chmod +x strap.sh
Arch ~]$ sudo ./strap.sh
[+] installing blackarch keyring...
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
Arch ~]$ 
`
and then i follow this tutorial instead [https://github.com/BlackArch/blackarch-site/pull/72](url)

and the result is like this 

`Arch ~]$ curl -O https://raw.githubusercontent.com/PedroSFreitas/blackarch-site/strap-sh-patch/strap.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0     15      0  0:00:01 --:--:--  0:00:01    34

Arch ~]$ chmod +x strap.sh
Arch ~]$ sudo ./strap.sh
./strap.sh: line 1: 404:: command not found
Arch ~]$ 
`
how to fix it? any idea?
thx

**Comment by ikstream** [comment]
You could try to replace the keyserver in the original script to something like http://pool.sks-keyservers.net/ as mentioned in [#1175](https://github.com/BlackArch/blackarch/issues/1175).

The alternative script does not exist at the location anymore, thats why you get a 404

**Comment by PedroSFreitas** [comment]
Just to add more information to @ikstream comment.
If what he said don't fix your issue, check your clock (time) and/or network settings. The script will fail with the exactly same message if you have any of those two items in a improper configuration (maybe DNS cache or something).

**Comment by gufkl** [comment]
it doest work
i tried fix my clock setting and replace this key to  http://pool.sks-keyservers.net
this my setting `#!/bin/sh
# strap.sh - install and setup BlackArch Linux keyring

# default mirror url
MIRROR='https://www.mirrorservice.org/sites/blackarch.org/blackarch/'

# simple error message wrapper
err()
{
    echo >&2 `tput bold; tput setaf 1`"[-] ERROR: ${*}"`tput sgr0`
    exit 1337
}

# simple warning message wrapper
warn()
{
    echo >&2 `tput bold; tput setaf 1`"[!] WARNING: ${*}"`tput sgr0`
}

# simple echo wrapper
msg()
{
    echo `tput bold; tput setaf 2`"[+] ${*}"`tput sgr0`
}

# check for root privilege
check_priv()
{
    if [ $EUID -ne 0 ] ; then
        err "you must be root"
    fi
}

# make a temporary directory and cd into
make_tmp_dir()
{
    tmp=`mktemp -d /tmp/blackarch_strap.XXXXXXXX`
    trap "rm -rf $tmp" EXIT
    cd "$tmp"
}

# retrieve the BlackArch Linux keyring
fetch_keyring()
{
    curl -s -O \
        'https://www.blackarch.org/keyring/blackarch-keyring.pkg.tar.xz{,.sig}'
}

# verify the keyring signature
# note: this is pointless if you do not verify the key fingerprint
verify_keyring()
{
    gpg \
        --keyserver  http://pool.sks-keyservers.net \
        --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3 > /dev/null 2>&1

    if ! gpg \
        --keyserver-options no-auto-key-retrieve \
        --with-fingerprint blackarch-keyring.pkg.tar.xz.sig > /dev/null 2>&1
    then
        err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
    fi
}

# delete the signature files
delete_signature()
{
    if [ -f "blackarch-keyring.pkg.tar.xz.sig" ] ; then
        rm blackarch-keyring.pkg.tar.xz.sig
    fi
}

# make sure /etc/pacman.d/gnupg is usable
check_pacman_gnupg()
{
    pacman-key --init
}

# install the keyring
install_keyring()
{
    if ! pacman --config /dev/null \
        --noconfirm -U blackarch-keyring.pkg.tar.xz
    then
        err 'keyring installation failed'
    fi
	# just in case
	pacman-key --populate
}

# ask user for mirror
get_mirror()
{
    printf "    -> enter a BlackArch Linux mirror url (default: $MIRROR): "
    while read line ; do
        case "$line" in
            http://*|https://*|ftp://*)
                msg 'checking mirror...'
                if ! curl -sI "$line/blackarch/os/i686/blackarch.db" |
                    head -n1 | grep -q 200
                then
                    warn 'blackarch.db not found on given mirror'
                    warn "using default mirror $MIRROR"
                else
                    MIRROR=$line
                    msg "using mirror $MIRROR"
                fi
                break
                ;;
            *)
                warn 'you did not specify a correct mirror url'
                msg "using default mirror $MIRROR"
                return
                ;;
        esac
    done < /dev/tty
}

# update pacman.conf
update_pacman_conf()
{
    # delete blackarch related entries if existing
    sed -i '/blackarch/{N;d}' /etc/pacman.conf

    cat >> "/etc/pacman.conf" << EOF
[blackarch]
Server = $MIRROR/\$repo/os/\$arch
EOF
}

# synchronize and update
pacman_update()
{
    pacman -Syy
}


pacman_upgrade()
{
    echo 'perform full system upgrade? (pacman -Su) [Yn]:'
    read conf < /dev/tty
    case "$conf" in
        ''|y|Y) pacman -Su ;;
        n|N) warn 'some blackarch packages may not work without an up-to-date system.' ;;
    esac
}

# setup blackarch linux
blackarch_setup()
{
    check_priv
    msg 'installing blackarch keyring...'
    make_tmp_dir
    fetch_keyring
    verify_keyring
    delete_signature
    check_pacman_gnupg
    install_keyring
    echo
    msg 'keyring installed successfully'
    # check if pacman.conf has already a mirror
    if ! grep -q "\[blackarch\]" /etc/pacman.conf; then
        msg 'configuring pacman'
        get_mirror
        msg 'updating pacman.conf'
        update_pacman_conf
    fi
    msg 'updating package databases'
    pacman_update
    msg 'BlackArch Linux is ready!'
}


blackarch_setup
`

**Comment by PedroSFreitas** [comment]
@gufkl 
As we said before, check your Network Settings (**Firewall, DNS, anything that could be interfering with your Network!**).

See if you can run this command alone:
```
gpg --keyserver pgp.mit.edu --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3 
```
If you can not, but can access via your browser this address: http://pgp.mit.edu/, then you probably have a Network issue/misconfiguration somewhere (which is impossible for us to determine since it can be a myriad of things).

One thing that you could try to solve this is running this command in the same directory as `strap.sh`:
```
sed -i s|pgp.mit.edu|18.9.60.141|g
```
And then run `strap.sh` again. But if it failed, then again check you Network.

**Comment by PedroSFreitas** [comment]
@gufkl any news on this?

**Comment by PedroSFreitas** [comment]
I just **tested** everything again on a Raspberry Pi 3 with a 8GB sdcard and **worked without a problem.**
And since the OP haven't replied, I'm closing this issue. If you think this is a mistake, just re-open the issue and provide further information.

**Thanks.**
