### ISSUE TITLE
sslyze Error

### ISSUE THREAD

**Issue by reloop2k** [BlackArch/blackarch#1783]
After installing in my arch box, following error ocures:

# sslyze -h
Traceback (most recent call last):
  File "/usr/sbin/sslyze", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

aur package works fine.

**Comment by noptrix** [comment]
can you switch to our main site (blackarch.org) as blackarch mirror in your pacman.conf and then do this: pacman -Syyu --needed --force blackarch. then try to run sslyze again

**Comment by reloop2k** [comment]
works fine now, thanks.
