### ISSUE TITLE
issues with wifi injection on existing arch installs

### ISSUE THREAD

**Issue by zetorian** [BlackArch/blackarch#1786]
Hello,

I recently noticed that while wifi injection test (a la aireplay -9 wlan0) works on blackarch iso's, it does not work on existing arch installs. For extra specificity i am using the iwlwifi driver on an intel 7260 internal laptop wifi card, which by all means should support injection. Injection also works with kali linux, which led me to believe is that the discrepancy is caused by a missing firmware/kernel patch. Probably like this one [here](http://git.kali.org/gitweb/?p=packages/linux.git;a=blob_plain;f=debian/patches/features/all/kali-wifi-injection.patch;hb=refs/heads/kali/master). I would very much like to avoid resorting to, firstly out of principle because it is not a part of arch, and secondly it is not up to date as it is meant for kernel 4.12. 

As injection is working for me on a blackarch iso, and I saw in a twitter post a while ago that blackarch has a patched kernel for injection, I am assuming that a similar patch exists somewhere for us as well. I cannot for the life of me find it, so if anyone would be willing to point me in the right direction of either patched firmware, kernels or even just the patch itself as I am more than capable of applying it that would be greatly appreciated.

it might also be helpful to post such a patch on the git hub repository, so that a PKGBUILD could be made for those of us who use existing installs.

Thanks much.

**Comment by zetorian** [comment]
update: i have tried to recompile the kernel with the backports patch "50-1-mac80211.compat08082009.wl_frag+ack_v1.patch" found in the blackarch repository, but that fails in the middle of the wireless drivers, i assume at mac80211, but i cant be sure.
my best guess is that this is that this patch has become depreciated.

if someone  could please post a solution that would be extremely helpful.
thanks much!

**Comment by PedroSFreitas** [comment]
@zetorian 
Thanks for your message.

For now we don't use a patched kernel, it's the same in Archlinux.
Although we're going to work on that and soon we'll have some news.
