### ISSUE TITLE
Hanging @ installing /usr

### ISSUE THREAD

**Issue by FloopDaPig** [BlackArch/blackarch#1788]
As above.... should take about 5min to transfer 20g @ usb speeds.... been a few hours....
Complete newb... no idea what info im supposed to send... suffice to say i tried to follow the install guide but my install looked very different to the guide.....

**Comment by FloopDaPig** [comment]
As far as I can tell I've followed the guide to the letter.... Although some people have mentioned issues using ext4... As per the guide.... Apparently this can cause issues and I should only use fat32?  Only thing I can think of is that I went for full encryption....  Is it encrypting as it installs and causing the problem?  I have obvious activity on all drives and connections.

**Comment by PedroSFreitas** [comment]
I don't believe you will have any problems using `ext4`.

Unfortunately I'm not familiar with the encrypted installation (I'm working on it :P), let's see if others can help you on that. Sorry.

**Comment by FloopDaPig** [comment]
Oh look! It seems to have moved onto the next stage! Patience is key apparently.....  Total of 6hrs..... Wow.

**Comment by mrtnrdl** [comment]
Did you have slow data transfer rates with that usb stick on other occasions? Might be an old & slow one..

**Comment by FloopDaPig** [comment]
Nah, i'm pretty sure it was because I was using an atapi bridge. (external hdd dock). Probably not great speeds. never really tested it speed wise... usually only use it to recover drives. Thanks for all the help!
