### ISSUE TITLE
boot from USB ISO error

### ISSUE THREAD

**Issue by samsonbull** [BlackArch/blackarch#1791]
When booting from the ISO using a USB I get the following error and Google was not very helpful:

[     10.343431] squashfs: SQUASHFS error: unable to read matter id index table.

The computer is a HP Elitebook Ultrabook with a SSD 500G and 16G of ram.  It already has Arch Linux installed on it.

 Any suggestions for a newbie?

**Comment by PedroSFreitas** [comment]
Could you provide more info, such as:

- Are you using the latest ISO file?

- How did you burn the ISO?
 
- Any other error messages?

**Thanks**.

**Comment by samsonbull** [comment]
Sorry, as i should have included that as well:
ISO used: blackarchlinux-live-2017.08.30-x86_64.iso

burned to USB flash drive using the following command on a Macbook:  sudo dd if=/Users/Samson/Desktop/blackarchlinux-live-2017.08.30-x86_64.iso of=/dev/disk7 bs=1m

booted to USB flash drive on the laptop and got the following output after it default to boot the BlackArch image:

:: running early hook [udev]
starting version 234
:: running early hook [archiso_pxe_nbd]
:: running hook [udev]
:: Triggering uevents...
[      9.477333]  [drm:intel_set_cpu_fifo_underrun_reporting [i915]] *ERROR* uncleared underpin on pipe A
[      9.477428]  [drm:intel_cpu_fifo_underrun_irq_handler [i915]] *ERROR* CPU pipe A FIFO underpin
:: running hook [memdisk]
:: running hook [archiso]
:: running hook [archiso_loop_mnt]
:: running hook [archiso_pxe_common]
:: running hook [archiso_pxe_nbd]
:: running hook [archiso_pxe_http]
:: running hook [archiso_pxe_nfs]
::Mounting '/dev/disk/by-label/BLACKARCH_201708' to '/run/archiso/nootmnt'
::Device '/dev/disk/by-label/BLACKARCH_201708' mounted successfully.
::Mounting /run/archiso/cowspace (temps) filesystem, size=256M...
::Mounting '/dev/loop0' to '/run/archiso/sfs/airootfs'
[  10.343431] squashfs: SQUASHFS error: unable to read matter id index table
mount: /run/archiso/sfs/airootfs: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
ERROR; Failed to mount '/dev/loop0'
     Failing back to interactive prompt

This is on a HP EliteBook 840 G1

**Comment by PedroSFreitas** [comment]
Strange.

I'd recommend you to check the shasum of the ISO file, see if it's matching the one in our webpage.
If not, make sure to download a new one, check again the shasum and burn the ISO.
If the shasum matches already, just try to burn again the ISO. Something went wrong there, probably.

**Comment by samsonbull** [comment]
Just tried that and had the exact same result.

Results of sha1 file hash check: 4ca5ece4b915a4cb9a930379003bed3fd806e081
Matched with what was on site: 4ca5ece4b915a4cb9a930379003bed3fd806e081

Output of the ISO burn to a USB flash drive:
TMacBook-Pro-2:Project samson$ diskutil unmountDisk /dev/disk5
Unmount of all volumes on disk5 was successful
MacBook-Pro-2:SE Project samson$ sudo dd if=/Users/samson/Desktop/blackarchlinux-live-2017.08.30-x86_64.iso of=/dev/disk5 bs=1m
7812+0 records in
7812+0 records out
8191475712 bytes transferred in 2794.387688 secs (2931403 bytes/sec)

This is a good laptop so I am not sure what is going on.  I had Kali, and then BackBox running successfully on it prior to this. Any other ideas?

**Comment by samsonbull** [comment]
UPDATE-  I gave up on the full ISO and downloaded the Net Install package.  I followed the same methodology on burning it to the USB stick.  I walked through the install that way and it worked like a champ.  It is now running on my Elitebook.  Time to start digging around.  Thank you.

**Comment by samsonbull** [comment]
I left a small donation for this great project. Thank you for your time and correspondence.

**Comment by PedroSFreitas** [comment]
@samsonbull 

Glad that you found a way for that.
Too bad I couldn't pin point the exactly problem there.

**Thanks for your donation**. Would you like to have your name/nick on the Donation Page (https://blackarch.org/donate.html)?

note: "closing" this issue.
