### ISSUE TITLE
[Update Tool] RSPET v1.0.0 will (probably) break the PKGBUILD for it

### ISSUE THREAD

**Issue by panagiks** [BlackArch/blackarch#1801]
Hello,

I'm the maintainer/developer of [RSPET](https://github.com/panagiks/RSPET). I just wanted to drop you a quick heads-up for an upcoming release of RSPET that, along with all the new goodies that have been added, I'm quite sure will break the [PKGBUILD](https://github.com/BlackArch/blackarch/blob/master/packages/rspet/PKGBUILD) that you have for RSPET.  So in an attempt to redeem my self for it I thought I'd give you a quick list of the things the new version need to work (and a few tools I've added to help with those):

* Directory: /etc/rspet/ (either chmod 0777 or chown to the user:group that will run RSPET)
* Directory: /etc/rspet/plugins/ (either chmod 0777 or chown to the user:group that will run RSPET)
* Directory: /etc/rspet/plugins/client/ (either chmod 0777 or chown to the user:group that will run RSPET)
* File: /etc/rspet/config.json (Found under server/config/ in RSPET repo, either chmod 0666 or chown to the user:group that will run RSPET)
* Directory: /var/log/rspet/ (either chmod 0777 or chown to the user:group that will run RSPET)

Additionally:

* File structure of the project has changed. Now server and client are separated in different folders (this could theoretically allow for separate packaging/installation)
* The server module now depends on Python3 (and a few new pip packages, some are available in arch repos some are only in PyPi)
* Some PATH setting may be required to recognize the namespacing used in the files (only for the server module, client remains a self-sufficient script)

Possible solution:

What I have managed to do to make installation easier is to somewhat streamline the installation of the server module through wheels. 
```sh
cd server
python setup.py bdist_wheel
pip install --user dist/rspet_server-${pkgver}-py3-none-any.whl[rest]
sudo env "PATH=$PATH" rspet-server-setup
```
I am not sure how feasible is a solution like the above with PKGBUILD (don't really have any experience with packaging for Arch).

The Release Candidate for v1.0.0 of RSPET can be found on [this branch](https://github.com/panagiks/RSPET/tree/v1.0.0_rc) and you can expect that the file structure and dependencies will not change before the release.

If there is any change that you would like to suggest (to make packaging for Arch easier) or if you would like me to delay the release until someone has time to look into adjusting the PKGBUILD feel free to drop me a line here. 

Again, sorry for the inconvenience of having to re-write the PKGBUILD, thank you for including RSPET to BlackArch's packages and thank you for an awesome pen testing distro!

**Comment by NovaCygni** [comment]
Im doing a bunch of the tool requests PKGBUILDS atm ill have a look at streamlining your "HotFix" as a Post-Install, if not just rewriting the new PKGBUILD. 

./Assigns-Self

**Comment by noptrix** [comment]
@panagiks thanks for the follow-up. @NovaCygni any news on this? have you tried to change using the current pkgbuild? shall i take a look?
