### ISSUE TITLE
[Tool request] Amber

### ISSUE THREAD

**Issue by EgeBalci** [BlackArch/blackarch#1803]
https://github.com/EgeBalci/Amber

Latest update added arch linux compatibility.

**Comment by EgeBalci** [comment]
@noptrix could you give me a hand with this ?

**Comment by noptrix** [comment]
@EgeBalci yes, sure. but we are in a 'updating all tools' phase. once we finished updating all tool amber and others will be added. could take a week or so.

**Comment by EgeBalci** [comment]
Thanks.

**Comment by noptrix** [comment]
sorry for the delay @EgeBalci. it's been added now. thanks for your patient
