### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by gofish543** [BlackArch/blackarch#1808]
After running fresh install after fresh install trying everything on the internet I cannot get Blackarch linux to work on my laptop.

After installing no applications work, even after running the proper pacman update commands (Which fail anyway on the mono application)

The exceptions all say cannot find /usr/bin/{program name}

How can I get this to work?

**Comment by gofish543** [comment]
https://github.com/BlackArch/blackarch/issues/1663
https://github.com/BlackArch/blackarch/issues/1009
https://github.com/BlackArch/blackarch/issues/1073

I have tried the three solutions above to no avail.

**Comment by ikstream** [comment]
Are you installing it directly onto your Laptop, or to VM?
Are you trying to install all tools?
In case you are trying to install all tools is there somewhat around 30GB space left in your root partition?

**Comment by NovaCygni** [comment]
You look like yourve probably not installed blackarch correctly, or have at some stage broken something, likely permissions, and I would guess your installing blackarch on a Non-Pure Archlinux install, Ie Antargos or Manjaro? If so they can be installed fine with no problems, though at this stage if its not critical to keep what your already installed distro you might be better of installing a pure Archlinux install with "Archlinux Anywhere Iso". and then installing Blackarch onto that is seemless...

**Comment by gofish543** [comment]
I am doing a fresh install of black arch Linux on my laptop which has 1 tb of space. 500mb for boot partition, 512 for swap and 930gb for root. The hard drive is empty when I do the install, no other form of Linux is on it.

**Comment by NovaCygni** [comment]
Use the Archlinux Anywhere ISO, itll resolve alot of common problems and automate a few things for you.

**Comment by myrage2000** [comment]
I think ArchLinux Anywhere ISO is now called Anarchy and adds its own repository in pacman.conf.
You could also use Revenge installer (I think UEFI is not working).
Never use Antergos (your system will not be stable because it adds its repositories before archlinux's ones in pacman.conf)

You can also install BlackArch on Manjaro (select unstable branch so you get updates earlier)

**Comment by gofish543** [comment]
Right on. Thanks for the helpful comments.
I tried the anyarch and it appears to be working.

**Comment by ninjaspl0it** [comment]
Hey, just thought I would add to this in case more run into this. I experienced same problem. Installing BlackArch from live usb as the main OS on a HP Elitebook. GRUB loaded, but no installation was found. /boot/ on my root partition was empty. I was able to solve this without using a new anarchy iso by doing the following:

1. boot into the live cd.
2. mount the root partition somewhere. (mount /dev/sda*3* /mnt), use "blkid -o list" if you need a list with UUID.
3. enter the mounted partition in /mnt, "arch-chroot ." from the root partition.
4. Now also mount the efi partition on your live usb, "mount /dev/sdb2 /mnt" on my system
5. Install the linux package. "pacman -S linux", "pacman -S linux-lts" to the root partition.

Reboot your system.
Enter GRUB-> type "ls" to list partitions. 
Find your root partition. Verify there's an image in /boot (ls (hd0,msdos3)/boot/

grub> set root=(hd0,msdos3)
grub> linux /boot/vmlinuz-linux root=/dev/sda3
grub> initrd /boot/initramfs.img
grub> boot

I was able to boot my system after this

**Comment by HOLY-FROMAGE** [comment]
hi, this is not working on luks encrypted partitions. any workaround?

**Comment by Eric-Zhang007** [comment]
@floppywiggler Thanks for your adding! It's so kind of you to help a noob out of trouble!
