### ISSUE TITLE
First boot error cannot open login 

### ISSUE THREAD

**Issue by shnnxn** [BlackArch/blackarch#1809]
i installed the blackarch on my laptop which is dual booted with windows10 and parrotsec os  and bios mode is LEGACY, and overwrite the blackarch on my parrotsec OS partition now , i used live cd to install and everything seem well during install but after the install when i try to open the blackarch it stuck on boot with message "cannot open login".how to fix this knowing this is first boot i dont think i can go into recovery and update or delete something 
P.S: i have been using debian based linux for almost 6 years . but first time with arch based so please help me

**Comment by ikstream** [comment]
Are there any additional messages during boot, indicating, that there is something wrong with your installation?
I will see if i can reproduce your issue, but it sounds to me, like there went something wrong during installation.

**Comment by shnnxn** [comment]
here is the attached image of issue [
![img_20171107_165538](https://user-images.githubusercontent.com/21156232/32491494-ec6de752-c3dc-11e7-96f0-c43c7264bb3f.jpg)
](url)

**Comment by shnnxn** [comment]
during the directory setup in installing blackarch i choose the existing partition 
for boot partition i choose sda1 (which is my boot partition)
for root i choose sda8 (which is my parrot sec Os partition) 
for swap i choose sda7 (which again was my parrot sec swap )

**Comment by ikstream** [comment]
So I would guess that the problem would be: "Failed to start Create Volatile Files and Directories"
There are several links related to this out there for arch. You could check, if any of them applies to your problem.

https://bbs.archlinux.org/viewtopic.php?id=199940
https://bbs.archlinux.org/viewtopic.php?pid=1736016
https://bbs.archlinux.org/viewtopic.php?id=208399
https://bbs.archlinux.org/viewtopic.php?id=196341

**Comment by shnnxn** [comment]
i am sorry guys but i really need to work so i shifted back to parrotsec . but i will try blackarch again after sometime then iwill let you know about the posted solution

**Comment by myrage2000** [comment]
Hey,
You have to install archlinux with the following configuration :
- mount /dev/sda8 /mnt
- mkdir /mnt/boot && mkdir /mnt/boot/efi
- mount /dev/sda1 /mnt/boot/efi
- swapon /dev/sda7

You should not mount your /dev/sda1 partition on /boot, but on /boot/efi instead.
You could also create a separate /boot partition (you have to do it if you want to encrypt your root partition).

You should install ArchLinux first and then add BlackArch repositories (for me it was easier)...
You can then install the WM by installing either openbox, fluxbox or awesomeWM and then installing blackarch-config-[your WM].

**Comment by urloong** [comment]
hey, guys, did u fixed this problem?

**Comment by easytouse2016r** [comment]
I install system again on virtual machine BlackArch Linux 32 bit Live ISO (You choose which version you want 32 or 64) - blackacrh-install, with the options (3) from the source, and I did not set the encryption, cfdisk (dos) 1GB Bot* (ext4), 2GB Swap, 37GB Rot(ext4). I added a regular user, (flux) manager. I did not install any tools during installation. I install grub, after finish reboot after start system,  I used (tty) ctr+alt+f2  and  I am log in {root and pasword} after {systemctl start dhcpcd@enp0s3.service} after {pacman -Syyu --force --needed blackacrh} notification {install all tools(default/all) 1-1705} after {pacman -Syyu --force --needed blackacrh} notification {install all tools(default/all) 1707-18..reste} after {pacman -Syyu --force --needed blackacrh} notification {install all tools(default/all) 1-1705} after {pacman -Syyu --force --needed blackacrh} notification {install all tools(default/all) 1707-18..reste} and reboot everything works *(problem with the program, veil(1706) package mono adin 1.1-1 , that blocks install all tools in one moment used (all))

**Comment by easytouse2016r** [comment]
before (blackarch-install) i connected to the internet (during install-network setup -> 3. Skip (use this if you are already connected)

**Comment by PedroSFreitas** [comment]
@shnnxn sorry you hear you have to shift to Parrot OS.
and sorry for the delay. But I think it's safe to say we have figured out the problem and it will be fixed in the near future. Probably with the next release.

Note: we'll close this issue in order to maintain a single one: #1837 which is pretty much the same.
