### ISSUE TITLE
replace unmaintained skipfish

### ISSUE THREAD

**Issue by Silur** [BlackArch/blackarch#1810]
original author hasn't updated since 2012, version 2.11 https://github.com/Silur/skipfish includes updated openssl, fixed proxying, single step installation. Web frontend update and more sophisticated tests coming.

**Comment by noptrix** [comment]
thank you. i will review the changes and update it soon

**Comment by Silur** [comment]
wow indeed I had this one too

**Comment by ikstream** [comment]
@Silur the mentioned repo does no longer exist, so i am closing this issue.
If you just moved the repository somewhere els please provide the new link
