### ISSUE TITLE
[Tool Request] BFAC

### ISSUE THREAD

**Issue by mazen160** [BlackArch/blackarch#1811]
BFAC (Backup File Artifacts Checker) is an automated tool that checks
for backup artifacts that may disclose the web-application's source
code. The artifacts can also lead to leakage of sensitive information,
such as passwords, directory structure, etc..

Homepage: https://github.com/mazen160/bfac

Thanks,
Mazin Ahmed

**Comment by noptrix** [comment]
thanks;added
