### ISSUE TITLE
[Tool Request] Cr3dOv3r

### ISSUE THREAD

**Issue by sbani** [BlackArch/blackarch#1816]
Quote from repo:
>Cr3dOv3r simply you give it an email then it does two simple jobs (but useful) :
>
>- Search for public leaks for the email and if it any, it returns with all available details about the leak (Using hacked-emails site API).
>- Now you give it this email's old or leaked password then it checks this credentials against 16 websites (ex: facebook, twitter, google...) then it tells you if login successful in any website!

Homepage: https://github.com/D4Vinci/Cr3dOv3r

Thanks,
sbani

**Comment by noptrix** [comment]
thanks. added

**Comment by sbani** [comment]
thank you @noptrix
