### ISSUE TITLE
Won't Start to Install

### ISSUE THREAD

**Issue by TheEnchantedCow** [BlackArch/blackarch#1817]
My crappy, [Dell Inspiron 3000](https://www.amazon.com/Dell-i3168-0028BLU-Laptop-Celeron-Windows/dp/B01F3R9136/ref=sr_1_4?ie=UTF8&qid=1511028727&sr=8-4&keywords=dell+inspiron+3000&dpID=41cnVcGV3UL&preST=_SY300_QL70_&dpSrc=srch)  ( <--- similar to that link...)

Isn't installing right, It goes to the boot menu with the BlackArch Linux archiso x86_64 UEFI CD and when I press enter it take a bit then a very small amount of code flashes on the screen then goes black. The USB drive I am using to install it is flashing as if its reading. I waited for a long time and it's not doing anything but that! Should I use a different image?!?!?!?!?!?

**Comment by myrage2000** [comment]
Hey, what did you use to write the image to your USB key ?
Try to use rufus and change "ISO" to "DD" in the options.
You could also install archlinux first, and then add BlackArch's repos.

**Comment by TheEnchantedCow** [comment]
I used [Etcher](https://github.com/resin-io/etcher). Its a really good img/iso writer so I doubt its the problem with this. I have installed many other images and OSs with the method, but I'll try _Rufus_.

Before I've also tried Arch Linux and that didn't install well either on this crappy laptop.

![image](https://user-images.githubusercontent.com/23041791/32994410-a6bd9f32-cd2c-11e7-8721-9c1e6229f056.png)

![image](https://user-images.githubusercontent.com/23041791/32994415-c3a9a4e2-cd2c-11e7-9d4d-38bc0bada9be.png)

When I tried Rufus It told me to do this. Oh wait now I clicked the DD option.

![image](https://user-images.githubusercontent.com/23041791/32994418-da8dd25a-cd2c-11e7-8840-760e75912e37.png)

Now it's writing, I think... I'm such a noob when It comes to Linux.

Then when I finished writing the image file to the drive I plugged it in and booted up the crappy laptop...

After that, I came across the main menu screen and let it autoselect the first option. Then the expected came. The screen turned black without any code and did the same thing as I mentioned before.

PLEASE SEND HELP!

I think I may just bee that this computer uses odd drivers for the graphics. Can anyone confirm that for me?!

**Comment by NotANormie** [comment]
Hold on second... You are formatting it in NTFS? That can't be right. You sure you didn't change it from FAT32 (which it should be)?

**Comment by TheEnchantedCow** [comment]
Okay, an update. I got it to finally boot as a Live CD. The problem was that I wasn't using Legacy boot. I was using UEFI boot where you choose a file in the drive to boot from. This was a mistake. Now I just need to find out how to install it from the live cd.

**Comment by 15045815396** [comment]
如果可以的话，你可以使用Win32_Disk_Imager试一下，我之前就是使用这款软件写入的系统，希望能帮助到你

**Comment by PedroSFreitas** [comment]
@TheEnchantedCow 
> Before I've also tried Arch Linux and that didn't install well either on this crappy laptop.

BlackArch is an modular extension of Arch Linux. If you can't install Arch on it, you probably won't be able to do with BlackArch.
Although I find quite unlikely the idea of not being able to install Arch. Make sure you did everything okay.

> Okay, an update. I got it to finally boot as a Live CD.

I'm closing this issue since you already found the solution to your problem.
