### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by tedat105** [BlackArch/blackarch#1820]
When i try to login there is a login loop

**Comment by Emils72** [comment]
I have the same problem. Just installed on VBox from the netinstall iso...
Every time it jumps back to the login form... :(

**Comment by noptrix** [comment]
Can you guys please choose another window manager rather than the default=fluxbox and let me know if it still jumps back?

**Comment by Emils72** [comment]
Sorry for my noobness... how do I change the window manager?

**Comment by patman96** [comment]
Same here.. There is only the option default & blackarch-dwm and both of them won't work.

**Comment by CodeGuro** [comment]
Does installer v0.6.1 still have this issue?
I downloaded blackarch v0.6 through the official website about 9 hours ago and came across this issue. I simply selected the default and it said fluxbox (and some other WM) couldn't install and simply continued.

Unfortunately, like patman96, I had only (default) and (blackarch-dwm) options at login, and neither worked. If I entered the right password for either the user or the root, it'd just loop back to login after trying to kick of xstart.

Please take a look into this.

**Comment by cha0tic75** [comment]
I am still getting this login loop after switching desktop.  Like above, there are only 2 options: Default, and BlackArch-Dwm.  Did this work for anyone else?  Maybe installing BlackArch on top of ArchLinux is the way to go?

**Comment by noptrix** [comment]
Did you guys selected the default value 'install all WMs'? I had no issues with the logins when installing and choosing between various WMs. Also, did you guys add a separate normal user? In the meanwhile I will have to take a look and retry the installer.

**Comment by noptrix** [comment]
Btw: It seems that many ppl got hit by this 'bug'. I am not sure if this is really a pro-active bug or if ppl miss something while using the installer. I will test the installer soon and fix it in case of a clear bug and I will let you know soon. Let's keep this issue open then.

**Comment by patman96** [comment]
Created standart User and also selected all wi dow manager. Tried it 2 times - same issue. I used  the netinstall iso, crated partition schema as in the tutorial, installed all blackarchtools. Only errors that I got during install was some dependencie Problems which you can not fix during install. 
For now I just use it wihout GUI.

**Comment by noptrix** [comment]
@patman96 Could you do me a favour and try to install without adding a user and let me know if still same issue? Then later on you can still add one...

**Comment by h0pes** [comment]
Got the exact same issue when trying to install [http://ftp.halifax.rwth-aachen.de/blackarch/iso/blackarchlinux-live-2017.11.24-x86_64.iso](url) on VMWare 14 Workstation under Windows 10 Host.
I think there is a problem when selecting the default:all option for Window Managers install. If I choosed 8 (install all) I see an error about "impossible to create `/mnt/somedir`. This happens regardless I added a second user apart root or not.
I was successful only when choosing only one Window Manager (in my case option 3, Fluxbox). Then everything works as expected (apart the fact that the installer does not seem to remember the locale for the keyboard - I choosed `it` during initial install steps). But on the login page there is the combo box about languages so I can easily switch from the us to my desired language before typing the user and password).

**Comment by noptrix** [comment]
Yes, yes. Ok guys, I found the bug and already fixed it. I will release a new version of the installer in a bit. You can then do: pacman -Syy && pacman -S blackarch-installer and restart with version 0.6.2. We will also release the new ISOs by tomorrow or this evening. Cheers

**Comment by noptrix** [comment]
And here we go: https://github.com/BlackArch/blackarch-installer/releases - please install 0.6.2. I will keep this ticket open until we released the new ISOs with the fixed version of the installer

**Comment by noptrix** [comment]
new isos released: https://blackarch.org/downloads.html - includes the installer v0.6.2. bugs fixed. re-open this ticket if you still encounter the same bug

**Comment by CodeGuro** [comment]
This bug was fixed with the new release. Thanks.

**Comment by samspei0l** [comment]
I have blackarch install on my laptop after booting today morning I am having problem login. Whenever I enter the credentials it goes to login loop. i have an extra user other than root. I have tried with every WMs and every credentials. I updated my system yesterday. Need Help ASAP!!!!!!!!!!!!!!

**Comment by ikstream** [comment]
This is most likely related to #2835. Please don't use three year old issues, if they are closed.
