### ISSUE TITLE
ERROR: invalid keyring signature

### ISSUE THREAD

**Issue by backd00r101** [BlackArch/blackarch#1822]
When i run strap.sh to install black arch tools, i get "ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch"
I tried alot of solutions but none worked 
output of  sh -x strap.sh :
+ MIRROR=https://www.mirrorservice.org/sites/blackarch.org/blackarch/
+ blackarch_setup
+ check_priv
+ '[' 0 -ne 0 ']'
+ msg 'installing blackarch keyring...'
++ tput bold
++ tput setaf 2
++ tput sgr0
+ echo '[+] installing blackarch keyring...'
[+] installing blackarch keyring...
+ make_tmp_dir
++ mktemp -d /tmp/blackarch_strap.XXXXXXXX
+ tmp=/tmp/blackarch_strap.gRRVmS52
+ trap 'rm -rf /tmp/blackarch_strap.gRRVmS52' EXIT
+ cd /tmp/blackarch_strap.gRRVmS52
+ fetch_keyring
+ curl -s -O 'https://www.blackarch.org/keyring/blackarch-keyring.pkg.tar.xz{,.sig}'
+ verify_keyring
+ gpg --keyserver http://pool.sks-keyservers.net --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3
+ gpg --keyserver-options no-auto-key-retrieve --with-fingerprint blackarch-keyring.pkg.tar.xz.sig
+ err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
++ tput bold
++ tput setaf 1
++ tput sgr0
+ echo '[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch'
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
+ exit 1337
+ rm -rf /tmp/blackarch_strap.gRRVmS52

**Comment by yanganto** [comment]
I got the same problem. Beside, I try to use 18.9.60.141 instead of pgp.mit.edu or connecting internet via different provider, but still got the invalid keyring error.

**Comment by PedroSFreitas** [comment]
Please, take your time to read this entire comment.
https://github.com/BlackArch/blackarch/issues/1122#issuecomment-346616342

**Comment by PedroSFreitas** [comment]
@yanganto let's keep the dialog here, since that thread is a different one.

What I have proposed was simple steps that could lead you to a solution, not solution was provided. As I said in the comment linked above, the `strap.sh` will throw `invalid keyring` message on the first error regarding:

1. Internet problem;
2. Network issue;
3. Clock issue;
4. DNS issue; and/or
5. any type of misconfiguration or network issue that could block your communication with mit.edu. 

It's not something that we can help, since it can be myriad of things that only you knows about your system. And as my comment states, the script is working fine under a new regular Arch Linux system.

Take your time to troubleshot your installation and configurations.

**Comment by backd00r101** [comment]
Thanks alot @PedroSFreitas It worked!, but another question please, am i able to view the blackarch menu in manjaro deepin? i downloaded blackarch-menus but nothing appears

**Comment by yanganto** [comment]
I can use gpg command to connect pgp.mit.edu server. The connection can construct, but I still can not receive the key. 

```
$ gpg --keyserver https://pgp.mit.edu --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
$ echo $?                                                                                 
2
```

**Comment by PedroSFreitas** [comment]
@backd00r101:
Unfortunately (or fortunately :P) I'm not familiar with Manjaro neither any Desktop Environment used with BlackArch tools (BA ships with WMs, not DEs).

@yanganto on your command you're using HTTPS, you shouldn't. Try again without it, please.

**Comment by yanganto** [comment]
I edit the script for show the error message, and find out the trustdb is corrupted.
I think I am close to the real problem.

```
verify_keyring()
{
    gpg \
        --keyserver hkp://pgp.mit.edu:80 \
        --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3 > /dev/null 2>&1

    if ! gpg \
        --keyserver-options no-auto-key-retrieve \
        --with-fingerprint blackarch-keyring.pkg.tar.xz.sig
    then
        err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
    fi
}

```

> [+] installing blackarch keyring...
> gpg: WARNING: no command supplied.  Trying to guess what you mean ...
> gpg: assuming signed data in 'blackarch-keyring.pkg.tar.xz'
> gpg: Signature made Mon 20 Jan 2014 12:36:55 AM CST
> gpg:                using RSA key 63EC0ADBEA87E4E3
> gpg: lookup_hashtable failed: Unknown system error
> gpg: trustdb: searching trust record failed: Unknown system error
> gpg: Error: The trustdb is corrupted.
> gpg: You may try to re-create the trustdb using the commands:
> gpg:   cd ~/.gnupg
> gpg:   gpg --export-ownertrust > otrust.tmp
> gpg:   rm trustdb.gpg
> gpg:   gpg --import-ownertrust < otrust.tmp
> gpg: If that does not work, please consult the manual
> [-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch

**Comment by PedroSFreitas** [comment]
@yanganto any follow up on this?
have you tracked it down?

I just tested the script, it ran okay on a virtual machine.

**Comment by yanganto** [comment]
@PedroSFreitas 
I modify the gpg verification part of the script and install the Black Arch, thank you.
Following is the script I used.
```
#!/bin/sh
# strap.sh - install and setup BlackArch Linux keyring

# default mirror url
MIRROR='https://www.mirrorservice.org/sites/blackarch.org/blackarch/'

# simple error message wrapper
err()
{
    echo >&2 `tput bold; tput setaf 1`"[-] ERROR: ${*}"`tput sgr0`
    exit 1337
}

# simple warning message wrapper
warn()
{
    echo >&2 `tput bold; tput setaf 1`"[!] WARNING: ${*}"`tput sgr0`
}

# simple echo wrapper
msg()
{
    echo `tput bold; tput setaf 2`"[+] ${*}"`tput sgr0`
}

# check for root privilege
check_priv()
{
    if [ $EUID -ne 0 ] ; then
        err "you must be root"
    fi
}

# make a temporary directory and cd into
make_tmp_dir()
{
    tmp=`mktemp -d /tmp/blackarch_strap.XXXXXXXX`
    trap "rm -rf $tmp" EXIT
    cd "$tmp"
}

# retrieve the BlackArch Linux keyring
fetch_keyring()
{
    msg 'fetch keyring'
    curl -s -O 'https://www.blackarch.org/keyring/blackarch-keyring.pkg.tar.xz{,.sig}'
}

# verify the keyring signature
# note: this is pointless if you do not verify the key fingerprint
verify_keyring()
{
    msg 'recv key'
    gpg \
        --keyserver hkp://pgp.mit.edu:80 \
        --recv-keys 4345771566D76038C7FEB43863EC0ADBEA87E4E3
    msg 'verify'
    if gpg --verify blackarch-keyring.pkg.tar.xz.sig blackarch-keyring.pkg.tar.xz
    then
        err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
    fi
    msg 'passed'
}

# delete the signature files
delete_signature()
{
    if [ -f "blackarch-keyring.pkg.tar.xz.sig" ] ; then
        rm blackarch-keyring.pkg.tar.xz.sig
    fi
}

# make sure /etc/pacman.d/gnupg is usable
check_pacman_gnupg()
{
    pacman-key --init
}

# install the keyring
install_keyring()
{
    if ! pacman --config /dev/null --noconfirm -U blackarch-keyring.pkg.tar.xz
    then
        err 'keyring installation failed'
    fi
        # just in case
        pacman-key --populate
}

# ask user for mirror
get_mirror()
{
    printf "    -> enter a BlackArch Linux mirror url (default: $MIRROR): "
    while read line ; do
        case "$line" in
            http://*|https://*|ftp://*)
                msg 'checking mirror...'
                if ! curl -sI "$line/blackarch/os/i686/blackarch.db" |
                    head -n1 | grep -q 200
                then
                    warn 'blackarch.db not found on given mirror'
                    warn "using default mirror $MIRROR"
                else
                    MIRROR=$line
                    msg "using mirror $MIRROR"
                fi
                break
                ;;
            *)
                warn 'you did not specify a correct mirror url'
                msg "using default mirror $MIRROR"
                return
                ;;
        esac
    done < /dev/tty
}

# update pacman.conf
update_pacman_conf()
{
    # delete blackarch related entries if existing
    sed -i '/blackarch/{N;d}' /etc/pacman.conf

    cat >> "/etc/pacman.conf" << EOF
[blackarch]
Server = $MIRROR/\$repo/os/\$arch
EOF
}

# synchronize and update
pacman_update()
{
    pacman -Syy
}


pacman_upgrade()
{
    echo 'perform full system upgrade? (pacman -Su) [Yn]:'
    read conf < /dev/tty
    case "$conf" in
        ''|y|Y) pacman -Su ;;
        n|N) warn 'some blackarch packages may not work without an up-to-date system.' ;;
    esac
}

# setup blackarch linux
blackarch_setup()
{
    check_priv
    msg 'installing blackarch keyring...'
    make_tmp_dir
    fetch_keyring
    verify_keyring
    delete_signature
    check_pacman_gnupg
    install_keyring
    echo
    msg 'keyring installed successfully'
    # check if pacman.conf has already a mirror
    if ! grep -q "\[blackarch\]" /etc/pacman.conf; then
        msg 'configuring pacman'
        get_mirror
        msg 'updating pacman.conf'
        update_pacman_conf
    fi
    msg 'updating package databases'
    pacman_update
    msg 'BlackArch Linux is ready!'
}


blackarch_setup
````

**Comment by OMICRON3069** [comment]
I run the script above and still have problem.
```
+ echo '[+] verify'
[+] verify
+ gpg --verify blackarch-keyring.pkg.tar.xz.sig blackarch-keyring.pkg.tar.xz
gpg: Signature made Mon 20 Jan 2014 12:36:55 AM CST
gpg:                using RSA key 63EC0ADBEA87E4E3
gpg: Good signature from "Evan Teitelman <teitelmanevan@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 4345 7715 66D7 6038 C7FE  B438 63EC 0ADB EA87 E4E3
+ err 'invalid keyring signature. please stop by irc.freenode.net/blackarch'
++ tput bold
++ tput setaf 1
++ tput sgr0
+ echo '[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch'
[-] ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch
```
But I have already change gpg key`4345771566D76038C7FEB43863EC0ADBEA87E4E3`'s trust level to `I trust ultimately` manually.
So, how to solve this?
