### ISSUE TITLE
Smartphone-pentest-framework not found

### ISSUE THREAD

**Issue by Hax4us** [BlackArch/blackarch#1823]

**Comment by PedroSFreitas** [comment]
We're closing this issue because it doesn't contain any useful information in order for us to troubleshoot it.
Please re-open it if you have any further information to provide.

**Comment by Hax4us** [comment]
@pedrosfreitas I can't install this tool with pacman -S

**Comment by Hax4us** [comment]
This tool is mentioned in blackarch tools list

**Comment by PedroSFreitas** [comment]
What is the output of:

`pacman -Syy smartphone-pentest-framework`

**Comment by Hax4us** [comment]
Unable to locate package

**Comment by PedroSFreitas** [comment]
You could be using an out date mirror, which is odd but not unlikely.
Make sure to use a different one and run `pacman -Syy` before running `pacman -S smartphone-pentest-framework`.

List of mirrors: https://blackarch.org/downloads.html#mirror-list
