### ISSUE TITLE
Fix Empire framework

### ISSUE THREAD

**Issue by sparta3407** [BlackArch/blackarch#1830]
hey , can you please fix Empire framework , it does not work at all thanks

**Comment by noptrix** [comment]
sure and thanks for letting us know

**Comment by PedroSFreitas** [comment]
@sparta3407 do you mind sharing the errors you found (output would be nice)? I just would like to know if what you're facing is the same we can reproduce on our tests. Thanks in advance.

**Comment by noptrix** [comment]
@sparta3407 @PedroSFreitas should be fixed now. simply update and run as root inside /usr/share/empire/setup the 'reset.sh' script. then restart empire and/or create database first with the scripts inside 'setup'

**Comment by noptrix** [comment]
https://twitter.com/ghstrike/status/942525116679933952 - closing ticket. if still issues simply re-open ;)
