### ISSUE TITLE
Empire can't run

### ISSUE THREAD

**Issue by ztencmcp** [BlackArch/blackarch#1835]
Hi,

The following error shows when i launch empire.

<img width="563" alt="default" src="https://user-images.githubusercontent.com/22705390/34402230-47d88126-ebdb-11e7-8192-37ec7939635b.png">

I have tried to reset it and can't help .

**Comment by myrage2000** [comment]
RTFM is your answer.

> python2 /usr/share/empire/setup/setup_database.py

As simple as that.

**Comment by PedroSFreitas** [comment]
Closing...
As @myrage2000 said, you need to setup the database before running it (the installation process informs you of this).
