### ISSUE TITLE
Boot stops after [OK] Reached target Graphical Interface.

### ISSUE THREAD

**Issue by collin5** [BlackArch/blackarch#1837]
Just did a fresh install of black arch following instructions [here](https://blackarch.org/blackarch-install.html), then rebooted after successfull install.
**Actual behaviour**
Fails to open display manager after message `[OK] Reached target Graphical Interface.`
<img width="874" alt="screen shot 2017-12-31 at 05 29 46" src="https://user-images.githubusercontent.com/11579108/34458693-cdd96bf6-edec-11e7-82b7-80a7a695b283.png">

**Expected behaviour**
Should be able to load display manager.

**Comment by mikeybro** [comment]
I have this issue, but it is because I ran:
pacman -S nvidia
but this messed up the system somehow, not sure how, so I ran:
pacman -R nvidia
and now I am stuck where you are. 
I can mount the drive on check out the grub and other directories if needed, which is what I might do, but I would rather just re-install, the fresh install worked out fine from the live-ISO.. Maybe its a driver issue for you as while.

**Comment by ikstream** [comment]
If you want to run Black Arch virtualized check out https://github.com/BlackArch/blackarch-virtualization
It provides Docker- and Vagrantfiles.
What does systemctl --failed tell you? Are there any failed services?
Are there errors in your journalctl?

**Comment by collin5** [comment]
@ikstream  can't access terminal, doing *CTRL+ALT+F2* takes me back to the same screen after a few seconds.

**Comment by ikstream** [comment]
Which iso did you use?

**Comment by collin5** [comment]
@ikstream  I used this one http://ftp.halifax.rwth-aachen.de/blackarch/iso/blackarchlinux-live-2017.12.11-x86_64.iso Found it on https://blackarch.org/downloads.html

**Comment by PedroSFreitas** [comment]
Sorry for the delay.
I think it's safe to say we have figured out the problem and it will be fixed in the near future. Probably with the next release.

**Comment by netzwerg-au** [comment]
I have to admit, I am finding trying to get Blackarch up and running on Hyper-V entirely frustrating (to be honest, Hyper-V is entirely frustrating, but I have no other choice right now).  I have tried installing from the Live ISO, which fails on both Gen1 and Gen2 VMs.  I have tried downloading the OVA, converting the HDD from a vmdk to a vhd and importing, but it craps out as it thinks it can't find a particular disk.  I thought I was getting somewhere with the netinst, but now I have this "Reached target Graphical Interface" issue.  I guess I am going back to Kali for now.  Hopefully this issue can be addressed soon.

**Comment by noptrix** [comment]
we will see how tof ix this issue now before we release the new ISOs.thanks for your patient

**Comment by markstachowski** [comment]
Still no steps on how to fix this issue?

**Comment by VincentXS** [comment]
me too,thats bad

**Comment by PedroSFreitas** [comment]
@markstachowski @VincentXS we'll release a new ISO on June 1st that should fix it.

**Comment by noptrix** [comment]
all, we will release the new ISOs and OVA on the 1st of June, as @PedroSFreitas mentioned. This issue should be fixed then.

**Comment by PedroSFreitas** [comment]
**Attention all**, we have released new ISO and OVA images, as well as bug-fixes on the installer. Please, download the new image; since we hope those bugs are fixed.

Sorry for the inconvenience.

**Comment by aadancade2** [comment]
yes me too , MR : VincentXS plz help me for this
