### ISSUE TITLE
[Tool removal request] pacaur

### ISSUE THREAD

**Issue by myrage2000** [BlackArch/blackarch#1839]
Pacaur is now unmaintained :
As mentioned here : https://bbs.archlinux.org/viewtopic.php?pid=1755144#p1755144
The GitHub page is now ready-only : https://github.com/rmarquis/pacaur

Trizen seems to be a good aur helper.

**Comment by PedroSFreitas** [comment]
@myrage2000 Thanks for bringing this up. I'll take a look at Trizen.

**Comment by ReK2Fernandez** [comment]
yeah please add Trizen or something similar to Pacaur. tx <3

**Comment by noptrix** [comment]
@myrage2000 Hi. Thanks for letting us know. Yep, trizen seems to be a good alternative although written in Perl...We are still reviewing few of the alternatives. Once done we will replace pacaur with $alternative and close this issue here.

**Comment by ReK2Fernandez** [comment]
agghh perl.. noo so 2001 :P  ruby/python/go/rust <----  👍

**Comment by noptrix** [comment]
thanks guys. pacaur has been removed and trizen is added, now.

**Comment by PedroSFreitas** [comment]
Done.
