### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by mikeybro** [BlackArch/blackarch#1842]

**Comment by PedroSFreitas** [comment]
I don't think so.

**Comment by ReK2Fernandez** [comment]
why will it be dead?

**Comment by mikeybro** [comment]
Well, maybe I haven't read through enough arch wikis, but I have been trying to install blackarch for the last 4 hours and keep getting errors. invalid SHA1 and the install aborts

**Comment by ikstream** [comment]
If it does not work for you, try installing arch Linux and then install black arch on top of it. 

https://blackarch.org/downloads.html#install-repo

**Comment by SampsonCrowley** [comment]
@ikstream the website can't be reached
