### ISSUE TITLE
New mirror in .NL

### ISSUE THREAD

**Issue by rroethof** [BlackArch/blackarch#1848]
I would like to add our new public mirror: 

HTTP: http://mirror.neostrada.nl/blackarch/
HTTPS: https://mirror.neostrada.nl/blackarch/
FTP: ftp://mirror.neostrada.nl/blackarch/
RSYNC: rsync://mirror.neostrada.nl/blackarch/

Sync schedule: Every 4 hrs 
Bandwidth: 100Mbits for public
Location: Netherlands
Sponsor: Neostrada B.V.
Sponsor URL: https://www.neostrada.nl/
IPv4 address to authorize: 195.238.74.240 
IPv6 address to authorize: 2a02:40c0:1000:1000::ffff:ffff
Email contact: mirror@neostrada.nl

**Comment by noptrix** [comment]
thanks a lot @rroethof. we've added the mirror on our website and mirror.lst
