### ISSUE TITLE
Install problems with creating partitions.

### ISSUE THREAD

**Issue by Linux-fan** [BlackArch/blackarch#1849]
I was trying to install Blackarch, but if I created partitions with cfdisk, I get error: could not create filesystem, the file sda1 does not exist and no size was specified. I try to create partitions before I run the installation script, but without results. I have check if the partitions are on the disk, but they just stand on it.

**Comment by ikstream** [comment]
the device name is usually unnumbered. In your case this would be /dev/sda
you can check your block devices with lsblk

**Comment by Linux-fan** [comment]
Thanks for the fast reaction, indeed I had entered the wrong path.
