### ISSUE TITLE
Artillery Performance Testing : sockets.io chat uses certificate based authentication

### ISSUE THREAD

**Issue by naveenrajvnr** [BlackArch/blackarch#1852]
Currently we are developing a ChatBot application which is using **sockets.io** protocol for chat conversations. Also we were using **SSL Certificate  based authentication** for Login to the application (**_Dynamic Value : SID will be generated_** once the Login is successful from the IAM Server)

Requesting kind suggestions & help on certificate based authentication.

> If you have example YAML Code for cert auth , Kindly please share for better understanding.

**Comment by naveenrajvnr** [comment]
#https://www.npmjs.com/package/artillery-plugin-http-ssl-auth

**Comment by naveenrajvnr** [comment]
#59 TLS certificate verification doesn't always work as expected

**Comment by PedroSFreitas** [comment]
wtf, off topic.
