### ISSUE TITLE
how to dual boot blackarch with windows

### ISSUE THREAD

**Issue by faizanlone666** [BlackArch/blackarch#1853]

**Comment by PedroSFreitas** [comment]
**Please, before opening a new Issue search for similar ones:**

1. https://github.com/BlackArch/blackarch/issues/1550
2. https://github.com/BlackArch/blackarch/issues/1245

Our installer doesn't support dual boot, specially with Windows.
You may want to check: 

- https://wiki.archlinux.org/index.php/Dual_boot_with_Windows
- https://wiki.archlinux.org/index.php/GRUB#Dual-booting

Important to say as well is that BlackArch is fully compatible with existing Arch Linux installation.
If you want you can just install Arch Linux and add our repository to it. This way you have way more control to do whatever you want. For this, check:

- https://blackarch.org/downloads.html#install-repo
