### ISSUE TITLE
Can't find blackarch tools!

### ISSUE THREAD

**Issue by KnownAsDon** [BlackArch/blackarch#1857]
I just installed blackarch on top of my current vanilla arch with strap and everything went fine. Now that is finished I cant seem to find the tools anywhere. Even if i type msfconsole from the terminal or open the applications(using kde plasma 5) there is nothing. Any help would be greatly appreciated!

**Comment by PedroSFreitas** [comment]
@KnownAsDon what are the step you did so far?

**Comment by KnownAsDon** [comment]
@PedroSFreitas added the blackarch repo with strap
and installed all the avaible tools with pacman...with this command
sudo pacman -S blackarch

**Comment by PedroSFreitas** [comment]
There is a high change `pacman` aborted with errors.
Try to run this: `pacman -Syyu --needed --force blackarch`

**Comment by KnownAsDon** [comment]
No mean i'm pretty sure it runned with no error cause i followed all the end of the process...the packages finished downloading it checked the keyring and the packages and that was all...but ill still try to run the command and if that doesnt work i will try the github method.

**Comment by KnownAsDon** [comment]
@PedroSFreitas Holly crap thank you so much bro...this time instead of downloading over 5gb worthed of files it downloaded only over 400mb and diffrently from last time it didnt only check the files but actually installed them...I dont know what went wrong last time but this actually did it.Thanks man!
