### ISSUE TITLE
Wifi Issue

### ISSUE THREAD

**Issue by UpashChhetri** [BlackArch/blackarch#1859]
Failed to start wifi issue showing netctl failed to start some service to connect to wifi.What to do How to fix?

**Comment by ikstream** [comment]
Please have a look at https://upthemes.com/blog/2014/02/writing-useful-github-issues/
Afterwards you could add some information about the failed service and some other relevant information about your issue.
Right now it sounds to me like it has nothing to do witch BlackArch, but with Archlinux
