### ISSUE TITLE
Blackarch as my daily OS for normal use too

### ISSUE THREAD

**Issue by UpashChhetri** [BlackArch/blackarch#1860]
I want to use my blackarch linux as normal distro too like its having xfce or kde desktop environment? So how to install desktop environments and video drivers so I can watch videos etc.

**Comment by abericart** [comment]
BlackArch is nearly identical to Arch Linux. Arch has a very good wiki that will show you how to install new software.

https://wiki.archlinux.org/index.php/General_recommendations#Graphical_user_interface

**Comment by UpashChhetri** [comment]
Does blackarch comes with officialo arch repository?

**Comment by abericart** [comment]
Yes

**Comment by Tempestyash123456** [comment]
Can I use BlackArch linux just like ubuntu as a normal OS ?

**Comment by ikstream** [comment]
Yes you can use it as a daily driver, but it usually doesn't make sense to do so.
Blackarch is just an additional repository for Arch Linux. It adds tools, that are useful for security researchers and penetration tester.
There are usually very limited reasons to run these tools bare metal. And never install all tools at once.
