### ISSUE TITLE
Usb

### ISSUE THREAD

**Issue by UpashChhetri** [BlackArch/blackarch#1861]
How can I get icon in blackarch and auto mount usb and copy files from usb to harddrive.after inserting usb to usbport.

**Comment by UpashChhetri** [comment]
Will thunar or like tool work with blackarch?
How will I get automount icon

**Comment by PedroSFreitas** [comment]
We don't recommend BlackArch for those that aren't familiar with Arch Linux, or Linux itself.
Your questions/comments aren't related to BlackArch but rather with Arch Linux in general. I recommend you to read the Arch Wiki at https://wiki.archlinux.org/.
By today BlackArch doesn't come installed with any DE or any File Manager.

Topics related to BlackArch are something around:

- Boot issues in the Live ISO;
- If one of our tools isn't working properly;
- If one of our tools isn't updated;
- Our installer;
- Our Live ISO in general;
- Our webpage;
- Or any of the tools developed by us;

Closing.
