### ISSUE TITLE
BlackArch Live USB Stick 

### ISSUE THREAD

**Issue by halflife9** [BlackArch/blackarch#1874]
I downloaded black arch from the official link, and with two different types of Usb Stick I tried to start it as Black Arch live, without success! Both the Usb Sticks after the initial start remain "frozen" as"you can see from the picture,  on Acer Aspire 5842G.
![img_4690](https://user-images.githubusercontent.com/37046939/36948387-75bef718-1fda-11e8-87b8-9752a2991756.JPG)
What do I do wrong? Can you help me?

**Comment by myrage2000** [comment]
Hey,
How did you write the images to the USB stick ?
You might want to try with "Legacy mode" enabled in your BIOS/UEFI.

**Comment by halflife9** [comment]
I tried using different software like poweriso with the option to make a bootable usb stick, another time with rufus, etcher.But did not help anything.In bios the start is imposed via the usb stick.All other distributions like Parted Magic, Ubuntu , Suse Leap, Xubuntu, Mint, etc etc. using USB Stick or DVD do not make any problems and Start correctly.... :(

**Comment by PedroSFreitas** [comment]
@halflife9 
**First step** is to checksum the ISO image you've downloaded, to be sure it's okay. You can find the sha1sum of the ISO in the Download page.

**Second step** is to make sure you're burning the image correctly to your thumb drive. The best way, by far, is to use `dd`. You can check the command on the Download page as well.

**And finally the third** is to check what @myrage2000 said. It's important to test another booting process (UEFI or Legacy)! It's very common to have problem when dealing with UEFI boot though. You can google it for more info. ;)

Also there is a know issue on https://github.com/BlackArch/blackarch/issues/1837 regarding the boot process. I think I have narrowed it down, but I need more tests; which takes some time. However it does look a bit different from what you have there.

_If you're willing to test it, go ahead and download this ISO: https://github.com/PedroSFreitas/blackarch-slim-iso (there is a link to Mega where you can download it, it's around 2.07GB iirc)._

**Comment by halflife9** [comment]
RIDICOULOS!!
Take a Look..I have to the Start the same like the Acer Aspire 5842G,but to the end come BlackArch Live on a "primitiv" Lenovo X61 from Year 2007...with NO BIOS Option UEFI etc etc
Look at the picture it start correctly..right?
![qq](https://user-images.githubusercontent.com/37046939/37028125-ae397d20-2133-11e8-9509-9e786648ae11.jpg)

**Comment by halflife9** [comment]
But I will look and resolve the Issue with the Acer with Your Help :)
in the Bios Option but..I have not to take change like mirage2000 says:...You might want to try with "Legacy mode" enabled in your BIOS/UEFI...
o now I try with the other comments from PedroSfreitas and all the other..:)
Yooh Brothers

**Comment by PedroSFreitas** [comment]
@halflife9 status?

**Comment by CyberRevenent** [comment]
@PedroSFreitas. I am also experiencing a similar issue as OP. It was burned to the drive through dd and the legacy BIOS selection was enabled. Let me know if there is a fix!

**Comment by PedroSFreitas** [comment]
@CyberRevenent yes, we know. There is a issue related to this in https://github.com/BlackArch/blackarch/issues/1837

I'm closing this one so we can track the issue in a single place (above).
