### ISSUE TITLE
ERROR: Wrong SHA1

### ISSUE THREAD

**Issue by MasudAlia** [BlackArch/blackarch#1875]
[+] Downloading and executing strap.sh

[-] ERROR: Wrong SHA1 sum for strap.sh: (orig: 6f152b79419491db92c1fdde3fad2d445f09aae3). Aborting!
[ blackarch ~ ]

**Comment by PedroSFreitas** [comment]
@MasudAlia please run:
`pacman -Syy blackarch-installer`

The version should be `0.6.2-1`.

**Comment by MasudAlia** [comment]
it's blackarchlinux-live-2017.06.13-x86_64

**Comment by PedroSFreitas** [comment]
Did you run the command I sent?

**Comment by MasudAlia** [comment]
...should I initiate from the beginning or just write the commend in error section?

**Comment by MasudAlia** [comment]
it's completed. what next?

**Comment by PedroSFreitas** [comment]
It's clear that the problem isn't on BlackArch, so it's safe to close and lock this conversation to avoid unnecessary noise.

_I recommend you get familiar with Arch Linux first._
