### ISSUE TITLE
blackarch issue

### ISSUE THREAD

**Issue by MasudAlia** [BlackArch/blackarch#1876]
I've installed black arch using the commend "pacman -Syy blackarch-installer" but after reboot it's not working.

**Comment by PedroSFreitas** [comment]
I strongly suggest you to avoid opening Github Issues for your personal Issues. This feature is meant for **Issues related to the project itself** . On top of that, it's clear that BlackArch isn't the right distro for you: **https://blackarch.org/faq.html**. Maybe I'd suggest Kali Linux.

If a simple look at the page you would find our guides. And here is the Guide for installation: https://blackarch.org/blackarch-install.html

Any other Issue related to it will be reported as spam.
Thanks in advance.
