### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by Anonyvius** [BlackArch/blackarch#1877]
I know this was already an closed issue. But i installed like 1 hour ago Blackarch v0.6.2, booted it up and now have an login loop. Everytime if i try to login it just jumps back to the login formula. I triet the deafault login ( root , blackarch ) and choose an different Desktop, But its still not working.

Sry for my bad english, i hope you know what i mean.

**Comment by PedroSFreitas** [comment]
A good idea would be to boot again using the ISO, chroot to the installed BA and change the credentials for root and for other possible users. Exit chroot, unmount everything and reboot.

**Comment by Anonyvius** [comment]
reinstalled it a third time, now its working fine.
