### ISSUE TITLE
fbht - github repo doesn't exist anymore

### ISSUE THREAD

**Issue by milovanderlinden** [BlackArch/blackarch#1879]
The repository https://github.com/chinoogawa/fbht-linux to which fbht points no longer exists.

**Comment by milovanderlinden** [comment]
Repository seems to have relocated to https://github.com/chinoogawa/fbht

**Comment by PedroSFreitas** [comment]
Thanks, @milovanderlinden.
The PR created by @ikstream is tracking this: https://github.com/BlackArch/blackarch/pull/1883

I'll proceed with manual test later and flag it to be merged.
