### ISSUE TITLE
Improved new slowloris DOS testing tool

### ISSUE THREAD

**Issue by houssniyh** [BlackArch/blackarch#1882]
I have created a slowloris DOS tool which is an improved version. The features are: using tor when that flag is passed (without needing to install proxychains or torify/torsocks), and the attack continues until the server is starting to get exhausted if vulnerable for this kind of attack. It is written in Python 3 and I would love to see this tool being added into BlackArch Linux, the tool is submitted to Kali Linux as well.

https://github.com/houssniyh/pwnloris

**Comment by NovaCygni** [comment]
Added at last push..

**Comment by PedroSFreitas** [comment]
@NovaCygni thanks.
