### ISSUE TITLE
Tool Request: IDA Free

### ISSUE THREAD

**Issue by gh00sty** [BlackArch/blackarch#1888]
it will be nice if you guys add the Free version of IDA to blackarch repo

**Comment by PedroSFreitas** [comment]
IDA Free only supports 64bits and lacks pretty much everything you probably need for a serious work.
Have you checked `radare2` + `cutter` ? It's open source!

**Comment by gh00sty** [comment]
@PedroSFreitas  for the moment i use gdb with peda and im open for radare2 i think i will give it a try

**Comment by PedroSFreitas** [comment]
Closing this due lack of interest.

**Comment by osospeed** [comment]
https://aur.archlinux.org/packages/ida-free
