### ISSUE TITLE
Can't run msfconsole because of ruby dependencies 

### ISSUE THREAD

**Issue by FabioNevesRezende** [BlackArch/blackarch#1902]
Hello. First of all I'm running Blackarch on top of a Archlinux distro. When I run **msfconsole** it fails with the error message:

> Traceback (most recent call last):
>         1: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
> <internal:gem_prelude>:2:in `require': cannot load such file -- rubygems.rb (LoadError)

My ruby --version is **ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]**

**Comment by PedroSFreitas** [comment]
**Metasploit** is supplied by Arch Linux: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/metasploit

However I just did a test on mine and it's working fine.
Maybe you got some errors while installing BlackArch on top of Arch. I'd suggest to run:
```
# pacman -Syyu blackarch --needed --force
```

Also don't forget that Arch Linux doesn't supply postgres database for msfconsole.
For more info: https://wiki.archlinux.org/index.php/Metasploit_Framework#Setting_up_the_database

My machine running msfconsole:
![image](https://user-images.githubusercontent.com/12863160/38469398-5e8bd870-3b2a-11e8-9eb4-bb6f23c34ec5.png)

**Comment by noptrix** [comment]
@FabioNevesRezende please install rubygems.

**Comment by FabioNevesRezende** [comment]
Thank guys, just installing rubygems was enough
