### ISSUE TITLE
Malware Analysis Toolkit

### ISSUE THREAD

**Issue by theragnarpatel** [BlackArch/blackarch#1907]
#1907

Can you add some Python tools and Library for Documents Malware Analysis.
Tool might be help as static, dynamic and behavior analysis. 
If you want then, I can list out best malware analysis tools for documents analysis and so on.

**Comment by PedroSFreitas** [comment]
I don't quite follow this Issue.
Are you asking to add documentation?

The only tool I can see we could try to add is: https://github.com/ANSSI-FR/polichombr.

**Comment by PedroSFreitas** [comment]
As said in my previous comment, all the links provided by OP are docs related.
I'm closing this because from those only a single one is an application that could be added to our repository.

If anyone think it's a mistake (closing it now), please provide further information that we can reopen it.
