### ISSUE TITLE
Install all tools

### ISSUE THREAD

**Issue by symbios24** [BlackArch/blackarch#1910]
Hello, i`m trying to install all 1863 tools on a raspberry pi i get the option default=all but if i type all i get an invalid command message,if i type for example 500 i get only the tool 500 in the row.how can i install all tools?

Thanks

**Comment by symbios24** [comment]
Is there a pre-made image somewhere for the raspberry-pi 2/3 ?

**Comment by symbios24** [comment]
any plans for release an image for the raspberry pi with black arch pre-installed?

**Comment by PedroSFreitas** [comment]
@symbios24 yes, we have that in mind. However it may take more time than we expected.

**Comment by PedroSFreitas** [comment]
Closing due inactivity from OP.
If you think it's a mistake, please re-open the issue supplying recent/more information.

Thanks.
