### ISSUE TITLE
[Bug] Problem with blackarch-keyring package

### ISSUE THREAD

**Issue by deltaxflux** [BlackArch/blackarch#1911]
I think that the gpg key is outdated. I think @noptrix speak German? So I don't have to translate.

**procedure**
```
cd [PATH]
makepkg
```

**Trace:**
```
==> Überprüfe Signaturen der Quell-Dateien mit gpg...
    blackarch-keyring-20140118.tar.gz ... FEHLGESCHLAGEN (Unbekannter öffentlicher Schlüssel 66E0CDBD1E01F333)
==> FEHLER: Eine oder mehrere PGP-Signaturen konnten nicht überprüft werden!
```

Could be related to this [issue](https://github.com/BlackArch/blackman/issues/6)

**Comment by deltaxflux** [comment]
DE
==> Überprüfe Signaturen der Quell-Dateien mit gpg...
    blackarch-keyring-20140118.tar.gz ... FEHLGESCHLAGEN (Unbekannter öffentlicher Schlüssel 66E0CDBD1E01F333)
==> FEHLER: Eine oder mehrere PGP-Signaturen konnten nicht überprüft werden!

EN:
==> Check signature of file with gpg
    blackarch-keyring-20140118.tar.gz ... Failed (Unknown public key 66E0CDBD1E01F333)
==> Error: One or more gpg signatures can get verified

Hope it makes something clear

**Comment by myrage2000** [comment]
If you trust this public key (66E0CDBD1E01F333), then please issue in a terminal:
`gpg --recv 66E0CDBD1E01F333 ` and then retry.

**Comment by deltaxflux** [comment]
I don't use blackarch. I was trying to check if this repo has outdated packages because I guessed that it is related to the another issue. Key is fine.

**Comment by ikstream** [comment]
I am going to close this issue as the initial problem should be solved, if you think this is a mistake, please provide further information.

**Comment by noptrix** [comment]
thank you @ikstream

**Comment by deltaxflux** [comment]
Agree.
