### ISSUE TITLE
blackarch 

### ISSUE THREAD

**Issue by skyghost66** [BlackArch/blackarch#1921]
HELLO I JUST INSTALL BLACKARCH IN MY LAPTOP AND AFTER REBOOT I TRY sudo pacman -Syyu AND I GET ALL THIS!!! : [ blackarch ~ ]# pacman -Syyu
:: Synchronizing package databases...
 core                     129.9 KiB   172K/s 00:01 [######################] 100%
 extra                   1603.6 KiB   754K/s 00:02 [######################] 100%
 community                  4.3 MiB   931K/s 00:05 [######################] 100%
 blackarch                  2.1 MiB   603K/s 00:03 [######################] 100%
 blackarch.sig            566.0   B  0.00B/s 00:00 [######################] 100%
:: Starting full system upgrade...
warning: bettercap: local (1015.3946fdd-1) is newer than community (2.5-1)
:: Replace compositeproto with extra/xorgproto? [Y/n] n
:: Replace damageproto with extra/xorgproto? [Y/n] n
n
n:: Replace fixesproto with extra/xorgproto? [Y/n] 
:: Replace fontsproto with extra/xorgproto? [Y/n] n
n
n:: Replace inputproto with extra/xorgproto? [Y/n] 
:: Replace kbproto with extra/xorgproto? [Y/n] n
warning: kitty: local (321.f19e811-2) is newer than community (0.9.1-1)
n

warning: perl-number-bytes-human: local (0.11-2) is newer than community (0.11-1)

:: Replace randrproto with extra/xorgproto? [Y/n] 
:: Replace recordproto with extra/xorgproto? [Y/n] 
:: Replace renderproto with extra/xorgproto? [Y/n] 

:: Replace scrnsaverproto with extra/xorgproto? [Y/n] 

:: Replace videoproto with extra/xorgproto? [Y/n] 

:: Replace wxpython with community/python2-wxpython3? [Y/n] 
:: Replace xextproto with extra/xorgproto? [Y/n] 
:: Replace xf86vidmodeproto with extra/xorgproto? [Y/n] 
:: Replace xineramaproto with extra/xorgproto? [Y/n] 
:: Replace xproto with extra/xorgproto? [Y/n] 
resolving dependencies...

looking for conflicting packages...
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: scapy3k and scapy are in conflict  

I DONT KNOW WHAT CAN I DO?CAN YOU HELP ME PLEASE ,THANK YOU!!!

**Comment by PedroSFreitas** [comment]
The replaces are due Arch Linux (upstream) changes.
There is no way you can avoid them, so **it should be okay to replace everything**.

We're working to release a new ISO around June, which will avoid it.

**Comment by zoodayz** [comment]
For me the best way to avoid it was install from the net and not the iso hope this helps I think it was option 1 in the installer

**Comment by PedroSFreitas** [comment]
@zoodayz you can also install Vanilla Arch and add BA repository to it.

**Comment by skyghost66** [comment]
thank you guys for your advice ,zoodayz i try to install from option 1 but
not successful ,any way i ill find the path ....thank you!!1
