### ISSUE TITLE
 RDP libraries not found.

### ISSUE THREAD

**Issue by akg87** [BlackArch/blackarch#1932]
Trying to run Eyewitness on Windows. 
- Installed all the required libs but giving error about RDP libraries

I have installed rdp and rdpy both but still the issue persist. Please suggest how could I resolve the same?

**Comment by ikstream** [comment]
Have you installed six and automat as recommended in [this](https://github.com/ChrisTruncer/EyeWitness/issues/239) issue?

**Comment by akg87** [comment]
Yes. It is already installed.

**Comment by akg87** [comment]
Did everything suggested in that ticket but issue still there.

**Comment by akg87** [comment]
Yes.

**Comment by PedroSFreitas** [comment]
This is Blackarch.
Closing and locking.
