### ISSUE TITLE
Responder/Multirelay

### ISSUE THREAD

**Issue by er4z0r** [BlackArch/blackarch#1939]
Allthough Blackarch does have a Responder package, I recently discovered that it is based on the old Repository by SpiderLabs, which seems to no longer be maintained (last commit 2016). 
The fork by Laurent Gaffe is much newer and contains additional tools such as MultiRelay. It is also the repo referenced by the @pythonresponder twitter account.

I suggest to either base the existing package on [lgandx fork](https://github.com/lgandx/Responder) or to create a new package responder-multirelay.

**Comment by PedroSFreitas** [comment]
@noptrix what do you think?

**Comment by noptrix** [comment]
thanks @er4z0r. will be changed :)

**Comment by noptrix** [comment]
added: responder-multirelay. thanks @er4z0r
