### ISSUE TITLE
Install BlackArch

### ISSUE THREAD

**Issue by PetruNN** [BlackArch/blackarch#1940]
Hello, after the last update, install the EFI way, no longer works.
--

**Comment by PedroSFreitas** [comment]
@PetruNN we'll take a look.

**Comment by myrage2000** [comment]
Hey,
I installed the very latest .iso to my UEFI-only laptop this week and everything worked.
Could you please describe your issue with efi ?

**Comment by PetruNN** [comment]
Thank you I have solved.

the hard drive should be formatted in gpt.
