### ISSUE TITLE
Can't Add Black Arch Repository on Manjaro xfce

### ISSUE THREAD

**Issue by swarupsro** [BlackArch/blackarch#1945]
`➜  ~ curl -O https://blackarch.org/strap.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4065  100  4065    0     0   3379      0  0:00:01  0:00:01 --:--:--  3379

➜  ~ sha1sum strap.sh                     
73aae423a31410e021ef1b8f1becd573d2bd17dc  strap.sh

➜  ~ chmod +x strap.sh                     

➜  ~ sudo ./strap.sh                       
[+] installing blackarch keyring...
[-] ERROR: You don't have an Internet connection!
`

**Comment by swarupsro** [comment]
just comment out the 'check_internet' line 
line '173'
problem solved

**Comment by Jesus-grao** [comment]
Idk how can i comment
