### ISSUE TITLE
update strap.sh

### ISSUE THREAD

**Issue by swarupsro** [BlackArch/blackarch#1953]
noptrix keyring is error !

**Comment by ikstream** [comment]
Please have a look at [how to write an issue](https://upthemes.com/blog/2014/02/writing-useful-github-issues/) that helps us to help you.

As i have to assume, what your exact problem is, i recommend having a look for the keyring section of the [FAQ](https://blackarch.org/faq.html)

**Comment by swarupsro** [comment]
`error: blackarch: key "F9A6E68A711354D84A9B91637533BAFE69A25079" is unknown
:: Import PGP key 4096R/F9A6E68A711354D84A9B91637533BAFE69A25079, "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>",`

**Comment by swarupsro** [comment]
`error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is unknown trust
error: failed to update blackarch (invalid or corrupted database (PGP signature))`

**Comment by ikstream** [comment]
Based on your answer i assume you have not checked the first link i provided, did you check the FAQ?

What have you tried so far? Have you checked your Problem on a search engine of your choice?

**Comment by killerkalai** [comment]
:: nodejs-lts-gallium and nodejs are in conflict. Remove nodejs? [y/N] N
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: nodejs-lts-gallium and nodejs are in conflict

any one say why this error is occur any one solution for this

**Comment by noraj** [comment]
please @killerkalai this has nothing to do with this issue and has already been answered here #3499
