### ISSUE TITLE
UEFI installation

### ISSUE THREAD

**Issue by UndeadHeavy** [BlackArch/blackarch#1959]
I need help with blackarch uefi gpt installation, can someone tell step by step? I've read arch linux wiki but its quite different on Blackarch linux where we have to choose one option.
Also on the official website installation is only for bios/mbr pc.

**Comment by ikstream** [comment]
You could install Arch Linux with UEFI following the arch wiki and put Blackarch on top of it as described on the Blackarch site.

**Comment by ikstream** [comment]
I am closing this issue as you opened a second one with a very similar topic

**Comment by PedroSFreitas** [comment]
For documentation purposes I'll leave here that the BlackArch installation script **does not support UEFI installation/configuration by default**. If you want to install it on a UEFI system, you should have do it manually; BlackArch is an extension of Arch Linux.

**Useful links:**
https://wiki.archlinux.org/index.php/installation_guide#Verify_the_boot_mode
https://wiki.archlinux.org/index.php/Unified_Extensible_Firmware_Interface
https://wiki.archlinux.org/index.php/EFI_system_partition
https://wiki.archlinux.org/index.php/Dual_boot_with_Windows
