### ISSUE TITLE
Dual Booting With Windows 10

### ISSUE THREAD

**Issue by Arszilla** [BlackArch/blackarch#1960]
I am learning about Cybersec and Pentesting. My books suggested Kali or BlackArch. After some issues with Kali regarding Hashcat and other tools (Problems were caused by Kali’s nature, thats why) I decided to try BlackArch

I installed via NetInstall earlier today. Now some issues that occurred were:

- I could not create a user; I’d enter my username for a non-root account but as soon as I hit enter it would take my username as a password and say some shit/bug out and I’d have to terminate the installation.

- I could not dual boot. I have a 250 GB SSD, 2 TB HDD and a 500 GB HDD. The 500 GB HDD is a 2.5” HDD from my old laptop. I tried to install BlackArch there; just like I did with Kali (To dual boot). I assigned a Boot, SWAP and root to SDD (That was what my drive was in the installation screen), made the Boot and root EXT4 as the BlackArch guide said. But after installation I could not access GRUB directly; I did not see BlackArch in my BIOS [There is a bootloader setting in my B350 Tomahawk] and I had to manually boot into my HDD to get to BlackArch

- During the installation of some of the tools they 404’d. I believe its because the internet access in Turkey is blocked; like I can’t access Imgur, Pastebin etc without a VPN and some tools like TOR cannot be downloaded (from their website) without a VPN/Proxy. Could this be the case?

My main issue is how can I dual boot BlackArch? Can you fine people help me? I mentioned the errors above in case they’d be useful.

I prefer not to install Arch then build BlackArch ontop of it because I don't know which DE to choose, and not sure how would that effect BlackArch.

**Comment by ikstream** [comment]
For the first part we will have to look into it, did not occur to me before. Just saw it today on IRC for the first time. You could skip user creation and create one after booting (I assume you did this?)

Have you set the boot flag for your boot partition?
Is your /boot on the first drive to be booted? (Could be some problem with two bootloader?)
Grub never worked out for me very well, always had issues with it. 

The 404 could come from old sources. You could run a sudo pacman -Sy prior your install. 
Is it only one mirror? If it still happens you could remove that mirror from your mirrorlist.

Installing blackarch on top of arch is desktop environment independent. You can also use manjaro if it is more convenient to you.

Hope I could help you.

**Comment by ikstream** [comment]
There is a section about installing BA on top of Arch. You install Arch and just add the BA repositories to the existing Arch install. So you would not ran the same installer as you did so far. The installer is not suited for dual boot by its self, as far as i know, so you would need to fit it afterwards to your needs. But i could be wrong on this part. There are syslinux, uboot, or systemd-boot as possible boot loaders

Some tools will work without a window manager or desktop environment but some need it to work properly.

Manjaro is basically a well hung arch variant. They use their own repositories and wait a little bit longer to update packages, so they are not so bleeding edge as Arch, but still way more up to date than Ubuntu. 
You can use the BA repo with it as well. They provide a conveniant way of installation.

Then there is Antergos if manjaro is not bleeding edge enough for you
As far as I know Antergos is a bleeding Edge Arch with an easy install, you could try that as well.

I am by no way a dual boot expert, but there are some guides out there for dual booting with manjaro/Arch.

**Comment by crexzo** [comment]
سلام کسی میدونه بلک آرچ چطوری کنار ویندوز ۱۰ نصب کنم؟
