### ISSUE TITLE
Blackarch on top of Arch linux

### ISSUE THREAD

**Issue by UndeadHeavy** [BlackArch/blackarch#1964]
What is blackarch window manage/login window and default Desktop environment? Is possible we make arch linux looks like Blackarch like when we right click and it does show all the tools.

**Comment by UndeadHeavy** [comment]
Hmm

**Comment by myrage2000** [comment]
You can install :
spectrwm
blackarch-config-spectrwm

And then : `cp /usr/share/blackarch/config/spectrwm/spectrwm.conf ~/.spectrwm.conf`

**Comment by UndeadHeavy** [comment]
Is spectrwm is DE or Window manager ? What is blackarch default DE?

**Comment by myrage2000** [comment]
Spectrwm seems to be the default WM.
There is not default DE for BlackArch (I mean, no terminals no fun). Anyway, you can install a DE yourself. I recommand xfce because you can then import the "right click menu list" with a plugin.

**Comment by ikstream** [comment]
I am closing this issue, as the question seems to be answered.
