### ISSUE TITLE
[Tool request] GhostPack (Work In Progress)

### ISSUE THREAD

**Issue by osospeed** [BlackArch/blackarch#1971]
https://github.com/GhostPack

Done:
- [x] [ghostpack-safetykatz](https://github.com/GhostPack/SafetyKatz), [PKGBUILD](https://github.com/osospeed/aur/blob/master/ghostpack-safetykatz/PKGBUILD)
- [x] [ghostpack-sharpdump](https://github.com/GhostPack/SharpDump), [PKGBUILD](https://github.com/osospeed/aur/blob/master/ghostpack-sharpdump/PKGBUILD)
- [x] [ghostpack-sharpwmi](https://github.com/GhostPack/SharpWMI), [PKGBUILD](https://github.com/osospeed/aur/blob/master/ghostpack-sharpwmi/PKGBUILD)

TODO:
- [ ] [ghostpack-rubeus](https://github.com/GhostPack/Rubeus)
- [ ] [ghostpack-seatbelt](https://github.com/GhostPack/Seatbelt), [PKGBUILD](https://github.com/osospeed/aur/blob/master/ghostpack-seatbelt/PKGBUILD)
`Build FAILED. Program.cs(5,26): error CS0234: The type or namespace name 'Eventing' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?) [/tmp/ghostpack-seatbelt/src/Seatbelt/Seatbelt/Seatbelt.csproj]`
- [ ] [ghostpack-sharpdpapi](https://github.com/GhostPack/SharpDPAPI)
- [ ] [ghostpack-sharproast](https://github.com/GhostPack/SharpRoast), [PKGBUILD](https://github.com/osospeed/aur/blob/master/ghostpack-sharproast/PKGBUILD)
`Build FAILED. Program.cs(5,32): error CS0234: The type or namespace name 'AccountManagement' does not exist in the namespace 'System.DirectoryServices' (are you missing an assembly reference?) [/tmp/ghostpack-sharproast/src/SharpRoast/SharpRoast/SharpRoast.csproj]`
- [ ] [ghostpack-sharpup](https://github.com/GhostPack/SharpUp), [PKGBUILD](https://github.com/osospeed/aur/blob/master/ghostpack-sharpup/PKGBUILD)
`Build FAILED. Program.cs(6,26): error CS0234: The type or namespace name 'Eventing' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?) [/tmp/ghostpack-sharpup/src/SharpUp/SharpUp/SharpUp.csproj]`

**Comment by osospeed** [comment]
- The initial idea was that we compile it on Linux, but as seen above this not so optimal.
- Second idea is to build it on windows using a CI server (e.g. Appveyor), and then take the binary Artifacts. In our case here, unfortunately my PR got rejected (https://github.com/GhostPack/SafetyKatz/pull/3).
So in such cases what about making a Blackarch account on Appveyor which builds windows tools and push it to our repo here ?
Any better idea ?

**Comment by vichhika** [comment]
Currently, I just saw this repository working on ghostpack binaries compiled.
https://github.com/r3motecontrol/Ghostpack-CompiledBinaries

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4223

**Comment by D3vil0p3r** [comment]
This issue can be closed
