### ISSUE TITLE
Conflicts are not written in the packages.

### ISSUE THREAD

**Issue by nils-van-zuijlen** [BlackArch/blackarch#1977]
I tried to install the groups `blackarch-scanner`, `blackarch-cracker`, `blackarch-recon` and `blackarch-forensic` in one go with pacman. I already had the `blackarch-wireless` group installed.
It didn't work because there were conflicts between the packages.

- `python2-normality` and `inquisitor` are using `/usr/lib/python2.7/site-packages/tests/__init__.py` and the `.pyc` and `.pyo` of that same file.
- `aquatone` and `dawnscanner` have so many conflicting files that I will not list them.
-  `aquatone` and `ridenum` share the file `/usr/share/licenses/LICENSE.txt`, which is a shame, they shall name that file according to the licence they use.
- `python2-cement` and `python2-roguehostapd` are using `/usr/lib/python2.7/site-packages/examples/__init__.py` and the `.pyc` and `.pyo` of that same file.
- `vhostscan` and `openlp` are using `/usr/lib/python3.6/site-packages/tests/helpers/__init__.py`
- `ruby-colorize` and `yawast` have files in common too in folders `/usr/lib/ruby/gems/2.5.0/gems/colorize-0.8.1` and `/usr/lib/ruby/gems/2.5.0/specifications`
- `python2-py-bcrypt` and `python2-bcrypt` are using the same directory: `/usr/lib/python2.7/site-packages/bcrypt/`.

**Comment by nils-van-zuijlen** [comment]
Suggestions of fixes:
- All packages that provide python libs available on pypi should use the same file tree as there.
  - [ ] `python2-normality`
  - [ ] `inquisitor`
  - [ ] `python2-cement`
  - [ ] `python2-roguehostapd`
  - [ ] `vhostscan`
  - [ ] `python2-py-bcrypt`
- `yawast` should not pack `ruby-colorize` with it. It should have it as a dependency or explicitly provide it.
- `aquatone` and `dawnscanner` should not pack `ffi` with them. Instead, they can depend of `ruby-ffi` from the `community` repository.

**Comment by FFY00** [comment]
The test/example directories shouldn't be renamed but rather removed. If possible upstream should be contacted to change the path too, so that it doesn't conflict if they are included by mistake.
