### ISSUE TITLE
Installing BlackArch on top of vanilla Arch

### ISSUE THREAD

**Issue by GlitchUcak** [BlackArch/blackarch#1978]
I have just tried to install blackarch on vanilla arch linux, after this command `sudo pacman -S blackarch` it gave me this one thousand-lined long [error](https://hastebin.com/ilevepehay.sql) 

I saw that a issue similar to mines was closed but it says you should `--force` or ` --ignore` but i can not ignore all of them there is too many and forcing seems little risky.

**Comment by noptrix** [comment]
@GlitchUcak run: sudo pacman -Syyu --needed blackarch --overwrite '*'
