### ISSUE TITLE
Nipe - ERROR

### ISSUE THREAD

**Issue by GouveaHeitor** [BlackArch/blackarch#1990]
When I run the "nipe" command I get the following error:

[~]> nipe
Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: ./lib/ /usr/lib/perl5/5.28/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.28/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.28/core_perl /usr/share/perl5/core_perl) at lib/Nipe/CheckIp.pm line 5.
BEGIN failed--compilation aborted at lib/Nipe/CheckIp.pm line 5.
Compilation failed in require at nipe.pl line 19.
BEGIN failed--compilation aborted at nipe.pl line 19.

Nipe requires the following modules to be installed: Switch JSON LWP :: UserAgent

**Comment by noptrix** [comment]
thanks for reporting. should be fixed now. if not re-open please
