### ISSUE TITLE
No mirror is working

### ISSUE THREAD

**Issue by sayantanHack** [BlackArch/blackarch#1995]
Hi, here while installing Blackarch there have an issue no mirror is taken properly . Even the default mirror is also not doing the job. I have tried 2 3 mirrors none them are working .This is showing after I putting any mirror . 
![barch](https://user-images.githubusercontent.com/26269305/44248563-e928bf80-a208-11e8-947a-7eca0e7b8ab1.png)

**Comment by ikstream** [comment]
please update you installer and run it again. current version should be 0.8

**Comment by sayantanHack** [comment]
How to update the installer from same Iso (old iso ) ?

**Comment by ikstream** [comment]
Run pacman -Sy blackarch-installer

**Comment by sayantanHack** [comment]
Any DE I choose why blackarchiyan call users  N00B !! N00B !! N00B !! ?

**Comment by ikstream** [comment]
I think this is just intended as a joke
