### ISSUE TITLE
llk error

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#1999]
sh: /usr/etc/logkeys-start.sh: No such file or directory

**Comment by GasparVardanyan** [comment]
[gaspar@GasparVardanyan ~]$ llk
sh: /usr/etc/logkeys-start.sh: No such file or directory
[gaspar@GasparVardanyan ~]$

**Comment by noptrix** [comment]
apres, es kfixem :)

**Comment by GasparVardanyan** [comment]
Xndrem. Karox e cragirs avelacvel BlackArch-in? https://github.com/GasparVardanyan/GCrypt
