### ISSUE TITLE
[Tool Update] EvilGinx 2

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2002]
Hi,

EvilGinx has been updated to version 2, supporting 2FA for example. THe PKGBUILD is still for 1.1 here.
Do you think it's possible to update it?
Thanks!

https://breakdev.org/evilginx-2-next-generation-of-phishing-2fa-tokens/

Cheers!

**Comment by noptrix** [comment]
hi @s7x - we've added evilginx2 as a new tool rather than updating the old one. just install evilginx2 directly.

**Comment by s7x** [comment]
Hi @noptrix, thanks a lot!
You guys rocks!
