### ISSUE TITLE
[Tool Installation Fail] Beef Xss

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2003]
Hi,

When attempting to install beef xss, I encounter the following error:

> 
> Installing nokogiri 1.8.4 with native extensions
> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
> current directory: /usr/share/beef/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.8.4/ext/nokogiri
> /usr/bin/ruby -r ./siteconf20180822-22397-17e9q2k.rb extconf.rb --use-system-libraries
> checking if the C compiler accepts ... yes
> Building nokogiri using system libraries.
> pkg-config could not be used to find libxml-2.0
> Please install either `pkg-config` or the pkg-config gem per
> gem install pkg-config -v "~> 1.1"
> pkg-config could not be used to find libxslt
> Please install either `pkg-config` or the pkg-config gem per
> gem install pkg-config -v "~> 1.1"
> pkg-config could not be used to find libexslt
> Please install either `pkg-config` or the pkg-config gem per
> gem install pkg-config -v "~> 1.1"
> ERROR: cannot discover where libxml2 is located on your system. please make sure `pkg-config` is installed.
> *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
> Provided configuration options:
> --with-opt-dir
> --without-opt-dir
> --with-opt-include
> --without-opt-include=${opt-dir}/include
> --with-opt-lib
> --without-opt-lib=${opt-dir}/lib
> --with-make-prog
> --without-make-prog
> --srcdir=.
> --curdir
> --ruby=/usr/bin/$(RUBY_BASE_NAME)
> --help
> --clean
> --use-system-libraries
> --with-zlib-dir
> --without-zlib-dir
> --with-zlib-include
> --without-zlib-include=${zlib-dir}/include
> --with-zlib-lib
> --without-zlib-lib=${zlib-dir}/lib
> --with-xml2-dir
> --without-xml2-dir
> --with-xml2-include
> --without-xml2-include=${xml2-dir}/include
> --with-xml2-lib
> --without-xml2-lib=${xml2-dir}/lib
> --with-libxml-2.0-config
> --without-libxml-2.0-config
> --with-pkg-config
> --without-pkg-config
> --with-xslt-dir
> --without-xslt-dir
> --with-xslt-include
> --without-xslt-include=${xslt-dir}/include
> --with-xslt-lib
> --without-xslt-lib=${xslt-dir}/lib
> --with-libxslt-config
> --without-libxslt-config
> --with-exslt-dir
> --without-exslt-dir
> --with-exslt-include
> --without-exslt-include=${exslt-dir}/include
> --with-exslt-lib
> --without-exslt-lib=${exslt-dir}/lib
> --with-libexslt-config
> --without-libexslt-config
> To see why this extension failed to compile, please check the mkmf.log which can be found here:
> /usr/share/beef/vendor/bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0/nokogiri-1.8.4/mkmf.log
> extconf failed, exit code 1
> Gem files will remain installed in /usr/share/beef/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.8.4 for inspection.
> Results logged to /usr/share/beef/vendor/bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0/nokogiri-1.8.4/gem_make.out
> An error occurred while installing nokogiri (1.8.4), and Bundler cannot continue.
> Make sure that `gem install nokogiri -v '1.8.4' --source 'https://rubygems.org/'` succeeds before bundling.
> In Gemfile:
> msfrpc-client was resolved to 1.1.1, which depends on
> rex was resolved to 2.0.12, which depends on
> nokogiri
> error: command failed to execute correctly

OS: Arch Linux 4.18.2.a-1-hardened
Install with: blackman -i beef -f

Cheers

**Comment by ikstream** [comment]
Does installing `ruby-pkg-config` fix this problem?

**Comment by s7x** [comment]
> Does installing ruby-pkg-config fix this problem?

Sadly not.

**Comment by noptrix** [comment]
@s7x I personally do not recommend using blackman since it's a beta prog and hasn't been tested often. Maybe one day when we enhance it, we would recommend it. I am closing this here.

**Comment by s7x** [comment]
@noptrix Ah? Damn, I'm using it all the time cause it's really helpful for people who don't want to install the full repo over an Arch installation. Thanks for the support still ;)
