### ISSUE TITLE
[Conflict Error] Multiple conflict error during upgrade

### ISSUE THREAD

**Issue by n0tty** [BlackArch/blackarch#2007]
Have been trying to upgrade packages but seem to keep facing the error of failure due to conflict.

> [ pwncode ~ ]$ sudo pacman -Syu
>  :: Synchronizing package databases...
>  core is up to date
>  extra   1644.5 KiB   277K/s 00:06 [############################################################] 100
>   community    4.5 MiB  1039K/s 00:04 [############################################################] 100
>   multilib is up to date
>   blackarch      2.1 MiB   394K/s 00:06 [############################################################] 100
>   blackarch.sig 566.0   B  0.00B/s 00:00 [############################################################] 100
>  :: Starting full system upgrade...
>  :: Replace ca-certificates-cacert with core/ca-certificates? [Y/n] 
>  warning: hcxtools: local (875.7a6b716-1) is newer than community 
>  (4.2.1+15+gbc206cc-1)
>  :: Replace libx264 with extra/x264? [Y/n] 
>  warning: mbelib: local (41.27b3f1b-1) is newer than community (1.3.0-1)
>  warning: multimon-ng: local (20180527-1) is newer than community (1.1.5-2)
>  :: Replace packer-io with community/packer? [Y/n] 
>  warning: perl-data-validate-ip: local (0.27-4) is newer than community 
>  (0.27-2)
>  warning: perl-parallel-forkmanager: local (1.19-4) is newer than community 
>  (1.19-3)
>  :: Replace pkg-config with core/pkgconf? [Y/n] 
>  resolving dependencies...
>  looking for conflicting packages...
>  warning: dependency cycle detected:
>  warning: libglvnd will be installed before its mesa dependency
>  warning: dependency cycle detected:
>  warning: x264 will be installed before its ffmpeg dependency
>  warning: dependency cycle detected:
>  warning: python2-incremental will be installed before its python2-twisted 
>  dependency
>  warning: dependency cycle detected:
>  warning: lib32-mesa will be installed before its lib32-libglvnd dependency
>  warning: dependency cycle detected:
>  warning: python-incremental will be installed before its python-twisted 
>  dependency
>  
>  
>  (1982/1982) checking keys in keyring                                                                  
>  [############################################################] 100%
>  (1982/1982) checking package integrity                                                                
>  [############################################################] 100%
>  (1982/1982) loading package files                                                                     
>  [############################################################] 100%
>  (1982/1982) checking for file conflicts                                                               
>  [############################################################] 100%
>  error: failed to commit transaction (conflicting files)
>  /usr/lib/python2.7/site-packages/bson/objectid.py exists in both 
>  'python2-pymongo' and 'python2-bson'
>  /usr/lib/python2.7/site-packages/bson/objectid.pyc exists in both 
>  'python2-pymongo' and 'python2-bson'
>  /usr/lib/python2.7/site-packages/bson/objectid.pyo exists in both 
>  'python2-pymongo' and 'python2-bson'
>  /usr/lib/python2.7/site-packages/bson/py3compat.py exists in both 
>  'python2-pymongo' and 'python2-bson'
>  /usr/lib/python2.7/site-packages/bson/py3compat.pyc exists in both 
>  'python2-pymongo' and 'python2-bson'
>  /usr/lib/python2.7/site-packages/bson/py3compat.pyo exists in both 
>  'python2-pymongo' and 'python2-bson'
>  /usr/lib/python2.7/site-packages/bson/tz_util.py exists in both 
>  'python2-pymongo' and 'python2-bson'
>  /usr/lib/python2.7/site-packages/bson/tz_util.pyc exists in both 
>  'python2-pymongo' and 'python2-bson'
>  /usr/lib/python2.7/site-packages/bson/tz_util.pyo exists in both 
>  'python2-pymongo' and 'python2-bson'
>  /usr/lib/python3.7/site-packages/yaml/__init__.py exists in both 
>  'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/__init__.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/__init__.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/composer.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/composer.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/constructor.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/constructor.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/cyaml.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/cyaml.cpython-37.pyc
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/dumper.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/dumper.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/emitter.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/emitter.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/error.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/error.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/events.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/events.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/loader.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/loader.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/nodes.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/nodes.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/parser.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/parser.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/reader.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/reader.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/representer.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/representer.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/resolver.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/resolver.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/scanner.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/scanner.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/serializer.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/serializer.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/tokens.cpython-37.opt-1.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/__pycache__/tokens.cpython-37.pyc 
>  exists in both 'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/composer.py exists in both 
>  'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/constructor.py exists in both 
>  'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/cyaml.py exists in both 'python-yaml' 
>  and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/dumper.py exists in both 
>  'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/emitter.py exists in both 
>  'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/error.py exists in both 'python-yaml' 
>  and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/events.py exists in both 
>  'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/loader.py exists in both 
>  'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/nodes.py exists in both 'python-yaml' 
>  and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/parser.py exists in both 
>  'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/reader.py exists in both 
>  'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/representer.py exists in both 
>  'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/resolver.py exists in both 
>  'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/scanner.py exists in both 
>  'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/serializer.py exists in both 
>  'python-yaml' and 'python-pyyaml'
>  /usr/lib/python3.7/site-packages/yaml/tokens.py exists in both 
>  'python-yaml' and 'python-pyyaml'
>  /usr/lib/python2.7/site-packages/bcrypt/__init__.py exists in both 
>  'python2-bcrypt' and 'python2-py-bcrypt'
>  /usr/lib/python2.7/site-packages/bcrypt/__init__.pyc exists in both 
>  'python2-bcrypt' and 'python2-py-bcrypt'
>  /usr/lib/python2.7/site-packages/bcrypt/_bcrypt.so exists in both 
>  'python2-bcrypt' and 'python2-py-bcrypt'
>  testssl.sh: /usr/bin/testssl exists in filesystem (owned by testssl)
>  testssl.sh: /usr/share/man/man1/testssl.1.gz exists in filesystem (owned by 
>  testssl)
>  /usr/bin/tabulate exists in both 'python2-tabulate' and 'python-tabulate'
>  /usr/lib/python2.7/site-packages/examples/__init__.py exists in both 
>  'python2-cement' and 'python2-roguehostapd'
>  /usr/lib/python2.7/site-packages/examples/__init__.pyc exists in both 
>  'python2-cement' and 'python2-roguehostapd'
>  /usr/lib/python2.7/site-packages/examples/__init__.pyo exists in both 
>  'python2-cement' and 'python2-roguehostapd'
>  /usr/lib/python3.7/site-packages/tests/__init__.py exists in both 'gdbgui' 
>  and 'python-oauth2'
>  /usr/lib/python3.7/site-packages/tests/__pycache__/__init__.cpython-37.opt-1.pyc 
>  exists in both 'gdbgui' and 'python-oauth2'
>  /usr/lib/python3.7/site-packages/tests/__pycache__/__init__.cpython-37.pyc 
>  exists in both 'gdbgui' and 'python-oauth2'
>  /usr/bin/fileinfo exists in both 'python-retdec-python' and 'leptonica'
>  Errors occurred, no packages were upgraded.`
> 

So I ignored these packages and tried this

> pacman -Syu --ignore gdbgui leptonica python-retdec-python python2-cement python2-roguehostapd python-pyyaml python-yaml python2-bcrypt python2-py-bcrypt testssl.sh python2-tabulate python-tabulate python2-pymongo python2-bson

But I still seem to get this

> $ pacman -Syu --ignore gdbgui leptonica python-retdec-python python2-cement python2-roguehostapd python-pyyaml python-yaml python2-bcrypt python2-py-bcrypt testssl.sh python2-tabulate python-tabulate python2-pymongo python2-bson
> :: Synchronizing package databases...
>  core is up to date
>  extra is up to date
>  community is up to date
>  multilib is up to date
>  blackarch is up to date
> :: Starting full system upgrade...
> :: Replace ca-certificates-cacert with core/ca-certificates? [Y/n] 
> warning: gdbgui: ignoring package upgrade (334.71e669d-1 => 364.78eb7ca-2)
> warning: hcxtools: local (875.7a6b716-1) is newer than community (4.2.1+15+gbc206cc-1)                                                                                   %
> :: Replace libx264 with extra/x264? [Y/n]                                                                                                                                %
> warning: mbelib: local (41.27b3f1b-1) is newer than community (1.3.0-1)                                                                                                  %
> warning: multimon-ng: local (20180527-1) is newer than community (1.1.5-2)                                                                                               %
> :: Replace packer-io with community/packer? [Y/n] 
> warning: perl-data-validate-ip: local (0.27-4) is newer than community (0.27-2)
> warning: perl-parallel-forkmanager: local (1.19-4) is newer than community (1.19-3)
> :: Replace pkg-config with core/pkgconf? [Y/n] 
> resolving dependencies...
> looking for conflicting packages...
> warning: dependency cycle detected:
> warning: libglvnd will be installed before its mesa dependency
> warning: dependency cycle detected:
> warning: x264 will be installed before its ffmpeg dependency
> warning: dependency cycle detected:
> warning: python2-incremental will be installed before its python2-twisted dependency
> warning: dependency cycle detected:
> warning: lib32-mesa will be installed before its lib32-libglvnd dependency
> warning: dependency cycle detected:
> warning: python-incremental will be installed before its python-twisted dependency
> 
> ... Lot of files ...
> 
> Total Installed Size:  12118.46 MiB
> Net Upgrade Size:       1247.53 MiB
> 
> :: Proceed with installation? [Y/n] 
> (1980/1980) checking keys in keyring                                                                  [############################################################] 100%
> (1980/1980) checking package integrity                                                                [############################################################] 100%
> (1980/1980) loading package files                                                                     [############################################################] 100%
> (1980/1980) checking for file conflicts                                                               [############################################################] 100%
> error: failed to commit transaction (conflicting files)
> /usr/bin/fileinfo exists in both 'leptonica' and 'python-retdec-python'
> /usr/lib/python2.7/site-packages/examples/__init__.py exists in both 'python2-cement' and 'python2-roguehostapd'
> /usr/lib/python2.7/site-packages/examples/__init__.pyc exists in both 'python2-cement' and 'python2-roguehostapd'
> /usr/lib/python2.7/site-packages/examples/__init__.pyo exists in both 'python2-cement' and 'python2-roguehostapd'
> /usr/lib/python3.7/site-packages/yaml/__init__.py exists in both 'python-pyyaml' and 'python-yaml'                                                                       %
> /usr/lib/python3.7/site-packages/yaml/__pycache__/__init__.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml' 
> /usr/lib/python3.7/site-packages/yaml/__pycache__/__init__.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'                                               %
> /usr/lib/python3.7/site-packages/yaml/__pycache__/composer.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'                                         %
> /usr/lib/python3.7/site-packages/yaml/__pycache__/composer.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/constructor.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/constructor.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/cyaml.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/cyaml.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/dumper.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/dumper.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/emitter.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/emitter.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/error.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/error.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/events.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/events.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/loader.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/loader.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/nodes.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/nodes.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/parser.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/parser.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'                                                 %
> /usr/lib/python3.7/site-packages/yaml/__pycache__/reader.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'                                           %
> /usr/lib/python3.7/site-packages/yaml/__pycache__/reader.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'                                                 %
> /usr/lib/python3.7/site-packages/yaml/__pycache__/representer.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'                                      %
> /usr/lib/python3.7/site-packages/yaml/__pycache__/representer.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/resolver.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/resolver.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/scanner.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/scanner.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/serializer.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/serializer.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/tokens.cpython-37.opt-1.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/__pycache__/tokens.cpython-37.pyc exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/composer.py exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/constructor.py exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/cyaml.py exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/dumper.py exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/emitter.py exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/error.py exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/events.py exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/loader.py exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/nodes.py exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/parser.py exists in both 'python-pyyaml' and 'python-yaml'                                                                         %
> /usr/lib/python3.7/site-packages/yaml/reader.py exists in both 'python-pyyaml' and 'python-yaml'                                                                         %
> /usr/lib/python3.7/site-packages/yaml/representer.py exists in both 'python-pyyaml' and 'python-yaml'   
> /usr/lib/python3.7/site-packages/yaml/resolver.py exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/scanner.py exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/serializer.py exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python3.7/site-packages/yaml/tokens.py exists in both 'python-pyyaml' and 'python-yaml'
> /usr/lib/python2.7/site-packages/bcrypt/__init__.py exists in both 'python2-bcrypt' and 'python2-py-bcrypt'
> /usr/lib/python2.7/site-packages/bcrypt/__init__.pyc exists in both 'python2-bcrypt' and 'python2-py-bcrypt'
> /usr/lib/python2.7/site-packages/bcrypt/_bcrypt.so exists in both 'python2-bcrypt' and 'python2-py-bcrypt'
> testssl.sh: /usr/bin/testssl exists in filesystem (owned by testssl)
> testssl.sh: /usr/share/man/man1/testssl.1.gz exists in filesystem (owned by testssl)
> /usr/bin/tabulate exists in both 'python2-tabulate' and 'python-tabulate'
> /usr/lib/python2.7/site-packages/bson/objectid.py exists in both 'python2-pymongo' and 'python2-bson'
> /usr/lib/python2.7/site-packages/bson/objectid.pyc exists in both 'python2-pymongo' and 'python2-bson'
> /usr/lib/python2.7/site-packages/bson/objectid.pyo exists in both 'python2-pymongo' and 'python2-bson'
> /usr/lib/python2.7/site-packages/bson/py3compat.py exists in both 'python2-pymongo' and 'python2-bson'
> /usr/lib/python2.7/site-packages/bson/py3compat.pyc exists in both 'python2-pymongo' and 'python2-bson'
> /usr/lib/python2.7/site-packages/bson/py3compat.pyo exists in both 'python2-pymongo' and 'python2-bson'
> /usr/lib/python2.7/site-packages/bson/tz_util.py exists in both 'python2-pymongo' and 'python2-bson'
> /usr/lib/python2.7/site-packages/bson/tz_util.pyc exists in both 'python2-pymongo' and 'python2-bson'
> /usr/lib/python2.7/site-packages/bson/tz_util.pyo exists in both 'python2-pymongo' and 'python2-bson'
> Errors occurred, no packages were upgraded.

--force seems to be depriciated to be used, even --overwrite flag doesn't help.

**Comment by n0tty** [comment]
pacman -Syu --overwrite="*" worked now.

**Comment by islamux** [comment]
pacman -Syu --overwrite="*"
Oh thanx a lot friend .
It works like a charm ^_^

**Comment by islamux** [comment]
pacman -Syu --overwrite="*" 

Thanx friend .it works like a charm ^_^

**Comment by TenKTech** [comment]
> What was the exact syntax you inputted? I am having the same issue, but I just think I'm using the "overwrite" option wrong.
The exact command is exactly as follows.  Worked for me too.
pacman -Syu --overwrite="*"
