### ISSUE TITLE
The "nipe" tool does not work

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2011]

**Comment by noptrix** [comment]
what's the error?

**Comment by GasparVardanyan** [comment]
Internet does not workin when nipe is enabled.

**Comment by Edu4rdSHL** [comment]
I hope that when the next two commits are merged into nipe/master the problem is fixed.

Start.pm: https://github.com/GouveaHeitor/nipe/commit/5e5e8257b4fa423070741168949a0826de91c9e4

Stop.pm: https://github.com/GouveaHeitor/nipe/commit/2703585526258ab92a495e915c5f1719edd633bf

**Comment by GouveaHeitor** [comment]
This has already been corrected, thanks to @Edu4rdSHL
