### ISSUE TITLE
Socialfish issues

### ISSUE THREAD

**Issue by Franchium** [BlackArch/blackarch#2015]
When i'm updating socialfish tools by pacman -Sy socialfish and finish then i went to run it i got a msg "use python 3 $ python3 SocialFish.py

How to fix that? I do also update python3 and 2 and thats not fix the problem

**Comment by noptrix** [comment]
we will fix that. hold on

**Comment by noptrix** [comment]
@Franchium should be fixed now. switch to blackarch.org in your mirror-list temporarily and update the tool or wait until your mirror gets synced

**Comment by Franchium** [comment]
there is still error reported
socialfish
Traceback (most recent call last) :
 File "SocialFish.py", line 35, in <module>
     From core.phisingRunner import *
 File "/usr/share/socialfish/core/phisingRunner.py", line 16, in <module>
    import request
ModuleNotFoundError:  No module named 'requests'

**Comment by Franchium** [comment]
So i just need to change import request on line 16 to import requests?
