### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by FFY00** [BlackArch/blackarch#2017]
You are providing some of the same packages as the official arch repo under a different name. Several ruby packages are packaging its dependencies together with them. Some python packages are installing to the top level python lib directory. We can't even install the `blackarch` group as is instructed.

I am sorry if this sounds a little harsh but I seriously don't understand where you want to go with this project. I don't expect something like this to be perfect but I expect it to be at least usable out of the box.

**Comment by noptrix** [comment]
@FFY00 "We can't even install the blackarch group as is instructed." Please paste the error you had after following the instructions for 'strap.sh'. The rest what you wrote about is unimportant. Check pacman options ('--overwrite'). It is usable, so we don't need to work on perfectionism. Also, who is we? Are you talking on behalf of all the archlinux users?

**Comment by FFY00** [comment]
> Also, who is we? Are you talking on behalf of all the archlinux users?
Yes, I am talking on behalf of the arch users.

> It is usable, so we don't need to work on perfectionism.
Most of the packages yes, but there are several conflicting.

> The rest what you wrote about is unimportant.
It most certainly is. You are duplicating dependencies, that you don't even maintain properly and you are packaging dependencies together with the main package, generating several conflicts.

> "We can't even install the blackarch group as is instructed." Please paste the error you had after following the instructions for 'strap.sh'.
As I said, several conflicts. Two of them are `ssrf-proxy` and `yawast`. You didn't pass `--ignore-dependencies` when you invoked `gem` in the `PKGBUILD` so they are installing the dependencies together with them, thus conflicting. You can reproduce this on any Blackarch installation by simply running `pacman -Suy && pacman -S blackarch`.

**Comment by noptrix** [comment]
alright. we will come up with a solution for these issues you mentioned (confliciting files, etc.), yes some packages missed appropriate ruby-gem options. we are also aware of these things... for now you could simply stick with `--overwrite='*'` option. most of the tools should then be usable.

**Comment by FFY00** [comment]
No problem. I might send a few PRs fixing this issues if I have time. I just expected it to work out of the box. These issues are fairly basic.

If you want to save up sone time, you can use [this](https://github.com/anatol/quarry) instead of packaging ruby gems yourselves. It's automatic and it was built by an arch Dev so it's reliable.

**Comment by FFY00** [comment]
Also, I have taken some time to review the open PRs. If you want, I can do this periodically. I think it will help reducing the workload and increase the overall quality of the packages.

**Comment by FFY00** [comment]
Update. Here's the log of `pacman -S blackarch`.

http://sprunge.us/yCGMwe

**Comment by noptrix** [comment]
Thanks again. Fixed via #2019
