### ISSUE TITLE
Proposal - Enforce a commiting style and rebases

### ISSUE THREAD

**Issue by FFY00** [BlackArch/blackarch#2021]
### Proposal 1 - Commit style

Right now the git history looks very messy.

![Old Commit Style](https://user-images.githubusercontent.com/11718923/45183685-b4fb5a00-b21c-11e8-9ca3-51141e905833.png)
(note that the merge commits don't get shadowed or indicate they are merge commits by default, that's a personal customization)

I propose we move to something more cleaner and organized, as shown below.

![New Commit Style](https://user-images.githubusercontent.com/11718923/45183902-48cd2600-b21d-11e8-8f47-0a71d1919b8c.png)
(this image was taken from #2019)

Now, to the proposal itself.

The style I propose (shown above) should follow 3 simple rules:
  - Conform with the format `package: message`
  - Should be all lowercase
  - The message should be as clean as possible and somewhat descriptive, not generic (Ex. `fix some things`)

### Proposal 2 - Use rebase instead of merges

Using rebases instead of merges have several benefits, the more relevant being a cleaner git history and avoid duplicated commits (merge commits).

Merge (the actual commit + the merge commit)
![Merge](https://user-images.githubusercontent.com/11718923/45184241-46b79700-b21e-11e8-9d7d-cf9fb562b02d.png)

Rebase (one simple commit, authored by the contributor and committed by the maintainer)
![Rebase](https://user-images.githubusercontent.com/11718923/45184312-85e5e800-b21e-11e8-8fd9-7eda89566d53.png)

Now, please note. there are two ways of doing this. The first is a simple rebase (`Rebase and Merge`), which will add all the PR commits to the git history, and the second is to squash the commits (`Squash and Merge`), which will squash all the commits into one then add it to the git history.

We need to know how to choose from this two. It's quite simple actually.

If the PR only modifies/adds one package, then we use the `Squash and Merge`. When we use the `Squash and Merge` we should **change the commit message** to respect the style introduced in Proposal 1. A good example would be #2022.

If the PR modifies/adds several packages, we should use the `Rebase and Merge`. When we use the `Rebase and Merge` we **must ask the PR author to conform with the style in Proposal 1**. An example would be #2029.

Using rebases/squash instead of merges is pretty straightforward, just select it in the github UI :smile: 

![PR Method](https://i.imgur.com/eNSBvmO.png)

**Comment by noptrix** [comment]
completely agree on this. we started to follow your proposals. thank you.

**Comment by Edu4rdSHL** [comment]
I can close it since that we have adopted the recommendations, we should add it to the documentation for future developers.
