### ISSUE TITLE
Repository for sqlninja broken

### ISSUE THREAD

**Issue by elroxar** [BlackArch/blackarch#2033]
`:: Retrieving packages...
error: failed retrieving file 'sqlninja-0.2.999-6-any.pkg.tar.xz' from www.mirrorservice.org : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
`
I get this after trying to install blackarch on top of an existing arch installation

**Comment by noptrix** [comment]
@elroxar which mirror do you use?

**Comment by elroxar** [comment]
@noptrix 'worldwide'

**Comment by noptrix** [comment]
? cat /etc/pacman.d/blackarch-mirror I want to know the address.

**Comment by elroxar** [comment]
This file doesn't exist. I only have the file /etc/pacman.d/blackarch-mirrorlist

**Comment by noptrix** [comment]
yes give me the address of the active mirror

**Comment by elroxar** [comment]
In that file there is one line uncommented it is
`Server = http://www.mirrorservice.org/sites/blackarch.org/blackarch/$repo/os/$arch`

**Comment by noptrix** [comment]
ok. now deactivate that one and try this one instead: Server = http://ftp.halifax.rwth-aachen.de/blackarch/$repo/os/$arch (germany). then do: pacman -Syu

**Comment by elroxar** [comment]
Ok. That worked. Thanks!
