### ISSUE TITLE
[BUG] SimplyEmail install

### ISSUE THREAD

**Issue by y0no** [BlackArch/blackarch#2041]
It seems that multiple dependencies are missing for SimplyEmail package.
We need to add these one : python2-lxml python2-mechanize python2-beautifulsoup3 python2-fake-useragent python2-magic

**Comment by Edu4rdSHL** [comment]
It also needs python2-configparser.

**Comment by y0no** [comment]
👍

**Comment by noptrix** [comment]
thank you @Edu4rdSHL
