### ISSUE TITLE
[BUG] URH install

### ISSUE THREAD

**Issue by y0no** [BlackArch/blackarch#2045]
URH seems to need "cython" as dependency to run correctly.

**Comment by noptrix** [comment]
@y0no urh is not managed by us anymore. arch comunity is maintaining it. please file a bug there. :)

**Comment by FFY00** [comment]
I am actually the maintainer :grin:. If you don't mind I could resolve the issue here, @noptrix.

Can I see the error @y0no?

**Comment by noptrix** [comment]
@FFY00 oh nice :) yeah sure, go ahead.

**Comment by FFY00** [comment]
Weird. I'll release a new revision.
