### ISSUE TITLE
[Pacman error] error: failed to commit transaction (conflicting files)

### ISSUE THREAD

**Issue by Dyotson** [BlackArch/blackarch#2046]
Hi, so trying to upgrade my packages, this happened:

:: Proceed with installation? [Y/n] y                                                                                                                                     
(3731/3731) checking keys in keyring               [######################] 100%                                                                                          
(3731/3731) checking package integrity             [######################] 100%                                                                                          
(3731/3731) loading package files                  [######################] 100%                                                                                          
(3731/3731) checking for file conflicts            [######################] 100%                                                                                          
error: failed to commit transaction (conflicting files)                                                                                                                   
/usr/lib/python2.7/site-packages/bcrypt/__init__.py exists in both 'python2-bcry                                                                                          pt' and 'python2-py-bcrypt'                                                                                                                                               
/usr/lib/python2.7/site-packages/bcrypt/__init__.pyc exists in both 'python2-bcr                                                                                          ypt' and 'python2-py-bcrypt'                                                                                                                                              
/usr/lib/python2.7/site-packages/bcrypt/_bcrypt.so exists in both 'python2-bcryp                                                                                          t' and 'python2-py-bcrypt'                                                                                                                                                
/usr/lib/python2.7/site-packages/bson/objectid.py exists in both 'python2-pymong                                                                                          o' and 'python2-bson'                                                                                                                                               
/usr/lib/python2.7/site-packages/bson/objectid.pyc exists in both 'python2-pymon                                                                                          go' and 'python2-bson'                                                                                                                                                  
/usr/lib/python2.7/site-packages/bson/objectid.pyo exists in both 'python2-pymon                                                                                          go' and 'python2-bson'                                                                                                                                                  
/usr/lib/python2.7/site-packages/bson/py3compat.py exists in both 'python2-pymon                                                                                          go' and 'python2-bson'                                                                                                                                                  
/usr/lib/python2.7/site-packages/bson/py3compat.pyc exists in both 'python2-pymo                                                                                          ngo' and 'python2-bson'                                                                                                                                                   
/usr/lib/python2.7/site-packages/bson/py3compat.pyo exists in both 'python2-pymo                                                                                          ngo' and 'python2-bson'                                                                                                                                                   
/usr/lib/python2.7/site-packages/bson/tz_util.py exists in both 'python2-pymongo                                                                                          ' and 'python2-bson'                                                                                                                                            
/usr/lib/python2.7/site-packages/bson/tz_util.pyc exists in both 'python2-pymong                                                                                          o' and 'python2-bson'                                                                                                                                               
/usr/lib/python2.7/site-packages/bson/tz_util.pyo exists in both 'python2-pymong                                                                                          o' and 'python2-bson'                                                                                                                                               
/usr/lib/python2.7/site-packages/tests/__init__.py exists in both 'python2-norma                                                                                          lity' and 'inquisitor'                                                                                                                                                  
/usr/lib/python2.7/site-packages/tests/__init__.pyc exists in both 'python2-norm                                                                                          ality' and 'inquisitor'                                                                                                                                                   
/usr/lib/python2.7/site-packages/tests/__init__.pyo exists in both 'python2-norm                                             and 'python2-pyyaml'                                                                                                                                            
/usr/lib/python2.7/site-packages/yaml/emitter.pyo exists in both 'python2-yaml'                                                                                           and 'python2-pyyaml'                                                                                                                                            
/usr/lib/python2.7/site-packages/yaml/error.py exists in both 'python2-yaml' and                                                                                           'python2-pyyaml'                                                                                                                                   
/usr/lib/python2.7/site-packages/yaml/error.pyc exists in both 'python2-yaml' an                                                                                          d 'python2-pyyaml'                                                                                                                                      
/usr/lib/python2.7/site-packages/yaml/error.pyo exists in both 'python2-yaml' an                                                                                          d 'python2-pyyaml'                                                                                                                                      
/usr/lib/python2.7/site-packages/yaml/events.py exists in both 'python2-yaml' an                                                                                          d 'python2-pyyaml'                                                                                                                                      
/usr/lib/python2.7/site-packages/yaml/events.pyc exists in both 'python2-yaml' a                                                                                          nd 'python2-pyyaml'                                                                                                                                         
/usr/lib/python2.7/site-packages/yaml/events.pyo exists in both 'python2-yaml' a                                                                                          nd 'python2-pyyaml'                                                                                                                                         
/usr/lib/python2.7/site-packages/yaml/loader.py exists in both 'python2-yaml' an                                                                                          d 'python2-pyyaml'                                                                                                                                      
/usr/lib/python2.7/site-packages/yaml/loader.pyc exists in both 'python2-yaml' a                                                                                          nd 'python2-pyyaml'                                                                                                                                         
/usr/lib/python2.7/site-packages/yaml/loader.pyo exists in both 'python2-yaml' a                                                                                          nd 'python2-pyyaml'                                                                                                                                         
/usr/lib/python2.7/site-packages/yaml/nodes.py exists in both 'python2-yaml' and                                                                                           'python2-pyyaml'                                                                                                                                   
/usr/lib/python2.7/site-packages/yaml/nodes.pyc exists in both 'python2-yaml' an                                                                                          d 'python2-pyyaml'                                                                                                                                      
/usr/lib/python2.7/site-packages/yaml/nodes.pyo exists in both 'python2-yaml' an                                                                                          d 'python2-pyyaml'                                                                                                                                      
/usr/lib/python2.7/site-packages/yaml/parser.py exists in both 'python2-yaml' an                                                                                          d 'python2-pyyaml'                                                                                                                                      
/usr/lib/python2.7/site-packages/yaml/parser.pyc exists in both 'python2-yaml' a                                                                                          nd 'python2-pyyaml'                                                                                                                                         
/usr/lib/python2.7/site-packages/yaml/parser.pyo exists in both 'python2-yaml' a                                                                                          nd 'python2-pyyaml'                                                                                                                                         
/usr/lib/python2.7/site-packages/yaml/reader.py exists in both 'python2-yaml' an                                                                                          d 'python2-pyyaml'                                                                                                                                      
/usr/lib/python2.7/site-packages/yaml/reader.pyc exists in both 'python2-yaml' a                                                                                          nd 'python2-pyyaml'                                                                                                                                         
/usr/lib/python2.7/site-packages/yaml/reader.pyo exists in both 'python2-yaml' a                                                                                          nd 'python2-pyyaml'                                                                                                                                         
/usr/lib/python2.7/site-packages/yaml/representer.py exists in both 'python2-yam                                                                                          l' and 'python2-pyyaml'                                                                                                                                                   
/usr/lib/python2.7/site-packages/yaml/representer.pyc exists in both 'python2-ya                                                                                          ml' and 'python2-pyyaml'                                                                                                                                                  
/usr/lib/python2.7/site-packages/yaml/representer.pyo exists in both 'python2-ya                                                                                          ml' and 'python2-pyyaml' 
/usr/lib/python2.7/site-packages/yaml/resolver.py exists in both 'python2-yaml' and 'python2-pyyaml'
/usr/lib/python2.7/site-packages/yaml/resolver.pyc exists in both 'python2-yaml' and 'python2-pyyaml'
/usr/lib/python2.7/site-packages/yaml/resolver.pyo exists in both 'python2-yaml' and 'python2-pyyaml'
/usr/lib/python2.7/site-packages/yaml/scanner.py exists in both 'python2-yaml' and 'python2-pyyaml'
/usr/lib/python2.7/site-packages/yaml/scanner.pyc exists in both 'python2-yaml' and 'python2-pyyaml'
/usr/lib/python2.7/site-packages/yaml/scanner.pyo exists in both 'python2-yaml' and 'python2-pyyaml'
/usr/lib/python2.7/site-packages/yaml/serializer.py exists in both 'python2-yaml' and 'python2-pyyaml'
/usr/lib/python2.7/site-packages/yaml/serializer.pyc exists in both 'python2-yaml' and 'python2-pyyaml'
/usr/lib/python2.7/site-packages/yaml/serializer.pyo exists in both 'python2-yaml' and 'python2-pyyaml'
/usr/lib/python2.7/site-packages/yaml/tokens.py exists in both 'python2-yaml' and 'python2-pyyaml'
/usr/lib/python2.7/site-packages/yaml/tokens.pyc exists in both 'python2-yaml' and 'python2-pyyaml'
/usr/lib/python2.7/site-packages/yaml/tokens.pyo exists in both 'python2-yaml' and 'python2-pyyaml'
/usr/bin/tabulate exists in both 'python2-tabulate' and 'python-tabulate'
/usr/lib/python2.7/site-packages/socks.py exists in both 'python2-socksipy-branch' and 'python2-pysocks'
/usr/lib/python2.7/site-packages/socks.pyc exists in both 'python2-socksipy-branch' and 'python2-pysocks'
/usr/lib/python2.7/site-packages/socks.pyo exists in both 'python2-socksipy-branch' and 'python2-pysocks'
/usr/lib/python2.7/site-packages/examples/__init__.py exists in both 'python2-cement' and 'python2-roguehostapd'
/usr/lib/python2.7/site-packages/examples/__init__.pyc exists in both 'python2-cement' and 'python2-roguehostapd'
/usr/lib/python2.7/site-packages/examples/__init__.pyo exists in both 'python2-cement' and 'python2-roguehostapd'
/usr/lib/python3.7/site-packages/tests/__init__.py exists in both 'gdbgui' and 'python-oauth2'
/usr/lib/python3.7/site-packages/tests/__pycache__/__init__.cpython-37.opt-1.pyc exists in both 'gdbgui' and 'python-oauth2'
/usr/lib/python3.7/site-packages/tests/__pycache__/__init__.cpython-37.pyc exists in both 'gdbgui' and 'python-oauth2'
/usr/bin/fileinfo exists in both 'python-retdec-python' and 'leptonica'
Errors occurred, no packages were upgraded.

It's seems that python is conflicting with something, not letting me upgrade

**Comment by Edu4rdSHL** [comment]
You can use the `--overwrite` option. See `man pacman`

```
       --overwrite <glob>
           Bypass file conflict checks and overwrite conflicting files. If the package that is about to be installed contains files
           that are already installed and match glob, this option will cause all those files to be overwritten. Using --overwrite
           will not allow overwriting a directory with a file or installing packages with conflicting files and directories.
           Multiple patterns can be specified by separating them with a comma. May be specified multiple times. Patterns can be
           negated, such that files matching them will not be overwritten, by prefixing them with an exclamation mark. Subsequent
           matches will override previous ones. A leading literal exclamation mark or backslash needs to be escaped.

```

**Comment by Dyotson** [comment]
Still having the same problem when upgrading

Using: pacman -S blackarch --overwrite python2 --overwrite python3

**Comment by Edu4rdSHL** [comment]
You are using improperly the `--overwrite` option. Read again, you need specify the file(s) to overwrite like `pacman -S --overwrite path/to/overwrite/* package` for recursively overwriting and  `pacman -S --overwrite file/to/overwrite package` to overwrite a specific file.

**Comment by Dyotson** [comment]
Tried what you said, same error the commands that I used:

[ archdyot ~ ]# pacman -S --overwrite /usr/lib/python3.7/ python3
[ archdyot ~ ]# pacman -S --overwrite /usr/lib/python2.7/ python2

**Comment by Dyotson** [comment]
When I run the commands I get a bunch of warnings too

**Comment by Edu4rdSHL** [comment]
Don't use the root slash `/` use: `pacman -S --overwrite usr/lib/python3.7/* usr/lib/python2.7/* python3 python2`

**Comment by Dyotson** [comment]
Now I get this:

warning: '/usr/lib/python2.7/zipfile.pyo' is a file, did you mean -U/--upgrade instead of -S/--sync?

**Comment by Edu4rdSHL** [comment]
Try with `pacman -Syu --ignore python-retdec-python` && `pacman -Syu`

**Comment by Franchium** [comment]
Tried pacman -S archlinux-keyring

**Comment by noptrix** [comment]
also, most of them should be fixed now. please use: pacman ... --overwrite='*' - closing this issue here.

**Comment by paulo203to** [comment]
I'm trying to install weechat this is the log https://url.privatepastebin.com/88 I don't seem to find any answers online

**Comment by ikstream** [comment]
What was the command you actually ran?

In addition, none of the conflicting packages is  maintained by us, nor is weechat. 
If you know, what you are doing, you can use the overwrite flag for pacman.
