### ISSUE TITLE
Modem

### ISSUE THREAD

**Issue by Franchium** [BlackArch/blackarch#2047]
How can i use usb modem on Blackarch?

**Comment by myrage2000** [comment]
Yes.

**Comment by Franchium** [comment]
Manual what?

**Comment by Franchium** [comment]
Manual what?

**Comment by ikstream** [comment]
This is not a  replacement for a search engine. "how to use a modem on arch linux" provides several hits. Please use a search engine of your choice for not-blackarch related problems.
