### ISSUE TITLE
Python conflicting file errors

### ISSUE THREAD

**Issue by IrkenEngineer** [BlackArch/blackarch#2051]
I'm trying to install certain catergories of BlackArch onto an existing instance of Arch. During installation, it stops when it gets to blackarch-config and I see this error:

```
error: failed to commit transaction (conflicting files) 
/usr/bin/tabulate exists in both 'python-tabulate' and 'python2-tabulate'
/usr/bin/fileinfo exists in both 'leptonica' and 'pythong-retdec-python'
Errors occurred, no packages were upgraded.
```

**Comment by FFY00** [comment]
@noptrix, just `mv "$pkgdir"/usr/bin/tabulate "$pkgdir"/usr/bin/tabulate2` in the python2 variant. `leptonica` seems to be packaging `fileinfo`?!!

**Comment by noptrix** [comment]
@FFY00 yep, i would do that with tabulate -> tabulate2. no idea about leptonica...i will move that fileinfo as well to fileinfo-leptonica or sth similar.

**Comment by noptrix** [comment]
@FFY00 python{2}-tabulate is not maintained by us anymore. it's m. via arch linux community.

**Comment by noptrix** [comment]
@FFY00 @IrkenEngineer ok, so all packages listed here including python{2}-tabulate, leptonica and pythong-retdec-python packages are not maintained by us. No idea what to do here.

**Comment by FFY00** [comment]
I'll take a look when I get home.

**Comment by noptrix** [comment]
@FFY00 thank you.

**Comment by noptrix** [comment]
@IrkenEngineer for the latter, cann you do: pacman -Rns pythong-retdec-python? because that package doesn't exist neither in blackarch nor in arch or arch AUR.

**Comment by noptrix** [comment]
@IrkenEngineer ok the last one i just fixed it (you wrote the package name wrong): python-retdec-python. released the fix. depends now on your blackarch mirror. but stll, you will get error with tabulate.

**Comment by IrkenEngineer** [comment]
Would changing mirrors possibly help the tabulate issue?

**Comment by noptrix** [comment]
@IrkenEngineer which mirror do you use?

**Comment by noptrix** [comment]
@IrkenEngineer maybe switch temporarily to blackarch.org and do the following (install pkgfile before) as root:
```
pacman -Rscn $(pacman -Qtdq)
updatedb
sync
pkgfile -u
yes | pacman -Scc --noconfirm
pacman -Syyu
```

**Comment by FFY00** [comment]
The tabulate issue was reported to the correct maintainer and the fileinfo one was fixed by https://github.com/BlackArch/blackarch/commit/5a77bc3e0aa542c869d6f2f5f111ebc8bf5c35e7.

Thank you.
