### ISSUE TITLE
pacman -Syy blackarch Error

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2055]
(3705/3705) checking for file conflicts                                                    [####################################################] 100%
error: failed to commit transaction (conflicting files)
/usr/lib/python2.7/site-packages/bcrypt/__init__.py exists in both 'python2-bcrypt' and 'python2-py-bcrypt'
/usr/lib/python2.7/site-packages/bcrypt/__init__.pyc exists in both 'python2-bcrypt' and 'python2-py-bcrypt'
/usr/lib/python2.7/site-packages/bcrypt/_bcrypt.so exists in both 'python2-bcrypt' and 'python2-py-bcrypt'
/usr/lib/python2.7/site-packages/bson/objectid.py exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/objectid.pyc exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/objectid.pyo exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/py3compat.py exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/py3compat.pyc exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/py3compat.pyo exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/tz_util.py exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/tz_util.pyc exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/tz_util.pyo exists in both 'python2-pymongo' and 'python2-bson'
blackarch-mirrorlist: /etc/pacman.d/blackarch-mirrorlist exists in filesystem
Errors occurred, no packages were upgraded.

**Comment by FFY00** [comment]
@noptrix you need to delete `pyhton2-py-bcrypt and remove it from https://github.com/BlackArch/blackarch/blob/3b78b8fe52384f74d9733a4e02efd0c24da22caa/packages/hasher/PKGBUILD#L11. You also need to remove `python2-bson`, I'll try to resolve the `python2-pymongo` issue.

**Comment by FFY00** [comment]
I had a look at it. `python2-bson` shouldn't be removed, it just should conflict with `python2-pymongo`.

**Comment by noptrix** [comment]
should be ok now. closing ticket
