### ISSUE TITLE
Errors occurred, no packages were upgraded.

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2057]
error: failed to commit transaction (conflicting files)
blackarch-mirrorlist: /etc/pacman.d/blackarch-mirrorlist exists in filesystem
Errors occurred, no packages were upgraded.

**Comment by noptrix** [comment]
@GasparVardanyan what did you do when you got this error?

**Comment by Edu4rdSHL** [comment]
Seeing the content of blackarch-mirrorlist (https://www.blackarch.org/blackarch-mirrorlist) it's safe to use `--overwrite etc/pacman.d/blackarch-mirrorlist` as pacman argument.

**Comment by GasparVardanyan** [comment]
@noptrix pacman -Syy blackarch

**Comment by noptrix** [comment]
@GasparVardanyan you can do what @Edu4rdSHL said: ```pacman -Syyu --overwrit='etc/pacman.d/blackarch-mirrorlist' --needed blackarch```

**Comment by GasparVardanyan** [comment]
> @GasparVardanyan what did you do when you got this error?
