### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2067]
:: Proceed with installation? [Y/n] 
(44/44) checking keys in keyring                   [######################] 100%
(44/44) checking package integrity                 [######################] 100%
(44/44) loading package files                      [######################] 100%
(44/44) checking for file conflicts                [######################] 100%
error: failed to commit transaction (conflicting files)
python2-cheetah: /usr/bin/cheetah exists in filesystem (owned by cheetah-suite)
Errors occurred, no packages were upgraded.

**Comment by noptrix** [comment]
We've removed cheetah-suite. Please remove it with: ```pacman -Rns cheetah-suite```

**Comment by GasparVardanyan** [comment]
Thank u.

**Comment by noptrix** [comment]
thanks. closing ticket
