### ISSUE TITLE
Upgrade Error - Conflicting Files Error 

### ISSUE THREAD

**Issue by 0xTHEgod** [BlackArch/blackarch#2077]
`**error:** failed to comit transaction (conflicting files)
/usr/lib/python3.7/site-packages/yaml/__init__.py exists in both 'python-yaml and python-pyyaml
/usr/lib/python3.7/site-packages/yaml/__pycache__/__init__.cpython-37.opt-1.pyc exists in both python-yaml and python-pyyaml
/usr/lib/python3.7/site-packages/yaml/__pycache__/__init__.cpython-37.pyc exists in both python-yaml and python pyyaml
/usr/lib/python3.7/site-packages/yaml/__pycache__/composer.cpython-37.opt-1.pyc exists in both python-yaml and python pyyaml`  ... and so on and so forth. 

I receive this message every time I attempt to update `pacman -Syu`

I tried to `--overwrite` the files. Perhaps I am not inputting the correct syntax `sudo pacman -Syu --overwrite=usr/lib/python3.7/site-packages/yaml/*` but I am in need of help here. 

Any responses would be greatly appreciated.

**Comment by Edu4rdSHL** [comment]
Use `pacman -Syu --overwrite='*'`

**Comment by 0xTHEgod** [comment]
I believe I am inputting the wrong syntax for the overwrite option. Based on the info I gave earlier, what would the overwrite specifically look like?

**Comment by Edu4rdSHL** [comment]
The --overwrite option takes an argument containing a glob. When used pacman will bypass file conflict checks for files that match the glob. You were not using a full path and not a glob.
