### ISSUE TITLE
@745275633 Run this script and let us know: http://sprunge.us/hYFJ - Also, which mirror do you use for BlackArch?

### ISSUE THREAD

**Issue by islamux** [BlackArch/blackarch#2080]
_Originally posted by @noptrix in https://github.com/BlackArch/blackarch/issues/1746#issuecomment-324282182_

This script did it . 
thanx.  ^_^

**Comment by islamux** [comment]
I had a problem in update & upgrad and that script solve it.

**Comment by islamux** [comment]
I had a problem in update and upgrad but this script solved it.
thanx a lot.

**Comment by ikstream** [comment]
As there seems to be no issue here, I am going to close it. If you think this is wrong, please leave additional information.

BR
