### ISSUE TITLE
Package named blackarch-menus seems like outdated

### ISSUE THREAD

**Issue by sTiKyt** [BlackArch/blackarch#2083]
My config:
Arch Linux
KDE Plasma
I don't have all directories in my Application Menu after installing blackarch-menus, only some of this.
Seems like this package wasn't updated since 2014, someone check it please, or explain what i'm doing wrong.

**Comment by ikstream** [comment]
which directory is missing

**Comment by noptrix** [comment]
@ikstream anything else we need to do? i've bumped the version number to 0.3 and released it. sorry, no idea about the menus package :)

**Comment by ikstream** [comment]
@noptrix i don't use a DE, so i am not sure about this as well. But i suspect, that there are several .desktop files missing for the tools available in Blackarch, so the tools don't show up in the menu.

**Comment by udomthongpai** [comment]
Want to fold barch openbox menu into an existing openbox menu, but the openbox menu version on github is 6 months old. Right now I could only do this by dowloading the latest barch iso and pulling out the menu. That's the long way around. Can the version on github be updated?

**Comment by noraj** [comment]
Seems like an outdated issue.

I guess openbox was updated since.
