### ISSUE TITLE
Installation is broken

### ISSUE THREAD

**Issue by TotallyLegitHuman** [BlackArch/blackarch#2084]
So i was installing BlackArch on a Virtual Machine (I'm using virtual box in case that's important.)
and i followed every step in the guide, even checked a few youtube videos to see if i had to do anything special to install it on a VM, but whatever i do it always seems to mess up somewhere in the installation,
after i finish setting what is root, boot and swap, it tells me to leave it to install, so i do, only to come back maybe half an hour later to see a screen being spammed with just this message, repeatedly :
" Chroot : could not run command 'passwd' : input/output error "

I have looked on the internet for a solution to this, but so far i haven't seen anything, it's like i'm the only one having this problem, does anyone know what might be causing this? is it because i'm trying to install it on a VM?
I really don't know what information to give since i have no idea what this even is, so if you need information to fix it just tell me what you need and i guess i'l add it.
Thanks in advance to anyone who is willing to try and help me.

**Comment by mrsmith0x00** [comment]
@TotallyLegitHuman you install from BlackArch repository (online)?
If yes, do you look for the best server on Arch Linux mirrorlist setup stage?
You tried to reinstall anew?
And please send more information, that we could help.

**Comment by mrsmith0x00** [comment]
@TotallyLegitHuman hmm, Arch base system install normally? Do you install all tools?

**Comment by mrsmith0x00** [comment]
@TotallyLegitHuman your issue: #1982 ?

**Comment by TotallyLegitHuman** [comment]
No that issue is not mine, but i have almost the same problem.
and what do you mean by arch base systems? does this mean i have to install arch, then install blackarch over it?
(Have i been doing it wrong this whole time??????)

**Comment by ikstream** [comment]
The Installation is separated into several parts, in one step, arch linux will be installed, in a next step the blackarch tools will be added. 

In general it is possible to install an Arch System and just add Blackarch on top of it.

**Comment by GasparVardanyan** [comment]
You can install Arch Linux and then do this:
wget https://blackarch.org/strap.sh
chmod +x strap.sh
sudo ./strap.sh
sudo pacman -Syy blackarch
