### ISSUE TITLE
Dislocker libmbedcrypto.so.1 => not found

### ISSUE THREAD

**Issue by 23pieces** [BlackArch/blackarch#2086]
Hi everyone!

When dislocker is installed the following error occurs:
dislocker: error while loading shared libraries: libmbedcrypto.so.1: cannot open shared object file: No such file or directory

The libmbedcrypto version that's installed with the package is libmbedcrypto.so.3.
The dislocker binary can also run with the so.3 library.

Maybe someone could either recompile the package with .so.3 or make a symlink while installation, for example:
ln -s libmbedcrypto.so.3 libmbedcrypto.so.1

Best regards
23pieces

**Comment by noptrix** [comment]
@23pieces thanks for this. should be fixed now.
