### ISSUE TITLE
i3 config error

### ISSUE THREAD

**Issue by xamafe** [BlackArch/blackarch#2089]
Hi,

I installed i3 as wm.
If I start i3 I get an errorbar.
The logfile states:
`ERROR: CONFIG: Expected one of these tokens: <word> `
`ERROR: CONFIG: (in file /home/watchme/.config/i3/config)`
`ERROR: CONFIG: Line 132: # Class                 border          backgr      text            indic`
`ERROR: CONFIG: Line 133: client.focused                      #000000     `
`ERROR: CONFIG: Line 134: client.focused_inactive                     `
`ERROR: CONFIG:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`ERROR: CONFIG: Line 135: client.unfocused                              `
`ERROR: CONFIG: Line 136: client.urgent           #000000        #000000`       
`ERROR: CONFIG: Expected one of these tokens: <word>`
`ERROR: CONFIG: (in file /home/watchme/.config/i3/config)`
`ERROR: CONFIG: Line 133: client.focused                      #000000`     
`ERROR: CONFIG: Line 134: client.focused_inactive                     `
`ERROR: CONFIG: Line 135: client.unfocused                              `
`ERROR: CONFIG:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`ERROR: CONFIG: Line 136: client.urgent           #000000        #000000       `
`ERROR: CONFIG: Line 137: client.placeholder                           `
`ERROR: CONFIG: Expected one of these tokens: <word>`
`ERROR: CONFIG: (in file /home/watchme/.config/i3/config)`
`ERROR: CONFIG: Line 134: client.focused_inactive            `         
`ERROR: CONFIG: Line 135: client.unfocused                       `       
`ERROR: CONFIG: Line 136: client.urgent           #000000        #000000`       
`ERROR: CONFIG:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`ERROR: CONFIG: Line 137: client.placeholder                           `
`ERROR: CONFIG: Line 138: `
`ERROR: CONFIG: Expected one of these tokens: <word>`
`ERROR: CONFIG: (in file /home/watchme/.config/i3/config)`
`ERROR: CONFIG: Line 135: client.unfocused                      `        
`ERROR: CONFIG: Line 136: client.urgent           #000000        #000000`       
`ERROR: CONFIG: Line 137: client.placeholder                           `
`ERROR: CONFIG:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`ERROR: CONFIG: Line 138: `
`ERROR: CONFIG: Line 139: # Define names for default workspaces for which we configure key bindings later on.`
`ERROR: CONFIG: Expected one of these tokens: <word>`
`ERROR: CONFIG: (in file /home/watchme/.config/i3/config)`
`ERROR: CONFIG: Line 136: client.urgent           #000000        #000000`       
`ERROR: CONFIG: Line 137: client.placeholder                           `
`ERROR: CONFIG: Line 138: `
`ERROR: CONFIG:           `
`ERROR: CONFIG: Line 139: # Define names for default workspaces for which we configure key bindings later on.`
`ERROR: CONFIG: Line 140: # We use variables to avoid repeating the names in multiple places.`
`ERROR: FYI: You are using i3 version 4.15 (2018-03-10)`

In the config file of i3 in lin 112ff there are many colors set.
For example:
`set_from_resource $xcolor0 color0`
But these colors aren't defined in .Xresources, except foreground and background.

Workaround:
comment all the lines from 134 to 138
`134 client.focused          $xcolor6       $xcolor1     $xbackground $xcolor7`
`135 client.focused_inactive $xcolor6       $xcolor0     $xcolor14  `
`136 client.unfocused        $xcolor6       $xcolor0     $xcolor14      `  
`137 client.urgent           $xbackground   $xcolor9     $xbackground`
`138 client.placeholder      $xcolor7       $xcolor7     $xcolor14`

Did I miss something?

**Comment by ikstream** [comment]
@xamafe did you install the blackarch-config-i3 package as well, or did you use the default i3 config?

**Comment by PedroSFreitas** [comment]
@xamafe, thanks for reaching out. Indeed we have a problem with our configuration, which is on hold due a non-merged PR.

Please check this link: https://github.com/BlackArch/blackarch-config-i3/issues/4

**Comment by xamafe** [comment]
sorry for the delay, I used the blackarch-config-i3

**Comment by Luraktinus** [comment]
i used the official iso and it happens there too, please set the default config for the next iso or fix it

**Comment by ikstream** [comment]
This problem should be fixed with  /BlackArch/blackarch-config-i3#7
