### ISSUE TITLE
fluxbox startup script issue

### ISSUE THREAD

**Issue by g0rbe** [BlackArch/blackarch#2090]
The issue:

Fluxbox's startup script (.fluxbox/startup) not run by default. If i place a script in it, it will not going to run.

The solution:

I modified one line /etc/lxdm/lxdm.conf
`session=/usr/bin/fluxbox` **->** `session=/usr/bin/startfluxbox`

According to the manual, startfluxbox execute the ~/.fluxbox/startup, where the last line is `exec fluxbox`

Anyway, i started using BlackArch today, very satisfied with it :slightly_smiling_face:

**Comment by noptrix** [comment]
@g0rbe thanks a lot. will be fixed.

**Comment by noptrix** [comment]
thanks a gain @g0rbe :)
