### ISSUE TITLE
wifi-pumpkin requests installed Networkmanager

### ISSUE THREAD

**Issue by xamafe** [BlackArch/blackarch#2091]
Hi,

I installed blackarch from iso (no previous arch install) on a T440.
All tools were installed.
When I tried to start wifi-pumpkin, "nmcli" was missing.
After installing and starting Networkmanager and connecting inet via eth0, I could start the hostapd.

My request would be to install NetworkManager within the normal installation, if wifi-pumpkin is installed.

Thanks

**Comment by mrsmith0x00** [comment]
@xamafe added, thanks a lot!
