### ISSUE TITLE
Stops at [OK] Reached target Graphical Interface. while installation

### ISSUE THREAD

**Issue by YasirRehman2017** [BlackArch/blackarch#2092]
Hi, I want to install black arch on my VPS The [ ISO File](http://ftp.halifax.rwth-aachen.de/blackarch/iso/blackarch-linux-live-2018.06.01-x86_64.iso) has been uploaded the to it and while I try to boot from it. It stucks at [OK] Reached target Graphical Interface. I'm a totally Newbie To Linux so please tell me the answser with some details.

**Comment by mrsmith0x00** [comment]
@YasirRehman2017 you should use netinstall iso, but... if you totally newbie, please know that you need another distro for a start (seriously, don't play in hackers).

**Comment by YasirRehman2017** [comment]
> @YasirRehman2017 you should use netinstall iso, but... if you totally newbie, please know that you need another distro for a start (seriously, don't play in hackers).

i have used ubuntu a lot but have no idea about the Arch Linux
