### ISSUE TITLE
Errors occurred, no packages were upgraded.

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2095]
:: Proceed with installation? [Y/n] 
(102/102) checking keys in keyring                                                         [####################################################] 100%
(102/102) checking package integrity                                                       [####################################################] 100%
(102/102) loading package files                                                            [####################################################] 100%
(102/102) checking for file conflicts                                                      [####################################################] 100%
error: failed to commit transaction (conflicting files)
python-rpyc: /usr/bin/rpyc_classic.py exists in filesystem (owned by python2-rpyc)
python-rpyc: /usr/bin/rpyc_registry.py exists in filesystem (owned by python2-rpyc)
python-z3: /usr/lib/python3.7/site-packages/z3/__init__.py exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/__init__.cpython-37.opt-1.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/__init__.cpython-37.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3.cpython-37.opt-1.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3.cpython-37.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3consts.cpython-37.opt-1.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3consts.cpython-37.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3core.cpython-37.opt-1.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3core.cpython-37.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3num.cpython-37.opt-1.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3num.cpython-37.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3poly.cpython-37.opt-1.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3poly.cpython-37.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3printer.cpython-37.opt-1.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3printer.cpython-37.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3rcf.cpython-37.opt-1.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3rcf.cpython-37.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3types.cpython-37.opt-1.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3types.cpython-37.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3util.cpython-37.opt-1.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/__pycache__/z3util.cpython-37.pyc exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/z3.py exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/z3consts.py exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/z3core.py exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/z3num.py exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/z3poly.py exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/z3printer.py exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/z3rcf.py exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/z3types.py exists in filesystem (owned by python-z3-solver)
python-z3: /usr/lib/python3.7/site-packages/z3/z3util.py exists in filesystem (owned by python-z3-solver)
Errors occurred, no packages were upgraded.

**Comment by noptrix** [comment]
@GasparVardanyan remove 'python-z3-solve' first by issuing: ```sudo pacman -Rns python-z3-solver``` then run ```sudo pacman -Su --overwrite='*'``` it is safe here.

**Comment by GasparVardanyan** [comment]
Շնորհակալություն։
