### ISSUE TITLE
[Tool Execution Fail] Btlejack

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2101]
Hello,

I have an error when trying to launch btlejack:

> Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 895, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (colorama 0.4.0 (/usr/lib/python3.7/site-packages), Requirement.parse('colorama==0.3.9'), {'halo'})
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/btlejack", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3123, in <module>
>     @_call_aside
>   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3107, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3136, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 580, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 593, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'colorama==0.3.9' distribution was not found and is required by halo

**Distribution:** Arch Linux 64x 4.18.17.a-1-hardened

Cheers!

**Comment by Edu4rdSHL** [comment]
Hello, @s7x . Can you try to install python-colorama and run again btlejack? I can not reproduce the issue in a full BlackArch installation but seems that we need to add python-colorama as dependency.

**Comment by ikstream** [comment]
@s7x thanks for reporting, should be fixed now
