### ISSUE TITLE
IP-Tracer [Tool request]

### ISSUE THREAD

**Issue by Rajkumrdusad** [BlackArch/blackarch#2106]
IP-Tracer is tool for ip tracing using ip-api. We can trace any ip using ip tracer tool.
Tool Link https://github.com/Rajkumrdusad/IP-Tracer.git
if this tool is ready for BlackArch so please add this tool.

**Comment by Edu4rdSHL** [comment]
Hello, @Rajkumrdusad thanks for your tool advice but it need some important fixes. You're assuming specific paths in your tool and it causes errors when running like:
```
edu4rdshl@blackarch ~/Scripts/IP-Tracer -> ./trace -t 216.58.222.206
Could not open input file: /home/edu4rdshl/.IP-Tracer/modules/.traceip.php
```
That issues are caused by: https://github.com/Rajkumrdusad/IP-Tracer/blob/master/trace#L12, https://github.com/Rajkumrdusad/IP-Tracer/blob/master/trace#L21, https://github.com/Rajkumrdusad/IP-Tracer/blob/master/trace#L25 and https://github.com/Rajkumrdusad/IP-Tracer/blob/master/trace#L29. Please use relative PATHs and i can add it tool to BA.

**Comment by Rajkumrdusad** [comment]
Ok i will check it.

**Comment by Rajkumrdusad** [comment]
hey @Edu4rdSHL trace is a bin file and i think you are running IP-Tracer without install directly from IP-Tracer directory that's the error will come.
Use sh install command and then type edu4rdshl@blackarch ~ -> trace -t 216.58.222.206
There are no any error but if there are need any change to add this on blackarch so we can change.

**Comment by Edu4rdSHL** [comment]
@Rajkumrdusad you need to know that when we add a tool, it's installed in /opt or /usr/share (depending of the case if we compile it or not) and if it's a bash tool it need to be ready for running. I used the install command and it basically copy all files except `trace` to $HOME, we don't hace reason to modify users home only by installing a tool.

**Comment by Rajkumrdusad** [comment]
fixed That issues are caused by: https://github.com/Rajkumrdusad/IP-Tracer/blob/master/trace#L12, https://github.com/Rajkumrdusad/IP-Tracer/blob/master/trace#L21, https://github.com/Rajkumrdusad/IP-Tracer/blob/master/trace#L25 and https://github.com/Rajkumrdusad/IP-Tracer/blob/master/trace#L29.

**Comment by Edu4rdSHL** [comment]
Yeah, it's better. Please, can you add a shebang line in the top of `trace`?

**Comment by Rajkumrdusad** [comment]
Yes

**Comment by Rajkumrdusad** [comment]
Shebang line is added in trace and ip-tracer file.

**Comment by Edu4rdSHL** [comment]
Don't use `#!/bin/bash`, please use `#!/usr/bin/env bash`

**Comment by Rajkumrdusad** [comment]
Ok

**Comment by Rajkumrdusad** [comment]
Done `#!/usr/bin/env bash` added in trace and ip-tracer

**Comment by Edu4rdSHL** [comment]
Then the tool is ready to add to BA, i'll add it very soon (where soon is less than 24 hours) :), thank you.

**Comment by Rajkumrdusad** [comment]
Thank's bro..

**Comment by Rajkumrdusad** [comment]
I think its more then a 24 hours. But tool is not added..

**Comment by noptrix** [comment]
> I think its more then a 24 hours. But tool is not added..

Doesn't matter. We are right now updating all tools and preparing for the new ISOs anyway. It is actually 'freeze time' for adding new packages.If you want to see hurrying progress for BlackArch consider to donate or help in anyway to this project.

@Edu4rdSHL let me know by adding the tool to 'to-release' file. :)

**Comment by Rajkumrdusad** [comment]
Great job keep it up. time doesn't metter.

**Comment by Edu4rdSHL** [comment]
@Rajkumrdusad please, make a new release of the tool, there are 25 commits to master since that release.

**Comment by Rajkumrdusad** [comment]
Ok done check it out it's works or not.

**Comment by Edu4rdSHL** [comment]
Tool added, thank you.

**Comment by Rajkumrdusad** [comment]
Thank You Bro.
