### ISSUE TITLE
[TOOL UPDATE REQUEST] Suricata compiled with LUA support

### ISSUE THREAD

**Issue by clarjon1** [BlackArch/blackarch#2111]
Hello,

Suricata has the ability to enable LUA scripting. In order to do this, it will need to be recompiled with luajit. 

Documentation for this is provided by OISF here: https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Installation_from_GIT_with_luajit

Thank you in advance!

**Comment by clarjon1** [comment]
After a bit of poking, it does appear that luajit is a dependency, and that lua support is enabled. However, from `suricata --build-info | grep -i lua`
Blackarch repo version: 
```
┗ suricata --build-info | grep -i lua
Features: NFQ PCAP_SET_BUFF AF_PACKET HAVE_PACKET_FANOUT LIBCAP_NG LIBNET1.1 HAVE_HTP_URI_NORMALIZE_HOOK PCRE_JIT HAVE_NSS HAVE_LUA HAVE_LIBJANSSON TLS MAGIC 
  LUA support:                             yes
  libluajit:                               no
```
From https://launchpad.net/~oisf/+archive/ubuntu/suricata-stable version ( Recommended by Suricata training ):
```
sigdev@sigdev:~$ suricata --build-info | grep -i lua
Features: NFQ PCAP_SET_BUFF AF_PACKET HAVE_PACKET_FANOUT LIBCAP_NG LIBNET1.1 HAVE_HTP_URI_NORMALIZE_HOOK PCRE_JIT HAVE_NSS HAVE_LUA HAVE_LUAJIT HAVE_LIBJANSSON PROFILING TLS MAGIC RUST 
  LUA support:                             yes, through luajit
  libluajit:                               yes
```

**Comment by noptrix** [comment]
done :) (reopen if wrong)
