### ISSUE TITLE
[Tool installation fail] Empire

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2117]
Hello there!
The tool empire fails to install with the following stack trace:

```
==> Starting package()...
/tmp/empire/PKGBUILD: line 58: /tmp/empire/pkg/empire/usr/bin/: Is a directory
==> ERROR: A failure occurred in package().
    Aborting...
[!] WARNING: Something wrong with makepkg: empire
loading packages...
error: '*.xz': could not find or read package
```

There's a typo in the PKGBUILD line 58: "pkgnae" instead of "pkgname"

Cheers!

**Comment by noptrix** [comment]
@s7x Perfect, thanks reporting all the errors. We'll fix them asap :)

**Comment by s7x** [comment]
> @s7x Perfect, thanks reporting all the errors. We'll fix them asap :)

I opened a last issue with all similar typos I found. Sorry for the spam :/
