### ISSUE TITLE
[Tool installation fail] Subfinder

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2119]
Hello there!

The tool subfinder fails to install, it tries to install go-pie as a dep but it's not referenced anywhere in the subfinder repo. Also the url of the repo is the old one. The new one is "https://github.com/subfinder/subfinder". It then fails to find the "README.md"

```
install: cannot stat 'src/https://github.com/subfinder/subfinder/README.md': No such file or directory
```

Cheers!

**Comment by noptrix** [comment]
thank you!
