### ISSUE TITLE
[Tool branch/version] Empire

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2124]
Hello there!
I would like to know if it could be envisaged to switch to the dev branch of Powershell "Empire" in Blackarch?

I'll explain why:

Most of the modules like process injection, mimikatz or custom Launcher arguments and such are not working against Windows updated in the last 6/7 months. They're not fixed in the master branch of their repo (cause I think they're waiting to launch a new release) but they're fixed in the dev branch (as seen in [#1237](https://github.com/EmpireProject/Empire/pull/1237) )

Do you think it would be a good idea? A lot of other things have been fixed too.

Cheers

**Comment by s7x** [comment]
@noptrix That's awesome news. Thanks a lot for all your work in NetSec's world.

**Comment by mrsmith0x00** [comment]
@s7x branch switched ;)
