### ISSUE TITLE
btscanner error loading shared libraries

### ISSUE THREAD

**Issue by 23pieces** [BlackArch/blackarch#2129]
Errors:
btscanner: error while loading shared libraries: libformw.so.5: cannot open shared object file: No such file or directory

btscanner: error while loading shared libraries: libmenuw.so.5: cannot open shared object file: No such file or directory

Fixes:

cd /usr/lib/
ln -s libformw.so.6.1 libformw.so.5
ln -s libmenuw.so.6.1 libmenuw.so.5

**Comment by 23pieces** [comment]
By the way the bruteforce mode is still crashing.
Does anyone still have the source for btscanner?
Maybe we could get a fix for that.

**Comment by noptrix** [comment]
thx. we've added the sources from pentoo distfiles mirror. see pkgbuild file
