### ISSUE TITLE
[Tool request] Trape

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2135]
Hello there!

A new tool as been presented at blackhat asia:
Trape. For OSINT/Phishing and stuff like that. You can track people though JS beacons, pish logins/creds, social engineering attacks ect... With a semi auto-implementation of ngrok for cheap & quick links.

https://github.com/jofpin/trape

Thought it might be a good idea to have this one in Blackarch.

Cheers!

**Comment by noptrix** [comment]
@s7x absolutely. thanks for sharing. will be added soon.

**Comment by s7x** [comment]
@noptrix Awesome! Thanks a lot!

**Comment by mrsmith0x00** [comment]
@s7x successfully added :)

**Comment by s7x** [comment]
@mrsmith0x00 Thanks a lot guys :)
