### ISSUE TITLE
[Tool request] HiddenEye

### ISSUE THREAD

**Issue by Franchium** [BlackArch/blackarch#2136]
HiddenEye is phishing tools that is more powerful and modern. I think that would be great and very useful for used. 

https://github.com/DarkSecDevelopers/HiddenEye

Thanks

**Comment by sTiKyt** [comment]
@Franchium thank you for this issue :3

**Comment by sTiKyt** [comment]
We must wait?
![image](https://user-images.githubusercontent.com/35602029/49490566-582e3080-f859-11e8-9ade-85e916dea12b.png)

**Comment by sTiKyt** [comment]
@Edu4rdSHL

**Comment by DeadNumbers** [comment]
@sTiKyt use `blackman -i hidden-eye`

**Comment by sTiKyt** [comment]
Yep, available, but PermissionError: (There no  permission problems in original version using git clone)
![image](https://user-images.githubusercontent.com/35602029/49540578-19d85600-f8d9-11e8-8274-b5b8db087665.png)

**Comment by sTiKyt** [comment]
@noptrix

**Comment by Edu4rdSHL** [comment]
That's a normal behavior because we are working into /usr/share.

**Comment by noptrix** [comment]
> @noptrix

see @Edu4rdSHL reply. use 'sudo' or hack as root :)
