### ISSUE TITLE
i3 Config issues/error and Gnome + Remmina Kiosk problem

### ISSUE THREAD

**Issue by Franchium** [BlackArch/blackarch#2146]
When im login using i3 wm there is an error like that, also there is a problem with GNOME + remmina Kiosk when im login with it i got back to login screen

![img_20181207_174635](https://user-images.githubusercontent.com/41231953/49643827-a5073800-fa0e-11e8-8c81-c95daf8ce507.jpg)
![img_20181207_174607](https://user-images.githubusercontent.com/41231953/49643894-d122b900-fa0e-11e8-94e1-244a4ff54bb4.jpg)
![img_20181207_174538](https://user-images.githubusercontent.com/41231953/49643896-d41da980-fa0e-11e8-8239-f9ce37deabab.jpg)

**Comment by ikstream** [comment]
please have a look at BlackArch/blackarch-config-i3#4

**Comment by Franchium** [comment]
I really dont understand? Does it means i just need to download that files and put in on Xresources? Or can you tell me step by step to fix it? How about Gnome + Remmina Kiosk issue?

**Comment by ikstream** [comment]
You need to apply the changes, introduced in the pull request to the according files.

I can't say anything about the gnome issue at the moment. Are there any entries in you journal from gnome, which could provide some pointers?

**Comment by Franchium** [comment]
I hope that will be fix on the next iso release

**Comment by Franchium** [comment]
And im completely dont understand how to applying the changes on the pull request

**Comment by ikstream** [comment]
You can view the new file on github, than copy paste it...
As for the Remmina kiosk, you can get the kiosk working if you install `gnome-session` `gnome-shell` and `gnome-settings-daemon`
To use a full fledge gnome desktop, you will have to install the gnome meta package.
