### ISSUE TITLE
Proposal - change repository name

### ISSUE THREAD

**Issue by Edu4rdSHL** [BlackArch/blackarch#2150]
I was considering the following: BlackArch Linux is a GNU/Linux distribution, the actual blackarch/blackarch repository only contain packages and is not the most proper name for the repo. Then I was considering the name change of `blackarch/blackarch` to `blackarch/blackarch-packages`.

I remain attentive to comments and approval of the team members.

Regards,
Eduard Toloza

**Comment by noraj** [comment]
Seems a good idea.

**Comment by noraj** [comment]
@Edu4rdSHL Did you think about the impact of that change?

**Comment by Edu4rdSHL** [comment]
@noraj as it's only used for development purposes the impact should be minimal (Team, contributors and build system).

@noptrix what do you think?

**Comment by noraj** [comment]
:+1:  `blackarch/blackarch-packages`

**Comment by ikstream** [comment]
I am indifferent about this. On the one hand it makes sense to rename it, but on the other hand it's a good landing point for people googling blackarch and wanting to contribute. I am not sure, if renaming it would reduce the amount of drive by contributions.

**Comment by Edu4rdSHL** [comment]
@ikstream we can use a repository redirection to avoid that.

**Comment by aancw** [comment]
@Edu4rdSHL If we change the name, it would affect existing tools or system that point to this repo?

**Comment by noraj** [comment]
Yes it certainly means we have to change the URL hardcoded in the website or blackman.

**Comment by aancw** [comment]
Then we need consider it for migration or keep as it if it's big issue.

**Comment by Edu4rdSHL** [comment]
It actually don't makes sense, we will keep the current name.
