### ISSUE TITLE
Linux OS Freeze problem with i915 driver

### ISSUE THREAD

**Issue by anilkaradag** [BlackArch/blackarch#2151]
**Hardware Info
-----------------**
Intel Apollo lake chipset and i915 driver for graphic card.

**OS Info
--------------------**
Debian Linux 9.3
Xorg is running with enabled(default mode) DPMS
installed firmware-misc-nonfree_20180825+dfsg-1_bpo9+1_all.deb package

**Problem Description
--------------------------**

After reviewed page [1], configured my Debian 9.3 Linux as like that. Tested system with tools stress(increase load average) and glxgears(mesa-utils) to graphic card rendering.

After 6h, system has been frozen. This is not first frozen with same scenario. Screenshots are accessible from [2]

First boot time: Dec 5 22:24
No logs after Dec 6 04:56(rcu_sched related logs has been raised at same time)
last boot time: Dec 8 16:58

[1] https://gist.github.com/Brainiarc7/aa43570f512906e882ad6cdd835efe57
[2] https://drive.google.com/drive/folders/1h7ZjZDR6Qax57mT6kwIlSJgnF4IVm-G7?usp=sharing

**Comment by Edu4rdSHL** [comment]
That is a Debian issue, not a BlackArch issue.
