### ISSUE TITLE
Internet does not work after "nipe start"

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2153]
https://i.imgur.com/PFk86yp.png

**Comment by ikstream** [comment]
Please provide some useful information with your issues.
Is the tor service running after you start nipe, are there any error messages related to nipe in the logs?

**Comment by GasparVardanyan** [comment]
https://imgur.com/a/qEAXu0T

**Comment by GasparVardanyan** [comment]
https://imgur.com/eRu8fqK

**Comment by Edu4rdSHL** [comment]
Please report it in https://github.com/GouveaHeitor/nipe/issues because it's a script issue. Also consideer using my own script https://gitlab.com/edu4rdshl/tor-router added to BA in af404f99f
