### ISSUE TITLE
ollydbg error

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2154]
wine: cannot find '/home/gaspar/.ollydbg/ollydbg.exe'

**Comment by GasparVardanyan** [comment]
┌─[gaspar@GasparVardanyan]─[~]
└──╼ $ sudo pacman -Syy ollydbg 
[sudo] password for gaspar: 
:: Synchronizing package databases...
 core                     132.7 KiB   207K/s 00:01 [######################] 100%
 extra                   1694.8 KiB   571K/s 00:03 [######################] 100%
 community                  4.7 MiB   488K/s 00:10 [######################] 100%
 multilib                 175.0 KiB   330K/s 00:01 [######################] 100%
 blackarch                  2.2 MiB   445K/s 00:05 [######################] 100%
 blackarch.sig            566.0   B  0.00B/s 00:00 [######################] 100%
warning: ollydbg-201g-8 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) ollydbg-201g-8

Total Installed Size:  3.45 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
:: Processing package changes...
(1/1) reinstalling ollydbg                         [######################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
┌─[gaspar@GasparVardanyan]─[~]
└──╼ $ ollydbg 
wine: cannot find '/home/gaspar/.ollydbg/ollydbg.exe'
┌─[✗]─[gaspar@GasparVardanyan]─[~]
└──╼ $

**Comment by GasparVardanyan** [comment]
Already works!

**Comment by ikstream** [comment]
Just for documentation: you have to remove the old ollydbg links in your home directory
