### ISSUE TITLE
TheFatRat

### ISSUE THREAD

**Issue by Franchium** [BlackArch/blackarch#2156]
why can't i run TheFatRat tools ? i tried enter thefatrat, fatrat and no command found.

**Comment by ikstream** [comment]
@mrsmith0x00 can you have a look into it?

**Comment by mrsmith0x00** [comment]
@Franchium did you run /usr/share/thefatrat/setup.sh ?

**Comment by Franchium** [comment]
I fix it by run setup.sh, but what i asking is why TheFatRat is not automatically installed? And when there is a request to run TheFatRat by enter fatrat command i tried to find fatrat on /bin or /usr/bin and couldn't find fatrat file (the one that run TheFatRat).

**Comment by Franchium** [comment]
In 2018.06.01 iso i should be able to run the tools without run setup.sh

**Comment by mrsmith0x00** [comment]
@Franchium some utilities, such as sniper && fatrat need to run setup.sh script on installed system.

**Comment by mrsmith0x00** [comment]
@Franchium now TheFatRat run without setup.sh
