### ISSUE TITLE
[Chore] blackbox-scanner source url died

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2162]
https://github.com/darkeyepy/blackbox => 404, because account deactivated

https://github.com/BlackArch/blackarch/blob/master/packages/blackbox-scanner/PKGBUILD

**Comment by noraj** [comment]
I laso have this error after install:

```
blackbox-scanner -h
Traceback (most recent call last):
  File "/bin/blackbox-scanner", line 16, in <module>
    from passlib.hash import nthash
ImportError: No module named passlib.hash
```

**Comment by noraj** [comment]
This is the same tool but this one is v2.0, the dead one was v2.2 so this is a downgrade

**Comment by ikstream** [comment]
I had a look into the forks and there seems to be one, which is ahead and on version 2.2
would you prefer if we use that one?
https://github.com/geosphere/blackbox

**Comment by noraj** [comment]
@ikstream Yeah, looks better !
