### ISSUE TITLE
Please apply Google Chrome to your browsers.

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2165]

**Comment by mrsmith0x00** [comment]
@GasparVardanyan we have three excellent browsers: chromium, elinks, firefox. If you need Google Chrome, please, install it by self with `yay -Sy google-chrome` !

**Comment by nhlinux** [comment]
"
[ blackarch ~ ]# yay -Sy google-chrome
Please avoid running yay as root/sudo.
:: Synchronizing package databases...
error: failed retrieving file 'core.db' from ftp.kaist.ac.kr : Connection timed out after 10001 milliseconds
 core is up to date
error: failed retrieving file 'extra.db' from ftp.kaist.ac.kr : Connection timed out after 10001 milliseconds
 extra                   1646.0 KiB  1746K/s 00:01 [######################] 100%
error: failed retrieving file 'community.db' from ftp.kaist.ac.kr : Connection timed out after 10001 milliseconds
 community                  4.7 MiB  1632K/s 00:03 [######################] 100%
error: failed retrieving file 'multilib.db' from ftp.kaist.ac.kr : Connection timed out after 10001 milliseconds
 multilib is up to date
 blackarch is up to date
:: There are 3 providers available for google-chrome:
:: Repository AUR
    1) google-chrome 2) google-chrome-beta 3) google-chrome-dev 

Enter a number (default=1): 1
==> Refusing to install AUR Packages as root, Aborting.
[ blackarch ~ ]# 
"
I don't understand. I'm not a system admin. Just a Linux end user.
Nick E.H.
