### ISSUE TITLE
[install error] No $APP installed

### ISSUE THREAD

**Issue by xamafe** [BlackArch/blackarch#2173]
Hi,

I installed blackarch from scratch. (It downloaded the newest installscript)
If you open fluxbox, you get an error, that no fbsetbg app is installed.

Also Firefox and chromium arent installed.

Thx for fixing
Xamafe

**Comment by ikstream** [comment]
What does from scratch mean? Did you install it on top of an arch linux installation, or did you use a live iso?
Did you install all tools? How much space did you provide for your install?

**Comment by Edu4rdSHL** [comment]
It isn't reproducible since that when setting up Window Managers from the blackarch-install script it install fluxbox here https://github.com/BlackArch/blackarch-installer/blob/master/blackarch-install#L1902 and fluxbox provides fbsetbg.

```
 ➤➤ $ pacman -Fs fbsetbg
extra/fluxbox 1.3.7-5
    usr/bin/fbsetbg
```
