### ISSUE TITLE
xterm: Selected font has no non-zero height for ISO-8859-1 encoding

### ISSUE THREAD

**Issue by begoodat5** [BlackArch/blackarch#2178]
xterm: Selected font has no non-zero height for ISO-8859-1 encoding

**Comment by noptrix** [comment]
https://bugs.archlinux.org/task/61237?string=xterm&project=5&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto= (bug report) https://www.archlinux.org/packages/?q=xterm (wait few hours/days)
