### ISSUE TITLE
[Tool installation fail] python2-iptools

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2185]
Hello there!

There's a problem in the PKGBUILD of python2-iptools.

```
/tmp/python2-iptools/PKGBUILD: line 14: syntax error near unexpected token `)'
/tmp/python2-iptools/PKGBUILD: line 14: `        'LICENSE')'
==> ERROR: Failed to source /tmp/python2-iptools/PKGBUILD
```

The problem lies line 14 of the PKGBUILD:

```
14	        'LICENSE')
```

Cheers!

**Comment by s7x** [comment]
@noptrix Awesome thanks!

**Comment by s7x** [comment]
@noptrix Another error:

In the PKGBUILD, the lines 19 and 25 needs to be changed, from:
**cd python-iptools-$pkgver** to **iptools-$pkgver**

Cheers!

**Comment by noptrix** [comment]
@s7x thanks a lot for your issues. i've fixed all of them and re-releasing the packages now. cheers mate

**Comment by s7x** [comment]
@noptrix No worries. Love your work so I'm doing what I can ;)
Cheers & thanks!
