### ISSUE TITLE
[Tool request] Bashfuscator

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2190]
Hello there!

A very cool python framework/utility to obfuscate bash code.

[Article here](https://0x00sec.org/t/yes-bash-can-get-uglier-introducing-bashfuscator-a-bash-obfuscation-framework/10216)
[Link to the repo](https://github.com/Bashfuscator/Bashfuscator)

Could be a great addition to evade signature based IDS and such.

Cheers!

**Comment by mrsmith0x00** [comment]
@s7x added!
