### ISSUE TITLE
drupwn: from git to release version

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2195]
https://github.com/BlackArch/blackarch/blob/master/packages/drupwn/PKGBUILD

from git to release version for easier maintaining https://github.com/immunIT/drupwn/releases

**Comment by mrsmith0x00** [comment]
@noraj thanks, it's moved ;)

**Comment by noraj** [comment]
e3a3f080c947eb0f64423ef86852d915d72afd21
