### ISSUE TITLE
morpheus error

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2196]
which: no apache2 in (/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-ndk:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)

g[☠] apache2 -> not found! 
g[☠] This script requires apache2 to work! 
g[☠] Please run: sudo apt-get install apache 
g[☠] to install missing dependencies...

**Comment by mrsmith0x00** [comment]
@GasparVardanyan fixed ;)
