### ISSUE TITLE
[dirsearch] valueerror error

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2201]
By default dirsearch save logs in the install dir causing permission error :
```

 _|. _ _  _  _  _ _|_    v0.3.8
(_||| _) (/_(_|| (_| )

Extensions: php | Threads: 4 | Wordlist size: 5979
Traceback (most recent call last):
  File "/usr/share/dirsearch/dirsearch.py", line 40, in <module>
    main = Program()
  File "/usr/share/dirsearch/dirsearch.py", line 36, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/usr/share/dirsearch/lib/controller/Controller.py", line 102, in __init__
    self.setupErrorLogs()
  File "/usr/share/dirsearch/lib/controller/Controller.py", line 226, in setupErrorLogs
    self.errorLog = open(self.errorLogPath, "w")
PermissionError: [Errno 13] Permission denied: '/usr/share/dirsearch/logs/errors-19-01-23_11-42-34.log'

```

But I found on their issue tracker there is a way to change the configuration: https://github.com/maurosoria/dirsearch/issues/92

So we should change https://github.com/BlackArch/blackarch/blob/master/packages/dirsearch/PKGBUILD and uncomment `save-logs-home = True` in `/usr/share/dirsearch/default.conf`.

**Comment by noraj** [comment]
`sed -i '/save-logs-home/s/^#//g' /usr/share/dirsearch/default.conf `

**Comment by noraj** [comment]
Thx @noptrix, I didn't PR directly because I was not sure about how to put the sed in the PKBUILD. Now I have an example.

**Comment by noraj** [comment]
![image](https://user-images.githubusercontent.com/16578570/94342620-81154c00-0012-11eb-9025-4c9dda77f05c.png)

**Comment by Edu4rdSHL** [comment]
It isn't an "log permission error", please open another bug report as it's unrelated but also you're bumping an old bug from more than one year.

**Comment by noraj** [comment]
@Edu4rdSHL Not exactly the same but anyway it's related to `save-logs-home`, ok it's not permission this time.
I wanted to quickly log that so I can fix it later myself.

**Comment by Edu4rdSHL** [comment]
Please don't bump old issues an/or modify them, it just difficult things for people searching issues. If you are going to fix it, just make the commit and that's all. Thanks.

**Comment by noraj** [comment]
> If you are going to fix it, just make the commit and that's all. Thanks.

If I do in a few days I'll have forgotten about it so I need to log it in an issue. I'll make a new one.
