### ISSUE TITLE
airflood: keep or not ?

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2203]
airflood 0.1 is the first and last version of airflood release in [2006](https://packetstormsecurity.com/files/51127/airflood.1.tar.gz.html). So the tool is clearly abandoned.
But more importantly  the tool is 100% in Spanish.

```
╰─➤  sudo airflood --help
airflood 0.1 - (C) 2006 nilp0inter2k6_at_gmail.com

  ataques:
     -F : LLena el espacio de clientes de la red
     -L : Igual que -F pero en repeticion continua

  opciones:
     -e : ESSID de la red
     -a : BSSID de la red
     -d : Retardo entre paquetes keep-alive
     -h : Cliente autentico de la red que se quiere expulsar
     -c : Cantidad de paquetes de desautentificacion en cada envio
     -v : MAC reservada en el espacio de clientes
     -t : Si se cumple el tiempo de un cliente se actualizan todos (util en algunos AP)

  uso: airflood <ataque> [opciones] <interfaz>
```
Also the tool is a massive reuse of aireplay-ng. As far as I understand we can do the same with `aireplay-ng --deauth`.

I think this is quite useless to have a tool like that.
Do you think we must keep this tool ?

**Comment by noptrix** [comment]
completely true what you say @noraj. but we have our own philosophy... long story short: we don't know how $tool_x and $tool_y act on specific situations. some tools act different, some tools bring other results. we know that the repository is very redundant but at the same time we want to give fully options, choice and control to the user ... normally, the philosophy is bigger than what i wrote now but this would really overflow this github issue :) if you are on IRC we can talk about that.

i am closing this ticket here

**Comment by noraj** [comment]
I understand and I agree but the tool here is not in English so at least it should be mentioned in the description.

**Comment by noraj** [comment]
#2206
