### ISSUE TITLE
airgeddon: packaging

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2204]
airgeddon https://github.com/BlackArch/blackarch/blob/master/packages/airgeddon/PKGBUILD is built with *git release* but they officially provides an ARCH tarball https://github.com/v1s1t0r1sh3r3/airgeddon/tree/master/binaries/arch and versioned releases https://github.com/v1s1t0r1sh3r3/airgeddon/releases.

**Comment by s7x** [comment]
@noptrix that's a great news! Will blackman be updated/supported some day with such thing? I know it's not a priority package for the Team to work on but I must admit I use it a lot to not mess around with thousands of repos from git and stuff like that. I'm running a simple Arch with custom tools from your repo and it works really well this way.

Cheers!

**Comment by noraj** [comment]
@noptrix Update for the unstable repository ?
