### ISSUE TITLE
Problem first connection in the new installation

### ISSUE THREAD

**Issue by vincenzopalazzo** [BlackArch/blackarch#2207]
Hello, I'm new in this context and in the first installation the blacharch I have a problem whit the internet interface.

When do you run pacman -S new-packege I get this error: `error: falied retriving file "specific file"` and when I do run a ping www.site.com I get this error `Temporary faliure in name resolution`. How I do resolve?

ps: sorry for my terrible English but i'm learning

**Comment by ikstream** [comment]
How did you install blackarch?
Probably the responsible service is disabled, or your network is not configured

**Comment by vincenzopalazzo** [comment]
Hello @ikstream, I did install blackarch whit the configure dns automatic, How do configure the network? sorry for questions stupid.

**Comment by mrsmith0x00** [comment]
@vincenzopalazzo run `systemctl enable wicd && systemctl start wicd` as root and then find wicd-gtk in menu and run it ;)

**Comment by vincenzopalazzo** [comment]
Oh, @mrsmith0x00 have it very simple! sorry form my incompetence, and another question, for install gnome that suffice do install gnome extra? I have not install X display in the procedure installation

**Comment by mrsmith0x00** [comment]
@vincenzopalazzo `pacman -Syu gnome gnome-extra && systemctl enable gdm.service NetworkManager.service && systemctl disable wicd && shutdown -r now`

Xorg server is installed by default, even you didn't install WMs.

**Comment by vincenzopalazzo** [comment]
I do run the process, thanks for the support, I would to develop a simple tool for the system.

**Comment by vincenzopalazzo** [comment]
@mrsmith0x00 Sorry, at the end process, I do login in the GUI and the login is OK but I do not go in the principal windows, it is a my error?

**Comment by vincenzopalazzo** [comment]
@mrsmith0x00 the login is OK but remains in the windows the login

**Comment by mrsmith0x00** [comment]
@vincenzopalazzo you login as root in gdm?

**Comment by vincenzopalazzo** [comment]
@mrsmith0x00 no,i login as a normal account

**Comment by mrsmith0x00** [comment]
@vincenzopalazzo hmm, all should be ok... Please, send me photo!

**Comment by vincenzopalazzo** [comment]
@mrsmith0x00 yes, this is my problem [click me](https://gph.is/2RTn73a)

**Comment by mrsmith0x00** [comment]
@vincenzopalazzo try to (as normal user): `sudo rm -rf ~/.Xauthority`, and then reboot

**Comment by vincenzopalazzo** [comment]
@mrsmith0x00 The file .Xauthority not exist, and when I try command startx I get an error file .Xauthority not exist and the normal user not have a permission

**Comment by mrsmith0x00** [comment]
@vincenzopalazzo what do you do after install? (excluding gnome and chown) and do you install lxdm and any WMs?

**Comment by vincenzopalazzo** [comment]
When the procedure installer left, I runned the OS and I logged in the system

**Comment by mrsmith0x00** [comment]
@vincenzopalazzo i mean then install do you install WMs?

**Comment by vincenzopalazzo** [comment]
oh sorry, no I do not install in WM, but in the real machine

**Comment by mrsmith0x00** [comment]
@vincenzopalazzo i mean windows managers (e.g. i3, fluxbox), not virtualbox!

**Comment by vincenzopalazzo** [comment]
Oh, no I don't install Windows manager

**Comment by mrsmith0x00** [comment]
@vincenzopalazzo good, you do something that cause this problem (i don't know what, but my coworker use Gnome with BlackArch without any errors).
You have two path:

1. Make fresh install without any desktop environments and windows managers, and then use my command with Gnome -> enjoy!

2. Install Antergos with Gnome and then simply add BlackArch repo: https://blackarch.org/downloads.html#install-repo -> enjoy!

**Comment by mrsmith0x00** [comment]
At this point i closed issue.

**Comment by vincenzopalazzo** [comment]
@mrsmith0x00 Thanks for your support, and another question, the Antergos have the possibility simple dual boot?

**Comment by mrsmith0x00** [comment]
@vincenzopalazzo yeah, have

**Comment by vincenzopalazzo** [comment]
@mrsmith0x00 thanks
