### ISSUE TITLE
Outdated ngrok

### ISSUE THREAD

**Issue by sTiKyt** [BlackArch/blackarch#2208]
![image](https://user-images.githubusercontent.com/35602029/51788585-4d708780-2188-11e9-93bb-1df1ee3e15fa.png)

**Comment by ikstream** [comment]
How did you install ngrok?

the last number is usually the package release number and marks changes on a PKGBUILD file, while the version of the package doesn't change.

**Comment by noptrix** [comment]
@sTiKyt u installed ngrok before adding the blackarch repository, thus your version is from AUR, which is 2.2.8-2. and as @ikstream mentioned already, this indicates the rel number (pkgrel). simply reinstall ngrok with ```yay -S ngrok``` to get rid of that warning and to use the official blackarch version rather the AUR one. closing ticket here

**Comment by sTiKyt** [comment]
Ok, i'm sorry :D
I'm just very beginner at LInux
