### ISSUE TITLE
Raspberry Pi 2 installation in Arch Linux - dependencies not resolving

### ISSUE THREAD

**Issue by pnylon** [BlackArch/blackarch#2210]
Hello, I was trying to install blackarch in Arch Linux on a Raspberry Pi 2+, but I'm seeing quite a few warnings on the dependencies. Everything was OK up until I ran `sudo pacman -S blackarch`. 

I thought I was doing something wrong, but I can't find any info about this anywhere after searching for a while. I saw an old issue posted back in early 2016 but nothing appears to have been resolved in that one.

`Enter a selection (default=all): 
warning: argon2-20171227-3 is up to date -- reinstalling
warning: iputils-20180629.f6aac8d-3 is up to date -- reinstalling
warning: nmap-7.70-2 is up to date -- reinstalling
warning: packer-1.3.3-1 is up to date -- reinstalling
warning: downgrading package yay (9.1.0-1 => 9.0.0-1)
resolving dependencies...
:: There are 4 providers available for java-environment:
:: Repository extra
   1) jdk-openjdk  2) jdk10-openjdk  3) jdk7-openjdk  4) jdk8-openjdk

Enter a number (default=1): 
warning: cannot resolve "python2-pyside", a dependency of "androbugs"
warning: cannot resolve "python-pyside", a dependency of "angr-management"
warning: cannot resolve "ruby2.3", a dependency of "arachni"
warning: cannot resolve "ruby2.3", a dependency of "ruby2.3-bundler"
warning: cannot resolve "ruby2.3-bundler", a dependency of "arachni"
warning: cannot resolve "pypy", a dependency of "python2-pyshark"
warning: cannot resolve "python2-pyshark", a dependency of "arpstraw"
:: There are 15 providers available for linux-headers:
:: Repository core
   1) linux-am33x-headers  2) linux-armv7-headers  3) linux-armv7-rc-headers  4) linux-clearfog-headers  5) linux-cubox-headers  6) linux-headers-odroid  7) linux-headers-utilite-dt  8) linux-imx6-headers
   9) linux-odroid-c1-headers  10) linux-odroid-xu3-headers  11) linux-peach-headers  12) linux-raspberrypi-headers  13) linux-utilite-headers  14) linux-veyron-headers  15) linux-zedboard-headers

Enter a number (default=1): 
warning: cannot resolve "mongodb", a dependency of "astra"
warning: cannot resolve "ruby2.3", a dependency of "arachni"
warning: cannot resolve "ruby2.3", a dependency of "ruby2.3-bundler"
warning: cannot resolve "ruby2.3-bundler", a dependency of "arachni"
warning: cannot resolve "arachni", a dependency of "autopwn"
warning: cannot resolve "python2-nassl", a dependency of "sslyze"
warning: cannot resolve "sslyze", a dependency of "autopwn"
warning: cannot resolve "wine", a dependency of "avet"
warning: cannot resolve "wine-mono", a dependency of "avet"
warning: cannot resolve "wine_gecko", a dependency of "avet"
warning: cannot resolve "wine", a dependency of "backdoorppt"
warning: cannot resolve "python2-pyside", a dependency of "binaryninja-python"
warning: cannot resolve "x3270", a dependency of "birp"
warning: cannot resolve "obexftp", a dependency of "bluediving"
warning: cannot resolve "openobex", a dependency of "bluediving"
:: There are 2 providers available for mysql:
:: Repository extra
   1) mariadb
:: Repository community
   2) percona-server

Enter a number (default=1): 
warning: cannot resolve "ruby2.3", a dependency of "cewl"
warning: cannot resolve "python2-pylibemu", a dependency of "chopshop"
warning: cannot resolve "john", a dependency of "cisco-snmp-enumeration"
warning: cannot resolve "john", a dependency of "crackserver"
warning: cannot resolve "python2-pyqt4", a dependency of "creepy"
warning: cannot resolve "ruby2.3", a dependency of "dradis"
warning: cannot resolve "ruby2.3", a dependency of "ruby2.3-bundler"
warning: cannot resolve "ruby2.3-bundler", a dependency of "dradis"
warning: cannot resolve "ruby2.3", a dependency of "dradis-ce"
warning: cannot resolve "ruby2.3", a dependency of "ruby2.3-bundler"
warning: cannot resolve "ruby2.3-bundler", a dependency of "dradis-ce"
warning: cannot resolve "python2-pyqt4", a dependency of "eyewitness"
warning: cannot resolve "python2-pyqt", a dependency of "ghost-py"
warning: cannot resolve "ghost-py", a dependency of "eyewitness"
warning: cannot resolve "python2-pyqt4", a dependency of "fern-wifi-cracker"
warning: cannot resolve "python2-pylibemu", a dependency of "flowinspect"
warning: cannot resolve "pyqt3", a dependency of "gerix-wifi-cracker"
warning: cannot resolve "python2-pyqt4", a dependency of "ghost-phisher"
warning: cannot resolve "python2-pyqt", a dependency of "ghost-py"
warning: cannot resolve "python2-pyqt4", a dependency of "hexorbase"
warning: cannot resolve "python2-qscintilla", a dependency of "hexorbase"
warning: cannot resolve "openobex", a dependency of "hidattack"
warning: cannot resolve "ruby2.3", a dependency of "hoper"
warning: cannot resolve "ruby2.3", a dependency of "whatweb"
warning: cannot resolve "whatweb", a dependency of "id-entify"
warning: cannot resolve "python2-pyqt", a dependency of "inguma"
warning: cannot resolve "wine", a dependency of "insanity"
warning: cannot resolve "python2-pyside", a dependency of "ipba2"
warning: cannot resolve "python2-pyqt4", a dependency of "iptv"
warning: cannot resolve "john", a dependency of "johnny"
warning: cannot resolve "ruby2.3", a dependency of "joomlavs"
warning: cannot resolve "ruby2.3", a dependency of "ruby2.3-bundler"
warning: cannot resolve "ruby2.3-bundler", a dependency of "joomlavs"
warning: cannot resolve "ruby2.3", a dependency of "arachni"
warning: cannot resolve "ruby2.3", a dependency of "ruby2.3-bundler"
warning: cannot resolve "ruby2.3-bundler", a dependency of "arachni"
warning: cannot resolve "arachni", a dependency of "lhf"
warning: cannot resolve "mongodb", a dependency of "malcom"
warning: cannot resolve "python2-pyside", a dependency of "binaryninja-python"
warning: cannot resolve "binaryninja-python", a dependency of "manticore"
warning: cannot resolve "solidity", a dependency of "manticore"
warning: cannot resolve "mongodb", a dependency of "nosqlattack"
warning: cannot resolve "libstdc++5", a dependency of "nsia"
warning: cannot resolve "python2-pyqt4", a dependency of "obevilion"
warning: cannot resolve "openobex", a dependency of "lightblue"
warning: cannot resolve "lightblue", a dependency of "obexstress"
warning: cannot resolve "mongodb", a dependency of "omnibus"
warning: cannot resolve "python2-nassl", a dependency of "sslyze"
warning: cannot resolve "sslyze", a dependency of "operative"
:: There are 2 providers available for netcat:
:: Repository extra
   1) gnu-netcat
:: Repository community
   2) openbsd-netcat

Enter a number (default=1): 
warning: cannot resolve "python-pyqt4", a dependency of "plasma"
warning: cannot resolve "python2-pyqt4", a dependency of "profuzz"
warning: cannot resolve "pyqt4-common", a dependency of "quickrecon"
warning: cannot resolve "wine", a dependency of "shellter"
warning: cannot resolve "ruby2.3", a dependency of "smbexec"
warning: cannot resolve "ruby2.3", a dependency of "ruby2.3-bundler"
warning: cannot resolve "ruby2.3-bundler", a dependency of "smbexec"
warning: cannot resolve "wine", a dependency of "smbrelay"
warning: cannot resolve "ruby2.3", a dependency of "arachni"
warning: cannot resolve "ruby2.3", a dependency of "ruby2.3-bundler"
warning: cannot resolve "ruby2.3-bundler", a dependency of "arachni"
warning: cannot resolve "arachni", a dependency of "sn1per"
warning: cannot resolve "python2-nassl", a dependency of "sslyze"
warning: cannot resolve "sslyze", a dependency of "sn1per"
warning: cannot resolve "ruby2.3", a dependency of "whatweb"
warning: cannot resolve "whatweb", a dependency of "sn1per"
warning: cannot resolve "john", a dependency of "snmp-brute"
warning: cannot resolve "libdaq-static", a dependency of "snort"
warning: cannot resolve "python2-pyqt4", a dependency of "sparta"
warning: cannot resolve "python2-nassl", a dependency of "sslyze"
warning: cannot resolve "ruby2.3", a dependency of "ssrf-proxy"
warning: cannot resolve "ruby2.3", a dependency of "ruby2.3-bundler"
warning: cannot resolve "ruby2.3-bundler", a dependency of "ssrf-proxy"
warning: cannot resolve "ruby2.3", a dependency of "twofi"
warning: cannot resolve "python2-pyside", a dependency of "ubertooth"
warning: cannot resolve "python2-pyqt4", a dependency of "ubertooth"
warning: cannot resolve "python2-pyqt4", a dependency of "ufo-wardriving"
warning: cannot resolve "pocketsphinx", a dependency of "python-speechrecognition"
warning: cannot resolve "python-speechrecognition", a dependency of "uncaptcha2"
warning: cannot resolve "swftools", a dependency of "vais"
warning: cannot resolve "python2-pyqt4", a dependency of "vivisect"
warning: cannot resolve "pyqt4-common", a dependency of "vivisect"
warning: cannot resolve "vlan", a dependency of "vlan-hopping"
warning: cannot resolve "ruby1.8-sqlite3", a dependency of "wafp"
warning: cannot resolve "python2-pyqt4", a dependency of "webslayer"
warning: cannot resolve "python2-pyqt", a dependency of "ghost-py"
warning: cannot resolve "ghost-py", a dependency of "webxploiter"
warning: cannot resolve "python2-pysqlite-legacy", a dependency of "wfuzz"
warning: cannot resolve "ruby2.3", a dependency of "whatweb"
warning: cannot resolve "python2-pyqt4", a dependency of "wifi-pumpkin"
warning: cannot resolve "ruby1.8-sqlite3", a dependency of "zackattack"
:: The following packages cannot be upgraded due to unresolvable dependencies:
      androbugs  angr-management  arachni  arpstraw  astra  autopwn  avet  backdoorppt  binaryninja-python  birp  bluediving  cewl  chopshop  cisco-snmp-enumeration  crackserver  creepy  dradis  dradis-ce
      eyewitness  fern-wifi-cracker  flowinspect  gerix-wifi-cracker  ghost-phisher  ghost-py  hexorbase  hidattack  hoper  id-entify  inguma  insanity  ipba2  iptv  johnny  joomlavs  lhf  malcom  manticore
      nosqlattack  nsia  obevilion  obexstress  omnibus  operative  plasma  profuzz  quickrecon  shellter  smbexec  smbrelay  sn1per  snmp-brute  snort  sparta  sslyze  ssrf-proxy  twofi  ubertooth
      ufo-wardriving  uncaptcha2  vais  vivisect  vlan-hopping  wafp  webslayer  webxploiter  wfuzz  whatweb  wifi-pumpkin  zackattack

:: Do you want to skip the above packages for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'python2-pyside' required by androbugs
:: unable to satisfy dependency 'python-pyside' required by angr-management
:: unable to satisfy dependency 'ruby2.3' required by arachni
:: unable to satisfy dependency 'ruby2.3' required by ruby2.3-bundler
:: unable to satisfy dependency 'ruby2.3-bundler' required by arachni
:: unable to satisfy dependency 'pypy' required by python2-pyshark
:: unable to satisfy dependency 'python2-pyshark' required by arpstraw
:: unable to satisfy dependency 'mongodb' required by astra
:: unable to satisfy dependency 'ruby2.3' required by arachni
:: unable to satisfy dependency 'ruby2.3' required by ruby2.3-bundler
:: unable to satisfy dependency 'ruby2.3-bundler' required by arachni
:: unable to satisfy dependency 'arachni' required by autopwn
:: unable to satisfy dependency 'python2-nassl' required by sslyze
:: unable to satisfy dependency 'sslyze' required by autopwn
:: unable to satisfy dependency 'wine' required by avet
:: unable to satisfy dependency 'wine-mono' required by avet
:: unable to satisfy dependency 'wine_gecko' required by avet
:: unable to satisfy dependency 'wine' required by backdoorppt
:: unable to satisfy dependency 'python2-pyside' required by binaryninja-python
:: unable to satisfy dependency 'x3270' required by birp
:: unable to satisfy dependency 'obexftp' required by bluediving
:: unable to satisfy dependency 'openobex' required by bluediving
:: unable to satisfy dependency 'ruby2.3' required by cewl
:: unable to satisfy dependency 'python2-pylibemu' required by chopshop
:: unable to satisfy dependency 'john' required by cisco-snmp-enumeration
:: unable to satisfy dependency 'john' required by crackserver
:: unable to satisfy dependency 'python2-pyqt4' required by creepy
:: unable to satisfy dependency 'ruby2.3' required by dradis
:: unable to satisfy dependency 'ruby2.3' required by ruby2.3-bundler
:: unable to satisfy dependency 'ruby2.3-bundler' required by dradis
:: unable to satisfy dependency 'ruby2.3' required by dradis-ce
:: unable to satisfy dependency 'ruby2.3' required by ruby2.3-bundler
:: unable to satisfy dependency 'ruby2.3-bundler' required by dradis-ce
:: unable to satisfy dependency 'python2-pyqt4' required by eyewitness
:: unable to satisfy dependency 'python2-pyqt' required by ghost-py
:: unable to satisfy dependency 'ghost-py' required by eyewitness
:: unable to satisfy dependency 'python2-pyqt4' required by fern-wifi-cracker
:: unable to satisfy dependency 'python2-pylibemu' required by flowinspect
:: unable to satisfy dependency 'pyqt3' required by gerix-wifi-cracker
:: unable to satisfy dependency 'python2-pyqt4' required by ghost-phisher
:: unable to satisfy dependency 'python2-pyqt' required by ghost-py
:: unable to satisfy dependency 'python2-pyqt4' required by hexorbase
:: unable to satisfy dependency 'python2-qscintilla' required by hexorbase
:: unable to satisfy dependency 'openobex' required by hidattack
:: unable to satisfy dependency 'ruby2.3' required by hoper
:: unable to satisfy dependency 'ruby2.3' required by whatweb
:: unable to satisfy dependency 'whatweb' required by id-entify
:: unable to satisfy dependency 'python2-pyqt' required by inguma
:: unable to satisfy dependency 'wine' required by insanity
:: unable to satisfy dependency 'python2-pyside' required by ipba2
:: unable to satisfy dependency 'python2-pyqt4' required by iptv
:: unable to satisfy dependency 'john' required by johnny
:: unable to satisfy dependency 'ruby2.3' required by joomlavs
:: unable to satisfy dependency 'ruby2.3' required by ruby2.3-bundler
:: unable to satisfy dependency 'ruby2.3-bundler' required by joomlavs
:: unable to satisfy dependency 'ruby2.3' required by arachni
:: unable to satisfy dependency 'ruby2.3' required by ruby2.3-bundler
:: unable to satisfy dependency 'ruby2.3-bundler' required by arachni
:: unable to satisfy dependency 'arachni' required by lhf
:: unable to satisfy dependency 'mongodb' required by malcom
:: unable to satisfy dependency 'python2-pyside' required by binaryninja-python
:: unable to satisfy dependency 'binaryninja-python' required by manticore
:: unable to satisfy dependency 'solidity' required by manticore
:: unable to satisfy dependency 'mongodb' required by nosqlattack
:: unable to satisfy dependency 'libstdc++5' required by nsia
:: unable to satisfy dependency 'python2-pyqt4' required by obevilion
:: unable to satisfy dependency 'openobex' required by lightblue
:: unable to satisfy dependency 'lightblue' required by obexstress
:: unable to satisfy dependency 'mongodb' required by omnibus
:: unable to satisfy dependency 'python2-nassl' required by sslyze
:: unable to satisfy dependency 'sslyze' required by operative
:: unable to satisfy dependency 'python-pyqt4' required by plasma
:: unable to satisfy dependency 'python2-pyqt4' required by profuzz
:: unable to satisfy dependency 'pyqt4-common' required by quickrecon
:: unable to satisfy dependency 'wine' required by shellter
:: unable to satisfy dependency 'ruby2.3' required by smbexec
:: unable to satisfy dependency 'ruby2.3' required by ruby2.3-bundler
:: unable to satisfy dependency 'ruby2.3-bundler' required by smbexec
:: unable to satisfy dependency 'wine' required by smbrelay
:: unable to satisfy dependency 'ruby2.3' required by arachni
:: unable to satisfy dependency 'ruby2.3' required by ruby2.3-bundler
:: unable to satisfy dependency 'ruby2.3-bundler' required by arachni
:: unable to satisfy dependency 'arachni' required by sn1per
:: unable to satisfy dependency 'python2-nassl' required by sslyze
:: unable to satisfy dependency 'sslyze' required by sn1per
:: unable to satisfy dependency 'ruby2.3' required by whatweb
:: unable to satisfy dependency 'whatweb' required by sn1per
:: unable to satisfy dependency 'john' required by snmp-brute
:: unable to satisfy dependency 'libdaq-static' required by snort
:: unable to satisfy dependency 'python2-pyqt4' required by sparta
:: unable to satisfy dependency 'python2-nassl' required by sslyze
:: unable to satisfy dependency 'ruby2.3' required by ssrf-proxy
:: unable to satisfy dependency 'ruby2.3' required by ruby2.3-bundler
:: unable to satisfy dependency 'ruby2.3-bundler' required by ssrf-proxy
:: unable to satisfy dependency 'ruby2.3' required by twofi
:: unable to satisfy dependency 'python2-pyside' required by ubertooth
:: unable to satisfy dependency 'python2-pyqt4' required by ubertooth
:: unable to satisfy dependency 'python2-pyqt4' required by ufo-wardriving
:: unable to satisfy dependency 'pocketsphinx' required by python-speechrecognition
:: unable to satisfy dependency 'python-speechrecognition' required by uncaptcha2
:: unable to satisfy dependency 'swftools' required by vais
:: unable to satisfy dependency 'python2-pyqt4' required by vivisect
:: unable to satisfy dependency 'pyqt4-common' required by vivisect
:: unable to satisfy dependency 'vlan' required by vlan-hopping
:: unable to satisfy dependency 'ruby1.8-sqlite3' required by wafp
:: unable to satisfy dependency 'python2-pyqt4' required by webslayer
:: unable to satisfy dependency 'python2-pyqt' required by ghost-py
:: unable to satisfy dependency 'ghost-py' required by webxploiter
:: unable to satisfy dependency 'python2-pysqlite-legacy' required by wfuzz
:: unable to satisfy dependency 'ruby2.3' required by whatweb
:: unable to satisfy dependency 'python2-pyqt4' required by wifi-pumpkin
:: unable to satisfy dependency 'ruby1.8-sqlite3' required by zackattack
`

**Comment by Edu4rdSHL** [comment]
Hello, please use: `pacman -Syyu --overwrite='*' blackarch`, doing `pacman -S blackarch` can fails because repos aren't synced and it also can do partial upgrades that aren't supported by BlackArch. Let me know if your issue is fixed running `pacman -Syyu --overwrite='*' blackarch`.

**Comment by pnylon** [comment]
Hello, thanks for the suggestion. I tried running the pacman command like that but it looks like it's doing the same thing. The output is the same as before. When it gets to this point `Do you want to skip the above packages for this upgrade? [y/N]` I always enter the default. I wanted to try a full install and not skip all those packages. I'm not sure what would happen yet if I enter y. I'm wondering if I should start over and install Arch Linux again. There were a few odd hangs when booting after the first boot.

**Comment by pnylon** [comment]
Hello, I tried again with a fresh arch linux and got the same thing happening. Also, after running `sudo ./strap.sh` I saw this: `ERROR: The keyring file /usr/share/pacman/keyrings/archlinux.gpg does not exist`. Not sure what that means. I did finish the arch linux installation and I installed a few small things before trying to install blackarch.

**Comment by ikstream** [comment]
There are several issues about that (e.g. BlackArch/blackarch#883). Please have a look at them, or try to follow the steps in ``` strap.sh ``` manually to resolve this

**Comment by pnylon** [comment]
I switched archlinuxarm back to archlinux on line 108 of strap.sh and I installed archlinux-keyring with `pacman -S archlinux-keyring`. Then I could run `sudo ./strap.sh` without the same error I was seeing above. I ran sudo pacman -Syu after ./strap.sh was finished, rebooted and now I'm back to where I was again at the start. Still can't install because of dependencies. I still haven't looked at some of the things in #883, but I'll try to check in there soon.

**Comment by ikstream** [comment]
The are related to the signature problems. I will try to look at your problem later this week. 
On the first view, the missing packages are from the blackarch repo. Could you please run ```pacman -Sg | grep blackarch```? Do you get any blackarch groups? If not, please run ```sudo pacman -Syy``` and try again

**Comment by pnylon** [comment]
Since Feb whenever I had a chance I kept updating arch, trying to install blackarch after each update, and seeing if I could find any solutions. I haven't found anything yet and I'm still seeing the same thing happening.

**Comment by ctoyan** [comment]
I also just tried doing it and got the same errors.

**Comment by noptrix** [comment]
we don't support armv7l anymore. only aarch64

**Comment by jskda** [comment]
Got the same error when upgrading from arch to blackarch. Everything was solved by adding a multilib packages to pacman.

Uncomment in /etc/pacman.conf:

```
#[multilib]
#Include = /etc/pacman.d/mirrorlist
```

then `sudo pacman -Sy` and try again `sudo pacman -S blackarch`

**Comment by ikstream** [comment]
Please don't try to install all tools at once. If you really want to slap on all tools on the poor raspberry pi, do it group wise. 
Installing all at once is asking for trouble.

Locking, as this is a really old topic.
