### ISSUE TITLE
need help with installing cmd

### ISSUE THREAD

**Issue by iNeedHelp125** [BlackArch/blackarch#2211]
i was looking how to install it on
https://blackarch.org/blackarch-install.html
but its a old one and idk how to install it there. if someone knows reply plz
i am using v1.0.3
edit: trna do full screen but its still not full screen http://prntscr.com/merpd5

**Comment by ikstream** [comment]
Do you have a concrete question?

**Comment by Edu4rdSHL** [comment]
Please follow https://blackarch.org/guide.html
