### ISSUE TITLE
fatrat error

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2215]
[x]::[warning]:this script require aapt to work

 [!]::Run setup.sh to install aapt

**Comment by DeadNumbers** [comment]
`ln -s /opt/android-sdk/build-tools/28.0.3/aapt /usr/bin/aapt`

**Comment by DeadNumbers** [comment]
`ln -s /opt/android-sdk/build-tools/28.0.3/aapt /usr/bin/aapt`

**Comment by Edu4rdSHL** [comment]
Please, describe the steps to reproduce it because it isn't reproducible actually.

**Comment by mrsmith0x00** [comment]
@GasparVardanyan fixed!
