### ISSUE TITLE
blackarch-installer failed to retrieve package

### ISSUE THREAD

**Issue by Syrkadian** [BlackArch/blackarch#2218]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
blackarch-installer failed to retrieve package

### Steps to reproduce
- Load ova into vmware
- run  systemctl start dhcpcd@ens32.service
- run sudo pacman -S blackarch-installer

**Actual result:** blackarch.org returned a 404. 
**Expected result:** package retrieval and install

### Screenshots
![blackarch-installer-error](https://user-images.githubusercontent.com/39872088/52259308-22e4a400-28d7-11e9-85ae-6889f47342d8.JPG)

### Info for developers

**Device:** NA
**GNU/Linux distribution:** Black Arch most recent from blackarch.org
**Tool version:** 0.0.0

### Link to debug log
Please see screenshot

**Comment by ikstream** [comment]
Please run  ``` pacman -Sy ```  before you try to install blackarch-installer. Current version ist 1.0.13
