### ISSUE TITLE
[Tool request] add CMSScan

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2244]
- [x] I have searched open and closed issues for duplicates

https://github.com/ajinabraham/CMSScan

**Comment by pwnfoo** [comment]
@noraj Made it easier to package the tool with a [PR to cmsscan.](https://github.com/ajinabraham/CMSScan/pull/26) Just need to sed replace the flag now :)

**Comment by noraj** [comment]
I'm preparing a draft but cmsscan lacks of a package for the dependency https://pypi.org/project/Flask-BasicAuth/ and also a setup.py file.
