### ISSUE TITLE
enum4linux: multiple bugs

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2248]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

### Bug description

```
$ enum4linux -u xxx -p xxx -S x.x.x.x
WARNING: polenum.py is not in your path.  Check that package is installed and your PATH is sane.
WARNING: ldapsearch is not in your path.  Check that package is installed and your PATH is sane.
...
 ===================================================== 
|    Enumerating Workgroup/Domain on 10.X.X.X    |
 ===================================================== 
Can't load /etc/samba/smb.conf - run testparm to debug it
[E] Can't find workgroup/domain

 ====================================== 
|    Session Check on 10.X.X.X    |
 ====================================== 
Use of uninitialized value $global_workgroup in concatenation (.) or string at /bin/enum4linux line 437.
[E] Server doesn't allow session using username 'xxx', password 'xxx'.  Aborting remainder of tests.
```

1. The script is looking for `polenum.py` but `polenum` is in the PATH
```
 $ which polenum
/bin/polenum
```
2. `ldapsearch` is part of `openldap`: missing dep
3. `/etc/samba/smb.conf` doesn't exist by default. see https://wiki.archlinux.org/index.php/Samba, so a post-install step with an echo is needed to warn the user
4.`/bin/enum4linux`: no clue

After creating `/etc/samba/smb.conf`, an another error occurred:

```
mkdir failed on directory /var/cache/samba/msg.lock: Permission denied
```

**Comment by aaaguirrep** [comment]
Hi, I have the next warning about polenum, did you fix it?
