### ISSUE TITLE
[Tool Installation Fail - blackman] MDK4

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2250]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
Hi there, we cannot install MDK4, there's a failure during the prepare() phase.
Also one of the required deps should cover more than just a single version of linux-headers if possible (for example linux-hardened-headers)

### Steps to reproduce
- blackman -i mdk4

**Actual result:**
```
==> Starting prepare()...
patching file Makefile
Hunk #1 FAILED at 1.
Hunk #2 FAILED at 9.
2 out of 2 hunks FAILED -- saving rejects to file Makefile.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
[!] WARNING: Something wrong with makepkg: mdk4
loading packages...
error: '*.xz': could not find or read package
```
Package fails to build during the prepare() phase

**Expected result:**
The package should prepare() correctly and be installed after.

### Info for developers

**Device:** Laptop
**GNU/Linux distribution:** Arch Linux 4.20.10.a-1-hardened
**Tool version:** blackman v0.5.13

### Link to debug log

```
==> Starting prepare()...
patching file Makefile
Hunk #1 FAILED at 1.
Hunk #2 FAILED at 9.
2 out of 2 hunks FAILED -- saving rejects to file Makefile.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
[!] WARNING: Something wrong with makepkg: mdk4
loading packages...
error: '*.xz': could not find or read package
```

**Comment by Edu4rdSHL** [comment]
Since that blackman is deprecated and need to be rewritten, issues related to blackman have not place for the moment, please install packages using pacman.
