### ISSUE TITLE
[Tool installation error] droopescan

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2255]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
Hi there, we cannot install or update droopescan cause the PKGBUILD of python-cement is failing at line 18

### Steps to reproduce
- pacman -S droopescan

**Actual result:** Installation fails when installing python-cement
**Expected result:** A working installation of the python-cement package

### Link to debug log

```
==> Validating source files with sha512sums...
    cement-3.0.2.tar.gz ... Passed
==> Extracting sources...
  -> Extracting cement-3.0.2.tar.gz with bsdtar
==> Starting build()...
/tmp/python-cement/PKGBUILD: line 18: cd: cement-2.10.12: No such file or directory
==> ERROR: A failure occurred in build().
    Aborting...
[!] WARNING: Something wrong with makepkg: python-cement
loading packages...
error: '*.xz': could not find or read package
```

**Comment by noptrix** [comment]
huh? @s7x how did you try to install it? via blackman? cause here it's working both with pacman and makepkg

**Comment by s7x** [comment]
@noptrix My bad I just installed the BlackArch repos on top of my Arch and rerun the install, it works now. Thanks ;)
