### ISSUE TITLE
[Tool request] cve-search

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2259]
cve-search: https://github.com/cve-search/cve-search

Here are the dependencies to add:

```
(python-feedformater)
(python-flask-pymongo)
(python-sleekxmpp)
mongodb
python
python-click
python-dateutil
python-flask
python-flask-login
python-irc
python-itsdangerous
python-jinja
python-lxml
python-passlib
python-pymongo
python-pytz
python-redis
python-requests
python-six
python-tornado
python-werkzeug
python-whoosh
python-xlrd
redis
requirements-parser
```

Between parenthesis the dependencies that don't have an existing package right now. So what is the procedure? Creating a PKGBUILD for each one or installing them via pip?

**Comment by Edu4rdSHL** [comment]
Hello, the procedure is to add the missing packages (and their dependencies) using PKGBUILDs.

**Comment by Edu4rdSHL** [comment]
Fixed via https://github.com/BlackArch/blackarch/commit/fba6c3ab339693365098a72791bac69a9cf0baac

**Comment by noraj** [comment]
Thanks @Edu4rdSHL !
