### ISSUE TITLE
[TOOL REQUEST]   GhostNET v2

### ISSUE THREAD

**Issue by Baitinq** [BlackArch/blackarch#2280]
I come to bring a new tool today that could be very beneficial for the blackarch community.

[GhostNET v2 ¦ https://github.com/Baitinq/GhostNET-v2]
- GhostNET is a simple python program to direct all traffic of the system through tor, to gain total anonymity. 

+ Usage
- "sudo ghostnet start/stop/status"

+ Features
- mac spoofing 
- tor rerouting
- cache cleaning

+Dependencies
- macchanger
- python3
- bleachbit
- openresolv
- networkmanager
- tor

*IMPORTANT
- This tool is not packaged as I am not familiar with arch package system

+ Author
- This program was made primarily by t7hm1 (https://github.com/t7hm1) with some contributions and fixes by baitinq (https://github.com/baitinq).

**Comment by mrsmith0x00** [comment]
@Baitinq sorry, but this isn't a penetration testing tool :(
But we have [torctl](https://github.com/BlackArch/torctl) - script for redirect all traffic through tor network.
