### ISSUE TITLE
BlackArch Linux will not Install

### ISSUE THREAD

**Issue by ArcticStagMedia** [BlackArch/blackarch#2281]
Hi There,

I am trying to install BlackArch Linux on a Virtual Machine on Mac. I get most of the way through the beginner tutorial on the web and every time I try to install I get an error that says Blackarch Linux requires 40GB of free space to install, I have tried to up the virtual HDD each time to give more and more space however the install always fails the same way. Running on a MacBook 2017 1.3 GHz 8GB Memory, 128GB SSD.

here is a copy of my most recent install log

[GLaDOS BlackArch-2019-03-19-09-28-54.log](https://github.com/BlackArch/blackarch/files/2980725/GLaDOS.BlackArch-2019-03-19-09-28-54.log)

**Comment by mrsmith0x00** [comment]
@ArcticStagMedia hello! First of all, if you had been created partitions before you increased free space to BlackArch Linux, you might have old small partitions. `root` partition should be more than 40G (keep in mind that filesystems also have their own journals). I recommended you to re-create VM and do fresh installation.

**Comment by ArcticStagMedia** [comment]
Great, All resolved
