### ISSUE TITLE
[Tool Request] Archivebox

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2285]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Info for developers

Hello there!
A new tool surfaced a few days ago and has been referenced in the [Pentester.land Hacking Newsletter N°45](https://pentester.land/newsletter/2019/03/19/the-5-hacking-newsletter-45.html#Misc.%20pentest%20&%20bug%20bounty%20resources). ArchiveBox is an open-source self-hosted web archive. Useful for archiving interesting writeups, tutorials, etc, in case they’re taken offline (happens a lot!)

[LINK TO THE WEBSITE](https://archivebox.io/)
[REPO LINK](https://github.com/pirate/ArchiveBox/)

### Description taken from the website:

_ArchiveBox takes a list of website URLs you want to archive, and creates a local, static, browsable HTML clone of the content from those websites (it saves HTML, JS, media files, PDFs, images and more)._

_You can use it to preserve access to websites you care about by storing them locally offline. ArchiveBox imports lists of URLs, renders the pages in a headless, autheticated, user-scriptable browser, and then archives the content in multiple redundant common formats (HTML, PDF, PNG, WARC) that will last long after the originals disappear off the internet. It automatically extracts assets and media from pages and saves them in easily-accessible folders, with out-of-the-box support for extracting git repositories, audio, video, subtitles, images, PDFs, and more._

Thought it could be an awesome addition to the BlackArchsenal. Not strictly hacking related but Blackarch misses a great archiving tool and this one is top notch.

Cheers!

**Comment by Edu4rdSHL** [comment]
Closed via https://github.com/BlackArch/blackarch/commit/17ffe58b0453f25dc00c0ddf54058af6e6ac3acc

**Comment by s7x** [comment]
You guys are awesome! Thanks a lot!
