### ISSUE TITLE
[Tool Request] tools from Archstrike

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2295]
Archstrike tools that BlackArch does not contain:

airgraph-ng-svn, amap, arachni-scanner, argtable, auto-xor-decryptographyr, autobrowser, automator, bamfdetect, blindelephant-svn, bt2, buildhosts, burst, callerpy, cjdns, cjdnsify, cjdscript, cookiejar, cpublaster, creds.py, cryptcat, cryptmount, cryptohazemultiforcer, csrft, ddrutility, delta, derrick, detectsniffer, eh, fatback, firesql, fragroute, funkload, g711conversions, g72x, ghost.py, ghostpdl, ghostpop3, goatrider, gpshell, gwt-toolset, hack_library, hash-identifier, heartbleed, hellcat, i2pd, ikeforce, interlock, jigsaw, jsql, karma-hostapd, knockd, kwprocessor, libestr, loki, magic-unicorn, mbox, meltdown, metasploit-payload-creator, metasploitavevasion, mfterm, mimikittenz, morbid, mt-st, nassl, ncp, nightfall, novnc, od1n, orbited, pacemaker, perl-tftp, powershell-payload-excel-delivery, powerupsql, prometheus, psychopath, pwatch, python-tld, python-yaswfp, python2-amoco, python2-bowcaster, python2-idstools, python2-miasm, python2-owasp-pysec, python2-pysqli, python2-uefi-firmware-parser, python2-utidylib, python2-vulndb, pytinydns, quicksand_lite, salsapipe, sec, seclists, shellsploit, simple-email-spoofer, slowloris6, snarf, squashfuse, ssdc, ssss, sstat, stickykeyshunter, stomper, thezoo, tnscmd10g, tomb, triad-decompiler, twittor, usbkill, vmcloak, watchman, wemo, windows-binaries, xmount, xorstrings.

https://archstrike.org/packages

**Comment by Edu4rdSHL** [comment]
Hello, please can you order that list? It's a bunch of non-sense order packages. Also there are libraries, etc. Try to order it.

**Comment by GasparVardanyan** [comment]
I filtered the archstrike tools using the blackarch tools using the browser console.

airgraph-ng-svn
amap
arachni-scanner
argtable
auto-xor-decryptographyr
autobrowser
automator
bamfdetect
blindelephant-svn
bt2
buildhosts
burst
callerpy
cjdns
cjdnsify
cjdscript
cookiejar
cpublaster
creds.py
cryptcat
cryptmount
cryptohazemultiforcer
csrft
ddrutility
delta
derrick
detectsniffer
eh
fatback
firesql
fragroute
funkload
g711conversions
g72x
ghost.py
ghostpdl
ghostpop3
goatrider
gpshell
gwt-toolset
hack_library
hash-identifier
heartbleed
hellcat
i2pd
ikeforce
interlock
jigsaw
jsql
karma-hostapd
knockd
kwprocessor
libestr
loki
magic-unicorn
mbox
meltdown
metasploit-payload-creator
metasploitavevasion
mfterm
mimikittenz
morbid
mt-st
nassl
ncp
nightfall
novnc
od1n
orbited
pacemaker
perl-tftp
powershell-payload-excel-delivery
powerupsql
prometheus
psychopath
pwatch
python-tld
python-yaswfp
python2-amoco
python2-bowcaster
python2-idstools
python2-miasm
python2-owasp-pysec
python2-pysqli
python2-uefi-firmware-parser
python2-utidylib
python2-vulndb
pytinydns
quicksand_lite
salsapipe
sec
seclists
shellsploit
simple-email-spoofer
slowloris6
snarf
squashfuse
ssdc
ssss
sstat
stickykeyshunter
stomper
thezoo
tnscmd10g
tomb
triad-decompiler
twittor
usbkill
vmcloak
watchman
wemo
windows-binaries
xmount
xorstrings

**Comment by ikstream** [comment]
Could you please double check your list? While some of the tools are not in blackarch, others are either already in archlinux or in blackarch

**Comment by GasparVardanyan** [comment]
I filtered using tool names: https://i.imgur.com/JR2Vnqc.png

**Comment by Edu4rdSHL** [comment]
Hello @GasparVardanyan. Most of the tools are renamed and/or are in ArchLinux, also some of the tools are not in 'blackarch' group tools that's why you're getting the difference and other tools aren't relevants to include.

Closing the issue.
