### ISSUE TITLE
[Tool Request] Webanalyze

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2311]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Info for developers
Hi there, a very cool tool jumped on a certain newsletter: Webanalyze.
It's a kind of port of Wappalyzer, written in Go, very useful for web application recon/fingerprint.
It can be integrated into your Go project too! It would be a great addition to the BlackArchsenal.

**Description (from the repo):**

*This is a port of Wappalyzer in Go. This tool is designed to be performant and allows to test huge lists of hosts.*

[Link to the Repo](https://github.com/rverton/webanalyze)

**Comment by noptrix** [comment]
thanks @s7x!

**Comment by s7x** [comment]
Thx to you guys! Tried to create it myself but first time for Go type package so it was full of errors.
Cheers!
