### ISSUE TITLE
[Tool Version Bump] Amass

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2314]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Info for developers
Hi there, Amass is actually at version 2.9.9 but it misses the amass.tracker tool/functionality.
It is used to track changes between 2 time-separate projects.
(If we look at the PKGBUILD from the AUR we can see the missing package/functionality)

```
<   install -Dm 755 "$pkgname" "$pkgdir/usr/bin/$pkgname"
<   install -Dm 755 "$pkgname.netdomains" "$pkgdir/usr/bin/$pkgname.netdomains"
<   install -Dm 755 "$pkgname.viz" "$pkgdir/usr/bin/$pkgname.viz"
<   install -Dm 755 "$pkgname.db" "$pkgdir/usr/bin/$pkgname.db"
---
>   install -Dm755 "${pkgname}" "${pkgdir}/usr/bin/${pkgname}"
>   install -Dm755 "${pkgname}.netdomains" "${pkgdir}/usr/bin/${pkgname}.netdomains"
>   install -Dm755 "${pkgname}.tracker" "${pkgdir}/usr/bin/${pkgname}.tracker"
>   install -Dm755 "${pkgname}.viz" "${pkgdir}/usr/bin/${pkgname}.viz"
>   install -Dm755 "${pkgname}.db" "${pkgdir}/usr/bin/${pkgname}.db"
```

Cheers!

**Comment by noptrix** [comment]
@s7x thanks a lot :)

**Comment by s7x** [comment]
@noptrix thanks to you!
