### ISSUE TITLE
[Tool Update] killcast

### ISSUE THREAD

**Issue by thewhiteh4t** [BlackArch/blackarch#2315]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

### Info for developers

**Tool version in my repo :** 1.0.2
**Tool version in BlackArch rep :** 1.0.1

https://github.com/thewhiteh4t/killcast
Tools are updated manually ? if yes then please update

**Comment by noptrix** [comment]
already updated as we discussed on discord ;)
