### ISSUE TITLE
[Tool Request] pwnedOrNot

### ISSUE THREAD

**Issue by s7x** [BlackArch/blackarch#2318]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Info for developers

Hi there!
A very cool little tool to help you find usernames/passwords/emails combos in haveIbennpwned and pastebin. Lightweight and simple to use.

**Description** (from git repo):

*pwnedOrNot uses haveibeenpwned v2 api to test email accounts and tries to find the password in Pastebin Dumps.*

[REPO LINK](https://github.com/thewhiteh4t/pwnedOrNot)

Cheers!

**Comment by mrsmith0x00** [comment]
@s7x added!

**Comment by s7x** [comment]
@mrsmith0x00 Fantastic!

**Comment by thewhiteh4t** [comment]
Thankyou !! @s7x @mrsmith0x00

**Comment by s7x** [comment]
@thewhiteh4t Thanks to you!
