### ISSUE TITLE
Blackarch Website & ISO version

### ISSUE THREAD

**Issue by Franchium** [BlackArch/blackarch#2324]
1. Why did blackarch have two website blackarch.org and blackarch.io ? I heard that blackarch.io is the new one, but why the another one is still exist ?

2. Is there any information for new release of blackarch ISO ?

**Comment by noptrix** [comment]
@Franchium 1) no, blackarch.io is not our new website. it's an inofficially site which we wanted to adopt but due to some contact-loss to the dev we stopped working on it. 2) 1st of june new ISO releases

**Comment by SampsonCrowley** [comment]
@noptrix is there a reason blackarch.org is still pointed at a valid host, but the server refuses to connect? it responds to ICMP but not http or https
