### ISSUE TITLE
[Package Update Needed] CANalyzat0r

### ISSUE THREAD

**Issue by sw-pschmied** [BlackArch/blackarch#2330]
Hello and thanks for including [CANalyzat0r](https://github.com/schutzwerk/CANalyzat0r) in blackarch. We've just fixed a bug that corrupted the GUI when running in blackarch so an update is required at the moment.

By chance, you can update the package `canalyzat0r` in blackarch to the latest version from GitHub now.

Cheers

**Comment by mrsmith0x00** [comment]
@sw-pschmied updated! :)
