### ISSUE TITLE
creddump: multiple problems

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2332]
Reference PKGBUILD: https://github.com/BlackArch/blackarch/blob/master/packages/lfimap/PKGBUILD

1. The source `https://code.google.com/p/creddump/` is dead
2. Automatic export `https://github.com/moyix/creddump` has no release
3. The way it is packaged right now is bugged, it will lead to the following error, because `install -Dm 755 -t "$pkgdir/usr/share/windows/$pkgname" cachedump.py lsadump.py pwdump.py` is used and the `framework` lib folder is not copied.
```
Traceback (most recent call last):
  File "/usr/share/windows/creddump/pwdump.py", line 25, in <module>
    from framework.win32.hashdump import dump_file_hashes
ImportError: No module named framework.win32.hashdump
```
4. Scripts are copied into `/usr/share/windows/$pkgname` so there is not tool available in the PATH.
5. The original 0.3 package requires `python-crypto` (aka pycrypto) that is not satisfied and need to be moved to `pycryptodome` anyway.

So I forked `https://github.com/moyix/creddump` to `https://github.com/noraj/creddump`, made the `sed -i 's/env python/env python2/' *.py` change and created a 0.3 release. And made a better PKGBUILD based on that.

I'll link the PR.

**Comment by Edu4rdSHL** [comment]
Fixed via https://github.com/BlackArch/blackarch/commit/b85c0d1421a8cd018b72cbe47bff9c4222dd06ba

**Comment by noraj** [comment]
@Edu4rdSHL 

Why not doing 

`source=("$pkgname::git+$url.git")`

rather than

`source=("$pkgname::git+https://github.com/moyix/$pkgname.git")`

?

**Comment by Edu4rdSHL** [comment]
See the PKGBUILD-generic-git template in https://github.com/BlackArch/blackarch-pkgbuilds

**Comment by noraj** [comment]
@Edu4rdSHL Yes but why? For readability ?

**Comment by Edu4rdSHL** [comment]
Yeah, that's one of the most important things for us: make easy to understand for new users that want to contribute.

**Comment by noraj** [comment]
@Edu4rdSHL Good reason so ;)
