### ISSUE TITLE
mobsf: venv failure

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2335]
### Bug description

```
$ mobsf -h          
run.sh: line 5: venv/bin/activate: No such file or directory

$ which mobsf
/usr/bin/mobsf

$ head /usr/bin/mobsf
#!/bin/sh
cd /usr/share/mobsf
exec bash run.sh

$ head -6 /usr/share/mobsf/run.sh 
#!/bin/bash
# Dev Server
#. venv/bin/activate && python manage.py runserver
# Prod Server
. venv/bin/activate && gunicorn -b 0.0.0.0:8000 MobSF.wsgi:application --workers=1 --timeout=1800
```

But there is no `venv` or `.venv` directory.

It may remember we changed something about virtualenv for this package.

### Steps to reproduce

- Install
- Launch

### Info for developers

**GNU/Linux distribution:** ArchLinux + BA repo
**Tool version:** blackarch/mobsf 1:866.a900c9d-1

**Comment by Edu4rdSHL** [comment]
We need that https://github.com/kennethreitz/requests/issues/5067 will be fixed first.

**Comment by sachinkamath** [comment]
@Edu4rdSHL That issue is now fixed

**Comment by Edu4rdSHL** [comment]
Thanks, we are closing it when the package got bumped.

**Comment by mrsmith0x00** [comment]
Successfully bumped :p
