### ISSUE TITLE
sippts: permissions / database / working directory

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2336]
### Bug description

```
$ sipscan
cp: cannot create regular file 'sippts.db': Permission denied
DBI connect('dbname=sippts.db','',...) failed: unable to open database file at sipscan.pl line 59.
unable to open database file at sipscan.pl line 59.
```

Troubleshooting:

```
$ which sipscan
/usr/bin/sipscan

$ head /usr/bin/sipscan
#!/bin/sh
cd /usr/share/sippts
exec perl sipscan.pl "${@}"

$ sed -n 59p /usr/share/sippts/sipscan.pl
my $db = DBI->connect("dbi:SQLite:dbname=$database","","") or die $DBI::errstr;

$ sed -n 47,48p /usr/share/sippts/sipscan.pl
my $database = "sippts.db";
my $database_empty = "sippts_empty.db";

$ sed -n 53,60p /usr/share/sippts/sipscan.pl
unless (-e $database || -e $database_empty) {
        die("Database $database not found\n\n");
}

system("cp $database_empty $database") if (! -e $database);

my $db = DBI->connect("dbi:SQLite:dbname=$database","","") or die $DBI::errstr;
my $hostsid = last_id();
```

The script has no permission to do `cp sippts_empty.db sippts.db` in the protected folder `/usr/share/sippts/`. 

But we can't do something has the following for `/usr/bin/sipscan` because the whole script is made to find the db in the working directory.

```
#!/bin/sh
exec perl /usr/share/sippts/sipscan.pl "${@}"
```

So with this kind of wrapper it ends with

```
$ sipscan
Database sippts.db not found
```

Even if using `-nodb` the script will still look for the db in the first place.

The only way (without making upstream changes or without using root privilegies) is to copy an empty db in the working directory `cp /usr/share/sippts/sippts_empty.db sippts.db`.

So it is rather unhandy. Have we another way or do we need to call for an upstream fix?

**Comment by noraj** [comment]
https://github.com/Pepelux/sippts

**Comment by Pepelux** [comment]
Hi Noraj

I've just update the scripts to create database file (and open connections) only if -db parameter is chosen. I don't know if there are other problems with permissions, for example when create TXT logs. On this case you can open another issue and I'll check it.

Commit. https://github.com/Pepelux/sippts/commit/128520e01f4bfc7ebfacbb5b1d55fa5280787a2c

**Comment by noraj** [comment]
You're very welcome, we'll try that.

**Comment by Edu4rdSHL** [comment]
Fixed via https://github.com/BlackArch/blackarch/commit/37e39a9044639345bf53031ee4e123ef1f94ca8a.

Thanks @noraj for reporting and thanks @Pepelux for fixing.
