### ISSUE TITLE
Cannot run vega

### ISSUE THREAD

**Issue by mikeybro** [BlackArch/blackarch#2344]
I have attached a log:
[1558473996059.log](https://github.com/BlackArch/blackarch/files/3205759/1558473996059.log)

**Comment by Edu4rdSHL** [comment]
We should consider removing it obsolete tool for some reasons:

* Upstream is not longer maintained.
* The tool is problematic as hell (following instructions of upstream doesn't work also).
* The techniques that it tool uses are obsoletes now and you probably get a lot of false-positives vulns.
* It doesn't work at all.

cc @noptrix @mrsmith0x00

**Comment by mrsmith0x00** [comment]
@Edu4rdSHL I support your opinion!

**Comment by mrsmith0x00** [comment]
@mikeybro deleted!
