### ISSUE TITLE
[Bug] reconnoitre - relative import

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2345]
### Bug description

```
$ reconnoitre -t 10.x.x.x -o 10.x.x.x --services
Traceback (most recent call last):
  File "reconnoitre.py", line 7, in <module>
    from lib.find_dns import find_dns
  File "/usr/share/reconnoitre/Reconnoitre/lib/find_dns.py", line 3, in <module>
    from file_helper import check_directory
ModuleNotFoundError: No module named 'file_helper'

$ cat /usr/bin/reconnoitre
#!/bin/sh
cd /usr/share/reconnoitre/Reconnoitre
exec python reconnoitre.py "$@"

$ tree /usr/share/reconnoitre/Reconnoitre
/usr/share/reconnoitre/Reconnoitre
├── __init__.py
├── lib
│   ├── config.json
│   ├── core
│   │   ├── __init__.py
│   │   ├── input.py
│   │   └── __version__.py
│   ├── file_helper.py
│   ├── find_dns.py
│   ├── hostname_scan.py
│   ├── __init__.py
│   ├── ping_sweeper.py
│   ├── service_scan.py
│   ├── snmp_walk.py
│   └── virtual_host_scanner.py
├── reconnoitre.py
└── wordlists
    └── virtual-host-scanning.txt
```

`lib/find_dns.py` is importing `lib/file_helper.py` like that `from file_helper import check_directory`.

## files

- PKGBUILD: https://github.com/BlackArch/blackarch/blob/master/packages/reconnoitre/PKGBUILD
- setup.py: https://github.com/codingo/Reconnoitre/blob/master/setup.py

**Comment by noraj** [comment]
The package is not respecting the template https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-python

I'm pretty sure that doing `python setup.py install` like said on the [README](https://github.com/codingo/Reconnoitre) will work.

**Comment by noraj** [comment]
The same happen with the template in a clean chroot environment: https://github.com/codingo/Reconnoitre/issues/87#issuecomment-495209515. It also happens to guys on Kali, so it may be upstream packaging problem.

**Comment by Edu4rdSHL** [comment]
Hi @noraj, thanks for the report. The package has been fixed but I'm not closing it because that's a upstream issue, I've made a PR for that, see https://github.com/codingo/Reconnoitre/pull/95
