### ISSUE TITLE
radare2-cutter error

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2362]
[gaspar@GasparVardanyan][~]
╼ $ Cutter 
Plugins are loaded from "/home/gaspar/.local/share/RadareOrg/Cutter/plugins"
Loaded 0 plugin(s).
Warning: r_bin_file_hash: file exceeds bin.hashlimit
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] find and analyze function preludes (aap)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Use -AA or aaaa to perform additional experimental analysis.
Cutter: ../src/widgets/GraphGridLayout.cpp:237: virtual void GraphGridLayout::CalculateLayout(std::unordered_map<long long unsigned int, GraphLayout::GraphBlock>&, long long unsigned int, int&, int&) const: Assertion `block.edges.size() == layoutState.edge[block.entry].size()' failed.
Aborted (core dumped)

**Comment by ikstream** [comment]
What version of radare2-cutter/radare2 are you using?

**Comment by GasparVardanyan** [comment]
radare2 3.5.1-1, radare2-cutter 1.8.2-1

**Comment by noptrix** [comment]
guys, radare2 and radare2-cutter are maintained by Arch community not by us.

**Comment by ikstream** [comment]
Haven't checked if we maintain radare2-cutter. But as we do not maintain it, i am closing this issue

**Comment by GasparVardanyan** [comment]
@noptrix please check: pacman -Si radare2 radare2-cutter
They both are included in blackarch, blackarch-reversing, blackarch-decompiler, blackarch-disassembler and blackarch-debugger groups.

**Comment by ikstream** [comment]
@GasparVardanyan they are in the repo, but are maintained by arch linux. They are in community.

**Comment by GasparVardanyan** [comment]
@ikstream Ok, thank you. I already have opened issue in radare's github page.
