### ISSUE TITLE
Warninrg: couldn't set locale.

### ISSUE THREAD

**Issue by AhmedAbdulmumin** [BlackArch/blackarch#2369]
Hey guys im New with BlackArch and i got couple serious problems with it i hope that u can help me..
1- whenever i Open up terminal it says "Warning: Couldn't set locale."
That was my First problem.

2-i cant connect to Internet or Not even opening/running "wicd-gtk"
When i write "wicd-gkt" on Terminal the message error says:
"Could not connect to wicd's D-bus interface.
Check  the wicd log for error message.
When i press ok again it says:
Error connecting to wicd service via D-bus.
"Please ensure the wicd service is running"
And when i want to remove /etc/resolv.conf it says persmission denied and i  ant Remove it with sudo too the Error message is:
Is not in the Sudoers file. This incident will be reported..
And my 3rd problem..

3-I cant have Access to files im using the Default desktop and its just the BlackArch image on the screen and the Right-click button has nothing at all to do with files or let me have access to it.
Please guys i'll be gratefull if u help

**Comment by ikstream** [comment]
Hi, how did you install Blackarch? Which terminal application shows this problem?

Is wicd service running? Is your user in the wheel group?

What desktop environment are you using?

**Comment by AhmedAbdulmumin** [comment]
> Hi, how did you install Blackarch? Which terminal application shows this problem?
> 
> Is wicd service running? Is your user in the wheel group?
> 
> What desktop environment are you using?

i downloaded from ISO file the offline download one/XTerm terminal says that
thx i fixed thewicd problem
im using the default one

**Comment by ikstream** [comment]
For the locale problem have you checked: https://bbs.archlinux.org/viewtopic.php?id=133507

**Comment by AhmedAbdulmumin** [comment]
> For the locale problem have you checked: https://bbs.archlinux.org/viewtopic.php?id=133507

dammit man i still cant fix it..

**Comment by Edu4rdSHL** [comment]
Hello, what do you have into `/etc/locale.gen` and `/etc/locale.conf` ?

**Comment by AhmedAbdulmumin** [comment]
> Hello, what do you have into `/etc/locale.gen` and `/etc/locale.conf` ?

idk man im totally new with linux and i really dont know how to do stuff unless all is wroten step by step

**Comment by Edu4rdSHL** [comment]
Then probably BlackArch is not for you. I will reopen it issue when you give the information needed.

**Comment by AhmedAbdulmumin** [comment]
> Then probably BlackArch is not for you. I will reopen it issue when you give the information needed.

Yeah, BlackArch for real is not for mee...
THx for the time guys.

**Comment by ikstream** [comment]
BlackArch is intended for users, who are familiar with the linux environment. If you want to use it further, have a look at the Arch Linux guides, as these will answer most of your questions. 
BlackArch basically adds to Arch some nice flavor.
Providing step by step guides for standard tasks is not in the scope of the repo.

**Comment by AhmedAbdulmumin** [comment]
Just a quick question...
Why when u download/Install a LinuxOS on a Laptop/PC...
First time u Download u get.. for example that wicd error and not locale...
next time on another laptop u exactly download same steps how u did on first.. this time it wont show that wicd error but that locale error?
why it doesnt get downloaded always as it has to be?

**Comment by ikstream** [comment]
In case of installation usually something failed unnoticed. In case of an live iso its probably just one error shown. 
As long as the checksum matches, it usually gets downloaded the same
