### ISSUE TITLE
[Tool request] dnSpy

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#2374]
https://github.com/0xd4d/dnSpy/

**Comment by vdun** [comment]
Thx very much noptrix :)
But can you extract it ?
I like having all the windows tools in ready to use/execute state (not zipped). As I always share the folder /usr/share/windows/xxx between Blackarch and my windows PC.

**Comment by noptrix** [comment]
> Thx very much noptrix :)
> But can you extract it ?
> I like having all the windows tools in ready to use/execute state (not zipped). As I always share the folder /usr/share/windows/xxx between Blackarch and my windows PC.

yup :) i wasn't sure if we should keep packaged or unpacked ... i will unpack all.
