### ISSUE TITLE
DB Error

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2388]
$ pacman -Sgg | grep blackarch
...
blackarch-unpacker mikrotik-npk
blackarch-mobileblackarch-reversing frida-ios-dump
blackarch-mobileblackarch-reversing frida-ipa-dump
blackarch-mobileblackarch-reversing objection
blackarch-radio gpredict
...

$ pacman -Si objection
Repository      : blackarch
Name            : objection
...
Groups          : blackarch  blackarch-mobileblackarch-reversing
                  blackarch-binary
...

**Comment by ikstream** [comment]
I told you before to open issues with relevant information included. As we provide an issue template and you didn't use it I am going to close this issue. 
Check the issue template, fill the relevant parts, especially the expected and acutall results.
and open a new issue, if you still think, that this is a defect.

BR
