### ISSUE TITLE
[New version] cppman

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2389]
cppman's build date in BlackArch is "Sun 06 Apr 2014 03:41:40 PM +04", but in AUR is "Sun 24 Apr 2016 01:49:19 PM +04".

**Comment by GasparVardanyan** [comment]
In BlackArch the cppman's version is 0.3.1, but in AUR: 0.5.0.

**Comment by noptrix** [comment]
i removed this package. thanks @GasparVardanyan
