### ISSUE TITLE
Stuck at "GRUB loading. Welcome to GRUB!" after i unecrypt the root partition in vmware

### ISSUE THREAD

**Issue by c0rnd0g** [BlackArch/blackarch#2404]
- [ ] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
I am brought to the GRUB boot menu and select BlackArch. I am then asked to enter the encryption password for my root partition. I am then brought to a screen that simply says:
GRUB loading.
Welcome to GRUB!
I cannot type and it is stuck here.

### Steps to reproduce
- Install latest BlackArch ISO image
-Create vmware virtual machine with settings:
*4GB of memory
*70GB hard disk single file
*Default settings for everything else
-Followed the ISO install tutorial on BlackArch website exactly
*Installed all window managers
*installed all packages
*setup encrypted root partition
-reboot and select BlackArch
-Enter encryption password for root

**Actual result** 
I get a black screen that says:
GRUB loading.
Welcome to GRUB!
I cannot type and it just stays there

**Expected result:** 
It boots in to BlackArch and asks for username and

### Screenshots

![Screenshot from 2019-07-11 18-49-27](https://user-images.githubusercontent.com/49825025/61092664-c7ca5680-a40c-11e9-900b-b11dbbf01ed7.png)

### Info for developers

**ISO version**
2019.06.01
**VMware version**
VMware Workstation 15 Player

### Link to debug log

[vmware.log](https://github.com/BlackArch/blackarch/files/3384373/vmware.log)
my vmware.log for this machine(not sure if this is helpful)

**Comment by mrsmith0x00** [comment]
@c0rnd0g hello!
Did you install vmware tools? Other VMs work?

**Comment by Edu4rdSHL** [comment]
No info was received, closing.
