### ISSUE TITLE
[Tool installation Fail] cewl

### ISSUE THREAD

**Issue by t0-git** [BlackArch/blackarch#2415]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

I try to install cewl and it doesn't work :
```

 (1/2) installing ruby2.3                          
Optional dependencies for ruby2.3
    tk: for Ruby/TK [installed]
(2/2) installing cewl                             
/tmp/alpm_oMcar1/.INSTALL: line 5: bundle-2.3: command not found
error: command failed to execute correctly  
```

I then install ruby2.3-bundler, and after that I install cewl successfully.

When I want to launch it :
```

 CeWL 5.4.5 (Exclusion) Robin Wood (robin@digi.ninja) (https://digi.ninja/)

Error: spider gem not installed
    Run 'bundle install' to install all the required gems

```

I try to install ruby-spider, but no result.
I also try to launch 'bundle install' but the result is :

` Could not locate Gemfile `

### Info for developers

Kernel : 5.1.16.a-1-hardened
Distro : Arch Linux
Cewl : 66.cf29509-2

**Comment by noptrix** [comment]
should be fixed now.
