### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by PanosTrak** [BlackArch/blackarch#2417]
### Sugestion
I think it would be nice if we had the ability to choose between red and green color.
And if there is a way to change the color can you tell me how?

**Comment by ikstream** [comment]
I assume you mean the colour of font in the terminal? Color settings can be done for some terminal emulators in the Xresources file. For others there are different configuration files, but this is based  on the terminal emulator you prefer to use.
The red colour matches the overall colour scheme  of Black Arch with red and black. 
Out of interest, are there problems with the perception of the red colour, like colour blindness or something like that?

**Comment by PanosTrak** [comment]
No I don't mean for the terminal I mean for the whole theme! And no there is not a problem it's just a preference and I think many people with avoid this distro for this red and black color ! :)

**Comment by ikstream** [comment]
This is an interesting suggestion, while different themes are definitely not on our list for the short or even long run, please feel free to create a config for your DE/WM of your choice.
Adding it as a package for like minded people would be an option.
