### ISSUE TITLE
Request: python-otxv2 examples folder

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#2418]
Include [examples](https://github.com/AlienVault-OTX/OTX-Python-SDK/tree/master/examples) folder as it has some command line interface to OTX.

**Comment by noptrix** [comment]
@vdun thx for reporting this. btw, this example directory is not included in pypi packaged version of otxv2. i don't know why. seems to be inconsistent packaging... but we switched to github version now. we've added 'examples' and 'tests' directories to /usr/share/${pkgname[x]}/ - cheers.

**Comment by vdun** [comment]
I still can't find the it ! ?
