### ISSUE TITLE
Updating BlackArch issue 

### ISSUE THREAD

**Issue by Hax0rG1rl** [BlackArch/blackarch#2429]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
Not able to update Blackarch to the latest packages. 

### Steps to reproduce
- Downloaded the 30GB OVA Image from the Balckarch official website
- Imported and start the VM (VMware the latest)
- Did the pacman -Syyu

**Actual result:** I get the errors below. 

**Expected result:** A clean error free upgrade process.

### Screenshots

![image](https://user-images.githubusercontent.com/3704868/62319474-23f73680-b4f2-11e9-971b-0f147ed60c1f.png)

![image](https://user-images.githubusercontent.com/3704868/62319504-370a0680-b4f2-11e9-950e-6e4c3416d9e6.png)

Any ideas how can I fix this? 

Thanks!

**Comment by Hax0rG1rl** [comment]
I found it. FAQ section. Today I learned something new. Now I can go to sleep.

**Comment by JulianVolodia** [comment]
GJ. BlackArch is not compatible with Arch Linux bleeding-edge status so need to be upgraded with:

`pacman -Syyu --needed --overwrite '*' blackarch`

Trying to do this after falling to above issue will fix that.

**Comment by Hax0rG1rl** [comment]
Wow, thank you for your answer. It took me like 5 hours trying various scenarios. Learned so much. OSCP is a small wimpy kid comparing with configuring and debugging and arch flavor install.

**Comment by JulianVolodia** [comment]
No problem. Sorry that too late and happy that you get over! :-)

I will 301 your thankfullness to my friend who show me this issue which he faced also. :-) Without him I will not know about this.

Do you face another issues?
I think most vital is know how to:
- have configured booting mem-stick (sdcard, pendrive, whole external disk...) to rescue,
- access your root partition when breaking boot,
- resize partitions (with crypto also) or moving data to another drive,
- last but not least - checkout&build from AUR.

**Comment by Hax0rG1rl** [comment]
@JulianVolodia check this 
![image](https://user-images.githubusercontent.com/3704868/62329152-2f099100-b509-11e9-97b0-74b0467879bd.png)

**Comment by JulianVolodia** [comment]
nice to remove this package which are in conflict always (so you installed wrong with -Syyu)

To learn more, see which package is where - use this from blackarch repository. Tool to use - QUERY mode, search option of pacman. I will return in moment ;)

**Comment by JulianVolodia** [comment]
BTW. if you have snapshot of downloaded OVA unless you are working on physics machine (but, maybe clean install backup already done?) you could get there and start with fresh. IMHO, when starting with arch it's good to start iterative mode and do some things again and again, having old-one installation stiil somewhere...

**Comment by JulianVolodia** [comment]
I am checking if you fall into issue with BlackArch or mixed packages from this issue.

**Comment by Hax0rG1rl** [comment]
> BTW. if you have snapshot of downloaded OVA unless you are working on physics machine (but, maybe clean install backup already done?) you could get there and start with fresh. IMHO, when starting with arch it's good to start iterative mode and do some things again and again, having old-one installation stiil somewhere...

Yeah, I did a snapshot of that. :D and thanks trying helping me. I am sure there are a lot of other dudes going through the same pain.

**Comment by noptrix** [comment]
> @JulianVolodia check this
> ![image](https://user-images.githubusercontent.com/3704868/62329152-2f099100-b509-11e9-97b0-74b0467879bd.png)
> 
> FFS

Remove ```android-tools``` here with ```sudo pacman -Rns android-tools``` and show us the results

**Comment by noptrix** [comment]
@Hax0rG1rl also, can you run this please as root:
```
pacman -Rscn $(pacman -Qtdq)
updatedb
pkgfile -u
pacman -Fyy
pacman-db-upgrade
yes | pacman -Scc
sync
```

then run ```pacman -Syyu --needed blackarch --overwrite='*'``` again

**Comment by Hax0rG1rl** [comment]
Thank you all. It seems I won't go to sleep after all, but hell yes, sleep is for the weak ppl

**Comment by Hax0rG1rl** [comment]
That worked flawlessly. Thank you all! Issue closed.

**Comment by JulianVolodia** [comment]
@noptrix thanks also, and @Hax0rG1rl sorry that I didn't helped like @noptrix 

Take care! :)

**Comment by Hax0rG1rl** [comment]
> @noptrix thanks also, and @Hax0rG1rl sorry that I didn't helped like @noptrix
> 
> Take care! :)

@julianvolodia I thanked you all. ;)

**Comment by JulianVolodia** [comment]
Thanks! Just mention that Maintainter is The Maintainer and good they are here.

I don't know about this fast and clear clean up way. CU

**Comment by Hax0rG1rl** [comment]
**Updates**

Not this is a critical thing but after the whole update process, those too are acting ina rogue way. Even you get them updated once they keep saying they have to be updated. Which is odd. 

![image](https://user-images.githubusercontent.com/3704868/62332804-21f29f00-b515-11e9-99b1-8cc155041efa.png)

**Comment by noptrix** [comment]
@Hax0rG1rl this is because we didn't update/mirrored the new versions. i will do it now and it should go away as soon as your mirror is synced with blackarch.org. so in short: do your last ```pacman -Syu``` call and then ignore this.

**Comment by noptrix** [comment]
> @Hax0rG1rl this is because we didn't update/mirrored the new versions for (checksec, wpscan). i will do it now and it should go away as soon as your mirror is synced with blackarch.org. so in short: do your last `pacman -Syu` call and then ignore this.

```
[ noptrix@blackarch-dev ~/blackarch ]$ repos/blackarch/scripts/up-officials 
[+] syncing packages
[+] comparing packages: core
[+] comparing packages: community
    > update available: checksec
    > update available: wpscan
``` so it's running now.

**Comment by Hax0rG1rl** [comment]
🙇‍♀

**Comment by Plague1234** [comment]
thanks you @noptrix
