### ISSUE TITLE
[Tool request] libguestfs

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#2430]
http://libguestfs.org

AUR:
https://aur.archlinux.org/packages/libguestfs/
https://aur.archlinux.org/packages/python-libguestfs/

**Comment by Edu4rdSHL** [comment]
Hello, @vdun. libguestfs is not a hacking tool, please give me valid reasons to add that and I will reopen the issue!

Thanks.

**Comment by vdun** [comment]
very useful forensic tool.
