### ISSUE TITLE
Vim error

### ISSUE THREAD

**Issue by Franchium** [BlackArch/blackarch#2431]
Everytime i quit the vim i got this error, it's just pop up in a second.
I already upgrade the vim to the latest version but still got the same error.

![Screenshot from 2019-08-10 11-15-11](https://user-images.githubusercontent.com/41231953/62817519-c97c5c80-bb27-11e9-868d-03c8c38c9e97.png)

![Screenshot from 2019-08-10 11-15-59](https://user-images.githubusercontent.com/41231953/62817482-3b07db00-bb27-11e9-9d62-46f6b3d70bf7.png)

**Comment by Franchium** [comment]
I just figured the problem out, the unite plugin on vim is the problem. I remove the unite plugin and no error appear. I think the unite plugin need to be fixed

**Comment by Franchium** [comment]
The plugin is unite vim

**Comment by ikstream** [comment]
Unite is not maintained by us, so I'm closing this issue

**Comment by Franchium** [comment]
But it comes pre-installed on blackarch.

**Comment by noptrix** [comment]
@Franchium we've removed the unite plugin. feel free to re-open if other issues occur :)
