### ISSUE TITLE
Blackarch as Main OS

### ISSUE THREAD

**Issue by TaylorSolid** [BlackArch/blackarch#2432]
I wish to make blackarch my main os, I understand some of the drawbacks as running it but it is on a different computer that had a hard drive issues that I replaced with a new one. What steps do I need to take to install as a main OS?

**Comment by ikstream** [comment]
Just follow the install instructions and you are fine. Have a look at the arch linux beginners guide to get a good understanding of what you are doing.

**Comment by Edu4rdSHL** [comment]
I never recommend a pentest OS as main OS. Anyways, that's a user choice.
