### ISSUE TITLE
[Tool installation Fail] dartspylru package conflict

### ISSUE THREAD

**Issue by AiyionPrime** [BlackArch/blackarch#2435]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

First things first, thanks for the awesome project; I love to have my favorite tools from kali over here.

### Bug description
DartsPyLRU is in conflict with python2-darts.util.lru from the aur.
Would it be possibe to mark this in the package?
Or even use the aur version, if it provides the same python package?

### Steps to reproduce
install `python2-darts.util.lru` from the aur, e.g.:
`yaourt -S python2-darts.util.lru`
Install `dartspylru` or `w3af`, which depends on it since 4ce4e5b724870adb0ce6440d6a8b9f3e87287731 .
`pacman -S blackarch/w3af`
or
`pacman -S blackarch/dartspylru`

**Actual result:**

```
error: failed to commit transaction (conflicting files)
dartspylru: /usr/lib/python2.7/site-packages/darts.util.lru-0.5-py2.7-nspkg.pth exists in filesystem (owned by python2-darts.util.lru)
dartspylru: /usr/lib/python2.7/site-packages/darts.util.lru-0.5-py2.7.egg-info/PKG-INFO exists in filesystem (owned by python2-darts.util.lru)
dartspylru: /usr/lib/python2.7/site-packages/darts.util.lru-0.5-py2.7.egg-info/SOURCES.txt exists in filesystem (owned by python2-darts.util.lru)
dartspylru: /usr/lib/python2.7/site-packages/darts.util.lru-0.5-py2.7.egg-info/dependency_links.txt exists in filesystem (owned by python2-darts.util.lru)
dartspylru: /usr/lib/python2.7/site-packages/darts.util.lru-0.5-py2.7.egg-info/namespace_packages.txt exists in filesystem (owned by python2-darts.util.lru)
dartspylru: /usr/lib/python2.7/site-packages/darts.util.lru-0.5-py2.7.egg-info/top_level.txt exists in filesystem (owned by python2-darts.util.lru)
dartspylru: /usr/lib/python2.7/site-packages/darts.util.lru-0.5-py2.7.egg-info/zip-safe exists in filesystem (owned by python2-darts.util.lru)
dartspylru: /usr/lib/python2.7/site-packages/darts/lib/utils/lru.py exists in filesystem (owned by python2-darts.util.lru)
dartspylru: /usr/lib/python2.7/site-packages/darts/lib/utils/lru.pyc exists in filesystem (owned by python2-darts.util.lru)
dartspylru: /usr/lib/python2.7/site-packages/darts/lib/utils/lru.pyo exists in filesystem (owned by python2-darts.util.lru)
Errors occurred, no packages were upgraded.
```

**Expected result:** 
Either a warning about the upcoming package conflict, or w3af being fine with the aur package?

### Info for developers
https://github.com/BlackArch/blackarch/blob/master/packages/dartspylru/PKGBUILD
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python2-darts.util.lru

**Comment by Edu4rdSHL** [comment]
Thanks for informing, @AiyionPrime. It's now fixed, just wait for repos to be synced.
