### ISSUE TITLE
black window after installing system

### ISSUE THREAD

**Issue by lucassiel** [BlackArch/blackarch#2437]
after installing the whole system start the login and password screen because entering the data starts the system soon everything is black and hangs, this happens with all tested Arch distributions,

PC - SETUP

i5-4690, 16gb ram
ssd 250 GB barracuda

r9 390 8gb HammerX video card

help me

**Comment by Edu4rdSHL** [comment]
> this happens with all tested Arch distributions
It isn't a BlackArch issue, looks like you need to search the necessary drivers to run the OS.
