### ISSUE TITLE
[Tool Request] Cherrytree

### ISSUE THREAD

**Issue by raj77in** [BlackArch/blackarch#2451]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

### Bug description
Cherrytree - A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single xml or sqlite file.
[Cherrytree homepage](https://www.giuspen.com/cherrytree)

### Steps to reproduce
Fearures:
-    rich text (foreground color, background color, bold, italic, underline, strikethrough, small, h1, h2, h3, subscript, superscript, monospace)
-    syntax highlighting supporting several programming languages
-    images handling: insertion in the text, edit (resize/rotate), save as png file
-    embedded files handling: insertion in the text, save to disk
-    multi-level lists handling (bulleted, numbered, to-do and switch between them, multiline with shift+enter)
-    simple tables handling (cells with plain text), cut/copy/paste row, import/export as csv file
-    codeboxes handling: boxes of plain text (optionally with syntax highlighting) into rich text, import/export as text file
-    execution of the code for code nodes and codeboxes; the terminal and the command per syntax highlighting is configurable in the preferences dialog
-    alignment of text, images, tables and codeboxes (left/center/right/fill)
-    hyperlinks associated to text and images (links to webpages, links to nodes/nodes + anchors, links to files, links to folders)
-    spell check (using pygtkspellcheck and pyenchant)
-    intra application copy/paste: supported single images, single codeboxes, single tables and a compound selection of rich text, images, codeboxes and tables
-    cross application copy/paste (tested with libreoffice and gmail): supported single images, single codeboxes, single tables and a compound selection of rich text, images, codeboxes and tables
-    copying a list of files from the file manager and pasting in cherrytree will create a list of links to files, images are recognized and inserted in the text
-    print & save as pdf file of a selection / node / node and subnodes / the whole tree
-    export to html of a selection / node / node and subnodes / the whole tree
-    export to plain text of a selection / node / node and subnodes / the whole tree
-    toc generation for a node / node and subnodes / the whole tree, based on headers h1, h2 and h3
-    find a node, find in selected node, find in selected node and subnodes, find in all nodes
-    replace in nodes names, replace in selected node, replace in selected node and subnodes, replace in all nodes
-    iteration of the latest find, iteration of the latest replace, iteration of the latest applied text formatting
-    import from html file, import from folder of html files
-    import from plain text file, import from folder of plain text files
-    import from basket, cherrytree, epim html, gnote, keepnote, keynote, knowit, mempad, notecase, rednotebook, tomboy, treepad lite, tuxcards, zim
-    export to cherrytree file of a selection / node / node and subnodes / the whole tree
-    password protection (using http://www.7-zip.org/) – NOTE: while a cherrytree password protected document is opened, an unprotected copy is extracted to a temporary folder of the filesystem; this copy is removed when you close cherrytree
-    tree nodes drag and drop
-    automatic link to web page if writing the URL
-    automatic link to node if writing node name either with no spaces and camelcase or surrounded by [[node name]]

**Actual result:** Package is not present in the repos'
**Expected result:** It will be useful addition for the community.

### Screenshots
[Main Window](https://www.giuspen.com/images/cherrytree-main_window_text.png)
[Main Window2](https://www.giuspen.com/images/cherrytree-main_window_code.png)

### Info for developers
**Tool version:** 0.37.6

I am willing to create this package but do not know the procedure. If there is a documentation on doing that, I can help in packaging the same, if required.

**Comment by noraj** [comment]
CherryTree as QOwnNotes, Vnotes, Boostnotes, joplin, etc and dozens of other app are just some notes taking apps.
We won't package them as BlackArch is a security focus distro and not a generic one.
The only one we maybe could package is https://github.com/ehrishirajsharma/SwiftnessX because it specially targets pentesters and includes some pentest checklists.
