### ISSUE TITLE
Dynamic badge system

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2455]
@noptrix

Do you think it is possible to build a [dynamic badge](https://shields.io/#dynamic-badge) system (served from our own server or from shields.io) where you put the name of a package (eg. chisel) and you get a badge with the version of the tool (as in BA repo or git).

![](https://img.shields.io/badge/BlackArch-91.ee6601a-black)
![](https://img.shields.io/badge/BlackArch-91.ee6601a-black?logo=arch%20linux)

Also clicking on the badge would points to `https://github.com/BlackArch/blackarch/tree/master/packages/${pkgname}` eg. https://github.com/BlackArch/blackarch/tree/master/packages/chisel (a problem could be tools were the git folder is named differently than the $pkgname).

**Comment by noptrix** [comment]
@noraj good idea ... i will see and let you know :)

**Comment by noraj** [comment]
Useless to implement that ourselves, repology does it already.

Example with rabid: https://repology.org/project/rabid/badges

[![BlackArch package](https://repology.org/badge/version-for-repo/blackarch/rabid.svg)](https://repology.org/project/rabid/versions)

**Comment by aancw** [comment]
@noraj this feature looks awesome for blackarch-site. So every tools list will display version badge.

**Comment by Edu4rdSHL** [comment]
As @noraj pointed out, Repology does exactly it.

I'm closing the issue but let me know if you have any comments.
