### ISSUE TITLE
weird characters in login window

### ISSUE THREAD

**Issue by raj77in** [BlackArch/blackarch#2457]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
Login window shows weird characters and is not legible.

### Steps to reproduce
- I upgraded from 2018.12.01 ova to latest
- After upgrade the login window is not legible.

**Actual result:** Text in login window is not legible.
**Expected result:** Text should be properly displayed in the login window.

### Screenshots
![VirtualBox_blackarch_03_09_2019_21_52_10](https://user-images.githubusercontent.com/3305948/64191355-eb060500-ce95-11e9-832f-130c83580ae4.png)

**Comment by noraj** [comment]
@raj77in Same as https://github.com/BlackArch/blackarch/issues/2433

**Comment by noraj** [comment]
What do you mean by `I upgraded from 2018.12.01 ova to latest` ?
You mean you were using OVA 2018.12.01 and did `pacman -Syu` and then the login was broken?

**Comment by raj77in** [comment]
@noraj Yes, I had 2018.12.01 running in Virtualbox and then I upgraded using the command given in the FAQ - ```pacman -Syyu --needed --overwrite '*' blackarch```

I looked at the other bug mentioned and installed ```terminus-font-ttf``` and rebooted but still the issue persists.
