### ISSUE TITLE
[Tool request] analyzeMFT

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#2462]
https://github.com/dkovar/analyzeMFT

**Comment by peeweep** [comment]
analyzemft-git and analyzemft are in AUR now.

**Comment by mrsmith0x00** [comment]
@vdun added!

**Comment by noraj** [comment]
078a867b03110e3fbc6476c1fff8a00d15574dc8
cc650cb138196819ae1dce514b4e4353c7e0eeb3
