### ISSUE TITLE
passwd: Module is unknown

### ISSUE THREAD

**Issue by sc-steven** [BlackArch/blackarch#2477]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
When installing BlackArch from either the Internet or local ISO i get the following error in repeat after successfully formatting the HDD.
```
passwd: Module is unknown
passwd: password unchanged
```

### Steps to reproduce
- Mount blackarch-linux-live-2019-09-01-x86_64.iso
- Boot into BlackArch
- sudo blackarch-install
- option 1 to update the local installer
- option 2 and run through standard setup (enabling encryption)
- After partitioning and format complete, the error appears

**Actual result:** 
```
passwd: Module is unknown
passwd: password unchanged
```

**Expected result:** 
Installer finishes successfully, i assume setting up the local user/password correctly.

### Screenshots
<img width="513" alt="Screen Shot 2019-09-30 at 2 38 22 pm" src="https://user-images.githubusercontent.com/54784064/65850047-8359b180-e390-11e9-90cb-d78c9150500e.png">

### Info for developers
**Device:**
VirtualBox on Apple Laptop

**GNU/Linux distribution:**
OSX 10.14.6
VirtualkBox 6.0.12

**Tool version:**
N/A

### Link to debug log
Where do i get this from?

**Comment by noraj** [comment]
The new version of the ISO seems to fix this. Please re-open if still happening.
