### ISSUE TITLE
Black Arch on VirtualBox --> Minimal BASH like line editing screen

### ISSUE THREAD

**Issue by rossophantasma** [BlackArch/blackarch#2489]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
Today i tried to install BlackArch on a 30GB VirtualBox VM under Windows 10 Pro, using the netinstall ISO. I followed the instructions but i can't get the OS to boot. Literally i did everything i could to troubleshoot it, boot and root partition separated, boot and root on the same partition, marked /boot as bootable on cfdisk, tried unmarking it, re-downloaded the ISO 3 times, but it wont get past the Minimal BASH-like screen. I've benn wondering if it has to do with the blackarch-install updating. After it updates itself, it tells me to restart blackarch-install, so i re-type that again and redo some steps (hostname, internet connection, locale and keymap)
### Steps to reproduce
- Start BlackArch installer
- Complete some steps until the installer prompts an update
- Let it update itself
- Restart the installer (retype blackarch-install)
- Let the installer finish
- Reboot PC
- Check

Actual result: Machine boots onto this screen mentioned at the title.
Expected result: Booting onto the system

### Screenshots
![asd](https://user-images.githubusercontent.com/50408643/66421896-191fbd00-e9df-11e9-8e54-c891b47f2754.png)

**Comment by noraj** [comment]
Check 

- https://rawsec.ml/en/archlinux-installation-in-virtualbox/
- https://wiki.archlinux.org/index.php/VirtualBox#Installation_steps_for_Arch_Linux_guests

to be sure you know how to properly install ArchLinux in Virtualbox, this is different than on a host.

**Comment by PixeLInc** [comment]
I can confirm this also happens on a normal host using any sort of network install.

Copying directly from the live iso dump seems to work fine but I cannot install blackarch either on a VM or a physical machine without running into this (unless using live dump which is less than ideal)

**Comment by rossophantasma** [comment]
> Check
> 
> * https://rawsec.ml/en/archlinux-installation-in-virtualbox/
> * https://wiki.archlinux.org/index.php/VirtualBox#Installation_steps_for_Arch_Linux_guests
> 
> to be sure you know how to properly install ArchLinux in Virtualbox, this is different than on a host.

Tried it, it still didn't work.

**Comment by rossophantasma** [comment]
> I can confirm this also happens on a normal host using any sort of network install.
> 
> Copying directly from the live iso dump seems to work fine but I cannot install blackarch either on a VM or a physical machine without running into this (unless using live dump which is less than ideal)

Thanks! I'll try the live iso method then. Thanks!

**Comment by rossophantasma** [comment]
> I can confirm this also happens on a normal host using any sort of network install.
> 
> Copying directly from the live iso dump seems to work fine but I cannot install blackarch either on a VM or a physical machine without running into this (unless using live dump which is less than ideal)

Live dumping is indeed working without troubles on a VirtualBox VM.

**Comment by ikstream** [comment]
please have a look at BlackArch/blackarch#1808. Does this address the problem

**Comment by rossophantasma** [comment]
> please have a look at #1808. Does this address the problem

I'll give it a try tomorrow, i have it installed via the LiveISO, working flawlessly as of today

**Comment by noraj** [comment]
The new version of the ISO seems to fix this. Please ask for re-open if the problem still happening.
