### ISSUE TITLE
Autopsy 4.12 fails to start

### ISSUE THREAD

**Issue by obilodeau** [BlackArch/blackarch#2497]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Autopsy 4.12.0 doesn't start.

### Steps to reproduce
- Upgrade to latest autopsy
- Run it
- Notice the crash

**Actual result:** 

```
org.netbeans.InvalidException: StandardModule:org.sleuthkit.autopsy.core jarFile: /opt/autopsy/autopsy/modules/org-sleuthkit-autopsy-core.jar: java.lang.NoClassDefFoundError: org/sleuthkit/datamodel/SleuthkitJNI
```

The requested file is not part of that jar.

**Expected result:**

Autopsy would start.

### Screenshots

![autopsy-4 12](https://user-images.githubusercontent.com/546325/67060839-711b9980-f12c-11e9-920a-3a647693ecea.png)

### Info for developers

**Device:** Dell XPS 15
**GNU/Linux distribution:** Arch
**Tool version:** 4.12

I'm still investigating a bit but I'm about to give up.

**Comment by obilodeau** [comment]
Got further along

![autopsy-4 12-java-runtime](https://user-images.githubusercontent.com/546325/67061398-3155b180-f12e-11e9-9d3a-cb3bf8b34be7.png)

**Comment by obilodeau** [comment]
To resolve that last issue, I needed to `makepkg` `sleuthkit-java` on my system where I use `java-8-openjdk` as my default java environment. Maybe the binary package should be built with a more compatible java version since it seems that the `autopsy` package is built like that.

I also needed to manually install `java8-openjfx`. I don't see how the `java-runtime` and `java-openjfx` dependencies could be adjusted so that the version of java installed pulls in the right java-openjfx version... Status quo doesn't bother me though.

For the first issue (`NoClassDefFound`), I'm going to send a PR: there's a problem in the symlink.

**Comment by Edu4rdSHL** [comment]
Hello @obilodeau. Thanks for the hints, we can simply add https://www.archlinux.org/packages/extra/x86_64/jre8-openjdk/ for the java-runtime dependency and that will solve the issue, I'm going to do some tests.

**Comment by tresh** [comment]
@Edu4rdSHL @obilodeau thanks for working on this. The problem does exist with the version bump to 4.13.0-2. I get the same error message as @obilodeau:

`org.netbeans.InvalidException: StandardModule:org.sleuthkit.autopsy.core jarFile: /opt/autopsy/autopsy/modules/org-sleuthkit-autopsy-core.jar: java.lang.NoClassDefFoundError: org/sleuthkit/datamodel/SleuthkitJNI`

For me the problem went away after applying the fix presented in https://github.com/BlackArch/blackarch/issues/2497#issuecomment-543466759. I used the most recently available package from AUR (https://aur.archlinux.org/packages/sleuthkit-java/), which has also been bumped to 4.7, and built it with makepkg. Hope that helps someone else.
