### ISSUE TITLE
impacket missing dependency

### ISSUE THREAD

**Issue by Torxed** [BlackArch/blackarch#2518]
As per comment on issue #2243,

Missing a dependency in the `PKGBUILD`: `python-pycryptodomex`

Won't be able to do `GetUserSPNs.py -request "domain/user:password"` without this.
Not sure even impacket itself will work without it.

**Comment by ikstream** [comment]
impacket is not maintained by us. It is provided by community

**Comment by Torxed** [comment]
oh f** yea you're right. Apologies.
