### ISSUE TITLE
[Tool request] srum-dump

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#2522]
https://github.com/MarkBaggett/srum-dump

**Comment by sachinkamath** [comment]
@noptrix @Edu4rdSHL Have a question around this. Whenever there are release files pushed in the Git repo (such as a windows executable), is it usually added into `/usr/share/$pkgname` , the windows binaries folder or is it ignored altogether?

**Comment by Edu4rdSHL** [comment]
The tool was basically made to work with windows only.
