### ISSUE TITLE
Grub not booting after install

### ISSUE THREAD

**Issue by Fizuaal** [BlackArch/blackarch#2533]
Installing Blackarch with Blackarch-install, all seems good but when I reboot, I am at the Grub rescue menu.

Don't know what to do. 

Tested on 2 differents laptops and peoples on discord have the same issue.

![IMG_20191031_102830](https://user-images.githubusercontent.com/45623406/68197319-5d8c8180-ffba-11e9-8f7e-8875e4496ec9.jpg)

**Comment by ikstream** [comment]
Duplicate. Please check BlackArch/blackarch#1808 for a possible solution
