### ISSUE TITLE
System template for Qubes OS

### ISSUE THREAD

**Issue by biladi** [BlackArch/blackarch#2537]
I know that this is not the most important thing to report on this site. However, this is very important to me. I don't have such great IT skills myself. I use Qubes OS which uses Xen for virtualization inside Fedora and Debian. However, I think your system would be very useful to us for Qubes OS users and it would be great if you were interested in making your system template that could be installed in Qubes OS. More information is available on the project website, but I am asking you to be interested in this, because we need your system very much in combination with the security offered in the virtual environment of Qubes OS. Please.

**Comment by noraj** [comment]
@biladi Qubes OS is great but what you want to do is already achievable. 
There is already an ArchLinux template, see https://www.qubes-os.org/doc/templates/archlinux/
Then you can install BlackArch on top of ArchLinux, see https://blackarch.org/downloads.html#install-repo
