### ISSUE TITLE
tools not opening

### ISSUE THREAD

**Issue by sh1va73** [BlackArch/blackarch#2539]
I have BlackArch ova installed on Virtualbox. When I right click on the desktop then the menu appears , but when I click a tool then it does not open / start. This happens with all tools, none of them start up. I can only start up the terminal. Any ideas what's wrong?

**Comment by mrsmith0x00** [comment]
@sh1va73 when you click on an application, it very quickly opens it with a key `--help` and closes it just as quickly.

**Comment by sh1va73** [comment]
Thanks for your reply, but its is still not clear to me. How do I properly open a tool from the menu?

**Comment by mrsmith0x00** [comment]
@sh1va73 open terminal and type the command.

**Comment by sh1va73** [comment]
ah ok thanks, I understand. so there is no use for that menu?

**Comment by mrsmith0x00** [comment]
@sh1va73 menu for tools overview.

**Comment by sh1va73** [comment]
ok thanks for pointing that out, all clear now.
