### ISSUE TITLE
[Tool addition] GWT-3D

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2543]
I'll add this GWT tool (2016) in the future:

- https://github.com/miaouPlop/GWT-3D
- http://miaouplop.github.io/GWT-3D/

And maybe this one too (2017):

- https://github.com/sourceincite/tools/blob/master/gwt.py
- https://srcincite.io/blog/2017/04/27/from-serialized-to-shell-auditing-google-web-toolkit.html

Or this old one (2012) but working offline:

- https://github.com/v-p-b/S2GWTEnum

**Comment by ikstream** [comment]
As the last commit is from 2016 does this add any value?

**Comment by noraj** [comment]
@ikstream This is a more update fork of [this toolkit](https://github.com/GDSSecurity/GWT-Penetration-Testing-Toolset) which is currently packaged but last commit is 2012. So its already better and theoretically support newer version of GWT.
