### ISSUE TITLE
Fail when install blackarch

### ISSUE THREAD

**Issue by piug** [BlackArch/blackarch#2544]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
When install all of the tools and run "sudo pacman -S blackarch" have some errors.
I try run "sudo pacman -Syyy" and "sudo pacman -Syu" but this does not solve the error.

My output:
:: There are 2394 members in group blackarch:
:: Repository blackarch
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
/usr/lib/python3.8/site-packages/ipython_genutils/__init__.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/__pycache__/__init__.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/__pycache__/_version.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/__pycache__/encoding.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/__pycache__/importstring.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/__pycache__/ipstruct.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/__pycache__/path.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/__pycache__/py3compat.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/__pycache__/tempdir.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/__pycache__/text.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/_version.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/encoding.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/importstring.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/ipstruct.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/path.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/py3compat.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/tempdir.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/testing/__init__.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/testing/__pycache__/__init__.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/testing/__pycache__/decorators.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/testing/decorators.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/tests/__init__.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/tests/__pycache__/__init__.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/tests/__pycache__/test_importstring.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/tests/__pycache__/test_path.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/tests/__pycache__/test_tempdir.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/tests/__pycache__/test_text.cpython-38.pyc exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/tests/test_importstring.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/tests/test_path.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/tests/test_tempdir.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/tests/test_text.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python3.8/site-packages/ipython_genutils/text.py exists in both 'python-traitlets' and 'ipython-genutils'
/usr/lib/python2.7/site-packages/bson/objectid.py exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/objectid.pyc exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/objectid.pyo exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/py3compat.py exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/py3compat.pyc exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/py3compat.pyo exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/tz_util.py exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/tz_util.pyc exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/bson/tz_util.pyo exists in both 'python2-pymongo' and 'python2-bson'
/usr/lib/python2.7/site-packages/whois/__init__.py exists in both 'python2-python-whois' and 'python2-whois'
/usr/lib/python2.7/site-packages/whois/__init__.pyc exists in both 'python2-python-whois' and 'python2-whois'
/usr/lib/python2.7/site-packages/whois/__init__.pyo exists in both 'python2-python-whois' and 'python2-whois'
/usr/bin/cymruwhois exists in both 'python-python-cymruwhois' and 'python-cymruwhois'
/usr/lib/python3.8/site-packages/google_streetview-1.2.9-py3.8.egg-info/PKG-INFO exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview-1.2.9-py3.8.egg-info/SOURCES.txt exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview-1.2.9-py3.8.egg-info/dependency_links.txt exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview-1.2.9-py3.8.egg-info/entry_points.txt exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview-1.2.9-py3.8.egg-info/requires.txt exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview-1.2.9-py3.8.egg-info/top_level.txt exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/__init__.py exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/__main__.py exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/__pycache__/__init__.cpython-38.opt-1.pyc exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/__pycache__/__init__.cpython-38.pyc exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/__pycache__/__main__.cpython-38.opt-1.pyc exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/__pycache__/__main__.cpython-38.pyc exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/__pycache__/api.cpython-38.opt-1.pyc exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/__pycache__/api.cpython-38.pyc exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/__pycache__/cli.cpython-38.opt-1.pyc exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/__pycache__/cli.cpython-38.pyc exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/__pycache__/helpers.cpython-38.opt-1.pyc exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/__pycache__/helpers.cpython-38.pyc exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/api.py exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/cli.py exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/config.json exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python3.8/site-packages/google_streetview/helpers.py exists in both 'google_streetview' and 'python-google-streetview'
/usr/lib/python2.7/site-packages/google_streetview-1.2.9-py2.7.egg-info/PKG-INFO exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview-1.2.9-py2.7.egg-info/SOURCES.txt exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview-1.2.9-py2.7.egg-info/dependency_links.txt exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview-1.2.9-py2.7.egg-info/entry_points.txt exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview-1.2.9-py2.7.egg-info/requires.txt exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview-1.2.9-py2.7.egg-info/top_level.txt exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/__init__.py exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/__init__.pyc exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/__init__.pyo exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/__main__.py exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/__main__.pyc exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/__main__.pyo exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/api.py exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/api.pyc exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/api.pyo exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/cli.py exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/cli.pyc exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/cli.pyo exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/config.json exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/helpers.py exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/helpers.pyc exists in both 'python2-google-streetview' and 'python2-google_streetview'
/usr/lib/python2.7/site-packages/google_streetview/helpers.pyo exists in both 'python2-google-streetview' and 'python2-google_streetview'
Errors occurred, no packages were upgraded.

**Comment by mrsmith0x00** [comment]
@piug  first of all, if you installed pentesting distro, you should know what is FAQ. And if yes, you can find: `pacman -Syyu blackarch --needed --noconfirm --overwrite '*'`
