### ISSUE TITLE
Upgrade error: Errors occurred, no packages were upgraded.

### ISSUE THREAD

**Issue by alecskup** [BlackArch/blackarch#2563]
Today I installed blackarch (I use live-usb) and after started update with `sudo pacman -Syu`
I see more files for update but I approve "Yes". 

![1scr](https://user-images.githubusercontent.com/58822727/70734013-79ebae80-1d1c-11ea-9d50-a74646dd2278.png)
![2scr](https://user-images.githubusercontent.com/58822727/70734020-807a2600-1d1c-11ea-9f85-ea1d2b7734a4.png)

In the end I see error:
```
python2-python-socketio: /usr/lib/python2.7/site-packages/socketio /tornado.pyc exists in filesystem (owned by python2-socketio)
 python2-python-socketio: /usr/lib/python2.7/site-packages/socketio/tornado.pyo exists in filesystem (owned by python2-socketio)
 python2-python-socketio: /usr/lib/python2.7/site-packages/socketio/zmq_manager.py exists in filesystem (owned by python2-socketio)
 python2-python-socketio: /usr/lib/python2.7/site-packages/socketio/zmq_manager.pyc exists in filesystem (owned by python2-socketio)
 python2-python-socketio: /usr/lib/python2.7/site-packages/socketio/zmq_manager.pyo exists in filesystem (owned by python2-socketio)
 Errors occurred, no packages were upgraded.

```

What do I do in this situation?

**Comment by mrsmith0x00** [comment]
@alecskup `sudo pacman -Syu --noconfirm --needed --overwrite '*'`
