### ISSUE TITLE
stegoveritas: dependency issue

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2564]
Version installed: `stegoveritas-1.2-2`

```
$ stegoveritas --help   
Traceback (most recent call last):
  File "/usr/bin/stegoveritas", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'stegoveritas-binwalk' distribution was not found and is required by stegoveritas
```

Upstream source: https://github.com/bannsec/stegoVeritas

BA PKGBUILD: https://github.com/BlackArch/blackarch/blob/master/packages/stegoveritas/PKGBUILD

## Related issues

Added after issue  #2302

**Comment by noraj** [comment]
By analysing the dependencies and making a diff between [upstream setup.py](https://github.com/bannsec/stegoVeritas/blob/master/setup.py) and [BA PKGBUILD](https://github.com/BlackArch/blackarch/blob/master/packages/stegoveritas/PKGBUILD)

I can see that:

- `binwalk` -> `stegoveritas-binwalk`
- `pyrhon-pfp` -> `stegoveritas-pfp`
- new `distro`

**Comment by noraj** [comment]
## Solution

- `python-distro` is already in community AL repo
- `binwalk` and python-pfp` maybe enough rather than `stegoveritas-binwalk` `stegoveritas-pfp` as it seems nothing was modified, the author just thought it was better to bring them via python rather than OS. So adding a `sed` line in the PKGBUILD to remove `stegoveritas-binwalk` `stegoveritas-pfp` from setup.py in pre-build and keep `binwalk` and python-pfp`  in the PKGBUILD.

**Comment by Edu4rdSHL** [comment]
Hello, @noraj. It issue is fixed in our part when we added stegoveritas-binwalk package. 

stegoveritas-binwalk is capable of provide the binwalk package, so, we need to update PKGBUILDs depending on binwalk to stegoveritas-binwalk and add provides=('binwalk') section to stegoveritas-binwalk PKGBUILD. 

Btw, stegoveritas is searching for exiftool in $PATH but it's under /usr/bin/perl_vendor/exiftool
and that's why it says that exiftool isn't installed now. Upstream needs to fix that issue.

**Comment by noraj** [comment]
https://github.com/bannsec/stegoVeritas/issues/21

> yeah, so basically I had to add my own quasi-versions of python-pfp due to their broken dependencies at the time. It appears they've been updating again now so maybe can switch back to the original python-pfp, but have not tested that.
> 
> distro was used to help with cross platform distribution identification.
> 
> binwalk's last official release in pypy was 2015. Tried to get them to push a new update but no-go, so basically pushed my own deployment of it. You're correct that it should be fine to use the binwalk from the system if it's already present.

So as I understand it. We can keep binwalk and don't care about `stegoveritas-binwalk` so just use a sed to remove it from setup.py. We can try with `python-pfp` and if it doesn't work so we'll have to package `stegoveritas-pfp` instead.

**Comment by noraj** [comment]
I should fix that when I'll be back at home.
