### ISSUE TITLE
Add [nessus].

### ISSUE THREAD

**Issue by ghost** [BlackArch/blackarch#257]
Nessus is a vulnerabiltiy scanner.

Homepage: http://www.tenable.com/products/nessus
AUR: https://aur.archlinux.org/packages/nessus

**Comment by DF001** [comment]
why are we closing the request as @noraj you maintain the package on arch aur https://aur.archlinux.org/packages/nessus ?? I understand the situation of not being able to redistribute but as it already exists on the arch aur i don't see any issue with that

**Comment by noraj** [comment]
It can't be redistributed in ArchLinux or BlackArch Linux.

In the [AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nessus) it's downloaded from the Tenable website, then there is a [license warning in the post install step](https://aur.archlinux.org/cgit/aur.git/tree/nessus.install?h=nessus).

In the AUR, the user build the PKGBUILD so there is no redistribution while in a Linux distribution the PKGBUILD are pre-built, stored on the distribution servers and mirrors servers so there is a redistribution which make it legally impossible. It's distributing a binary versus distributing a script that download a binary.

**Comment by DF001** [comment]
so @noraj the only way is basically git clone the the aur package and than install the PKGBUILD that we have to compile and tell the user to do the same ??

**Comment by noraj** [comment]
Yeah install it from AUR with git and makepkg or any AUR helper.
