### ISSUE TITLE
[Tool request] endpointdiff

### ISSUE THREAD

**Issue by Hax0rG1rl** [BlackArch/blackarch#2586]
https://github.com/ameenmaali/endpointdiff

**Comment by noraj** [comment]
Can you explain how is it security related?

**Comment by bgman111111** [comment]
> https://github.com/ameenmaali/endpointdiff

NO female VIOLENCE TOWARD ALL MEN

**Comment by bgman111111** [comment]
> Can you explain how is it BAN her. women has to respect men. what women try think they are different from men. and can want everything. no in 21 century hss equality. if not tgen this is CRIME. IF then i want blackarch be ubuntu.

**Comment by Hax0rG1rl** [comment]
@noraj I admit this is very in between. I will close this one. 

@bgman111111, I do consider that even spending a few drops of my brain energy thinking to post a comment to your posts would be a blasphemy.
