### ISSUE TITLE
cuckoo: No module named wol

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#2590]
On fresh blackarch chroot:
```
[root@root /]# cuckoo -h
Traceback (most recent call last):
  File "cuckoo/main.py", line 14, in <module>
    import cuckoo
  File "/usr/lib/python2.7/site-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/usr/lib/python2.7/site-packages/cuckoo/machinery/__init__.py", line 10, in <module>
    __file__, "cuckoo.machinery", globals(), Machinery, as_dict=True
  File "/usr/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 46, in enumerate_plugins
    "review its contents and/or validity!" % (module_name, e)
cuckoo.common.exceptions.CuckooOperationalError: Unable to load the Cuckoo plugin at cuckoo.machinery.physical: No module named wol. Please review its contents and/or validity!
```

**Comment by noraj** [comment]
`wol` seems to be a sub-class of `wakeonlan` module but `wakeonlan` is already required: https://github.com/cuckoosandbox/cuckoo/search?q=wakeonlan&unscoped_q=wakeonlan

`'python2-wakeonlan'` is already required in the PKGBUILD: https://github.com/BlackArch/blackarch/tree/master/packages/cuckoo

Are you sure you're not a wrong environment or something ?

**Comment by vdun** [comment]
I guess it needs this specific version of wakeonlan 0.2.2
https://github.com/cuckoosandbox/cuckoo/blob/master/setup.py#L219

I guess making the PKGBUILD install the dependencies in a virtualenv would fix the problem.

**Comment by noraj** [comment]
> I guess making the PKGBUILD install the dependencies in a virtualenv would fix the problem.

You're probably right but the whole packaging need to be changed.

**Comment by noraj** [comment]
Cuckoo has not made the python 3 upgrade between 2015 and 2020. Also more than 100 PR are opened. There are a hell of issues in cascade. Cuckoo is nearly dead, the few commits are not helping, it's starving to death slowly.

**Comment by D3vil0p3r** [comment]
Please close this issue
https://github.com/BlackArch/blackarch/blob/f7ebcc8661af436f0064bcd6e07a369594293c77/lists/broken#L35
