### ISSUE TITLE
New Tool

### ISSUE THREAD

**Issue by haroonawanofficial** [BlackArch/blackarch#2593]
We were already working on new tool so here it is, I am new to posting tools, so bear with me 

https://github.com/haroonawanofficial/flameapk
- Tool is updated according to your distro need

It have two files:
1. kali_installer
2. flameapk

Image links
----------------
1. https://camo.githubusercontent.com/51ecd70b8c681cd38f048dbcfb06f364a77e1fda/68747470733a2f2f692e6962622e636f2f346d59775079332f666c616d6561706b2e706e67
2. https://camo.githubusercontent.com/4cc32ed5c968b91eac704dbb4b9d297ccb331b6c/68747470733a2f2f692e6962622e636f2f767a4c6662436e2f666c616d6561706b322e706e67
3. https://camo.githubusercontent.com/4cc32ed5c968b91eac704dbb4b9d297ccb331b6c/68747470733a2f2f692e6962622e636f2f767a4c6662436e2f666c616d6561706b322e706e67
4. https://camo.githubusercontent.com/e96b5edd3983dae3091da1eae69d4cd39b5af617/68747470733a2f2f692e6962622e636f2f3267774b734a502f666c616d6561706b332e706e67
5. https://camo.githubusercontent.com/499ac7e81f835602ac3aa0bd124d1aef79b86466/68747470733a2f2f692e6962622e636f2f6a6b50374232592f666c616d6561706b342e706e67
6. https://camo.githubusercontent.com/e7f9255a4895c1b8d70c4902d5771fea403ab1a3/68747470733a2f2f692e6962622e636f2f446267745942392f666c616d65706b352e706e67
7. https://camo.githubusercontent.com/7270900857971301830b169eb49fb2df3307548a/68747470733a2f2f692e6962622e636f2f425a57793264362f666c616d6561706b352e706e67

Video Link:
https://streamable.com/s/mzt66/zprlaj

**Comment by noraj** [comment]
Feelings about it: https://github.com/BlackArch/blackarch/issues/2592

**Comment by haroonawanofficial** [comment]
If it can fit in Black Arch then good otherwse may be in future me and my members can work on true tool rated to this idea.

**Comment by noptrix** [comment]
@haroonawanofficial  ok ping us in future
