### ISSUE TITLE
Cuckoo PKGBUILD refactoring [Meta issue]

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2612]
- [ ] #2590 : Move to avirtual env as it requires exact dependencies versions
- [ ] #2559 : maybe check wrapper

**Comment by noraj** [comment]
Python3 move for Cuckoo was asked since 2015 (see https://github.com/cuckoosandbox/cuckoo/issues/594) and not started yet, the volume of commits the last years is very low, more than 100 PRs are opened, most issues get no answers. 
For me it's clear that cuckoo is a zombie project as good as abandoned.

**Comment by D3vil0p3r** [comment]
Close this issue
https://github.com/BlackArch/blackarch/blob/f7ebcc8661af436f0064bcd6e07a369594293c77/lists/broken#L35)

**Comment by noraj** [comment]
https://github.com/BlackArch/blackarch/commit/985d50180c633a67c19c54dfbc928f5376ab309c
