### ISSUE TITLE
Renaming blackarch-devtools

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2614]
What about moving https://github.com/BlackArch/blackarch/tree/master/packages/blackarch-devtools to another name so we can have **blackarch-devtools** for https://github.com/Edu4rdSHL/blackarch-devtools.

I wanted to package Edu4rdSHL/blackarch-devtools but the name is conflicting and I think blackarch-devtools is better suited for Edu4rdSHL tool than the actual one.

The change will have little impact:

```
/packages/blackarch-devtools/PKGBUILD:pkgname=blackarch-devtools
/scripts/arm-qemu/armv6/init.sh:   pacstrap -G -M -C root/etc/pacman.conf root base-devel devtools-alarm blackarch-devtools git vim
/scripts/arm-qemu/armv7/init.sh:   pacstrap -d -G -M -C root/etc/pacman.conf root base-devel devtools-alarm blackarch-devtools git vim
```

If you prefer not to rename the actual blackarch-devtools, what package name should to Edu4rdSHL/blackarch-devtools. We can still use `blackarch-devtools` in /urs/bin as the actual blackarch-devtools package does not have a blackarch-devtools binary.

What do you think @noptrix @Edu4rdSHL ?

**Comment by Edu4rdSHL** [comment]
Hello, I was talking with @noptrix about it before, we can simply rename my package to another thing but I don't have ideas how to call it, write here a good one and it will be added. :P

**Comment by noraj** [comment]
pkgname=blackarch-developer-toolkit

binary name: ba-dev

@Edu4rdSHL ?
