### ISSUE TITLE
SpiderFoot - Out-Of-Date

### ISSUE THREAD

**Issue by otisdog8** [BlackArch/blackarch#2622]
https://www.spiderfoot.net/spiderfoot-3-0-open-source-release/
Current repo version is 2.12 and newest version is 3.0
Repo: https://github.com/smicallef/spiderfoot

**Comment by noraj** [comment]
It has been totally moved to python 3 so the PKGBUILD need to serious upgrade:
https://github.com/BlackArch/blackarch/blob/master/packages/spiderfoot/PKGBUILD
