### ISSUE TITLE
[Tool request] socialscan

### ISSUE THREAD

**Issue by pranqster** [BlackArch/blackarch#2624]
Tool that offers accurate and fast checks for email address and username usage on online platforms.

Link: https://github.com/iojw/socialscan

**Comment by pranqster** [comment]
Any particular reason this was closed?

**Comment by noptrix** [comment]
> Any particular reason this was closed?

tool was added

**Comment by pranqster** [comment]
Was it renamed to something else? I didn't happen to see it when I searched the repos.

**Comment by noptrix** [comment]
@pranqster doh! sorry, we forgot to build the package. it was only available in the git repository. we just released it now :)

**Comment by pranqster** [comment]
Haha! No worries. Very much appreciated.

**Comment by noptrix** [comment]
> Was it renamed to something else? I didn't happen to see it when I searched the repos.
nope. it's `socialscan`:

`[ noptrix@blackarch-dev ~/blackarch/repos/blackarch/packages/socialscan ]$ ls
PKGBUILD`
