### ISSUE TITLE
Packages failing to build due to upstream issues

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2632]
PKGBUILD failing to build with `ba-dev -b` that I didn't have time to investigate:

- pcileech
- lanmap2

**Comment by Edu4rdSHL** [comment]
Hello. Going to look into it, thanks for reporting. Next time will be usefull if you attach `ba-dev` logs.

**Comment by noraj** [comment]
I'm working on https://github.com/BlackArch/blackarch/pull/2619#issuecomment-581075742, also the error output wasn't that explicit.

For `lanmap2`:

```
...
In file included from /usr/include/pcap.h:43,                                                                                                                                                                                                 
                 from cap.c:18:                                                                                                                                                                                                               
/usr/include/pcap/pcap.h:328:16: note: declared here                                                                                                                                                                                          
  328 | PCAP_API char *pcap_lookupdev(char *)                                                                                                                                                                                                 
      |                ^~~~~~~~~~~~~~
make[1]: *** [<builtin>: cap.o] Error 1
make[1]: Leaving directory '/build/lanmap2/src/lanmap2/src' 
make: *** [Makefile:7: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Build failed, check /home/noraj/blackarch_chroot/blackarch/build
Failed to build the package
```

**Comment by Edu4rdSHL** [comment]
Well, while investigating I've found (that both are upstream issues):

* pcileech

It's failing because the upstream source need to add compatibility with the linux-headers kernel for 5.5 releases. See https://github.com/ufrisk/pcileech/issues/111

* lanmap2

Another upstream issue, the program fails because due to conflicting types errors, means there's incompatibility of parameters/arguments type in declaration and definition of the function.

```
../tools/oui2insert < ../data/oui.txt | sqlite3 ./db
make[1]: Leaving directory '/tmp/lanmap2/db'
make -C tools
make[1]: Entering directory '/tmp/lanmap2/tools'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/tmp/lanmap2/tools'
make -C src
make[1]: Entering directory '/tmp/lanmap2/src'
cc -W -Wall -std=gnu99 -Wno-unused -ggdb -O0 -DDEBUG -Wno-unused-parameter   -c -o cap.o cap.c
cap.c:200:12: error: conflicting types for ‘listen’
 static int listen(void)
            ^~~~~~
In file included from /usr/include/pcap/socket.h:67,
                 from /usr/include/pcap/pcap.h:87,
                 from /usr/include/pcap.h:43,
                 from cap.c:17:
/usr/include/sys/socket.h:222:12: note: previous declaration of ‘listen’ was here
 extern int listen (int __fd, int __n) __THROW;
            ^~~~~~
cap.c: In function ‘listen’:
cap.c:209:7: warning: ‘pcap_lookupdev’ is deprecated: use 'pcap_findalldevs' and use the first device [-Wdeprecated-declarations]
       dev = pcap_lookupdev(errbuf);
       ^~~
In file included from /usr/include/pcap.h:43,
                 from cap.c:17:
/usr/include/pcap/pcap.h:328:16: note: declared here
 PCAP_API char *pcap_lookupdev(char *)
                ^~~~~~~~~~~~~~
make[1]: *** [<builtin>: cap.o] Error 1
make[1]: Leaving directory '/tmp/lanmap2/src'
make: *** [Makefile:7: all] Error 2
```
**Workarounds:**

* For `pcileech` we can just (for now) don't build the `pcileech_kmd/linux` module that according to the [project owner ](https://github.com/ufrisk/pcileech/issues/78#issuecomment-451482195)

> This module is only needed if you wish to pre-insert a pcileech module from the root account on the target system though. It's only needed when you wish to avoid scanning for the kernel, or when you are unable to scan for the kernel (32-bit <4GB limited USB3380 hardware device). Or it may also useful when you wish to avoid scanning if you have a slower device (such as DMA patched iLO).

When it's fixed in upstream ([see the bug report](https://github.com/ufrisk/pcileech/issues/111)), we can build it again.

* For `lanmap2` that repository isn't maintained since May, 2014 so I'm going to remove it.

**Comment by noraj** [comment]
@Edu4rdSHL Nice troubleshooting

**Comment by mrsmith0x00** [comment]
@noraj @Edu4rdSHL at that time it seems to be building and working fine.
