### ISSUE TITLE
ldapscripts: inconsistent PKGBUILD and Makefile

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2633]
At runtime, eg `ldapfinger`  or `ldapid`

```
/usr/lib/ldapscripts/runtime: line 733: /usr/etc/ldapscripts/ldapscripts.conf: No such file or directory
```

The runtime looks for `/usr/etc/ldapscripts/ldapscripts.conf` but in the PKGBUILD we did `mv "$pkgdir/usr/etc" "$pkgdir/etc"`.

This may help

```
$ grep -r 'ldapscripts.conf' ./ldapscripts-2.0.8
./ldapscripts-2.0.8/man/man5/ldapscripts.5:The main configuration of the ldapscripts is usually the file /etc/ldapscripts/ldapscripts.conf (or /usr/local/etc/ldapscripts/ldapscripts.conf, depending on your system). Modify it to fit your needs before using the scripts. You can override that default path by defining the LDAPSCRIPTS_CONF environment variable.
./ldapscripts-2.0.8/Makefile:ETCFILE = ldapscripts.conf
./ldapscripts-2.0.8/lib/runtime:_CONFIGFILE=${LDAPSCRIPTS_CONF:="/etc/ldapscripts/ldapscripts.conf"}
...
```

Also in the PKGBUILD: `make DESTDIR="$pkgdir" PREFIX="/usr" install`

![image](https://user-images.githubusercontent.com/16578570/73704570-c5ef1a00-46f3-11ea-8da6-6c43966a13a2.png)

So it's normal we have `/usr/etc/ldapscripts/ldapscripts.conf` instead of `/etc/ldapscripts/ldapscripts.conf`.

So either we do:

- sed `Makefile` in pre() to remove `$(PREFIX)` from `ETCDIR` and keep `mv "$pkgdir/usr/etc" "$pkgdir/etc"`. Which seems the right way to me.
- or we remove `mv "$pkgdir/usr/etc" "$pkgdir/etc"`

**Comment by Edu4rdSHL** [comment]
@noraj thanks for reporting and all your awesome work!

**Comment by noraj** [comment]
Great work @Edu4rdSHL
