### ISSUE TITLE
gcrypt - new repository

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2643]
The old repository is moved to https://github.com/GasparVardanyan/gcrypt_old_repo
The new repository is there: https://github.com/GasparVardanyan/gcrypt

**Comment by noraj** [comment]
@GasparVardanyan What did you changed? Only removed unneeded side-files ?

**Comment by GasparVardanyan** [comment]
@noraj I've removed commits history.

**Comment by GasparVardanyan** [comment]
And some changes in the code.
