### ISSUE TITLE
Show warning when run thefatrat

### ISSUE THREAD

**Issue by piug** [BlackArch/blackarch#2680]
- [X] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
I have installed blackarch linux but when I run "sudo ./fatrat" it makes me an error "this script require aapt to work" but the files do not containt setup.sh file

![image](https://user-images.githubusercontent.com/10526229/75744488-fcf82180-5cd9-11ea-8348-51ec42711ea7.png)

### Steps to reproduce
- cd /usr/share/thefatrat
- sudo ./fatrat
- Show in terminal:
[x]::[warning]:this script require aapt to work
 [!]::Run setup.sh to install aapt

### Screenshots
![image](https://user-images.githubusercontent.com/10526229/75744212-3e3c0180-5cd9-11ea-8b53-ef73f23a2b99.png)

### Info for developers

**GNU/Linux distribution:** Blackarch linux installed on top of arch linux
uname -r => 5.5.7-zen1-1-zen

**Comment by noptrix** [comment]
re-open this issue if not fixed.
