### ISSUE TITLE
[error] ncurses5-compat-libs breaks libtinfo.so.5

### ISSUE THREAD

**Issue by Focshole** [BlackArch/blackarch#2682]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
Installing ncurses5-compat-libs does not provide libtinfo.so.5, which instead should be provided (AUR package does it). 

### Steps to reproduce
- Install ncurses5-compat-libs

**Actual result:**  /lib64/libtinfo.so.5 is missing
**Expected result:** /lib64/libtinfo.so.5 should be present and working

### Info for developers

**GNU/Linux distribution:** Archlinux with blackarch repo properly installed

**Comment by noptrix** [comment]
@Focshole thank you! will be fixed
