### ISSUE TITLE
evil-winrm

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2701]
https://github.com/Hackplayers/evil-winrm

**Comment by aancw** [comment]
Nice! I hope this tools is available in blackarch repo.

**Comment by aancw** [comment]
I will try to build this package if you don't mind.

**Comment by noraj** [comment]
@aancw You're welcome to do it but be warned that it can be a complex task.

See existing examples:

- https://github.com/BlackArch/blackarch/tree/master/packages/fingerprinter
- https://github.com/BlackArch/blackarch/tree/master/packages/whatweb

**Comment by noptrix** [comment]
added

**Comment by noraj** [comment]
Thanks @aancw and @noptrix
