### ISSUE TITLE
hxd: Download from original source

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#2704]
Currently it is mirrored from https://github.com/mrsmith0x00/hxd.git (it should not be!)
https://github.com/BlackArch/blackarch/blob/c5a3bbe4b71ae9f9ac8448bd14671ece85273ff5/packages/hxd/PKGBUILD#L14

Instead, it can be done like this:
```
wget https://mh-nexus.de/downloads/HxDSetup.zip
unzip HxDSetup.zip
innoextract ./HxDSetup.exe
```

**Comment by aancw** [comment]
What's different?

**Comment by mrsmith0x00** [comment]
@vdun ok, I will move very soon

**Comment by mrsmith0x00** [comment]
@vdun fixed! :)

**Comment by vdun** [comment]
Thx @mrsmith0x00.
But, it is in german!
