### ISSUE TITLE
Error Running strap.sh

### ISSUE THREAD

**Issue by FernandoIV** [BlackArch/blackarch#2715]
After run `sudo ./strap.sh`:

`error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is unknown trust
error: failed to update blackarch (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases
`

I was trying answers in other issues but cant find a work one.

**Comment by aancw** [comment]
cc @noptrix

**Comment by ikstream** [comment]
@FernandoIV  have you checked the FAQ as well?

**Comment by noraj** [comment]
@FernandoIV https://blackarch.org/faq.html
![image](https://user-images.githubusercontent.com/16578570/78054999-3082a600-7383-11ea-9adf-6e7805a4065b.png)

**Comment by FernandoIV** [comment]
Thanks enveryone, I was checking My Sexy installation and I saw the date and time of My system and was wrong change that yo current and then run 'sudo pacman -Syyu' and that works for me.
