### ISSUE TITLE
Missing Dependency: Wine not found

### ISSUE THREAD

**Issue by dsxmachina** [BlackArch/blackarch#2718]
### Bug description
Hello there - am am trying to Install BlackArch on top of a fresh Arch Linux installation by following this instructions: https://blackarch.org/downloads.html#install-repo

However, `sudo pacman -S blackarch` and also `sudo pacman -Syyu --needed blackarch --overwrite='*'` result in a long output of unresolved dependencies.

### Steps to reproduce
`sudo pacman -S blackarch`

**Actual result:** 
warning: cannot resolve "lib32-openssl", a dependency of "checkpwd"
warning: cannot resolve "wine", a dependency of "extractusnjrnl"
warning: cannot resolve "wine", a dependency of "wine-gecko"
warning: cannot resolve "wine_gecko", a dependency of "extractusnjrnl"
warning: cannot resolve "wine", a dependency of "wine-mono"
warning: cannot resolve "wine-mono", a dependency of "extractusnjrnl"
warning: cannot resolve "lib32-nettle", a dependency of "gnutls2"
:: There are 4 providers available for opencl-driver:
:: Repository extra
   1) opencl-mesa  2) opencl-nvidia
:: Repository community
   3) beignet  4) intel-compute-runtime

Enter a number (default=1): 
warning: cannot resolve "wine", a dependency of "hxd"
warning: cannot resolve "wine", a dependency of "wine-gecko"
warning: cannot resolve "wine_gecko", a dependency of "hxd"
warning: cannot resolve "wine", a dependency of "wine-mono"
warning: cannot resolve "wine-mono", a dependency of "hxd"
warning: cannot resolve "wine", a dependency of "indx2csv"
warning: cannot resolve "wine", a dependency of "wine-gecko"
warning: cannot resolve "wine_gecko", a dependency of "indx2csv"
warning: cannot resolve "wine", a dependency of "wine-mono"
warning: cannot resolve "wine-mono", a dependency of "indx2csv"
warning: cannot resolve "wine", a dependency of "indxcarver"
warning: cannot resolve "wine", a dependency of "wine-gecko"
warning: cannot resolve "wine_gecko", a dependency of "indxcarver"
warning: cannot resolve "wine", a dependency of "wine-mono"
warning: cannot resolve "wine-mono", a dependency of "indxcarver"
warning: cannot resolve "wine", a dependency of "insanity"
warning: cannot resolve "lib32-gtk2", a dependency of "jd-gui"
warning: cannot resolve "lib32-libsm", a dependency of "jd-gui"
warning: cannot resolve "lib32-libxxf86vm", a dependency of "jd-gui"
warning: cannot resolve "lib32-zlib", a dependency of "android-sdk-build-tools"
warning: cannot resolve "android-sdk-build-tools", a dependency of "android-apktool"
warning: cannot resolve "android-apktool", a dependency of "kwetza"
warning: cannot resolve "wine", a dependency of "log-file-parser"
warning: cannot resolve "wine", a dependency of "wine-gecko"
warning: cannot resolve "wine_gecko", a dependency of "log-file-parser"
warning: cannot resolve "wine", a dependency of "wine-mono"
warning: cannot resolve "wine-mono", a dependency of "log-file-parser"
warning: cannot resolve "wine", a dependency of "mft2csv"
warning: cannot resolve "wine", a dependency of "wine-gecko"
warning: cannot resolve "wine_gecko", a dependency of "mft2csv"
warning: cannot resolve "wine", a dependency of "wine-mono"
warning: cannot resolve "wine-mono", a dependency of "mft2csv"
warning: cannot resolve "wine", a dependency of "mftcarver"
warning: cannot resolve "wine", a dependency of "wine-gecko"
warning: cannot resolve "wine_gecko", a dependency of "mftcarver"
warning: cannot resolve "wine", a dependency of "wine-mono"
warning: cannot resolve "wine-mono", a dependency of "mftcarv
[... it goes even further]

**Expected result:** 
Full BlackArch installation

### Info for developers
I can not install wine solely via pacman:
`sudo pacman -S wine` results in "error: target not found: wine"

**GNU/Linux distribution:** 
ArchLinux

**Comment by aancw** [comment]
Have you run strap.sh?

**Comment by ikstream** [comment]
You have to activate the `multilib` repo in your pacman config

**Comment by dsxmachina** [comment]
Yep, multilib solved it - thank you !
