### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by lytroths** [BlackArch/blackarch#2724]
i just switched to blackarch i wrote the command pacman -S blackarch then download everything and then i reboot and tried to run some tools but a message in the terninal was saying command not found
what should i do

**Comment by noraj** [comment]
@lytroths 

> i wrote the command pacman -S blackarch then download everything

Installing all 2500+ tools may not be the best solution.
It would be better to install only the categories you will use or only the tools you plan to use.

```
# To install a category of tools, run
$ sudo pacman -S blackarch-<category>

# To see the blackarch categories, run
$ sudo pacman -Sg | grep blackarch
```

> a message in the terninal was saying command not found

We can't help you if you don't show us what commands you tried to run.

**Comment by lytroths** [comment]
Any social media to contact

**Comment by noraj** [comment]
https://blackarch.org/community.html
Come asking on IRC or discord
