### ISSUE TITLE
Drozer can't find /usr/lib/libprotobuf.so.21

### ISSUE THREAD

**Issue by highjack** [BlackArch/blackarch#2730]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
When launching "drozer console" the application looks for a shared object file in the library path called "libprotobuf.so.21" which does not exist.

### Steps to reproduce
```
drozer console
Traceback (most recent call last):
  File "_drozer.py", line 30, in <module>
    __import__("drozer.cli.%s" % (sys.argv[1]))
  File "/usr/share/drozer/drozer/cli/console.py", line 8, in <module>
    from drozer.console import Console
  File "/usr/share/drozer/drozer/console/__init__.py", line 4, in <module>
    from drozer.console.console import Console
  File "/usr/share/drozer/drozer/console/console.py", line 5, in <module>
    from pydiesel.api.protobuf_pb2 import Message
  File "/usr/share/drozer/pydiesel/api/__init__.py", line 9, in <module>
    from pydiesel.api.frame import Frame
  File "/usr/share/drozer/pydiesel/api/frame.py", line 3, in <module>
    from pydiesel.api.protobuf_pb2 import Message
  File "/usr/share/drozer/pydiesel/api/protobuf_pb2.py", line 4, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: libprotobuf.so.21: cannot open shared object file: No such file or directory
```
### Workaround
This probably isn't the preferred method, but I was able to resolve the issue locally by symlinking /usr/lib/libprotobuf.so.21 to  /usr/lib/libprotobuf.so.22
```
sudo ln -s /usr/lib/libprotobuf.so.22 /usr/lib/libprotobuf.so.21
```

### Info for developers
**Tool version:** 2.4.4-2

**Comment by noptrix** [comment]
@highjack thank you! we will take over your quick'n'dirt workaround for now.

**Comment by leodahal4** [comment]
Still not working on mine system.

**Comment by Edu4rdSHL** [comment]
Please do not necro-bump issues, if the issue has been closed then open a new one but also the new error is different as it complains about `libprotobuf.so.23` and not `.21`.

I have fixed it in https://github.com/BlackArch/blackarch/commit/3a1a6bdb332a96133e1ccb2ee38e3a3af0a637fa but please report in a new issue in you find this problem again.
