### ISSUE TITLE
Why don't have  security and bug tracker on black arch? 

### ISSUE THREAD

**Issue by Kidman1670** [BlackArch/blackarch#2739]
I think a bug/security/CVE tracker for Black Arch will make this distribution more professional.

**Comment by ikstream** [comment]
If you have found any security issues with packages maintained by BlackArch, you can report them to team@blackarch.org.
Core packages, like the kernel however are not maintained by the BlackArch team. These are maintained by the arch linux developers, as the blackarch repo just sits on top of a regular arch install.

**Comment by noraj** [comment]
The github issue tracker is and issue tracker and the mail to report security ones about BA iteself. But all AL issues must be reported to AL and upstream issues to upstream projects.
