### ISSUE TITLE
Appmon missing dependecies

### ISSUE THREAD

**Issue by ikstream** [BlackArch/blackarch#2748]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
Appmon misses at least on dependecy based on the email we received earlier today
```
$ appmon 
Traceback (most recent call last):
  File "appmon.py", line 22, in <module>
    import database as db
  File "/usr/share/appmon/database/__init__.py", line 18, in <module>
    import dataset, json, time, htmlentities
  File "/usr/lib/python2.7/site-packages/dataset/__init__.py", line 3, in <module>
    from dataset.database import Database
  File "/usr/lib/python2.7/site-packages/dataset/database.py", line 3, in <module>
    from urllib.parse import parse_qs, urlparse
ImportError: No module named parse
```

**Comment by aancw** [comment]
Can you try it?

https://github.com/dpnishant/appmon/issues/99

**Comment by ikstream** [comment]
I installed and tested our package, but have no time to fix it myself atm. That's the reason for the issue

**Comment by aancw** [comment]
Okay. I will push change to that package.

**Comment by aancw** [comment]
AUR still using 1.1.2, but in BA is use 1.3.1

**Comment by noraj** [comment]
Upstream author answered with a joke https://github.com/dpnishant/appmon/issues/103#issuecomment-677021779

Also PR are rotting open, eg. https://github.com/dpnishant/appmon/pull/104

**Comment by blshkv** [comment]
upstream fixed both bugs, you can bump and close this bug
