### ISSUE TITLE
login screen, pressing esc on password keeps the text field in password mode

### ISSUE THREAD

**Issue by willmendil** [BlackArch/blackarch#2756]
Hi

Display bug on the login screen. In terms of setup, I followed to the letter https://blackarch.org/blackarch-install.html 

my distro is not luk encrypted. In terms of version I installed blackarch-linux-live-2020.01.01-x86_64 I installed this in vmware

```
$ uname -a
Linux black 5.6.8-arch1-1 #1 SMP PREEMPT Wed, 29 Apr 2020 16:22:56 +0000 x86_64
```

I type a random user,

![image](https://user-images.githubusercontent.com/8661949/80839989-a4bb9e00-8bfc-11ea-8c80-39ba3907395f.png)

When I press enter, i get the password field. Then I press esc because, let's say i typed the wrong user. And now the user field is in password mode, that means I cannot see what i type.

![image](https://user-images.githubusercontent.com/8661949/80840026-b0a76000-8bfc-11ea-9976-e198f05c4d2d.png)

Hope this is enough info

**Comment by Edu4rdSHL** [comment]
@mrsmith0x00 @noptrix is not this an lxdm issue rather than our issue?

**Comment by mrsmith0x00** [comment]
@willmendil I think that this is a lxdm issue. Please, could you write to Arch Linux bug tracker in details about that issue with lxdm? I think that their maintainers can fix that.
