### ISSUE TITLE
idb fails to install

### ISSUE THREAD

**Issue by The3Null4Player613310** [BlackArch/blackarch#2761]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
idb fails to install correctly

### Steps to reproduce
- install over existing copy of arch...
- pacman -S idb --fails to install

**Actual result:** 
idb fails to install and complains about icui8n not existing.
**Expected result:**
idb should install without problem.

### Info for developers
GNU/Linux distribution: Arch, Black Arch, Arch Strike
Tool version: idb-2.10.3-11

**Comment by The3Null4Player613310** [comment]
I am willing to potentially do the work to fix this.
Please notify me if there is anything you'd like me to do.

**Comment by aancw** [comment]
```
 ▲ ~/ sudo pacman -S idb
resolving dependencies...
looking for conflicting packages...

Packages (1) idb-2.10.3-11

Total Download Size:   0.18 MiB
Total Installed Size:  0.18 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 idb-2.10.3-11-x86_64                                 181.4 KiB  1259 KiB/s 00:00 [##############################################] 100%
(1/1) checking keys in keyring                                                    [##############################################] 100%
(1/1) checking package integrity                                                  [##############################################] 100%
(1/1) loading package files                                                       [##############################################] 100%
(1/1) checking for file conflicts                                                 [##############################################] 100%
(1/1) checking available disk space                                               [##############################################] 100%
:: Processing package changes...
(1/1) installing idb                                                              [##############################################] 100%
```

**Comment by aancw** [comment]
I'm experience different issue.
![image](https://user-images.githubusercontent.com/6284204/81574194-b3aa0980-93cf-11ea-81df-ae5aea35268c.png)

**Comment by ikstream** [comment]
just for documentation i will add the full output i get while trying to install idb
https://pastebin.com/kw7KgyFz

**Comment by aancw** [comment]
We need to include in broken package for idb?

**Comment by ikstream** [comment]
As it is broken, it should be added.

**Comment by The3Null4Player613310** [comment]
Saw [this](https://bugs.launchpad.net/ubuntu/+source/qt4-x11/+bug/989915) and it gave me an idea to try the command below.
`sudo ln -s /usr/lib/libicui18n.so.67.1 /usr/lib/libcui18n`
Just out of curiosity what would this do, and is there a better way to do this? 
I noticed I had a libicui18n.so file.

I'm installing now. \*fingers crossed\*

**Comment by aancw** [comment]
@The3Null4Player613310 can you post full log?

**Comment by The3Null4Player613310** [comment]
Seems to be a qtbindings issue...

> This is definitely a gcc version issue with newer versions of gcc (5+, and maybe even 4.6, though it seems they relaxed some things in later 4.x versions) of gcc not supporting the code generated by Smoke, in particular with creating derived classes with destructors for base classes that have private destructors. I'll see if I can recreate/fix next week. Unfortunately Smoke is no longer maintained, but hopefully this won't be too hard to fix.

more relevent info [here](https://github.com/ryanmelt/qtbindings/issues/146).

**Comment by The3Null4Player613310** [comment]
> @The3Null4Player613310 can you post full log?

Sure @aancw  you can find it [here](https://github.com/BlackArch/blackarch/files/4613570/idb_install_log.txt).

**Comment by aancw** [comment]
@The3Null4Player613310 so you have fixed icu error? That log is same with me.

**Comment by aancw** [comment]
Upstream issue: https://github.com/dmayer/idb/issues/111

**Comment by The3Null4Player613310** [comment]
@aancw haven't fixed yet, going to try an older version of gcc from the aur.

**Comment by The3Null4Player613310** [comment]
Actually went with a different approach and cloned the qtbindings repo and used rake and it compiled... going to play around with different versions to see what went wrong.

**Comment by The3Null4Player613310** [comment]
So the original compiled with no problem and after a bit of searching I found that it seems @shyouhei has already fixed it with this snippet in "qtbindings-x.x.x.x/ext/ruby/qtruby/src/qtruby.h"

> // Ruby 2.6 introduced an optimization which breaks QT compilation
>  // See https://github.com/ruby/ruby/commit/df9a70900a7380bc9b42b12ab90cf182988bcd45
>  // See also https://github.com/ruby/ruby/commit/8699a7a00655253ee9e4eedd55fbaea42f975788
>  #undef ALLOCA_N
>  #define ALLOCA_N(type,n) ((type*)alloca(sizeof(type)*(n)))

The newest version on GitHub works so you can probably just drop it in on line 47 of
.../ruby/2.7.0/gems/qtbindings-4.8.6.5/ext/ruby/qtruby/src/qtruby.h
until someone updates the stuff rubygems.org

**Comment by noraj** [comment]
upstream (qtbindings dep): https://github.com/ryanmelt/qtbindings/issues/157

qtbindings' author abandoned the project and won't maintain it.

**Comment by khang33k** [comment]
how to uninstall idb then? The default pacman -Rsn does not remove the ruby packages downloaded during install and the broken ruby built package.

**Comment by D3vil0p3r** [comment]
Close it once https://github.com/BlackArch/blackarch/pull/4325 has been merged
