### ISSUE TITLE
Installation on top ARCH  Key  verifiation failed, tried the FAQ but no help.

### ISSUE THREAD

**Issue by sk0x1234** [BlackArch/blackarch#2766]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Info for developers

**Device:** Manufacturer Model XVI (Only if you consideer needed, for example, network cards)
**GNU/Linux distribution:** (If you are using one distro that is not BlackArch, example: Manjaro, Anarchy, etc)
**Tool version:** 0.0.0

**Comment by ikstream** [comment]
As there is no info, what you have tried and what's your exact problem, I am going to close this. Please check closed and open issues, there are some with additional tips regarding key issues. Also check your time settings. Often it's a problem with time.

**Comment by sk0x1234** [comment]
Key provided inside scripts is not working.
http://pool.sks-keyservers.net/pks/lookup?search=4345771566d76038c7feb43863ec0adbea87e4e3&fingerprint=on&op=index
