### ISSUE TITLE
Blackarch Linux 2020.1.1 Installation

### ISSUE THREAD

**Issue by Ras7** [BlackArch/blackarch#2769]
Hi All
I tried to install blackarch along with win10 by writing Live Image on usb drive, after the installation completed without any error then I reboot the pc but there is no blackarch in the boot menu. it will directly boot to win10. I disabled secure boot.
Help me to resolve this issue I really appreciate it.  Thanks.

**Comment by noraj** [comment]
This is not a BA issue, either understand how to properly do a dual boot https://wiki.archlinux.org/index.php/Dual_boot_with_Windows or install BA in a VM.
