### ISSUE TITLE
Installer exits after failed encrypt password verification

### ISSUE THREAD

**Issue by duketwo** [BlackArch/blackarch#2771]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
Installation exits if the dm/luks password verification fails.

### Steps to reproduce
install with encryption on and enter two different passwords at the verification step

**Comment by Edu4rdSHL** [comment]
Hello, thanks for reporting. This issue should be fixed in the latest git version of https://github.com/BlackArch/blackarch-installer, please try again and let us know.
