### ISSUE TITLE
LAZY script

### ISSUE THREAD

**Issue by Nikolai201811** [BlackArch/blackarch#2772]
Добавьте пакет LAZY script из https://github.com/arismelachroinos/lscript

**Comment by noraj** [comment]
1. Please write in english
2. lscript project is a low quality wrapper around know tools already installed on BA, including it will be a pain and useless.

**Comment by Nikolai201811** [comment]
Linset doesn't work

ср, 27 мая 2020 г. в 02:21, Alexandre ZANNI <notifications@github.com>:

**Comment by noraj** [comment]
> Linset doesn't work

One more reason not to add it on BA.
