### ISSUE TITLE
Postgresql 

### ISSUE THREAD

**Issue by Dadoznights** [BlackArch/blackarch#2775]
Hello I am having problem while installing 
Postgresql  

When I open psql and type the command 
initdb -D /var/lib/postgres/data
I get this error 
Error while loading shared libraries: libicui18n.so.67 cannot open shared file object file :  no such file or directory initdb:
error: the program postgres is needed by initdb was not found in the same directory as /usr/bin/initdb. Check your installation.

Pleas help

**Comment by ikstream** [comment]
I can't recreate your problem, it worked for me with:
`su - postgres -c "initdb --locale en_US.UTF-8 -D '/var/lib/postgres/data'"`

Have you updated recently? 
Nevertheless postgress is not maintained by us. As this is an archlinux problem I am closing this issue.

**Comment by noraj** [comment]
@Dadoznights https://bugs.archlinux.org/?project=1&string=postgresql

**Comment by Dadoznights** [comment]
Thanks
It didn't work and I am going to arch linux
