### ISSUE TITLE
[Tool request] ntml_theft

### ISSUE THREAD

**Issue by nhs28** [BlackArch/blackarch#2786]
https://github.com/Greenwolf/ntlm_theft

**Comment by Edu4rdSHL** [comment]
This tool is already in our repos as `ntml-theft`.

**Comment by noraj** [comment]
@nhs28 Edu is right, please search before opening an issue:

```
$ curl https://blackarch.org/tools.html --silent | grep ntlm-theft
                                <td class=tbl-name itemprop="name">ntlm-theft</td>
```

[PKGBUILD](https://github.com/BlackArch/blackarch/blob/master/packages/ntlm-theft/PKGBUILD)

But @Edu4rdSHL it seems the package was never released on our repo.

```
$ pacman -Ss ntlm-theft
$ sudo pacman -S ntlm-theft
error: target not found: ntlm-theft
```

**Comment by Edu4rdSHL** [comment]
@noraj the package is already released. See http://ftp.halifax.rwth-aachen.de/blackarch/blackarch/os/x86_64/ntlm-theft-16.26d3213-1-any.pkg.tar.zst for example.

**Comment by noraj** [comment]
@Edu4rdSHL I must use an incomplete mirror. So this is why it's a pain not to have a mirror status tools like https://www.archlinux.org/mirrors/status/
