### ISSUE TITLE
VirtualBox random black screens on login!

### ISSUE THREAD

**Issue by PanosTrak** [BlackArch/blackarch#2788]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
I'm running blackarch on virtual box, imported from the ova!
That problem didn't existed in the first place.
When i boot normally i can only login with Openbox (the others show a black screen), if i boot with fallback initramfs i can login with the others.
The machine uses the VBoxSVGA with 3D Accelaration disabled!
I recently installed arandr (maybe that caused the problem idk)

### Steps to reproduce
I don't actually know!

### Info for developers
I can provide on request

### Link to debug log
I can provide on request

**Comment by noraj** [comment]
Since version 6.0.0 Virtualbox recommend to use `VMSVGA` and if you had no problem before installing `arandr` it's maybe due to it's installation that you have this problem, try to undo what you did.

**Comment by PanosTrak** [comment]
I have "-Rns'd" arandr but the problem still remains. Switching to `VMSVGA` doesn't fix the issue. I just realized that the this bug is random. Sometimes i can login, others times its just a black screen, so what I said before:

>  if i boot with fallback initramfs i can login 

does not apply!

**Comment by PanosTrak** [comment]
And by the way `VBoxSVGA` sets the resolution automatically, the other graphics controller don't!

**Comment by ikstream** [comment]
Have you installed anything else or enabled USB passthrough or special config, etc?
I rebooted the ova several times now and it didn't show up so far.

**Comment by PanosTrak** [comment]
> Have you installed anything else

If you mean on the guest OS, yes i have installed some packages and did a fully update but only the `arandr` is relevant to graphics/display from the packages that I installed! 
 
> or enabled USB passthrough 

I don't know what's this or how to enable it so my answer is no!

> or special config, etc?

Nope

And by the way i just checked that other tty's work!

**Comment by mrsmith0x00** [comment]
@PanosTrak did you encounter this bug earlier? Or just in this release? What OS you use on host? What is your VirtualBox version on the host? Did you only update the system and do nothing? Could you please answer this questions :)

**Comment by ikstream** [comment]
It was pointed out irc by @noptrix , that this is a known virtualbox issue and they are working on it.
see https://www.virtualbox.org/ticket/19640. A proposed solution is to downgrade to 6.1.8 of virtualbox-guest-utils and guest-dkms, or wait till 6.1.12

**Comment by PanosTrak** [comment]
@ikstream Yep that was the problem, I downgraded to 6.1.8 on both virtualbox-guest-utils and virtualbox-guest-dkms, tested 6 times and all test were successful! Thank you!
