### ISSUE TITLE
Some hacking harness aka reverse/bind shell fancy listener/handler

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2791]
- [ ] https://github.com/JusticeRage/FFM
- [ ] https://github.com/calebstewart/pwncat maybe waiting an answer for the naming issue https://github.com/calebstewart/pwncat/issues/18#issuecomment-647017243

**Comment by pwnfoo** [comment]
*bump*
> maybe waiting an answer for the naming issue calebstewart/pwncat#18 (comment)

This is a blocker because the author has refused to rename the tool. Got any ideas @noraj ?

**Comment by noraj** [comment]
@pwnfoo We can still name the package `pwncat-calebstewart` and the binary `pwncat-caleb` or something.
