### ISSUE TITLE
PyMISP no longer compatible with Python2

### ISSUE THREAD

**Issue by Brueggus** [BlackArch/blackarch#2797]
- [ x ] I have searched open and closed issues for duplicates
- [ x ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
python2-pymisp throws errors. PyMISP is no longer compatible with Python 2, starting with v2.4.120. See https://github.com/MISP/PyMISP/blob/main/README.md, IMPORTANT NOTE.

### Steps to reproduce
```
➜  ~ python2
>>> import pymisp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pymisp/__init__.py", line 26, in <module>
    from .abstract import AbstractMISP, MISPEncode, pymisp_json_default, MISPTag, Distribution, ThreatLevel, Analysis  # noqa
  File "/usr/lib/python2.7/site-packages/pymisp/abstract.py", line 46
    def _load_json(path: Path) -> Union[dict, None]:
                       ^
SyntaxError: invalid syntax
```

### Info for developers

**GNU/Linux distribution:** Arch
**Tool version:** 2.4.127

**Comment by noraj** [comment]
Both python3 and python2 are packaged, since python2 is deprecated and the upstream author also deprecated the python 2 version of is lib, we won't spend time fixing the python2 version. You should use the python3 version.
