### ISSUE TITLE
VBOX ON  BLACKARCH PROBLEM 

### ISSUE THREAD

**Issue by Dadoznights** [BlackArch/blackarch#2798]
HERE IS THE ISSUE

The vboxdrv kernel module is not loaded. Either there is no module
         available for the current kernel (5.4.6-arch3-1) or it failed to
         load. Please recompile the kernel module and install it by

           sudo /sbin/vboxconfig

         You will not be able to start VMs until this problem is fixed.

**Comment by noraj** [comment]
Last linux-lts is 5.4.49 not 5.4.6. To use virtualbox with lts kernel you must use the dkms driver and have linux hearder files etc.
There is no issue with BlackArch, virtualbox is a ArchLinux package and it's more probably a wrong config on your side.

See https://wiki.archlinux.org/index.php/VirtualBox
