### ISSUE TITLE
ssh-audit fork

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2802]
https://github.com/arthepsy/ssh-audit is not maintained since 2016, someone [forked it in 2019](https://github.com/jtesta/ssh-audit) and has release several versions since.

What do we do for [ssh-audit package](https://github.com/BlackArch/blackarch/blob/master/packages/ssh-audit/PKGBUILD)?

1. Do we just update `source`?
2. Or do do we create a `ssh-autdit2` package with the new fork? Since the original stopped at v1.7.0 and the fork began at v2.0.0

**Comment by ikstream** [comment]
If there is no breaking change against the original package i would say, we just change the the source.
If a feature was removed or otherwise not available anymore i would be for a new package.

**Comment by noraj** [comment]
@ikstream Reading the changelog there are only additions and fixs, no removal.
