### ISSUE TITLE
Pacman verify key

### ISSUE THREAD

**Issue by QairexStudio** [BlackArch/blackarch#2805]
Hi all my bros. im have pacman verify key issue. i was look "why do i get invalid keyring signature ?" subject from https://blackarch.org/faq.html here. but i can not fix it because i wasnt install strap.sh file. [https://ibb.co/5YJjGyG](url) how can setup it with succesfully thanks to help

**Comment by Edu4rdSHL** [comment]
Hello, what are you trying to do?

**Comment by QairexStudio** [comment]
> Hello, what are you trying to do?

Bro i want to do install package with pacman

**Comment by QairexStudio** [comment]
> Hello, what are you trying to do?

Also how can join developer team? What  can i do need to join? if developer allow to develop Black arch linux. i will develop it?

**Comment by Edu4rdSHL** [comment]
> Bro i want to do install package with pacman 

Has you tried: `pacman -Sy blackarch-keyring && pacman -Syu your_package`?

>  Also how can join developer team? What can i do need to join? if developer allow to develop Black arch linux. i will develop it?

You need to learn about ArchLinux development, making PPKGBUILDs, pacman and so on. See https://github.com/BlackArch/blackarch/blob/master/docs/HOWTO-DEV.md, plus https://github.com/Edu4rdSHL/blackarch-devtools will help you.

**Comment by QairexStudio** [comment]
> > Bro i want to do install package with pacman 
> 
> Has you tried: `pacman -Sy blackarch-keyring && pacman -Syu your_package`?
> 
> >  Also how can join developer team? What can i do need to join? if developer allow to develop Black arch linux. i will develop it?
> 
> You need to learn about ArchLinux development, making PPKGBUILDs, pacman and so on. See https://github.com/BlackArch/blackarch/blob/master/docs/HOWTO-DEV.md, plus https://github.com/Edu4rdSHL/blackarch-devtools will help you.

Thank you bro i know 8 programming language i will work very hard

**Comment by Edu4rdSHL** [comment]
Make sure `/var/lib/pacman/db.lock` isn't being used by another process (use fuser), if that isn't being used then delete the file, that will fix your issue.
