### ISSUE TITLE
Blackarch Close Bug

### ISSUE THREAD

**Issue by QairexStudio** [BlackArch/blackarch#2806]
Hello brother, I found an error in blackarch. After closing ctrl + c from the terminal, the program was not closed. I wrote the killall command, I tried the kill command but it didn't work.  [Photo](https://ibb.co/nrmCnG3)

**Comment by ikstream** [comment]
please provide console output, not images. If the output is to large, put it in a pastebin.

**Comment by QairexStudio** [comment]
> please provide console output, not images. If the output is to large, put it in a pastebin.

bro. No way out can only be understood by seeing. 
If you saw it, you understood that it would not be put on the satin console.

**Comment by ikstream** [comment]
os-prober is not maintained by blackarch.

**Comment by QairexStudio** [comment]
> os-prober is not maintained by blackarch.

bro
is there a similar package?

**Comment by noraj** [comment]
@QairexStudio The best for you is to install VirtualBox on Windows and install BlackArch in virtualbox. If you still want to dual-boot check [Dual boot with Windows](https://wiki.archlinux.org/index.php/Dual_boot_with_Windows).
