### ISSUE TITLE
Virtual Box run problem

### ISSUE THREAD

**Issue by QairexStudio** [BlackArch/blackarch#2808]
Hi all bros. i cant execute virtualbox why?
Output:
``/usr/lib/virtualbox/VirtualBox: /usr/lib/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/lib/virtualbox/VirtualBox)
/usr/lib/virtualbox/VirtualBox: /usr/lib/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/lib/virtualbox/UICommon.so)``

**Comment by noraj** [comment]
`pacman -Q virtualbox qt5-base`

**Comment by QairexStudio** [comment]
> Post the output of:
> 
> ```
> $ pacman -Q virtualbox qt5-base
> $ pacman -Ql qt5-base | grep -i LibQt5Core
> $ ls /usr/lib/libQt5Core.* -l
> ```
> 
> Did you forgot to reboot after a `pacman -Syu`?
> 
> @QairexStudio, there is an issue template, please don't ignore it.

thanks i trying it

**Comment by Edu4rdSHL** [comment]
@noraj it's a user problem because don't know how to use ArchLinux/Arch-based distros. He should learn how to do it instead of opening bugs everywhere.

@QairexStudio next time you open a unrelated bug you'll be banned from here. You were warned.
