### ISSUE TITLE
Java bytecode editors & decompilers

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2812]
- [x] Cafebabe #2815
  - https://grax.info/
  - https://github.com/GraxCode/Cafebabe
- [ ] ~~JByteMod #2816~~ tool is abandoned and not building
  - https://github.com/GraxCode/JByteMod-Beta
- [x] JBE
  - https://set.ee/jbe/
- [ ] JBytedit
  - https://github.com/Eyremba/JBytedit
- [x] reJ
  - http://rejava.sourceforge.net/

**Comment by D3vil0p3r** [comment]
#4226

**Comment by D3vil0p3r** [comment]
[reJ #4228](https://github.com/BlackArch/blackarch/pull/4228)

**Comment by D3vil0p3r** [comment]
This issue can be closed. [JByteMod is an abandoned project in favor of Cafebabe](https://github.com/GraxCode/JByteMod-Beta).
