### ISSUE TITLE
Installting Blarch via ISO > Dosen´t boot after installation < 7/24/2020

### ISSUE THREAD

**Issue by johndoeachtunddreizg** [BlackArch/blackarch#2817]
**Howdy mate ! - wanna be a hero today?**

I got a little hiccup one 2 of my "machines"...

**Topic:**
Installting Blarch via ISO > Dosen´t boot after installation <

**Lappy 1:**
Lenovo T60
x86_64
32-bit, 64bit
Little Endian
36 bit phy, 48 bit vir
Intel Core 2 CPU T7200 @ 2.0GHz
IDE Interface: Intel 82801G (ICH7 Family) IDE Controller (rev02)
BIOS: Lenovo V: 79ETE7WW (2.27)
SSD

**Li´lappy 2:**
Asus Eee Pc 1001P
x86_64
32-bit, 64bit
Little Endian
36 bit phy, 48 bit vir
Intel Core 2 CPU N450 @ 1.66GHz
IDE Interface: Intel NM10/ICH7 
HDD

_If you ask me for the Kernelversion of each Lap, i can only offer you the
[uname -a] at the moment of installation - before shutdown :)_

**Bullet points:**
- Latest ISO.
- Walkthrough every single step - exactly as recommended.
- Everything fine until [shutdown now]
- Unplug flash drive > Start Lappy > Result at each time:

**Starting version 245.6-8-arch
/dev/sda3: clean, 61566/7249920 files, 1202087/28990326 blocks**

- Staion Six - Sahara...No more sign of life.
~
- Attempted for around 10 times on each Lappy - with the same result.
  ([c], [e], [ctrl-alt-F2], [Blarch Bootmenu ] works btw.)
~
- Afer that i started with dozens variations of the installing procedure, like:
- Install online and offline.
- With and without [LUKS] (with LUKS it asks for pw during the boot, of course).
- With and without [dos] label type.
- Add an empty partition in front of boot* - cuz of the [dos] counting method.
- Reinstall blackman & grub before shutdown.
- Tried to confuse the boot due to some terms i found netwise.
- Watched any YT-Tutorial.
- Learned Hindi.
- Watched even more turorials.
- ...and combined all the variation above.

NOTHINGNESS...

I still think it´s a noobistic fallacy - Any idea?
Slowly getting desperate...

**Comment by ikstream** [comment]
What's your installer version?

**Comment by johndoeachtunddreizg** [comment]
Hi ikstream,
**thanks for your reply.**

The installtion to the flash-drive went thru:
$ sudo dd bs=512M if=file.iso of=/dev/sdb
(no rufus involved)

The Blarch-ISO-Version is: 2020.06.01
Last Linux on both machines was MX with latest updates.

**But somehow i think that was not your question :)**
(Hab sone Antwort befürchtet, mein Gutster)

Wkr
Josh

**Comment by ikstream** [comment]
It's more about the version of the script you used to install BA to your machines.
What's the output of
`pacman -Qs blackarch-installer`

Did you run `pacman -Sy  blackarch-installer` before the install? If not, please do so and try again.

**Comment by johndoeachtunddreizg** [comment]
Trying to follow your advise...

The path was:
**[ blackarch/ ]# sudo pacman -S blackarch-installer**   
{as recommended in the Blarch-Guide, with the result:}
warning: database file for ´core´ does not exist (use ´-Sy´ to download)
warning: database file for ´extra´ does not exist (use ´-Sy´ to download)
warning: database file for ´community´ does not exist (use ´-Sy´ to download)
warning: database file for ´multilib´ does not exist (use ´-Sy´ to download)
warning: database file for ´blackarch´ does not exist (use ´-Sy´ to download)
error: target noot found: blackarch-installer

**[ blackarch/ ]# pacman -Sy** 
error: failed retrieving file ´multilib.db´from mirror.xxx.xxx : Could not resolve host: mirror.xxx.xxx
(This message repeated itself for around 180 times with different hosts. Followed by:)
error: failed to retrieving file ´blackarch.db´ from www.blackarch.org : could not resolve host: www.blackarch.org
error: failed to update blackarch
error: failed to sychronize all databases

**[ blackarch/ ]# pacman -Qs blackarch-installer**
warning: database file for ´core´ does not exist (use ´-Sy´ to download)
warning: database file for ´extra´ does not exist (use ´-Sy´ to download)
warning: database file for ´community´ does not exist (use ´-Sy´ to download)
warning: database file for ´multilib´ does not exist (use ´-Sy´ to download)
warning: database file for ´blackarch´ does not exist (use ´-Sy´ to download)
local/blackarch-installer **1.1.45-1**
	The official BlackArch Linux installer.

**Then came a lightbulb - shining above my head!**

I started the installation (done as hundered times before),
until the point [>>Network Setup].
There i hit [1.] as always. 
At this point Blarch usually kicked my out 2 or 3 times until the installtion procedure was ongoing.
In the monent of  "ongoing installation" i stopped the process [ctrl c] and went back to:
**[ blackarch/ ]# sudo pacman -S blackarch-installer**
&
**[ blackarch/ ]# pacman -Qs blackarch-installer**
local/blackarch-installer **1.2.1-1**
	The official BlackArch Linux installer.
&
**[ blackarch/ ]# sudo blackarch-install**
&...
...
...
Until:
**[+] BlackArch Linux installation successfull!**
Yo noob...
./sbin/blackarch-install: line 2374: 0: command not found
/sbin/blackarch-install: line 2370: [. -ne unary operator expected
Hack the...

[shutdown now]
- Unplug flash drive > Start Lappy > **but still:**

**Starting version 245.6-8-arch
/dev/sda3: clean, 59690/7135232 files, 12000752/28518518 blocks**

No Happy Lappy...maybe i should read a book about gardening.

**Comment by johndoeachtunddreizg** [comment]
Trying to follow your advise...,
this time exact with:
pacman -Sy blackarch-installer
and the rest of the story...

But still the same result - dosent boot...
Sorry!

**Comment by Edu4rdSHL** [comment]
You aren't giving useful information. If you want more support please go to Discord (https://discord.gg/KMVkKDN) or IRC (#BlackArch on Freenode), I'm unable to reproduce your issue.

**Comment by johndoeachtunddreizg** [comment]
Dear ikstream & Edu4rdSHL,

thank you for your quick and useful answers!

Blarch is not projected for the noobs :)
I plunged into the world of Linux just 6 month ago and have to dig a bit more on the basics.
I gave you all the information i could reconstruct - It was not my idea to waste your time - Sorry!

**All the best an stay well!**

**Comment by johndoeachtunddreizg** [comment]
Update:
**S O L V E D !**

After some hours of "off topic" i restarted the installation, again with [blackarch-installer 1.2.1-1] and:
**VICTROY!**

Dear ikstream:
Somewhere, Sometime, Someone
will donate you a icecold bottle of bear - take it :)

wkr Josh
