### ISSUE TITLE
[Tool Request] GNU GCC PowerPC Toolchain

### ISSUE THREAD

**Issue by Rubonnek** [BlackArch/blackarch#2818]
It would be awesome to have precompiled gcc cross compiler for PowerPC targets.

**Comment by Edu4rdSHL** [comment]
@Rubonnek we are a hacking distro, not a development one. Sorry.

**Comment by Rubonnek** [comment]
Looks like we have very different definitions of what hacking then means -- I'll just grab the precompiled tools from another distro.
