### ISSUE TITLE
[Tool Request] Evine

### ISSUE THREAD

**Issue by saeeddhqan** [BlackArch/blackarch#2820]
Evine is a simple, fast, and interactive web crawler and web scraper written in Golang. Evine is useful for a wide range of purposes such as metadata and data extraction, data mining, reconnaissance, and testing.

[evine](https://github.com/saeeddhqan/evine
)

**Comment by noraj** [comment]
closed by 9c3c6ccb5f475f3f0faf669abfeb1899219dc804
