### ISSUE TITLE
tishna

### ISSUE THREAD

**Issue by Ko4X** [BlackArch/blackarch#2825]
[Tishna-master.zip](https://github.com/BlackArch/blackarch/files/5024200/Tishna-master.zip)
Nice Framework

**Comment by noraj** [comment]
I fear we won't add this too (https://github.com/mikolz94/Tishna-Automated-Web-Application-Hacker), it seems to be yet another poorly written wrapper around existing tools.

**Comment by Ko4X** [comment]
The tool is awsome. ask to the developper if i can share it before doing so... this is not My tool.  Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by noraj** [comment]
No this kind of stuff is redundant and will bring nothing more:

`fux.sh`

```bash
#!/bin/bash
echo -ne "[+] Enter Target: "
read target
echo -ne "[+] Enter File Type: "
read filetype
python3 fuxploider.py --url $target --not-regex "wrong file type"
python3 fuxploider --url $target/$filetype --not-regex "error" --template phpinfo
```

`lfi.sh`

```bash
#!/bin/bash
echo -ne "[+] Enter Target /w Parameter: "
read target
./lfi.py --url=$target
```

We will not add this tool.
