### ISSUE TITLE
Infection Monkey

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2827]
- **Name**: Infection Monkey
- **Source URL**: https://sourceforge.net/projects/infection-monkey.mirror/

**Comment by noptrix** [comment]
@noraj any news on this? if not let's close it please

**Comment by noraj** [comment]
> @noraj any news on this? if not let's close it please

no a tool request I opened on behalf of someone else

**Comment by D4imyo** [comment]
i am working on it
