### ISSUE TITLE
PhanTap

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2828]
- **Name**: PhanTap
- **Source URL**: https://github.com/nccgroup/phantap

**Comment by H8to** [comment]
Seems it has been added.
```
blackarch/phantap 57.fb3be84-1 [blackarch blackarch-networking]
    An 'invisible' network tap aimed at red teams.
```
The documentation is for OpenWRT only though. 
If you manage to add a pull request to the original project for Arch instructions this would be appreciated. :1st_place_medal:
