### ISSUE TITLE
I have blackarch install on my laptop after booting today morning I am having problem login. Whenever I enter the credentials it goes to login loop. i have an extra user other than root. I have tried with every WMs and every credentials. I updated my system yesterday. Need Help ASAP!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by samspei0l** [BlackArch/blackarch#2837]
I have blackarch install on my laptop after booting today morning I am having problem login. Whenever I enter the credentials it goes to login loop. i have an extra user other than root. I have tried with every WMs and every credentials. I updated my system yesterday. Need Help ASAP!!!!!!!!!!!!!!

_Originally posted by @samspei0l in https://github.com/BlackArch/blackarch/issues/1820#issuecomment-680583560_

**Comment by ikstream** [comment]
As I said before, this is most likely related to #2835. Did you try the things recommended there?
I am going to close this for now as duplicate. If it is not related to the issue, feel free to reopen this issue.
