### ISSUE TITLE
Pacman update error, tried several methods but still failed,please

### ISSUE THREAD

**Issue by Manipulator-shadow** [BlackArch/blackarch#2840]
Type: Question

## Question

pacman -Syyu

Then

error:GPGME error: No data
: :Synchronizing package databases . . .
core  100%
extra 100%
community 100%
multilib 100%
error failed retrieving file 'blackarch.db' from mirrors.****.***.** :The requested URL returned error :404
failed to update blackarch(failed to retrieve some files)
error:failed to synchronize all databases

I have tried to change many mirror sources, but it still doesn't work. I have modified pacman.d and pacman.conf and pacman.d/ Blackarch-mirrorlist, but it still doesn't work ,Who can solve this problem? Thanks.

**Comment by Manipulator-shadow** [comment]
There is so little information about Blackarch on the Internet. Oh, my god

**Comment by Manipulator-shadow** [comment]
There is so little information about Blackarch on the Internet. Oh, my god

**Comment by ikstream** [comment]
Are you trying to install Blackarch on something else than aarch64/x86_64?

**Comment by Manipulator-shadow** [comment]
> 您是否正在尝试在aarch64 / x86_64以外的其他版本上安装Blackarch？

Thank you very much for your answer but I installed BlackArch on VMware Workstation

**Comment by Manipulator-shadow** [comment]
> 您是否正在尝试在aarch64 / x86_64以外的其他版本上安装Blackarch？



> Are you trying to install Blackarch on something else than aarch64/x86_64?

Thank you very much for your answer but I installed BlackArch on VMware Workstation，thank you

**Comment by Manipulator-shadow** [comment]
> Are you trying to install Blackarch on something else than aarch64/x86_64?

Thank you very much for your answer but I installed BlackArch on VMware Workstation，thank you

**Comment by Manipulator-shadow** [comment]
> Are you trying to install Blackarch on something else than aarch64/x86_64?

BlackArch has not been installed anywhere else thank you

**Comment by Edu4rdSHL** [comment]
@Manipulator-shadow please paste the FULL error, not ` error failed retrieving file 'blackarch.db' from mirrors.*..** :The requested URL returned error :404` because that means nothing. Also, how do you "installed" BlackArch? Using the live ISO, Netinstall, on top of ArchLinux, from the OVA image?
