### ISSUE TITLE
Read this, before posting new tool request!

### ISSUE THREAD

**Issue by ghost** [BlackArch/blackarch#2842]
### Reasons for closing or having closed a tool request:
1. It is a simple wrapper for another tool, for example, a wrapper for Nmap that merely calls the program with pre-configured keys.
2. The tool is very outdated or no longer supported by its developers, which often creates dependency problems for other projects.
3. The tool has a broken build, relies on complex variables, or is highly dependent on a specific GNU/Linux distribution (not Arch Linux).
4. The tool is based on Python 2, and Python 2 support has ended, leading to issues with its dependencies.
5. The tool duplicates the functionality of existing tools and can be entirely replaced by a more popular and supported product.
6. Utilities related to anonymization or various scripts for launching free VPNs are not necessary since we provide [torctl](https://github.com/BlackArch/torctl)
7. Any tools related to illegal or unethical activities, such as brute-forcing Facebook accounts or conducting Denial of Service (DOS) attacks, will not be added.
### Please read this carefully before submitting a new tool request!

**Comment by saltasatelites** [comment]
Blakarch has lots of tools with python2 dependencies. Sure the devs have think about that, but I suposse is a huge work.

**Comment by noraj** [comment]
I put it in the issue template instead: https://github.com/BlackArch/blackarch/commit/4cb8df0800e37ef36384f917439b48ee960ec0dd
