### ISSUE TITLE
Kernel panics and freezes virtualbox-dkms

### ISSUE THREAD

**Issue by bitshiftnetau** [BlackArch/blackarch#2843]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Seemingly random kernel panics with virtualbox-dkms linux-lts when running up any virtual machine in virtualbox. Instantly reproducible when running netdiscover. 

### Steps to reproduce

- install system using BlackArch usb installer
- install xorg and i3
- install virtualbox-dkms (reboot)
- run up any virtual machine (tested with blanks, metasploitable, and kioptix Lv1&2)
- run netdiscover -r 192.168.x.x/24 /16, or nmap or just wait a while.
- observe either a freeze or full kernel 

**Actual result: kernel panic or freeze

**Expected result: smooth running of a system 

### Info for developers

**Device:** 
Lenovo T410
Kernel: 5.8.3-arch1-1
Legacy BIOS
MBR

**GNU/Linux distribution:** BlackArch

**misc:
- have run up memory checks with HirensBoot, everything is clean
- did a fresh install of ArchLinux using the same kernel and desktop configs, same VM, netdiscover from the AUR, ran just fine when doing steps to reproduce.
- yes, virtualization is on in BIOS. 

### Link to debug log

Not possible as freeze and/or kernel panic

**Comment by Edu4rdSHL** [comment]
What do you have in logs? The packages you have installed are managed by ArchLinux developers, so they should have the same behavior. Please provide more information about the error (journal).

**Comment by bitshiftnetau** [comment]
It's interesting you mention that, because there are other things that they don't share the same behaviour with a normal Arch installation. 

There is nothing inside the journal related to the freeze.

**Comment by Edu4rdSHL** [comment]
Which things doesn't have the same behavior? Please again, be more explicit, if we don't have any info we can't help you as we can't reproduce that issue internally as well.

**Comment by bitshiftnetau** [comment]
I've already raised 'other things' in bugs. Let's just focus on this issue.

**Comment by Edu4rdSHL** [comment]
I didn't get your point, when you have more info please go back and I will reopen the issue.

**Comment by bitshiftnetau** [comment]
No thanks. Think I'm done with you lot. 

The most unhelpful lot of wankers I have ever encountered. Have a shitty day asshole.
