### ISSUE TITLE
Fix docs for installing on top of Arch

### ISSUE THREAD

**Issue by bitshiftnetau** [BlackArch/blackarch#2844]
In the docs it says

"# Run https://blackarch..../strap.sh as root and follow instructions", but the line after that is using curl to check the file. 

The code line should be:

`wget https://blackar..../strap.sh`

Not

`curl -O https://blackar.../strap.sh`

Also when installing blackarch on top of Arch Linux, I had to manually enable the multilib repo and update with -Syy. This is expected as blackarch contains some 32b tools.

This step should be recorded in the docs before running pacman -S blackarch

E.g. 

"# Enable multilib repo in pacman.conf:"
`vim /etc/pacman.conf`

"# Uncomment the following lines:"

```
# [multilib]
# Include = /etc/pacma....
```

**Comment by Edu4rdSHL** [comment]
The `wget` and `curl` comparison that you have made doesn't make sense and multilib is optional.

**Comment by bitshiftnetau** [comment]
If you're instructing people to get a file then not giving them the correct command, that is bad docs. 

Even just add an output pipe into a strap.sh file would suffice. Just something that is consistent with the instruction description. 

The only thing the current command does is output the text file to the shell. 

If multilib is optional then document that so people aren't wondering about errors when installing 5000 packages.

**Comment by Edu4rdSHL** [comment]
No, it doesn't, you executed curl without the -O argument, that's why you just have the output in your terminal and not in a file and also `multilib` is already enabled by the installer. See [here](https://github.com/BlackArch/blackarch-installer/blob/3a7e6ffeb19e6f5077ba89dd517f40bd6999e47b/blackarch-install#L506-L537).

**Comment by bitshiftnetau** [comment]
That's because the -O flag is what you have written in the docs. 

Mate this isn't difficult to understand. Document the commands as they are supposed to be executed. Simple.

I'm not asking you to stand on your head and juggle. Just improve the docs.

These instructions are for installing on top of an existing Arch system where the multilib is NOT enabled. This has nothing to do with the BlackArch installer.

**Comment by Edu4rdSHL** [comment]
> That's because the -O flag is what you have written in the docs.

Yes, and that's how this should be executed, you executed it without -O.

> These instructions are for installing on top of an existing Arch system where the multilib is NOT enabled. This has nothing to do with the BlackArch installer.

We will consider it.
