### ISSUE TITLE
New Mirror For BlackArch

### ISSUE THREAD

**Issue by youds** [BlackArch/blackarch#2847]
Hi

I’m reaching out today to offer my mirror for your infrastructure/website. We are committed supporting open-source projects and BlackArch is suitable under that description.

URL for the mirror access points to follow:
 - http://mirrors.gethosted.online/blackarch
 - https://mirrors.gethosted.online/blackarch
 - ftp://mirrors.gethosted.online/blackarch
 - rsync://mirrors.gethosted.online/blackarch

Location: Great Britain

The mirror has been accepted in the past however as there is no change on the website I was hoping to find a resolution.

**Comment by Edu4rdSHL** [comment]
Hey @youds, thank you!

**Comment by youds** [comment]
Hi

My BlackArch mirror needs reinstating. Instead of using a dedicated server provider we have bought our own hardware and now have it setup with high bandwidth capacity at a colocation in Rothwell, UK. Can the mirror be reinstated on your website?

Kind regards

**Comment by aancw** [comment]
Just to make sure, the repo url and domain is still same? Only server location is changed?

**Comment by youds** [comment]
Hi

Yep, everything remained the same, apart from location.


Courtesy of Youds Media Limited

Contact:
Office: +441200 422 533
Web: http://www.youds.com/ <http://www.youds.com/>
Email: ***@***.***

**Comment by youds** [comment]
Hi

Hoping to get this resolved, any chance of the website being updated? 

Kind regards


Courtesy of Youds Media Limited

Contact:
Office: +441200 422 533
Web: http://www.youds.com/ <http://www.youds.com/>
Email: ***@***.***

**Comment by aancw** [comment]
Yeah, we will let u know when it's updated.
