### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sonuishaq67** [BlackArch/blackarch#2849]
Type: Question

## Question
Installing black arch on top of clean newly installed arch linux
Selected all repositories 
End of installation I get this error 
![Screenshot from 2020-09-15 15-07-47](https://user-images.githubusercontent.com/55189255/93194464-bd6cc080-f765-11ea-9d03-cbc3d07e048d.png)

Any workaround for this?

**Comment by roptimizer** [comment]
@sonuishaq67 read FAQ section first: ```--overwrite '*'```
