### ISSUE TITLE
[Tool request] Lockdoor Framework

### ISSUE THREAD

**Issue by SofianeHamlaoui** [BlackArch/blackarch#2850]
- **Name**: Lockdoor Framework : A penetration testing framework with cyber security resources
- **Source URL**: https://github.com/SofianeHamlaoui/Lockdoor-Framework

#### The framework was selected as  "The Best Pack Of Tools For Cyber Security Students" by [The Shadow Brockers](https://en.wikipedia.org/wiki/The_Shadow_Brokers)

![TSB](https://mybe.online/wp-content/uploads/2020/06/1591236813_maxresdefault-750x375.jpg)
> ( The old video was deleted due to their Youtube channel, the old link is here : https://www.youtube.com/watch?v=6njKRrKQtow )

### You can also check the articles about the Framework from multiple blogs in different languages: 

**-  [English]** : 
- Kitploit : https://www.kitploit.com/2019/10/lockdoor-framework-penetration-testing.html

- KaliLinuxTutorials : https://kalilinuxtutorials.com/lockdoor-framework-penetration-testing-framework-cyber-security/

 - KaliLinuxTR : https://toolbox.kali-linuxtr.net/lockdoor-framework-a-pentesting-framework-with-cyber-security-resources.tool
- GitHackTools : https://githacktools.blogspot.com/2019/09/lockdoor-framework-pentesting-framework-with-cyber-security-resources.html
- AllAboutHack : https://allabouthack.com/lockdoor-framework-a-penetration-testing-framework-with-cyber-security-resources/
- xPloitLab :  https://xploitlab.com/lockdoor-framework-penetration-testing-framework-with-cyber-security-resources/
- CrackItDown : https://www.crackitdown.com/2019/11/lockdoor-best-pack-of-tools-for-cybersecurity-students.html
- and more ....

**- [Chinese]** : 
- Tencent : https://cloud.tencent.com/developer/article/1535075
- Chainnews : https://www.chainnews.com/zh-hant/articles/700142833654.htm
- CSDN : https://blog.csdn.net/u012206617/article/details/102934172
- and more ....

**- [Russian]** : 

- Dfir : http://dfir.pro/index.php?link_id=98576 

**- [Spanish]** : 

- Telegram : 
![](https://i.imgur.com/pVAc3s8.png)

**- [German]** : 
- tSecurity : https://tsecurity.de/de/881850/Cybersecurity/Cybersecurity-Nachrichten/Lockdoor-Framework-A-Penetration-Testing-Framework-With-Cyber-Security-Resources/

**- [Portuguese]** : 
- FullCrypters : https://fullcrypters.net/lockdoor-framework-um-framework-de-teste-de-penetracao-com-recursos-de-seguranca-cibernetica/

**- [Indian]** :
- OneHack : https://onehack.us/t/lockdoor-the-best-pack-of-tools-for-cyber-security-students/63799

**- [Arabic]** : 
- A Facebook Page : https://www.facebook.com/www.mathet.info/posts/2909739469070978

**Comment by SofianeHamlaoui** [comment]
The tool is available on the AUR here : https://aur.archlinux.org/packages/lockdoor/ and tested on Archlinux, Debian, Ubuntu,Opensuse, CentOS, MacOs and Windows.
Also available for a docker container on dockerhub : https://hub.docker.com/r/sofianehamlaoui/lockdoor

**Comment by ikstream** [comment]
This seems like a nice tool for non pentesting distributions. But I don't see how this will add value to a pentesting distribution, which already provides all (or at least most) of the tools your framework provides.

If you think i am wrong, feel free to correct me.

**Comment by SofianeHamlaoui** [comment]
@ikstream Hello, I hope you are doing good.

The framework doesn’t only contain the tools, it does automatisation means it will ask for your targets, number of actions or verbose mode for example (it depends on each tool) and just make it easier to use those tools.

Also, it helps a lot with the resources it contains as it has cheatsheets, some pdf and images to help you with your penetration testing process that you can check on each category of the used tool.

What I can do, is as the tools on this framework are already installed on Blackarch, I can make a Blackarch version of it.

But honestly, besides that it’s customizable, automatize and contains resources that can help the Penetration Testing process easier, I don’t see with what else it can help.

Thank you for your answer @ikstream

**Comment by SofianeHamlaoui** [comment]
> This seems like a nice tool for non pentesting distributions. But I don't see how this will add value to a pentesting distribution, which already provides all (or at least most) of the tools your framework provides.
> 
> 
> 
> If you think i am wrong, feel free to correct me.
