### ISSUE TITLE
Can't install blackarch group via pacman. Reason: "/usr/bin/witnessme exists in both 'python-witnessme' and 'witnessme'"

### ISSUE THREAD

**Issue by rumanzo** [BlackArch/blackarch#2851]
I try to install blackarch with Netinstall ISO
```
[ blackarch / ]# pacman -S blackarch
:: There are 2577 members in group blackarch:
:: Repository blackarch
...
Total Installed Size:  48036.56 MiB
Net Upgrade Size:      48023.45 MiB

:: Proceed with installation? [Y/n]
(5015/5015) checking keys in keyring                                                                             [####################################################################] 100%
( 858/5015) checking package integrity                                                                           [#################---------------------------------------------------]  26%
(5015/5015) checking package integrity                                                                           [####################################################################] 100%
(5015/5015) loading package files                                                                                [####################################################################] 100%
(5015/5015) checking for file conflicts                                                                          [####################################################################] 100%
error: failed to commit transaction (conflicting files)
/usr/bin/witnessme exists in both 'python-witnessme' and 'witnessme'
Errors occurred, no packages were upgraded.
```

**Comment by noraj** [comment]
BA repo provides only [python-witnessme](https://github.com/BlackArch/blackarch/blob/master/packages/python-witnessme/PKGBUILD) package and no witnessme package. There is no `witnessme` package in ArchLinux or AUR.
If you have a conflict for `/usr/bin/witnessme` it can only be because you installed the pip package system-wide which is a terribly wrong practice that always end in conflicts like you just experienced.

About pip package you have several options:

- never install pip package (recommended)
- install in a virtual environment (native venv, pyenv, virtualenv, etc.)
- install in a user directory with the `--user` flag

Try a `sudo pip uninstall witnessme` and then try again `sudo pacman -S python-witnessme`

**Comment by rumanzo** [comment]
> BA repo provides only [python-witnessme](https://github.com/BlackArch/blackarch/blob/master/packages/python-witnessme/PKGBUILD) package and no witnessme package. There is no `witnessme` package in ArchLinux or AUR.
> If you have a conflict for `/usr/bin/witnessme` it can only be because you installed the pip package system-wide which is a terribly wrong practice that always end in conflicts like you just experienced.
> 
> About pip package you have several options:
> 
> * never install pip package (recommended)
> * install in a virtual environment (native venv, pyenv, virtualenv, etc.)
> * install in a user directory with the `--user` flag
> 
> Try a `sudo pip uninstall witnessme` and then try again `sudo pacman -S python-witnessme`

It's clean setup. Installer user pip?

**Comment by noraj** [comment]
There is no `witnessme` package so I wonder which other package than `python-witnessme` could provide `/usr/bin/witnessme`.

**Comment by Edu4rdSHL** [comment]
Looks like that `witnessme` was not removed from repo DB/mirrors.

```
└─▶ pkgfile witnessme
blackarch/python-witnessme 1:1.5.0-1	/usr/bin/witnessme
blackarch/witnessme 32.4a87653-1    	/usr/bin/witnessme
```
The commit will avoid this problem but also fix existing installations.
