### ISSUE TITLE
[Tool Update Request] HiddenEye aka HiddenEye Legacy

### ISSUE THREAD

**Issue by sTiKyt** [BlackArch/blackarch#2866]
- **Name**: HiddenEye  aka hidden-eye aka hiddeneye
- **Source URL**: https://github.com/DarkSecDevelopers/HiddenEye-Legacy

### Problem:
Due to certain circumstances, the original HiddenEye code is going to be abandoned and used as reference  for creating of a new, better version. In regard to this situation, we are requesting you to rename "**HiddenEye**" package to "**HiddenEye Legacy**" and to replace the terminal command to "**hiddeneye-legacy**"

### Alternative Solution:
You could also abandon old code and switch it to https://github.com/Open-Security-Group-OSG/HiddenEyeReborn/
But we prefer it to be handled as  completely another tool.

Thank you in advance.

**Comment by noraj** [comment]
What's the interest of packaging the legacy version which is abandoned? Better to package the reborn version?

**Comment by sTiKyt** [comment]
Project is frozen for now anyway
