### ISSUE TITLE
SirepRAT

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2870]
- **Name**: SirepRAT
- **Source URL**: https://github.com/SafeBreach-Labs/SirepRAT

**Comment by noraj** [comment]
Be warned it's python 2

**Comment by noraj** [comment]
- [ ] setup.py https://github.com/SafeBreach-Labs/SirepRAT/issues/13

**Comment by pwnfoo** [comment]
Closed in #2930. Python3 movement in #2956
