### ISSUE TITLE
Consider moving impacket as python-impacket

### ISSUE THREAD

**Issue by pwnfoo** [BlackArch/blackarch#2878]
Type: Discussion

## Discussion

Since we're using that naming convention for most Python packages, doesn't it make sense to move `impacket` as `python-impacket` for the sake of consistency?

**Comment by noraj** [comment]
Yes but no, this is just AL mirroring of https://www.archlinux.org/packages/?q=impacket

**Comment by pwnfoo** [comment]
Ah, alright. I didn't realise it was part of the community repo.
