### ISSUE TITLE
[Tool Request] ROADtools

### ISSUE THREAD

**Issue by pwnfoo** [BlackArch/blackarch#2885]
- **Name**: ROADtools
- **Source URL**: https://github.com/dirkjanm/ROADtools

**Comment by noptrix** [comment]
@pwnfoo any news on this? if not let's close it please.

**Comment by pwnfoo** [comment]
> @pwnfoo any news on this? if not let's close it please.

 #2940 is open for this. Looks like @noraj needs some help with it.

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4366

**Comment by D3vil0p3r** [comment]
@noptrix can you please close this ticket and https://github.com/BlackArch/blackarch/pull/2940 ?
