### ISSUE TITLE
[Tool Request] Stormspotter

### ISSUE THREAD

**Issue by pwnfoo** [BlackArch/blackarch#2886]
- **Name**: Stormspotter
- **Source URL**: https://github.com/Azure/Stormspotter

**Comment by Jagroop-Singh** [comment]
Hey there, can I claim this?

**Comment by ikstream** [comment]
Just open a pull request for it. You can also label the PR as work in progress, if you need some time to finish it

**Comment by ikstream** [comment]
For packaging, please follow our [Guidelines](https://github.com/BlackArch/blackarch/blob/master/docs/HOWTO-DEV.md)

**Comment by noptrix** [comment]
@pwnfoo any news on this? if not let's close it please.

**Comment by D3vil0p3r** [comment]
This is another tool mainly deployed as container. For this kind of requests must we put the effort on thinking how to deploy containers as discussed in https://github.com/BlackArch/blackarch-pkgbuilds/issues/21 or should we deploy them by packages by nodejs?

**Comment by D3vil0p3r** [comment]
The project seems unmaintained. Issues and PRs seem not managed. Since there is no answer by the user requesting the tool, I would close it.

**Comment by noraj** [comment]
Also, it is a web application with a Neo4j database so that would be difficult to package and there is already a docker.
