### ISSUE TITLE
[Tool Request] Zracker

### ISSUE THREAD

**Issue by devim-stuffs** [BlackArch/blackarch#2889]
- **Name**: Zracker
- **Source URL**: https://github.com/devim-stuffs/Zracker

-**About**: Zracker is a Zip File Password Recovery Utility Tool, including Dictionary and BruteForce Attacks, both working over CPU-Power/ CPU_Cores, increasing the speed 'n' times the no. of Cores Selected/Available.

**Comment by noraj** [comment]
The devim-stuffs github account was renamed or deleted.
