### ISSUE TITLE
Update python-pyngrok

### ISSUE THREAD

**Issue by mallmaluss** [BlackArch/blackarch#2891]
- **Name**: python-pyngrok
- **Source URL**: https://github.com/alexdlaird/pyngrok/tree/5.0.0

Update for package

**Comment by noraj** [comment]
@Edu4rdSHL Are we packaging libraries as standalone (not as dependency)?

**Comment by Edu4rdSHL** [comment]
Hey @noraj , yes, libraries are standalone, not in groups.
