### ISSUE TITLE
How to install Ivre GUI on blackarch

### ISSUE THREAD

**Issue by poyan94** [BlackArch/blackarch#2892]
Type: Question

## Question
Hello My friends, I have installed blackarch, and I want to access IVRE via web access (i mean GUI),
first of all, I set an IP for my blackarch, and now I want to access IVRE through my network with GUI
What should I do exactly?

**Comment by ikstream** [comment]
- What have you tried so far?
- What problems do you encounter?
- Have you read the documentation of ivre?
