### ISSUE TITLE
[Tool Request] Pwndoc

### ISSUE THREAD

**Issue by pwnfoo** [BlackArch/blackarch#2900]
- **Name**: pwndoc
- **Source URL**: https://github.com/pwndoc/pwndoc

Doesn't qualify as a security tool, but this can be a good addition.

**Comment by noraj** [comment]
In general you want to deploy teh docker on a server to allow collaboration and not having it on your own machine, same for Dradis or Faraday.

**Comment by noptrix** [comment]
@pwnfoo any news on this? if not let's close it please.

**Comment by noraj** [comment]
I think we can close this.
