### ISSUE TITLE
nbtscan segmentation fault

### ISSUE THREAD

**Issue by saltasatelites** [BlackArch/blackarch#2901]
- [x ] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Make any kind of query. You always get a segmentation fault. 

### Steps to reproduce

- install from blackarch or Archlinux/community. (same version 1.5.1-8)
- make a query. For example:  
 >nbtscan 192.168.1.25-137

- that reproduce the bug
- Segmentation fault
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
  Scan a range of IP addresses

### Screenshots
none

### Info for developers

**GNU/Linux distribution:** Archlinux with Blackarch repository above. You can install from the community repo too. It's the same package.
**Tool version:** 1.5.1-8

### Link to debug log

No log.

**Comment by ikstream** [comment]
ntbscan isn't maintained by Blackarch, as it is upstream. Please report to arch Linux, if it hasn't already be done

**Comment by dualfade** [comment]
Will update build --
