### ISSUE TITLE
Error:failed to retrieve file

### ISSUE THREAD

**Issue by ccnick6** [BlackArch/blackarch#2905]
Whenever I try to use pacman to install anything I always get error: failed retrieving file (then like 50 lines of errors)
The bottom 2 say
Error: failed to update blackarch (invalid url for server)
Error: failed to synchronize all databases

**Comment by ikstream** [comment]
Hi,

Please provide the full output. 
- How did you install blackarch?
- what have you tried so far?
- have you checked different mirrors?
- Please provide the exact command you are using

**Comment by ccnick6** [comment]
> Hi,
> 
> Please provide the full output. 
> - How did you install blackarch?
> - what have you tried so far?
> - have you checked different mirrors?
> - Please provide the exact command you are using
> 
> 
> 

I spent 4+ hours tryna figure it out last night and I concluded it was a network issue bc all 500 mirrors weren't working even when I put a new one in. I fixed it, thanks tho
