### ISSUE TITLE
Network

### ISSUE THREAD

**Issue by ccnick6** [BlackArch/blackarch#2908]
Type: Question

## Question
I am new to all of this and I'm trying my best. I've been having this issue where I can't connect to any mirror. I've determined it's a connection issue with my wifi. I'll do any commands u guys need I just need help

**Comment by ikstream** [comment]
Please provide mor info!

- What have you tried? 
- Have you tried a wired connection?
- Have you looked up your issue on the arch wiki/internet?

**Comment by noraj** [comment]
@ccnick6 Maybe it will be quicker if you come talk to the community on the #support channel.
![image](https://user-images.githubusercontent.com/16578570/98530455-3af11080-227f-11eb-9b31-97a185cdb7cc.png)

**Comment by ikstream** [comment]
Feel free to reopen, if you provide more info
