### ISSUE TITLE
Kayak

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2910]
- **Name**: Kayak
- **Source URL**: https://github.com/dschanoeh/Kayak / https://dschanoeh.github.io/Kayak/
- Description: Kayak is an application for CAN bus diagnosis and monitoring.
- Asked by HP#8941 on discord

**Comment by D4imyo** [comment]
i did not find .jar file for this tool, however, it can be built/installed with `mvn`, so can i use `mvn` in the PKGBUILD to install it ?

**Comment by noptrix** [comment]
@D4imyo sure. actually, it's even the preferred way to build from source whenever possible... so go ahead with mvn :)

**Comment by noraj** [comment]
@D4imyo It would be fantastic if you could even PR a `java-maven` template [here](https://github.com/BlackArch/blackarch-pkgbuilds) after that 😃

**Comment by D3vil0p3r** [comment]
The repository was archived since 2020. Are you sure to request it? Let me know and I'll try to package it.
