### ISSUE TITLE
lazyrecon

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2912]
- **Name**: lazyrecon
- **Source URL**: https://github.com/nahamsec/lazyrecon
- recon script
- asked by rain#6450 on discord

**Comment by pwnfoo** [comment]
Too many hardcodes 😨

**Comment by noraj** [comment]
This look low quality code and there are many other OSINT tools doing better than this.

**Comment by noptrix** [comment]
yeah, really nothing fancy and kinda lame, sorry. had to leave my comments :)
