### ISSUE TITLE
[Tool Request] Uberfile

### ISSUE THREAD

**Issue by pwnfoo** [BlackArch/blackarch#2924]
- **Name**: Uberfile
- **Source URL**: https://github.com/ShutdownRepo/uberfile

Just dropped but looks nice. This is from the exegol dev

**Comment by noraj** [comment]
- [ ] setup.py https://github.com/ShutdownRepo/uberfile/issues/1

**Comment by ShutdownRepo** [comment]
I'll work on this asap :+1:

**Comment by ShutdownRepo** [comment]
It should work now

**Comment by dualfade** [comment]
Testing and will update the package. Thank you.
