### ISSUE TITLE
enum4linux-ng

### ISSUE THREAD

**Issue by pwnfoo** [BlackArch/blackarch#2925]
- **Name**: enum4linux-ng
- **Source URL**: https://github.com/cddmp/enum4linux-ng
- **Description**:  A next-generation version of enum4linux with additional features like JSON/YAML export. Aimed for security professionals and CTF players.

This one seems to have nicer features. Do you think this one is worth adding?

**Comment by noraj** [comment]
enum4linux is unmaintained and buggy as hell so enum4linux-ng is welcome

**Comment by noraj** [comment]
- [ ] setup.py https://github.com/cddmp/enum4linux-ng/issues/11
