### ISSUE TITLE
pyGPOAbuse

### ISSUE THREAD

**Issue by pwnfoo** [BlackArch/blackarch#2929]
- **Name**: pyGPOAbuse
- **Source URL**: https://github.com/Hackndo/pyGPOAbuse
- **Description**: Partial python implementation of [SharpGPOAbuse](https://github.com/FSecureLABS/SharpGPOAbuse)

**Comment by noraj** [comment]
- [ ] setup.py https://github.com/Hackndo/pyGPOAbuse/issues/2

**Comment by noraj** [comment]
See https://github.com/Hackndo/pyGPOAbuse/issues/2#issuecomment-750414173, the project is unmaintained, so as of  #2842 we do not accept tool request for unmaintained project.
