### ISSUE TITLE
jwt-cli

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#2950]
- **jwt-cli**:
- **https://github.com/troyharvey/jwt-cli**:

**Comment by noraj** [comment]
https://inventory.raw.pm/

There are many JWT tools that are able to decode, crack, forge, etc. JWT cookies, many of them are already on BA.

![image](https://user-images.githubusercontent.com/16578570/101985005-62276d00-3c85-11eb-814f-27cb6a8c269c.png)

But this one only decodes tokens it crack or forge as other do, so I see no interest to add this one.

**Comment by noraj** [comment]
see `5.` https://github.com/BlackArch/blackarch/issues/2842
