### ISSUE TITLE
Tool Request Salea Logic

### ISSUE THREAD

**Issue by sangoku116** [BlackArch/blackarch#2951]
- **Name**: Salea Logic 
- **Source URL**: https://www.saleae.com/downloads/
AUR URL: https://aur.archlinux.org/packages/saleae-logic/

Version 2 Alpha 
Source URL: https://ideas.saleae.com/f/changelog/2315/
AUR URL: https://aur.archlinux.org/packages/saleae-logic-alpha/

**Comment by Edu4rdSHL** [comment]
Hello @sangoku116. Thank you for submiting it, anyways, seems that it's a propietary program and we need an official permission from the tool owners to distribute it in our repos. I was looking for an email/way to contact them but don't found it.

If you can help us providing an email where we can contact them, will be awesome.

Regards,
Ed

**Comment by sangoku116** [comment]
From looking at the website, the way to contact them would be through this form https://contact.saleae.com/hc/en-us/requests/new or by calling them.

**Comment by Edu4rdSHL** [comment]
Thank you for getting back to me on this so quickly. I will try to contact them as soon as possible.

**Comment by Edu4rdSHL** [comment]
I have got permission from Saleae to distribute the tool in our repos, I will add this soon.

**Comment by sangoku116** [comment]
> I have got permission from Saleae to distribute the tool in our repos, I will add this soon.

Awesome, thank you for the feedback!

**Comment by Edu4rdSHL** [comment]
Hello, package added.
