### ISSUE TITLE
Add "MaskPhish" Good Social Engineering Tool

### ISSUE THREAD

**Issue by jaykali** [BlackArch/blackarch#2961]
- **MaskPhish**:
- **https://github.com/jaykali/maskphish**:

This is a tool that makes any phishing URL to any normal looking URL.
See following screenshot:
![mask](https://user-images.githubusercontent.com/62602243/102440553-7339fa80-4046-11eb-902f-e9b044984773.png)

**Comment by Edu4rdSHL** [comment]
Hello @jaykali , thank you for suggesting the tool. After reviewing we have decided to no include it.

Regards,
Eduard
