### ISSUE TITLE
python packages, 3.8 -> 3.9

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#2964]
Example:
https://blackarch.org/blackarch/blackarch/os/x86_64/trufflehog-162.0d6f2df-1-any.pkg.tar.xz

Still installs to /usr/lib/python3.8/site-packages/
instead of /usr/lib/python3.9/site-packages/

**Comment by noptrix** [comment]
@vdun thank you. are there any other packages which have the same issue?
