### ISSUE TITLE
nbtscan segfaults on Arch base image

### ISSUE THREAD

**Issue by bitshiftnetau** [BlackArch/blackarch#2974]
nbtscan segfaults when installing to ArchLinux from a base Arch image with the BlackArch repos enabled. 

Initially I had issues because I was still installing community/nbtscan, but then I install blackarch/nbtscan and it still segfaults.

It appears the same issue was raised on Arch forums [here](https://bbs.archlinux.org/viewtopic.php?id=240477) and is noted in the notes of the original repo [here](https://github.com/scallywag/nbtscan)

**Comment by ikstream** [comment]
We don't maintain nbtscan, it is only mirrored from community. Maybe we should change that and use the [source](https://github.com/resurrecting-open-source-projects/nbtscan) debian uses. 

Can you please provide the command you entered, just in case

**Comment by bitshiftnetau** [comment]
Sure, it was just a normal scan:

`nbtscan x.x.x.x-x`

Also segfaults on range:

`nbtscan -r x.x.x.x/24`

Or file usage:

`nbt -f iplist.txt`

**Comment by pwnfoo** [comment]
@bitshiftnetau Please see #2901

**Comment by ikstream** [comment]
Release has been updated in #2982 Therefore closing this issue.
