### ISSUE TITLE
Blackarch-installer v1.2.19

### ISSUE THREAD

**Issue by Walnut-dev** [BlackArch/blackarch#2981]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

[+] Creating ROOT Partition
mke2fs 1.45.5 (20 march 2020)
The file 4 does not exist and no size was specified
Error: Could not create filesystem

### Steps to reproduce

- Downloaded full install
- Flashed USB of 16GB

**Actual result:** the black arch-install script cancels
**Expected result:** finishing installation
### Info for developers

**Device:** APPLE MB2015, issue persists on my Windows 10 aswell

Not dual booting currently however I do have 2 separate partitions saved as /dev/sdx1 and /dev/sdx2 for the macOS installation

### Link to debug log

[+] Creating ROOT Partition
mke2fs 1.45.5 (20 march 2020)
The file 4 does not exist and no size was specified
Error: Could not create filesystem

**Comment by noraj** [comment]
Issue for the installer should be addressed here: https://github.com/BlackArch/blackarch-installer

**Comment by Walnut-dev** [comment]
@noraj thanks for the heads up i went ahead and opend a issue on that repository aswell, Would you mind telling me what you think the problem is?

**Comment by ikstream** [comment]
What was your input when you selected the root partition? I am currently downloading the current iso to have a look at it.

**Comment by ikstream** [comment]
I am closing this issue, as the other issue is linked and used for debugging puposes
