### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-72: ordinal not in range(128) arch linux xerosploit

### ISSUE THREAD

**Issue by aladdinsparta** [BlackArch/blackarch#2990]
sudo xerosploit on acrh linux 

Traceback (most recent call last):
  File "xerosploit.py", line 980, in main
    home()
  File "xerosploit.py", line 89, in home
    print (tabulate(table, stralign="center",tablefmt="fancy_grid",headers="firstrow"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-72: ordinal not in range(128)

**Comment by Edu4rdSHL** [comment]
Hi, you messed up something in your system. As you saw in the discord, even installing the tool from their repo doesn't work. It isn't an distro problem.
