### ISSUE TITLE
About apktool packaging dependencies ?

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3001]
Type: Question

## Question

1. I'm comparing our [PKGBUILD](https://github.com/BlackArch/blackarch/blob/master/packages/android-apktool/PKGBUILD) with the [Apktool official install](https://ibotpeaches.github.io/Apktool/install/) and also the [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=android-apktool). There is only a jar (that requires Java) and a bash wrapper so I'm not sure we need to required `android-sdk-build-tools` at all (that is not required in the AUR package and not mentioned in the official install guide).
2. `android-sdk-build-tools` dependencies seems weird: https://github.com/BlackArch/blackarch/blob/b829654d2aa9c398d78d2193642027b2cd2469c6/packages/android-sdk-build-tools/PKGBUILD#L15-L16
  The 32 bits packages requires 64 bits libs and the 64 bits package requires 32 bits libs.

**Comment by Edu4rdSHL** [comment]
I will check it today.

**Comment by aancw** [comment]
I'm agree with @noraj, it's standalone jar file.

**Comment by Edu4rdSHL** [comment]
Hey @noraj @aancw, it have been fixed in the referenced commit and the aditional  `android-sdk-build-tools` issue addressed in https://github.com/BlackArch/blackarch/commit/930ac2edef48b96ba4cb561b608c2f00812b4fe5#diff-19e04881798fb6e0cd7bf022a540db11686748e558f8fcafefeb7f60f5998bd6
