### ISSUE TITLE
The menus of blackarch don't show me after installing kde plasma there is any solution?

### ISSUE THREAD

**Issue by Edu4rdSHL** [BlackArch/blackarch#3021]
The menus of blackarch don't show me after installing kde plasma there is any solution?
and there is some bugs like there is some text don't show in any window or applications in kde plasma 
There is any solutions?

_Originally posted by @Youssef-Tamer in https://github.com/BlackArch/blackarch/discussions/3020#discussioncomment-367866_

**Comment by Edu4rdSHL** [comment]
> The menus of blackarch don't show me after installing kde plasma there is any solution?

BlackArch menus doesn't work by magic, they are generated for each WM we use and the XFCE desktop environment, menus aren't availables for plasma so it's expected and the solution is that you manually create each menu.

> and there is some bugs like there is some text don't show in any window or applications in kde plasma
> There is any solutions?
> 
> _Originally posted by @Youssef-Tamer in [#3020 (comment)](https://github.com/BlackArch/blackarch/discussions/3020#discussioncomment-367866)_

Please attach images.

**Comment by aancw** [comment]
@Youssef-Tamer Can you attach an image referring to text don't show in any window?

**Comment by Youssef-Tamer** [comment]
> @Youssef-Tamer Can you attach an image referring to text don't show in any window?

Thing like that
![Screenshot_20210215_120829.jpg](https://user-images.githubusercontent.com/74739696/107932986-da145b00-6f86-11eb-80c7-1b7f68a60327.jpg)

**Comment by Edu4rdSHL** [comment]
Can you provide a useful image and explain what's "like that"? Thanks.

**Comment by Youssef-Tamer** [comment]
> Can you provide a useful image and explain what's "like that"? Thanks.

![Screenshot_20210215_120632_com google android youtube](https://user-images.githubusercontent.com/74739696/108004430-880f1c00-6ffe-11eb-9cc7-00304fc99345.jpg)

**Comment by Youssef-Tamer** [comment]
> Can you provide a useful image and explain what's "like that"? Thanks.

![Uploading Screenshot_20210216_022857.jpg…]()

**Comment by aancw** [comment]
I still don't understand and I think it's common arch or kde issue. Have you posted in on arch forum?

**Comment by thego0n** [comment]
maybe the tool by anyon3 could be forked / improved to add menus for the KDE plasma desktop when any solution is found. 

@Youssef-Tamer 

https://github.com/Anyon3/blackmate

~go0s

**Comment by Edu4rdSHL** [comment]
> ![Screenshot_20210216_022857](https://user-images.githubusercontent.com/74739696/108004621-07045480-6fff-11eb-9d8e-27af1f1723dc.jpg)

Please delete your `.config/.config/gtk-*` folders and `~/.gtkrc*` files, then restart Plasma, it's happening because you're mixing Desktop environments and themes. Also, please make sure that you have the `breeze` package installed.

Finally, use KDE Settings to configure the color for GTK and QT apps.
