### ISSUE TITLE
tftp-bruteforce doesn't start

### ISSUE THREAD

**Issue by Zeecka** [BlackArch/blackarch#3030]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Tool doesn't start.

### Steps to reproduce

- Install tftp-bruteforce
- Try to run the tool `tftp-bruteforce` or inspect  /usr/bin/tftpbrute

**Actual result:** 
```
/usr/bin/tftpbrute: line 2: /usr/share//tftpbrute.pl: No such file or directory
```

**Expected result:** 
```/usr/share/tftp-bruteforce/tftpbrute.pl, , V 0.1 
usage: perl /usr/share/tftp-bruteforce/tftpbrute.pl  <tftpserver> <filelist> <maxprocesses> 
example  ./tftpbrute.pl 192.168.66.202 brutefile.txt 100
```

### Screenshots

![2021-02-19_21-53](https://user-images.githubusercontent.com/24873615/108561012-d58cd100-72fd-11eb-961f-13bf9468ae8c.png)

### Info for developers

- https://github.com/BlackArch/blackarch/blob/master/packages/tftp-bruteforce/PKGBUILD#L27
- Tested with zsh

**Comment by Zeecka** [comment]
Note : Even after patching `/usr/bin/tftpbrute`, the tool doesn't run : 

![2021-02-19_22-14](https://user-images.githubusercontent.com/24873615/108562275-eb02fa80-72ff-11eb-8107-28adca24dfcc.png)

**Comment by Edu4rdSHL** [comment]
The `tfpbrute.pl` script should be directly in `/usr/bin` without the wrapper script, @noraj ^

**Comment by noraj** [comment]
> The `tfpbrute.pl` script should be directly in `/usr/bin` without the wrapper script, @noraj ^

Yes, it's EZ to fix, I'll fix it as soon as I'm on my computer but if you want to fix it tonight feel free to.

**Comment by Edu4rdSHL** [comment]
I will do.

**Comment by Edu4rdSHL** [comment]
It's fixed now, @Zeecka .

**Comment by noraj** [comment]
thx @Edu4rdSHL
