### ISSUE TITLE
Tool Discussion: xattacker

### ISSUE THREAD

**Issue by pwnfoo** [BlackArch/blackarch#3037]
## Info

Tool URL: https://github.com/Moham3dRiahi/XAttacker/
Referenced PR: https://github.com/Moham3dRiahi/XAttacker/pull/52

## What?

From @noraj's communication in Discord: 

```
We have a XAttacker (free version) in our repo, but this tool (the free version) seems to exist to 
legitimate the premium scam. The owner is deleting user comments, he disabled issues 
so the only way to talk publicly is open a PR, etc. also the very lame architecture & README 
always seemed suspicious to me. 

Do we keep this scam in our repo?
Even excepting the scam, the free tool is low quality, I'm even surprised 
we added it in the first place: https://github.com/Moham3dRiahi/XAttacker/blob/master/XAttacker.pl
```

## Screenshots

![image](https://user-images.githubusercontent.com/9546091/109130582-e7e09200-7777-11eb-87da-9ef8ca381197.png)

**Comment by Edu4rdSHL** [comment]
@americanitunes101, sorry for ping-ing you. Was your https://github.com/americanitunes101/XAttacker/commit/2424ea62d7267c10d9e689614b22e68449e96f3c problem solved?

@Moham3dRiahi, hi, can you please clarify what's happening there? Otherwise, the tool will be removed from our repos.

**Comment by americanitunes101** [comment]
> @americanitunes101, sorry for ping-ing you. Was your [americanitunes101/XAttacker@2424ea6](https://github.com/americanitunes101/XAttacker/commit/2424ea62d7267c10d9e689614b22e68449e96f3c) problem solved?
> 
> @Moham3dRiahi, hi, can you please clarify what's happening there? Otherwise, the tool will be removed from our repos.

Nope. Zero response from him after his initial claim he was going to "fix the issue" when he returned home.
He has read the messages I've sent to him on ICQ, and goes about himself to delete every Telegram chat I try and start with him. 
For someone as talented as him, I'd happily donate $100 to further his script development for the community if I knew how badly he must need it if he's reduced to being a **scamming piece of shit**. Hope he hasn't managed to scam anyone else!

**Comment by americanitunes101** [comment]
He's just gone and done another round of deleting comments rather than just delivering the god damn tool.

**Comment by Edu4rdSHL** [comment]
After seeing that the repo owner doesn't answer any question, I assume the scam is real and thus I have removed the package.

Regards,
Ed

**Comment by mastercho** [comment]
I just did quick check and saw he continue do scamming people be careful don't fall for scam!
