### ISSUE TITLE
Why I cannot download blackarch.db while running torctl?

### ISSUE THREAD

**Issue by martin-braun** [BlackArch/blackarch#3038]
Type: Question

## Question
Hi, I installed `torctl` to my fresh Arch Linux distro like described [here](https://bennybackslash.github.io/%2Fposts%2FTorctl%20on%20Arch.html) and it works great. However, when I update by running `sudo pacman -Syu` I basically get the same error that was previously reported in #1264. `pacman` is unable to retrieve the blackarch.db. I tried to change the mirror to blackarch.org, but the problem persisted until I decided to stop torctl by running `torctl stop`.

Why is that? Shouldn't this work? I think it should allow me to update through Tor. Turning Tor off using`torctl` off for updating is like leaving the door open while visiting the neighbor.

**Comment by Edu4rdSHL** [comment]
Please paste the logs of the error that you're actually getting.
