### ISSUE TITLE
Assetnote Wordlists

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3052]
- **Name**: Assetnote Wordlists
- **Source URL**: https://wordlists.assetnote.io/ - https://github.com/assetnote/wordlists
- **Description**: Monthly updated web content discovery wordlists

Let's include them like we do for SecLists under `/usr/share/assetnote-wordlists`

**Comment by aancw** [comment]
I think it's a lot of data with zip. Better to use this for https://github.com/BlackArch/wordlistctl

**Comment by noraj** [comment]
No zip, `wget -r --no-parent -R "index.html*" https://wordlists-cdn.assetnote.io/data/ -nH`

**Comment by aancw** [comment]
I see, so what's indicator for package update? Also, The file name is incremental, 
```
httparchive_apiroutes_2020_11_20.txt               28-Mar-2021 14:06            47552163
httparchive_apiroutes_2021_01_28.txt               28-Mar-2021 14:06             6937210
httparchive_apiroutes_2021_02_28.txt               28-Mar-2021 14:06             6842181
httparchive_apiroutes_2021_03_28.txt               28-Mar-2021 14:06             6562857
httparchive_aspx_asp_cfm_svc_ashx_asmx_2020_11_..> 28-Mar-2021 14:06             1771887
httparchive_aspx_asp_cfm_svc_ashx_asmx_2021_01_..> 28-Mar-2021 14:06              951017
httparchive_aspx_asp_cfm_svc_ashx_asmx_2021_02_..> 28-Mar-2021 14:06              904516
httparchive_aspx_asp_cfm_svc_ashx_asmx_2021_03_..> 28-Mar-2021 14:06              949024
httparchive_cgi_pl_2020_11_18.txt                  28-Mar-2021 14:06               45100
httparchive_cgi_pl_2021_01_28.txt                  28-Mar-2021 14:06               30240
httparchive_cgi_pl_2021_02_28.txt                  28-Mar-2021 14:06               27808
httparchive_cgi_pl_2021_03_28.txt       
```
What do you think?

**Comment by noraj** [comment]
Only httparchive wordlists and Kiterunner Wordlists are updated. The manual ones are already included in SecLists.

**Comment by noptrix** [comment]
@noraj any news on this? if not let's close it please

**Comment by noraj** [comment]
please don't close

**Comment by D3vil0p3r** [comment]
How would you like to act on this? Making a package as done for `seclists`or implementing it in `wordlistctl`?

**Comment by noraj** [comment]
I would see several packages:

- assetnote-wordlists-auto: automatically generated wordlists
- assetnote-wordlists-kiterunner: wordlists generated by kiterunner
- assetnote-wordlists-technology-host: technology <=> host mappings
- assetnote-wordlists-manual: manually generated wordlists

And then a meta-package `assetnote-wordlists` that will have the previous 4 as dependency.

**Comment by D3vil0p3r** [comment]
In PKGBUILD we can use something like:
```
package() {
  curl -s https://wordlists-cdn.assetnote.io/data/automated/ | grep -oP 'href="\K[^"]+\.[a-zA-Z0-9]+' | xargs -I {} curl -O https://wordlists-cdn.assetnote.io/data/automated/{}
}
```
for `auto`. Same approach for the other packages. If you have a better idea let me know.

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4341

My proposal:
* Only one package `assetnote-wordlists` with 4 subdirs (`automated`, `kiterunner`, `manual`, `technologies`) instead of 4 separated ones + 1 metapackage

Rationale:
* prevent to increase entropy
* make management of `assetnote-wordlists` package easier
* among the generated source files, there are also old ones that are almost a clone of the latest ones. So, the package retrieves only the latest .txt files. It saves a lot of package size (much less than `seclists` package size)

**Comment by noraj** [comment]
> I would see several packages:
> 
>     * assetnote-wordlists-auto: automatically generated wordlists
> 
>     * assetnote-wordlists-kiterunner: wordlists generated by kiterunner
> 
>     * assetnote-wordlists-technology-host: technology <=> host mappings
> 
>     * assetnote-wordlists-manual: manually generated wordlists
> 
> 
> And then a meta-package `assetnote-wordlists` that will have the previous 4 as dependency.

All 5 packages can be in one PKGBUILD (like we did earlier for python 2 and python 3 version of the same lib see https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-python-dual-lib-setuptools).

**Comment by D3vil0p3r** [comment]
Y I thought about that chance... But I'm not sure if it can be worth to separate packages, even if PKGBUILD will be one. What are the advantages you see over the proposed solution?

**Comment by noraj** [comment]
> Y I thought about that chance... But I'm not sure if it can be worth to separate packages, even if PKGBUILD will be one. What are the advantages you see over the proposed solution?

As content is large in storage, having different packages helps save space by installing only what one really need. But if one need all, the meta package make is easy to fetch all packages. Like it is for texlive, you don't necessarily want to install the full texlive.

**Comment by D3vil0p3r** [comment]
Ok. Let's see noptrix thought too.
