### ISSUE TITLE
EFI partition reinstall

### ISSUE THREAD

**Issue by Kinny092** [BlackArch/blackarch#3057]
Type: Question

Hi, I have recently installed BlackArch and is a very new user. I mistakenly installed the EFI partition (nvme0n1p1) as EXT4. 

After the installation completes, there is no GRUB bootloader on startup. I found out that the partition needs to be either Fat32 or VFAT. 

After some painstakingly time spent on researching, I changed it to VFAT but at the same time, it cleared all the files on that partition including vmlinuz-linux and initramfs-linux.img.   

I tried to start blackarch installation again hoping to find an option that just installs the EFI files but no there isnt. I could not go on because when it prompts me if I would like root to be encrypted, I opted yes. The issue is that I had already done this process and my root (nvme0n1p2) is already encrypted with LUKS.

Is there any way I can install the EFI files and the bootloader so I can begin using the system?
I would refrain trying to decrypt my root and somehow clear the hard drive to factory default. 

Thanks

**Comment by ikstream** [comment]
- Start in live boot
- open your encrypted root with `cryptsetup open /dev/sdxx root`
- mount `/dev/mapper/root` somewhere, mount your boot partition to `<mountpoint>/boot`
- chroot into your mounted system.
- Follow the arch wiki on how to setup [systemd-boot](https://wiki.archlinux.org/index.php/Systemd-boot)
- run `mkinitcpio`
- you should be good to go

**Comment by Kinny092** [comment]
> * Start in live boot
> * open your encrypted root with `cryptsetup open /dev/sdxx root`
> * mount `/dev/mapper/root` somewhere, mount your boot partition to `<mountpoint>/boot`
> * chroot into your mounted system.
> * Follow the arch wiki on how to setup [systemd-boot](https://wiki.archlinux.org/index.php/Systemd-boot)
> * run `mkinitcpio`
> * you should be good to go

Thanks for your reply. I tried that and rebooted. Now i am getting something different. I get a UEFI boot manager option but there is only one option which is to reboot into firmware interface. The computer reboots again.

**Comment by ikstream** [comment]
have you created the loader entries according to systemd-boot arch wiki?

**Comment by Kinny092** [comment]
> have you created the loader entries according to systemd-boot arch wiki?

Oh i was looking at that and got sidetracked and forgot. I could not find esp/loader/loader.conf at that time of looking at it. There was no esp directory at all. I mounted my first partition to /boot and mkinitcpio was happy.

**Comment by Edu4rdSHL** [comment]
Please mark @ikstream 's reply as answer.

**Comment by Kinny092** [comment]
> Please mark @ikstream 's reply as answer.
Im still trying to make it work. Still trying to figure how to add the loader entries in my context when the root fs is encrypted. I would prefer to mark it as solution when ive added the entry. Otherwise the guide is pretty much leading me to somewhere that is not the solution i need.

**Comment by Edu4rdSHL** [comment]
The entries needs to be created in the boot partition which isn't encrypted, anyways that's a totally different problem than "reinstalling the EFI partition", it was already answered by Stefan and you confirmed it with

> I get a UEFI boot manager option but there is only one option which is to reboot into firmware interface.

So, as I said you need to create the entries in the boot partition, if you have mounted the EFI partition in `/boot` then the entry need to be created in `/boot/loader/entries/` and point to the correct cryptdevice. See https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_an_entire_system#Configuring_the_boot_loader

**Comment by Kinny092** [comment]
> 
> 
> The entries needs to be created in the boot partition which isn't encrypted, anyways that's a totally different problem than "reinstalling the EFI partition", it was already answered by Stefan and you confirmed it with
> 
> > I get a UEFI boot manager option but there is only one option which is to reboot into firmware interface.
> 
> So, as I said you need to create the entries in the boot partition, if you have mounted the EFI partition in `/boot` then the entry need to be created in `/boot/loader/entries/` and point to the correct cryptdevice. See https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_an_entire_system#Configuring_the_boot_loader

thanks for that, i will mark his post as answer but sorry im new to the forum. how do i do that?

**Comment by Edu4rdSHL** [comment]
It was my fail, I thought that it was a discussion but it was actually an issue. Feel free to close.

**Comment by Kinny092** [comment]
> It was my fault, I thought that it was a discussion but it's actually an issue. Feel free to close.

Dont be, im a rookie with arch and is still learning. I can say blackarch is probably the hardest linux to install as it does not install properly. 

I have managed to create the necessary files and loader entries so for these, the issue can be closed. I tried to start up and it says /dev/disk/by-label did not show up after 30 seconds. Tried to google and found a heap of users experienced the same thing, some thinking it could be because of usb 2.0/3.0, flashing software, hardware architecture etc but i have some doubts with the last line of arch.conf where there is an options="label=arch_os". I cant comprehend that, maybe there is something else i need to add below it. 

Anyway, thats it for my rant for now, i will keep looking for answers and raise another topic if necessary. Thanks for all your help guys. 

Please do let me know if you have any quick idea about this label issue.
![20210326_015619](https://user-images.githubusercontent.com/25901267/112498511-83483f80-8dd6-11eb-8968-4ac36687ea26.jpg)

**Comment by Edu4rdSHL** [comment]
@Kinny092 do you mind joining to our IRC (#blackarch in Freenode) or our Discord https://discord.gg/KMVkKDN ?

Additionally I have two videos on how to install BlackArch Linux in UEFI/BIOS.

- BIOS: https://odysee.com/@SecHackLabs:b/blackarch-bios:4
- UEFI: https://odysee.com/@SecHackLabs:b/blackarch-uefi:d

I hope to hear from you soon.

**Comment by Kinny092** [comment]
> 
> 
> @Kinny092 do you mind joining to our IRC (#blackarch in Freenode) or our Discord https://discord.gg/KMVkKDN ?
> 
> Additionally I have two videos on how to install BlackArch Linux in UEFI/BIOS.
> 
>     * BIOS: https://odysee.com/@SecHackLabs:b/blackarch-bios:4
> 
>     * UEFI: https://odysee.com/@SecHackLabs:b/blackarch-uefi:d
> 
> 
> I hope to hear from you soon.
> 
> Edit:
> 
> Regarding to the label you need to change it, you really may want to use UUIDs or directly disk partitions.

im not a discord user but i will try to learn how to use it.

sure i will watch those videos. 

do you have an example of how i should implement the UUID? there are a couple in the wiki, not sure exactly which i should enter and in which conf file.

**Comment by Kinny092** [comment]
so the solution to this is that i needed to mount root / directory first 
`sudo mount /dev/nvme0n1p2 /mnt`
lets not mount boot yet
next, i have to chroot into mnt
`sudo arch-chroot /mnt`
next, i found out that my /boot partition has all craps so i had to clear them
`rm -rf /boot/*`
now we leave chroot by typing exit
next we try to mount boot
`cryptsetup open /dev/nvme0n1p1 r00t `(you can call r00t as something else but be sure you use it use it below in the UUID section)
type in the passphrase
`sudo mount /dev/mapper/r00t /mnt/boot`
Install bootctl by typing `bootctl install`
check /etc/fstab is mounted correctly
ls boot should have initramfs.img, initramfs-fallback.img, vmlinuz, efi folder and loader folder.
in loader folder there should be an loader.conf that forces bootloader to obtain loader entries from the next child folder.
in entries folder within loader folder, there should be a arch.conf and arch-fallback.conf 
`cryptdevice=UUID={UUID}:cryptlvm root=/dev/mapper/r00t quiet rw`
The above line is required for LUKS partition whereby UUID including { } should be replaced with the UUID of the LVM itself. You may check it with lsblk -f or fdisk -l but make sure the UUID is from the volume and not just the mapper you have opened. 
leave chroot and umount.
restart. 
If you see this post a few years later and is stuck, feel free to send me an email or a message and i will try to help. 
Many thanks to @Edu4rdSHL and @ikstream for helping out or i will still be sobbing.
