### ISSUE TITLE
[Tool Request] GG_Images

### ISSUE THREAD

**Issue by rua2p** [BlackArch/blackarch#3062]
- **Name**:
GG_Images
- **Source URL**:
https://codeberg.org/nanoory/GG_Images
- **Description**:
Good for OSINT for downloading photos from gg.pl

**Comment by Jagroop-Singh** [comment]
Hey there, I've built and tried out the PKGBUILD, as well as building through their build method, and I'm seeing errors with most of the functionality not working. Not sure if the error is on their side or on mine, I'm doing some troubleshooting to see if I can get it to work, just using git clone and go build.

**Comment by Jagroop-Singh** [comment]
@rua2p Have you gotten this working on arch linux?

**Comment by Jagroop-Singh** [comment]
I've tried everything to get it to work. 
Methods Tried:
downgrading go to 1.15
using gcc-go
downloading and running the elf executable from codeberg
git cloning and building 
building an earlier version
building an earlier version from zip file instead of tar.gz file

So far, I'm receiving the same error, where I can launch the app, however the only things that show are three tabs, welcome, about, and downloading, with me being unable to do anything on them.

**Comment by ikstream** [comment]
![snip_2021-06-04-15:06:46](https://user-images.githubusercontent.com/5787845/120805946-98fc8280-c546-11eb-88fd-735fa01d0bb2.jpg)

You have to actually click the arrow to make the download section expand. Works so far for me

**Comment by Jagroop-Singh** [comment]
https://gist.github.com/Jagroop-Singh/c4a95490d023c645a5cf03b1dfc852a0

**Comment by Jagroop-Singh** [comment]
oh, must be a misconfiguration on my pc. The PKGBUILD I made might still work then, I'll add the dependencies and then try it on a fresh image, to see if I can get it to work.

**Comment by Jagroop-Singh** [comment]
I'm dumb, yeah, the dropdown appears when you click the arrow next to Download, I just assumed it wasn't working because I was receiving weird errors about the fyne library. Okay, I'll just polish up the PKGBUILD and submit a pull request sometime later today.

**Comment by D4imyo** [comment]
@Jagroop-Singh did you submit a pull request ?

**Comment by Jagroop-Singh** [comment]
I've been busy with classes to test it, I'll test it sometime today or tomorrow, and send the pull request. In my current system it works fine, so it should be good.

**Comment by Jagroop-Singh** [comment]
This is done, thanks to the help of @pwnfoo in fixing some of the styling and dependency issues.

**Comment by D4imyo** [comment]
this issue should be closed 
 #3165
