### ISSUE TITLE
JD-GUI package refactoring

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3063]
Type: Discussion

## Discussion

I was wondering if [jd-gui PKGBUILD](https://github.com/BlackArch/blackarch/blob/master/packages/jd-gui/PKGBUILD) could be improved:

- migrating from gtk2 to gtk3?
- use 64 bits version instead of lib32?
- How to test with ba-dev since a X11 display is needed?
- are all the deps really needed?

**Comment by aancw** [comment]
Is GTK required by JD-GUI? There is no GTK package in AUR AL https://aur.archlinux.org/packages/?O=0&SeB=nd&K=jd-gui&outdated=&SB=n&SO=a&PP=50&do_Search=Go , as far as I know it's using Swing.

Testing JD-GUI run in GTK3 and GTK2

```
#Gtk3 forced:
env SWT_GTK3=1 jd-gui
 
#Gtk2 forced:
env SWT_GTK3=0 jd-gui
```

All is running well 

![image](https://user-images.githubusercontent.com/6284204/114171796-fc12d400-995e-11eb-9c2e-85602ff95764.png)

> How to test with ba-dev since a X11 display is needed?

Can we redirect the display to Xserver? Is there any experience about testing GUI app? @noptrix @Edu4rdSHL

**Comment by Edu4rdSHL** [comment]
@noraj you can simply set the `DISPLAY` variable and that should work. In my case I use a nspawn container (that has access to X server) and inside it the ba-dev environment. I used `ba-dev -p jd-gui-1.6.6-1-x86_64.pkg.tar.zst -e "DISPLAY=:0.0 jd-gui"` and it works. Anyways, that package is missing `libxtst` as dependency, without it you'll get: `libXtst.so.6:  cannot open shared object file: No such file or directory`

**Comment by noraj** [comment]
So `gtk2` dependency is not needed?

**Comment by Edu4rdSHL** [comment]
I didn't say that and I didn't even tested, I just said that with the actual PKGBUILD even the `libxtst` dep is missing.

**Comment by aancw** [comment]
> So `gtk2` dependency is not needed?

Reference to AUR there is no gtk dependencies

**Comment by noptrix** [comment]
@noraj any news on this? if not let's close it please

**Comment by noraj** [comment]
idk, I don't want to modify what I don't understand

**Comment by Tazmain** [comment]
Java swing shouldn't be dependant on GTK at all. Which environments do we want this to run in?

**Comment by D3vil0p3r** [comment]
[build.gradle](https://github.com/java-decompiler/jd-gui/blob/master/build.gradle) does not seem to mention any specific GUI deps like GTK. As mentioned, this app use Swing. In SwingUtil.java there are some functions mentioning GTK but I don't think they require any additional gtk dependency, otherwise we would get warnings or errors when launching the Java application. I'm not sure other deps like `'libsm' 'libxxf86vm'`. If I remove them, the application works correctly.

The only needed runtime dependencies are: `libxtst java-runtime`.

**Comment by D3vil0p3r** [comment]
This is my proposal: https://github.com/BlackArch/blackarch/pull/4231 Please let me know what you think and, if ok, I will switch from Draft to Open.
