### ISSUE TITLE
[Tool Request] - BruteShark

### ISSUE THREAD

**Issue by brainfucksec** [BlackArch/blackarch#3079]
- **BruteShark**
- **https://github.com/odedshimon/BruteShark**
- **Network Forensic Analysis Tool**

**Comment by brainfucksec** [comment]
The GUI of the program is unfortunately only for Windows, but for Linux there is a [CLI version](https://github.com/odedshimon/BruteShark#brutesharkcli)

**Comment by Edu4rdSHL** [comment]
I wonder if the Windows GUI is compatible with Wine, we can have both versions in that case.

**Comment by D3vil0p3r** [comment]
I know it is also in Kali, but I'm not sure if it has only CLI version or also GUI over Wine. It could be a nice to have in BlackArch

**Comment by D3vil0p3r** [comment]
The project seems no more maintained, and the tool uses deprecated version of OpenSSL and it seems bugged. I would not add it.
