### ISSUE TITLE
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid

### ISSUE THREAD

**Issue by dchara01** [BlackArch/blackarch#3081]
I am getting the below on `pacman -Syyuu`

 blackarch               3.4 MiB  5.52 MiB/s 00:01 [#######################] 100%
 blackarch.sig         566.0   B  0.00   B/s 00:00 [#######################] 100%
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid
error: failed to update blackarch (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases

**Comment by Edu4rdSHL** [comment]
1. Don't use `-Syyuu`, that's unnecessary, `-Syu` is fine.
2. Read: https://www.blackarch.org/faq.html

**Comment by Ringroad28** [comment]
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is unknown trust
error: no operation specified (use -h for help)
<orrupted database (PGP^Jsignature))

**Comment by Xerips** [comment]
This happens whenever I change the default mirror list (just commenting/uncommenting what's there by default). It's super annoying and I've never had this issue with any other repository. None of the fixes work except for setting the `SigLevel =` to `Never` which is terrible for security purposes.

**Comment by anunna** [comment]
```
echo "F9A6E68A711354D84A9B91637533BAFE69A25079:4:" >> /usr/share/pacman/keyrings/blackarch-trusted
pacman-key --populate
```
