### ISSUE TITLE
Cameradar is compiled with hardcoded path prefixes which can't exist

### ISSUE THREAD

**Issue by sempervictus** [BlackArch/blackarch#3082]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Cameradar won't run even with explicitly specified credential config

### Steps to reproduce

- Run `cameradar` or `cameradar -c /usr/share/cameradar/dictionaries/credentials.json`
- Fail

**Actual result:** 
```
$ cameradar
Invalid credentials dictionary: could not read credentials dictionary file at /usr/share/cameradar//src/github.com/Ullaakut/cameradar/dictionaries/credentials.json:: open /usr/share/cameradar//src/github.com/Ullaakut/cameradar/dictionaries/credentials.json: no such file or directory
$ cameradar -c /usr/share/cameradar/dictionaries/credentials.json
Invalid routes dictionary: open /usr/share/cameradar//src/github.com/Ullaakut/cameradar/dictionaries/routes: no such file or directory
```
**Expected result:**
The github repo/build-time gopath shouldn't be in the binary's search paths

**Comment by Edu4rdSHL** [comment]
Hello, the issue has been fixed, I have tested it.

**Comment by Loki-Norse-Github** [comment]
###- [ ] 3/88~~773~~)3;Yeah him Sripflm xf(4;;;;(I try calling seedless  phone l
- [ ] off the wall r red edk3:(4;3;.34;;;24@,44;(

**Comment by sempervictus** [comment]
Thank you
