### ISSUE TITLE
BlackArch can't -Syyu (update/upgrade)

### ISSUE THREAD

**Issue by 4dimensio** [BlackArch/blackarch#3084]
Type: Question

## Question
So I just built installer USB. Installed and setup on SSD. All is going well synced everything, going fine but I need to update and upgrade BlackArch 2020.12.01, makes sense right???
But I am now having hell trying to do this and getting errors. Please look at picture. 
Can someone help out,please???
![IMG_20210425_143628](https://user-images.githubusercontent.com/46723024/116005738-4f7b5800-a5d6-11eb-8a65-208642128bb7.jpg)

**Comment by Edu4rdSHL** [comment]
If you encounter a 'replace python2-twisted with python-twisted' message in your next upgrade say 'Y'. If it fails due to obfsproxy depending on python2-twisted remove it via pacman -Rns obfsproxy and rerun pacman -Syyu. We've removed obfsproxy and replaced python2-twisted with python2-twistedx

**Comment by 4dimensio** [comment]
Thank you that worked!!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
