### ISSUE TITLE
Checking package integrity... 

### ISSUE THREAD

**Issue by 4dimensio** [BlackArch/blackarch#3089]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Describe here the issue that you are experiencing.

### Steps to reproduce

- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Info for developers

**Device:** Manufacturer Model XVI (Only if you consideer needed, for example, network cards)
**GNU/Linux distribution:** (If you are using one distro that is not BlackArch, example: Manjaro, Anarchy, etc)
**Tool version:** 0.0.0

### Link to debug log

So I'm doing the update/upgrade for 2020.12.01 and it's failing on this
Error; script: signature  from "Orhun Parmaksiz <orhun@archlinux.org>" is u unknown trust
File /var/cache/pacman/pkg/scrot-1.5-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted pacakge (PGP signature)). 
So I delete ot re-run.... Pac-Man -Syyu it Re downloads but still same thing.  This was a huge download over 23gb and I really am lost here

**Comment by Edu4rdSHL** [comment]
Hi, the commands to fix it are:

```
pacman -Sy archlinux-keyring blackarch-keyring && pacman -Syu
```
