### ISSUE TITLE
Checking files for conflicts

### ISSUE THREAD

**Issue by 4dimensio** [BlackArch/blackarch#3090]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Describe here the issue that you are experiencing.

### Steps to reproduce

- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Info for developers

**Device:** Manufacturer Model XVI (Only if you consideer needed, for example, network cards)
**GNU/Linux distribution:** (If you are using one distro that is not BlackArch, example: Manjaro, Anarchy, etc)
**Tool version:** 0.0.0

### Link to debug log

New error doing this upgrade. 
error: failed to commit transaction (conflicting files) 
crackmapexec: /usr/bin/cme exist in filesystem
crackmapexec: /usr/bin/cmedb exist in filesystem
crackmapexec: /usr/bin/crackmapexec exist in filesystem.... 
errors occurred,  no packages were upgraded. 

Any help would be great

**Comment by Edu4rdSHL** [comment]
Use `--overwrite='*'` and please at least try to complete the bug template, it was created for one reason. Next time you don't fill the template I will close the issue without explanation.

**Comment by 4dimensio** [comment]
Thank you sir for the help, it is much appreciated. I do do that but blackaech then wants to download more.  Something like 3.5gb. I use... pacman -Syyu --needed blackarch --overwrite=`*` or Pac-Man -Syu --needed --overwrite ='*' blackarch and then it tells me I have to download now 10gb more.  Well I already have downloaded 8gb with
pacman -Syyu.
Can't I just do Pac-Man -R <file> and be done with it?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Edu4rdSHL** [comment]
I didn't told you to put "blackarch" in any place, just add `--overwrite='*'` to your initial command. Adding `blackarch` you're telling to pacman "install all the tools in the repo".

**Comment by 4dimensio** [comment]
I know but I was reading the blacksrch FAQ in there website snd it said I should use it.
So thank you for the clarification .
I will use pacman  -Syyu --overwrite=`*`.
Thank you for your time and understanding .

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by 4dimensio** [comment]
Well when I use --overwrite='*' in any command I get...
bash: bin: command not found

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by noraj** [comment]
Use:

```
$ sudo pacman -Syu --overwrite /usr/bin/cme --overwrite /usr/bin/cmedb --overwrite /usr/bin/crackmapexec
```

**Comment by 4dimensio** [comment]
Thank you I will give that a try tonight when I get home.  I hope that works

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by aancw** [comment]
```
$ sudo pacman -S crackmapexec --overwrite="usr/*"
warning: crackmapexec-620.15df163-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) crackmapexec-620.15df163-2

Total Installed Size:  16.11 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                                                  [##############################################################################] 100%
(1/1) checking package integrity                                                                                                [##############################################################################] 100%
(1/1) loading package files                                                                                                     [##############################################################################] 100%
(1/1) checking for file conflicts                                                                                               [##############################################################################] 100%
(1/1) checking available disk space                                                                                             [##############################################################################] 100%
:: Processing package changes...
(1/1) reinstalling crackmapexec                                                                                                 [##############################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

**Comment by 4dimensio** [comment]
Thank all of you guys.  When I get home tonight from work,  I'll try everything.
Maybe I did mistype but it did state ...
bash: bin: command not found

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by 4dimensio** [comment]
I'll re-run... Pac-Man -Syyu and do the update/upgrade.  It's around 7.5gb

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Edu4rdSHL** [comment]
@4dimensio you aren't posting logs, screenshots, or giving any exact message. When the error happens please send THE FULL log from the moment that you write the command.

**Comment by 4dimensio** [comment]
Sure will tonight when I run ...
Pac-Man -Syyu

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Edu4rdSHL** [comment]
If you run "Pac-Man -Syyu" it will not work. Please read https://wiki.archlinux.org/title/Pacman

Locking this issue.
