### ISSUE TITLE
BLACKARCH INSTALLATION

### ISSUE THREAD

**Issue by computerhead254** [BlackArch/blackarch#3091]
Type: Question
Can i get any assistance from this team please?? i have been lately installing BLACKARCH_SLIM_2021.iso and i experience this error when installing.
 
**"mounting '/dev/disk/by-label/BLACKARCH_202103' to '/run/archiso/bootmnt'
waiting 30 seconds for device /dev/disk/by-label/BLACKARCH_202103.."

ERROR: '/dev/disk/by-label/BLACKARCH_202103' device did not show up after 30 seconds.. falling back to interactive prompt
you can try to fix the problem manually, log out when you are finished
can't access tty: job control turned off 
[Rootfs: ]#**

 can i get any solution to this??
the error in the following image:>>
![WhatsApp Image 2021-05-03 at 12 37 38 PM](https://user-images.githubusercontent.com/58890748/116864159-1499a580-ac10-11eb-91b5-85e51b87c3fa.jpeg)

**Comment by ikstream** [comment]
Did you install it on your hardware, a virtual machine or is this the startup of a live medium?

If it is the live medium, did you verify the checksum of the downloaded iso file before flashing?

**Comment by computerhead254** [comment]
> 
> 
> Did you install it on your hardware, a virtual machine or is this the startup of a live medium?
> 
> If it is the live medium, did you verify the checksum of the downloaded iso file before flashing?

it is a slim iso found in blackarch.org  and its an installer its not live. am installing for a dual boot on startup and not a virtual machine.

**Comment by ikstream** [comment]
How did you install the system? This looks a lot like the messages from a flashed USB stick. 

Did you verify the checksum of the iso and what tools did you use to create the boot medium?

**Comment by computerhead254** [comment]
> How did you install the system? This looks a lot like the messages from a flashed USB stick.
> 
> Did you verify the checksum of the iso and what tools did you use to create the boot medium?

yeah i was installing from a USB stick . I did not verify the checksum however since i downloaded it from the official blackarch website but it seems to work fine when i use it on my virtual machine.

**Comment by ikstream** [comment]
The checking was more about errors in downloading the iso, not manipulation in my question. 

Did you use the GUI installer to install blackarch?

Please boot from the USB stick again. Mount your partitions, you installed Blackarch and chroot into it. Check if the entries in `/etc/fstab` match with the labels or UIDs from `lsblk`

**Comment by computerhead254** [comment]
i did not not install the OS because it brings this error screen after i enter the install command. during the installation wizard it means that i was not able to access  the GUI.

**Comment by ikstream** [comment]
So it is a problem with the live medium. 
How did you flash the USB stick? Verify that the checksum matches and  reflash the USB stick if they match.

If you use windows to flash it, use `rufus` in DD mode, if linux use `dd`

**Comment by computerhead254** [comment]
> 
> 
> So it is a problem with the live medium.
> How did you flash the USB stick? Verify that the checksum matches and reflash the USB stick if they match.
> 
> If you use windows to flash it, use `rufus` in DD mode, if linux use `dd`

yes i used the following procedure but was not successful... but i dont know how to verify the checksum

**Comment by ikstream** [comment]
If you use windows, there seem to be multiple options:
- https://www.addictivetips.com/windows-tips/check-the-checksum-of-a-file-windows-10/
- https://answers.microsoft.com/en-us/windows/forum/windows_10-security/finding-checksum-values-in-windows-10/dbc3c569-4b5a-4967-8810-c25255cdc1fd

If your regular system is a Linux, use `sha1sum`. You need to compare the output with the checksum on blackarch.org

**Comment by computerhead254** [comment]
the  following are the hashes from the original site blackarch.org and the file itself for the image file blackarch_slim.iso


![black hash](https://user-images.githubusercontent.com/58890748/117163846-b9f97880-adcc-11eb-80e7-fbcb07421a0d.PNG)
![black slim](https://user-images.githubusercontent.com/58890748/117163869-bf56c300-adcc-11eb-8e64-ad25262fb626.PNG)

**Comment by ikstream** [comment]
Have you tried flashing a different iso to the USB-stick and booting from it before?

**Comment by computerhead254** [comment]
> 
> 
> Have you tried flashing a different iso to the USB-stick and booting from it before?

no i have not tried.. lemme try

**Comment by ikstream** [comment]
As there hasn't been any activity for 9 days, i am closing this issues, feel free to reopen, if your issue is not solved.

**Comment by KELVIN25509** [comment]
The activity was amazing
