### ISSUE TITLE
the_cleaner. sh

### ISSUE THREAD

**Issue by 4dimensio** [BlackArch/blackarch#3094]
Type: Question

## Question
Has the (the_cleaner. sh) been removed or renamed?  I can't seam to find it or run it from terminal
I would like to clean my Blackarch from all the downloads and wasted files just laying around.

**Comment by Edu4rdSHL** [comment]
It's part of `secure-delete`

**Comment by 4dimensio** [comment]
thank you sir

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
