### ISSUE TITLE
Cannot install BlackArch tools on an existing Arch

### ISSUE THREAD

**Issue by K-S3curity** [BlackArch/blackarch#3095]
Hi ! 
I experience issues while trying to install BlackArch tools on my Arch Linux machine.

I've downloaded the strap.sh script from the Official website and executed it, then, I ran the following command : 
pacman -S blackarch
The problem is that pacman cannot satisfy the dependencies of some tools.

Here is a screenshot
![image](https://user-images.githubusercontent.com/66269273/117588436-cb1af000-b112-11eb-9b51-c6022757cdbc.png)

Can someone help me please ?

**Comment by Edu4rdSHL** [comment]
Have you enabled `[multilib]` as advised on the downloads page?

**Comment by K-S3curity** [comment]
No I didn't

**Comment by Edu4rdSHL** [comment]
Ok, do it and try again then. That will solve your issue.

**Comment by K-S3curity** [comment]
Thanks for your help
