### ISSUE TITLE
BlackArch fresh install strap.sh checksum mismatch

### ISSUE THREAD

**Issue by bman120** [BlackArch/blackarch#3096]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

BlackArch install fails at bootstrap script with latest NetInstall ISO: "blackarch-linux-netinst-2020.12.01-x86_64.iso" due to checksum mismatch:
```sh
$ Wrong SHA1 sum for strap.sh: d062038042c5f141755ea39dbd615e6ff9e23121 (orig: 95b485d400f5f289f7613fe576f4a3996aabed62). Aborting!"
```

### Steps to reproduce

- Download latest NetInstall ISO from blackarch.org
- Execute `blackarch-install`
- Install updated blackarch-installer package (as prompted)
- Re-execute blackarch-install
- Root file system encrypted or unencrypted (tried both, either option does not change outcome)
- Do not create separate user account when prompted (should not change outcome)
- Select timezone (America/Eastern)
- Select Mirror (tried multiple different ones - does not change outcome)

**Actual result:** 
Install script first executes and updates to the latest version of blackarch installer (1.2.20-1). Re-run `blackarch-install` and follow all prompts. Immediately following the mirror selection (regardless of mirror) receive error above. 
Manually run steps from `blackarch-install` script:

```sh
$ curl -s https://blackarch.org/checksums/strap | awk '{print $1}'
95b485d400f5f289f7613fe576f4a3996aabed62
```

```sh
$ curl -s -o $strap_sh 'https://www.blackarch.org/strap.sh' > $VERBOSE 2>&1
d062038042c5f141755ea39dbd615e6ff9e23121
```

**Expected result:** 
`blackarch-install` executes successfully, and the manual commands above result in matching checksums

### Screenshots

![Screenshot from 2021-05-10 20-27-32](https://user-images.githubusercontent.com/16708617/117740276-17773600-b1ce-11eb-84c6-46b120fdf434.png)
![Screenshot from 2021-05-10 20-03-18](https://user-images.githubusercontent.com/16708617/117739084-8d2dd280-b1cb-11eb-8b99-0f4ada06c7c0.png)
![Screenshot from 2021-05-10 20-28-38](https://user-images.githubusercontent.com/16708617/117740342-3d9cd600-b1ce-11eb-95d9-4c4ffa912864.png)
![Screenshot from 2021-05-10 20-31-55](https://user-images.githubusercontent.com/16708617/117740563-b4d26a00-b1ce-11eb-8fdb-185218f0f8ee.png)

### Info for developers

**Device:** GNOME Boxes VM 
**GNU/Linux distribution:** Arch kernel 5.12.1-arch1-1; GNOME 40.1
**Tool version:** 1.2.20-1

**Comment by Edu4rdSHL** [comment]
I have successfully reproduced the issue and it¿s being fixed in a few minutes. Thank you for reporting.

**Comment by bman120** [comment]
Confirmed it's working as expected now. Thank you!
