### ISSUE TITLE
Blackarch in VM

### ISSUE THREAD

**Issue by 4dimensio** [BlackArch/blackarch#3100]
Type: Question
I have BLackarch install as a vm.  I have install the virtualbox tools in Blackarch.  Also have made sure in virtualbox that move files (to & from)  bi-directional between guest and host as well as clipboard.  I still can't do it,  So is there some other tools/files I need to install in Blackarch
to utilize (click&drag=folders/files : copy&paste=text) 
Or is Blackarch Harden and does not allow for such operations?

**Comment by Edu4rdSHL** [comment]
What is your host OS?

**Comment by 4dimensio** [comment]
It is unfortunately Win10 home

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Edu4rdSHL** [comment]
What do you mean by " I have install the virtualbox tools in Blackarch", which packages have you installed?

**Comment by 4dimensio** [comment]
I am using virtualbox 6.1.22 with the expansion pack for thus version of virtualbox... if I remember correctly what I installed in my Blackarch vm was.....
virtualbox-guest-edition-utlize

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Edu4rdSHL** [comment]
What do you need to install is the `virtualbox-guest-utils` package through pacman.

**Comment by 4dimensio** [comment]
thank you sir,  I will give it a go in the morning and let you know...
sudo pacman -S virtualbox-guest-utils

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by 4dimensio** [comment]
Well I did the....sudo pacman -S virtualbox-guest-utils and I received a conflict with virtualbox-guest-utils dkms.  So I removed the "virtualbox-guest-utils dkms" and installed the  virtualbox-guest-utils and then did a (-Syyu)  to download and sync packages,  rebooted and still can not "drag/drop" or "copy/paste" from host to Blackarch vm.  So I'm at a lost here, I am just trying to not to "manually" type all my cmds or list.  So any ideas sir?

**Comment by noraj** [comment]
@4dimensio https://blog.raw.pm/en/archlinux-installation-in-virtualbox/#Install-the-Guest-Additions

**Comment by 4dimensio** [comment]
thanks I'll try that tonight when I get off work

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by 4dimensio** [comment]
sudo systemctl enable vboxservice
does not work.  Still can not drag drop

**Comment by noraj** [comment]
> sudo systemctl enable vboxservice
> does not work. Still can not drag drop

https://wiki.archlinux.org/title/VirtualBox/Install_Arch_Linux_as_a_guest
