### ISSUE TITLE
Broken package for tool `Arjun`

### ISSUE THREAD

**Issue by theEndurance-del** [BlackArch/blackarch#3101]
## Bug Description ##
The package `arjun` was installed as a dependency for the `legion` package.
But it seems that the package for `arjun` is broken.

* Reason: * Arjun does not launch

## Steps to reproduce ##
- `sudo pacman -Sy legion`
- `arjun`
- Error: `'/usr/share/arjun/arjun.py' no such file or directory`
## Screenshot ##
![Screenshot_2021-05-14_11-56-11](https://user-images.githubusercontent.com/57960301/118231168-58ac6600-b4ac-11eb-8741-55385df27d27.png)

[x] Mitigated manually

## Mitigation ##
- `sudo pacman -Rdd arjun`
- `sudo python3 -m pip install arjun`

*This has apparently fixed the issue permanently, because it never occurred after that even after installing the tool from repository.*

Distribution: `Blackarch Linux` (installed via blackarch slim ISO).

**Comment by Edu4rdSHL** [comment]
Update the `arjun` package, it was fixed days ago in https://github.com/BlackArch/blackarch/commit/005270ef6633852a8c763208ffe1a78f6989c0fb
