### ISSUE TITLE
evil-winrm: cannot load such file -- rexml/document (LoadError)

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3102]
### Bug description

evil-winrm runtime broken because of a dependency

https://github.com/WinRb/WinRM/issues/328

### Steps to reproduce

`ba-dev -e 'evil-winrm -h' -p evil-winrm-267.3c318f1-2-any.pkg.tar.zst`

**Comment by noraj** [comment]
In a worst case scenario we could rebuild with the lock gemfile using older dependencies

https://github.com/BlackArch/blackarch/blob/a2feef2302581c7ad7bccc5004d981770157617a/packages/evil-winrm/evil-winrm.install#L4

**Comment by OscarAkaElvis** [comment]
This commit was done on evil-winrm to fix it: https://github.com/Hackplayers/evil-winrm/commit/83bc6ec050aaa97500ef6ff1ccd535d180ddb598

**Comment by noraj** [comment]
@OscarAkaElvis Tell me when the dev branch will be merged in master branch.

**Comment by OscarAkaElvis** [comment]
Ok, I will. We are taking some time because new version of evil-winrm will have remote path completion and is complicated. 😄 But we are so close to finish it.
