### ISSUE TITLE
owasp maryam - Update needed

### ISSUE THREAD

**Issue by necrose99** [BlackArch/blackarch#3108]
OWASP Maryam is a modular/optional open source framework based on OSINT and data gathering
https://pypi.org/project/maryam/

[PKGBUILD.Maryam.txt](https://github.com/BlackArch/blackarch/files/6563633/PKGBUILD.Maryam.txt)

enjoy

**Comment by ikstream** [comment]
Maryam is already included in our repos, it needs an update though

**Comment by noraj** [comment]
> OWASP Maryam is a modular/optional open source framework based on OSINT and data gathering
> https://pypi.org/project/maryam/
> 
> [PKGBUILD.Maryam.txt](https://github.com/BlackArch/blackarch/files/6563633/PKGBUILD.Maryam.txt)
> 
> enjoy

Next time check our [tool page](https://blackarch.org/tools.html) or use pacman search feature:

```
$ pacman -Ss maryam                                                                                                                                                                                                                        
blackarch/maryam 2:462.473f218-1 (blackarch blackarch-scanner blackarch-webapp blackarch-recon)
    Full-featured Web Identification framework written in Python.
```
