### ISSUE TITLE
reconftw

### ISSUE THREAD

**Issue by dualfade** [BlackArch/blackarch#3112]
- **reconftw**:
- **https://github.com/six2dez/reconftw**:
- **ReconFTW automates the entire process of reconnaisance for you. It outperforms the work of subdomain enumeration along with various vulnerability checks and obtaining maximum information about your target.**:

**Comment by dualfade** [comment]
This tool works very well. If interested I will package it up --

**Comment by noraj** [comment]
🤔 I'm very dubious about wrapper tools that claims to **automates the entire process of reconnaisance**, **checks like XSS, Open Redirects, SSRF, CRLF, LFI, SQLi, SSL tests, SSTI, DNS zone transfers, and much more.**, **performs OSINT techniques, directory fuzzing, dorking, ports scanning, screenshots, nuclei scan on your target**.

I also doubt we will be able to reasonably translate [install.sh](https://github.com/six2dez/reconftw/blob/main/install.sh) into a PKGBUILD.

**Comment by Edu4rdSHL** [comment]
cc @six2dez

**Comment by six2dez** [comment]
Hey! @dualfade thanks to propose my tool to 
be packaged for Blackarch. As @noraj said, the install script provided performs a lot of steps and I don't know if it could be easily packaged. Anyway If you want try to, I would be able to help you with anything.

About the purpose of the tool, it's main objective is to collect the more subdomains possible and do some operations over them and it does very well imho, the rest of "attack automations" are just extra features added to help with the recon process. Like the osint part, it's just to provide the whole picture about your target.

**Comment by dualfade** [comment]
@six2dez  Thanks. I ran it in docker without issues and it runs great. But yes very good point on packaging. I / we may may just hold up on that. Thanks for the response. Appreciate it.

**Comment by dualfade** [comment]
Gonna hold. Thanks All.
