### ISSUE TITLE
Zeus-scanner

### ISSUE THREAD

**Issue by Aguamandan** [BlackArch/blackarch#3114]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Zeus-scanner tool fails to run. Re-installed with same outcome:
````
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
File "/usr/share/zeus-scanner/zeus.py", line 10, in <module>
from var import blackwidow
File "/usr/share/zeus-scanner/var/blackwidow/__init__.py", line 6, in <module>
import lib.core.common
File "/usr/share/zeus-scanner/lib/core/common.py", line 19, in <module>
import lib.core.settings
File "/usr/share/zeus-scanner/lib/core/settings.py", line 38, in <module>
PATCH_ID = str(subprocess.check_output(["git", "rev-parse", "origin/master"]))[:6]
File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'origin/master']' returned non-zero exit status 128.
````

### Steps to reproduce

enter 
````
sudo zeus-scanner
````
or just
````
zeus-scanner
````
in terminal. 
Figured I'd report it, I really don't have time to fix all the broken code I encounter. If this was the incorrect procedure, please let me know.

**Actual result:** 
Tool does not run.

**Expected result:** 
Tool runs.

### Screenshots

Code included above

### Info for developers

````
uname -a
Linux Harbinger 5.12.8-arch1-1 #1 SMP PREEMPT Fri, 28 May 2021 15:10:20 +0000 x86_64 GNU/Linux
````

**Device:** HP Omen: 15-dc0051nr
**GNU/Linux distribution:** BlackArch installed over existing Arch
**Tool version:** zeus-scanner-414.21b8756-3

### Link to debug log

Not sure what exactly is being requested here.

**Comment by ikstream** [comment]
Thank you for reporting.

Zeus-scanner hasn't  seen much love since 2018 and no update since 2019. I am looking into it, but even their docker version (with modified Dockerfile to make it run at all) doesn't work and has a lot of open (duplicated) [issues](https://github.com/Ekultek/Zeus-Scanner/issues)

**Comment by ikstream** [comment]
There are several upstream issues, that need to be addressed by the maintainer. Unfortunately it seems like zeus-scanner is no longer maintained. Therefore we are going to remove the binaries from our repository for now.
