### ISSUE TITLE
broken packages

### ISSUE THREAD

**Issue by trevalkov** [BlackArch/blackarch#3115]
Type: Question
I have recently upgraded my system with 'sudo pacman -Syu', during this some packages got broken and rendering pip useless. l have tried building the packages from source from I still get the same "syntax error" when I run pip. I have fixed the problem by reinstalling the system (xD), just wondering if anyone knows anything about this issue.
Thank you.

**Comment by ikstream** [comment]
Without anything specific, like which packages broke, this issue does not provide any value. Your problem is obviously fixed. If you provide additional _detailed_ information feel free to reopen the issue.

**Comment by noraj** [comment]
`sudo pip install` = conflict with python system package = broken system

1. (Better) Only use `python-xxx` package from AL/BA repository
2. pip install in a virtual environment when needer
3. **NEVER** run `sudo pip install`

**Comment by Edu4rdSHL** [comment]
`pip install $package --user` will save you from breaking things at system level.
