### ISSUE TITLE
Requesting a new tool

### ISSUE THREAD

**Issue by pythagonist** [BlackArch/blackarch#3124]
- **name**: pwsort
- **Source URL**: https://github.com/pythagonist/pwsort
- **Description**: pwsort is a tool, which can be used on leaked password files. With it's function you can easily create a password-file for cracking. It sorts passwords/other items by their sum of duplicates, or just by their popularity. The speed of doing so relies on the computers hardware. Fully coded in Python.

**Comment by pwnfoo** [comment]
Hey @pythagonist, we will not be adding this tool because built-ins like `sort` and `uniq` can accomplish this much faster than Python.

`cat wordlist | sort | uniq -c | sort -rn` does the trick.

If you plan to add more features in the future, please open an issue again!

**Comment by noraj** [comment]
@pwnfoo You are right also there is already Duplicut https://github.com/BlackArch/blackarch/issues/2937 which does that but in `C` and is much faster.

**Comment by pythagonist** [comment]
I see. Thank you for clearing me up. I understand that this tool mentioned above is way more complex and better than mine. Maybe I'll try and find a better solution...
Greetings
