### ISSUE TITLE
Genisys

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3128]
- **Name**: Genisys
- **Source URL**: https://github.com/Cryptonian007/Genisys
- **Description**: Telegram Members Scraping and Adding Toolkit

Asked by noptrix#4216

**Comment by noraj** [comment]
I don't believe this belongs to BA repo but this is a bit in the greyzone as it can sued for (cl)OSINT.

**Comment by D4imyo** [comment]
this tool already exist in the BA repo

**Comment by noraj** [comment]
Right noptrix added it 4 months ago https://github.com/BlackArch/blackarch/blame/master/packages/genisys/PKGBUILD
