### ISSUE TITLE
nzyme

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3130]
- **Name**: nzyme
- **Source URL**: https://github.com/lennartkoopmann/nzyme
- **Description**: WiFi defense system

asked by Edu4rdSHL#5506

**Comment by noraj** [comment]
Is not BA focused on offensive security? How can it be used in a wifi pentest?

**Comment by Edu4rdSHL** [comment]
BlackArch is focused on hacking, not offensive or defensive only, there are already plenty of defensive tools such as:

- wireless-ids
- sniffjoke
- zeus
- zeek

and more.

Just take a look at the `blackarch-defensive` group.

**Comment by noraj** [comment]
![image](https://user-images.githubusercontent.com/16578570/121310223-6dd9b080-c903-11eb-9e56-d46c9aefebca.png)

We should change pentest into cybersecurity then.
