### ISSUE TITLE
Elevate

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3131]
- **Name**: Elevate
- **Source URL**: https://github.com/Healdb/Elevate
- **Description**: takes in a partial organization name, an email address, or a domain name, and finds all other domain names owned by that organization.

asked by Dmitry_Anderson#9739

**Comment by D4imyo** [comment]
this tool would be under "blackarch-misc" and "blackarch-webapp", right ?

**Comment by ikstream** [comment]
I would probably put it in `blackarch` and `blackarch-recon` as it is a domain finder, similar to `subfinder` etc
