### ISSUE TITLE
BurpSuite Broken Package Dependencies

### ISSUE THREAD

**Issue by Ezteb** [BlackArch/blackarch#3133]
- I used a rootfs from dlwsl project to install archlinux on the new WSLg of Windows 10 Insiders Dev build 21390.1010
- Procceded to add the BlackArch repository using the strap.sh script from te official page
- Installed BurpSuite community edicion correctly
-  It won't run asking for diferent *.so files
    * Installing libxext, libxrender and lixtst corrected this behaviour
- Now starting burpsuite hive the folowing error:
    *  "Could not start Burp: java.lang.InternalError: java.lang.reflect.InvocationTargetException"
    *  Installing java-openjfx fix this error and burpSuite start running in GUI mode
- Now can't open burp browser whit the error:
    * "net.portswigger.devtools.client.p: Refusing to start browser as your current configuration does not support running without sandbox"
    * Solved folowing: https://forum.portswigger.net/thread/burp-embedded-browser-feature-chromium-sandbox-issue-a1d3816e

**Comment by Edu4rdSHL** [comment]
WSL is not officially supported. The tool runs fine in a native installation.

**Comment by Edu4rdSHL** [comment]
Additionally, every package in the repos assume that the base and base-devel packages are installed in the environment.

**Comment by Ezteb** [comment]
Thanks for the aclaration!!!
WSL is not more that a virtual machine so a vanilla arch install can have a similar issue.
I'm stuck whit windows for propietary software for work and I only starting on linux and cibersecurity so I just wanna try to help in any way i can to people on similar situation!!! XD

**Comment by Edu4rdSHL** [comment]
Hello, the `'libxext' 'libxrender' 'libxtst'` dependencies were definitely missing but apart from it everything works fine. ` java-openjfx` shouldn't be needed and is not needed because we are already using the `java-runtime` package required which also installs `jre-openjdk`. Regarding the sandbox thing, it's required if you run it as root but we don't have anything to do there.

**Comment by Ezteb** [comment]
you are right!!! I uninstalled java-openjfx on my WSL instance and is working fine!! the real problem apart 'libxext' 'libxrender' 'libxtst' was runing it as root!!!

**Comment by Ezteb** [comment]
thanks for the time and the great work!!!

**Comment by Edu4rdSHL** [comment]
Thank you for reporting it.
