### ISSUE TITLE
Unable to install blackarch tools in raspberry pi 4 with manjaro 

### ISSUE THREAD

**Issue by mrusli70** [BlackArch/blackarch#3135]
Type: Question

## Question
I am using the current version of Manjaro with KDE plasma environment. Manjaro version 21.04 64 bit version of arch linux. 
I cannot seems to install all the blackarch tools into my raspberry pi 4. 

I have list of issues. Such as ... 

Total Download Size:      26.99 MiB
Total Installed Size:  26050.63 MiB
Net Upgrade Size:      26030.38 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 openbsd-netcat-1...    23.6 KiB  2.89 MiB/s 00:00 [#########################] 100%
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from mirrors.dr460nf1r3.me : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from ftp.halifax.rwth-aachen.de : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from ftp.halifax.rwth-aachen.de : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from ftp.halifax.rwth-aachen.de : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from ftp.halifax.rwth-aachen.de : Protocol "rsync" not supported or disabled in libcurl
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from blackarch.unixpeople.org : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from blackarch.unixpeople.org : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from blackarch.unixpeople.org : Protocol "rsync" not supported or disabled in libcurl
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from mirror.undisclose.de : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from mirror.undisclose.de : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from mirror.undisclose.de : Protocol "rsync" not supported or disabled in libcurl
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from www.mirrorservice.org : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from www.mirrorservice.org : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from rsync.mirrorservice.org : Protocol "rsync" not supported or disabled in libcurl
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from mirror.zetup.net : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from mirror.zetup.net : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from blackarch.pr0s3c.nl : The requested URL returned error: 526
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from blackarch.pr0s3c.nl : The requested URL returned error: 526
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from mirror.math.princeton.edu : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from mirror.math.princeton.edu : Protocol "rsync" not supported or disabled in libcurl
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from distro.ibiblio.org : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from distro.ibiblio.org : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from deadbeef.ninja : The requested URL returned error: 404
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from mirror.team-cymru.com : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from mirror.team-cymru.com : Maximum file size exceeded
error: failed retrieving file 'skul-27.7bd83f1-2-aarch64.pkg.tar.zst' from mirror.team-cymru.com : Protocol "rsync" not supported or disabled in libcurl
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
[rusli@manjaro pacman.d]$ 

I cannot seems to install anything at all. Is there any simpler methods to solve this problem?

**Comment by noraj** [comment]
You don't have enough storage on your Rasp. Don't install all 2500 tools but only those you actually need.

**Comment by Edu4rdSHL** [comment]
@noraj that error is not related to storage but an issue with the mirror. 

@mrusli70 please try changing the mirror for BlackArch and try again.

**Comment by noraj** [comment]
Thx @Edu4rdSHL 

@mrusli70 In that case I suggest to to always have several mirrors enable at least 2-3 so when the first fails, timeout or 404 a package you have 1-2 fallback and don't fail the whole operation.

**Comment by Edu4rdSHL** [comment]
Closing because there was not feedback from the user.
