### ISSUE TITLE
Installer Unable to display Chinese

### ISSUE THREAD

**Issue by kouhe3** [BlackArch/blackarch#3138]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Installer Unable to display Chinese

### Steps to reproduce

Select Chinese in the Installer.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Chinese characters have become garbled

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

I can see Chinese.

### Screenshots

![image](https://user-images.githubusercontent.com/25522053/122671594-09b7c600-d1fa-11eb-8c77-c604f82117f6.png)

### Info for developers

**Device:** Manufacturer Model XVI (Only if you consideer needed, for example, network cards)

AMD A8-7500 Radeon R7, 10 Compute Cores 4C+6G     3.00 GHz

**GNU/Linux distribution:** 

BlackArch Linux 64 bit Slim ISO | 2021.03.01
-- | --

(If you are using one distro that is not BlackArch, example: Manjaro, Anarchy, etc)
**Tool version:** 0.0.0

**Comment by ikstream** [comment]
Thank you for reporting. 

To solve this issue on the fly, you can install `adobe-source-han-sans-cn-fonts`.
We will add the font in a new release to fix it on our site

**Comment by kouhe3** [comment]
adobe-source-han-sans-kr-fonts for Korean ， not for Chinese.
If you use it : 

![image](https://user-images.githubusercontent.com/25522053/122875639-1ad21580-d367-11eb-805a-7ea7777eab8d.png)

Still □□□□□

**Comment by ikstream** [comment]
I see, while checking, I might have missed some character. So it's probably best to add them all by them self

Thank you for pointing out

**Comment by kouhe3** [comment]
What about : 

https://archlinux.org/packages/extra/any/noto-fonts-cjk/

or

https://archlinux.org/packages/community/any/adobe-source-han-sans-otc-fonts/

Them support CJK(CJK：Chinese, Japanese, Korean)

**Comment by Edu4rdSHL** [comment]
Have you tested the previous mentioned fonts and they fix your problem? If yes, I will include the noto fonts package.

**Comment by kouhe3** [comment]
> Have you tested the previous mentioned fonts and they fix your problem? If yes, I will include the noto fonts package.

noto-fonts-cjk works in my BlackArch. Some Chinese Arch Linux users use this font too. 

![image](https://user-images.githubusercontent.com/25522053/123096545-ca8bae00-d461-11eb-8347-51c7d7eeb16d.png)

[chat history](https://t.me/archlinuxcn_group/2023907)

**Comment by ikstream** [comment]
> Have you tested the previous mentioned fonts and they fix your problem? If yes, I will include the noto fonts package.

Wouldn't the adobe font be suited better for sthe slim iso, as it is smaller compared to  the noto font?

**Comment by Edu4rdSHL** [comment]
> > Have you tested the previous mentioned fonts and they fix your problem? If yes, I will include the noto fonts package.
> 
> Wouldn't the adobe font be suited better for sthe slim iso, as it is smaller compared to the noto font?

Yes, but please include only one package. According to the user, `adobe-source-han-sans-otc-fonts` cover all cases as it supports CJK, so we can go with this instead of the noto fonts. If you add the weight of all fonts in https://github.com/BlackArch/blackarch-iso/pull/34/, size is larger than `adobe-source-han-sans-otc-fonts`

**Comment by kouhe3** [comment]
So,let's use adobe-source-han-sans-otc-fonts !

**Comment by ikstream** [comment]
I missread https://github.com/adobe-fonts/source-han-sans/issues/13 and thought, that the `cn` contains more symbols for only a few more storage compared to otc. But the opposide seems to be true. I will change the fonts to use otc
