### ISSUE TITLE
blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid

### ISSUE THREAD

**Issue by sevenday4** [BlackArch/blackarch#3141]
I have just tried to update my arch linux system in which I have Blackarch installed on top of. When doing the update, this error keeps showing itself:
blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid

I have tried reinstalling and updating the key and still getting the error. I guess the key needs to be updated.

**Comment by Edu4rdSHL** [comment]
Read [the FAQ](https://blackarch.org/faq.html)
