### ISSUE TITLE
File conflict in python-viv-utils

### ISSUE THREAD

**Issue by JanusTests** [BlackArch/blackarch#3156]
When issuing pacman -Syu get two conflicts within python-viv-utils.

<img width="1098" alt="Screenshot 2021-07-01 at 10 12 40 PM" src="https://user-images.githubusercontent.com/72477937/124138817-9cd5e300-dab9-11eb-8b3c-390b48d1135a.png">

**Comment by ikstream** [comment]
install the `python-viv-utils` package individualy with `--overwrite="*"` and do your update afterwards

**Comment by JanusTests** [comment]
Have tried this but to no avail ☹

**Comment by JanusTests** [comment]
Has worked on one device but not on another. No worries, I will fresh install Blackarch on the offending device. Thank you 😊
