### ISSUE TITLE
cannot run strap.sh file on arch linux

### ISSUE THREAD

**Issue by Prashant918** [BlackArch/blackarch#3159]
while installing blackarch  on top of my arch linux , i am getting the error it shows that 
[+] installing blackarch keyring
[-] Error: could not verify the key. Please check: https://blackarch.org/faq.html

what to do now ? i am trying almost form 1 day and i had tried all prossible solutiion related to problem.
please help me out

**Comment by ikstream** [comment]
Have you verified, that your system can resolve `keyserver.ubuntu.com` and `pgp.mit.edu`?
Also make sure that you system is synced in time with running e.g. `ntpd`.
Make sure you disabled VPNs, as some domains might Block certain provider. 

If all that does not work, try each key retrieval command from the script manually. If they fail, please provide the output.

**Comment by Prashant918** [comment]
I tried everything related to my error showing on my arch and i and I have also check what you had said but no result I found...
I am sharing my output here
<img width="805" alt="Screenshot 2021-07-11 at 11 27 38 PM" src="https://user-images.githubusercontent.com/46848568/125205436-dc61b380-e29f-11eb-9b2b-a6943076aa0a.png">

**Comment by Prashant918** [comment]
I have solved my problem on my own. Thanks for your help

**Comment by techvio1** [comment]
@Prashant918 can you show me how ? i'm currently facing the issue
