### ISSUE TITLE
StegoVeritas: module 'magic' has no attribute 'from_buffer' 

### ISSUE THREAD

**Issue by tylerstonge** [BlackArch/blackarch#3162]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

There seems to be an issue with the version of `python-magic` library which is causing an error in the StegoVeritas tool. It was marked as resolved in #2751 but I am seeing the issue on a new install of BlackArch with `sudo pacman -Syu --needed --overwrite='*' blackarch` run.

### Steps to reproduce

- attempt to run `stegoveritas` on an image: `stegoveritas test.jpg`
- the program will crash and complain about the `from_buffer` missing function.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

The application complains about a missing function.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The program runs stego analysis on the supplied image.

### Info for developers

**Tool version:** 1.8-2

### Link to debug log

```
>>> stegoveritas -d -carve reverse.jpg                 
INFO:StegoVeritas:Analyzing file: /home/dropkick/Downloads/reverse.jpg
INFO:StegoVeritas:Results Directory: /home/dropkick/Downloads/results
Running Module: SVImage
+------------------+------+
|   Image Format   | Mode |
+------------------+------+
| JPEG (ISO 10918) | RGB  |
+------------------+------+
DEBUG:StegoVeritas:Modules:Image:Analysis:ExtractFrames:Nothing to do.
DEBUG:StegoVeritas:Modules:Image:Analysis:StegHide:Nothing to do.
DEBUG:StegoVeritas:Modules:Image:Analysis:ColorMap:Nothing to do.
DEBUG:StegoVeritas:Modules:Image:Analysis:Trailing:Nothing to do.
DEBUG:StegoVeritas:Modules:Image:Analysis:Filters:Nothing to do.
DEBUG:StegoVeritas:Modules:Image:Analysis:ExtractLSB:Nothing to do.
DEBUG:StegoVeritas:Modules:Image:Analysis:BruteLSB:Nothing to do.
Running Module: MultiHandler

Traceback (most recent call last):
  File "/sbin/stegoveritas", line 33, in <module>
    sys.exit(load_entry_point('stegoveritas==1.8', 'console_scripts', 'stegoveritas')())
  File "/usr/lib/python3.9/site-packages/stegoveritas/stegoveritas.py", line 270, in main
    veritas.run()
  File "/usr/lib/python3.9/site-packages/stegoveritas/stegoveritas.py", line 53, in run
    module.run()
  File "/usr/lib/python3.9/site-packages/stegoveritas/modules/__init__.py", line 31, in run
    module.run(self)
  File "/usr/lib/python3.9/site-packages/stegoveritas/modules/multi/analysis/carve.py", line 29, in run
    multi.veritas.test_output(f.read())
  File "/usr/lib/python3.9/site-packages/stegoveritas/stegoveritas.py", line 79, in test_output
    m = magic.from_buffer(thing, mime=True)
AttributeError: module 'magic' has no attribute 'from_buffer'
```

**Comment by noraj** [comment]
ref. from https://github.com/BlackArch/blackarch/issues/2759#issuecomment-873681296

**Comment by D3vil0p3r** [comment]
The issue can be closed. That error is not spawned anymore.
