### ISSUE TITLE
virtualbox-guest-utils and virtualbox-guest-utils-nox are in conflict

### ISSUE THREAD

**Issue by Dharmesh-Dez** [BlackArch/blackarch#3168]
Type: Question

## Question
can anyone tell me how to solve this, i am new to blackarch

**Comment by anunna** [comment]
The erorr is clear and only one of those packages can exist on the system. 

If you did not intend to install `virtualbox-guest-utils-nox` then first uninstall it. If you did intend it, uninstall `virtualbox-guest-utils`

**Comment by Dharmesh-Dez** [comment]
(2354/2354) checking keys in keyring               [######################] 100%
downloading required keys...
:: Import PGP key E0959FEA8B550539, "George Rawlinson <grawlinson@archlinux.org>"? [Y/n] y
:: Import PGP key F83424824B3E4B90, "Orhun Parmaksız <orhun@archlinux.org>"? [Y/n] y
(2354/2354) checking package integrity             [######################] 100%
error: ruby-msgpack: signature from "Tim Meusel <bastelfreak@archlinux.org>" is marginal trust
:: File /var/cache/pacman/pkg/ruby-msgpack-1.4.2-3-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: ruby-unf: signature from "Tim Meusel <bastelfreak@archlinux.org>" is marginal trust
:: File /var/cache/pacman/pkg/ruby-unf-0.2.0.beta2-6-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: ruby-domain_name: signature from "Tim Meusel <bastelfreak@archlinux.org>" is marginal trust
:: File /var/cache/pacman/pkg/ruby-domain_name-0.5.20190701-4-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: ruby-http-cookie: signature from "Tim Meusel <bastelfreak@archlinux.org>" is marginal trust
:: File /var/cache/pacman/pkg/ruby-http-cookie-1.0.3-7-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.

**Comment by Dharmesh-Dez** [comment]
this happens
how can i solve this

**Comment by anunna** [comment]
`pacman -Sy archlinux-keyring blackarch-keyring && pacman -Syu`

**Comment by anunna** [comment]
No further responses, but this should fix the issue.
