### ISSUE TITLE
problem happened while updating today. help me to solve this...

### ISSUE THREAD

**Issue by Dharmesh-Dez** [BlackArch/blackarch#3183]
[ blackarch ~ ]# sudo pacman -Syu
:: Synchronizing package databases...
 core                  625.8 KiB  1340 KiB/s 00:00 [######################] 100%
 extra                 625.8 KiB  2.04 MiB/s 00:00 [######################] 100%
 community             625.8 KiB  2.78 MiB/s 00:00 [######################] 100%
 multilib              625.8 KiB  2.66 MiB/s 00:00 [######################] 100%
 blackarch is up to date
:: Starting full system upgrade...
error: could not open file /var/lib/pacman/sync/core.db: Unrecognized archive format
error: could not open file /var/lib/pacman/sync/extra.db: Unrecognized archive format
error: could not open file /var/lib/pacman/sync/community.db: Unrecognized archive format
error: could not open file /var/lib/pacman/sync/multilib.db: Unrecognized archive format
warning: bladerf: local (2021.03-1) is newer than blackarch (0.9.0-5)
warning: hamlib: local (3.3-10) is newer than blackarch (3.3-2)
warning: mbelib: local (1.3.0-2) is newer than blackarch (1.3.0-1)
warning: osm-gps-map: local (1.2.0-1) is newer than blackarch (1.1.0-3)
warning: perl-bytes-random-secure: local (0.29-9) is newer than blackarch (0.29-6)
warning: perl-task-weaken: local (1.06-4) is newer than blackarch (1.06-2)
warning: perl-yaml-libyaml: local (0.75-6) is newer than blackarch (0.63-1)
warning: python-backcall: local (0.2.0-4) is newer than blackarch (0.2.0-3)
warning: python-bitstring: local (3.1.7-3) is newer than blackarch (3.1.7-2)
warning: python-crc16: local (0.1.1-7) is newer than blackarch (0.1.1-3)
warning: python-easyprocess: local (0.3-3) is newer than blackarch (0.3-2)
warning: python-flask-socketio: local (5.0.1-1) is newer than blackarch (4.2.1-2)
warning: python-httpx: local (0.18.2-1) is newer than blackarch (0.18.1-1)
warning: python-inflect: local (5.3.0-1) is newer than blackarch (5.0.2-2)
warning: python-jinja-time: local (0.2.0-5) is newer than blackarch (0.2.0-3)
warning: python-notify2: local (0.3.1-5) is newer than blackarch (0.3.1-3)
warning: python-odfpy: local (1.4.1-4) is newer than blackarch (1.4.1-2)
warning: python-plumbum: local (1.7.0-3) is newer than blackarch (1.7.0-1)
warning: python-poyo: local (0.5.0-4) is newer than blackarch (0.5.0-3)
warning: python-ptrace: local (0.9.8-1) is newer than blackarch (0.9.3-2)
warning: python-pyee: local (8.1.0-3) is newer than blackarch (8.1.0-2)
warning: python-pypugjs: local (5.9.9-1) is newer than blackarch (5.9.4-2)
warning: python-pytesseract: local (0.3.8-1) is newer than blackarch (0.3.7-2)
warning: python-r2pipe: local (5.3.0-1) is newer than blackarch (1.5.3-2)
warning: python-readability-lxml: local (0.8.1-3) is newer than blackarch (0.8.1-2)
warning: python-requests-unixsocket: local (0.2.0-4) is newer than blackarch (0.2.0-3)
warning: python-ropper: local (1.13.6-1) is newer than blackarch (1.9.10-1)
warning: python-whichcraft: local (0.6.1-4) is newer than blackarch (0.6.1-3)
warning: python2-ujson: local (2.0.3-1) is newer than blackarch (1.35-1)
:: Replace reaver with blackarch/reaver-wps-fork-t6x? [Y/n] y
warning: rtkit: local (0.13-1) is newer than blackarch (0.11-4)
warning: ruby-domain_name: local (0.5.20190701-4) is newer than blackarch (0.5.20190701-3)
warning: ruby-json: local (2.5.1-3) is newer than blackarch (2.5.1-2)
warning: ruby-nokogiri: local (1.11.7-2) is newer than blackarch (1.11.3-2)
warning: sbc: local (1.5-2) is newer than blackarch (1.2-1)
warning: sslsplit: local (0.5.5-1) is newer than blackarch (0.5.2-1)
error: failed to prepare transaction (invalid or corrupted database)

**Comment by zeeshan1991k** [comment]
Same with me. Wasted my whole day. At last reverted to kali.

**Comment by ikstream** [comment]
Have you tried googling your problem like `arch linux Unrecognized archive format`. There are solutions available.

- Try `-Syyu` first
- if it doesn't work, delete the problematic databases and do a `-Syyu` afterwards

**Comment by noraj** [comment]
cf. https://wiki.archlinux.org/title/Pacman#Troubleshooting

**Comment by Vandell63** [comment]
Hey, i got the same issue even after removing all dbs and re `-Syyu`.
I solved it by changing mirror location from pacman.d/mirrorlist to my country. Also for the blackarch-mirrorlist.
Hope it can help you @zeeshan1991k

**Comment by ikstream** [comment]
The issue seems to be related to an issue with an Arch Linux mirror. See https://www.reddit.com/r/archlinux/comments/oon3sx/pacman_sync_databases_unrecognized_archive_format/

Removing it solved the issue on the devices I encountered the issue
