### ISSUE TITLE
Partion error 

### ISSUE THREAD

**Issue by Sarge12345** [BlackArch/blackarch#3193]
Hi, 

I tried to install in dual boot, but not create more than 4
partition.

Then when I tried to mount the partitions, receive this error:
 Creating BOOT partition > /sbin/blackarch-install: line 976:
mkfs.fat32: command not found > Error: Could not create filesystem.

Thank you very much

One more person had this error but he fixed it by making the hard drive should be formatted in gpt.

But mine is already in gpt format

Thank you.

**Comment by ikstream** [comment]
Please make sure, that you are using the most recent installer version. 
The installer should be on version 1.2.20.

**Comment by Sarge12345** [comment]
its fixed now, i used the dot format

**Comment by thestrangequarks** [comment]
> its fixed now, i used the dot format

please close this issue so that if anyone has same problem will know that it is solved so will look here for answers!!!
