### ISSUE TITLE
Boot Problem

### ISSUE THREAD

**Issue by thestrangequarks** [BlackArch/blackarch#3194]
Type: Question

## Boot Problem
I just installed blackarch on bare metal and there were no errors during installation but after completion of the setup during boot this error is comming regarding bad superblocks  ( attaching screenshot below )

![IMG_20210728_134312465_HDR.jpg](https://user-images.githubusercontent.com/84588720/127291716-6fe6081e-d146-4e83-825a-58dd90864bc4.jpg)

Can anyone help me with that ??

I installed blackarch using offline installer (iso)
Boot directory - /dev/sda1   (ext2)
Root directory - /dev/sda3  (ext4)

Also before this I faced a issue regarding recovering journal ; clean xxxx files /xxxxx blocks during boot up but now this one is changed with the now one !!!

**Comment by ikstream** [comment]
Do you have UEFI or legacy boot enabled? In case of UEFI you need to change `/dev/sda1` to `vfat`
`
On a side note, If you had a working install, why did you redo the install?

**Comment by noraj** [comment]
- https://wiki.archlinux.org/title/Installation_guide
- https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface

**Comment by thestrangequarks** [comment]
> Do you have UEFI or legacy boot enabled? In case of UEFI you need to change `/dev/sda1` to `vfat`
> `
> On a side note, If you had a working install, why did you redo the install? 
> 
> 

I have legacy boot enabled , this is a fresh install and the boot error occurred after the installation completes when I try to reboot the system .

**Comment by ikstream** [comment]
It looks like something went wrong with your file system here. 
You can either check theses to links ([[1](https://www.cyberciti.biz/tips/surviving-a-linux-filesystem-failures.html)], [[2](https://archived.forum.manjaro.org/t/cant-boot-error-mount-new-root-wrong-fs-type/104906)]) and try to recover your system, or just do it again, as you wouldn't loose any data by now.

Unfortunately I don't have the time to try to reproduce your issue right now.

**Comment by thestrangequarks** [comment]
> It looks like something went wrong with your file system here. 
> You can either check theses to links ([[1](https://www.cyberciti.biz/tips/surviving-a-linux-filesystem-failures.html)], [[2](https://archived.forum.manjaro.org/t/cant-boot-error-mount-new-root-wrong-fs-type/104906)]) and try to recover your system, or just do it again, as you wouldn't loose any data by now.
> 
> Unfortunately I don't have the time to try to reproduce your issue right now. 

Thanks , I am reinstalling it , if the issue still persists I think there is also a space issue here so I will try to change the partition using gpart !! And will notify

**Comment by thestrangequarks** [comment]
The problem is solved after reinstalling blackarch !!! I think the problem was with the power outrage so if your pc or laptop is interrupted by a power cut due to that bad blocks error will be there so reinstalling is the best way i guess to solve this problem ( also running fsck command to fix the errors will also result in the same issue ) :)
