### ISSUE TITLE
Everytime I tries to make a user in installation of blackarch, it fails.

### ISSUE THREAD

**Issue by gKBJbi** [BlackArch/blackarch#3197]
Hello

I am trying to install blackarch linux on virtualbox using full iso from official webpage. Most of the installation process goes well but when I am asked to create a non-root user, I type my new username and it fails. It prints out like the image

![image](https://user-images.githubusercontent.com/76414774/127603023-67148be7-5b1c-4a52-afa6-4519d27a4cec.png)

**Comment by halnkano** [comment]
Does anyone have any solution to this?

**Comment by ikstream** [comment]
Please make sure, that your installer is at version 1.2.20. What is the user name you are trying to use?

**Comment by halnkano** [comment]
I used the version "2020.12.01" according to the website https://blackarch.org/downloads.html which I think the most recent one.

**Comment by halnkano** [comment]
username is just like 'halnkano'.

**Comment by noptrix** [comment]
@gKBJbi check the new version of ISO. feel free to re-open the ticket if you still encounter the same
