### ISSUE TITLE
Scrying in the repo but not available as package

### ISSUE THREAD

**Issue by Hazegard** [BlackArch/blackarch#3207]
- **Name**: Scrying
- **Source URL**: 
- **Description**:

The tool was added in this repo (see: https://github.com/BlackArch/blackarch/commit/42706aff3198015cc0ba0e09004564bac4ed77f2#diff-b5c00ca3fa3b8c10c056f08b8bf6dd89227a323dcbc1b619228007d7567231e6)
Its PKGBUILD is available here: https://github.com/BlackArch/blackarch/blob/a12e5575633f63762eebb106724ab67c75f71f1c/packages/scrying/PKGBUILD

It was then removed from the "to-release" list in this commit: https://github.com/BlackArch/blackarch/commit/5e8da36a0552985f4c6124571d30bb4f0fe64d1a#diff-b5c00ca3fa3b8c10c056f08b8bf6dd89227a323dcbc1b619228007d7567231e6

But it is not available through pacman, nor listed on Black package list.

Is there a reason why this tool was not added to the packages ?

**Comment by noraj** [comment]
@Hazegard Thanks for the report.

@noptrix Seems you forgot to build [scrying](https://github.com/BlackArch/blackarch/blob/master/packages/scrying/PKGBUILD) when you removed it from `to-release`.

**Comment by noptrix** [comment]
no guys, it had a built error... i will try again soon. cheers:)
