### ISSUE TITLE
Error when trying to install the BlackArch OS on the VM

### ISSUE THREAD

**Issue by cronos-exe** [BlackArch/blackarch#3209]
Type: I don't know what to do or why I get this, a little help pls?

Hello,
I installed the BlackArch OS, version 2020.12.01, from the official site. After the torrent was ready I got it into my VM, created in VirtualBox and tried to install it using the command `pacman -Sy`.
But I got this error, actually a lot bigger...
![VirtualBox_BlackArch OS_10_08_2021_16_39_26](https://user-images.githubusercontent.com/76951144/128881703-64aa21e8-9929-4315-bc82-43ec45fc589e.png)
![blackarch error](https://user-images.githubusercontent.com/76951144/128881751-f75fe8b0-de37-4c21-b882-b625b18b6cfd.png)

I didn't see this happening to other people or tutorial on YT.
The Vm has 1.9 RAM (my laptop has only 4 RAM so I can't give more) and 80 GB memory.
It is known why this is happening? Is from my computer? And is there a way that I can resolve it?

**Comment by noraj** [comment]
Hi @cronos-exe 

1. Never use `pacman -Sy`, this leads to [partial upgrades](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported)
2. You just don't have any internet connection on your host or VM, DNS resolving of all mirrors are failling
