### ISSUE TITLE
s3scanner needs update

### ISSUE THREAD

**Issue by dualfade** [BlackArch/blackarch#3211]
s3scanner is no longer working with latest commits.

[0] % s3scanner --help
python: can't open file '/usr/share/s3scanner/s3scanner.py': [Errno 2] No such file or directory

PKGBUILD needs to be updated accordingly.

Url:
https://github.com/sa7mon/S3Scanner

**Comment by noptrix** [comment]
@dualfade thx mate. check if this fix works. should be ok.
