### ISSUE TITLE
Aquatone update

### ISSUE THREAD

**Issue by 0x483d** [BlackArch/blackarch#3225]
- **Name**: Aquatone
- **Source URL**: https://github.com/shelld3v/aquatone
- **Description**: The currently existing Version (https://github.com/michenriksen/aquatone) has not been updated since 2 years.
A new fork is under active development (https://github.com/shelld3v/aquatone).
Is it possible to update aquatone?

**Comment by noptrix** [comment]
@0x483d sure, thanks a lot for this.
