### ISSUE TITLE
Adding man package to blackarch group

### ISSUE THREAD

**Issue by AlexOConnorHub** [BlackArch/blackarch#3230]
Type: Discussion

## Discussion
I just installed the blackarch group (after running `strap.sh`) on a fresh install of arch linux. When going to use the tools provided with the blackarch package, I noticed I wasn't able to use the man command, because it was not installed. This package is already in the repo, so I was able to just install it, but  I was wondering if there was any reason this wasn't in the blackarch group, since this is one of the most useful ways to get accurate information about the package/command one may be wanting to work with.

**Comment by ikstream** [comment]
`man-db` and `man-pages` are upstream packages. They are not maintained by us and are no tool specific to BlackArch.
The `strap.sh` only adds our repo to your Arch install, so it's up to you which tools you install.

If you choose an install version, where one of our installer puts Arch and BA on your device `man-*` gets installed afaik.
In addition only a very limited number of BA tools provide man pages. 

I hope this provides a satisfying answer to your question. If not, feel free to reopen the issue.
