### ISSUE TITLE
New mirror request [China]

### ISSUE THREAD

**Issue by d-w-x** [BlackArch/blackarch#3236]
Would you please add new mirror in mirror list and the config files?

-----

mirror info:

- url: https://mirrors.nju.edu.cn/blackarch/
- protocol: http, https, rsync
- Synchronization frequency: every day (could more if need)
- Bandwidth: 10Gb/s
- Location: Nanjing, China, Asia
- Contact: my@yaoge123.com

**Comment by noraj** [comment]
Thanks a lot ❤️

**Comment by d-w-x** [comment]
No problem! 

Have a nive day~

**Comment by noptrix** [comment]
@d-w-x thank you very much.
