### ISSUE TITLE
New Mirror From UK

### ISSUE THREAD

**Issue by vgn-pa** [BlackArch/blackarch#3237]
Hi

We are long standing donators of mirror services for high-end projects such as GNU, KDE, Gnome, Ubuntu, ArchLinux, Apache etc and would like to support your project as such in keeping with our open-source commitments.

The mirror is served over rsync, ftp and http(s) and can be found here http://mirrors.gethosted.online/blackarch/

We are DDoS protected with content serviced from Rothwell UK.

Kind regards

**Comment by noraj** [comment]
Thanks a lot for you support, it's much appreciated. I think it's our first mirror in UK.

**Comment by vgn-pa** [comment]
No problem! I was idling on irc for a long while. Glad to have you on board.

Kind regards
