### ISSUE TITLE
Signature from "Levon noptrix"

### ISSUE THREAD

**Issue by xkpx64** [BlackArch/blackarch#3242]
Type: I just installed blackarch but can't install mc or update the db.

``` Xarch /home/xkpx ]# pacman -S mc
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is unknown trust
error: database 'blackarch' is not valid (invalid or corrupted database (PGP signature))

```

## Question
How to fix it ?

**Comment by anunna** [comment]
`pacman -S archlinux-keyring blackarch-keyring && pacman -Syu`

Please check the FAQ and closed issues in the future.

**Comment by abofratutuutu** [comment]
Hello, I still encounter this error message:

`error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is unknown trust

error: failed to synchronize all databases (invalid or corrupted database (PGP signature))
`
even after running @anunna code: `pacman -S archlinux-keyring blackarch-keyring && pacman -Syu`

**Comment by noraj** [comment]
https://blackarch.org/faq.html
