### ISSUE TITLE
Kali Linux MITMF Dependencies

### ISSUE THREAD

**Issue by Ethedark** [BlackArch/blackarch#3245]
Type: Question

## Question
When I am trying to download MITMF libraries which is ''apt-get install python-dev python-setuptools libpcap0.8-dev libnetfilter-queue-dev libssl-dev libjpeg-dev libxml2-dev libxslt1-dev libcapstone3 libcapstone-dev libffi-dev file'' I get this message on terminal 

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
file is already the newest version (1:5.39-3).
libcapstone-dev is already the newest version (4.0.2-3).
libffi-dev is already the newest version (3.3-6).
libffi-dev set to manually installed.
python-setuptools is already the newest version (44.1.1-1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libpython2.7-minimal : Breaks: python (< 2.7.18)
                        Breaks: python-dev (< 2.7.18)
 libpython2.7-stdlib : Breaks: python (< 2.7.18)
                       Breaks: python-dev (< 2.7.18)
 python : Depends: python-minimal (= 2.7.3-4+deb7u1) but it is not installable
 python-is-python2 : Breaks: python
 python2 : Breaks: python (< 2.7.15-2)
 python2.7 : Breaks: python (< 2.7.18)
             Breaks: python-dev (< 2.7.18)
 python2.7-minimal : Breaks: python (< 2.7.18)
                     Breaks: python-dev (< 2.7.18)
 python3-six : Breaks: python (< 2.7.18)
 python3-yaml : Breaks: python (< 2.7.18)
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

The libraries shown in terminal are already downloaded. Is the problem because it is above the versions shown? Is MITMF obsolete? Can anyone give information about it

**Comment by noraj** [comment]
It's is BlackArch issue tracker here, not Kali Linux one. Go to https://bugs.kali.org/
