### ISSUE TITLE
Running bloodhound and editing the password from neo4j console stretches terminal and changes font

### ISSUE THREAD

**Issue by yeti-code** [BlackArch/blackarch#3261]
### Bug description

Title says it all. When I run bloodhound, and subsequently the neo4j console to edit the default password. The terminal windows will stretch, and the font will change after connecting to bloodhound via the new neo4j password.

### Steps to reproduce

On a fresh instance in Virtualbox using the OVA image imported:

# run bloodhound

~~~
bloodhound
~~~

# Navigate neo4j console

~~~
firefox http://localhost:7474
~~~

# login to neo4j

~~~
username: neo4j
password: neo4j
~~~

# Change password to whatever you want

close the neo4j console

Go back to bloodhound console

login with new credentials

~~~
neo4j

pass: newpassword

~~~

# let bloodhound load

exit

close all terminals

then open up a new terminal from fluxbox menu

boom, bug!

### Info for developers

# Host:
Windows 10 Home
Version: 10.0.19042 Build 19042

System Model: ASUS Zenbook UX461UA x64-based

Processor: Intel Core i5-8250U

# Virtual Machine Info:

Software: Virtualbox Version 6.1.28 r147628 (Qt5.6.2)

Blackarch OVA

blackarch-linux-2021.09.01

Image attached

![2021-10-30 10_30_32-Window](https://user-images.githubusercontent.com/76129522/139537955-0bb9fc4c-1f61-4b5a-8c16-5768ee264d7d.png)

**Comment by noraj** [comment]
bloodhound package has been updated since, re-open if it still persist
