### ISSUE TITLE
rmiscout

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3266]
- **Name**: rmiscout
- **Source URL**: https://github.com/BishopFox/rmiscout
- **Description**: ![image](https://user-images.githubusercontent.com/16578570/140657809-d8fc46ea-fecd-4c8d-a7f4-1f6d44f96353.png)

**Comment by D4imyo** [comment]
hey noraj, can i take this ?

**Comment by noraj** [comment]
> hey noraj, can i take this ?

if I have not PRed it tomorrow night feel free too 😃
