### ISSUE TITLE
Postgresql

### ISSUE THREAD

**Issue by KingOfMyworld** [BlackArch/blackarch#3277]
I am unable to start the postgresql in blackarch for the metasploit

It shows starting postgresql is failed

**Comment by dualfade** [comment]
[image.png]

[image.png]

[image.png]

Follow this. It should get you up and running pretty quick.

~!>D

dualfade[at]vadersecurity.com, OSCP OSWE OSWP
https://www.vadersecurity.com
phone: +1 855-626-6440
threema: 6V2Y9Y6P
bcard:https://bit.ly/35TOyj2

[image]

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by KingOfMyworld** [comment]
it show only like [image.png] like that please kindly resubmit the solution

**Comment by dualfade** [comment]
All the screenshots ( png files ) walk you through how to do it ? They are not showing up ?

~!>D

christopher.downs[at]vadersecurity.com, OSCP OSWE OSWP
https://www.vadersecurity.com
phone: +1 855-626-6440
threema: 6V2Y9Y6P
bcard:https://bit.ly/35TOyj2

[image]

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dualfade** [comment]
Setting upPostgresql--

https://wiki.archlinux.org/title/PostgreSQL

initdb--locale=en_US.UTF-8 -E UTF8 -D /var/lib/postgres/data

Ctld ( log back to your user ) --

Enablepsql--

sudosystemctlenable --nowpostgresql.service

Check Port / Service --

sudoss -tunlp| grep 5432 ;sudosystemctlstatuspostgresql.service

CreatePostgresqlUSER "msf" --

Update the USERS PSQL password --

sudo -iu postgres

createuser --interactive

name: msf

superuser: no

allowed to create db;s: y

allow to create new users / roles: n

ALTER ROLE msf WITH PASSWORD 'somecrazypassornot'

As "our" user / in this case "dualfade" --

Test PSQL connect with USER --

sudo msfconsole
db_connect ***@***.***
db_status

You should be done.
Hope this helps.

~!>D

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
