### ISSUE TITLE
Acunetix Web Vulnerability Scanner 13

### ISSUE THREAD

**Issue by d3417** [BlackArch/blackarch#3282]
- **Acunetix Web Vulnerability Scanner 13**:
- **https://ftuapps.dev/wp-content/uploads/2020/02/FTUApps.com-Acunetix-Web-Vulnerability-Scanner-v13.0.200217097-for-Linux-x64-Crack.torrent**:
- **Multi-threaded, lightning fast crawler and scanner that can crawl hundreds of thousands of pages without interruptions.
Highest detection of WordPress vulnerabilities – scans WordPress installations for over 1200 known vulnerabilities in WordPress’ core, themes and plugins.
An easy to use Login Sequence Recorder that allows the automatic crawling and scanning of complex password protected areas including multi-step, Single Sign-On (SSO) and OAuth-based websites.
Easily generate a wide variety of technical and compliance reports aimed towards developers and business owners alike.**:

**Comment by ikstream** [comment]
This seems to be pirated software. We are not redistributing cracked, or otherwise pirated software.
If this is not the case feel free to reopen the issue

**Comment by d3417** [comment]
Just remove license.json and make the PKGINFO to run only the installer et voilà, non-pirated softwares into BlackArch Sources, if any guy want to crack (after the trial installation from your sources) Acunetix, can do herself without any help.

I hope to be clear.

**Comment by d3417** [comment]
Ah, and remove wvsc binary file from files to put in /usr/bin because it's the cracked version, only the .sh installer put in /usr/bin the original wvsc, that is contained in the torrent
