### ISSUE TITLE
Blackarch keyrings

### ISSUE THREAD

**Issue by PranaKnight** [BlackArch/blackarch#3285]
Type: Question

## Question

Hey, there! I'm running blackarch in the following conf: 

Kernel: x86_64 5.15.7-arch1-1 
CPU Intel core i5 7th   7600
Lenguage: Portuguese Brazil

And yesterday 12/12/2021 after updating the systems through pacman -Syyu I'm having the following error: 

erro: blackarch: a assinatura de "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" é inválida
erro: falha ao sincronizar todas as bases de dados (base de dados inválida ou corrompida (assinatura PGP))

I tried solving the errors with the FAQ solution in https://blackarch.org/faq.html and it didn't work. 

Checked time, dns, network connection and disabled firewall but the issue still continued. 

Can somebody help me, pls ? 

I'm a beginner in blackarch, so if more details or more specifics are needed I'll gladly provide. 

Thx!

**Comment by PranaKnight** [comment]
Solved

Some of the mirrors of US region in blackarch mirrorlist are causing the problems. Commenting them and using the default german one solved the issue.

**Comment by ikstream** [comment]
Sorry for the late response and good to see you could solve your issue.
Please also check if there a new mirrorlist `/etc/pacman.d/`. These are appended with `.pacnew`.
This is important, to keep your mirrorlist up-to-date

**Comment by ikstream** [comment]
I would recommend to update at the bare minimum once a month to avoid most issues. More often is better. Usually the pacman output will tell you, when a new config file is available.
