### ISSUE TITLE
no Internet connection

### ISSUE THREAD

**Issue by godheus** [BlackArch/blackarch#3287]
Type: Question

## Question 

Hi, i can't connect to internet in blackarch, i normally connect with tenda wireless router. please help

**Comment by ikstream** [comment]
We would need more information, like what have you tried, how are you trying to connect and are there any error messages?

**Comment by noraj** [comment]
You may want to use a NAT or Bridge NIC, you won't be able to use wireless in a VM unless you perform PCI pass-through or USB pass-through with a WIFI card.

https://wiki.archlinux.org/title/VMware and https://wiki.archlinux.org/title/VMware/Install_Arch_Linux_as_a_guest may help you.
