### ISSUE TITLE
Metasploit Pro Web Framework

### ISSUE THREAD

**Issue by d3417** [BlackArch/blackarch#3295]
- **Metasploit Pro Web Framework**:
- **[Source URL](https://www.rapid7.com/products/metasploit/download/pro/)**:
- **For penetration testers and other security professionals**:

Download Link: https://downloads.metasploit.com/data/releases/metasploit-latest-linux-x64-installer.run

**Comment by d3417** [comment]
I can upload my /opt/metasploit as tar.gz for extraction during installation progress without official graphical installer.

**Comment by ikstream** [comment]
Looks like it is distributed under a commercial license, so we are not packaging it
