### ISSUE TITLE
Hydra compiled without LIBSMBCLIENT support

### ISSUE THREAD

**Issue by RedlineTriad** [BlackArch/blackarch#3299]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Hydra seems to be compiled without support for scanning SMB2 shares.

### Steps to reproduce

- Install `hydra`
- Run `hydra -l test -p test localhost  smb2`

**Actual result:** `[ERROR] Compiled without LIBSMBCLIENT support, module not available!`

**Expected result:** It would attempt to connect to a `smb2` share on localhost and test if `test:test` was a valid login.

### Info for developers

**GNU/Linux distribution:** Manjaro
**Tool version:** Hydra v9.2

**Comment by noptrix** [comment]
@RedlineTriad Hydra and several other major security tools are not maintained by us. We only mirror them by simply adding those packages to our DB. [here](https://github.com/BlackArch/blackarch/lists/official) you can check official ArchLinux packages mirrored, but not maintained by us. please file a bug at ArchLinux.
