### ISSUE TITLE
GET www.blackarch.org/blackarch/keyring/blackarch-keyring.pkg.tar.xz returns 404

### ISSUE THREAD

**Issue by rickmer** [BlackArch/blackarch#3305]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
HTTP GET www.blackarch.org/blackarch/keyring/blackarch-keyring.pkg.tar.xz returns 404

### Steps to reproduce

```
$ curl -s -O 'https://www.blackarch.org/blackarch/keyring/blackarch-keyring.pkg.tar.xz'
$ file blackarch-keyring.pkg.tar.xz 
blackarch-keyring.pkg.tar.xz: HTML document, ASCII text, with CRLF line terminators
$ grep '404' blackarch-keyring.pkg.tar.xz 
<head><title>404 Not Found</title></head>
<h1>404 Not Found</h1>
```
**Actual result:** 
It is not possible to install blackarch using strap.sh

**Expected result:** 
GET request should respond HTTP 200 and contain actual keyring.pkg

**Additional Info**
GNU/Linux distribution: Arch Linux

Note: If strap.sh is run, this issue results in the errror message that - for obvious reasons - "the key could not be verified". That may cause Bugreports like: https://github.com/BlackArch/blackarch/issues/3241

**Comment by noptrix** [comment]
@rickmer thx. should be fixed now.
