### ISSUE TITLE
msfconsole eroor rubygems

### ISSUE THREAD

**Issue by SkrudjReal** [BlackArch/blackarch#3308]
Hello all! I try to start msfconsole but i have a problem, when i try to start it that's say -
Scrooge wrote:

    [root@GOD gooder]# msfconsole
    Traceback (most recent call last):
        1: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
    <internal:gem_prelude>:1:in `require': cannot load such file -- rubygems.rb (LoadError)

Reinstall metasploit, ruby, rubygems and update system doesn't help.
Scrooge wrote:

    pacman -Syyu
    pacman -Rdd ruby rubygems
    pacman -R metasploit && pacman -Sy metasploit

My system is Arch xfce, i had added blackarch repo and community. Help please

**Comment by noptrix** [comment]
@SkrudjReal please file a bug at ArchLinux community. we don't maintain this package.

**Comment by SkrudjReal** [comment]
> @SkrudjReal please file a bug at ArchLinux community. we don't maintain this package.

They say me go to blackarch comunity!

**Comment by SkrudjReal** [comment]
![Screenshot_2022-01-13_12-33-05](https://user-images.githubusercontent.com/76687908/149316075-c946c410-e908-456e-aabf-878bdd706f67.png)

**Comment by noptrix** [comment]
@SkrudjReal then they don't know what they say. again: we don't maintain or manage this package. we just mirror it from ArchLinux. closing and locking this issue here.

**Comment by noraj** [comment]
@SkrudjReal This is bad faith from fukawi2. It's AL that maintains [metasploit](https://archlinux.org/packages/community/x86_64/metasploit/) package. You can find open bugs about this package [here](https://bugs.archlinux.org/?project=5&string=metasploit). As for me I have no issue launching `msfconsole` with an up to date AL with BA repo. Check if you are using virtual environments such as rbenv, asdf, rvm, etc.
