### ISSUE TITLE
xray (web scanner)

### ISSUE THREAD

**Issue by m0tky** [BlackArch/blackarch#3310]
- **Name**:xray
- **Source URL**:https://github.com/chaitin/xray
- **Description**:https://docs.xray.cool/#/

**Comment by noraj** [comment]
It's a different `xray` than the one requested in #1794 and added in https://github.com/BlackArch/blackarch/commit/700c0725a6aba8119bd0d58123ebd88d7bd72304. The one already included is a recon tool wheras this one is a web scanner.

As the name is conflicting we will have to think about another package name and bin name.

**Comment by D3vil0p3r** [comment]
`xray-toolset` could be well. Xray 2.0 seems to not have anymore a `xray` binary as the old `1.0` but it uses:
* [xpoc](https://docs.xray.cool/tools/xpoc/BasicIntroduction)
* [xapp](https://docs.xray.cool/tools/xapp/BasicIntroduction)
* [xlint](https://docs.xray.cool/tools/xlint/QuickStart)

I don't see any docs related to build from source so I guess that the best approach should be retrieving binaries.

**Comment by D3vil0p3r** [comment]
To be closed: https://github.com/BlackArch/blackarch/pull/4355#issuecomment-2481552633
