### ISSUE TITLE
Raptor

### ISSUE THREAD

**Issue by d3417** [BlackArch/blackarch#3311]
Hello guys, i've created a "porting" of this beautiful program that analyze multiple languages and platforms in search of bugs and vulnerabilities, originally are for Debian/Ubuntu/Kali and derivates, now it's possible to run in ArchLinux with my mods.

https://github.com/d3417/raptor-archlinux/releases/tag/beta

Consider to download, use or publish only the version in Releases section because it's complete, i've not uploaded in the main repo branch all folders.

**Comment by ikstream** [comment]
I am somewhat adverse to add a Python2 that has seen code improvements by the original author last in 2016.
Since you haven't kept the commit history, I don't know if you improved the code without diffing the two repos.
