### ISSUE TITLE
How to update to the latest version

### ISSUE THREAD

**Issue by Biaogo** [BlackArch/blackarch#3312]
Type: Question

## Question
Download the latest ova image from the official website, you know, it doesn't update very often, so how do I update the system to the latest or package?
I tried the normal update methods '-Syu' and '--overwride "*" '
This will cause the installation to give another error

**Comment by ikstream** [comment]
Plea

**Comment by ikstream** [comment]
Feel free to reopen this issue, when you provide the error output

**Comment by Biaogo** [comment]
I tried installing the system using BlackArch Linux 64 bit Netinstall ISO, After downloading the installation package, it has always output these contents:
```shell
chroot: failed to run command 'passwd': No such file or directory
...
chroot: failed to run command 'passwd': No such file or directory
```

**Comment by Biaogo** [comment]
When setting the locale on the way, the error output also occurred:
```shell
sed: can't read /mnt/etc/locale.gen: No such file or directory
```

**Comment by ikstream** [comment]
Please run ` pacman -Syy archlinux-keyring blackarch-keyring` before running the installer
