### ISSUE TITLE
kscan

### ISSUE THREAD

**Issue by m0tky** [BlackArch/blackarch#3313]
- **Name**:kscan
- **Source URL**:https://github.com/lcvvvv/kscan
- **Description**:https://github.com/lcvvvv/kscan

**Comment by noptrix** [comment]
@m0tky hello. thanks. where is the EN description for this tool?

**Comment by noraj** [comment]
I have looked for but it seems there is no english documentation.

**Comment by m0tky** [comment]
yes， it doesn't have an english version

**Comment by D4imyo** [comment]
@noraj also the description of arguments/status messages is not in english. should we add this tool ?

**Comment by noraj** [comment]
https://github.com/lcvvvv/kscan/issues/48

https://github.com/lcvvvv/kscan/pull/53/files

https://github.com/lcvvvv/kscan/blob/master/README_ENG.md

https://github.com/lcvvvv/kscan/blob/master/kscan.go.eng

should be available in english now

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4232
