### ISSUE TITLE
new tool: ADExplorerSnapshot

### ISSUE THREAD

**Issue by pwnfoo** [BlackArch/blackarch#3330]
- **Name**: ADExplorerSnapshot.py
- **Source URL**: https://github.com/c3c/ADExplorerSnapshot.py
- **Description**: ADExplorerSnapshot.py is an AD Explorer snapshot ingestor for BloodHound.

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4234
