### ISSUE TITLE
Installation of packages

### ISSUE THREAD

**Issue by Cidscapital** [BlackArch/blackarch#3336]
I have installed the slim iso version but I want it to include all tools without reinstalling the full iso. How can I install all tools at once.

**Comment by noptrix** [comment]
@Cidscapital it has nothing to do with `full iso` when you install all tools... simply run `yay -S blackarch --needed` and you will get all tools of BlackArch. some tools will miss, because they are not in the primary `blackarch` group. you can install them indvidually.
