### ISSUE TITLE
add aarch64 compatibility for all dependencies

### ISSUE THREAD

**Issue by moham96** [BlackArch/blackarch#3338]
### Bug description

Can't install blackarch on top of an aarch64 archlinuxarm base (virtual machine)

### Steps to reproduce

- fire up a generic aarch64 archlinuxarm vm (for me i used UTM on macos as a qemu gui)
- update the system and follow [these](https://blackarch.org/downloads.html#install-repo) steps to install blackarch
- you will see that in the last step (issuing `pacman -S blackarch`) that there are many unresolvable dependencies (see below debug log for full pacman output)
- using the command with the `--overwrite` argument doesn't resolve the issue either 
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
The packages don't install due to unresolvable dependencies

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The packages should install fine 

### Info for developers

**Device:** Apple macbook air m1 2020
**GNU/Linux distribution:** Host is MacOS 12.2.1 Guest is archlinuxarm inside a UTM virtual machine
**Tool version:** N/A

### Link to debug log

https://www.toptal.com/developers/hastebin/ahuhabuyej.yaml

**Comment by noraj** [comment]
I'm not sure but [this section](https://blackarch.org/downloads.html#blackarch-arm) states that it requires a platform listed [here](https://archlinuxarm.org/platforms) and MAC M1 are not.

**Comment by moham96** [comment]
@noraj i'm not running it on native m1, it's running as a generic aarch64 VM so it is supported, my guess is there is a problem with the packaging not with anything related to the platform

**Comment by moham96** [comment]
Just to be sure I downloaded [ArchLinuxARM-aarch64-latest.tar.gz](http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz) and run it in a chroot inside a Ryzen 5 x86 machine(to find if the m1 is the culprit) and the same problem exists

**Comment by ikstream** [comment]
Thank you for reporting, we identified the problem, but it will take a moment to address it.

**Comment by moham96** [comment]
@ikstream can we have more info about the issue ? is it on blackarch side? on archlinuxarm side? any ETA?

Regards

**Comment by ikstream** [comment]
It's a problem on our side. While the packages have arch=any they are not in the alarm repos. So we need to package and test them for aarch64.
We are currently looking to release a new x86 iso and the aarch64 user share seems to be relatively small so far. 
Nevertheless we will take care of the issue as soon as possible, but the priority is on x86.

It should be possible to install individual tools however.

**Comment by noraj** [comment]
Never do `pacman -S blackarch` it is useless and will never work anyway on any platform as there will always be at least one tool failing among 2800+ tools.

**Comment by ikstream** [comment]
As this is still an issue we need to address and not all dependencies are available on aarch64, I would keep this issue open until it's fixed.

**Comment by moham96** [comment]
> Never do `pacman -S blackarch` it is useless and will never work anyway on any platform as there will always be at least one tool failing among 2800+ tools.

`pacman -S blackarch` is mentioned in the docs, if it doesn't work it shouldn't be there.
There should not be a tool failing to install since we are not building from source so every tool should ideally be possible to install with no problem.

Regards

**Comment by ikstream** [comment]
You are not building from source, but we do for packaging (for some). 

There is a discussion to remove the mentioned line from docs.

**Comment by noptrix** [comment]
These issues should be resolved. However, there may be some unresolved ones that are flagged as warnings. You can exclude these packages and its dependencies by confirming 'yes' when prompted to skip the installation of unresolved packages.
