### ISSUE TITLE
[Tool Request] - Starkiller

### ISSUE THREAD

**Issue by b0n1t0** [BlackArch/blackarch#3346]
- **Name**: Starkiller
- **Source URL**: https://github.com/BC-SECURITY/Starkiller
- **Description**: Starkiller is a Frontend for [Powershell Empire](https://github.com/BC-SECURITY/Empire/). It is an Electron application written in VueJS.

**Comment by noraj** [comment]
> As of Empire 5.0 and Starkiller 2.0, you no longer need to install Starkiller or build it from source. It is prepackaged in Empire as a submodule and served via Empire's API.
