### ISSUE TITLE
BlackArch slim

### ISSUE THREAD

**Issue by justick01** [BlackArch/blackarch#3383]
Hi. This isn't really an issue but I wanted to say that BlackArch slim is kinda buggy and it doesn't have enough tools. A small list of tools that needs to be there:
openvas; netstumbler; ettercap; smikims-arpspoof; rtorrent and many more.

**Comment by dualfade** [comment]
Install them. That's the idea of slim. Minimal tool set so you do not have to download the internet.------- Original Message -------

**Comment by noraj** [comment]
> openvas; netstumbler; ettercap; smikims-arpspoof; rtorrent and many more.

those tool are specific and event not related to security for rtorrent. as @dualfade said the slim ISO is meant to be slim, if you want many stuff take the full ISO else install what you need with pacman
