### ISSUE TITLE
qbittorrent: error while loading shared libraries: libicui18n.so.71: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by justick01** [BlackArch/blackarch#3384]
sorry for interrupting again but when i'm trying to open qbittorrent it gives me this error: qbittorrent: error while loading shared libraries: libicui18n.so.71: cannot open shared object file: No such file or directory
falkon: error while loading shared libraries: libicui18n.so.71: cannot open shared object file: No such file or directory
same with falkon. Can you guys please help me? i searched on the internet and I didn't find an answer and I don't know what to do ( i'm new to linux so sorry if I seem stupid ) thank you for helping!

**Comment by noraj** [comment]
qbittorrent is from ArchLinux https://archlinux.org/packages/community/x86_64/qbittorrent/

**Comment by justick01** [comment]
yes i know i have downloaded it with pacman -s qbittorrent

**Comment by noraj** [comment]
Ask for support here https://bbs.archlinux.org/. We are not ArchLinux team. Sorry.
