### ISSUE TITLE
BlackArch Docker

### ISSUE THREAD

**Issue by Shadow-XT** [BlackArch/blackarch#3385]
Type: Question

## Question
Is there no docker image of blackarch?

I found a docker image warehouse for blackarchlinux / blackarch on dockerhub, and it was updated four days ago, but click in to 404 not found

![image](https://user-images.githubusercontent.com/65745507/164593292-e54c46db-de2d-4b08-932c-a05e9a062c53.png)

![image](https://user-images.githubusercontent.com/65745507/164593320-9964052a-c93a-4088-8680-d8c76ad5cca2.png)

Is this warehouse deleted?

**Comment by noraj** [comment]
Source: https://github.com/BlackArch/blackarch-docker

I have no 404 on https://hub.docker.com/r/blackarchlinux/blackarch

**Comment by D3vil0p3r** [comment]
Hey @noraj I was testing BlackArch docker from the Source you linked above, I cloned the repository by `git clone https://github.com/BlackArch/blackarch-docker` and I installed all the needed dependencies (fakeroot, fakechroot, docker, devtools, make) but when I run `make docker-blackarch-base` I get the following message:
```
make: Nothing to be done for 'docker-blackarch-base'.
```
Do you get the same message?
