### ISSUE TITLE
[help wanted] add dev-tools dependency check to pkgcheck

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3391]
I someone could PR to https://github.com/FFY00/pkgcheck to add a check that the following check

https://wiki.archlinux.org/index.php/PKGBUILD#makedepends

The dependencies required should be the minimum and so eliminating useless dependencies.

> Note: The group [base-devel](https://www.archlinux.org/groups/x86_64/base-devel/) is assumed to be already installed when building with makepkg. Members of this group should not be included in `makedepends` array.

So when someone would add `binutils`, make, etc. to makedepends this would trigger a warning with [our github action workflow](https://github.com/BlackArch/blackarch/blob/master/.github/workflows/tests.yml)

this would avoid huge work like https://github.com/BlackArch/blackarch/pull/2619/

**Comment by D3vil0p3r** [comment]
@noraj Is it still needed? If yes., do you mean to open a PR in pkgcheck repository to implement a function that allows pkgcheck to check also all the packages included in `base-devel` group?

**Comment by noraj** [comment]
> Is it still needed?

Yes

> do you mean to open a PR in pkgcheck repository

A function that check that the PKGBUILD is not including makedependencies that already are in in base-devel.

**Comment by D3vil0p3r** [comment]
What do you think about this @noraj ?
![image](https://github.com/user-attachments/assets/ab8c6fa9-e2c9-4793-92cb-357bf86829a2)

![image](https://github.com/user-attachments/assets/60ea2f6d-6c12-4f51-a2ee-5d0e5e604d12)

It takes around 5 seconds because queries base-devel by pacman.

**Comment by noraj** [comment]
looks promising

**Comment by noraj** [comment]
I'm quite busy, I don't have time to test this right now

**Comment by D3vil0p3r** [comment]
Our PRs have been merged upstream. I created a PR in BA to update pkgcheck.

Our changes upstream should help BA team to accelerate and make more efficient the package check process.

https://github.com/BlackArch/blackarch/pull/4340
