### ISSUE TITLE
Does the Full BlackArch Iso have a manual TTY install option, instead of the guided one?

### ISSUE THREAD

**Issue by BlackarchNet** [BlackArch/blackarch#3399]
I know the Full iso has the guided installer and the Slim iso uses Calamares, I hate both and would like to know if there's a terminal installer, like Pacstrap or Basestrap, and if there isn't one can someone add it to a feature request for me, I appreciate any help and before anyone says it, Yes I know BlackArch can be added on top of Arch, BUUUT I don't care and won't do it that way.

**Comment by BlackarchNet** [comment]
Should open a BlackArch Forum on the official website, this GitHub is like a ghost town, besides me the newest open topic was a week ago, there has to be a more efficient way to reach out to the community and discuss.

**Comment by ikstream** [comment]
BlackArch uses Arch and sits on top of it. So there are all tools available you find in Arch. So you can use pacstrap

**Comment by BlackarchNet** [comment]
> BlackArch uses Arch and sits on top of it. So there are all tools available you find in Arch. So you can use pacstrap

I'm aware, but if I'm on BlackArch I don't want my system to say "Arch Linux" at boot, in system settings, in Neofetch etc. m OCD like that, however the primary reason is I have an EFI pure system, no bios, no dos, no legacy, so naturally I picked GPT, and everything runs fine using Blackman, until I reach the place where I have to set mountpoints, encryption etc, then it bugs out and crashes back to the desktop.
