### ISSUE TITLE
Instashell: source not found

### ISSUE THREAD

**Issue by qkqsb** [BlackArch/blackarch#3404]
The source URL provided for instashell is unavailable. (https://github.com/thelinuxchoice/instashell)
The original author has seemingly disappeared without any new location for the code. I've linked what seems to be the most popular repo of this code that is still available below.
https://github.com/maxrooted/instashell

The package also cannot be downloaded from any mirror as far as I can tell. I tested the code in the repository I linked, and near as I can tell it works.

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4235
