### ISSUE TITLE
outdated packages

### ISSUE THREAD

**Issue by AlanJojo** [BlackArch/blackarch#3414]
### gdb version 11.2-1 is currently in the blackarch repository.
- Version 12.1-1 has already been released.

### python-pyspnego version 0.5.1-1 is currently in the blackarch repository.
- Version 0.5.2-1 has already been released.

### python-pyee version 8.2.2-2 is currently in the blackarch repository.
- Version 9.0.3-1 has already been released.

### python-aiosqlite version 0.17.0-2 is currently in the blackarch repository.
- Version 0.17.0-3 has already been released.

### paru version 1.9.3-1 is currently in the blackarch repository.
- Version 1.10.0-1 has already been released.

### sslsplit version 0.5.2-1 is currently in the blackarch repository.
- Version 0.5.5-1 has already been released.

### rtkit version 0.11-4 is currently in the blackarch repository.
- Version 0.13-1 has already been released.

### mkinitcpio-openswap version 0.1.0-1 is currently in the blackarch repository.
- Version 0.1.0-3 has already been released.

### gconf version 3.2.6+11+g07808097-6 is currently in the blackarch repository.
- Version 3.2.6+11+g07808097-10 has already been released.

### ncurses5-compat-libs version 6.1-3 is currently in the blackarch repository.
- Version 6.3-1 has already been released.

### sbc version 1.2-1 is currently in the blackarch repository.
- Version 1.5-2 has already been released.

## Links
gdb - https://www.sourceware.org/gdb/download/
python-pyspnego - https://github.com/jborean93/pyspnego/releases/tag/v0.5.2
python-pyee - https://pyee.readthedocs.io/en/latest/#version-9-0-3
python-aiosqlite - https://aiosqlite.omnilib.dev/en/stable/
paru - https://github.com/Morganamilo/paru/releases/tag/v1.10.0
sslsplit - https://www.roe.ch/SSLsplit
rtkit  - https://github.com/heftig/rtkit/releases/tag/v0.13
mkinitcpio-openswap - https://aur.archlinux.org/packages/mkinitcpio-openswap
gconf - https://gitlab.gnome.org/Archive/gconf
ncurses5-compat-libs - https://invisible-island.net/ncurses/announce.html#h2-release-notes
sbc - https://git.kernel.org/pub/scm/bluetooth/sbc.git

**Comment by noraj** [comment]
gdb has been updated today an is AL not BA https://archlinux.org/packages/extra/x86_64/gdb/

**Comment by vdun** [comment]
Also:
python-telethon

**Comment by noraj** [comment]
> nacker

https://github.com/carmaa/nacker not updated upstream for 9 years so the last version available
