### ISSUE TITLE
New mirror request [CA, US]

### ISSUE THREAD

**Issue by singingtelegram** [BlackArch/blackarch#3423]
Could you add our mirror to the mirrorlist?

url: https://mirrors.ocf.berkeley.edu/blackarch
protocol: http, https, rsync
Synchronization frequency: every 2 hours
Bandwidth: 20 Gb/s
Location: Berkeley, CA, USA
Contact: sm+mirrors at ocf.berkeley.edu

**Comment by noraj** [comment]
Thanks for the mirroring service!
