### ISSUE TITLE
New Mirror Request [SG]

### ISSUE THREAD

**Issue by lflare** [BlackArch/blackarch#3429]
Hello,

I've started a mirroring service @ [SG.GS](https://sg.gs).

| Protocol | URL |
| --- | --- |
| HTTP | http://mirror.sg.gs/blackarch |
| HTTPS | https://mirror.sg.gs/blackarch |
| RSYNC | rsync://mirror.sg.gs/blackarch |

Sync Interval: 6h
Bandwidth: 10Gbps
Location: Singapore, Singapore
Contact: [mirror-admin@sg.gs](mailto:mirror-admin@sg.gs)

**Comment by noraj** [comment]
Thanks for the mirroring !
