### ISSUE TITLE
[Discussion] BlackArch Most Used Tools category package implementation

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3442]
Type: Discussion

## Discussion

Hello everyone,
since the overall number of tools is very huge, and by installing also several blackarch categories could take a lot of space in our machine or virtual machine, could be the chance to have a package, named for example blackark-most100, that allow to install just the most used tools? Otherwise, for example, if I need wfuzz for fuzzing, xxstrike for xss, nmap, wireshark and other famous tools, the user can avoid to install all the tools of one category, if it needs only some of them. I know that it is possible to install single packages but doing a package like "blackarch-most100" or "blackarch-top100"" for the most 100 used tools, I think could be efficient, mostly in term of disk space.

Thanks.

**Comment by noraj** [comment]
There is this list that is used to build the Slim ISO https://github.com/BlackArch/blackarch-iso/blob/master/slim-iso/packages.x86_64
