### ISSUE TITLE
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is unknown trust

### ISSUE THREAD

**Issue by Am1rTl** [BlackArch/blackarch#3446]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------
Hi, i want update sistem and write `pacman -Syy` .
And then i see this.
````
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is unknown trust
:: Synchronizing package databases...
 core                  155.9 KiB  81.2 KiB/s 00:02 [######################] 100%
 extra                1716.2 KiB   257 KiB/s 00:07 [######################] 100%
 community               6.7 MiB   832 KiB/s 00:08 [######################] 100%
 multilib              169.6 KiB  85.5 KiB/s 00:02 [######################] 100%
 blackarch               3.6 MiB   405 KiB/s 00:09 [######################] 100%
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is unknown trust
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))
```

Thanks for help:)

**Comment by noraj** [comment]
https://www.blackarch.org/faq.html : [Why do I get invalid keyring signature?](https://www.blackarch.org/faq.html#collapseFour)

99% chance it solve your issue

**Comment by killerkalai** [comment]
blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is unknown trust

i get this error. when i use sudo pacman -Syyu . any one say how to solve this problem.
