### ISSUE TITLE
Ligolo-ng

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3448]
- **Name**: Ligolo-ng
- **Source URL**: https://github.com/nicocha30/ligolo-ng
- **Description**: An advanced, yet simple, tunneling/pivoting tool that uses a TUN interface.

**Comment by marianomarciello** [comment]
Hello,
The build process of this package seems broken right now. 
[https://github.com/nicocha30/ligolo-ng/issues/17](https://github.com/nicocha30/ligolo-ng/issues/17)

In the PKGBUILD file we can just download the pre-compiled version? 

Thanks

**Comment by noraj** [comment]
We prefer not to use pre-built binaries for security reasons. We'll wait for upstream to fix.

**Comment by noraj** [comment]
v0.4 is now compatible with go 1.18

**Comment by marianomarciello** [comment]
I think this can be closed :smiley:
