### ISSUE TITLE
blackarch fail to create bootable usb

### ISSUE THREAD

**Issue by satyapal358** [BlackArch/blackarch#3450]
Type: Discussion
I have tried every software to make black arch bootable USB. but it can not work. Please send. I used Power ios, balena Etcher, Rufus, window MUltiple boots, etc. By power iso processing can be complete but after completing pen drive doesn't show in computer. I am using a 32 GB pen drive. I have to use another operating system it can be booted easily. but this gives me tension for 7 weeks.
so what should I do?

**Comment by noraj** [comment]
Di you tried https://wiki.archlinux.org/title/USB_flash_installation_medium? It could be BIOS vs UEFI.

**Comment by satyapal358** [comment]
yes! I tried every action to create a bootable pen drive...

**Comment by satyapal358** [comment]
yes! I did...

**Comment by ikstream** [comment]
While the stick works for a different OS, did you test a different Stick anyway?
Which iso did you try?

**Comment by satyapal358** [comment]
Kali Linux I have used to create bootable USB

Everything I have tried.

**Comment by ikstream** [comment]
If you have a running linux system try using `dd`.

**Comment by satyapal358** [comment]
I am using windows.
