### ISSUE TITLE
john the ripper outputting an error on blackarch

### ISSUE THREAD

**Issue by clides** [BlackArch/blackarch#3458]
Type: Question

## Question

The library attempted to open the following supporting CUDA libraries,
but each of them failed.  CUDA-aware support is disabled.
libcuda.so.1: cannot open shared object file: No such file or directory
libcuda.dylib: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.so.1: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.dylib: cannot open shared object file: No such file or directory
If you are not interested in CUDA-aware support, then run with
--mca opal_warn_on_missing_libcuda 0 to suppress this message.  If you are interested
in CUDA-aware support, then try setting LD_LIBRARY_PATH to the location
of libcuda.so.1 to get passed this issue.
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)

Command I used:

unshadow /etc/shadow /etc/passwd > johntest.txt
john --wordlist=/usr/share/wordlists/rockyou.txt johntest.txt

I get this output message when I tried to use john to crack a password list from unshadow. I have reinstalled john and the issue is still here. I am not very experienced with linux and I can't figure out how to solve the issue. Any help would be greatly appreciated.

edit: also I can't find ssh2john on blackarch, do I have to install it separately?

**Comment by marianomarciello** [comment]
Hello @clides I think you need to install the CUDA library.
This are pretty huge and so I think is better do not install it with john itself. John can work fine without CUDA too.
I installed cuda library with this simple command:
`sudo pacman -S cuda-tools`

Regarding ssh2john I have already installed it in my Blackarch and it is owned by the package blackarch/john. This mean if you install john in the proper way you should have ssh2john too.

Hope this help, let me know if you need other information.

**Comment by clides** [comment]
> 

Thank you for the response, all I need to do is to install the cuda-tools right? How can I install john in the proper way?

**Comment by clides** [comment]
Ok, I will try later, thank you so much for your help

**Comment by noraj** [comment]
Upstream issues (https://github.com/open-mpi/hwloc/issues/354, https://github.com/openwall/john/issues/4765)

put this in your ~/.zshrc

```bash
# https://github.com/open-mpi/hwloc/issues/354                                                                                                                                                                                          
export HWLOC_HIDE_ERRORS=2                                                                                                                                                                                                              
                                                                                                                                                                                                                                         
# https://github.com/openwall/john/issues/4765                                                                                                                                                                                          
 export OMPI_MCA_opal_warn_on_missing_libcuda=0
```
