### ISSUE TITLE
Boot Partition problem

### ISSUE THREAD

**Issue by Zoey335** [BlackArch/blackarch#3462]
Type: Question
system files

## Question

Right after i finish partitioning my hard drives i get an error screen that said

/sbin/blackarch-install: line 1192: /sbin/mkfs.ext4: input/output error
ERROR: Could not create filesystem

lm not really sure what to do at this point can anyone point me in the right direction?

**Comment by marianomarciello** [comment]
Hello @Zoey335 
What kind of partition are you trying to create ?
Maybe you are trying to create an efi parition instead of a gpt partition.

Try to give some more information. Maybe the output of the command `fdisk -l` can help.

**Comment by D3vil0p3r** [comment]
Issue dead. Please close it.
