### ISSUE TITLE
Terminator Framework (Tool)

### ISSUE THREAD

**Issue by G00Dway** [BlackArch/blackarch#3469]
- **Name**: Terminator
- **Source URL**: https://github.com/G00Dway/Terminator
- **Description**: Hello BlackArch Devs! Am an tool developer and cybersecurity expert, i just maked a framework with 15-16 modules here (1 module per day) i named it Terminator framework and i reallly want you devs to add my tool to BlackArch! i am using BlackArch since 2020, and am using it as main driver without any problems! thank you for reading my post :)

**Comment by ikstream** [comment]
Link is dead, closing
