### ISSUE TITLE
Creation of a new category of tools blackarch-ide

### ISSUE THREAD

**Issue by patranger** [BlackArch/blackarch#3472]
- **Name**:
- blackarch-ide
- 
- **Source URL**:
- https://github.com/neovide/neovide
- https://github.com/akiyosi/goneovim
- 
- **Description**:
It would be very helpful if there was a tool category containing the most important and useful IDEs.

**Comment by noraj** [comment]
we package only security related projects, IDE are generic, so we won't create a IDE category

neovide is packaged in AL not BA https://archlinux.org/packages/community/x86_64/neovide/

goneovim is not security related so we won't package it but if you are interested it's in AUR https://aur.archlinux.org/packages?O=0&K=goneovim
