### ISSUE TITLE
Hashcat CUDA and OPENCL errors

### ISSUE THREAD

**Issue by clides** [BlackArch/blackarch#3487]
Type: Question

## Question

When I run "hashcat -I" or "hashcat -b" this error comes out:
--------------------------------------------------------------------------------------
cuInit(): no CUDA-capable device is detected

clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR

ATTENTION! No OpenCL-compatible, HIP-compatible or CUDA-compatible platform found.

You are probably missing the OpenCL, CUDA or HIP runtime installation.

* AMD GPUs on Linux require this driver:
  "AMD ROCm" (4.5 or later)
* Intel CPUs require this runtime:
  "OpenCL Runtime for Intel Core and Intel Xeon Processors" (16.1.1 or later)
* NVIDIA GPUs require this runtime and/or driver (both):
  "NVIDIA Driver" (440.64 or later)
  "CUDA Toolkit" (9.0 or later)
------------------------------------------------------------------------------------
I have already installed the cuda-tools by using "sudo pacman -S cuda-tools" and this is a fresh install of blackarch slim. Do anyone know how to fix this problem? Any help would be greatly appreciated

**Comment by noraj** [comment]
Check https://wiki.archlinux.org/title/GPGPU#OpenCL_Runtime. And if there is a bug, report it to ArchLinux team who packages hashcat.
