### ISSUE TITLE
nodejs-lts-gallium & nodejs 

### ISSUE THREAD

**Issue by skiss0** [BlackArch/blackarch#3499]
conflict when I try to install the [blackarch-windows] whole group

**Comment by noraj** [comment]
both nodejs-lts-gallium and nodejs (and also nodejs-lts-fermium) are provided by AL. And yes the LTS ones are tagged as conflicting with nodejs:

https://github.com/archlinux/svntogit-community/blob/728093bfbc9023b7435b2198e11753c30d9e4379/trunk/PKGBUILD#L16

So you can't have both at the same time. Don't install the whole group and pick only the tools that you need. If you need several version of nodejs in parallel take a look at https://asdf-vm.com/.

**Comment by skiss0** [comment]
> both nodejs-lts-gallium and nodejs (and also nodejs-lts-fermium) are provided by AL. And yes the LTS ones are tagged as conflicting with nodejs:
> 
> https://github.com/archlinux/svntogit-community/blob/728093bfbc9023b7435b2198e11753c30d9e4379/trunk/PKGBUILD#L16
> 
> So you can't have both at the same time. Don't install the whole group and pick only the tools that you need. If you need several version of nodejs in parallel take a look at https://asdf-vm.com/.

Thanks
