### ISSUE TITLE
pfff has a signature fail on fresh install

### ISSUE THREAD

**Issue by peterclemenko** [BlackArch/blackarch#3515]
pfff has a pgp signature fail on a fresh install

note i am using arch wsl, so it might be an impact, but every other package seems to work fine

**Comment by peterclemenko** [comment]
:: Retrieving packages...
 pfff-0.29-9-x86_64                           30.1 MiB  3.21 MiB/s 00:09 [########################################] 100%(5995/5995) checking keys in keyring                                     [########################################] 100%
(5995/5995) checking package integrity                                   [########################################] 100%
error: pfff: signature from "Jürgen Hötzel (Arch Linux developer key) <juergen@archlinux.org>" is marginal trust
:: File /var/cache/pacman/pkg/pfff-0.29-9-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] Y
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.
[root@Bladerunner ~]#

**Comment by noraj** [comment]
pfff is outdated and must be updated but a new PKGBUILD is required, see #2986. Consider this package as not working.

However, I'm not sure that this PGP issue is related or not.

PS: I'll close this issue in favor of  #2986
