### ISSUE TITLE
Bytecode-Viewer UPDATE

### ISSUE THREAD

**Issue by blue-devil** [BlackArch/blackarch#3516]
- **Name**: Bytecode-Viewer
- **Source URL**: https://github.com/Konloch/bytecode-viewer/releases/tag/v2.11.2
- **Description**: Bytecode Viewer - a lightweight user-friendly Java/Android Bytecode Viewer, Decompiler & More.

NOTE: When i clicked new issue there are several options but no "Upgrade Request", so I open the issue under `tool request`

**Comment by D3vil0p3r** [comment]
Already updated. Close please
