### ISSUE TITLE
Error while installing owtf

### ISSUE THREAD

**Issue by Szewcson** [BlackArch/blackarch#3523]
### Bug description

While installing owtf error appears.

### Steps to reproduce
1.) Install owtf

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
error:
```
Collecting PTP==0.4.2
  Using cached PTP-0.4.2.tar.gz (694 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in PTP setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Installation should finish without errors

**Comment by D3vil0p3r** [comment]
@noraj the mentioned error does not appear anymore. Btw can you just do a test install on your side? Thanks

**Comment by noraj** [comment]
Install works
