### ISSUE TITLE
error: failed retrieving file 'blackarch.db' from ftp.halifax.rwth-aachen.de : SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by AkumuKernel** [BlackArch/blackarch#3539]
Hi Hi, I have this error
`error: failed retrieving file 'blackarch.db' from ftp.halifax.rwth-aachen.de : SSL certificate problem: unable to get local issuer certificate`

How can I fix it?

**Comment by noraj** [comment]
This mirror has an expired certificate, just pick another mirror in /etc/mirrorlist

https://wiki.archlinux.org/title/Mirrors
