### ISSUE TITLE
Mugshot outdated

### ISSUE THREAD

**Issue by visious25** [BlackArch/blackarch#3540]
Hi, you should update your repository. I got Mugshot from AUR.

$ pacman -Si mugshot 
Repository       : blackarch
Name               : mugshot
Version             : 0.4.2-1
Description      : Program to update personal user details.
Architecture     : any
URL                  : https://github.com/bluesabre/mugshot
Licenses           : GPL3
Groups             : None
Provides           : None
Depends On     : gtk3  python-pexpect  python-dbus  python-cairo python-gobject
                           accountsservice
Optional Deps  : cheese: webcam support
                           pidgin: update buddy icon
                           libreoffice: update user details
Conflicts With   : None
Replaces           : None
Download Size : 117.69 KiB
Installed Size    : 774.74 KiB
Packager          : Levon Kayan <noptrix@nullsecurity.net>
Build Date        : Tue 22 Dec 2020 07:13:33 PM EET
Validated By     : MD5 Sum  SHA-256 Sum  Signature

$ pacman -Qi mugshot 
Name               : mugshot
Version             : 0.4.3-3
Description       : Program to update personal user details
Architecture      : any
URL                   : https://github.com/bluesabre/mugshot
Licenses            : GPLv3
Groups              : None
Provides            : None
Depends On      : gtk3  python-pexpect  python-cairo  python-gobject
                            accountsservice
Optional Deps   : cheese: webcam support
                            pidgin: update buddy icon [installed]
                            libreoffice: update user details [installed]
                            gnome-control-center: collection of stock face icons
Required By       : None
Optional For      : None
Conflicts With    : None
Replaces            : None
Installed Size     : 781.58 KiB
Packager           : Unknown Packager
Build Date         : Tue 27 Sep 2022 09:31:10 AM EEST
Install Date        : Thu 29 Sep 2022 03:47:25 PM EEST
Install Reason    : Explicitly installed
Install Script      : No
Validated By      : None

**Comment by noraj** [comment]
@noptrix We have 0.4.3 in the [PKGBUILD](https://github.com/BlackArch/blackarch/blob/master/packages/mugshot/PKGBUILD) but the repository still shows 0.4.2. 

It seems it is because the build is failing:

```
==> Starting prepare()...
patching file mugshot_lib/Builder.py
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file mugshot_lib/Builder.py.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
==> ERROR: Build failed, check /home/noraj/blackarch_chroot/blackarch/build
Failed to build the package.
```

I tried building, installing and running it without the patch and it seems to work.

**Comment by visious25** [comment]
I don't know, with old version of mugshot I'm getting this error in terminal:

$ mugshot
Traceback (most recent call last):
File "/usr/bin/mugshot", line 35, in
import mugshot
ModuleNotFoundError: No module named 'mugshot'
