### ISSUE TITLE
Parcial Clone

### ISSUE THREAD

**Issue by Lowkkii** [BlackArch/blackarch#3542]
Recently i got a new USB disk, with 2TB of storage, and i use it for clone pentesting tools and similars for remote use (normally i just clone source). I tried to clone th` BlackArch git repo` directly, but seems not much practical - while`BlackArch pacman repo `has a division for tools type. Exist any form to clone BlackArch packet tool without installing or setting a path for it? Or clone just a subfolder for tools?
I dont pretend clone all tools, therefore i asking about clone specific packet tool, like `pacman -Syu |  grep BlackArch-Forensic` to `media/generic-usb` to become a folder.

PS: i know its kind annoying, but i don't want clone directly from github, 'cause is "messed up".

_i aren't english, so if i confused or write something unreadable, just advise and i try to reform the phrase. Sorry!_

**Comment by noraj** [comment]
What do you want to copy on your USB stick? Install files (PKGBUILDs) or pre-compiled binaries (tar.zst)?

**Comment by Merylne** [comment]
i think in that situation is better use pre-compiled binaries, once time i use in several computers. But when i not have any experience with this, if you recommend one for this methods, I appreciate it too.
