### ISSUE TITLE
paceman fail

### ISSUE THREAD

**Issue by lilkitten667** [BlackArch/blackarch#3549]
──(root㉿TweakPadV25)-[/home/lilkitten666]
└─# sudo ./strap.sh
[+] installing blackarch keyring...
./strap.sh: 117: pacman-key: not found
./strap.sh: 123: pacman: not found
[-] ERROR: keyring installation failed

**Comment by noraj** [comment]
What OS are you running this on? BlackArch supports only ArchLinux so you must have `pacman`.

**Comment by lilkitten667** [comment]
wsl it is a temp until i can replace my computer i am "fixing" this one, he wants it lol
wiindows beta enterprizre

**Comment by lilkitten667** [comment]
windows 11 latest pre-release

**Comment by lilkitten667** [comment]
i have tried installing the actual package itself and installed other things i have no idea, i DL the actuail iso image. i am at a loss this isn't mu first clean install of an OS, Arch? no!! thats why i was so excited to get a computer that could hold it. tho temp

**Comment by noraj** [comment]
You can make a VM with BA. Either use the OVA or the Slim ISO: https://blackarch.org/downloads.html.
