### ISSUE TITLE
I can't update Blackarch

### ISSUE THREAD

**Issue by nyShade** [BlackArch/blackarch#3584]
Type: Question

## Question
OK, guys I am using the 2021.09.01 FULL iso and I have tried my hardest to update/upgrade my Blackarch. I can sync ...pacman -Syy but when I pacman -Syyu i get a lot of "questions" I guest you can call it.. 
DO I want to replace this with that (Y/n)
Do I want to keep community version (y/N)
I counted 15 questions.
So I did..
pacman Syyu --needed blackarch --overwrite='*'
and still got all these questions...
DO I want to upgrade this, removing this package breaks that, keep community version.

Never had any problem before updating/upgrading.

ANy newer version of the full iso coming out soon? Or Can someone tell me how to get pass all these dam question so I can update/upgrade?

**Comment by noraj** [comment]
https://man.archlinux.org/man/core/pacman/pacman.8.en, `--noconfirm`
