### ISSUE TITLE
Please add all awesome web hacking bug hunting super cool tools from ProjectDiscovery 

### ISSUE THREAD

**Issue by CyberGhazi786** [BlackArch/blackarch#3587]
Please add all awesome web hacking bug hunting super cool tools from ProjectDiscovery 
- **Name**: See the link
- **Source URL**: https://github.com/orgs/projectdiscovery/repositories
- **Description**: 83 Tools

**Comment by noraj** [comment]
most of them are already there

**Comment by CyberGhazi786** [comment]
Better to close the BlackArch project. You love to deny users' requests. It's very easy to say, "Use Docker Compose," but do you know that Docker Composers lack many of the functions of these frameworks? I am very upset and disappointed by your ignorant comments that you reply against all tools or framework requests on BlackArch Linux platform. I am leaving BlackArch and moving back to kali linux because these people at least satisfy their users' requests. Goodbye. Black Arch is a junk yard of obsolete tools and scripts that no one uses in current times.
BlackArch Linux R.I.P 🫡💐👋🙏♥️👍
