### ISSUE TITLE
Evil-WinRM - OpenSSL::Digest::DigestError happened, message is Digest initialization failed: initialization error

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3593]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

When `evil-winrm` tool from BlackArch repo is run, the following output is generated:
```
evil-winrm -u Jareth -p sarah -i 10.10.79.152

Evil-WinRM shell v3.4

Info: Establishing connection to remote endpoint

Error: An error of type OpenSSL::Digest::DigestError happened, message is Digest initialization failed: initialization error

Error: Exiting with code 1
```
Furthermore, each time evil-winrm is run, this git warning is produced:
```
evil-winrm -h            
fatal: not a git repository (or any of the parent directories): .git

<SNIP>
```
This issue occurs also in BlackArch after a Full Upgrade of the system.

In Debian-based OS, Evil-WinRM works correctly.

### Steps to reproduce

- By guessing Arch system has BlackArch repo available, run `sudo pacman -Syyu`
- Run `sudo pacman -Syy evil-winrm`
- Take a test machine where you can test Evil-WinRM, for example this TryHackMe machine: https://tryhackme.com/room/yearoftheowl
- Run `evil-winrm -u Jareth -p sarah -i 10.10.79.152`

where `10.10.79.152` is the Target IP address. It will be different in your case.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

The following output is produced:
```
Evil-WinRM shell v3.4

Info: Establishing connection to remote endpoint

Error: An error of type OpenSSL::Digest::DigestError happened, message is Digest initialization failed: initialization error

Error: Exiting with code 1
```
Furthermore, each time evil-winrm is run, this git warning is produced:
```
evil-winrm -h            
fatal: not a git repository (or any of the parent directories): .git

<SNIP>
```

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

The following is the expected output:
```
Evil-WinRM shell v3.4

Info: Establishing connection to remote endpoint

*Evil-WinRM* PS C:\Users\Jareth\Documents>
```

### Info for developers

**GNU/Linux distribution:** Arch Linux
**Tool version:** 3.4 (latest)

**Comment by noraj** [comment]
> Run `sudo pacman -Syy evil-winrm`

Don't do that, it's partial upgrade https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported

I'll take a look at EvilWinrm openssl issue and update it at the same time.

**Comment by noraj** [comment]
Also note evil-winrm is listed as broken in this issue https://github.com/BlackArch/blackarch/issues/3519#issuecomment-1276680649

**Comment by noraj** [comment]
> Furthermore, each time evil-winrm is run, this git warning is produced:
> 
> ```
> evil-winrm -h            
> fatal: not a git repository (or any of the parent directories): .git
> 
> <SNIP>
> ```

I have fixed this issue in #3597 but I can't investigate on the OpenSSL error until #3519 is fixed

**Comment by DF001** [comment]
@noraj issue has been fixed this morning go to /etc/ssl/openssl.cnf and under  
[openssl_init]
   providers = provider_sect
   [provider_sect]
   default = default_sect
add: 
legacy = legacy_sect
so it shows as 
[provider_sect]
default = default_sect
legacy = legacy_sect
than 
search for 
[default_sect]
#activate = 1
remove the # and under that line add 
[legacy_sect]
activate = 1
save the file and evil-winrm will work again
Cause of issue. openssl was missing md4

**Comment by noraj** [comment]
It would be best it has a dedicated config file

**Comment by D3vil0p3r** [comment]
> It would be best it has a dedicated config file

In your opinion, what is the best way for managing this? Inside the evil-winrm PKGBUILD or in a separated manner from evil-winrm (that could mean create and set manually a dedicated openssl config file)?

**Comment by noraj** [comment]
> In your opinion, what is the best way for managing this? Inside the evil-winrm PKGBUILD or in a separated manner from evil-winrm (that could mean create and set manually a dedicated openssl config file)?

IDK openssl well, IDK if it can load a custom config file from a path.

**Comment by D3vil0p3r** [comment]
After the update of evil-winrm by `sudo pacman -Syyu`, I don't get that warning about .git but I get the following warning:
```
fatal: detected dubious ownership in repository at '/usr/share/evil-winrm'
To add an exception for this directory, call:

	git config --global --add safe.directory /usr/share/evil-winrm
```
I tried also to remove evil-winrm by pacman and remove `/usr/share/evil-winrm` folder and reinstall it but I get the same warning.

**Comment by D3vil0p3r** [comment]
Hey @noraj 
about the warning above when Evil WinRM is run:
```
fatal: detected dubious ownership in repository at '/usr/share/evil-winrm'
To add an exception for this directory, call:

	git config --global --add safe.directory /usr/share/evil-winrm
```
how is it possible to solve it?

**Comment by noraj** [comment]
This is due to https://github.com/BlackArch/blackarch/blob/e58c627a7b79fb6ed38d9b88eb3853345b645c48/packages/evil-winrm/PKGBUILD#L40 that was need to fix https://github.com/BlackArch/blackarch/issues/3593#issuecomment-1325778440

You can try playing with `safe.directory` git option to see how we can integrate this in the PKGBUILD.

**Comment by D3vil0p3r** [comment]
> This is due to
> 
> https://github.com/BlackArch/blackarch/blob/e58c627a7b79fb6ed38d9b88eb3853345b645c48/packages/evil-winrm/PKGBUILD#L40
> 
> that was need to fix [#3593 (comment)](https://github.com/BlackArch/blackarch/issues/3593#issuecomment-1325778440)
> You can try playing with `safe.directory` git option to see how we can integrate this in the PKGBUILD.

I will try. I have only a question for you: is there a sense or a reason to keep `.git` folder in `/usr/share/evil-winrm`?

**Comment by D3vil0p3r** [comment]
@noraj by my tests, if `git config --global --add safe.directory /usr/share/evil-winrm` is added in `package()` function of the PKGBUILD, it works and it is run as the current user. The problem is that you cannot manage automatically the removal of `safe.directory` variable when the package is uninstalled.

The best idea should be to add `git config --global --add safe.directory /usr/share/evil-winrm` in the `.install` script file because in this manner is possible also to remove `safe.directory` variable when the package is uninstalled. The problem of this approach is that, unlike the `package()` function in PKGBUILD, the `.install` script is run as `root` instead of the current user, so the `safe.directory` variable will be set only for the root user, and not for the current user, so if the current user calls `evil-winrm` command, it will get always that warning.

I need to understand if the `.install` script can be run as the current user that is installing the package.

**Comment by D3vil0p3r** [comment]
According to my last tests, this is my working proposal that manages also cases of reinstallation of the package and prevent multiple `safe.directory` variable to be set on git. My idea is applied only to the `.install` file that has the following code:
```
post_install() {
  set -e
  cd /usr/share/evil-winrm
  rm -f Gemfile.lock
  bundle config build.nokogiri --use-system-libraries
  bundle config set --local path 'vendor/bundle'
  bundle install
  if ! su $SUDO_USER -c "git config --global --get safe.directory /usr/share/evil-winrm"; then
      su - $SUDO_USER -c "git config --global --add safe.directory /usr/share/evil-winrm"
  fi
}

post_upgrade() {
  post_install "$@"
}

post_remove() {
   echo "Uninstalling Evil WinRM..."
   if su $SUDO_USER -c "git config --global --get safe.directory /usr/share/evil-winrm"; then
      su $SUDO_USER -c "git config --global --unset-all safe.directory /usr/share/evil-winrm"
   fi
}
```
`.install` script is run as root but among its environment variables, `$SUDO_USER` is the user calling the installation of the package. I tested it and it works correctly.

**Comment by noraj** [comment]
Does it work with `--local` who set the option in `.git/` and not on a per user basis?

**Comment by D3vil0p3r** [comment]
With that approach, how do you manage the removal of `safe.directory` when `evil-winrm` will be uninstalled?

**Comment by noraj** [comment]
> By that approach, how do you manage the removal of `safe.directory` when `evil-winrm` will be uninstalled?

Since it will only set stuff in `.git/`, the removal of `/usr/share/evil-winrm/` when performing `pacman -R` would get rid of it. But I'm not sure this option works locally.

**Comment by D3vil0p3r** [comment]
> > By that approach, how do you manage the removal of `safe.directory` when `evil-winrm` will be uninstalled?
> 
> Since it will only set stuff in `.git/`, the removal of `/usr/share/evil-winrm/` when performing `pacman -R` would get rid of it. But I'm not sure this option works locally.

I tested it but when I run `evil-winrm` I still get that warning message despite the variable has been added in `/usr/share/win-rm/.git/config` as:
```
[safe]
	directory = /usr/share/evil-winrm
```

**Comment by soufian2017** [comment]
A working patch for the `/etc/ssl/openssl.cnf` file would be this
https://github.com/openssl/openssl/issues/21247#issuecomment-1598716974

```
[openssl_init]
providers = provider_sect

[provider_sect]
default = default_sect
legacy = legacy_sect

[default_sect]
activate = 1

[legacy_sect]
activate = 1
```
