### ISSUE TITLE
ReconFTW

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3603]
- **Name**: ReconFTW
- **Source URL**: https://github.com/six2dez/reconftw
- **Description**: automated recon on a target domain

**Comment by ikstream** [comment]
I am not sure if we should package this. To me it looks like something better run from a container than on Blackarch as it basically pulls in and installs a lot of tools.

**Comment by dualfade** [comment]
Agreed. It does run best containerized and requires quite a few dependencies to make it all work. 

This is how I personally use it when I do.
------- Original Message -------

**Comment by noraj** [comment]
> I am not sure if we should package this. To me it looks like something better run from a container than on Blackarch as it basically pulls in and installs a lot of tools.

I just opened a clean issue replacing https://github.com/BlackArch/blackarch/issues/3602 that was a bit bloated with off-topic stuff.
