### ISSUE TITLE
could not update pls help me with this issue

### ISSUE THREAD

**Issue by VIP-Joker** [BlackArch/blackarch#3604]
pacman -Syyu 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 blackarch is up to date
:: Starting full system upgrade...
:: Replace absl-py with community/python-absl? [Y/n] 
:: Replace at-spi2-atk with extra/at-spi2-core? [Y/n] 
:: Replace atk with extra/at-spi2-core? [Y/n] 
:: Replace crda with core/wireless-regdb? [Y/n] 
warning: gef: local (2076.ec114a6-1) is newer than community (2022.06-2)
warning: gsocket: local (448.bc85158-1) is newer than community (1.4.38-2)
:: Replace hwids with core/hwdata? [Y/n] 
:: Replace intel-mkl with community/intel-oneapi-mkl? [Y/n] 
:: Replace lib32-atk with multilib/lib32-at-spi2-core? [Y/n] 
:: Replace libmemcached with community/libmemcached-awesome? [Y/n] 
warning: plumber: local (18.3f1be68-3) is newer than community (1.8.0-1)
warning: python-ana: local (0.06-4) is newer than community (0.06-1)
warning: python-cooldict: local (1.04-4) is newer than community (1.04-1)
warning: python-crc16: local (0.1.1-7) is newer than blackarch (0.1.1-3)
:: Replace python-jaraco with community/python-jaraco.classes? [Y/n] 
:: Replace python-jaraco with community/python-jaraco.collections? [Y/n] 
:: Replace python-jaraco with community/python-jaraco.functools? [Y/n] 
:: Replace python-jaraco with community/python-jaraco.itertools? [Y/n] 
:: Replace python-jaraco with community/python-jaraco.logging? [Y/n] 
:: Replace python-jaraco with community/python-jaraco.stream? [Y/n] 
:: Replace python-jaraco with community/python-jaraco.text? [Y/n] 
warning: python-minidump: local (1:0.0.18-1) is newer than community (0.0.21-2)
:: Replace python-nest_asyncio with community/python-nest-asyncio? [Y/n] 
:: Replace python-ropper with community/ropper? [Y/n] 
:: Replace python-sgmllib with extra/python-sgmllib3k? [Y/n] 
:: Replace python-z3 with community/python-z3-solver? [Y/n] 
warning: ruby-net-http-persistent: local (2:4.0.0-1) is newer than community (4.0.1-1)
warning: rustscan: local (648.a444ab6-1) is newer than community (2.1.1-1)
warning: syft: local (674.58b21c0-1) is newer than community (0.60.3-1)
warning: trivy: local (549.c159501d-1) is newer than community (0.34.0-1)
:: Replace typo-enumerator with blackarch/typo3scan? [Y/n] 
:: Replace wxgtk-common with extra/wxwidgets-common? [Y/n] 
:: Replace wxgtk3 with extra/wxwidgets-gtk3? [Y/n] 
:: Replace xmlrpc-c with community/libxmlrpc? [Y/n] 
resolving dependencies...
:: There are 126 providers available for tessdata:
:: Repository community
   1) tesseract-data-afr  2) tesseract-data-amh  3) tesseract-data-ara
   4) tesseract-data-asm  5) tesseract-data-aze  6) tesseract-data-aze_cyrl
   7) tesseract-data-bel  8) tesseract-data-ben  9) tesseract-data-bod
   10) tesseract-data-bos  11) tesseract-data-bre  12) tesseract-data-bul
   13) tesseract-data-cat  14) tesseract-data-ceb  15) tesseract-data-ces
   16) tesseract-data-chi_sim  17) tesseract-data-chi_tra
   18) tesseract-data-chr  19) tesseract-data-cos  20) tesseract-data-cym
   21) tesseract-data-dan  22) tesseract-data-dan_frak  23) tesseract-data-deu
   24) tesseract-data-deu_frak  25) tesseract-data-div  26) tesseract-data-dzo
   27) tesseract-data-ell  28) tesseract-data-eng  29) tesseract-data-enm
   30) tesseract-data-epo  31) tesseract-data-equ  32) tesseract-data-est
   33) tesseract-data-eus  34) tesseract-data-fao  35) tesseract-data-fas
   36) tesseract-data-fil  37) tesseract-data-fin  38) tesseract-data-fra
   39) tesseract-data-frk  40) tesseract-data-frm  41) tesseract-data-fry
   42) tesseract-data-gla  43) tesseract-data-gle  44) tesseract-data-glg
   45) tesseract-data-grc  46) tesseract-data-guj  47) tesseract-data-hat
   48) tesseract-data-heb  49) tesseract-data-hin  50) tesseract-data-hrv
   51) tesseract-data-hun  52) tesseract-data-hye  53) tesseract-data-iku
   54) tesseract-data-ind  55) tesseract-data-isl  56) tesseract-data-ita
   57) tesseract-data-ita_old  58) tesseract-data-jav  59) tesseract-data-jpn
   60) tesseract-data-jpn_vert  61) tesseract-data-kan  62) tesseract-data-kat
   63) tesseract-data-kat_old  64) tesseract-data-kaz  65) tesseract-data-khm
   66) tesseract-data-kir  67) tesseract-data-kmr  68) tesseract-data-kor
   69) tesseract-data-kor_vert  70) tesseract-data-lao  71) tesseract-data-lat
   72) tesseract-data-lav  73) tesseract-data-lit  74) tesseract-data-ltz
   75) tesseract-data-mal  76) tesseract-data-mar  77) tesseract-data-mkd
   78) tesseract-data-mlt  79) tesseract-data-mon  80) tesseract-data-mri
   81) tesseract-data-msa  82) tesseract-data-mya  83) tesseract-data-nep
   84) tesseract-data-nld  85) tesseract-data-nor  86) tesseract-data-oci
   87) tesseract-data-ori  88) tesseract-data-pan  89) tesseract-data-pol
   90) tesseract-data-por  91) tesseract-data-pus  92) tesseract-data-que
   93) tesseract-data-ron  94) tesseract-data-rus  95) tesseract-data-san
   96) tesseract-data-sin  97) tesseract-data-slk  98) tesseract-data-slk_frak
   99) tesseract-data-slv  100) tesseract-data-snd  101) tesseract-data-spa
   102) tesseract-data-spa_old  103) tesseract-data-sqi
   104) tesseract-data-srp  105) tesseract-data-srp_latn
   106) tesseract-data-sun  107) tesseract-data-swa  108) tesseract-data-swe
   109) tesseract-data-syr  110) tesseract-data-tam  111) tesseract-data-tat
   112) tesseract-data-tel  113) tesseract-data-tgk  114) tesseract-data-tgl
   115) tesseract-data-tha  116) tesseract-data-tir  117) tesseract-data-ton
   118) tesseract-data-tur  119) tesseract-data-uig  120) tesseract-data-ukr
   121) tesseract-data-urd  122) tesseract-data-uzb
   123) tesseract-data-uzb_cyrl  124) tesseract-data-vie
   125) tesseract-data-yid  126) tesseract-data-yor

Enter a number (default=1): 
looking for conflicting packages...
warning: removing 'nodejs' from target list because it conflicts with 'nodejs-lts-gallium'
:: nodejs-lts-gallium and nodejs are in conflict. Remove nodejs? [y/N] y
:: espeak-ng and espeak are in conflict. Remove espeak? [y/N] y
:: ruby-sqlite3 and ruby1.8-sqlite3 are in conflict. Remove ruby1.8-sqlite3? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: installing ffmpeg (2:5.1.2-1) breaks dependency 'libavcodec.so=58-64' required by java8-openjfx
:: installing ffmpeg (2:5.1.2-1) breaks dependency 'libavformat.so=58-64' required by java8-openjfx
:: removing wxgtk-common breaks dependency 'wxgtk-common' required by wxgtk2

**Comment by VIP-Joker** [comment]
its keep on showing error: failed to prepare transaction (could not satisfy dependencies) in vbox

**Comment by noraj** [comment]
1. Try removing some old libraries that are conflicting.
2. `java8-openjfx` is not in official AL repos, it's AUR
3. please search of open issue before opening a new one: #3529. This has been reported 2 years ago upstream but they don't seems to care that much.

If you have Autopsy installed just removed it's it's deprecated in BA repo until its dependencies are updated upstream.

**Comment by VIP-Joker** [comment]
Thank you it worked like a charm
