### ISSUE TITLE
Katana

### ISSUE THREAD

**Issue by ikstream** [BlackArch/blackarch#3612]
- **Name**: Katana
- **Source URL**: https://github.com/projectdiscovery/katana
- **Description**: A next-generation crawling and spidering framework

**Comment by ikstream** [comment]
We package [katana(s)](http://sourceforge.net/projects/katanas/) at the moment, which uses python2 and hasn't seen any substantial updates in the last years. 

I haven't checked if the packaged version works as expected, but if we keep it, we could rename it to [katana-framework](https://github.com/PowerScript/KatanaFramework) and use the github link as it seems to have received some updates since last build date.

**Comment by noraj** [comment]
Oh there are two things:

- [ ] Rename the current katana (https://github.com/PowerScript/KatanaFramework) to katana-framework
- [ ] Add katana (https://github.com/projectdiscovery/katana)
