### ISSUE TITLE
OSERT - /usr/bin/osert:164:in `<main>': undefined method `order!' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3616]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

It is not a blocking bug. When OSERT tool is run by `osert` command, the tool returns the following error:
```
osert

/usr/bin/osert:164:in `<main>': undefined method `order!' for nil:NilClass (NoMethodError)
```
Is it possible to trigger the "help" output when `osert` command is launched in order to have a clean output?

Same when a command like `osert init TEST` is run:
```
osert init TEST

[+] Choose a Certification:
0. OSCP
1. OSWA
2. OSWE
3. OSCE
4. OSEE
5. OSWP
6. OSED
7. OSEP
8. OSDA
9. OSMR
> /usr/bin/osert:186:in `gets': No such file or directory @ rb_sysopen - TEST (Errno::ENOENT)
	from /usr/bin/osert:186:in `gets'
	from /usr/bin/osert:186:in `<main>'
```
or by using `generate` subcommand:
```
osert generate TEST

[+] Preparing your final report...
[+] Choose syntax highlight style [breezedark]:
0. pygments
1. tango
2. espresso
3. zenburn
4. kate
5. monochrome
6. breezedark
7. haddock
> /usr/bin/osert:239:in `gets': No such file or directory @ rb_sysopen - TEST (Errno::ENOENT)
	from /usr/bin/osert:239:in `gets'
	from /usr/bin/osert:239:in `<main>'
```

Summarizing, is it possible to implement an error handling method that, for example, instead to show these errors, show the "help" output for `osert` command and the "sub-help" for `init` and `generate` subcommands?

### Steps to reproduce

- `osert` or `osert init TEST` or `osert generate TEST`

**Actual result:** Shown in the description above.

**Expected result:** The related help outputs of those commands.

### Info for developers

**GNU/Linux distribution:** Arch Linux
**Tool version:** 76.47e77b2-1

**Comment by noraj** [comment]
> It is not a blocking bug. When OSERT tool is run by `osert` command, the tool returns the following error:
> 
> ```
> osert
> 
> /usr/bin/osert:164:in `<main>': undefined method `order!' for nil:NilClass (NoMethodError)
> ```

This one appears only when you provide no command or options.

```
$ osert -h
Usage: osert <subcommand> [options]

Markdown Templates for Offensive Security OSCP, OSWE, OSEE, OSWP, OSEP, OSED Exam Report.

Sub-commands:
  init     :  Copy a template that you will use to write your report
  generate :  Generate your PDF report and 7z archive

See 'osert COMMAND --help' for more information on a specific command.
```

When you provide a command and no option or a valid option there is no error either.

```
$  osert init
[+] Choose a Certification:
0. OSCP
1. OSWA
2. OSWE
3. OSCE
4. OSEE
5. OSWP
6. OSED
7. OSEP
8. OSDA
9. OSMR

$ osert init -h
Usage: init [options]
    -o, --output REPORT              File path to store a copy of the template to write your report
```

I don't think it's really useful but still I added some tiny error handling https://github.com/noraj/OSCP-Exam-Report-Template-Markdown/commit/705b4fc73441fd334bf6c185493a0f1043d6b644.

Note :It's not a BA issue but an upstream issue. Please don't open issue on BA tracker.

**Comment by D3vil0p3r** [comment]
Hello @noraj Thank you for your update. I have just a last request about the error handling in OSERT for a clean output:

When the user runs `osert dsadsad`, the output is:
```
/usr/bin/osert:168:in `<main>': undefined method `order!' for nil:NilClass (NoMethodError)
```
Is it possible also here to spawn the help output instead of this error?

Furthermore, when `osert init dadad` is run, we get the correct help output of init command, but before it, we get the list of certifications choice that at this point is useless to show because the initial command is wrong:
```
osert init dsadsad

[+] Choose a Certification:
0. OSCP
1. OSWA
2. OSWE
3. OSCE
4. OSEE
5. OSWP
6. OSED
7. OSEP
8. OSDA
9. OSMR
> No such file or directory @ rb_sysopen - dsadsa
Usage: osert init [options]
    -o, --output REPORT              File path to store a copy of the template to write your report
```
Is it possible to spawn only the help output without:
```
[+] Choose a Certification:
0. OSCP
1. OSWA
2. OSWE
3. OSCE
4. OSEE
5. OSWP
6. OSED
7. OSEP
8. OSDA
9. OSMR
> No such file or directory @ rb_sysopen - dsadsa
```
?
Then, also `osert generate sadsada` has the same weird output.

Can you give a look? Thank you in advance!
