### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by Croccodoyle** [BlackArch/blackarch#3621]
-  I have searched open and closed issues for duplicates
-  I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Steps to reproduce

- I am trying to ru the Spiderfoot Dev Build on MacOS Monterey 12.6 with M1Pro. 
- have successfully run install code including requirements.txt

**Actual result:**
  File "/Users/XXX/spiderfoot/spiderfoot/db.py", line 318, in __init__
sqlite3.OperationalError: unable to open database file

**Expected result:** No error

**Device:** MacBook Pro M1 Pro Monterey 12.6

**Comment by noraj** [comment]
> have successfully run install code including requirements.txt

You installed spiderfoot with pacman from BA repo or manually?

> File "/Users/XXX/spiderfoot/spiderfoot/db.py", line 318, in **init**
> sqlite3.OperationalError: unable to open database file

What command did you run?

Everything is working as expected:

```
$ sudo pacman -S spiderfoot
$ spiderfoot -h
$ spiderfoot -s example.org
```

I'm closing this issue since you didn't provide install step and runtime command and everything is working when following the intended way.
