### ISSUE TITLE
Rengine

### ISSUE THREAD

**Issue by CyberGhazi786** [BlackArch/blackarch#3624]
⣶⣻⠿⠿⣛⣛⠉⠉⠁⠀⠀⠀⠀⠀⠉⠉⢛⣛⡿⢿⢿⣶
⣿⣿⢸⡟⠉⣣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣜⠉⢻⡇⣿⣿
⢿⣹⠘⠃⠀⠉⢿⣦⠀⠀⠀⠀⠀⠀⣴⡿⠉⠀⠀⡇⣿⣿
⢸⣿⡇⠀⠀⠀⣸⣮⠀⠀⠀⠀⠀⠀⣵⡇⠀⠀⠀⢀⣿⡿
⠘⣿⣧⠀⠀⠐⢿⣿⣀⠀⠀⠀⠀⣀⣿⡿⠂⠀⠀⢸⣿⡇
⠀⢻⣿⡄⠀⠀⠀⠹⣿⣿⣦⣴⣿⣿⠏⠀⠀⠀⠀⣿⣿⠀
⠀⠈⣿⣷⠀⠀⠀⠀⣿⣟⡿⢿⣿⡿⠀⠀⠀⠀⣼⣿⠇⠀
⠀⠀⠘⣿⣧⠀⠀⠀⠸⣿⣿⣿⣿⠇⠀⠀⠀⣰⣿⠏⠀⠀
⠀⠀⠀⠘⣿⣷⡀⠀⠀⢹⣿⣿⠏⠀⠀⠀⣴⣿⠏⠀⠀⠀
⠀⠀⠀⠀⠈⢻⣿⣄⢄⡀⢿⡿⠀⡀⣠⣾⡿⠃⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠙⠿⣷⣽⡷⡶⣫⣾⡿⠋⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⠿⠿⠟⠉⠀⠀⠀⠀⠀⠀⠀⠀

Rengine | Automatic Recon Framework |  https://github.com/yogeshojha/rengine

Please add this excellent automatic deep web recon framework in Black Arch Linux.

An automated reconnaissance framework for web applications with a focus on highly configurable streamlined recon process via Engines, recon data correlation, and organization, continuous monitoring, backed by a database, and simple yet intuitive User Interface.
reNgine makes it easy for penetration testers to gather reconnaissance with minimal configuration and with the help of reNgine's correlation, it just makes recon effortless.

Thanks,

**Comment by noraj** [comment]
It's not a tool but a web app that use many tools. It's available as a docker-compose you can use to deploy it easily.

**Comment by CyberGhazi786** [comment]
Better to close the BlackArch project. You love to deny users' requests. It's very easy to say, "Use Docker Compose," but do you know that Docker Composers lack many of the functions of these frameworks? I am very upset and disappointed by your ignorant comments that you reply against all tools or framework requests on BlackArch Linux platform. I am leaving BlackArch and moving back to kali linux because these people at least satisfy their users' requests. Goodbye. Black Arch is a junk yard of obsolete tools and scripts that no one uses in current times.
BlackArch Linux R.I.P 🫡💐👋🙏♥️👍
