### ISSUE TITLE
ReconFTW | https://github.com/six2dez/reconftw.git | Awesome automatic web vulnerability discovery framework.

### ISSUE THREAD

**Issue by CyberGhazi786** [BlackArch/blackarch#3625]
⢰⠓⠒⢳⠔⠋⠉⠉⠓⣤⠔⠒⠒⠲⡤⡲⡿⢖⡦⣰⠒⠒⡦⠒⠒⠒⢄⠀
⢸⠀⠀⠈⠀⠀⢾⡇⠀⠀⢠⠔⢲⢮⡾⢶⡶⡖⡮⡞⡀⠀⡡⠦⡄⠀⠈⡆
⢸⠀⠀⠀⠀⣤⣀⣀⡄⠀⡇⠀⢸⢸⡚⢸⡇⢻⣿⣿⡇⠀⡇⠀⢸⠀⠀⡇
⢸⠀⠀⢠⠀⠈⠒⠖⠋⡀⠈⠲⠾⢟⢅⠀⠃⠘⣨⣳⠃⠀⡇⠀⢸⠀⠀⡇
⠸⠤⠤⠼⠑⠤⢤⣤⠤⠚⠢⠤⠤⠴⠓⠯⠤⢭⡖⠻⣤⣤⡇⠀⢸⣤⣤⠇
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢣⣀⠕⠀⠀⠀⠀⠀⠀⠀
ReconFTW | https://github.com/six2dez/reconftw.git | Awesome automatic web vulnerability discovery framework.

Please add / install this awesome automatic web application vulnerability discovery framework in Black Arch Linux.

It performs various vulnerability checks like XSS, Open Redirects, SSRF, CRLF, LFI, SQLi, SSL tests, SSTI, DNS zone transfers, and much more. Along with these, it performs OSINT techniques, directory fuzzing, dorking, ports scanning, screenshots, nuclei scan on your target.

Thanks

**Comment by noraj** [comment]
Please search for existing issue before opening a duplicate: https://github.com/BlackArch/blackarch/issues?q=is%3Aissue+ReconFTW+is%3Aclosed

**Comment by noraj** [comment]
cf. #3603 for the reason.

**Comment by CyberGhazi786** [comment]
Better to close the BlackArch project. You love to deny users' requests. It's very easy to say, "Use Docker Compose," but do you know that Docker Composers lack many of the functions of these frameworks? I am very upset and disappointed by your ignorant comments that you reply against all tools or framework requests on BlackArch Linux platform. I am leaving BlackArch and moving back to kali linux because these people at least satisfy their users' requests. Goodbye. Black Arch is a junk yard of obsolete tools and scripts that no one uses in current times.
BlackArch Linux R.I.P 🫡💐👋🙏♥️👍
