### ISSUE TITLE
Osmedeus | https://github.com/j3ssie/osmedeus.git | Osmedeus Workflow Engine for Offensive Security.

### ISSUE THREAD

**Issue by CyberGhazi786** [BlackArch/blackarch#3626]
**⠀⠀⠀⠀⢀⠠⢂⣍⣡⠒⣄⠢⢅⡂⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⣀⠵⠞⠛⢻⣿⣿⣷⣯⣒⡌⣒⠱⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠐⠁⠀⠀⠀⠀⠛⠿⣿⣿⣿⡷⣌⢣⠖⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⣿⡜⢦⣛⠀⠀⢀⡠⢄⡰⣆⢤⡄⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⠷⣝⠶⣩⠡⣌⡗⢮⣧⣿⣾⣷⣾⣿⣧⢄⠀
⠀⠀⠀⠀⠀⠀⠀⢀⣤⣿⣿⣿⢯⡟⣼⢫⣿⡹⣎⣻⣿⣿⡿⣿⠿⠃⠀⠈⠙⢧
⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⡿⣏⡾⣵⢛⡶⣻⣍⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠈
⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⡿⣝⣞⡳⠀⢸⣽⣳⢧⣿⣿⣿⡛⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣠⣶⣿⣿⣿⣿⣻⡽⡾⠁⠀⠀⢷⣯⢿⣽⣿⣿⣿⣷⡄⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣿⣿⣿⣿⣿⢷⣻⡝⠁⠀⠀⠀⠈⢫⣿⢾⣿⣿⣿⣿⣟⠀⠀⠀⠀⠀
⠀⠀⠀⣰⣿⣿⣿⣿⣟⣿⡟⠀⠀⠀⠀⠀⠀⠀⢻⣿⣾⣿⣿⣿⣿⣆⠀⠀⠀⠀
⠀⢠⣿⣿⣿⣿⣿⣿⣯⠏⠀⢀⣤⣶⣶⣦⣤⡀⠀⢻⣿⣿⣿⣿⣿⣿⣷⡄⠀⠀
⠀⢹⣿⣿⣿⣿⣿⢿⣽⠁⣰⣿⣿⣿⣷⣯⣷⣿⡆⠈⣿⣿⣿⣿⣿⣿⣿⡏⠀⠀
⠀⣾⣿⣿⣿⣿⡿⣿⡇⠀⢿⣿⡿⣿⣿⣿⣿⣿⡗⠀⢸⣿⣿⣿⣿⣿⣿⣷⠀⠀
⣴⣿⣿⣿⣿⣿⣿⣿⣧⠀⠘⢯⣿⢿⣻⣿⣿⠿⠁⠀⣼⣿⣿⣿⣿⣿⣿⣿⣧⠀
⣿⣿⣿⣿⣿⣿⢿⣿⣿⣦⡀⠀⠉⠙⠛⠋⠉⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣽⣿⠀
⠈⣿⣿⣿⣿⣽⣿⣻⣿⢿⣿⣶⣤⣄⣀⣠⣤⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀
⠀⢻⣿⣿⣿⣿⣽⣳⢿⣻⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣻⣿⣿⣿⣿⡟⠀⠀
⠀⢸⣿⡿⣽⣿⣿⣿⣝⡷⣯⢿⣻⢿⣿⣿⣿⣿⣿⢿⣯⣿⣿⣿⣿⣽⣿⡇⠀⠀
⠀⠀⠙⠿⣿⣿⣿⣿⣿⣿⣷⣯⣽⣿⣾⣿⣯⣽⣾⣿⣿⣿⣿⣿⣿⠟⠋⠀⠀⠀
⠀⠀⠀⠀⠈⠛⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠁⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠉⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀

Osmedeus | https://github.com/j3ssie/osmedeus.git | Osmedeus Workflow Engine for Offensive Security.

Please add / install this superb Workflow Engine for Offensive Security.

🔥 What is Osmedeus?

Osmedeus is a Workflow Engine for Offensive Security. It was designed to build a foundation with the capability and flexibility that allows you to build your own reconnaissance system and run it on a large number of targets.

Thanks**

**Comment by noraj** [comment]
Duplicate https://github.com/BlackArch/blackarch/issues/2562
