### ISSUE TITLE
paru outdated in the repository

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3637]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

When I run `sudo pacman -S paru` I get an old version 1.9.3-1 (that is using old OpenSSL version) instead of the version described in its PKGBUILD (1.11.2):
```
sudo pacman -S paru
warning: paru-1.9.3-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (1)     Old Version  New Version  Net Change  Download Size

blackarch/paru  1.9.3-1      1.9.3-1        0.00 MiB       2.31 MiB

Total Download Size:   2.31 MiB
Total Installed Size:  7.28 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
```
The content of paru [PKGBUILD](https://github.com/BlackArch/blackarch/blob/master/packages/paru/PKGBUILD) has:
```
# This file is part of BlackArch Linux ( https://www.blackarch.org/ ).
# See COPYING for license details.
#
# AUR Maintainer: Morgan <morganamilo@archlinux.org>

pkgname=paru
pkgver=1.11.2
pkgrel=1
pkgdesc='Feature packed AUR helper.'
<SNIP>
```

Maybe it could be that despite there is the PKGBUILD with the new version, the new package has not been built and published on BlackArch repo.

Could you please fix it?

### Steps to reproduce

- `sudo pacman -S paru`

**Actual result:**

```
sudo pacman -S paru
warning: paru-1.9.3-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (1)     Old Version  New Version  Net Change  Download Size

blackarch/paru  1.9.3-1      1.9.3-1        0.00 MiB       2.31 MiB
```

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

```
sudo pacman -S paru

resolving dependencies...
looking for conflicting packages...

Package (1)     Old Version  New Version  Net Change  Download Size

blackarch/paru  1.9.3-1      1.11.2-1        X MiB       Y MiB
```

**Comment by noraj** [comment]
It (the PKGBUILD) has been updated 1 month ago (see https://github.com/BlackArch/blackarch/pull/3579), but it seems it was not built or the build has failed. I don't have access to the build pipeline. @noptrix Could you check why it's not deployed?

**Comment by SecT0uch** [comment]
I have the same issue with several packages: `python-pypykatz`  merged 2 months ago and `feroxbuster` 3 weeks ago.

I understand maintenance can be a lot of work, but the community could help if the build pipeline were public. 
Most of us choose (Black)Arch for the release speed and the ability to contribute to the PKGBUILDs.

**Comment by noraj** [comment]
This kind of ideas have been on an internal tracker for some time 
![image](https://user-images.githubusercontent.com/16578570/208691370-5a580d85-d7ef-42c8-a29c-730cd046c1c4.png)

But that would require a lot of effort to deploy and I don't have access to the infrastructure.

**Comment by D3vil0p3r** [comment]
@noptrix @noraj any news on this issue?

**Comment by noraj** [comment]
As I said in my previous comment, I don't have access to the infrastructure like the build pipeline. Come on matrix ask noptrix.

**Comment by ikstream** [comment]
It's currently up-to-date so I'm closing this issue
