### ISSUE TITLE
BlackArch OS - Weird login issue on Firefox when trying to login to OpenAI ChatGPT

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3638]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

On BlackArch, when I try to access to chat.openai.com by Firefox browser, after inserting the correct credential logins, it goes back to login window. It does not happen if another browser (chromium-based) is used, but if I use a desktop client as web wrapper, I have the same behavior I get by Firefox and I'm not able to access to it.

I noted that for some Arch-based distro as Manjaro and Garuda it works, and for other distros as BlackArch, no.

### Steps to reproduce

- Open Firefox
- Visit chat.openai.com
- Try to login with correct credentials

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

After the successful login, the window comes back to the login page.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Login to the chat window.

**Comment by noraj** [comment]
Could be outdated browser, bloated cache, conflicting cookie, your router, your ISP, some browser's plugin, etc. Why would you think it's due to BA outside of "it works on another distro"?

Without detailed technical information we can't investigate anyway.

**Comment by D3vil0p3r** [comment]
> Could be outdated browser, bloated cache, conflicting cookie, your router, your ISP, some browser's plugin, etc. Why would you think it's due to BA outside of "it works on another distro"?
> 
> Without detailed technical information we can't investigate anyway.

Just reported what I met during its day by day usage.

**Comment by noraj** [comment]
I have a BlackArch VM and it's working on it with latest Firefox. It's very unlikely it's caused by BlarchArch but it was just to highlight the issue was totally unactionable without detailed technical details.
