### ISSUE TITLE
blackarch black screen when i try to download

### ISSUE THREAD

**Issue by VenomLightpro** [BlackArch/blackarch#3639]
# bug #
I wanted to install  blackarch and after booting from a USB flash drive after a black screen and that's it. there is nothing more. even logs. 
после того как загружаюсь с  blackarch. черный экран и все. даже логов нету.

# my device
hp pavilion - 15

pls help
пожалуйста помогите

**Comment by noraj** [comment]
Hi, please join our Matrix channel if you want some support: https://matrix.to/#/#BlackArch:matrix.org

Then mention :

- Which ISO did you used?
- How did you flash it to the USB drive?
- BIOS mode: UEFI or legacy?

**Comment by VenomLightpro** [comment]
Hi.I wanted to install blackarch and after booting from a USB flash drive after a black screen and that's it. there is nothing more. even logs. iso - BlackArch Linux 64 bit Netinstall ISO. I tried to flash through dd and through ventoy. bios mod: both uefi and legac

**Comment by VenomLightpro** [comment]
Hi.I wanted to install blackarch and after booting from a USB flash drive after a black screen and that's it. there is nothing more. even logs. iso - BlackArch Linux 64 bit Netinstall ISO. I tried to flash through dd and through ventoy. bios mod: both uefi and legac
