### ISSUE TITLE
black instalation screen

### ISSUE THREAD

**Issue by VenomLightpro** [BlackArch/blackarch#3643]
### Bug description

Hi.I wanted to install blackarch and after booting from a USB flash drive after a black screen and that's it. there is nothing more. even logs. iso - BlackArch Linux 64 bit Netinstall ISO. I tried to flash through dd and through ventoy. bios mod: both uefi and legac

### Steps to reproduce

- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Info for developers

**Device:** hp-pavilion 15
**GNU/Linux distribution:** garuda linux

### Link to debug log

nope

**Comment by noraj** [comment]
As asked on #3639, please join Matrix if you want some support (https://matrix.to/#/#BlackArch:matrix.org. The issue tracker is for issues and feature requests.

**Comment by VenomLightpro** [comment]
what distro does it support?

**Comment by noraj** [comment]
BlackArch Linux and BlackArch repository on top or ArchLinux
