### ISSUE TITLE
Replace rtl8814au-aircrack-dkms with rtl8814au-dkms-git

### ISSUE THREAD

**Issue by tategotoazarasi** [BlackArch/blackarch#3646]
- **Name**: rtl8814au-dkms-git
- **Source URL**: https://aur.archlinux.org/packages/rtl8814au-dkms-git
- **Description**: The package rtl8814au-aircrack-dkms in BlackArch repo is dropped from AUR (https://aur.archlinux.org/packages/rtl8814au-aircrack-dkms-git), use rtl8814au-dkms-git instead.

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4243
