### ISSUE TITLE
[QUESTION] - How packages related to BA groups are managed by PKGBUILD?

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3648]
Type: Question

## Question

Hello, I have a curiosity about BlackArch groups (like `blackarch-cracker`, `blackarch-scanner`, and so on). Since the related PKGBUILD files are not shown publicly in this repository, I was curious to understand how these groups/packages manage the installation of tool packages inside it.

For example, `blackarch-cracker` package has, let's say, 100 tools, so 100 packages. How does PKGBUILD file manage the installation of these 100 packages? By running `pacman` in `package()` function or by adding these 100 packages in `depends` variable?

**Comment by noraj** [comment]
Each tool PKGBUILD defines the [groups](https://wiki.archlinux.org/title/PKGBUILD#groups) it is in.

E.g. `haiti` is in `blackarch-crypto`. Also, all tools are in the global `blackarch` groups.

https://github.com/BlackArch/blackarch/blob/e53bde280e2f7b32f919b703d9bb90d8809809c8/packages/haiti/PKGBUILD#L8

Only authorized groups are accepted, the list is here: https://github.com/BlackArch/blackarch/blob/master/lists/groups

Anything else rely on the [default pacman behavior](https://wiki.archlinux.org/title/Meta_package_and_package_group).

**Comment by D3vil0p3r** [comment]
Thank you @noraj. So groups are not managed by PKGBUILD. Technically, a group, like `blackarch-crypto`, works in the following manner:

Given a specific repository, like BlackArch, when a user executes `sudo pacman -S blackarch-crypto`, pacman will go through all the packages of BlackArch repository and go to retrieve all those tools that contain `blackarch-crypto` in `groups` variable. It means that you can assign packages to a group only if you have these packages in your repository (i.e., BlackArch in our example). Groups cannot be used for tools of other repositories since you don't control them, is it correct?

**Comment by noraj** [comment]
Groups are defined in PKGBUILD, PKGBUILD are built into package archives, packages archives are made available on a repository. So not you can't control groups outside the repository you control.

**Comment by D3vil0p3r** [comment]
Yes, I understand, I wrote the statement `So groups are not managed by PKGBUILD` in a wrong manner, I meant that for creating a group you don't need to create a dedicated PKGBUILD for a group (as occurs for packages) because "group" concept is like an abstraction. Btw yes, you answered well to my question. Thank you again.
