### ISSUE TITLE
[BUG] Impacket mssqlclient.py [-] [('SSL routines', '', 'internal error')]

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3650]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

When `mssqlclient.py` tool from impacket is used, the following error is returned:
```
Impacket v0.9.24 - Copyright 2021 SecureAuth Corporation

[*] Encryption required, switching to TLS
[-] [('SSL routines', '', 'internal error')]
```
This issue was related to a wrong configuration in `/usr/lib/python3.10/site-packages/impacket/tds.py` that has been solved in the most recent versions of Impacket. The issue has been shown here: https://github.com/fortra/impacket/issues/856#issuecomment-729880208

The Impacket version in BlackArch has this bug and does not allow to use mssqlclient.py tool. By upgrading Impacket to the latest version will solve the issue.

### Steps to reproduce

- Build a machine with MS SQL server
- From the client, run mssqlclient.py reporting:'password'@10.10.10.125 -windows-auth

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
```
Impacket v0.9.24 - Copyright 2021 SecureAuth Corporation

[*] Encryption required, switching to TLS
[-] [('SSL routines', '', 'internal error')]
```

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
```
Impacket v0.10.1.dev1+20221214.172823.8799a1a2 - Copyright 2022 Fortra

[*] Encryption required, switching to TLS
[*] ENVCHANGE(DATABASE): Old Value: master, New Value: volume
[*] ENVCHANGE(LANGUAGE): Old Value: , New Value: us_english
[*] ENVCHANGE(PACKETSIZE): Old Value: 4096, New Value: 16192
[*] INFO(QUERIER): Line 1: Changed database context to 'volume'.
[*] INFO(QUERIER): Line 1: Changed language setting to us_english.
[*] ACK: Result: 1 - Microsoft SQL Server (140 3232) 
[!] Press help for extra shell commands
SQL> 
```
While getting impacket from git, remember to run all of the following commands:
```
git clone https://github.com/fortra/impacket
python3 -m pip install impacket
python3 -m pip install . 
```
The last one command is important to run for setting `tds.py` file in the correct manner.

**Comment by noraj** [comment]
impacket is an AL package https://archlinux.org/packages/community/any/impacket/. Open an issue on AL bugtracker.

PS : the package is currently flagged as out of date.

**Comment by D3vil0p3r** [comment]
> impacket is an AL package https://archlinux.org/packages/community/any/impacket/. Open an issue on AL bugtracker.
> 
> PS : the package is currently flagged as out of date.

Thank you @noraj I will do it now. I opened the issue ticket here because I see impacket coming from "blackarch" repo as the following image shows:
![image](https://user-images.githubusercontent.com/83867734/210114638-f7614d96-4322-4315-b9be-3b22824e2146.png)

**Comment by dualfade** [comment]
I do not know if this helps, but since python 3.10.x; I have started running impacket scripts the following way. I have also download the latest repo from github and stuffed it in /opt/impacket.

[0] % sudo -E pyenv exec python --version
Python 3.9.7

Example:
sudo -E pyenv exec python /opt/impacket/examples/smbserver.py -smb2support Volume . -username dualfade -password dualfade

I know this is not a solution, but it is a working fix until things work right with the latest python release. At least for me at this point. 

Cheers, 
------- Original Message -------

**Comment by D3vil0p3r** [comment]
@dualfade thank you for your answer. I have already a solution for `mssqlclient.py` error, that is solved by upgrading the `impacket` package. Just now I submitted a bug report to ArchLinux related package hoping that they will update it.

What I don't understand is: why, when I run `sudo pacman -S impacket`, I get `blackarch/impacket` as shown in the image above.

**Comment by dualfade** [comment]
Huh. That is a good question. I see the same, but that package is not in the repo. 

I will look around too and see if I can find where that is coming from. 

be good.
~!>D




------- Original Message -------

**Comment by noraj** [comment]
> > impacket is an AL package https://archlinux.org/packages/community/any/impacket/. Open an issue on AL bugtracker.
> > PS : the package is currently flagged as out of date.
> 
> Thank you @noraj I will do it now. I opened the issue ticket here because I see impacket coming from "blackarch" repo as the following image shows: ![image](https://user-images.githubusercontent.com/83867734/210114638-f7614d96-4322-4315-b9be-3b22824e2146.png)

It's an empty wrapper for AL package.

![image](https://user-images.githubusercontent.com/16578570/210116802-1564b71e-c699-4c8a-a83a-01a5876af549.png)

You can find it out easily:

- `pacman -Ss package` and see it's duplicated
- search in https://github.com/BlackArch/blackarch/tree/master/packages and see it's not there

**Comment by D3vil0p3r** [comment]
FYI: https://bugs.archlinux.org/task/76969
