### ISSUE TITLE
QT3 - Missing source files qt-copy-kde-patches.tar.bz2 and qt-patches.tar.bz2

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3660]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

[qt3](https://github.com/BlackArch/blackarch/tree/master/packages/qt3) folder does not have two source files specified in its [PKGBUILD](https://github.com/BlackArch/blackarch/blob/master/packages/qt3/PKGBUILD). In particular:
* qt-copy-kde-patches.tar.bz2
* qt-patches.tar.bz2

For this reason, if you run `makepkg -si`, you will get the following error:
```
==> ERROR: qt-copy-kde-patches.tar.bz2 was not found in the build directory and is not a URL.
```
while, `PKGBUILD` has these files as source:
```
<SNIP>
source=("https://download.qt.io/archive/qt/3/qt-x11-free-$pkgver.tar.gz"
        'qt3-png15.patch' 'qt-copy-kde-patches.tar.bz2' 'qt-patches.tar.bz2'
        'eastern_asian_languagues.diff' 'qt-odbc.patch' 'gcc-4.6.patch'
        'qt-x11-free-3.3.5-makelibshared.patch')
<SNIP>
```

**Comment by noraj** [comment]
Then the question is, is there still a tool that requires qt3?

**Comment by D3vil0p3r** [comment]
> Then the question is, is there still a tool that requires qt3?

Currently, the BA package requiring qt3 are [pyqt3](https://github.com/BlackArch/blackarch/blob/master/packages/pyqt3) and [qscintilla-qt3](https://github.com/BlackArch/blackarch/blob/master/packages/qscintilla-qt3)

BA tools depending on pyqt3 are:
* [faradaysec](https://github.com/BlackArch/blackarch/tree/master/packages/faradaysec)
* [gerix-wifi-cracker](https://github.com/BlackArch/blackarch/blob/master/packages/gerix-wifi-cracker)
* [inguma](https://github.com/BlackArch/blackarch/tree/master/packages/inguma)

**Comment by noraj** [comment]
> Currently, the BA package requiring qt3 are [pyqt3](https://github.com/BlackArch/blackarch/blob/master/packages/pyqt3) and [qscintilla-qt3](https://github.com/BlackArch/blackarch/blob/master/packages/qscintilla-qt3)

And the only package requiring qscintilla-qt is pyqt3

**Comment by D3vil0p3r** [comment]
> > Currently, the BA package requiring qt3 are [pyqt3](https://github.com/BlackArch/blackarch/blob/master/packages/pyqt3) and [qscintilla-qt3](https://github.com/BlackArch/blackarch/blob/master/packages/qscintilla-qt3)
> 
> And the only package requiring qscintilla-qt is pyqt3

Yes.

**Comment by noraj** [comment]
I see no `pyqt` in https://github.com/infobyte/faraday/blob/master/requirements.txt and it seems it was used only for the Faraday IDE anyway. We just need the webui so I think we can remove pyqt3 dependency and if it is still bugging then use `--gui=nogui` option cf. https://github.com/infobyte/faraday/issues/58#issuecomment-159742224

**Comment by noraj** [comment]
gerix-wifi-cracker see #3572

**Comment by noraj** [comment]
inguma is abandoned since 2008 and of course still using python that was dropped from AL repo

**Comment by noraj** [comment]
so `qt3`, [pyqt3](https://github.com/BlackArch/blackarch/blob/master/packages/pyqt3) and [qscintilla-qt3](https://github.com/BlackArch/blackarch/blob/master/packages/qscintilla-qt3) can be dropped from our repos since they are no more required or required only by deprecated tools.

**Comment by D3vil0p3r** [comment]
> so `qt3`, [pyqt3](https://github.com/BlackArch/blackarch/blob/master/packages/pyqt3) and [qscintilla-qt3](https://github.com/BlackArch/blackarch/blob/master/packages/qscintilla-qt3) can be dropped from our repos since they are no more required or required only by deprecated tools.

It is a good news for me 👯 !

**Comment by D3vil0p3r** [comment]
Fixed qt3: https://github.com/BlackArch/blackarch/pull/4244 . Probably, the reason those missing patch archives were missing was due to `*.bz2` entry inside `.gitignore`. It needs to be managed.

**Comment by noraj** [comment]
The previous discussion was that it was not needed anymore…

**Comment by D3vil0p3r** [comment]
Should we add faradaysec gerix-wifi-cracker inguma qscintilla-qt3 pyqt3?

**Comment by noraj** [comment]
faraday does not requires qt3 or pyqt3 anymore, gerix-wifi-cracker is no longer existing and rely on python2 anyway, inguma relies on python, is abandoned and obsolete and redundant. All this should be dropped.

**Comment by noraj** [comment]
all those were already listed here: https://github.com/BlackArch/blackarch/blob/master/lists/broken

**Comment by noraj** [comment]
However, @D3vil0p3r you could try to build faraday without qt3 and do some cleanup in its dependencies.

**Comment by D3vil0p3r** [comment]
ok @noraj . If I see good results, I will submit the change

**Comment by D3vil0p3r** [comment]
https://github.com/infobyte/faraday/blob/master/CHANGELOG/footer.md

![image](https://github.com/user-attachments/assets/3fbf679a-9d5e-45b3-ad49-298a98a9cc33)
