### ISSUE TITLE
Shells by @4ndr34z

### ISSUE THREAD

**Issue by dualfade** [BlackArch/blackarch#3687]
- **Shells**:
- **https://github.com/4ndr34z/shells**:
- **A script for generating common revshells fast and easy.
Especially nice when in need of PowerShell and Python revshells, which can be a PITA getting correctly formatted.**:

**Comment by D3vil0p3r** [comment]
[Implemented](https://github.com/BlackArch/blackarch/blob/master/packages/shellz/PKGBUILD). Close please

**Comment by noraj** [comment]
Fixed by #3689
