### ISSUE TITLE
Dissect

### ISSUE THREAD

**Issue by Schamper** [BlackArch/blackarch#3688]
- **Name**: Dissect
- **Source URL**: https://github.com/fox-it/dissect
- **Description**: Dissect is a pure Python framework consisting of multiple libraries and tools to interact with things like disk images and virtual machine disks. More information available at https://docs.dissect.tools/en/latest/.

**Comment by D3vil0p3r** [comment]
Huge effort. All [these](https://github.com/fox-it/dissect?tab=readme-ov-file#projects) need to be package separetely.

**Comment by noraj** [comment]
> Huge effort.

Unless we use a virtual env. That's what we generally do for dependency hell liek this.

**Comment by D3vil0p3r** [comment]
Huge work but worth. Here the PR: https://github.com/BlackArch/blackarch/pull/4361
