### ISSUE TITLE
burpsuite taking to long to download

### ISSUE THREAD

**Issue by DF001** [BlackArch/blackarch#3690]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

burpsuite taking way to long to download. It should not take this long as other software downloads at the max speed of my internet and never at this speed.

### Steps to reproduce

- run sudo pacman -S burpsuite
- download takes to long at 100Kib
- All other programs install at max 14Mib a sec

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
burpsuite should be downloading much fast and not at a snail pace 
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Download much faster
### Screenshots

![Burp issue](https://user-images.githubusercontent.com/13202791/213888222-69d2c8bb-a11b-4cbe-ac8a-c848b839dbc9.png)

### Info for developers

tested on BA and AthenaOS. Only way on AthenaOS to fix it was to update the mirrors.

**Comment by noraj** [comment]
Speed depends on the mirror speed limit. If your mirror is slow, use another one. You can use [reflector](https://wiki.archlinux.org/title/Reflector) as well.

**Comment by DF001** [comment]
can you please check what is going on with the mirror or is that not possible ??

**Comment by noraj** [comment]
You didn't even mention which mirror you are using.

**Comment by DF001** [comment]
> You didn't even mention which mirror you are using.

how can i figure that out ?

**Comment by noraj** [comment]
`grep -v '#' /etc/pacman.d/blackarch-mirrorlist`

**Comment by noraj** [comment]
Read [how mirrors work](https://wiki.archlinux.org/title/Mirrors) and then modify `/etc/pacman.d/blackarch-mirrorlist` manually or use reflector.

**Comment by DF001** [comment]
> `grep -v '#' /etc/pacman.d/blackarch-mirrorlist`

Server = https://ftp.halifax.rwth-aachen.de/blackarch/$repo/os/$arch

**Comment by noraj** [comment]
To ask for support please join us on Matrix or reddit. This issue tracker is for bugs and feature requests.
