### ISSUE TITLE
sqlmap Outdated. 

### ISSUE THREAD

**Issue by F0rkEU** [BlackArch/blackarch#3694]
sqlmap is outdated that causes the script not to work properly.

You can see the current version of sqlmap. It's 1.6.12-1. 
![image](https://user-images.githubusercontent.com/121362809/213918026-c6f242b3-49a2-4e09-b359-c11e8b938e66.png)

There is a new stable version out: https://github.com/sqlmapproject/sqlmap/releases/tag/1.7

Please update the Repo.

**Comment by noraj** [comment]
sqlmap is provided by AL https://archlinux.org/packages/community/any/sqlmap/
