### ISSUE TITLE
Remove/rename a tool called snitch

### ISSUE THREAD

**Issue by tocic** [BlackArch/blackarch#3708]
Please remove/rename a tool called `snitch` since [the upstream URL](http://ntsecurity.nu/toolbox/snitch) doesn't exist anymore. It redirects to a tool collection which doesn't have a similar tool AFAIK. According to the Wayback Machine, it was designed for Windows 95 / 98 / ME / NT 4.0 and has now been removed.

The actual problem is that its name clashes with a name of [a different package from AUR](https://aur.archlinux.org/packages/snitch) which causes some inter-repository crawling issues.

**Comment by tocic** [comment]
@noptrix any updates on this?

**Comment by tocic** [comment]
@D3vil0p3r Hello. Could you please look at this?

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/3984

**Comment by D3vil0p3r** [comment]
@noraj look the linked PR above. Should we close this issue?

**Comment by tocic** [comment]
Are there any "discussion thread about this or better via matrix"?

**Comment by noraj** [comment]
> @noraj look the linked PR above. Should we close this issue?

Yes.
