### ISSUE TITLE
Update flare-floss

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#3715]

**Comment by sven-eliasen** [comment]
The tool seems pretty updated to me : 
![image](https://github.com/BlackArch/blackarch/assets/37241392/0ae59da4-3fcc-4cab-9ffe-72573ac6dbe6)
![image](https://github.com/BlackArch/blackarch/assets/37241392/d1808ba6-659a-40c1-8fbd-32f6f8c4a059)

But why isn't it updated on the website ?
![image](https://github.com/BlackArch/blackarch/assets/37241392/f846806a-e7b6-46c3-9fa8-37b734beb18e)

**Comment by D3vil0p3r** [comment]
To be closed
