### ISSUE TITLE
Problem install BlackArch Linux 64 bit Full ISO 2021.09.01

### ISSUE THREAD

**Issue by Stocker918** [BlackArch/blackarch#3723]
https://blackarch.org/blackarch/torrent/blackarch-linux-full-2021.09.01-x86_64.iso.torrent

Hello. I use 2 new original flash cards (Kingston 64GB and SanDisk 64GB). Installing on new SSD (Smartbuy 128GB Splash (the disk is completely free)). I installed Kali Linux on this SSD, and everything install/works fine. An error appears during installation:
https://i.imgur.com/6yAv1vp.jpeg
https://i.imgur.com/JxV2oSD.jpeg

I used Google to search for this error. They write that the name of the flash card from which the installation is performed may be incorrect. But I have the correct name of the flash card (BLACKARCH_202108) and an error still occurs.

**Comment by noraj** [comment]
Known issue https://github.com/BlackArch/blackarch-iso/issues/41, the ISO are outdated, new ones are being built.
