### ISSUE TITLE
linux-headers used as dependency of some tools

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3744]
Type: Question

## Question

I'm using an Arch Linux system with Linux Zen kernel and I was seeing that some BA tools have `linux-headers` (related to the "vanilla" linux kernel) as dependency. Is it correct that `linux` or `linux-headers` are used as dependencies on these tools despite they can be used on other kinds of kernel? Or is it better they are removed as depenencies since the packages that use `linux-headers` as dependency don't have `linux` as dependency, with the risk to create some conflict if the user has another kernel pkg installed?

** Tools using "linux-headers" as dependency **
arptools
batman-adv
binflow
chipsec
eresi
libpfring
libpjf
pcileech
pfring-dkms
python-pysctp
radare2-keystone
scamper
sylkie
tracedump
tyton
vpnpivot
wolpertinger

** Tools using "linux" as dependency **
backports-patched

**Comment by noraj** [comment]
There is no kernel or kernel header group or meta package that could let the user choose it's own kernel.
Among all those tools I don't know if some need the headers to build a module or if they just need the headers to find some data in the code.

Maybe a workaround would be to replace `linux-headers` dependency to a list of all headers as optional dependencies.

```diff
-depends=('linux-headers')
+optdepends('linux-headers' 'linux-lts-headers' 'linux-hardened-headers' 'linux-rt-headers' 'linux-rt-lts-headers' 'linux-zen-headers')
```

**Comment by D3vil0p3r** [comment]
What I could do is to build each one of those packages without `linux-headers` dependency and check if the build fails or not. If I don't get errors, I can use `optdepends` as you suggested.

**Comment by ikstream** [comment]
As we ship `linux` by default and the diifferent header don't conflict, I would say, we keep the `linux-headers` dependency and add the other headers as dependency. That way, we avoid issues for the regular users and provide an option for user with different kernel builds. Only a build check might not be enough to figure out if the tool works properly without them imo.

Have you experienced any issues with the requirements so far @D3vil0p3r ?

**Comment by D3vil0p3r** [comment]
> As we ship linux by default and the diifferent header don't conflict, I would say, we keep the linux-headers dependency and add the other headers as dependency. 
>
Think that BA is shipped also [on top of Arch](https://www.blackarch.org/downloads.html#install-repo) so users could have different kernel and headers pkgs from vanilla. I like noraj proposal.

Btw @ikstream @noraj can we re-discuss this topic so we can close this?
