### ISSUE TITLE
[Tool Request] wmbus

### ISSUE THREAD

**Issue by utenus** [BlackArch/blackarch#3760]
- **Name**:
rtl-wmbus
wmbusmeters

- **Source URL**:
https://github.com/xaelsouth/rtl-wmbus
https://github.com/wmbusmeters/wmbusmeters

- **Description**:
Useful when trying to read the mbus radio protocol, e.g. from a water meter.

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4247
https://github.com/BlackArch/blackarch/pull/4249
