### ISSUE TITLE
[Tool Request] SDR tools

### ISSUE THREAD

**Issue by utenus** [BlackArch/blackarch#3762]
- **Name**:

SDRPlusPlus
sdrangel
inspectrum
maia-sdr
shinysdr
srsRAN_4G
Salamandra
hacktv
openwebrx
sdrtrunk
FISSURE
qradiolink
rtl_433
pagermon
qFlipper
effex
gqrx-scanner

- **Source URL**:

https://github.com/AlexandreRouma/SDRPlusPlus
https://github.com/f4exb/sdrangel
https://github.com/miek/inspectrum
https://github.com/maia-sdr/maia-sdr
https://github.com/kpreid/shinysdr
https://github.com/srsran/srsRAN_4G
https://github.com/eldraco/Salamandra
https://github.com/fsphil/hacktv
https://github.com/jketterl/openwebrx
https://github.com/DSheirer/sdrtrunk
https://github.com/ainfosec/FISSURE
https://codeberg.org/qradiolink/qradiolink
https://github.com/merbanan/rtl_433/
https://github.com/pagermon/pagermon
https://github.com/flipperdevices/qFlipper
https://github.com/evanmayer/effex
https://github.com/neural75/gqrx-scanner

- **Description**:

I created one issue for many tools so as not to make a mess. Recently, I've been trying to work a lot with HackRF, LimeSDR, Flipper Zero and maybe soon with Pluto+, so it would be very useful to expand the collection of SDR tools and I'm sure I'm not the only one who would be happy.

**Comment by noraj** [comment]
Good idea, but actually an issue per tool is better. Because it's unpractical to have a list to track which tool was added and apply the correct labels to the issue or to assign someone working on it. Plus it will mix up all comments of all tools.

**Comment by noraj** [comment]
Could you re-open an issue per tool please? Also tell me on which ones you are willing to work?

**Comment by utenus** [comment]
Sure, no problem, I'm reopening per tool.
