### ISSUE TITLE
[Tool Request] qradiolink

### ISSUE THREAD

**Issue by utenus** [BlackArch/blackarch#3781]
- **Name**: qradiolink
- **Source URL**: https://codeberg.org/qradiolink/qradiolink
- **Description**: Similar to SDR Plus Plus.

**Comment by D3vil0p3r** [comment]
This tool uses GNURadio old libs and patching those ones starts to be a mess because some header files have been removed from latest versions of GNURadio https://github.com/qradiolink/qradiolink/issues/127

Due to this, I would close this request.

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4367
