### ISSUE TITLE
[Tool Request] openwebrx 

### ISSUE THREAD

**Issue by utenus** [BlackArch/blackarch#3784]
- **Name**: openwebrx
- **Source URL**: https://github.com/jketterl/openwebrx
- **Description**:
Very nice for simple SDR analysis. It similar to SDR Plus Plus a bit, only it has a different interface and other functions. It's quite fresh and less stable than SDR# but nice for monitoring.

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4378
