### ISSUE TITLE
SDR#

### ISSUE THREAD

**Issue by utenus** [BlackArch/blackarch#3789]
- **Name**: SDR#

- **Source URL**:
https://airspy.com/download/
https://www.rtl-sdr.com/sdrsharp-plugins/

- **Description**:
SDR# is the most popular SDR tool, as you can easily see on YouTube.
The program itself is free, but the problem is that it is only available for Windows.
Maybe somehow using Wine we could run it on BlackArch because it's a very important tool in terms of SDR along with add-ons.

https://www.rtl-sdr.com/rtl-sdr-quick-start-guide/  - how to install SDR# on Windows

**Comment by D3vil0p3r** [comment]
Airspy: https://archlinux.org/packages/extra/x86_64/airspy/

https://github.com/BlackArch/blackarch/pull/4261
