### ISSUE TITLE
[Tool Request] falcon

### ISSUE THREAD

**Issue by utenus** [BlackArch/blackarch#3802]
- **Name**: falcon
- **Source URL**: https://github.com/falkenber9/falcon
- **Description**:
Useful when testing LTE networks.

**Comment by D3vil0p3r** [comment]
I suggest to close this ticket. `falcon` last commit is 4 years ago and the maintainer has last activity on GitHub on 2021.

**Comment by noraj** [comment]
Yeah unless it comes with a PR, it's useless to keep it open.
