### ISSUE TITLE
dsd-fme

### ISSUE THREAD

**Issue by utenus** [BlackArch/blackarch#3806]
- **Name**: dsd-fme
- **Source URL**: https://github.com/lwvmobile/dsd-fme
- **Description**:
For voice decoding during SDR analysis.

**Comment by markcarter00** [comment]
hello my dsd-fme rc 4 not working and it wood be nice if you can put  auto on the bp or on all the Forcing Key Priority just asking if you can it wood be the best dsd i ever add if you can do that and add tetra as well thank mark

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4265
