### ISSUE TITLE
[Tool Request] dspectrumgui

### ISSUE THREAD

**Issue by utenus** [BlackArch/blackarch#3807]
- **Name**: dspectrumgui
- **Source URL**: https://github.com/tresacton/dspectrumgui
- **Description**:
Nice for backward SDR analysis.

**Comment by D3vil0p3r** [comment]
The tool seems abandoned. Furthermore it gem libs (like `untaint`) that are deprecated since Ruby 3.0 so the build fails. Please close it.

**Comment by noraj** [comment]
I one is interested, one should try a dockerfile with an old ruby.
