### ISSUE TITLE
GooFuzz

### ISSUE THREAD

**Issue by m3n0sd0n4ld** [BlackArch/blackarch#3811]
- **Name**: GooFuzz
- **Source URL**: https://github.com/m3n0sd0n4ld/GooFuzz
- **Description**: GooFuzz is a tool to perform fuzzing with an OSINT approach, managing to enumerate directories, files, subdomains or parameters without leaving evidence on the target's server and by means of advanced Google searches (Google Dorking).

**Comment by D3vil0p3r** [comment]
Tool already submitted. @noraj can you close this?

**Comment by m3n0sd0n4ld** [comment]
Sorry, I didn't know I had to close it.

Thank you again for including the tool :D

Take care!
