### ISSUE TITLE
DefectDojo Tool Request

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3812]
- **Name**: DefectDojo
- **Source URL**: https://github.com/DefectDojo/django-DefectDojo
- **Description**: security orchestration and vulnerability management platform. DefectDojo allows you to manage your application security program, maintain product and application information, triage vulnerabilities and push findings to systems like JIRA and Slack. DefectDojo enriches and refines vulnerability data using a number of heuristic algorithms that improve with the more you use the platform.

It could be very useful. I was looking it on Kali Linux but I see that on the original GitHub project page, it runs by Docker container, instead on Kali no (probably because on Kali the pkg has been created by a deprecated method: [setup/README.md](https://github.com/DefectDojo/django-DefectDojo/blob/master/setup/README.md))

What could be the best and the smartest way for creating a BlackArch package for this kind of tool?

**Comment by ikstream** [comment]
I don't think it would be useful to create a package for it. As it is available as a container image, which is the recommended by them. 
While it is very useful for penetration tests, I think it's better suited for a server and not a pentest-box.

**Comment by D3vil0p3r** [comment]
> I don't think it would be useful to create a package for it. As it is available as a container image, which is the recommended by them. While it is very useful for penetration tests, I think it's better suited for a server and not a pentest-box.

I saw that Kali created a [package](https://gitlab.com/kalilinux/packages/defectdojo) for it (by using docker elements), and I was wondering if there was some PKGBUILD template for creating a package that deploys DefectDojo Docker container at the same manner for BlackArch environment.

**Comment by ikstream** [comment]
Not yet. I am not sure if we want to go that direction and deploy applications in container on a user's system, as it is a far reaching decision. E.g. the packages would need to be genetic enough to allow a user to use Podman or docker with their own configuration.
These two are conflicting packages.

**Comment by D3vil0p3r** [comment]
Podman and docker are not conflicting packages. I use both of them for different purposes. About the preference of using podman or docker by the user, idk if it can be managed at PKGBUILD or post_install level.

**Comment by ikstream** [comment]
You are totally right, it's podman-docker, thats conflicting :D

**Comment by noraj** [comment]
Those kinds of web application platforms are more intended for teams and often hosted on servers not on individual pentester laptop.

- I don't really see the interest to package such web application in BA in the first place
- Most of the time they will be very complex to package and will require a manual database setup and the dependency management will be a mess
- When the platform is already packaged as several containers with docker-compose, there is not much added value to make a PKGBUILD out of it

I think it will be a pain and very time-consuming to package and maintain while few people will use it and won't add much ease compared to the usage of docker-compsoe directly.

**Comment by ikstream** [comment]
For reference the link: BlackArch/blackarch-pkgbuilds#21
