### ISSUE TITLE
Error with tools xgps and xgpsspeed 

### ISSUE THREAD

**Issue by CamoCatX** [BlackArch/blackarch#3837]
- [ ] I have searched open and closed issues for duplicates
- [ X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

When I tried to install the drone package on arch with Black Arch on top of it, I could not get the tools in the package to work.

### Steps to reproduce

- Download Arch Linux 
-  Set up the desktop environment ( I used DeepIn but it probably does not make a difference) 
- Download BlackArch on top according to the PDF on the website.
- Download the drone package
- Run the tools xgps or xgpsspeed (it does not matter)

_**After receiving first error I installed pip** ( sudo pacman -S python2-pip and sudo pacman -S python-pip) **and pycairo** (pip install pycairo).**This fixed the missing library issue**_

### The Bug
After reproducing the following steps, you should be greeted with this same error: 
`Traceback (most recent call last): 
  File "/usr/bin/xgpsspeed", line 36, in <module>
      gi.require_version('Gtk',  '3.0') 
      ^^^^^^^^^^^
AttributeError: module 'gi' has no attribute 'require_version'`

### Expected result:
For it to work

**Comment by ikstream** [comment]
I had finally time to look at your issue. Unfortunately, neither `xgps` nor `xpsspeed` is maintained by us, but by archlinux. 
They are both part of the `gpsd` package. It comes with a set of optional dependencies, which includes `python-cairo` and `python-gobject` (which should fix your issues). You might need to install all these optional dependencies. You can check them by running `pacman -Si gpsd`.
