### ISSUE TITLE
[Tool Request]: emba

### ISSUE THREAD

**Issue by utenus** [BlackArch/blackarch#3843]
- **Name**: emba
- **Source URL**: https://github.com/e-m-b-a/emba
- **Description**: Useful for security analysis of embedded solutions.

**Comment by D3vil0p3r** [comment]
https://github.com/e-m-b-a/emba/issues/1384

**Comment by D3vil0p3r** [comment]
According to the mentioned issue ticket, `emba` is much more suitable to be used as container instead to distributed as a package, mainly because the source scripts strongly rely on Debian-based systems, and also for the huge number of dependencies to retrieve.

**Comment by noraj** [comment]
Until we offer docker/podman packages.
