### ISSUE TITLE
How BlackArch packages are signed?

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3848]
## Question

I was looking the [tests.yml](https://github.com/BlackArch/blackarch/blob/master/.github/workflows/tests.yml) in GitHub Actions that build the packages of BlackArch in this repo (or at least, the ones that are changed with respect to the last commit) and then performs a package check.

On the step of building package, I see it leverages on the [travis/Dockerfile](https://github.com/BlackArch/blackarch/blob/master/travis/Dockerfile) that runs `makepkg -s -f --noconfirm --needed --noprogressbar` and not `--sign` argument is given.

It means that the BlackArch packages are not signed? If they are signed, it means that they are signed manually one by one? If they are not, is it not a risk for the integrity of the packages?

Thanks

**Comment by ikstream** [comment]
The packages are only build on github as a check. The actual release builds are done on our own server where they are signed as well.

**Comment by D3vil0p3r** [comment]
> The packages are only build on github as a check. The actual release builds are done on our own server where they are signed as well.

Are they signed one by one by the maintainers or in an automated way?
