### ISSUE TITLE
Desktop error and some other firmware modules are missing for dell Inspiron 1525

### ISSUE THREAD

**Issue by xiv3r** [BlackArch/blackarch#3858]

**Comment by noraj** [comment]
It will require more information than that to be able to identify the issue.

**Comment by ikstream** [comment]
If you provide further information, please feel free to reopen this issue.

Please include all relevant info related to:
- What kind of error
- full error output (If it's longer, please use a pastebin or similar)
- what are you trying to do
- what is the expected output
- what have you tried so far
