### ISSUE TITLE
pwntools is creating conflicting errors due to python-pwntools

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3859]
BlackArch repo contains `pwntools` but Arch Linux as [python-pwntools](https://archlinux.org/packages/extra/any/python-pwntools/) package in Extra repository that is used as dependencies in several infosec packages and this creates conflicts with `pwntools`.

Since `pwntools` and `python-pwntools` come from the same source, could be suitable to delete `pwntools` from BlackArch repo?

**Comment by noraj** [comment]
For now `sudo pacman -Syu --overwrite='/usr/lib/python3.11/site-packages/pwnlib/*' --overwrite='/usr/lib/python3.11/site-packages/pwntools-4.10.0-py3.11.egg-info/*' --overwrite='/usr/lib/python3.11/site-packages/tests/*
' --overwrite='/usr/lib/python3.11/site-packages/pwn/*'` is required to upgrade if one has a tool requiring pwntools. After the upgrade: `sudo pacman -Rns pwntools`.

**Comment by noraj** [comment]
#3868 was handled, this issue can be closed?

**Comment by D3vil0p3r** [comment]
> #3868 was handled, this issue can be closed?

Yes. Closed.
