### ISSUE TITLE
Not available BlackArch mirror to probably remove

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3860]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

The mirror `http://blackarch.pi3rrot.net/blackarch/blackarch/os/x86_64` is not available anymore. It should be removed from `blackarch-mirrorlist` file package.

### Steps to reproduce

- Put `http://blackarch.pi3rrot.net/blackarch/blackarch/os/x86_64` as first server of `blackarch-mirrorlist` file
- Run `sudo pacman -Syyu`

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
```
error: GPGME error: No data
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))
```

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Correct repository synchronization.

**Comment by PardesiCat** [comment]
haha we both came  same time   cheers bro

here i made complete list of   unavailable mirrors list 

https://github.com/BlackArch/blackarch/issues/3861

BA team look here
