### ISSUE TITLE
unavailable mirror

### ISSUE THREAD

**Issue by PardesiCat** [BlackArch/blackarch#3861]
Type: unavailable mirror

## Mirror no longer working

**1.**  as i reported here  https://github.com/BlackArch/blackarch/issues/3832,   you guys forgot to remove the **fosshost mirror of USA**  (2nd mirror under USA)
and  1 & 3   https://blackarch.pr0s3c.nl/blackarch/   also  not hosting anymore

**2.**   now under FRANCE  number 2 mirror is redirecting to other site (no longer available)
 
  http://blackarch.pi3rrot.net/blackarch/   

![Screenshot from 2023-06-20 02-11-40](https://github.com/BlackArch/blackarch/assets/55957190/092cf240-33bc-492e-b62c-be4b4f1b9ded)

![Screenshot from 2023-06-20 01-45-46](https://github.com/BlackArch/blackarch/assets/55957190/ccd3e07c-d832-4087-b46f-81e66c1ce69d)

**3.**   under GERMANY number 3  no longer hosting blackarch mirror  only he hosting chaotic aur  (garuda linux repos)
  https://mirrors.dr460nf1r3.org/repos/blackarch/

![Screenshot from 2023-06-20 01-55-11](https://github.com/BlackArch/blackarch/assets/55957190/495de9d2-0b1b-4417-9116-e8583e311b91)

**4.** under great britan  last mirror of  fosst  host also 
   https://uk.mirrors.fossho.st/blackarch/

**5. Iran** mirror  also redirecting another of there site  (http one)  (https not available)
http://mirror.blackrepo.com/  &  https://mirror.blackrepo.com
![Screenshot from 2023-06-20 02-22-04](https://github.com/BlackArch/blackarch/assets/55957190/1a310fb2-8d95-4cf6-b40f-110da9c23181)

**6. SINGAPORE**  both  http & httos mirror also unavalable

http://download.nus.edu.sg/mirror/blackarch/
https://download.nus.edu.sg/mirror/blackarch/

![Screenshot from 2023-06-20 02-27-24](https://github.com/BlackArch/blackarch/assets/55957190/65225137-f9ba-4c14-aaf5-5f04053c4d21)

**Comment by PardesiCat** [comment]
## mirrors that working but not syncing for long time 

1. Ecuador  mirror last sync  2018     ( 1 & 2 & 3 number)   last one fine
 

![image](https://github.com/BlackArch/blackarch/assets/55957190/715bd336-fc5c-449f-9f1c-46e1f9e0aff2)


**2. RUSSIA**    last sync 22 april 2023
![Screenshot from 2023-06-20 03-09-05](https://github.com/BlackArch/blackarch/assets/55957190/d386e560-ebaf-4b31-a323-a03cd6c39bdc)


http://mirror.truenetwork.ru/blackarch/       (3 & 4 & 5 NUMBER) 

![Screenshot from 2023-06-20 03-04-53](https://github.com/BlackArch/blackarch/assets/55957190/3be3cca4-03d9-4760-b853-32b7d6bfdaff)

**Comment by averyterrel** [comment]
The following mirrors from https://blackarch.org/blackarch-mirrorlist are inaccessible:
```
ftp://mirror.neostrada.nl/blackarch/
ftp://distro.ibiblio.org/blackarch/
http://download.nus.edu.sg/mirror/blackarch/
http://mirror.neostrada.nl/blackarch/
http://mirror.undisclose.de/blackarch/
https://download.nus.edu.sg/mirror/blackarch/
https://mirror.neostrada.nl/blackarch/
https://mirror.undisclose.de/blackarch/
http://mirror.blackrepo.com/
http://blackarch.pi3rrot.net/blackarch/
```
`https://mirror.uta.edu.ec/blackarch/` is out of date by almost 5 years
The following sites do not return a 404 code but are inaccessible:
```
https://mirror.albony.xyz/blackarch/
https://mirrors.gethosted.online/blackarch/ should be https://mirrors.gethosted.online/blackarch/blackarch/
```

**Comment by PardesiCat** [comment]
@averyterrel    Albony Mirror is down due to a dead HDD. He told me that he ordered a replacement for his HDD.

here today  i asked him and yess its temp down

![20230623_19h22m34s_grim](https://github.com/BlackArch/blackarch/assets/55957190/0b969bea-86de-4484-a5a0-302efcc7c43e)

**Comment by Albonycal** [comment]
I think I emailed to all distros who were affected by this. Maybe I forgot to add the blackarch email. Sorry for inconvenience caused

**Comment by noraj** [comment]
Mirror out of sync since 2020 http://nz-mirror.intergrid.com.au/blackarch/blackarch/os/x86_64/?C=M;O=D cf #3918

**Comment by D3vil0p3r** [comment]
@noraj did you actually check if all the mentioned mirrors are not working anymore? If so, I can proceed to open PR.
