### ISSUE TITLE
Broken git-pipeline.

### ISSUE THREAD

**Issue by marianomarciello** [BlackArch/blackarch#3867]
Type: Question

## Broken git-pipeline
Hello everyone.
Today (21st June 2023) I have done one commit on a PR that I have done earlier. It seems that the git pipeline is not working since python2.7.x is removed from setup-python (as stated here [https://github.com/BlackArch/blackarch/actions/runs/5338164180/jobs/9675159979?pr=3857](https://github.com/BlackArch/blackarch/actions/runs/5338164180/jobs/9675159979?pr=3857)).
I am just notifying it. Someone can take care of this ?

I wrote a message on the Matrix server too.

Thanks for your time.

**Comment by apt-ghetto** [comment]
The support for Python 2.7 was removed from the images => https://github.com/actions/runner-images/issues/7401

**Comment by ikstream** [comment]
> The support for Python 2.7 was removed from the images => [actions/runner-images#7401](https://github.com/actions/runner-images/issues/7401)

We are aware of it and already responded on matrix. It will be fixed soon, but it's not critical.
Thank you nevertheless for pointing out.

**Comment by noraj** [comment]
I just removed it cf. https://github.com/BlackArch/blackarch/commit/b66c5c9a5c0e16152e2cf56d4591344428a82519 and it builds correctly https://github.com/BlackArch/blackarch/actions/runs/5381654271.

I guess [sepehrdaddev](https://github.com/BlackArch/blackarch/commits?author=sepehrdaddev) added it for pkgcheck-arch but [pkgcheck-arch](https://pypi.org/project/pkgcheck-arch/) supports python 3 as well.
