### ISSUE TITLE
Update CREEPY

### ISSUE THREAD

**Issue by PardesiCat** [BlackArch/blackarch#3881]
Type: Discussion

## Discussion

tool name : **creepy**

we use the tool name creepy [current in use](https://github.com/ilektrojohn/creepy)

but that is outdated in Blackarch repo (last updated in 2014) insead if we pack

this updated of [creepy](https://github.com/jkakavas/creepy) ,  it will be good

**Comment by PardesiCat** [comment]
https://github.com/BlackArch/blackarch/blob/master/lists/broken

**Comment by noraj** [comment]
it's currently broken with no upstream update and in our broken list so nothing we can really do, I think we can close this issue until something happens upstream
