### ISSUE TITLE
flare-floss outdated

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#3888]

**Comment by noraj** [comment]
We're at commit 860, upstream is at commit 1291.

**Comment by noraj** [comment]
I need to package envi required for viv-utils that flare-floss requires. https://github.com/williballenthin/viv-utils/issues/121

**Comment by noraj** [comment]
I'm working on it on the branch https://github.com/BlackArch/blackarch/tree/noraj/flare-floss
