### ISSUE TITLE
Blackarch not boot after install.

### ISSUE THREAD

**Issue by ashXbd** [BlackArch/blackarch#3901]
Anyone Please Help me!
I am install Blackarch Linux fast time. after install when i reboot pc and unplug my bootable usb drive. than i cant find any grub boot menu and my pc not boot blackarch linux. i was try it 4 to 5 times and every time i get same problem

**Comment by noraj** [comment]
The better place to get support is to join the community on Matrix: https://blackarch.org/community.html

**Comment by ashXbd** [comment]
> The better place to get support is to join the community on Matrix: https://blackarch.org/community.html

Thanks
