### ISSUE TITLE
de4dot: Not compiled

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#3914]
AUR: https://aur.archlinux.org/packages/de4dot-git
Please see comment: https://aur.archlinux.org/packages/de4dot-git#comment-902548
Kali: http://http.kali.org/pool/main/d/de4dot/

**Comment by noraj** [comment]
Could you provide the full error stack trace.

Note: https://github.com/de4dot/de4dot is archived since 2020

**Comment by vdun** [comment]
Package contains no binary:
`# pacman -Ql de4dot | grep bin`
It is archived, but still useful.

**Comment by noraj** [comment]
Yes, it was packaged as a Windows package, just downloading the pre-compiled exe (windows PE) and put it on `/usr/share/windows` for deployment on a target.

See https://github.com/BlackArch/blackarch/blob/master/packages/de4dot/PKGBUILD

Are you interested into providing an improved package so we have a linux binary as well?

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4271 enjoy
