### ISSUE TITLE
Not working BlackArch mirror

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3918]
The mirror **http://nz-mirror.intergrid.com.au/blackarch/$repo/os/$arch** is not working well because it lacks of some packages (for example `python2` and similar), so they are not synced with the main one, and packages dependent on this missing packages cannot be retrieved and pacman errors are produced.

**Comment by noraj** [comment]
To me it looks out of sync since 2020 http://nz-mirror.intergrid.com.au/blackarch/blackarch/os/x86_64/?C=M;O=D
