### ISSUE TITLE
ligolo-ng: proxy installs as agent, and agent as proxy

### ISSUE THREAD

**Issue by DidierA** [BlackArch/blackarch#3923]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

PKGBUILD contains
```
  install -Dm 755 proxy "$pkgdir/opt/$pkgname/agent"
  install -Dm 755 agent "$pkgdir/opt/$pkgname/proxy"
```

as a result, when launching /opt/ligolo-ng/agent we get the proxy and vice-versa.

**Comment by ikstream** [comment]
Thank you for reporting the problem, unfortunately there is a build issue with the current upstream  go version 1.20. 

nicocha30/ligolo-ng#32
