### ISSUE TITLE
[Tool Request]: badsecrets

### ISSUE THREAD

**Issue by utenus** [BlackArch/blackarch#3927]
- **Name**: badsecrets
- **Source URL**: https://github.com/blacklanternsecurity/badsecrets
- **Description**:
 A library for detecting known secrets across many web frameworks

**Comment by dualfade** [comment]
This is a very useful tool. can grab it if you would like.

**Comment by dualfade** [comment]
@noptrix would we like to add this ?

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4273
