### ISSUE TITLE
Burp Suite Distribution Terms

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3934]
## Question

Port Swigger does not allow distribution (as specified in [7.3](https://portswigger.net/burp/eula/community)) and I guess it could affect the distribution by a package. So, is it permitted that BlackArch repository distributes Burp package? If so, why?

**Comment by ikstream** [comment]
7.3 relates to removing tpm, it does not say anything about the distribution of Burp. 
You are not supposed to redistribute anything that can remove the tpm from burp community edition.

At least that's my understanding of 7.3

**Comment by noraj** [comment]
The sentence is too long, here disected:

> The Licensee must not attempt in any way to remove or circumvent any such TPM, nor [...] distribute [...] for private or commercial purposes any means the sole intended purpose of which is to facilitate the unauthorised removal or circumvention of such TPM.

Meaning it is not allowed to distribute a software which has a goal to remove the Burp TMP or copyright.

**Comment by D3vil0p3r** [comment]
Thank you very much!
