### ISSUE TITLE
Package Error - PEEPDF

### ISSUE THREAD

**Issue by PardesiCat** [BlackArch/blackarch#3936]
Type: Discussion 

## Discussion about Peepdf Tool

hei inside blackarch  PEEPDF tool is not  working  it will be great if you guys look at it

error log  ( note : python installed)

![peepdf](https://github.com/BlackArch/blackarch/assets/55957190/0cf1f449-42fe-4a8f-8ff9-b96ca0fbda39)

# Test in source 

but when i headed towards [BA-PKGBUILD](https://github.com/BlackArch/blackarch/blob/master/packages/peepdf/PKGBUILD)
 for source of the package  and got it then

for tesing purpose ( if the tool from source working or not )

**Yess its working fine**
as you can see in ss

![peepdfpype](https://github.com/BlackArch/blackarch/assets/55957190/049c2dad-4440-4a16-aec5-eb8ab467b7ce)

[ik setup.py install meathod  is deprecated  just did to test the packge in src ]

install log incase need
[installlog.txt](https://github.com/BlackArch/blackarch/files/12330579/installlog.txt)

**Comment by noptrix** [comment]
@PardesiCat try now - if not fixed re-open this issue
