### ISSUE TITLE
Spoofy

### ISSUE THREAD

**Issue by PardesiCat** [BlackArch/blackarch#3956]
- **Name**: 
- Spoofy
- 
- **Source URL**: 
- https://github.com/MattKeeley/Spoofy
- 
- **Description**:
- Spoofy is a program that checks if a list of domains can be spoofed based on SPF and DMARC records. 
- its python tool

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4275
