### ISSUE TITLE
[Tool Request] Wazuh

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3960]
- **Name**: Wazuh
- **Source URL**: https://github.com/wazuh/wazuh/
- **Description**: Unified XDR and SIEM protection for endpoints and cloud workloads.

**Comment by noraj** [comment]
- https://aur.archlinux.org/packages?K=Wazuh
- https://wiki.archlinux.org/title/Unofficial_user_repositories#condorcore
