### ISSUE TITLE
w3af does not work

### ISSUE THREAD

**Issue by raj77in** [BlackArch/blackarch#3971]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Not able to start w3af console or gui application.

### Steps to reproduce

- Installed blackarch with latest OVA file in Virtualbox.
- Ran sysclean.sh
- Tried to run w3af-gui

**Actual result:** 
Getting below error:
```
# w3af-gui 
/sbin/python2: can't find '__main__' module in '/usr/share/w3af/'
```
**Expected result:** 
w3af gui should start.

### Screenshots

![image](https://github.com/BlackArch/blackarch/assets/3305948/94b54bb2-4c17-405d-a943-5fcdf8307621)

### Info for developers
Virtual machine created from latest OVA file

**Comment by saltasatelites** [comment]
Install python2 (deprecated) Is an outdate tool

**Comment by noraj** [comment]
https://github.com/BlackArch/blackarch/blob/master/packages/w3af/PKGBUILD

By the way, the last github release is 1.6.49 (https://github.com/andresriancho/w3af/archive/refs/tags/1.6.49.tar.gz) but the last git tag is 1.6.54 (https://github.com/andresriancho/w3af/archive/refs/tags/1.6.54.tar.gz) so it could be updated.

Also the last git tag is from 2015 while the last commit is from 2020 so we maybe move to a git pkgver instead.

But even the last commit seems to still use Python 2.7. I think we could say upstream is abandonned:

- Using python 2.7 in 2023
- No commit for 3 years
- No release for 8 years

Also some guy claims to have made a python 3 port named w4af https://github.com/w4af/w4af/

**Comment by noraj** [comment]
https://github.com/BlackArch/blackarch/commit/7e7fed1f5a485a364ab0706b640f3cb182134631
