### ISSUE TITLE
Bloodhound upstream repo migration

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3972]
We need to change

https://github.com/BlackArch/blackarch/blob/0a2ee213e5d77c33d76a0bc59750ccae56e77ab8/packages/bloodhound/PKGBUILD#L16

to https://github.com/SpecterOps/BloodHound

**Comment by noraj** [comment]
@noptrix Should we start packaging dockers? Like deploying a docker-compose.yml with remote images or sources + locally built Dockerfiles under `/usr/share` and create a wrapper launching the docker-compose in `/usr/bin`?

**Comment by noptrix** [comment]
@noraj is this still valid or can we close this?

**Comment by noraj** [comment]
- https://github.com/BloodHoundAD/BloodHound is BH v4
- https://github.com/SpecterOps/BloodHound is BH v5

but they are 2 different products, so I guess we don't need a migration, we keep BH v4 as is right now, and may package v5 one day, so yes I'll close this.
