### ISSUE TITLE
Problem after booting from usb

### ISSUE THREAD

**Issue by edenlith** [BlackArch/blackarch#3979]
I downloaded the slim iso and booted it into a usb using rufus. When I boot from the usb I am greeted with a blackarch menu with four options (can't remember the names correctly but it's something like blackarch with speech, blackarch, firmware and exit I think). I choose the second option and get sent to rootfs with this error displayed: :: running early hook [udev]
Starting systemd-udevd version 253.3-3-arch
:: running early hook [archiso_pxe_nbd]
:: running hook [udev]
:: Triggering uevents...
:: running hook [memdisk]
:: running hook [archiso]
:: running hook [archiso_loop_mnt]
:: running hook [archiso_pxe_common]
:: running hook [archiso_pxe_nbd]
:: running hook [archiso_pxe_http]
:: running hook [archiso_pxe_nfs]
:: Mounting '/dev/disk/by-label&BLACKARCH_202305' to '/run/archiso/bootmnt'
mount: /run/archiso/bootmnt: unknown filesystem type 'ntfs' 
	dmesg(1) may have more information after failed mount system call.
ERROR: failed to mount '/dev/disk/by-label/BLACKARCH_202305"
Falling back to interactive prompt
You can try to fix the problem manually, log out when you are finished 
sh: can't access tty; job control turned off

Does the usb format need to be changed? Can the iso be corrupted?

Thanks

**Comment by ikstream** [comment]
Have you verified the checksum before you flashed the image to the USB drive?

**Comment by edenlith** [comment]
No. I'm a noob on this. Can you tell me how to do it?

**Comment by noraj** [comment]
1. Find the hash here: https://blackarch.org/downloads.html
2. `echo <hash> blackarch.iso | sha1sum -c`

**Comment by edenlith** [comment]
@noraj thanks for the good customer service but you can close the thread. I found out that rufus was not the right software to create a bootable iso with blackarch and instead used etcher which fixed the problem. Do you happen to know where i can find a tutorial to install blackarch on an external drive?

**Comment by noraj** [comment]
check the ArchLinux wiki : Install Arch Linux on a removable medium.
