### ISSUE TITLE
hostapd-wpe outdated

### ISSUE THREAD

**Issue by 2goese** [BlackArch/blackarch#3980]
It's still on 2.9.1

Latest version is 2.10 as seen on [AUR](https://aur.archlinux.org/packages/hostapd-wpe).

**Comment by noraj** [comment]
- [ ] https://github.com/BlackArch/blackarch/blob/master/packages/hostapd-wpe/PKGBUILD

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4276
