### ISSUE TITLE
no internet connection 

### ISSUE THREAD

**Issue by kokojdbxdk** [BlackArch/blackarch#3983]
Hi, I'm new blackarch user
when i download black arch full iso  in vbox in my laptop and join into the machine
i type: sudo pacman -Sy to update files in the black arch
and this what happen 
![IMG_20231020_145200](https://github.com/BlackArch/blackarch/assets/144600761/baa2fe12-d8f1-4f74-b77e-849ab9e9a394)
he says:  failed  to synchronous all database (invalid url for server 
Please anyone help

**Comment by anunna** [comment]
Did you connect to the internet? Internet is disabled by default.

**Comment by kokojdbxdk** [comment]
> Did you connect to the internet? Internet is disabled by default.

its a virtual box i connect to the internet but i hv this error

**Comment by kokojdbxdk** [comment]
> If you have confirmed that you have an active internet connection within your VM, change your mirror to one that is closer to you. You can comment out mirrors of your choice in `/etc/pacman.d/blackarch-mirrorlist` and run `pacman -Sy` again.

Not working the same problem 💔

**Comment by kokojdbxdk** [comment]
i think i know the problem i hv internet in my desktop 
![Uploading IMG_20231020_203515.jpg…]()
there is no any wifi in the black arch
how can i add one i use virtual box

**Comment by kokojdbxdk** [comment]
![Uploading IMG_20231020_203515.jpg…]()

**Comment by kokojdbxdk** [comment]
![Uploading IMG_20231020_203515.jpg…]()

**Comment by kokojdbxdk** [comment]
any one help pls

**Comment by anunna** [comment]
I can't see your images. If you want WIFI in your VM, you would need a compatible card that supports passthrough (dedicated PCI card commonly). It would be recommended to setup a bridged interface for either Ethernet or WiFi, both would result in Ethernet connection in your VM. If you are looking to do WIFI scanning from the VM, you'll need to do some hardware research if your card supports it.

If you have a notebook, high chance your integrated wireless card does not support this. 

Also read up on [networking](https://www.virtualbox.org/manual/ch06.html) for Virtual Box for better understanding.
