### ISSUE TITLE
Hi does some1 know why when im opening VSCode from AUR or code oss on blackarch slim with default blackarch XFCE4 settings it lagging and it is impossible to use it but if i run it on KDE Plasma it works as it should

### ISSUE THREAD

**Issue by woeczx** [BlackArch/blackarch#3986]
Type: Question

## Question

**Comment by noraj** [comment]
Hi

Could you

- re-open the issue on the appropriate issue tracker https://github.com/BlackArch/blackarch-iso/issues (as it seems to concerns SLIM ISO)
- put your description in the text filed and not in the title
- fill the bug template as much as you can https://github.com/BlackArch/blackarch/blob/master/.github/ISSUE_TEMPLATE/01_bug_report.md?plain=1
