### ISSUE TITLE
witchxtool - cannot resolve "perl-data-validate-ip"

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3989]
`witchxtool` cannot be installed. Its installation produces now the following issue:
```
sudo pacman -S witchxtool

resolving dependencies...
warning: cannot resolve "perl-data-validate-ip", a dependency of "witchxtool"
:: The following package cannot be upgraded due to unresolvable dependencies:
      witchxtool

:: Do you want to skip the above package for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'perl-data-validate-ip' required by witchxtool
```
Is there a way to replace that dependency or `witchxtool` should be deleted from the repo?

**Comment by saltasatelites** [comment]
This tool has not been updated in the last 5 years- it is completely deprecated.
Th only way to install the modules is via -MCPAN and probably causes more problems than solutions.

**Comment by D3vil0p3r** [comment]
> This tool has not been updated in the last 5 years- it is completely deprecated. Th only way to install the modules is via -MCPAN and probably causes more problems than solutions.

or just packaging the [missing dependency](https://aur.archlinux.org/packages/perl-data-validate-ip)

**Comment by saltasatelites** [comment]
Sorry, but I don't understand the point of add more and more deprecated tools to BlackArch, having tools that do the same better and with active development.

**Comment by D3vil0p3r** [comment]
> Sorry, but I don't understand the point of add more and more deprecated tools to BlackArch, having tools that do the same better and with active development.

I agree with you, I was just pointing an existing alternative.

**Comment by anunna** [comment]
Dependency was added anyway in #4002. We are not adding deprecated tools, it exists since 2018. If it works, its mostly fine; Someone may prefer the tool.

Maintain until its conflicting/unmaintainable.

**Comment by D3vil0p3r** [comment]
Thank you @anunna
