### ISSUE TITLE
Issue: tor-router version 4.001a510-1 Experiences Algorithmic Termination Issue with an Old Commit

### ISSUE THREAD

**Issue by Extr3m4R4710** [BlackArch/blackarch#3995]
# Issue: tor-router version 4.001a510-1 Experiences Algorithmic Termination Issue with an Old Commit

- **Package Name**: tor-router

- **Source URL**: [Commit Link](https://github.com/Edu4rdSHL/tor-router/commit/290d0b1e29a13a4e1d4f109a6a31bdd1da523dc9)

- **Description**: 
  The package tor-router-4.001a510-1-any.pkg.tar.xz is currently using an outdated commit, which is causing an algorithmic termination problem. However, this issue has already been addressed and resolved in the [latest commit](https://github.com/Edu4rdSHL/tor-router/commit/290d0b1e29a13a4e1d4f109a6a31bdd1da523dc9).

### Background on Issue Creation:
I was instructed by dualfade to create an issue. But before that I was told to create a PR from noptrix (perhaps my English was so bad that noptrix thought I was asking for an update of the original tor-router and not this package), so I made a mistake and accidentally created a bad I created a bad PR. So there are two PRs in total: dualfade and mine. 

Sorry for the troll act.

I am here to assist to the best of my abilities. thank you.

**Comment by dualfade** [comment]
This was updated and pushed --
blackarch/tor-router 21.290d0b1-1 (16.6 KiB 39.8 KiB) [blackarch blackarch-defensive]

https://github.com/BlackArch/blackarch/pull/3990

Closing.
