### ISSUE TITLE
DoSinator: Dos testing tool developed with Python

### ISSUE THREAD

**Issue by HalilDeniz** [BlackArch/blackarch#4001]
# DoSinator

DoSinator is a powerful Denial of Service (DoS) testing tool developed with Python. Designed for security professionals and researchers, this tool allows them to simulate various DoS attacks. In this way, it provides a realistic environment for assessing the resilience of networks, systems and applications against potential cyber threats.

---

![Dosinator](https://github.com/HalilDeniz/Dosinator/raw/main/source/dosinator2.png)

## Features

- **Multiple Attack Modes**: DoSinator supports SYN Flood, UDP Flood, ICMP Flood,Os Fingerprint, Slowloris, and Smurf attack modes, allowing you to simulate various types of DoS attacks.
- **Customizable Parameters**: Adjust the packet size, attack rate, and duration to fine-tune the intensity and duration of the attack.
- **IP Spoofing**: Enable IP spoofing to mask the source IP address and enhance anonymity during the attack.
- **Multithreaded Packet Sending**: Utilize multiple threads for simultaneous packet sending, maximizing the attack speed and efficiency.
- **Data from File**: Load custom data from a file to be sent in the attack packets.
- **PCAP Output**: Save the outgoing attack packets to a PCAP file for further analysis.
[Dosinator](https://github.com/HalilDeniz/Dosinator)

**Comment by anunna** [comment]
Thank you for your request. We do not accept DOS tools.
