### ISSUE TITLE
Persistent issue with the keyring, having errors with unknown trust. Is there an error in my configuration?

### ISSUE THREAD

**Issue by Icarus131** [BlackArch/blackarch#4006]
Type: Question

# Question: 

# Before anything, here is the error message I have been getting:
`error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is unknown trust
error: database 'blackarch' is not valid (invalid or corrupted database (PGP signature))`

# What I have tried:
- Following the FAQ and all the steps highlighted in it regarding keyring errors
- Removing cache (Doubt this helps much but did it anyway)
- Modifying the mirrors
- Running strap.sh again

# What works and what doesnt:
- As of now the only way my machine is still usable is because everytime I run `pacman-key --populate archlinux blackarch` the error does not show up and pacman works as usual. As soon as I reboot my machine the error starts showing up again, not allowing me to use pacman to any extent. This forces me to basically populate the keys on every reboot.

**Comment by noraj** [comment]
Please understand, this issue tracker is mean to track issues (bugs or feature requests).

For ask support, please go to:

- BlackArch Linux
  - the matrix community channel, see https://www.blackarch.org/community.html
  - our reddit https://www.reddit.com/r/BlackArchOfficial/
- ArchLinux
  - mailing list https://lists.archlinux.org/postorius/lists/
  - IRC https://wiki.archlinux.org/title/Arch_IRC_channels
