### ISSUE TITLE
Getting Dependencies Conflicts While Perfoming Full-Upgrad from slim version

### ISSUE THREAD

**Issue by recklessdriver** [BlackArch/blackarch#4008]
## Question: Getting dependencies conflicts while performing full upgrad from slim blackarch version. 

I have run the following command to perform the full upgrade.
```
sudo pacman -Sy
sudo pacman -Su
```

### Error screenshot
![full-upgrade error](https://github.com/BlackArch/blackarch/assets/150805786/873548ae-bd42-4f95-af25-7f9889fc2b44)

### Looking forward for your support.
Thanks

**Comment by anunna** [comment]
Arch Linux made changes to Java. [Read more](https://archlinux.org/news/incoming-changes-in-jdk-jre-21-packages-may-require-manual-intervention/)

Please run to resolve: 
`pacman -Rns jre-openjdk jdk-openjdk && pacman -Syyu && sysclean.sh && pacman -S blackarch --needed`

**Comment by recklessdriver** [comment]
Hey, 

Thanks for prompt reply. 

I tried running commands but I am getting this error now, 

![error-2](https://github.com/BlackArch/blackarch/assets/150805786/a8ac0978-b696-459d-926a-4c1f81e33b81)

I am new to BA, can u also share some learning resources?

Thanks,

**Comment by recklessdriver** [comment]
Hey

I tried 
```
pacman -Syu jdk-openjdk
```
as per documentation.

Getting these errors. 

![e1](https://github.com/BlackArch/blackarch/assets/150805786/0019efa5-93e7-4c47-9347-7085771bb4e3)

**Comment by noraj** [comment]
> ![error-2](https://user-images.githubusercontent.com/150805786/282865524-a8ac0978-b696-459d-926a-4c1f81e33b81.png)

You can uninstall calamares, it's an installer and no longer needed after installation.

**Comment by noraj** [comment]
Please understand, this issue tracker is mean to track issues (bugs or feature requests).

For ask support, please go to:

- BlackArch Linux
  - the matrix community channel, see https://www.blackarch.org/community.html
  - our reddit https://www.reddit.com/r/BlackArchOfficial/
- ArchLinux
  - mailing list https://lists.archlinux.org/postorius/lists/
  - IRC https://wiki.archlinux.org/title/Arch_IRC_channels
