### ISSUE TITLE
unblob

### ISSUE THREAD

**Issue by tridentsx** [BlackArch/blackarch#4009]
I would love to have unblob as official package its my new goto tool for extractions of binaries replacing binwalk, much less false positives and it just works.
Please consider adding it.

**Comment by noraj** [comment]
Please fill the template you removed:

```md
- **Name**:
- **Source URL**:
- **Description**:
```

**Comment by noraj** [comment]
If you consider adding the package yourself:

- AL PKGBUILD guide: https://wiki.archlinux.org/index.php/PKGBUILD
- BA PKGBUILD templates: https://github.com/BlackArch/blackarch-pkgbuilds

**Comment by tridentsx** [comment]
- unblob:
- https://github.com/onekey-sec/unblob:
- unblob is an accurate, fast, and easy-to-use extraction suite. It parses unknown binary blobs for more than 30 different archive, compression, and file-system formats, extracts their content recursively, and carves out unknown chunks that have not been accounted for.:

Sorry didnt see the template

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/issues/4009
