### ISSUE TITLE
Tool Add

### ISSUE THREAD

**Issue by mahidm2** [BlackArch/blackarch#4017]
zphisher
Need  this tool for social 🙃🙃

**Comment by noraj** [comment]
Please fill the template correctly

![image](https://github.com/BlackArch/blackarch/assets/16578570/44d0c130-d3c0-411b-954b-8e8468d129fb)

![image](https://github.com/BlackArch/blackarch/assets/16578570/ae6b24c0-0c23-4428-aaec-0bca6913d135)
