### ISSUE TITLE
Error signature during a BlackArch update.

### ISSUE THREAD

**Issue by kheIdar** [BlackArch/blackarch#4018]
I encountered an error during a BlackArch update, and I can't find the solution:

sudo pacman -Syu
error: blackarch: signature from 'Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>' is unknown trust
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 multilib is up to date
 blackarch                               4.0 MiB  1228 KiB/s 00:03 [####################################] 100%
error: blackarch: signature from 'Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>' is unknown trust
error: failed to synchronize all databases (invalid or corrupted database

If someone can help me, thank you.

**Comment by noraj** [comment]
https://blackarch.org/faq.html

**Comment by Kheldartv** [comment]
I already tried, but it didn't solve my problem.

**Comment by noraj** [comment]
you sure it's not a dead mirror like https://github.com/BlackArch/blackarch/discussions/3939#discussioncomment-6768749

**Comment by Kheldartv** [comment]
I imagine that this is not the best solution, but I haven't found a better one yet. Yes, I have tried mirrors, but no results.

**Comment by isidoridev** [comment]
Temporary fix if you **_really_** want to update (possibly has problems) is to skip blackarch packages by commenting inside the `pacman.conf`: 
```
#[blackarch]
#Include = /etc/pacman.d/blackarch-mirrorlist
```
Hopefully a proper solution is found.

**Comment by BIGBEASTISHANK** [comment]
i tried changing mirrors and removing blackarch.db.sig file still no improvement, still getting same error

**Comment by 0xBroth** [comment]
So I've found a pseudo fix for myself. (No pun intended lol) I've used a combination of the FAQ from the Blackarch website, [3939](https://github.com/BlackArch/blackarch/discussions/3939#discussioncomment-6768749), and an attempted local key sign.

`sudo pacman-key --recv-keys F9A6E68A711354D84A9B91637533BAFE69A25079 && sudo pacman-key --lsign-key F9A6E68A711354D84A9B91637533BAFE69A25079`

The above takes the signature associated with the "noptrix" key and locally signs it.  I know in some cases this might not work, but I was able to get it to work after I ran the FAQ and played around with the mirrors.

This however is a band aid fix because I find every time I restart the machine the key has to be re-signed.

I get this out put when running the following command before running the key sign:
```
gpg --homedir /etc/pacman.d/gnupg --list-keys | grep nop
gpg: WARNING: unsafe ownership on homedir '/etc/pacman.d/gnupg'
gpg: Note: trustdb not writable
uid           [  full  ] Levon 'noptrix' Kayan (BlackArch Master) <noptrix@nullsecurity.net>
uid           [ unknown] Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>
```

After the key sign:
```
gpg --homedir /etc/pacman.d/gnupg --list-keys | grep nop
gpg: WARNING: unsafe ownership on homedir '/etc/pacman.d/gnupg'
gpg: Note: trustdb not writable
uid           [  full  ] Levon 'noptrix' Kayan (BlackArch Master) <noptrix@nullsecurity.net>
uid           [  full  ] Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>
```

The developer key seems to be giving me the issue, and won't seem to stick.  I'm still a noob at this so I'm not sure if this will help anyone. ¯\_(ツ)_/¯

**Comment by BIGBEASTISHANK** [comment]
> So I've found a pseudo fix for myself. (No pun intended lol) I've used a combination of the FAQ from the Blackarch website, [3939](https://github.com/BlackArch/blackarch/discussions/3939#discussioncomment-6768749), and an attempted local key sign.
> 
> `sudo pacman-key --recv-keys F9A6E68A711354D84A9B91637533BAFE69A25079 && sudo pacman-key --lsign-key F9A6E68A711354D84A9B91637533BAFE69A25079`
> 
> The above takes the signature associated with the "noptrix" key and locally signs it. I know in some cases this might not work, but I was able to get it to work after I ran the FAQ and played around with the mirrors.
> 
> This however is a band aid fix because I find every time I restart the machine the key has to be re-signed.
> 
> I get this out put when running the following command before running the key sign:
> 
> ```
> gpg --homedir /etc/pacman.d/gnupg --list-keys | grep nop
> gpg: WARNING: unsafe ownership on homedir '/etc/pacman.d/gnupg'
> gpg: Note: trustdb not writable
> uid           [  full  ] Levon 'noptrix' Kayan (BlackArch Master) <noptrix@nullsecurity.net>
> uid           [ unknown] Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>
> ```
> 
> After the key sign:
> 
> ```
> gpg --homedir /etc/pacman.d/gnupg --list-keys | grep nop
> gpg: WARNING: unsafe ownership on homedir '/etc/pacman.d/gnupg'
> gpg: Note: trustdb not writable
> uid           [  full  ] Levon 'noptrix' Kayan (BlackArch Master) <noptrix@nullsecurity.net>
> uid           [  full  ] Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>
> ```
> 
> The developer key seems to be giving me the issue, and won't seem to stick. I'm still a noob at this so I'm not sure if this will help anyone. ¯_(ツ)_/¯

ok

**Comment by TazMania-Git** [comment]
Thanks @0xBroth, works for me!

**Comment by D3vil0p3r** [comment]
If the issue is related to gnupg  version, why the only broken signing key is only the noptrix one while the other AL keys are working as expected?

**Comment by lilian-lilifox** [comment]
> If the issue is related to gnupg version, why the only broken signing key is only the noptrix one while the other AL keys are working as expected? @D3vil0p3r 

Thanks to @anunna 

When using 'gnupg=2.4.3-2'，it outputs (Notice that third-party key signatures using the SHA1 algorithm are rejected):
```bash
sudo pacman-key --populate archlinux blackarch
==> Appending keys from archlinux.gpg...
==> Appending keys from blackarch.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signed 9 keys.
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
==> Disabling revoked keys in keyring...
  -> Disabled 44 keys.
==> Updating trust database...
gpg: Note: third-party key signatures using the SHA1 algorithm are rejected
gpg: (use option "--allow-weak-key-signatures" to override)
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   9  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   9  signed:  97  trust: 0-, 0q, 0n, 9m, 0f, 0u
gpg: depth: 2  valid:  72  signed:  21  trust: 72-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2024-01-21
```

And when using `gnupg=2.2.41-2`, it outputs:
```bash
sudo pacman-key --populate archlinux blackarch
==> Appending keys from archlinux.gpg...
==> Appending keys from blackarch.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signed 9 keys.
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
==> Disabling revoked keys in keyring...
  -> Disabled 44 keys.
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   9  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   9  signed: 100  trust: 0-, 0q, 0n, 9m, 0f, 0u
gpg: depth: 2  valid:  75  signed:  28  trust: 75-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2024-01-21
```

It works well! And then you can `pacman -Syu` as before. 
So I think its the reason noptrix's key uses the algorithm that gnupg does not accept anymore in recent update.

### And a small tip:
You need do this in `pacman.conf` first before downgrade:
```
#[blackarch]
#Include = /etc/pacman.d/blackarch-mirrorlist
```
then run downgrade and add it to IgnorePkg:
```bash
$ downgrade 'gnupg=2.2.41-2'
```
And follow this issue. Hopefully it'll be fixed soon.

**Comment by D3vil0p3r** [comment]
I can reproduce the same. Thank you @lilian-lilifox

**Comment by anunna** [comment]
Thanks for this @lilian-lilifox I've let noptrix know and see if we can get his key updated in the keyring. 

I do however, for interest, have other issues on my system with 2.4.3 where I am unable to generate new gpg keys and some packages are unable to install via AUR. Mostly packages that install keys, etc., which may also be victim to weak keys but that's a different conversation.

**Comment by jakejasey** [comment]
I to am having this issue. Has there been any updates on this yet?

**Comment by dualfade** [comment]
A new strap.sh was released today. You may want to look into this.
https://blackarch.org/downloads.html#install-repo

**Comment by Schimi6** [comment]
> A new strap.sh was released today. You may want to look into this. https://blackarch.org/downloads.html#install-repo

this fixed everything, good news for all of us!

**Comment by nixfreak** [comment]
New strap.sh works on a pre-installed machine. 

```
