### ISSUE TITLE
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@mullsecurity.net>" is unknown trust

### ISSUE THREAD

**Issue by Rojje** [BlackArch/blackarch#4027]
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@mullsecurity.net>" is unknown trust error: database 'blackarch' is not valid (invalid or corrupted database (PGP signature))

**I've been trying to fix it since yesterday and I don't know how to do it, I've followed all the other solutions and it still doesn't work (I'm installing arch linux from 0 for the first time :)).**

**Comment by anunna** [comment]
You are required to make sure you are not submitting a duplicate issue. Before you opened this issue, you would have noticed the 3rd open issue is the same as this. 

I have posted a temporary solution in it, please follow it, I am closing this issue. 

Duplicate of #4018

**Comment by Rojje** [comment]
Thx
