### ISSUE TITLE
PPLKiller

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#4032]
- **Name**: PPLKiller
- **Source URL**: https://github.com/Mattiwatti/PPLKiller
- **Description**: Protected Processes Light Killer

**Comment by D3vil0p3r** [comment]
PPLKiller uses `Microsoft.Cpp.Default.props` that does not exist on Linux, it is a Windows component. So it cannot be compiled by `msbuild`. The best option could be to contact the maintainer and ask to submit a compiled .exe directly on GitHub Releases.

https://github.com/Mattiwatti/PPLKiller/issues/23
