### ISSUE TITLE
[Tool Request] dnspyex

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#4038]
- **Name**: dnspyex
- **Source URL**: https://github.com/dnSpyEx/dnSpy
- **Description**: Unofficial revival of the well known .NET debugger and assembly editor, dnSpy

**Comment by noraj** [comment]
As for most C# stuff it won't be to run it on Linux but just to provide binary to copy on a windows host cf. https://github.com/BlackArch/blackarch/blob/master/packages/dnspy/PKGBUILD

**Comment by D3vil0p3r** [comment]
@noraj close it please
