### ISSUE TITLE
Error during the installation of mana due to missing "libnl1" dependency

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#4040]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

During the install of `mana`, the user gets:
```
sudo pacman -S mana

resolving dependencies...
warning: cannot resolve "libnl1", a dependency of "mana"
:: The following package cannot be upgraded due to unresolvable dependencies:
      mana
```

### Steps to reproduce

- `sudo pacman -S mana`

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
```
sudo pacman -S mana

resolving dependencies...
warning: cannot resolve "libnl1", a dependency of "mana"
:: The following package cannot be upgraded due to unresolvable dependencies:
      mana
```

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Correct install of `mana`.

**Comment by saltasatelites** [comment]
Mana is deprecated and the development stopped 7 years ago.
Quote:
 At Defcon 26 we talked about how we're deprecating mana-toolkit in favour of [bettercap](http://bettercap.org/) and [berate-ap](https://github.com/sensepost/berate_ap). The core of mana, [hostapd-mana](https://github.com/sensepost/hostapd-mana) is still under active development. This repo isn't going anywhere, and can still be used, but it hasn't been actively maintained for some time. Keep an eye on [w1f1.net](https://w1f1.net/) for more info.

**Comment by D3vil0p3r** [comment]
So, should it be removed from BlackArch repo?

**Comment by anunna** [comment]
Yes, if the dev said they deprecated in favour of another then we keep what was recommended and remove the abandonment tool.
