### ISSUE TITLE
How to update the system after intall?

### ISSUE THREAD

**Issue by jabbalaci** [BlackArch/blackarch#4046]
Type: Question

## Question

I installed the slim ISO version. After the installation, I noticed that only one line was active in `/etc/pacman.d/mirrorlist`, so I uncommented some more mirrors. Later I noticed the file `blackarch-mirrorlist` . Should I uncomment some servers in this file too?

For updating everything, I prefer to use the command `yay`. Does it use both mirror lists (i.e. `mirrorlist` and `blackarch-mirrorlist`)?

Also, in the header of `/etc/pacman.d/mirrorlist` we can see the date 2021. Is it a good idea to refresh this file by using https://archlinux.org/mirrorlist/ ? Thanks.

**Comment by noraj** [comment]
mirrorlist is for AL repos and blackarch-mirrorlist for BA repos

see https://wiki.archlinux.org/title/Mirrors#Sorting_mirrors for sorting mirrors
