### ISSUE TITLE
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid error: failed to synchronize all databases (invalid or corrupted database (PGP signature))

### ISSUE THREAD

**Issue by iannnooooo** [BlackArch/blackarch#4055]
[ ian-hpnotebook /home/ianm ]# curl -O https://blackarch.org/strap.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5599  100  5599    0     0   6498      0 --:--:-- --:--:-- --:--:--  6510
[ ian-hpnotebook /home/ianm ]# echo 3f121404fd02216a053f7394b8dab67f105228e3 strap.sh | sha1sum -c
strap.sh: OK
[ ian-hpnotebook /home/ianm ]# chmod +x strap.sh
[ ian-hpnotebook /home/ianm ]# ./strap.sh
[+] checking gnupg version...
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid
[+] installing blackarch keyring...
[+] backing up pacman.conf
[+] downgrade gnupg to stable release
[+] fixing gnupg trust database...
'/etc/pacman.conf' -> '/etc/pacman.conf.blackarch'
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid
error: database 'blackarch' is not valid (invalid or corrupted database (PGP signature))
loading packages...
warning: downgrading package gnupg (2.4.3-2 => 2.2.41-2)
error: failed to prepare transaction (invalid or corrupted database)
rm: cannot remove '/etc/pacman.d/gnupg': Device or resource busy
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
==> Generating pacman master key. This may take some time.
gpg: Generating pacman keyring master key...
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/A34568262017218781AE8038C407EFFC0A5E896E.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
==> Appending keys from archlinux.gpg...
==> Appending keys from blackarch.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signed 9 keys.
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
==> Disabling revoked keys in keyring...
  -> Disabled 44 keys.
==> Updating trust database...
gpg: Note: third-party key signatures using the SHA1 algorithm are rejected
gpg: (use option "--allow-weak-key-signatures" to override)
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   9  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   9  signed:  99  trust: 0-, 0q, 0n, 9m, 0f, 0u
gpg: depth: 2  valid:  74  signed:  22  trust: 74-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2024-01-21
==> Updating trust database...
gpg: next trustdb check due at 2024-01-21
[+] setting IngorePkg gnupg...
loading packages...
warning: blackarch-keyring-20140118-3 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) blackarch-keyring-20140118-3

Total Installed Size:  0.04 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                   [##############################################] 100%
(1/1) checking package integrity                                                 [##############################################] 100%
(1/1) loading package files                                                      [##############################################] 100%
(1/1) checking for file conflicts                                                [##############################################] 100%
:: Processing package changes...
(1/1) reinstalling blackarch-keyring                                             [##############################################] 100%
==> Appending keys from blackarch.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2024-01-21
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
==> Appending keys from archlinux.gpg...
==> Appending keys from blackarch.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2024-01-21

[+] keyring installed successfully
[+] updating package databases
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid
:: Synchronizing package databases...
 core                                                128.3 KiB  60.9 KiB/s 00:02 [##############################################] 100%
 extra                                                 8.3 MiB  1198 KiB/s 00:07 [##############################################] 100%
 community                                            45.0   B  78.0   B/s 00:01 [##############################################] 100%
 multilib                                            139.5 KiB   128 KiB/s 00:01 [##############################################] 100%
 blackarch                                             4.0 MiB  1465 KiB/s 00:03 [##############################################] 100%
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))
[!] WARNING: Synchronizing pacman has failed. Please try manually: pacman -Syy
[+] restoring pacman.conf
[+] BlackArch Linux is ready!

## Kindly can someone assist

**Comment by noraj** [comment]
You may find the solution in one of the solved issues https://github.com/BlackArch/blackarch/issues?q=is%3Aissue+error%3A+blackarch%3A+signature+from+%22Levon+%27noptrix%27+Kayan+is%3Aclosed

**Comment by noraj** [comment]
Closing as no more news for 1 month.

**Comment by golam71** [comment]
@noraj  re open issue its back
