### ISSUE TITLE
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is unknown trust

### ISSUE THREAD

**Issue by Ringroad28** [BlackArch/blackarch#4061]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Describe here the issue that you are experiencing.

### Steps to reproduce

- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Info for developers

**Device:** Manufacturer Model XVI (Only if you consideer needed, for example, network cards)
**GNU/Linux distribution:** (If you are using one distro that is not BlackArch, example: Manjaro, Anarchy, etc)
**Tool version:** 0.0.0

**Comment by noraj** [comment]
Have you checked the answers in the 24 others similar issues: https://github.com/BlackArch/blackarch/issues?q=is%3Aissue+error%3A+blackarch%3A+signature+from+%22Levon+%27noptrix%27+Kayan+%28BlackArch+Developer%29+%3Cnoptrix%40nullsecurity.net%3E%22+?

**Comment by SomewhatAwake** [comment]
It looks like the issue has cropped up again, the new strap.sh doesn't work for me, and nothing I've tried in the closed tickets seems to work.

**Comment by MichaelSebero** [comment]
I've got the same issue as well.

**Comment by MichaelSebero** [comment]
The SHA1 sum of the file doesn't match the file either it should be 9f770789df3b7803105e5fbc19212889674cd503 but it's 26849980b35a42e6e192c6d9ed8c46f0d6d06047.

**Comment by barebonescyber** [comment]
Confirming @MichaelSebero's update.

All previously discussed fixes fail to resolve this issue currently.

Confirmed all steps listed in [Black Arch Wiki / FAQ](https://www.blackarch.org/faq.html#collapseFour) have been followed.

Pulled a fresh version of strap.sh from https://blackarch.org/strap.sh and received the following:

~ $ curl -O https://blackarch.org/strap.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4548  100  4548    0     0   8721      0 --:--:-- --:--:-- --:--:--  8712

~ $ sha1sum strap.sh
26849980b35a42e6e192c6d9ed8c46f0d6d06047  strap.sh

Hash is different from documentation for fix.

**Comment by yeti-code** [comment]
This issue is back, can confirm. Nothing solves it. Even running the strap.sh file from blackarch.org. It's sadly issues like this which crop up that push me towards just loading up kali or my own custom VM. I want to switch to blackarch fulltime without having to set anything up myself. This is why I don't unfortunately.

**Comment by luoyueyuguang** [comment]
I encountered this issue too.
Two days ago, I solved it by using new strap.sh.But I encounter it again.
Today, I added arch4edu,then I executed my first`sudo pacman -Syyu` in the day,I encountered it.
In /etc/pacman.conf, I can add
```
[blackarch]
SigLevel=Never
Include = /etc/pacman.d/blackarch-mirrorlist
```
to skip this error temporarily,but I don't think this is good solution can be used for long.

**Comment by SomewhatAwake** [comment]
> This issue is back, can confirm. Nothing solves it. Even running the strap.sh file from blackarch.org. It's sadly issues like this which crop up that push me towards just loading up kali or my own custom VM. I want to switch to blackarch fulltime without having to set anything up myself. This is why I don't unfortunately.

i'd say just install blackarch on top of regular arch, then you can just disable the repo till it fixes itself :p

**Comment by aldayrruiz** [comment]
> I encountered this issue too. Two days ago, I solved it by using new strap.sh.But I encounter it again. Today, I added arch4edu,then I executed my first`sudo pacman -Syyu` in the day,I encountered it. In /etc/pacman.conf, I can add
> 
> ```
> [blackarch]
> SigLevel=Never
> Include = /etc/pacman.d/blackarch-mirrorlist
> ```
> 
> to skip this error temporarily,but I don't think this is good solution can be used for long.

Yes, that avoid signing, and it works, obviously... but this is a problem that comes from 2018. How is that posible?

**Comment by BICH0** [comment]
You can fix it pushing the Levon signature to trusted keys of the blackarch-keyring and repopulating the pacman-key, its not a perfect solution but i think its better than disabling package signing for a whole repository, you can achieve this executing the following commands as root:
```
echo "F9A6E68A711354D84A9B91637533BAFE69A25079:4:" >> /usr/share/pacman/keyrings/blackarch-trusted
pacman-key --populate
```
I hope this gets solved soon

**Comment by LiamBaniAdam** [comment]
Another way is to execute this command 

`gpg --refresh-keys`

And then Follow these instructions from the [official site](https://blackarch.org/faq.html): 

```
# Run https://blackarch.org/strap.sh as root and follow the instructions.
$ curl -O https://blackarch.org/strap.sh

# Verify the SHA1 sum
$ echo 26849980b35a42e6e192c6d9ed8c46f0d6d06047 strap.sh | sha1sum -c

# Set execute bit
$ chmod +x strap.sh

# Run strap.sh
$ sudo ./strap.sh

# Enable multilib following https://wiki.archlinux.org/index.php/Official_repositories#Enabling_multilib and run:
$ sudo pacman -Syu
```
