### ISSUE TITLE
INSTALLATION DONE, CANNOT DO ANYTHING

### ISSUE THREAD

**Issue by EXTER001** [BlackArch/blackarch#4072]
The installation was 100% successful, but when I boot and log Blackarch, I have a blue screen, left mouse button working well, propose me terminals, browsers network, blacharch, fluxbox menu. But when I click on anything, nothing happen. Cannot even log out or reboot.

The interface I got is a fade blue screen with the date working very well bottom right and the number of the active desktop on bottom left.

I can change the active desktop from 1 to 4 but nothing happen at all when launching even a simple terminal.

If I log with a alt account or with root it's the same problem. 

The screen logging is working very well with the black hat guy.

**Comment by dualfade** [comment]
Have you tried logging into another TTY and install another terminal ? Or just use Fluxbox run command to launch anything ?

**Comment by noraj** [comment]
So everything works, you just don't like the window manager (and I agree with you). But you are free to install any other [WM](https://wiki.archlinux.org/title/Window_manager) or [DE](https://wiki.archlinux.org/title/Desktop_environment).
