### ISSUE TITLE
pev: error while loading shared libraries: libpe.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by astro-angelfish** [BlackArch/blackarch#4073]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

While trying to use `pev` related command, an error occurred because of lack of `libpe.so.1` file. Seems like a partial installation of `pev` or `readpe` there.
According to their [README](https://github.com/mentebinaria/readpe#how-to-install-on-linux), adding or running following commands in PKGBUILD should fix, but is there any solution better instead of a post-installation hook?
```
echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/libpe.conf
sudo ldconfig
```

### Steps to reproduce

- Do an aborted `sudo pacman -Syu`
- Reinstall everything via `pacman -Qqn | sudo pacman -S - --overwrite='*'`
- Try command like `peres`, the command fails.

**Actual result:** peres: error while loading shared libraries: libpe.so.1: cannot open shared object file: No such file or directory

**Expected result:** peres should run normally, at least it should give me a help output.

### Screenshots

N/A

### Info for developers

**Device:** Hasee TX6-CU5DS with 16GB memory.
**GNU/Linux distribution:** Arch Linux
**Tool version:** pev 0.81-1

### Debug log

peres: error while loading shared libraries: libpe.so.1: cannot open shared object file: No such file or directory

**Comment by D3vil0p3r** [comment]
@astro-angelfish I checked. It works again. Can you do a double check so we can close this issue?

**Comment by astro-angelfish** [comment]
Seems OK on my laptop. Closing this issue for now.
