### ISSUE TITLE
zarn

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#4074]
- **Name**: zarn
- **Source URL**: https://github.com/htrgouvea/zarn
- **Description**: perl SAST

dependencies (https://github.com/htrgouvea/zarn/blob/main/cpanfile)

- JSON -> probably `extra/perl-json`
- File::Find::Rule -> `extra/perl-file-find-rule`
- Getopt::Long -> `blackarch/perl-getopt-long`
- `YAML::Tiny` -> `extra/perl-yaml-tiny`
- `PPI::Document` -> doesn't look packaged yet

**Comment by D3vil0p3r** [comment]
`PPI::Document` is contained in [extra/perl-ppi](https://man.archlinux.org/man/extra/perl-ppi/PPI::Document::File.3pm.en). If confirmed, we can start to package `zarn`.

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4379
