### ISSUE TITLE
Passgan

### ISSUE THREAD

**Issue by Sturridge32** [BlackArch/blackarch#4076]
- **Name**:
- **Source URL**:
- **Description**:

Please consider making a Pull Request (PR). Here are some helpful resources:

- AL PKGBUILD guide: https://wiki.archlinux.org/index.php/PKGBUILD
- BA PKGBUILD templates: https://github.com/BlackArch/blackarch-pkgbuilds

**Comment by noraj** [comment]
@Sturridge32 Make the effort of filling the template please.
