### ISSUE TITLE
Birp tool not working 

### ISSUE THREAD

**Issue by pentagramz** [BlackArch/blackarch#4080]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
Birp tool is throwing error after connecting to mainframe IP
Describe here the issue that you are experiencing.

after connecting to IP showing py3270 error please fix it 
### Steps to reproduce

- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Info for developers

**Device:** Manufacturer Model XVI (Only if you consideer needed, for example, network cards)
**GNU/Linux distribution:** (If you are using one distro that is not BlackArch, example: Manjaro, Anarchy, etc)
**Tool version:** 0.0.0

**Comment by pentagramz** [comment]
<img width="644" alt="birp" src="https://github.com/BlackArch/blackarch/assets/7072014/daaac2b2-a9bc-49fc-b0a6-ac150d9c019b">

**Comment by noraj** [comment]
upstream birp has not been updated for 7 years https://github.com/sensepost/birp

it relies on deprecated python 2, the patch may requires a change

https://github.com/BlackArch/blackarch/blob/master/packages/birp/py3270wrapper.py.patch

**Comment by D3vil0p3r** [comment]
I don't get that error on Connection Failure. Btw @noraj should we add this tool on broken list due to Python 2 and abandoned project?
