### ISSUE TITLE
x3270 not working

### ISSUE THREAD

**Issue by pentagramz** [BlackArch/blackarch#4081]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
x3270 not working
libssl.so.1.1 error

### Steps to reproduce

- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Info for developers

**Device:** Manufacturer Model XVI (Only if you consideer needed, for example, network cards)
**GNU/Linux distribution:** (If you are using one distro that is not BlackArch, example: Manjaro, Anarchy, etc)
**Tool version:** 0.0.0

**Comment by noraj** [comment]
it's version 4.1ga12 right now

https://github.com/BlackArch/blackarch/blob/d735abb10b42ec15302080269eb190259783f8e0/packages/x3270/PKGBUILD#L6

and should be updated to 4.3ga4

https://x3270.miraheze.org/wiki/Downloads

**Comment by D3vil0p3r** [comment]
This issue can be closed @noraj The error reported has been fixed.

**Comment by noraj** [comment]
fixed in https://github.com/BlackArch/blackarch/commit/c7225f36c988b4341283ea26d1fcb69106143452
