### ISSUE TITLE
levye -> crowbar

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#4087]
levye has been renamed crowbar, the old repo https://github.com/galkan/levye no longer exist so need to migrate to https://github.com/galkan/crowbar

fields to update:

- url
- source
- check if depends or `package()` need updates
- change license to `license=('MIT')`

**Comment by saltasatelites** [comment]
The 'new' repository has not had any updates in the last 4 years and is just another brute force tool of which there are already hundreds.

**Comment by ikstream** [comment]
I think we should add/change it nevertheless to allow an (easier) transition from Kali to BA and keep these video guides made for Kali also work on BA
