### ISSUE TITLE
Implementation of a tool

### ISSUE THREAD

**Issue by Edu0x01** [BlackArch/blackarch#4091]
Good morning, I would like to try to implement my tool.

It's called Lrod and is used to help bug hunters and pentesters during reconnaissance.

**Characteristics:**

☑ Enumeration of subdomains using passive techniques (such as "subfinder")
☑ Lots of extra queries to enumerate DNS
☑ Domain Zone Transfer Attack
☑ WAF type detection
☑ Common enumeration (CMSs, reverse proxies, jquery...)
☑ Target domain "Whois"
☑ Subdomain Acquisition Checker
☑ Check common open ports
☑ Checks active subdomains (like "httprobe")
☑ Wayback machine support for enumerating endpoints (like "waybackurls")
☑ Email Collection

**Pendency:**

Compare the results with other tools like subfinder, gau, httprobe...
Improve existing code and functions

**Third part:**

The tool uses different services to obtain subdomains in different ways
The WAF detector has been modified and adapted from the CRLFSuite concept <3
All DNS queries use dns-python 100%, no digging or any extra tools required
Email collection functions are done using Hunter.io API with personal token (free registration)

Abs, **Eduardo Barbosa**

https://gitlab.com/Edu0x01/Lrod

![Screenshot at Feb 28 08-39-16](https://github.com/BlackArch/blackarch/assets/92599201/f02f8e3d-710b-4376-8c1d-81cc3c9dff40)

![Screenshot at Feb 28 08-40-21](https://github.com/BlackArch/blackarch/assets/92599201/a55847ae-2f99-4a29-9973-c8577a45a53b)

**Comment by Edu0x01** [comment]
Hello, I just renamed the tool to Lrod... I believe it makes the process easier

https://gitlab.com/Edu0x01/Lrod

**Comment by noraj** [comment]
> Good morning, I would like to try to implement my tool.

I you want to try to create a PKGBUILD for your tool, you can find resources at https://gist.github.com/noraj/5045be32490f1161161e16fc5820066c, especially the PKGBUILD templates and guides.

**Comment by Edu0x01** [comment]
Hi Noraj, any news about the implementation?
Do I need to do or change something?

**Comment by noraj** [comment]
As far as I understand, you offered to create the PKGBUILD for your own tool:

> Good morning, I would like to try to implement my tool.

**Comment by D3vil0p3r** [comment]
Good morning, I would like to try to implement your tool. (joking)

https://github.com/BlackArch/blackarch/pull/4282
