### ISSUE TITLE
ExtremeDumper

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#4095]
- **Name**:
- **Source URL**: https://github.com/wwh1004/ExtremeDumper
- **Description**: .NET Assembly Dumper

**Comment by saltasatelites** [comment]
No updates for two years. It seems an abandoned project.

**Comment by noraj** [comment]
Anyway, it's mostly useless to package .NET app on a Linux distro, the only case is if you want to cross-compile a build for windows to have a binary ready to drop on a target.
