### ISSUE TITLE
blackarch install problem - 

### ISSUE THREAD

**Issue by notbob11** [BlackArch/blackarch#4106]
Type: Question

## Question
Hey
I just installed blackarch to a new micro-sd card  with the net install method. I created EFI, swap, and root filesystems with the partitioner. I opted to install all the window managers. After rebooting, the blackarch right click menu did nothing. Would not start browser, or terminal. I can change some of the settings in the fluxbox menu, though.

Next, at the login screen, I pressed alt-ctl-f2 to log in as root. I had to manually configure the ethernet connection before running pacman -Syyu. 

Then I ran pacman -S blackarch, and chose the default on each option to download from, and also chose all tools.

This downloaded a zillion packages. Then the keys were verified with no errors. Then the packages themselves were checked. 

After deleting 30 or 40 corrupted or invalid packages,, and assuming all 6000+ packages would be the same. I bailed.

What is going on? Why would the install leave me with an unfinished system? Why are 

I am starting to think arch is too much for me.

**Comment by noraj** [comment]
Please install only the tools you need rather than all the packages (`blackarch` group).

**Comment by notbob11** [comment]
> you will NEVER be able to install all of them at once

I am slow and easily confused, but, why is it an option then? If it is a common issue, one would think steps would be taken to rectify it. 

As a new blackarch user, I must have missed when it was on the issue tracker, and I now have been suitably chastised for my foolishness.

I will slowly add tools and so forth as needed, as I have already learned that advice is good. 

Thanks

**Comment by noraj** [comment]
> I am slow and easily confused, but, why is it an option then? If it is a common issue, one would think steps would be taken to rectify it.

That why the command to install the whole blackarch group has been remove from the website: https://github.com/BlackArch/blackarch-site/pull/152/files, here is listed a few amount of similar issues: https://github.com/BlackArch/blackarch-site/pull/152#issuecomment-1184563719. As there are 2800+ tools and 2-3 times more dependencies and we are very, very few to maintain all this, it's almost guaranteed than one package is broken, so trying to install all packages will fails 100% of the time.

> I will slowly add tools and so forth as needed, as I have already learned that advice is good.

Yes please do that, it will also save you ton of space, have faster updates, etc.
