### ISSUE TITLE
Problem update

### ISSUE THREAD

**Issue by tweeksss** [BlackArch/blackarch#4117]
I did not solve the problem with updates and put slim and netinstall and full, if there were fewer problems with full, then with the rest it's a horror, your solution does not work when running sudo./strap.sh an error pops up in slim, I won't say anything about netinstall at all, by a miracle I was able to use the executable file on full and to update through crutches, in general, they could have already posted working images during this time and not forced to dance with a tambourine around a laptop, the further the scarier the images -.-

**Comment by noraj** [comment]
This is an issue tracker, not a rant forum.
