### ISSUE TITLE
error: GPGME error: No data

### ISSUE THREAD

**Issue by v1ncenz0graw** [BlackArch/blackarch#4123]
Type: Question

## Question
i entered sudo pacman -Syu     in order to update  after BlackArch slim instalation and i got this error message.

error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
:: Synchronizing package databases...
 core                                                 175.0 KiB   127 KiB/s 00:01 [##############################################] 100%
 extra                                                175.0 KiB   245 KiB/s 00:01 [##############################################] 100%
 community                                            175.0 KiB   427 KiB/s 00:00 [##############################################] 100%
 multilib                                             175.0 KiB   431 KiB/s 00:00 [##############################################] 100%
 blackarch                                              3.9 MiB   580 KiB/s 00:07 [##############################################] 100%
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))

How can i fix it?

**Comment by ikstream** [comment]
Hi, Is your key ring initialised and populated?

**Comment by v1ncenz0graw** [comment]
> Hi, Is your key ring initialised and populated?

It worked. thanks
