### ISSUE TITLE
ERROR - Building grokevt package

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#4124]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

In order to keep PKGBUILDs consistents, I was analyzing some packages if they build correctly.

[grokevt](https://github.com/BlackArch/blackarch/blob/master/packages/grokevt/PKGBUILD) fails during the package process:
```
make: *** No rule to make target 'install'.  Stop.
==> ERROR: A failure occurred in package().
    Aborting...
```
The `make install` refers to the Makefile inside the release folders, but, even if you run the building process in the release folder, for example 0.5.0, the build process fails due to the doc building process that lack of .gz doc files.

The docbook part in Makefile uses `docbook2man` command that does not seem to exist anymore (probably the new one is `db2x_docbook2man` (so its package must be added in the dependency list).

### Steps to reproduce

- `makepkg -src` on grokevt [PKGBUILD](https://github.com/BlackArch/blackarch/blob/master/packages/grokevt/PKGBUILD)

**Comment by saltasatelites** [comment]
Hello.
depends=('python2' 'reglookup' 'cpio')
Needs python2 (deprecated)
