### ISSUE TITLE
Change in mirror URL

### ISSUE THREAD

**Issue by Albonycal** [BlackArch/blackarch#4132]
mirror.albony.xyz is now using the domain https://mirror.albony.in/ 
please change it accordingly 

Thanks

**Comment by noraj** [comment]
https://github.com/BlackArch/blackarch/blob/c1b0816e2b9cb3ca95286bf038c82cabb7161067/mirror/mirror.lst#L38

https://github.com/BlackArch/blackarch-site/blob/dd58461433ece9b8a5846272a0c3fdcd6e4d40fd/blackarch-mirrorlist#L67

**Comment by D3vil0p3r** [comment]
@Albonycal I see your mirror is a little unstable. Sometimes it redirects to https://mirror.nag.albony.in/blackarch/ that is inaccessible and other time to https://mirror.maa.albony.in/blackarch/ that works...

**Comment by Albonycal** [comment]
@noraj Can you please change my mirror's URL in your mirrorlist to mirror.maa.albony.in? 

Sorry for this, 

Thanks

**Comment by D3vil0p3r** [comment]
Done https://github.com/BlackArch/blackarch/pull/4269 Just wait for merging
