### ISSUE TITLE
waybar - git - Blackarch install 

### ISSUE THREAD

**Issue by mairm1340** [BlackArch/blackarch#4136]
Hi All 
I use Hyprland as my main window manager. I was trying blackarch on a VM and I now feel i should run this on my main system.

so I did install sudo pacman -S blackarch

~
❯ sudo pacman -S blackarch
:: There are 2893 members in group blackarch:
:: Repository blackarch
   1) 0d1n  2) 0trace  3) 3proxy  4) 3proxy-win32  5) 42zip  6) a2sv  7) abcd  8) abuse-ssl-bypass-waf  9) acccheck  10) ace  11) aclpwn  
   
   ----<<< Intentionally emitted out the output------>>>>>
   
Enter a selection (default=all):
warning: argon2-20190702-5 is up to date -- reinstalling
warning: bind-9.18.26-2 is up to date -- reinstalling
warning: capstone-5.0.1-3 is up to date -- reinstalling
warning: ddrescue-1.28-1 is up to date -- reinstalling
warning: iputils-20240117-1 is up to date -- reinstalling
warning: nmap-7.94-2 is up to date -- reinstalling
warning: open-iscsi-2.1.9-2 is up to date -- reinstalling
warning: socat-1.8.0.0-1 is up to date -- reinstalling
warning: tcpdump-4.99.4-1 is up to date -- reinstalling
warning: testdisk-7.2-1 is up to date -- reinstalling
warning: traceroute-2.1.5-1 is up to date -- reinstalling
resolving dependencies...
:: There are 5 providers available for java-environment:
:: Repository extra
   1) jdk-openjdk  2) jdk11-openjdk  3) jdk17-openjdk  4) jdk21-openjdk  5) jdk8-openjdk

Enter a number (default=1): 1
:: There are 2 providers available for libmariadbclient:
:: Repository extra
   1) mariadb-libs  2) mariadb-lts-libs

Enter a number (default=1): 1
warning: cannot resolve "python-boto", a dependency of "aws-extender-cli"
:: There are 2 providers available for java-runtime=11:
:: Repository extra
   1) jdk11-openjdk  2) jre11-openjdk

Enter a number (default=1): 1
:: There are 3 providers available for mysql:
:: Repository extra
   1) mariadb  2) mariadb-lts  3) percona-server

Enter a number (default=1): 1
:: There are 128 providers available for tessdata:
:: Repository extra
   1) tesseract-data-afr  2) tesseract-data-amh  3) tesseract-data-ara  4) tesseract-data-asm  5) tesseract-data-aze  6) tesseract-data-aze_cyrl  7) tesseract-data-bel  8) tesseract-data-ben  9) tesseract-data-bod  10) tesseract-data-bos

  <<<< output emitted>>>>

  128) tesseract-data-yor

Enter a number (default=1): 1
:: There are 5 providers available for opencl-driver:
:: Repository extra
   1) intel-compute-runtime  2) opencl-clover-mesa  3) opencl-nvidia  4) opencl-rusticl-mesa  5) rocm-opencl-runtime

Enter a number (default=1):
:: There are 2 providers available for qt6-multimedia-backend:
:: Repository extra
   1) qt6-multimedia-ffmpeg  2) qt6-multimedia-gstreamer

Enter a number (default=1): 1
:: The following package cannot be upgraded due to unresolvable dependencies:
      aws-extender-cli

:: Do you want to skip the above package for this upgrade? [y/N] y
looking for conflicting packages...
:: openbsd-netcat-1.226_1-2 and gnu-netcat-0.7.1-9 are in conflict. Remove gnu-netcat? [y/N] y
:: spdlog-1.14.1-1 and spdlog-git-1.13.0.r39.g8fed530b-1 are in conflict. Remove spdlog-git? [y/N] y
:: yay-12.3.5-1 and yay-git-12.3.5.r6.g779a9f1-1 are in conflict. Remove yay-git? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: removing spdlog-git breaks dependency 'libspdlog.so=1.13-64' required by waybar-git

I did run pactree command to see who is using the above

~
❯ pactree -r spdlog
spdlog-git provides spdlog
└─waybar-git

~
❯ pactree -r yay
yay-git provides yay

~
❯ pactree -r waybar-git
waybar-git

Since I run hyprland and I need waybar how can I get blackarch on my system.

**Appreciate your assistance on this.**

**Comment by mairm1340** [comment]
If I keep spdlog-git even then i cannot proceed....


:: Do you want to skip the above package for this upgrade? [y/N] y
looking for conflicting packages...
:: openbsd-netcat-1.226_1-2 and gnu-netcat-0.7.1-9 are in conflict. Remove gnu-netcat? [y/N] y
:: spdlog-1.14.1-1 and spdlog-git-1.13.0.r39.g8fed530b-1 are in conflict. Remove spdlog-git? [y/N] n
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: spdlog-1.14.1-1 and spdlog-git-1.13.0.r39.g8fed530b-1 are in conflict

**Comment by ikstream** [comment]
Don’t do `pacman-Syu`! You are trying to install nearly 3k packages. Ofcourse there will be issues. Install the packages you want.
Java uninstall jdk and sdk, reinstall the jdk and you’re good to go.
Netcat you have to uninstall one and install the other, not sure which one.
If you use AUR packages, or non blackarch repo packages you are on your own. We don’t maintain any *-git packages as far as I know.

**Comment by mairm1340** [comment]
I am able to install one package at a time...
is there a way to install the commonly used one at one go ?

**Comment by ikstream** [comment]
Download this file and cat it into pacman. This will install the slim tools in one go

**Comment by mairm1340** [comment]
i fail to see the attachment... :(

**Comment by mairm1340** [comment]
i did download the package file 
then I did use the below script

#!/bin/bash

# Read each package name from the package list file and install it
while IFS= read -r package; do
    echo "Installing $package..."
    sudo pacman -S --noconfirm "$package"
    echo "Done installing $package."
done < package_list.txt

echo "All packages have been installed."


obviously we need to make it executable and run !

**Comment by ikstream** [comment]
I don’t know why the link did not work, but it is the file I was talking about.
That’s a quite complex way to do it, but if it works for you.
