### ISSUE TITLE
[update]: Package fluxion out of date

### ISSUE THREAD

**Issue by victorkamoto** [BlackArch/blackarch#4137]
The version in blackarch repositories is 3:1571.4f461a4-2
The latest release on the repo is 4.10 (2018). There are also recent commits not part of a release. (9months)

![image](https://github.com/BlackArch/blackarch/assets/43573646/597d5423-1176-4bc7-8dc1-484086e869bd)

https://github.com/FluxionNetwork/fluxion

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4284
