### ISSUE TITLE
issue system not booting

### ISSUE THREAD

**Issue by MINFM** [BlackArch/blackarch#4138]
Hello folks

I was installing Black Arch on a virtual machine but when it was done I rebooted the machine and it showed:

ERROR: device '/dev/mapper/r00t' not found. Skipping fsck.
mount: /new_root: no filesystem type specified.
You are now being dropped into an emergency shell.
sh: can't access tty; job control turned off

I can not even type anything in the shell for some reason
what can the problem be and how can it get solved? do I need to reinstall the system?

**Comment by ikstream** [comment]
Which hypervisor did you use?

you can start a live iso, mount your partition(s) and check `/etc/fstab` if the correct values are registered in there. If it isn’t, adjust accordingly.

**Comment by MINFM** [comment]
> Which hypervisor did you use?
> 
> you can start a live iso, mount your partition(s) and check `/etc/fstab` if the correct values are registered in there. If it isn’t, adjust accordingly.


It turned out because I did not give the machine enough storage
I gave it only 47 gigabytes while it will take more than 60 gigabytes
I reacreated the machine with 74 gigabytes of storsge and after that I removed the 21 gigabytes iso attachment and now it worked
Thanks anyway
