### ISSUE TITLE
Dependencies on PEP517 Python packages

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#4139]
## Question

On PKGBUILD with PEP517 template like [python-thinc](https://github.com/BlackArch/blackarch/blob/master/packages/python-thinc/PKGBUILD), since in `package()` the `pip install` command is run, I guess it will install all the dependencies specified in `pyproject.toml` file. At this point, is there a sense to still specify dependencies in `depends` variable of PKGBUILD if they are already installed by `pip install`?

**Comment by micwoj92** [comment]
`--no-deps` is specified, which ignores dependencies of package. It would be much cleaner IMO to install packages python-installer instead of PIP.
```
package() {
    cd $_name-$pkgver
    python -m installer --destdir="$pkgdir" dist/*.whl
}
```
AUR package does it this way. https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-thinc

**Comment by noraj** [comment]
ref. https://wiki.archlinux.org/title/Python_package_guidelines#Standards_based_(PEP_517)

**Comment by micwoj92** [comment]
Why was this closed as completed? I don't see this being addressed.

**Comment by D3vil0p3r** [comment]
I would move in a [discussion](https://github.com/BlackArch/blackarch/discussions), not here.
