### ISSUE TITLE
failed retrieving file 'blackarch.db' from ftp.halifax.rwth-aachen.de 

### ISSUE THREAD

**Issue by BALVEY7** [BlackArch/blackarch#4147]
`
[arch@archlinux ~]$ sudo pacman -Syyu
:: Synchronizing package databases...
 core                                                    119.8 KiB   255 KiB/s 00:00 [-------------------------------------------------] 100%
 extra                                                     7.8 MiB  1305 KiB/s 00:06 [-------------------------------------------------] 100%
 multilib                                                138.5 KiB   343 KiB/s 00:00 [-------------------------------------------------] 100%
 blackarch.db failed to download
error: failed retrieving file 'blackarch.db' from ftp.halifax.rwth-aachen.de : Failed to connect to ftp.halifax.rwth-aachen.de port 443 after 10002 ms: Timeout was reached
error: failed to synchronize all databases (download library error)
[arch@archlinux ~]$ 

`
This is the issue i am receiving any help would be appriciated

**Comment by noraj** [comment]
Just change of mirror.
