### ISSUE TITLE
python-pyppeteer <-> python-playwright

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#4151]
## Question

As reported in [pyppeteer](https://github.com/pyppeteer/pyppeteer) repository, is it possible to replace `python-pyppeteer` by `python-playwright` on the dependency list of the impacted packages that use `python-pyppeteer`?

**Comment by noraj** [comment]
It's not a drop-in replacement, just an alternative. It's up to the upstream project to maker the move.
