### ISSUE TITLE
Conflicto de paquetes "jdk-openjdk y jre-openjdk"

### ISSUE THREAD

**Issue by DajhanChi** [BlackArch/blackarch#4175]
Type: Question
Utilice el comando "pacman -Syu --needed --overwrite='*' blackarch" y me arroja lo siguiente, dandome error al final por conflicto de paquetes, u o me permite actualizar que podria hacer para actualiuzar correctamente la distro??

En esta ocacion le marque todo si, pero en otras ocaciones tambien marque todo no y me arroja el mismo error...
Adjunto lo que me arroja:

Iniciando actualización completa del sistema...
:: ¿Remplazar appstream-qt con extra/appstream-qt5? [S/n] s
:: ¿Remplazar dbus-python con extra/python-dbus? [S/n] s
:: ¿Remplazar kactivities con extra/kactivities5? [S/n] s
:: ¿Remplazar kactivities con extra/plasma-activities? [S/n] s
:: ¿Remplazar karchive con extra/karchive5? [S/n] s
:: ¿Remplazar kauth con extra/kauth5? [S/n] s
:: ¿Remplazar kbookmarks con extra/kbookmarks5? [S/n] s
:: ¿Remplazar kcodecs con extra/kcodecs5? [S/n] s
:: ¿Remplazar kcompletion con extra/kcompletion5? [S/n] s
:: ¿Remplazar kconfig con extra/kconfig5? [S/n] s
:: ¿Remplazar kconfigwidgets con extra/kconfigwidgets5? [S/n] s
:: ¿Remplazar kcoreaddons con extra/kcoreaddons5? [S/n] s
:: ¿Remplazar kcrash con extra/kcrash5? [S/n] s
:: ¿Remplazar kdbusaddons con extra/kdbusaddons5? [S/n] s
:: ¿Remplazar kdeclarative con extra/kdeclarative5? [S/n] s
:: ¿Remplazar kded con extra/kded5? [S/n] s
:: ¿Remplazar kglobalaccel con extra/kglobalaccel5? [S/n] s
:: ¿Remplazar kguiaddons con extra/kguiaddons5? [S/n] s
:: ¿Remplazar ki18n con extra/ki18n5? [S/n] s
:: ¿Remplazar kiconthemes con extra/kiconthemes5? [S/n] s
:: ¿Remplazar kio con extra/kio5? [S/n] s
:: ¿Remplazar kitemviews con extra/kitemviews5? [S/n] s
:: ¿Remplazar kjobwidgets con extra/kjobwidgets5? [S/n] s
:: ¿Remplazar knotifications con extra/knotifications5? [S/n] s
:: ¿Remplazar kpackage con extra/kpackage5? [S/n] s
:: ¿Remplazar kservice con extra/kservice5? [S/n] s
:: ¿Remplazar ktextwidgets con extra/ktextwidgets5? [S/n] s
:: ¿Remplazar kwallet con extra/kwallet5? [S/n] s
:: ¿Remplazar kwayland con extra/kwayland5? [S/n] s
:: ¿Remplazar kwidgetsaddons con extra/kwidgetsaddons5? [S/n] s
:: ¿Remplazar kwindowsystem con extra/kwindowsystem5? [S/n] s
:: ¿Remplazar kxmlgui con extra/kxmlgui5? [S/n] s
:: ¿Remplazar plasma-framework con extra/libplasma? [S/n] s
:: ¿Remplazar plasma-framework con extra/plasma-framework5? [S/n] s
:: ¿Remplazar solid con extra/solid5? [S/n] s
:: ¿Remplazar sonnet con extra/sonnet5? [S/n] s
resolviendo dependencias...
:: Existen 2 proveedores disponibles para dbus-units:
:: Repositorio core
   1) dbus-broker-units  2) dbus-daemon-units

Introduzca un número (por omisión=1): 
:: Existen 2 proveedores disponibles para qt6-multimedia-backend:
:: Repositorio extra
   1) qt6-multimedia-ffmpeg  2) qt6-multimedia-gstreamer

Introduzca un número (por omisión=1): 
buscando conflictos entre paquetes...
error: se han detectado paquetes con conflictos sin resolver
error: no se pudo preparar la operación (dependencias en conflicto)
:: jdk-openjdk y jre-openjdk están en conflicto

**Comment by DajhanChi** [comment]
Me podrian ayudar por favor,,,se les agradese de antemano

**Comment by ikstream** [comment]
Not an BlackArch issue.
https://archlinux.org/news/incoming-changes-in-jdk-jre-21-packages-may-require-manual-intervention/

Please use English for requests and refrain from installing all tools at once.
Where did you get the command `pacman -S blackarch` from?

**Comment by DajhanChi** [comment]
I took the command from the main blackarch page in the questions section

**Comment by DajhanChi** [comment]
[How can I fetch/install the latest update available?](https://blackarch.org/faq.html#collapseThree)
By simply running pacman -Syu --needed --overwrite='*' blackarch. This command requires root privileges.

**Comment by DajhanChi** [comment]
I am new to this community, and also using this system, and it is the first time that I encounter this conflict, I come from Ubuntu...thank you very much for your help...

**Comment by DajhanChi** [comment]
Could you guide me to do a correct update of the blackarch system?

**Comment by ikstream** [comment]
Especially if you are new to arch please be aware, that it is a rolling distribution and requires regular updates (twice a month is a good rhythm, once a month should be minimum). To upgrade your system use `pacman -Syu`. 
Avoid partial upgrades. In general you can follow the [arch wiki for instructions]( https://wiki.archlinux.org/title/system_maintenance#Upgrading_the_system) as blackarch uses archlinux as base and adds only the repository with security tools. 

The command you used will try to install all tools at once. 
Thanks for letting me know where you found it, we will fix that.
