### ISSUE TITLE
python-pywebcopy: wrong dependencies?

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#4181]
Why [python-pywebcopy](https://github.com/BlackArch/blackarch/blob/master/packages/python-pywebcopy/PKGBUILD) dependencies in BA PKGBUILD are different from the ones specified upstream in https://github.com/rajatomar788/pywebcopy/blob/master/requirements.txt ?

Note also that the dependency lxml and lxml-html-clean are now separated project so lxml dependency must be replaced by [python-lxml-html-clean](https://archlinux.org/packages/extra/any/python-lxml-html-clean/).

**Comment by noraj** [comment]
> Why [python-pywebcopy](https://github.com/BlackArch/blackarch/blob/master/packages/python-pywebcopy/PKGBUILD) dependencies in BA PKGBUILD are different from the ones specified upstream in https://github.com/rajatomar788/pywebcopy/blob/master/requirements.txt ?

Because the package is outdated I guess? Seems that previous versions updstream were requiring way more dependencies: https://github.com/rajatomar788/pywebcopy/commit/9a5080d37f1225f786ad5817a7dbd205dfd674a0#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552

> Note also that the dependency lxml and lxml-html-clean are now separated project so lxml dependency must be replaced by [python-lxml-html-clean](https://archlinux.org/packages/extra/any/python-lxml-html-clean/).

I don't think so, upstream is still requiring [lxml](https://pypi.org/project/lxml/) and not [lxml-html-clean](https://pypi.org/project/lxml-html-clean/). And nothing says on lxml-html-clean README that it is a 100% compatible drop-in replacement of lxml. Maybe upstream could change, but we can't change until upstream change.

@D3vil0p3r Would you like to make the changes to update the dependencies and more generally the PKGBUILD if needed?

**Comment by D3vil0p3r** [comment]
Sure... what I start to note by running the python module in non-Arch systems with `lxml` and not `lxml-html-clean`, when I use the module I get the error:
```
Traceback (most recent call last):
  File "/home/athena/Downloads/test.py", line 4, in <module>
    wp = config.create_page()
         ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8qjbn3zr43azi40bfqgbn6n0yzm229lj-python3.12-pywebcopy-7.0.2/lib/python3.12/site-packages/pywebcopy/configs.py", line 241, in create_page
    from .core import WebPage
  File "/nix/store/8qjbn3zr43azi40bfqgbn6n0yzm229lj-python3.12-pywebcopy-7.0.2/lib/python3.12/site-packages/pywebcopy/core.py", line 12, in <module>
    from .elements import HTMLResource
  File "/nix/store/8qjbn3zr43azi40bfqgbn6n0yzm229lj-python3.12-pywebcopy-7.0.2/lib/python3.12/site-packages/pywebcopy/elements.py", line 24, in <module>
    from .parsers import iterparse
  File "/nix/store/8qjbn3zr43azi40bfqgbn6n0yzm229lj-python3.12-pywebcopy-7.0.2/lib/python3.12/site-packages/pywebcopy/parsers.py", line 14, in <module>
    from lxml.html.clean import Cleaner
  File "/nix/store/v4vgibrhyyk5r3rfvh7jbjyqkw2gk4qw-python3.12-lxml-5.2.2/lib/python3.12/site-packages/lxml/html/clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.
```
I need to check if this error is produced also for Arch distros.

**Comment by noraj** [comment]
I that the case on AL too, please ask upstream to add [lxml-html-clean](https://pypi.org/project/lxml-html-clean/) as a dependency in requirements.txt. And if lxml is unneeded to remove it.

**Comment by D3vil0p3r** [comment]
https://github.com/rajatomar788/pywebcopy/pull/130 https://github.com/BlackArch/blackarch/pull/4183
