### ISSUE TITLE
error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid

### ISSUE THREAD

**Issue by naveenkumar-cyber** [BlackArch/blackarch#4187]
Type: Question

## error: blackarch: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid
i have tried all the possible ways but not able to resolve this issue after update, and there are lots of tool is missing after upgrade please help me get rid of this issue

**Comment by anunna** [comment]
You should look at closed issues for the same topic to avoid repeating the same topic.

#4061
