### ISSUE TITLE
Sherlock pkgbuild should be updated to reflect new versioning scheme

### ISSUE THREAD

**Issue by ppfeister** [BlackArch/blackarch#4191]
Not really a bug, not really a tool request...so here we are at discussion.

Sherlock [[upstream]](https://github.com/sherlock-project/sherlock) [[pkgbuild]](https://github.com/BlackArch/blackarch/blob/55abb0751c32e11ad84468f42fa0423c84d36543/packages/sherlock/PKGBUILD) was added quite a while ago, at which point the only true source of version info was found in the code itself. Not very conducive to consistent packaging. Due to this, Sherlock is packaged here on a rolling basis, similar to other distros (at the time).

Recently, Sherlock has adopted properly tagged releases somewhat styled after semver (not entirely, but similar). Most other repositories have adjusted [[repology]](https://repology.org/project/sherlock-social-osint/versions). Not only does this make for easier mental parsing of version information, it allows for much more consistent user experiences across platforms.

If able and compliant with the Black Arch standard, Sherlock's pkgbuild should be converted to use the now-available releases rather than the HEAD of master.

**Comment by noraj** [comment]
The PKGBUILD needs an overall update
