### ISSUE TITLE
package android-ndk is broken

### ISSUE THREAD

**Issue by unknowndevQwQ** [BlackArch/blackarch#4192]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

/opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/*/bin is broken symlink file

### Screenshots

```
ls -ahl /opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/aarch64-linux-android/bin 
total 12K
drwxr-xr-x 2 root root 4.0K Aug 30 01:57 .
drwxr-xr-x 3 root root 4.0K Aug 30 01:57 ..
lrwxrwxrwx 1 root root  131 Feb 26  2022 as -> /buildbot/src/android/ndk-release-r23/out/linux/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-as
```

### Info for developers

**GNU/Linux distribution:** arch
**Tool version:** r23

~#2765~

**Comment by noraj** [comment]
let's see if #4198 fix this

**Comment by D3vil0p3r** [comment]
I don't see any broken link anymore. @noraj can you check and eventually close the issue? Thanks

**Comment by noraj** [comment]
@D3vil0p3r please stop mentioning me in every issue mate 😂, especially those where I'm already in the participants  

I have already subscribed to all activities and will get a notification anyway. Mentionning me directly only adds a mobile notification, which becomes anoyings with the number of mentions.
![image](https://github.com/user-attachments/assets/ba9efafd-d8b9-421a-9a80-6cc73e7659c7)

Right now I'm super busy, I can't take the time to take a look at it

**Comment by noraj** [comment]
```
➜ tar -tvf 'android-ndk-2:r27-1-x86_64.pkg.tar.zst' --force-local | grep '\->'                                                                                                                                       
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/shader-tools/linux-x86_64/libc++.so -> ../../toolchains/llvm/prebuilt/linux-x86_64/lib/libc++.so                                                     
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -> clang-18                                                                                          
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -> clang
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/ld -> ld.lld
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld -> lld
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/ld64.lld -> lld
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/lld-link -> lld
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-addr2line -> llvm-symbolizer
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-dlltool -> llvm-ar
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-lib -> llvm-ar
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib -> llvm-ar
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-readelf -> llvm-readobj
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip -> llvm-objcopy
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-windres -> llvm-rc
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/wasm-ld -> lld
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/i386-unknown-linux-gnu/libc++.so.1 -> libc++.so
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/i386-unknown-linux-gnu/libc++abi.so.1 -> libc++abi.so
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/libc++.a -> x86_64-unknown-linux-gnu/libc++.a
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/libc++.so -> x86_64-unknown-linux-gnu/libc++.so
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/libc++.so.1 -> x86_64-unknown-linux-gnu/libc++.so.1
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/libc++abi.a -> x86_64-unknown-linux-gnu/libc++abi.a
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/libc++abi.so.1 -> x86_64-unknown-linux-gnu/libc++abi.so.1
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/libunwind.so -> x86_64-unknown-linux-gnu/libunwind.so
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/libxml2.so -> libxml2.so.2
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/python3.11/site-packages/lldb/_lldb.cpython-311-x86_64-linux-gnu.so -> ../../../liblldb.so
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/python3.11/site-packages/lldb/lldb-argdumper -> ../../../../bin/lldb-argdumper
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/x86_64-unknown-linux-gnu/libc++.so.1 -> libc++.so
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/x86_64-unknown-linux-gnu/libc++abi.so.1 -> libc++abi.so
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/musl/lib/i686-unknown-linux-musl/libc++.so.1 -> libc++.so
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/musl/lib/x86_64-unknown-linux-musl/libc++.so.1 -> libc++.so
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/python3/bin/python3 -> python3.11
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/python3/lib/libpython3.11.so -> libpython3.11.so.1.0
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/python3/lib/pkgconfig/python3-embed.pc -> python-3.11-embed.pc
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/python3/lib/pkgconfig/python3.pc -> python-3.11.pc
lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/python3/share/man/man1/python3.1 -> python3.11.1
```

**Comment by unknowndevQwQ** [comment]
> ```
> ➜ tar -tvf 'android-ndk-2:r27-1-x86_64.pkg.tar.zst' --force-local | grep '\->'                                                                                                                                       
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/shader-tools/linux-x86_64/libc++.so -> ../../toolchains/llvm/prebuilt/linux-x86_64/lib/libc++.so                                                     
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -> clang-18                                                                                          
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -> clang
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/ld -> ld.lld
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld -> lld
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/ld64.lld -> lld
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/lld-link -> lld
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-addr2line -> llvm-symbolizer
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-dlltool -> llvm-ar
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-lib -> llvm-ar
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib -> llvm-ar
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-readelf -> llvm-readobj
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip -> llvm-objcopy
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-windres -> llvm-rc
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/wasm-ld -> lld
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/i386-unknown-linux-gnu/libc++.so.1 -> libc++.so
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/i386-unknown-linux-gnu/libc++abi.so.1 -> libc++abi.so
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/libc++.a -> x86_64-unknown-linux-gnu/libc++.a
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/libc++.so -> x86_64-unknown-linux-gnu/libc++.so
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/libc++.so.1 -> x86_64-unknown-linux-gnu/libc++.so.1
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/libc++abi.a -> x86_64-unknown-linux-gnu/libc++abi.a
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/libc++abi.so.1 -> x86_64-unknown-linux-gnu/libc++abi.so.1
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/libunwind.so -> x86_64-unknown-linux-gnu/libunwind.so
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/libxml2.so -> libxml2.so.2
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/python3.11/site-packages/lldb/_lldb.cpython-311-x86_64-linux-gnu.so -> ../../../liblldb.so
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/python3.11/site-packages/lldb/lldb-argdumper -> ../../../../bin/lldb-argdumper
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/x86_64-unknown-linux-gnu/libc++.so.1 -> libc++.so
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib/x86_64-unknown-linux-gnu/libc++abi.so.1 -> libc++abi.so
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/musl/lib/i686-unknown-linux-musl/libc++.so.1 -> libc++.so
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/musl/lib/x86_64-unknown-linux-musl/libc++.so.1 -> libc++.so
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/python3/bin/python3 -> python3.11
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/python3/lib/libpython3.11.so -> libpython3.11.so.1.0
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/python3/lib/pkgconfig/python3-embed.pc -> python-3.11-embed.pc
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/python3/lib/pkgconfig/python3.pc -> python-3.11.pc
> lrwxrwxrwx root/root         0 2024-10-20 19:56 opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/python3/share/man/man1/python3.1 -> python3.11.1
> ```

```
ld ->ld.lld
lld.ld -> ld
```
Are you serious?

**Comment by noraj** [comment]
> ld ->ld.lld
> lld.ld -> ld

it's lld, so it's not a circular reference

> ld -> ld.lld
> ld.lld -> lld
