### ISSUE TITLE
TInjA – the Template INJection Analyzer

### ISSUE THREAD

**Issue by m10x** [BlackArch/blackarch#4196]
- **Name**: TInjA
- **Source URL**: https://github.com/Hackmanit/TInjA
- **Description**:  TInjA is a CLI tool for testing web pages for template injection vulnerabilities. It supports 44 of the most relevant template engines for eight different programming languages.

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4288
