### ISSUE TITLE
can you add other tools 

### ISSUE THREAD

**Issue by hackeyware** [BlackArch/blackarch#4206]
can you add havoc c2 and villain please good night

**Comment by anunna** [comment]
I have opened requests for both of them on your behalf.

Please ensure that you go through the tool request process when opening a new issue for each tool individually; We require the below requested information. Also consider submitting a PR yourself for the tools with the below packaging guidelines below.

Example below:

- **Name**:
- **Source URL**:
- **Description**:

Please consider making a Pull Request (PR). Here are some helpful resources:

- AL PKGBUILD guide: https://wiki.archlinux.org/index.php/PKGBUILD
- BA PKGBUILD templates: https://github.com/BlackArch/blackarch-pkgbuilds
