### ISSUE TITLE
Rename valhalla to valhallaapi

### ISSUE THREAD

**Issue by derEremit** [BlackArch/blackarch#4209]
My problem.
valhalla from blackarch is trying to replace an aur package valhalla which is an openstreetmap routing engine

Reasoning:

1.
pretty much every package named valhalla in every distro is pointing to the valhalla routing engine
https://repology.org/project/valhalla/versions

2.
the valhalla in blackarch is also called valhallaapi on github
https://github.com/NextronSystems/valhallaAPI

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4289
