### ISSUE TITLE
Opened issue tickets on BA

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#4220]
Type: Discussion

## Discussion

@noraj I see 150 open issues on BA repo. Probably I can find some free time in the near period to manage all these. If you agree, it's ok for me. I would just ask you to review submitted code on PRs when needed.

Thanks

**Comment by noraj** [comment]
Feel free to PR to add new tools. If wanting to fix broken package maybe discuss it before. Anyway we'll rzview your PR.
