### ISSUE TITLE
SavvyCAN

### ISSUE THREAD

**Issue by utenus** [BlackArch/blackarch#4291]
- **Name**: savvycan
- **Source URL**: https://github.com/collin80/SavvyCAN
- **Description**:  QT based cross platform canbus tool

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4293

I would suggest you to learn how to package tools you like in order to be autonomous. Start from [these templates](https://github.com/BlackArch/blackarch-pkgbuilds), use existing BA PKGBUILDs as example, and if you have further doubts, please ask.

**Comment by noraj** [comment]
> I would suggest you to learn how to package tools you like in order to be autonomous. Start from [these templates](https://github.com/BlackArch/blackarch-pkgbuilds), use existing BA PKGBUILDs as example, and if you have further doubts, please ask.

Right, you made 31 requests (https://github.com/BlackArch/blackarch/issues/created_by/utenus%20), are you really using all this tools? If the answer is yes, please read the following guides to learn how to create a PKGBUILD:

- https://wiki.archlinux.org/title/PKGBUILD
- https://wiki.archlinux.org/title/Creating_packages

and help us package the tool you need
