### ISSUE TITLE
Updating blackarch full of bootable drive all errors solved unless brltty.7..... cant find it in mirrors anyone's know where to find it or how to removeit from pkg list original pkg list of full iso 

### ISSUE THREAD

**Issue by Primefenecio** [BlackArch/blackarch#4297]
- **Name**:
- **Source URL**:
- **Description**:

Please consider making a Pull Request (PR). Here are some helpful resources:

- AL PKGBUILD guide: https://wiki.archlinux.org/index.php/PKGBUILD
- BA PKGBUILD templates: https://github.com/BlackArch/blackarch-pkgbuilds

**Comment by anunna** [comment]
Open issues properly with a sensible title and accurate description. Don't use Tool request templates and labels for other issues.
