### ISSUE TITLE
multiple packages cannot be installed due to package duplication with arch linux repository

### ISSUE THREAD

**Issue by astro-angelfish** [BlackArch/blackarch#4299]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

When installing through BlackArch package groups after suffering from #4159, I've found that there still some package installation issues.

For example, I tried `pacman -Syu blackarch-misc --overwrite='*' --needed` but I got multiple package corrupted. And after investigating with `--debug` flag, I found things like these:

```
debug: found cached pkg: /var/cache/pacman/pkg/valabind-1.8.0-4-x86_64.pkg.tar.zst
debug: replacing pkgcache entry with package file for target valabind
debug: opening archive /var/cache/pacman/pkg/valabind-1.8.0-4-x86_64.pkg.tar.zst
debug: starting package load for /var/cache/pacman/pkg/valabind-1.8.0-4-x86_64.pkg.tar.zst
debug: found mtree for package /var/cache/pacman/pkg/valabind-1.8.0-4-x86_64.pkg.tar.zst, getting file list
debug: finished mtree reading for /var/cache/pacman/pkg/valabind-1.8.0-4-x86_64.pkg.tar.zst
debug: sorting package filelist for /var/cache/pacman/pkg/valabind-1.8.0-4-x86_64.pkg.tar.zst
debug: internal package groups mismatch
```

I guess its conflict with upstream Arch Linux repository, and found the [package](https://archlinux.org/packages/extra/x86_64/valabind/) in Arch Linux repository. Removing them might fix but requires further configuration to package groups.

For now I cannot provide full list of conflicts, maybe I could do it later as long as I'm free.

### Steps to reproduce

- Do `sudo pacman -S blackarch-misc` on the top of arch install. (Issue might not be reproducible on ISO install.)
- Confirm the operation
- See the bug

**Actual result:**

`error: failed to commit transaction (invalid or corrupted package)`

**Expected result:**

`:: Processing package changes...`

### Screenshots

N/A. Text should be enough.

### Info for developers

Device: Hasee TX6-CU5DS with 16GB memory.
GNU/Linux distribution: Arch Linux
Tool version: valabind-1.8.0-4, one of the conflicts.

### Link to debug log

They can't even be correctly installed. No log available.

**Comment by noraj** [comment]
> pacman -Syu blackarch-misc --overwrite='*' --needed

Please don't try to install groups, yes there are broken packages, so installing batch of hundreds at once will most often result in errors.

We don't have a `valabind` package, `blackarch/valabind` is a symlink to `extra/valabind`.

It's weird installing `pacman -S blackarch/valabind` have a corruption issue. @noptrix https://github.com/BlackArch/blackarch/issues/4317 had the same issue, it may be generalized, is there a change in some way that would need a rebuild?
