### ISSUE TITLE
Project Monalisa 

### ISSUE THREAD

**Issue by Akash420-oss** [BlackArch/blackarch#4310]
- **Name**: Project-Monalisa
- **Source URL**: https://github.com/Akash420-oss/Project-Monalisa
- **Description**: It is a Networking based Project

- AUR(Arch User Repository): https://aur.archlinux.org/packages/project-monalisa

**Comment by noraj** [comment]
What does the project do? Can you share some usages? Reading the README or your description it's highly unclear.

**Comment by Akash420-oss** [comment]
This Project based on Networking. Actually i've made this project for who those know about how networking protocols are worked and commandline argument just like nmap or any linux tools do. But here you can run the command with "sudo mona" that is it. While run this you have to provide the answers this project ask you some questions like which type of attack you want to choose?, give the target ip or provide the port number etc lots of questions are there but based on that you'll get a better result, i've made this instead of commandline arguments. I know it may take time where commandline arguement doesn't.
 
- ***Usages: *** It has 5 types of attacks like 1. Ping Attack, 2. Socket Programming, 3. Port Scanning, 4. DoS Attack, 5. MITM Attack. Under Ping Attack 6 types of  Ping Attacks like IP,TCP,UDP,ICMP,ARP,Default ping etc. But it will only for host discovery purpose. Lots of attacks are there. i have made this with scapy and nmap. Please run it and check it...
- I've attached a screenshot of this project.
![Project_Monalisa_screenshot](https://github.com/user-attachments/assets/6f133471-e59b-40ba-be4e-407ba5ad1614)

**Comment by Akash420-oss** [comment]
> We don't package wrappers of other tools.

could you please elaborate more about this. Because i couldn't get that...

**Comment by anunna** [comment]
You mentioned that you used scapy and nmap to make this tool. Those are existing tools and you have essentially made a wrapper that would remove the need for a user to run any commands since you have coded it into your framework. To make it easy for anyone that does not know how to use basic networking tools like nmap, scapy, Wireshark, proxychains. 

You literally have a GUI application as a dependency for a CLI tool

It's a lazyscript essentially which most frameworks are anyway.

**Comment by Akash420-oss** [comment]
> You mentioned that you used scapy and nmap to make this tool. Those are existing tools and you have essentially made a wrapper that would remove the need for a user to run any commands since you have coded it into your framework. To make it easy for anyone that does not know how to use basic networking tools like nmap, scapy, Wireshark, proxychains.
> 
> You literally have a GUI application as a dependency for a CLI tool
> 
> It's a lazyscript essentially which most frameworks are anyway.

Thank you for your valuable feedaback i will try to work with more...
