### ISSUE TITLE
[Tool Request] sharpfuzz

### ISSUE THREAD

**Issue by astro-angelfish** [BlackArch/blackarch#4312]
- **Name**: sharpfuzz
- **Source URL**: https://github.com/Metalnem/sharpfuzz
- **Description**: AFL-based fuzz testing for .NET

I think I could make a PR as long as I figured out how to install it and simplify its usage..?

**Comment by D3vil0p3r** [comment]
Try on your own to create PKGBUILD related to this package so you can be autonomous.

Here Arch wiki about PKGBUILD: https://wiki.archlinux.org/title/PKGBUILD
Start by using one of these templates according to the nature of the tool to package: https://github.com/BlackArch/blackarch-pkgbuilds

If you have any questions, also dumb-like, please ask.

**Comment by noraj** [comment]
Other resources

- https://wiki.archlinux.org/title/Wine_package_guidelines
- https://gist.github.com/noraj/5045be32490f1161161e16fc5820066c

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4383
