### ISSUE TITLE
regripper: missing plugins

### ISSUE THREAD

**Issue by ridicolos** [BlackArch/blackarch#4314]
### Bug description

Regripper is installed without any plugins and if you

### Steps to reproduce

```console
sudo pacman -Sy regripper
regripper-l
```

**Actual result:**

For every plugin which exists for regripper you get an error saying that it can't find the plugin. Here is a exmpale of the plugin `psscript`

```output
Error: Can't locate plugins/psscript.pl in @INC (@INC entries checked: /usr/lib/perl5/5.40/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.40/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.40/core_perl /usr/share/perl5/core_perl) at ./rip.pl line 103.
```

**Expected result:**

For the same plugin `psscript` (with regripper from AUR (regripper-git) or in kali)

```output
252. psscript v.20200525 [Software, NTUSER.DAT]
   - Get PSScript.ini values
```

---

I would be willing on trying to help and contribute, if someone can point me into a direction on how to fix this issue

**Comment by D3vil0p3r** [comment]
The error is caused due to a missing binary wrapper that refers to the regripper installation directory. Give me 5 min to create the PR to fix it

**Comment by D3vil0p3r** [comment]
`($plugindir = File::Spec->catfile("plugins"));` in `rip.pl` must be replaced by `($plugindir = File::Spec->catfile("/usr/share/regripper/plugins"));`.

**Comment by D3vil0p3r** [comment]
The upstream PR has been merged. Opened https://github.com/BlackArch/blackarch/pull/4330
