### ISSUE TITLE
warning: blackarch-keyring: unknown key 'makepkgopt' in package description - strap.sh

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#4329]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

It is a non-blocking warning, just reported to run a clean `strap.sh` script. When a user runs `strap.sh`, it gets the following warning message:
```
warning: blackarch-keyring: unknown key 'makepkgopt' in package description
warning: blackarch-keyring: unknown key 'makepkgopt' in package description
warning: blackarch-keyring: unknown key 'makepkgopt' in package description
warning: blackarch-keyring: unknown key 'makepkgopt' in package description
warning: blackarch-keyring: unknown key 'makepkgopt' in package description
warning: blackarch-keyring: unknown key 'makepkgopt' in package description
warning: blackarch-keyring: unknown key 'makepkgopt' in package description
warning: blackarch-keyring: unknown key 'makepkgopt' in package description
warning: blackarch-keyring: unknown key 'makepkgopt' in package description
```
As you know, this occurs because the `blackarch-keyring` package hosted in https://www.blackarch.org/keyring/blackarch-keyring.pkg.tar.xz has been created in 2014, so before the release of pacman 5.0.0 (2016) that added some changes triggering this kind of warning.

The latest (and original) `blackarch-keyring` package has been released on 2018-09-25.

In order to fix this warning messages, can you replace the old file package hosted https://www.blackarch.org/keyring/blackarch-keyring.pkg.tar.xz by the latest 2018-09-25 `blackarch-keyring` package (and its related `.sig` file)?

### Steps to reproduce

- `curl -s -O 'https://www.blackarch.org/keyring/blackarch-keyring.pkg.tar.xz'`
- `sudo pacman -U blackarch-keyring.pkg.tar.xz`

**Comment by noraj** [comment]
Also, I think we should replace those:

https://www.blackarch.org/keyring/

```
https://www.blackarch.org/keyring/blackarch-keyring-20180925.tar.gz                  14-Oct-2018 00:25               16347
https://www.blackarch.org/keyring/blackarch-keyring-20180925.tar.gz.sig              14-Oct-2018 00:25                 566
https://www.blackarch.org/keyring/blackarch-keyring.pkg.tar.xz                       14-Oct-2018 00:25               17064
https://www.blackarch.org/keyring/blackarch-keyring.pkg.tar.xz.sig
```

by

```
https://blackarch.org/blackarch/blackarch/os/x86_64/blackarch-keyring-20180925-5-any.pkg.tar.zst       23-Mar-2022 10:09               18365
https://blackarch.org/blackarch/blackarch/os/x86_64/blackarch-keyring-20180925-5-any.pkg.tar.zst.sig   23-Mar-2022 10:09                 566
```

https://blackarch.org/blackarch/blackarch/os/x86_64/

**Comment by noptrix** [comment]
i will

**Comment by noptrix** [comment]
done - feel free to re-open and let me know if sth is wrong :)
