### ISSUE TITLE
brosec and padoracle conflict

### ISSUE THREAD

**Issue by NobodySpecial256** [BlackArch/blackarch#4401]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Brosec and padoracle can't both be installed. This is similar to https://github.com/BlackArch/blackarch/issues/3224.

### Link to debug log

[blackarch-error.txt](https://github.com/user-attachments/files/17957294/blackarch-error.txt)

**Comment by noptrix** [comment]
@NobodySpecial256 we'are aware of this and will fix it. thanks!

**Comment by NobodySpecial256** [comment]
Oh, now you're acting friendly after banning me from your Matrix community (before I even sent a single message) and telling my friend to eat a dick...

![noptrix](https://github.com/user-attachments/assets/f379417d-a295-4daf-a555-e55af1a7e006)

By the way, I gotta ask, whatever happened to issues #4403, #4404, and #4405?
