### ISSUE TITLE
Tool Request: nikto

### ISSUE THREAD

**Issue by wsbwzfyvt** [BlackArch/blackarch#4432]
- **Name**: nikto
- **Source URL**: https://github.com/sullo/nikto
- **Description**: Web server scanner which performs comprehensive tests against web servers for multiple items, including over 7,000 potentially dangerous files/programs, checks for outdated versions of over 1250 servers, and version specific problems on over 270 servers. It also checks for server configuration items such as the presence of multiple index files, HTTP server options, and will attempt to identify installed web servers and software. Scan items and plugins are frequently updated and can be automatically updated.

**Comment by noraj** [comment]
It's already packaged on ArchLinux.
