### ISSUE TITLE
remote-method-guesser

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#4433]
- **Name**: remote-method-guesser
- **Source URL**: https://github.com/qtc-de/remote-method-guesser
- **Description**: Java RMI vulneraibility scanner

**Comment by D3vil0p3r** [comment]
Isn't there a standard maven-based PKGBUILD template in https://github.com/BlackArch/blackarch-pkgbuilds ?

**Comment by D3vil0p3r** [comment]
Here https://github.com/BlackArch/blackarch/pull/4434

I included also ysoserial and bash completion support.

**Comment by noraj** [comment]
> Isn't there a standard maven-based PKGBUILD template in https://github.com/BlackArch/blackarch-pkgbuilds ?

There is on PKGBUILD-java-jar, but PKGBUILD-java-maven would be welcome.

> I included also ysoserial and bash completion support.

Good idea.

**Comment by D3vil0p3r** [comment]
> > Isn't there a standard maven-based PKGBUILD template in https://github.com/BlackArch/blackarch-pkgbuilds ?
> 
> There is on PKGBUILD-java-jar, but PKGBUILD-java-maven would be welcome.
> 
Here the proposed PKGBUILD template https://github.com/BlackArch/blackarch-pkgbuilds/pull/28
