### ISSUE TITLE
[OUTDATED VERSION] Dislocker

### ISSUE THREAD

**Issue by heumann-a** [BlackArch/blackarch#4435]
- [X] I have searched open and closed issues for duplicates

----------------------------------------

### Bug description

- Outdated Version of dislocker in your Repository
- Wrong Link to french website who do not even host information about dislocker

### Steps to reproduce

- Search on your website in Tools for "dislocker"
- Link goes to some french website, dont know why...
- Tool version outdated 

**Expected result:** 

- Link to https://github.com/Aorimn/dislocker/tags
- Version of 0.7.3

**Comment by noraj** [comment]
The pkgbuild https://github.com/BlackArch/blackarch/blob/master/packages/dislocker/PKGBUILD is using upstream latest commit, so if the tarball in BA repos is outdated it must be because it's broken and so the building pipeline is failing.
