### ISSUE TITLE
Add [wordlistctl].

### ISSUE THREAD

**Issue by 000000000000000000000000000000000000** [BlackArch/blackarch#515]
We are going to create a tool that manages wordlists.

**Comment by heichblatt** [comment]
Hi all,

is this still a plan? I was thinking of creating an AUR package with all [SkullSecurity](http://wiki.skullsecurity.org/Passwords) lists instead.

**Comment by noptrix** [comment]
yeah it's a plan. but really long-term. so if you want to create one simply close this issue :)
