### ISSUE TITLE
Unrecognized archive format

### ISSUE THREAD

**Issue by pouar** [BlackArch/blackarch#669]
pacman spams "error: could not open file /var/lib/pacman/sync/blackarch.db: Unrecognized archive format"

**Comment by 230v** [comment]
i am include black arch repo, but have this problem. if you know how to fix, please tell me

**Comment by cyberthrone** [comment]
No estan disponibles yo tengo 3 dias intentando y no eh podido tampoco

   github.com/cyberthrone/ <http://github.com/cyberthrone/>
  https://launchpad.net/~alfierimorillo
  Ubuntu User number is # 35087
  Public profile linux for user #555597
  alfieri.morillo@libreoffice-ve.net
  Web Master libreoffice-ve <http://libreoffice-ve.org/> y Gimp-ve
<http://gimp-ve.com/>
  https://wiki.ubuntu.com/Alfierimorillo <https://wiki.ubuntu.com/Alfieri>
 La universidad es el refugio donde reprimen las ideas. Prohibido pensar,
solo a repetir lo establecido sin pataleo.

2015-05-19 18:16 GMT-04:30 230v <notifications@github.com>:
