### ISSUE TITLE
disable root by default

### ISSUE THREAD

**Issue by zabbal** [BlackArch/blackarch#796]
Would be great if BlackArch would come with root account disabled in default install - this would bring security of default installation on-par with Ubuntu and Fedora which are administered via sudo by user-defined login.

**Comment by ldionmarcil** [comment]
Update @noptrix ?

**Comment by demogorgonz** [comment]
That should be optional.. I would rather integrate fail2ban by default..

**Comment by zabbal** [comment]
Of course it's optional - you can always run "sudo passwd root" and set password for root if you'd like to decrease your system security slightly.
