### ISSUE TITLE
when installing to disk, how to get same theme/enviroment than live cd?

### ISSUE THREAD

**Issue by ChrisFernandez** [BlackArch/blackarch#829]
I have installed blackarch to HD, everything works.. and I find myself having to boot into arch linux live cd to strip the themes configs etc.. seens that blackarch will install the themes and the configs but will not enable them... is there a way to get the same desktop/theme running in a easy way with out having to pull pieces from one place and another?

Thanks

**Comment by noptrix** [comment]
you can install blackarch-config-<package (packages: fluxbox, openbox, awesome, lxdm) and follow the install instructions.

**Comment by noptrix** [comment]
also, the next ISOs will do a 1:1 copy of your environment. so you will not need to do anything after installing BlackArch Linux from the Live ISO.

**Comment by noptrix** [comment]
use the new ISOs and new installer. we just released them today
