### ISSUE TITLE
Error installing Live ISO with usb drive

### ISSUE THREAD

**Issue by puregatory** [BlackArch/blackarch#832]
![10416651_577632662337974_5939422020389285555_n](https://cloud.githubusercontent.com/assets/10094488/5326180/6d95daba-7d3b-11e4-8380-13a869e48d5f.jpg)

Checking file sha1sum ok, downloaded from blackarch web live ISO i686, I want booting with usb drive but I get this again and again.. No option for Installing black arch, just boot from existing Os,memtest,hdtest,reboot,and poweroff.. Whats my wrong step? Im use dd command, unetbootin, usbwriter, powerIso, but I still get this again,nothing change.. anyone can help?

**Comment by noptrix** [comment]
the new isos will include the fixes. we will probably release new ISOs in a few weeks. sorry for the delay.

**Comment by black2man** [comment]
1.On bootscreen  go to  "run memtest86+" and press [TAB]
2. Type:  .linux boot/i686/vmlinuz archisobasedir=arch archisolabel=BLACKARCH_201410 initrd=boot/i686/archiso.img [press Enter] 
3. After boot you are automaticaly root: 
Now run : pacman-db-update
4. (optional) run pacman -S blackarch-install-scripts
5. Now run "blackarch-install"

**Comment by noptrix** [comment]
this has been fixed now with the new ISOs and new version of the installer

**Comment by hunterhub** [comment]
i have the same problem even when i used the new ISO 2016-01-10, i want to install blackarch linux

**Comment by SilverBut** [comment]
@noptrix No, it did NOT fixed at all. You may want to reopen this ticket.

**Comment by noptrix** [comment]
Thx for re-reporting. This will be fixed in the upcoming ISOs  (~11th April).

**Comment by noptrix** [comment]
this is fixed and the new ISOs will be released on the 11th of april

**Comment by EffrvscngJcbx** [comment]
1.On bootscreen go to line "run memtest86+" and press [TAB]
2. Type: .linux boot/x86_64/vmlinuz archisobasedir=blackarch archisolabel=BLACKARCH_201601 initrd=boot/x86_64/archiso.img

what @black2man had posted but instead  of archisobasedir=arch .. use archisobasedir=blackarch 
=D

**Comment by sunilolo** [comment]
I use to have the same problem - boot blackarch.iso from usb -- and i try Rufus utility and its work now ..
Rufus utility >> https://rufus.akeo.ie/?locale=en_US
i choose this one Rufus 2.11 (916 KB)
The utility will ask to download -- ldlinux.sys -- and -- ldlinux.bss -- and it will do it Automatically
and i use this Image
http://www.mirrorservice.org/sites/blackarch.org/blackarch/iso/blackarchlinux-live-2016.08.31-x86_64.iso
And this one too
http://www.mirrorservice.org/sites/blackarch.org/blackarch/iso/blackarchlinux-netinst-2016.08.31-i686.iso
the user name is : root and the password is : blackarch
Goodluck
