### ISSUE TITLE
[!] Error in installing From Live ISO + error in installing base packages 

### ISSUE THREAD

**Issue by N3TC4T** [BlackArch/blackarch#835]
Hi 

First i should say thanks for this good distribution /

I tried to install blackarch from live ISO in hard drive using blackach-install script but after copying scripts and files to hdd  in copying and downloading the base files and packages i got the under error /

error: failed to prepare transaction (could not satisfy dependencies) 
:: virtualbox-guest-modules: requires linux < 3.16
==> ERROR: Failed to install packages to new root

I was checked the Under page before but i couldn't solve my problem /

https://github.com/BlackArch/blackarch/issues/811

i was tested the "pacman -Syu " before running installation script and even "pacstrap" manualy but same error /

thanks

**Comment by noptrix** [comment]
known issue. will be fixed in upcoming ISOs. thanks for reporting
