### ISSUE TITLE
can't install BlackArch on Vmware Workstation

### ISSUE THREAD

**Issue by houssem07** [BlackArch/blackarch#842]
Hello ! 
I've downloaded ----> blackarchlinux-live-2014.10.07-x86_64.iso <---
But i can't install it on Vmware Workstation 10.0.0 build-1295980 
I wish i can get the Solution 
Thanks

**Comment by noptrix** [comment]
this is a known issue and will be fixed in the upcoming ISOs. please install arch linux and add blackarch linux on top of it. the menus and configs for the window managers can be installed afterwards, for example: pacman -S blackarch-config-fluxbox blackarch-config-lxdm etc.

**Comment by houssem07** [comment]
ah OK thanks i'm waiting , Ok so i'll try with ArchLinux 
Thanks again ^_^

**Comment by noptrix** [comment]
yep :)

**Comment by houssem07** [comment]
I can't wait to try BlackArch , so i hope that Next ISO will get fixed ^_^
