### ISSUE TITLE
[binwalk] cannot find mod-firmware-kit

### ISSUE THREAD

**Issue by stoked-security** [BlackArch/blackarch#846]
Hi,
Binwalk uses mod-firmware-kit during the extracting process (-e) of certain file types. Which commands are executed for which file type is controlled by the following config file:

/usr/lib/python2.7/site-packages/binwalk/config/extract.conf

A quick look at the config file shows that the path for firmware-mod-kit is set to /opt/firmware-mod-kit/ by default, while the firmware-mod-kit package from Blackarch installs in /usr/share/firmware-mod-kit/. This will prevent binwalk from executing firmware-mod-kit tools during the extraction process. A simple workaround is to create a symlink with the following command and everything works fine: 
ln -s /usr/share/firmware-mod-kit/ /opt/firmware-mod-kit

In addition the extract.conf lists different archive formats it expects to be installed. None of these are listed as an optional dependency.

**Comment by noptrix** [comment]
thx for reporting. we will fix this.

**Comment by noptrix** [comment]
already fixed, built and released
