### ISSUE TITLE
[peach] wrapper script does not work

### ISSUE THREAD

**Issue by stoked-security** [BlackArch/blackarch#847]
Executing the peach command after installation results in the following error:
Cannot open assembly '/usr/bin/peach.exe': No such file or directory.

The wrapper script in /usr/bin/peach assumes peach.exe is in the same directory, which is not the case. It is located at /usr/share/peach/peach.exe

**Comment by noptrix** [comment]
thx for reporting. will be fixed.

**Comment by noptrix** [comment]
fixed, built and released.
