### ISSUE TITLE
How can I fix this?

### ISSUE THREAD

**Issue by fenrironfire** [BlackArch/blackarch#851]
Upon adding the blackarch keyrings, and doing "pacman -S blackarch" to install it, I get this once it finishes downloading:
http://pastebin.com/RbkhL3kL
(Posted on pastebin due to length)

Any assistance? This is a fresh install of arch with KDE.

**Comment by noptrix** [comment]
How did you install the keyrings? Btw, try as a temporary solution: pacman -S blackarch --needed --force instead.

**Comment by noptrix** [comment]
Also, which mirror do you use?

**Comment by fenrironfire** [comment]
I installed them using the the first method, this:
curl -s http://blackarch.org/strap.sh | sudo sh
And the mirror I'm using is: 
http://blackarch.cdndepo.com/blackarch/$repo/os/$arch

**Comment by nrzizrn** [comment]
check this out https://wiki.archlinux.org/index.php/pacman#.22Failed_to_commit_transaction_.28conflicting_files.29.22_error

**Comment by fenrironfire** [comment]
So should I just eitherr delete the folders, or rename them or such? I've never really had this error before.

**Comment by TantumCraig** [comment]
Same problem on fresh arch install with KDE, although am fairly certain KDE doesnt have anything to do with the issue, seems to apply to any arch install (up to date one at least). Weary of using force when the directories are what they are (/usr/bin etc), is that assured to not be an issue? Or is there another way to bypass/update coming soon?

**Comment by TantumCraig** [comment]
And correction, /usr/bin was not a conflict sbin was along with the others + python issues shown in the pastebin above, seems to be the sym links

**Comment by nrzizrn** [comment]
Sorry. Yeah, we're on the way to fix all this. thanks for reporting.

**Comment by nrzizrn** [comment]
Packages left to close issue

bletchley: /bin exists in filesystem
/usr/bin/cudaHashcat exists in both 'cudahashcat' and 'oclhashcat'
dhcdrop: /usr/sbin exists in filesystem
ipaudit: /usr/sbin exists in filesystem
mausezahn: /usr/sbin exists in filesystem
mboxgrep: /bin exists in filesystem
missidentify: /usr/local/share/man exists in filesystem
ncpfs: /sbin exists in filesystem
ncpfs: /usr/sbin exists in filesystem
nield: /usr/sbin exists in filesystem
phoss: /usr/sbin exists in filesystem
rifiuti2: /usr/local/share/man exists in filesystem
silk: /usr/sbin exists in filesystem
tiger: /var/run exists in filesystem

**Comment by TantumCraig** [comment]
Hi nrzizrn, awesome thanks a ton, will keep an eye out and retry the install after a little, and thanks for your guys' awesome work with blackarch! Have used it a while but this is the first time doing it from repo and not ISO, hopefully KDE menus will be coming soon as well!:)

**Comment by nrzizrn** [comment]
Sure, i will let you know when this is fixed completely (few days..).

Update packages left:
bletchley: /bin exists in filesystem
/usr/bin/cudaHashcat exists in both 'cudahashcat' and 'oclhashcat'
ncpfs: /sbin exists in filesystem
ncpfs: /usr/sbin exists in filesystem
nield: /usr/sbin exists in filesystem
rifiuti2: /usr/local/share/man exists in filesystem
silk: /usr/sbin exists in filesystem

**Comment by noptrix** [comment]
all done. listed packages are fixed now. thx for reporting.
