### ISSUE TITLE
Cannot connect via wifi to install from ISO

### ISSUE THREAD

**Issue by arcadiandecay** [BlackArch/blackarch#860]
Hello!  
     So, I've installed normal Arch plenty of times, never from an ISO.  My problem is showing up in being unable to connect to my network via WiFi.  After the initial install took place, the installer dropped out and said it couldn't connect to the repositories, which was what I had been worried about.
     I've tried everything that I know to try (in fact, I've had this issue on a normal Arch install from the same computer, same wifi adapter (Ralink RT3070)).  
     I would normally use WiFi menu, but it always times out, as does issuing the dhcpcd command on the interface, itself.  Everything seems to initialize correctly, including wpa_supplicant.  O.o  
     I'm at a bit of a loss.  Has anyone else had this issue?

Thank you!!

**Comment by ldionmarcil** [comment]
Hey. Can you confirm the kernel sees your card? Run `lspci' and check if you can see your card in there.

**Comment by arcadiandecay** [comment]
I actually resolved this issue, because I was too tired to realize that I wasn't getting a strong enough signal. I have hit another roadblock, though, but will open a different thread for that one. Thank you for responding!!  You rawk!

**Comment by ldionmarcil** [comment]
No problem. Feel free to reach us on IRC for more direct support.
