### ISSUE TITLE
Old packages

### ISSUE THREAD

**Issue by ohaz** [BlackArch/blackarch#864]
When I use pacman -Syu, I get this:

>:: Starting full system upgrade...
>warning: android-sdk-build-tools: local (r20-1) is newer than blackarch (r19.0.3-1)
>warning: pyqt3: local (3.18.1-14) is newer than blackarch (3.18.1-1)
>warning: qscintilla-qt3: local (1.7.1-6) is newer than blackarch (1.7.1-1)
>warning: qt3: local (1:3.3.8b-7) is newer than blackarch (3.3.8b-1)
>warning: underscorejs: local (1.6.0-6) is newer than blackarch (1.6.0-1)
>resolving dependencies...

Are those supposed to be older or do they just need to be updated in the repo?

**Comment by noptrix** [comment]
09:44:24 <@noptrix> ohaz, you can ignore those warnings: the patch version differs. means, 
                    fd.e. community made some changes regarding userland not $tool directly. 
                    that way you have to inctrement the $pkgrel which results in -2 -3 -4 etc 
                    -> warning occurs "blah is odler than"
09:44:43 <@noptrix> maybe there is a clever/smart way to circumvent those warnings
09:44:47 <@noptrix> i will take a look later
