### ISSUE TITLE
metasploit post_install() fails with ruby<2.1

### ISSUE THREAD

**Issue by bardo** [BlackArch/blackarch#872]
The metasploit package runs the `bundle-1.9` command in its `post_install()` function, but metasploit now only supports ruby >= 2.1:
https://github.com/darkoperator/MSF-Installer/issues/45#issuecomment-75522947

Solution: add `ruby-bundler` to the package dependencies, and change `/usr/bin/bundle-1.9 install` into `/usr/bin/bundle install` in `metasploit.install`.

**Comment by noptrix** [comment]
this has been fixed
