### ISSUE TITLE
[metasploit] Proper dependencies for ruby 2 no applied.

### ISSUE THREAD

**Issue by RainbowDashDC** [BlackArch/blackarch#877]
Currently your version of metasploit can and is run with ruby 2.2, or atleast on my arch install it is. This doesn't, and it complains

```
Could not find rake-10.4.2 in any of the sources
Run `bundle install` to install missing gems.
```

This is fixed by adding `~/.gem/ruby/2.2.0/bin` to PATH env.

You then have to run `bundle --deployment` in /usr/share/metasploit inorder to get the correct dependencies.

After that a patch (regardless of ruby version) for robots needs to be applied.

```
chmod -R 755 /usr/share/metasploit/vendor/bundle/ruby/2.2.0/gems/robots-0.10.1/
```

Took me awhile to figure out how to fix this, but just letting you know.

**EDIT**: It appears the same issue is encountered for ruby-1.9 aswell, but it fails to install with

```ruby
Installing metasploit_data_models (0.23.0) 
Gem::InstallError: metasploit_data_models requires Ruby version >= 2.1.
An error occurred while installing metasploit_data_models (0.23.0), and Bundler
cannot continue.
Make sure that `gem install metasploit_data_models -v '0.23.0'` succeeds before
bundling.
```

**Comment by noptrix** [comment]
thanks for sharing this with us. we will fix and release msf asap.

**Comment by noptrix** [comment]
added, fixed. thx
