### ISSUE TITLE
python2-capstone conflicting packages

### ISSUE THREAD

**Issue by bengtfrost** [BlackArch/blackarch#881]
# already installed with capstone

[bfrost@tux ~]$ pacaur -S python2-capstone
[sudo] password for bfrost: 
resolving dependencies...
looking for conflicting packages...

Package (1)                 New Version  Net Change

blackarch/python2-capstone  3.0-1          0.70 MiB

Total Installed Size:  0.70 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                               [###########################################] 100%
(1/1) checking package integrity                                             [###########################################] 100%
(1/1) loading package files                                                  [###########################################] 100%
(1/1) checking for file conflicts                                            [###########################################] 100%
error: failed to commit transaction (conflicting files)
python2-capstone: /usr/lib/python2.7/site-packages/capstone/__init__.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/__init__.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/__init__.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/arm.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/arm.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/arm.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/arm64.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/arm64.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/arm64.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/arm64_const.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/arm64_const.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/arm64_const.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/arm_const.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/arm_const.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/arm_const.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/mips.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/mips.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/mips.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/mips_const.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/mips_const.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/mips_const.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/ppc.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/ppc.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/ppc.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/ppc_const.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/ppc_const.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/ppc_const.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/sparc.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/sparc.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/sparc.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/sparc_const.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/sparc_const.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/sparc_const.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/systemz.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/systemz.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/systemz.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/sysz_const.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/sysz_const.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/sysz_const.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/x86.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/x86.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/x86.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/x86_const.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/x86_const.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/x86_const.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/xcore.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/xcore.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/xcore.pyo exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/xcore_const.py exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/xcore_const.pyc exists in filesystem
python2-capstone: /usr/lib/python2.7/site-packages/capstone/xcore_const.pyo exists in filesystem
Errors occurred, no packages were upgraded.

**Comment by noptrix** [comment]
hi. please use pacman -Syyu --force --needed

**Comment by bengtfrost** [comment]
OK. Used pacman (pacaur, lazy me) -S capstone instead. Thanks
