### ISSUE TITLE
Live-ISO (32-bit) install error / critical failure (gcc and virtual box guest modules)

### ISSUE THREAD

**Issue by utterbull** [BlackArch/blackarch#882]
Using black-archinstall (v0.7.8) from a Live-ISO has failed multiple times. The last information displayed is summarized below.
`warning: so-and-so is up to date -- reinstalling`
`warning: this-and-that is up to date -- reinstalling`
shows warnings for about 20 different items
`resolving dependencies...`
`looking for interconflicts...`
`error: failed to prepare transaction (could not satisfy dependencies)`
`: : gcc: requires gcc-libs=4.9.1-2`
`: : virtualbox-guest-modules: requires linux<3.17`
`==> ERROR: Failed to install packages to new root`
`[x] CRITICAL : failed to install Archlinux base packages`

**Comment by noptrix** [comment]
hi. this has been fixed. the new ISOs and new version of installer will be released in just few days. closing the issue here.
