### ISSUE TITLE
[metasploit] Run msfconsole dependencies git

### ISSUE THREAD

**Issue by ardemiranda** [BlackArch/blackarch#886]
Run msfconsole error:
> There was a Errno::ENOENT while loading metasploit-framework.gemspec: 
> No such file or directory - git from
>   /usr/share/metasploit/metasploit-framework.gemspec:27:in ``'

installed git and the error stopped.
Add git dependence on PKGBUILD

**Comment by noptrix** [comment]
thanks for reporting. will fix it

**Comment by noptrix** [comment]
fixed and released.
