### ISSUE TITLE
 [metasploit] Run msfconsole dependencies i18n

### ISSUE THREAD

**Issue by ardemiranda** [BlackArch/blackarch#887]
Run msfconsole error:
> Could not find i18n-0.6.11 in any of the sources
> Run `bundle install` to install missing gems.

Installed ruby-i18n version 7.0 aur archlinux and keeps giving the same error

**Comment by noptrix** [comment]
thanks for reporting. will be fixed

**Comment by noptrix** [comment]
fixed and released.
