### ISSUE TITLE
add menu blackarch in xfce4

### ISSUE THREAD

**Issue by programacion-web** [BlackArch/blackarch#891]
hi thanks for the work done,

I would like to know how to add the menu xfce4 the category blackarch, just install a few categories of blackarch in my usual arch linux

thanks

**Comment by abericart** [comment]
blackarch-menus needs some work to support this I suspect. I'll have a look.

**Comment by frac1234** [comment]
blackarch-menus now works on xfce4

**Comment by incomingstick** [comment]
:+1:

**Comment by incomingstick** [comment]
Is there anything we as users may need to do on our end? I just updated my whole arch system and rebooted, but the BlackArch menu isn't showing still. I'm an currently reinstalling the whole blackarch repo, maybe that  will fix it? I will update if it doesn't work.

**Comment by incomingstick** [comment]
After doing the full reinstall and reboot the menu is still not showing up. Using a Menu editing tool, such as MenuLibre, I can see it as an available menu system, but I can't seem to figure out why it isn't showing up as an actual menu. Looking at all the menu and directory files, they look correct as well. Am I missing something? It look's like it's still not working. I even tried updating just the blackarch-menus package.

**Comment by cyrus104** [comment]
I can see the menu when I right click on the desktop but not all of the apps show up. Is it possible at have a blackarch-xfce4-config added.

**Comment by 0b4cL** [comment]
Did anyone find a solution to this issue yet? I'm in the exact same boat as cyrus104.

**Comment by cyrus104** [comment]
When it would be nice to have a full theme package for xfce, menu bar colors, menus, background, etc...

I haven't got the menu add yet, not sure why it won't go.

**Comment by noptrix** [comment]
we will add support for xfce soon. still needs some time.

**Comment by heichblatt** [comment]
Hello everyone,

turns out the Blackarch menu showing up in the desktop menu but not the panel menu is a known bug.

- [Arch forum](https://bbs.archlinux.org/viewtopic.php?pid=1652217#p1652217)
- [Bug](https://bugzilla.xfce.org/show_bug.cgi?id=11801)
- [Unreleased fix](https://git.xfce.org/xfce/garcon/commit/?id=6ce5f2f7d6e98493deb8153ea28f37d4489c5e21)

So since this issue was originally about that bug, I'm closing it. Feel free to open a separate issue about general XFCE support in BlackArch.

Cheers

**Comment by heichblatt** [comment]
Some more context: the bug is in the garcon library. Arch currently includes 0.4, upstream has released 0.5. The fix will probably be included in 0.6.
