### ISSUE TITLE
Suggestion: mirrorlist (generator) package?

### ISSUE THREAD

**Issue by piepie62** [BlackArch/blackarch#897]
Hello, I have been following this project for a little while, and I have been slightly frustrated with the inability to obtain an up-to-date mirrorlist that is inclusive of all the mirrors for the repository. I have had some problems with my self-made ones, mostly as mirrors seem to stop working. I think it would be a good idea to have either a mirrorlist or a mirrorlist generator package, so that one could fetch all of the currently working mirrors. Thank you for your time and work on this project; you have been doing great work!

**Comment by TheBlackRabbit** [comment]
try checking the mirror in the main repo....

**Comment by piepie62** [comment]
Done, closing.
