### ISSUE TITLE
Error installing Live ISO with usb drive #2

### ISSUE THREAD

**Issue by norbertklar** [BlackArch/blackarch#899]
I have same issue with new Live ISOs: https://github.com/BlackArch/blackarch/issues/832

You said, you're guys fixed it.

**Comment by noptrix** [comment]
weird. is this i686 you tried on i686 machine?

**Comment by norbertklar** [comment]
Yes. I tried x86_x64 version in my machine this morning, and that's working excellent. Yea, that's weird, because my native system - Manjaro - is i686 version.

**Comment by jpippy** [comment]
I am having this same issue. Latest i686 version on a x86 machine.

**Comment by noptrix** [comment]
issue reported multiple times (i686 related only). we are working on it and we will release the new fixed ISOs soon.
