### ISSUE TITLE
loki update

### ISSUE THREAD

**Issue by 0xc0decafe** [BlackArch/blackarch#901]
Hi, nightly builds of loki are available at http://c0decafe.de/loki/nightly/loki-0.3.0_r*-x86_64.pkg.tar.xz they include a lot of bug fixes and new functionality. There is also an PKGBUILD file available that builds from svn, if this fits your packaging needs better: http://c0decafe.de/svn/codename_loki/trunk/pkg_scripts/PKGBUILD.

thanks and have a nice one.

**Comment by noptrix** [comment]
Hi Daniel,

thanks for your comment and information about loki. We will include the nightly-build version. Cheers.

**Comment by noptrix** [comment]
built and released. thx again.

**Comment by 0xc0decafe** [comment]
So after ~15 years I did take on the challenge to build loki so it can run on modern systems.

With that said, I'll just leave this here:

https://c0decafe.de/loki/loki-0.3.0-4f01734e92_debian-9_X64_bin.zip
https://c0decafe.de/loki/loki-0.3.0-4f01734e92_debian-9_ARM64_bin.zip

Have phun!
