### ISSUE TITLE
oclhashcat failed to retrieve file size exceeded

### ISSUE THREAD

**Issue by henry-gray** [BlackArch/blackarch#902]
I've got a issue with the following message

error: failed retrieving file 'oclhashcat-1.36-1-i686.phg.tar.xz' from mirror.team-cymru.org: maximum file size exceeded

This is the first time I have seen this error and not sure how to resolve it.

**Comment by noptrix** [comment]
could you please retry?

**Comment by henry-gray** [comment]
Sorry but still getting the same error,  I get error when I try and change mirrors.

**Comment by demogorgonz** [comment]
Hello @henry-gray , have you saw the arch wiki pages on changing mirror here: https://wiki.archlinux.org/index.php/Mirrors ?

I personally use mirror: "http://blackarch.nullsecurity.net/blackarch/", but the whole list can be found here at bottom: http://blackarch.org/downloads.html

Retry with command: pacman -Syyu --needed blackarch

Good luck :)

**Comment by demogorgonz** [comment]
Solution is to enable curl in pacman so it does not time out and throw error about maximum file size. More info can be found here: https://www.reddit.com/r/archlinux/comments/2axo9x/unable_to_update_using_pacman_maximum_file_size/

Let us know how it went :+1:

**Comment by henry-gray** [comment]
I've install blackarch twice now, first time I didn't have to enable curl, so something must have changed, but enabling curl has worked so thank you for your help.

**Comment by demogorgonz** [comment]
You are welcome :) tho i would still try several mirrors, try rebooting after switching just to make sure the config is reloaded... The error occurs when the mirror is timed out(10s), i've run couple tests with "limits" and "loss" out of curiosity and have faced same problem as you. Is your network stable ? - I mean Adsl,fiber (cable based) or 3g,wifi ?

**Comment by henry-gray** [comment]
At present it is only ADSL,, I first got the error when using wifi, then I tried over Ethernet with the same problem. It would appear that even with 15mb download it is not good enough, even though I had no problem installing Arch Linux first.

**Comment by demogorgonz** [comment]
Maybe is the mirror problem, can you post here which mirrors have you tried?

**Comment by henry-gray** [comment]
The mirror used was the default one,  http://mirror.team-cymru.org/blackarch/$repo/os/$arch

**Comment by demogorgonz** [comment]
There are actually couple things that could result in the error message:
- Internet connection
- Mirror under heavy load - slow response time
- DNS
- Not fully synced mirror

Anyway, as mentioned before curl does not have timeout, i am pretty sure that you wont experience same error again :+1:

**Comment by henry-gray** [comment]
I hope not, and again, thank you.

**Comment by noptrix** [comment]
if this happenes again re-open the issue :)
