### ISSUE TITLE
Cant see install from live-iso!

### ISSUE THREAD

**Issue by moontoise** [BlackArch/blackarch#904]
hi
i have x86_64 iso burned on DvD and now i want to install blackarch on my hard.
but when i run blackarch-install, i see 2 choices (From package repository, From sources using blackman) and cant see the From live-iso option!
now, how i can easy install blackarch on my hard and dual boot with other OS's ?!
thanks

**Comment by koldbyte** [comment]
I also faced the same issue.

duplicate issue #903

**Comment by lebdude** [comment]
I also have the same issue

**Comment by AeroX2** [comment]
Copied and pasted from this thread https://github.com/BlackArch/blackarch/issues/832

black2man commented on Jan 28
[solution for 32bit Version -> i686]
1.On bootscreen go to line "run memtest86+" and press [TAB]
2. Type: .linux boot/i686/vmlinuz archisobasedir=arch archisolabel=BLACKARCH_201504 initrd=boot/i686/archiso.img [press Enter] 
3. After boot you are automaticaly root: 
(optional) run : pacman-db-upgrate
4. (optional) run pacman -S blackarch-install-scripts
5. Now run "blackarch-install"

**Comment by th3-h4d3s** [comment]
you need to check sha1 checksum with checksum given on download page if both keys are different then you need to download the iso file again and then install it should work properly.
actually by doing that you will insure that your file is not corrupted. 
linux command to calculate sha1 checksum is: 
sha1sum filename

**Comment by hackerjargon** [comment]
Downloaded both i686 and x86_64 and verified both checksums.
The live ISO is not the problem

Even the blacarch-install-script here on github only referace the repo and blacman install (see bellow snippit from the script). There is no "Install from Live-ISO" option in the code as mentioned in the blackarch-install-script.txt document:

--
# print installer menu and get chosen options
install_menu_how()
{
    while ! [ "${menu_opt_how}" = "${MENU_REPO}" -o \
              "${menu_opt_how}" = "${MENU_BLACKMAN}" ]; do
        header "Welcome to BlackArch Linux installation!"

        printf "%s" "${WHITE}"

        printf "[+] Installation modes:\n"
        printf "    1. Install from package repository\n"
        printf "    2. Install from sources using blackman\n"
        echo
        printf "Make a choice [h - help]: "; read menu_opt_how

        [ "${menu_opt_how}" == "h" ] && help_menu_how
    done
--

I've also checked and the v0.7 of the install script doesn't have the code for this

**Comment by N3TC4T** [comment]
Hey guys
v0.7 was very bugy in installing from live-iso and I think they was removed the code cuz of that , I think they made a new installer script written in python .
btw I will make a live-iso installer for myself .

**Comment by N3TC4T** [comment]
Here old version you can find installing from live-iso :+1: 
https://github.com/BlackArch/blackarch-install-scripts/tree/afe0209bd442d1a81e4af6b7e8f83b30004140fc

**Comment by N3TC4T** [comment]
Done!
use this release :

https://github.com/BlackArch/blackarch-install-scripts/releases/tag/v0.7.8

but in BLACKARCH-INSTALL file :
before installing base packages line 506 add this two command : 

rm -r "${ROOT}"/var/lib/pacman/local/virtualbox*
rm -r "${ROOT}"/var/lib/pacman/local/gcc-lib*

It's worked for me :+1: 

and IF you got a error in any pacman installation , use --force option :8ball:

**Comment by jknlsn** [comment]
Hey, I'm having no luck installing from the .iso to VirtualBox! Goes through the whole process and then when I reboot says that there is an error that no bootable media is found!

I've had to download the whole architecture now a couple of times and wold prefer not to keep chewing through my bandwidth trying to resolve this, how would I use your blackarch-install-scripts instead?

Any help would be much appreciated!

**Comment by NoName-007** [comment]
N3TC4T
can you please tell me how to update or change or use BLACKARCH-INSTALL SCRIPTS
