### ISSUE TITLE
Please upgrade package pulseaudio and its dependecy libpulse

### ISSUE THREAD

**Issue by battleprogrammerandrew** [BlackArch/blackarch#905]
I am running Arch linux with blackarch as a repository and everytime I do a full system upgrade I get this warning: pulseaudio: local (6.0-2) is newer than blackarch (5.0-1). 
So upgrade the package pulseaudio and libpulse to a newer version so I can downgrade my local package and get rid of the warning. 
I can not downgrade to pulseaudio 5.0-1 because libpulse 5.0-1 is not in blackarch repo and I could not find this version anywhere.

**Comment by noptrix** [comment]
thanks for your message. we will remove pulseaudio from blackarch,

**Comment by noptrix** [comment]
removed

**Comment by battleprogrammerandrew** [comment]
This did not fix for me. I still get the warning even though I have synchronized the package database. Pacman and yaourt tell me that pulseaudio (5.0-1) is still in the repository, i have this in my pacman.conf
[blackarch]
Server = http://mirror.team-cymru.org/blackarch/$repo/os/$arch

I don't get it why this problem persists, doesn't it have to be removed from the database also ?

**Comment by ldionmarcil** [comment]
Hey @battleprogrammerandrew, it seems the http://mirror.team-cymru.org/ is out of sync. Use a different server to do your update and it should go through.

**Comment by battleprogrammerandrew** [comment]
Using a different mirror solved the problem. Thank you both for your help.
