### ISSUE TITLE
Inclusion of pth-toolkit

### ISSUE THREAD

**Issue by kurobeats** [BlackArch/blackarch#908]
Tool addition request for pth-toolkit:

https://github.com/byt3bl33d3r/pth-toolkit

**Comment by noptrix** [comment]
thx. will be added

**Comment by noptrix** [comment]
where can we find the sources?

**Comment by Oweoqi** [comment]
Looks like the google code repo has been abandoned. byt3bl33d3r's repo seems to be the only one kicking around

**Comment by noptrix** [comment]
sorry for being late. totally missed. we will include this asap

**Comment by Oweoqi** [comment]
All good
On 25 Sep 2015 12:54 am, noptrix <notifications@github.com> wrote:sorry for being late. totally missed. we will include this asap

**Comment by noptrix** [comment]
added and released. sorry, i totally forgot it :)
