### ISSUE TITLE
Help on VPN

### ISSUE THREAD

**Issue by ls4k** [BlackArch/blackarch#911]
I am new to blackarch and i'm confused on how to conect to a VPN or to make my ip Anonymous.

Thanks

**Comment by demogorgonz** [comment]
You could actually google for the info... Or provide what kind of VPN connection you want to establish...

https://wiki.archlinux.org/index.php/PPTP_VPN_client_setup_with_pptpclient
http://houbysoft.com/v/en/papers/pptp/
https://wiki.archlinux.org/index.php/L2TP/IPsec_VPN_client_setup

**Comment by ldionmarcil** [comment]
This is unfortunately unrelated to Blackarch. As @demogorgonz mentionned, you should look for Google for info on this. Feel free to drop by on IRC if you want further info, though.
