### ISSUE TITLE
Can't find any tools in blackarch

### ISSUE THREAD

**Issue by abasquin** [BlackArch/blackarch#912]
Hello World !
I just finished install blackarch on my desktop but when i clic on an application in the blackarch menu, the application is not found.

So i tried :
find / -name "nmap"
find / -name "sqlmap"
find / -name "metasploit"
and so on ...
but there is no result. The applications don't seem to be installed whereas during the installation, it downloads every packages and seems to have installed them proprely.

I can't understand what's happened and I can't find any topic on the internet about this issue, so anybody has an idea ??

Thank you so much and sorry for my english.

**Comment by Elektrochemie** [comment]
I have the same problem.
After installing the full set of tools and rebooting the system, none of the tools were installed. I tried it several times with both netinstall and live iso in virtualbox and vmware player. There were no error messages displayed during or after installation process. Hope someone can help here. Greetings

**Comment by abasquin** [comment]
After all i found that packages were downloaded but not installed.
The solution is : 
# pacman -S blackarch
and if it block try : 
# pacman -S blackarch --force

**Comment by Elektrochemie** [comment]
That did the trick. Wish i had asked around a little earlier. Thanks a bunch. 
Regards

**Comment by vishalmohanraj** [comment]
> I have the same problem.
> After installing the full set of tools and rebooting the system, none of the tools were installed. I tried it several times with both netinstall and live iso in virtualbox and vmware player. There were no error messages displayed during or after installation process. Hope someone can help here. Greetings

same problem pleas solve me
