### ISSUE TITLE
user name and password

### ISSUE THREAD

**Issue by imokn1974** [BlackArch/blackarch#913]
hello, I just boot up BlackArcg, it asking me for user name and password.  whats the default or the user name and password? thank you

**Comment by demogorgonz** [comment]
root
blackarch

**Comment by sayantandatta97** [comment]
Hi all Please help me out I have forgot my Black Arch Linux Password . How can I fix this issue please help me out.

**Comment by PedroSFreitas** [comment]
@sayantandatta97 Please **do not bump old threads**.

Google is your friend: https://wiki.archlinux.org/index.php/reset_root_password

Locking...
