### ISSUE TITLE
ruby-rdoc and ruby-json conflicts

### ISSUE THREAD

**Issue by snusmubrik** [BlackArch/blackarch#914]
Trying to install:
pacman -S blackarch

failed to commit transaction (conflicting files)
/usr/lib/ruby/gems/2.2.0/gems/rdoc-4.2.0/bin/rdoc exists in both 'ruby' and 'ruby-rdoc'
/usr/lib/ruby/gems/2.2.0/gems/rdoc-4.2.0/bin/ri exists in both 'ruby' and 'ruby-rdoc'
Errors occurred, no packages were upgraded.

**Comment by noptrix** [comment]
hi. thanks for your report. can you please try to exclude 'ruby-ronin', e.g. pacman -S blackarch --ignore ruby-ronin? we will provide a fix in the meanwhile. thx

**Comment by noptrix** [comment]
or switch temporary to main-site mirror: blackarch.org

**Comment by snusmubrik** [comment]
Thanks, it helped!

**Comment by noptrix** [comment]
np.

**Comment by nimmuk09** [comment]
i encountered the same issue today.  i have also tried the suggestions above. 
error code:
/usr/bin/bundle exists in both 'ruby-bundler' and 'gitrob'
/usr/bin/bundler exists in both 'ruby-bundler' and 'gitrob'
     exists in both 'bettercap' and 'ruby-colorize'

**Comment by noptrix** [comment]
use --force option for pacman

**Comment by nimmuk09** [comment]
thanks.

**Comment by l0v3rb** [comment]
same same issue today. i have also tried the suggestions above.
error code:
/usr/bin/bundle exists in both 'ruby-bundler' and 'gitrob'
/usr/bin/bundler exists in both 'ruby-bundler' and 'gitrob'
exists in both 'bettercap' and 'ruby-colorize

**Comment by l0v3rb** [comment]
Thanks noptrix..  worked

**Comment by borysn** [comment]
I am getting a lot of ruby conflicts, especially with gitrob, and ruby-json. Installing over arch also broke ruby and my gems, due to forcing despite ownership conflicts.

**Comment by incomingstick** [comment]
This is an issue for myself as well. using --force installs everything but it still throws the errors. its bearable but annoying.
