### ISSUE TITLE
Add OWASP Zed Attack Proxy

### ISSUE THREAD

**Issue by dr1861** [BlackArch/blackarch#918]
Is it possible to add ZAP to the list of available tools?
http://github.com/zaproxy/zaproxy

While it works similarly to BurpSuite, it can give differing results.

**Comment by noptrix** [comment]
It is added already! Closing this issue

**Comment by dr1861** [comment]
Hello,

In searching the blackarch repository, I only find the python bindings
for owasp zap, not the zap java thick client.
