### ISSUE TITLE
TypeError in Setoolkit 

### ISSUE THREAD

**Issue by Ahiknsr** [BlackArch/blackarch#919]
when i try to run the setoolkit it's throwing a TypeError .here is the error

#setoolkit 
[!] Metasploit path not found. These payloads will be disabled.
[!] Please configure in the config/set_config.

      Press <return> to continue

[-] New set_config.py file generated on: 2015-07-14 18:42:34.105261
[-] Verifying configuration update...
[!] Update failed? Timestamp on config file is: 2013-10-30 04:29:41.749820
[*] SET is using the new config, no need to restart
Traceback (most recent call last):
  File "/usr/share/set/setoolkit", line 228, in <module>
    log(error)
  File "/usr/share/set/src/core/setcore.py", line 695, in log
    if not os.path.isfile("%s/" + os.getenv("HOME") + "/.set/logs/set_logfile.log" % (definepath())):
TypeError: not all arguments converted during string formatting

**Comment by noptrix** [comment]
fixed.
