### ISSUE TITLE
Setoolkit doesn't work

### ISSUE THREAD

**Issue by frac1234** [BlackArch/blackarch#921]
when I run setoolkit, it throws me this error:

[-] New set_config.py file generated on: 2015-07-15 12:31:11.523425
[-] Verifying configuration update...
[!] Update failed? Timestamp on config file is: 2013-10-30 04:29:41.726467
[*] SET is using the new config, no need to restart
Traceback (most recent call last):
File "/usr/share/set/setoolkit", line 228, in
log(error)
File "/usr/share/set/src/core/setcore.py", line 695, in log
if not os.path.isfile("%s/" + os.getenv("HOME") + "/.set/logs/set_logfile.log" % (definepath())):
TypeError: not all arguments converted during string formatting

this problem is same with issue #919 and issue #894

**Comment by azerupi** [comment]
Same here

**Comment by noptrix** [comment]
should be fixed. closing
