### ISSUE TITLE
Can't boot Live ISO

### ISSUE THREAD

**Issue by Kanareika** [BlackArch/blackarch#924]
I try to use BlackArch in VMware Workstation 10, but don't have option to boot live version or install. Pic -> http://i62.tinypic.com/2po2j5i.png

Sorry for my bad English.

**Comment by Kanareika** [comment]
I forgot to say - this is latest x32 iso, downloaded by torrent.

Sorry for my bad English.

**Comment by hoodrat31337** [comment]
Have you tried re-creating the ISO or re-creating the VM to boot from?
[Here](http://blackarch.pi3rrot.net/blackarch/iso/blackarchlinux-live-2015.07.31-x86_64.iso) is a link to the latest Black Arch iso.

**Comment by jaredestroud** [comment]
Have you tried re-downloading the ISO or re-creating the VM?

The latest version can be found [here](http://blackarch.pi3rrot.net/blackarch/iso/blackarchlinux-live-2015.07.31-x86_64.iso).
