### ISSUE TITLE
fstab when separate /boot partition

### ISSUE THREAD

**Issue by ilkerdagli** [BlackArch/blackarch#927]
The installation script is not updating the fstab. On separate boot partition setup, because of /boot is not mounted, when you upgrade kernel, its updating the kernel on the rootfs partition, not in the boot partition. Therefore kernel is not booting properly.

**Comment by noptrix** [comment]
thx. will be fixed.

**Comment by noptrix** [comment]
hey. can you please move this issue to BlackArch/blackarch-install-scripts or re-open the issue there?

**Comment by Sirman** [comment]
ｉ　ｇｏｔ　ａｒｃｈｌｉｎｕｘ　ｒｅａｄｙ　ｅｎｊｏｙ　ｉｔ　ｗｈｅｎ　ｉ　ｆｉｎｉｓｈｅｄ　ｔｈｅ　ｉｎｓｔａｌｌａｔｉｏｎ，ｂｕｔ　ｉ　ｃａｎ＇ｔ　ｒｅｂｏｏｔ　ｓｙｓｔｅｍ

**Comment by Sirman** [comment]
Is there some way to solve the problem about kernel is not booting properly?

**Comment by noptrix** [comment]
This has been fixed with the new installe released along the new ISOs.
