### ISSUE TITLE
Tool inclusion request: autopwn

### ISSUE THREAD

**Issue by rascal999** [BlackArch/blackarch#930]
https://github.com/nccgroup/autopwn
https://pypi.python.org/pypi/autopwn
https://registry.hub.docker.com/u/rascal999/autopwn/

I am tool author so you if have any questions or requirements let me know.

**Comment by noptrix** [comment]
thx. will be included

**Comment by noptrix** [comment]
included

**Comment by rascal999** [comment]
Hi noptrix, I've made significant changes to autopwn and is now released as v1.0.0 (available at https://github.com/nccgroup/autopwn). The biggest single change is the fact that autopwn is now just a JSON API service, and is communicated to by client-side tools. I have created a Java GUI to interface with autopwn, which is available at https://github.com/rascal999/autopwn-gui.

Requesting inclusion of updated autopwn and autopwn-gui.
