### ISSUE TITLE
sqlninja: bugs and missing dependencies

### ISSUE THREAD

**Issue by nil0x42** [BlackArch/blackarch#936]
missing dependencies:
"""
perl-dbi
perl-dbd-sqlite
"""

bugs:
$ sqlninja
"""
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{\|{ <-- HERE \|/ at lib/utils.pl line 464.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE {/ at lib/utils.pl line 464.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{{ <-- HERE / at lib/utils.pl line 464.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/}{ <-- HERE }{/ at lib/utils.pl line 465.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/}{}{ <-- HERE / at lib/utils.pl line 465.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\{ <-- HERE [0...256]/ at lib/utils.pl line 467.
Sqlninja rel. 0.2.999-alpha1 <http://sqlninja.sf.net>
(C) 2006-2013 icesurfer & nico
[+] Parsing sqlninja.conf...
[+] Loading extraction module: lib/getdata_time.pl
DBI connect('dbname=session.db','',...) failed: unable to open database file at lib/session.pl line 70.
"""
(i consider the last line only being a bug)

**Comment by halitalptekin** [comment]
you can see these errors(utils.pl) under perl 5.22.0-1, but if you downgrade to perl 5.20.2-1, it will be fixed. another dependency problem is fixed at https://github.com/BlackArch/blackarch/commit/6000c2d8926cf237f870aaf0286a6dc09ae03731
