### ISSUE TITLE
Attempting to create regular user account results in infinite loop and then cancellation of the installation process

### ISSUE THREAD

**Issue by the-robits-are-coming** [BlackArch/blackarch#945]
During black arch install from a live iso, when I was prompted to create a regular user account after changing the root password in the installation process, it launched into an infinite loop as soon as I clicked enter to specify the name of the new user. the paswrd: prompt would come up, but it would fill itself in with user '(username)' does not exist. then on the next line it would tell me to try again before bringing up the passwrd prompt and automatically filling it in again.

passwd: user '(username)' does not exist
wrong passwd - please try again
passwd: user '(username)' does not exist

and so on and so forth for a few minutes until the installation process was killed and the this would appear in the prompt:

/bin/blackarch-install: line 584: 5865 segmentation fault         (core dumpted) chroot "${ROOT}" "/bin/chhroot-install" "${mode}" -D "${HD}" -R "${root_part}" "$(${LUKS} && printf '%sl' '-')" -k "${keymaps}"

following this the command prompt from the home directory of the live iso was brought up and the installation process seems to have been cancelled.

**Comment by noptrix** [comment]
thx for reporting. could you reopen this issue on blackarch-install-scripts rather than here?

**Comment by noptrix** [comment]
did not see any options to move this issue :/

**Comment by noptrix** [comment]
This has been fixed with the new installe released along the new ISOs.
