### ISSUE TITLE
pwntools. problems with installation

### ISSUE THREAD

**Issue by dropnz** [BlackArch/blackarch#947]
# pacman -S pwntools

# pacman -Qi pwntools | grep Depends
Depends On     : python2  python2-paramiko  python2-mako  python2-pyelftools

# cat /usr/lib/python2.7/site-packages/pwntools-2.2-py2.7.egg-info/requires.txt
paramiko
argparse
mako
pyelftools
capstone=2.1
ropgadget
pyserial
requests
psutil

to start pwntools i had to do this:
 - install argparse with pip2 (argparse package not found in archlinux and blackarch repositories)
 - replace "capstone=2.1" with "capstone" in /usr/lib/python2.7/site-packages/pwntools-2.2-py2.7.egg-info/requires.txt
 - manually install some packages: pacman -S python2-pyserial ropgadget python2-psutil python2-requests

thanks

**Comment by noptrix** [comment]
thx for reporting. we are going to fix it.

**Comment by noptrix** [comment]
fixed and released
