### ISSUE TITLE
Problem when installing from arch

### ISSUE THREAD

**Issue by Oknax** [BlackArch/blackarch#948]
Hi all,
I'm new on Arch Linux. I was pretty on Debian since many years. 
i've tried to install blackarch. All was happening good but at a moment many messages like that appear "error: failed retrieving file 'wyd-0.2-5-any.pkg.tar.xz' from www.blackarch.org : The requested URL returned error: 404"
until this message appear "error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded."
I've tried to change mirrors in my pacman.conf but it still doesn't work.
Please, help me :(

i've made a screenshot : http://hpics.li/a672fe1

**Comment by noptrix** [comment]
simply retry. the mirror was not completely synced i guess.

**Comment by Oknax** [comment]
I've tried again and again and again but doesn't work anymore

**Comment by noptrix** [comment]
can you please show me your pacman.conf. also, please run: pacman -Scc and re-try pacman -Syyu --needed --force blackarch.

**Comment by noptrix** [comment]
or stop by IRC on irc.freenode.net #blackarch

**Comment by Oknax** [comment]
this is my pacman.conf

**Comment by noptrix** [comment]
can you please try this one instead:
[blackarch]                                                                      
Server = http://blackarch.nullsecurity.net/blackarch/$repo/os/$arch

**Comment by noptrix** [comment]
i mean simply choose another mirror

**Comment by Oknax** [comment]
Ok no problem i'm gonna try this one. I'll keep u updated

**Comment by Oknax** [comment]
Still the same message.....
http://hpics.li/660c151

**Comment by noptrix** [comment]
ok that should not be... i think you have done something wrong when setting up the repo. could you please re-try executing: http://blackarch.org/strap.sh - but delete the blackarch related lines from your pacman.conf and remove your /etc/pacman.d/gnupg

**Comment by noptrix** [comment]
so? any news?

**Comment by Oknax** [comment]
Yes, still the same..

**Comment by Oknax** [comment]
Ok i've got an idea but i don't know if it will work. If i install all the packages ( in my /var/pacman/) from pacman -U ? Can it work ?
