### ISSUE TITLE
Problem on istalling BlackArch Linux 32 bit

### ISSUE THREAD

**Issue by Muhammed-Pro** [BlackArch/blackarch#949]
I trying to install BlackArch linux on Virtualbox more than ten times with the same error !
![ksjdfh laj](https://cloud.githubusercontent.com/assets/6201621/9836776/499df8ea-5a26-11e5-9c85-5120df987d91.PNG)

**Comment by aancw** [comment]
Can you try this mirror? 
[blackarch]
Server = http://blackarch.mirror.digitalpacific.com.au/$repo/os/$arch

Hope it will be help

**Comment by Muhammed-Pro** [comment]
How can use it ? btw I see that
Not Found

The requested URL /$repo/os/$arch was not found on this server.
Apache/2.2.15 (CentOS) Server at blackarch.mirror.digitalpacific.com.au Port 80

**Comment by Muhammed-Pro** [comment]
How can use it ? btw I see that
Not Found

The requested URL /$repo/os/$arch was not found on this server.
Apache/2.2.15 (CentOS) Server at blackarch.mirror.digitalpacific.com.au Port 80

**Comment by aancw** [comment]
Add to /etc/pacman.conf

And try to pacman -Syu

**Comment by Muhammed-Pro** [comment]
So How can I access it ?

**Comment by aancw** [comment]
That address wil be something like this http://blackarch.mirror.digitalpacific.com.au/blackarch/os/x86_64/

Are you already add to your /etc/pacman.conf ?

[blackarch]
Server = http://blackarch.mirror.digitalpacific.com.au/$repo/os/$arch

**Comment by Muhammed-Pro** [comment]
Permission denied
![dsljbf](https://cloud.githubusercontent.com/assets/6201621/9848054/18089ff2-5ade-11e5-82da-8deb410725b5.PNG)

**Comment by aancw** [comment]
Dont run /etc/pacman.conf

Just add in /etc/pacman.conf with text editor like nano, vi, vim or other.

**Comment by Muhammed-Pro** [comment]
The problem is on networking on virtualbox, I don't know Why it not connected, any suggestions bro ?
![kdjsgk](https://cloud.githubusercontent.com/assets/6201621/9848961/6b1f0ad4-5ae6-11e5-8596-1bd010be68b7.PNG)

**Comment by aancw** [comment]
Oh ok then. Show me the resulf of ifconfig. and you are use lan cable or wifi?

**Comment by Muhammed-Pro** [comment]
![mednb](https://cloud.githubusercontent.com/assets/6201621/9849989/e0e6a750-5aef-11e5-9aff-ed47a947dcc5.PNG)

**Comment by aancw** [comment]
Nah. The problem is that your network is not detected by virtualbox. Try setting your network again. If you use wifi then set to wireless lan card.

**Comment by noptrix** [comment]
network connection is missing
