### ISSUE TITLE
Problem installing on Pi2

### ISSUE THREAD

**Issue by daveymate** [BlackArch/blackarch#950]
Hey guys, I'm installing blackarch on a Pi2, ARMv7. I used the strap.sh method, and got the core build to install using pacman -S blackarch. Now that everything is installed, I can't access any of the tools. It's like they aren't there. Is there any other documentation I could look through, I've poured through everything I can find with no luck. Thanks

**Comment by aancw** [comment]
Are you already installed that tool?

**Comment by daveymate** [comment]
I can grep blackarch from pacman and see a list of tools. But I can't run them, or even find them any where else in a folder. Not a clue.

**Comment by aancw** [comment]
Can you post a screenshot?
