### ISSUE TITLE
blackarch not boot to UI

### ISSUE THREAD

**Issue by justinpham0210** [BlackArch/blackarch#953]
hi everyone,
I installed blackarch (version 2015.07.31) on virtualbox and hyper-v also but after finish installing it won't boot to UI just tty1 (Blackarch Linux 4.1.6-1-ARCH on tty1). Even after i logged in, i cannot use almost /bin/sh command. :( does anyone esle meet the same problem like me? How can i fix this?

Thanks

**Comment by noptrix** [comment]
will be fixed in the upcoming ISOs. 1-2 weeks
