### ISSUE TITLE
Installing blackarch on arch linux fails

### ISSUE THREAD

**Issue by azzarin** [BlackArch/blackarch#954]
Hey, 
Im trying to install BlackArch on top of Arch Linux. 
after running strap.sh it gives me an error saying: ERROR: invalid keyring signature. please stop by irc.freenode.net/blackarch 

im running this: 
# Run https://blackarch.org/strap.sh as root and follow the instructions: 
$ curl -O http://blackarch.org/strap.sh && sha1sum strap.sh 

# SHA1 sum should match: f8456229463718c097cf70ed06a806f981be7423 
$ sudo ./strap.sh

I have tried to run pacman -Syu/-Scc/-Syyu

**Comment by noptrix** [comment]
can you please join our irc?

**Comment by ramadhinolfski** [comment]
i joined the irc but no one answer my question, i was waiting for long time but still don't have an answer.

would you help me?
