### ISSUE TITLE
os version

### ISSUE THREAD

**Issue by L1ghtn1ng** [BlackArch/blackarch#955]
To make it easier for users to support blackarch can we get the output of the following

platform.linux_distribution()
 ('arch', '', '')

To say

platform.linux_distribution()
('blackarch', '', '')

I am running this under python3

**Comment by L1ghtn1ng** [comment]
This can be fixed by modifying the /etc/os-release file

**Comment by noptrix** [comment]
it is already in the ISO, or what do you exactly mean?

**Comment by L1ghtn1ng** [comment]
If you type python3 in a terminal then import platform then type in
platform.linux_distribution() then hit the enter key the output returned
will say arch. This fuction reads /etc/os-release file. This is the
output taken from Ubuntu's os-release file

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="15.10 (Wily Werewolf)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.10"
VERSION_ID="15.10"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"


We would just need to modify it To say Blackarch. Scripts can call the
platform.linux_distribution() and from that know exactly they are on
Blackarch.

**Comment by L1ghtn1ng** [comment]
Forgot to mention that I am using Ubuntu's os-release file as an example

**Comment by noptrix** [comment]
ok i already got it ... though, we can only use the os-file in the ISOs, not as a blackarch package and updating an existing arch linux...

**Comment by noptrix** [comment]
so i will add in the next ISOs to os-release. thanks. if you don't mind i would like to close the ticket

**Comment by L1ghtn1ng** [comment]
Sure you can close the ticket. Was wondering though that for people that
have it installed already that you can just push out an update to change
it as well as include it in the next ISOs

**Comment by noptrix** [comment]
will be included in the next isos. we will release new isos probably next week ;) thx for sharing the infos

**Comment by L1ghtn1ng** [comment]
If you open a terminal and run the commands in my first post you will get the output arch. This needs to be changed to blackarch. This is so programmes can tell spacifically its blackarch they are on
