### ISSUE TITLE
Inclusion of drozer

### ISSUE THREAD

**Issue by Oweoqi** [BlackArch/blackarch#957]
I've been playing with this in Ubuntu today and it's insanely good. Highly recommend we include this, there's a .deb version too for you to tear to pieces if it makes things easier.

source: https://github.com/mwrlabs/drozer
deb: https://www.mwrinfosecurity.com/system/assets/931/original/drozer_2.3.4.deb

It depends on jdk 1.6 but I've been running it with openjdk 6 and there's been zero issues.

**Comment by noptrix** [comment]
thx, will be included soon

**Comment by Oweoqi** [comment]
I'm a newbie at this, but this about right? http://dpaste.com/35D5MF1

**Comment by noptrix** [comment]
released
