### ISSUE TITLE
Blackarch doesn't see the touchpad on my MacBook Pro 2011

### ISSUE THREAD

**Issue by Nikitaodessa** [BlackArch/blackarch#958]
Blackarch doesn't see the touchpad on my MacBook Pro 2011, when it was installed

**Comment by auscompgeek** [comment]
https://wiki.archlinux.org/index.php/MacBookPro8,1/8,2/8,3_%282011%29

**Comment by MoralDEV** [comment]
chroot into your system and download Synaptics
