### ISSUE TITLE
Invalid or corrupted package (PGP signature)

### ISSUE THREAD

**Issue by brandonriggs** [BlackArch/blackarch#959]
Hey guys,

I'm having an issue when upgrading blackarch via pacman -Syu. Once pacman attempts to install mitmf, I receive the following error:

>error: mitmf: signature from "Levon 'noptrix' Kayan (BlackArch Developer) <noptrix@nullsecurity.net>" is invalid
>:: File /var/cache/pacman/pkg/mitmf-421.d0b4fd6-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
>Do you want to delete it? [Y/n]

Deleting the file makes no difference, nor does pacman -Scc or pacman-key --refresh-keys. I've also tried using both pool/ipv4.pool sks keyservers and MIT's. Please advise, thanks!

> Linux localhost 4.2.2-1-ARCH #1 SMP PREEMPT Tue Sep 29 22:21:33 CEST 2015 x86_64 GNU/Linux

**Comment by aancw** [comment]
Same with this? https://github.com/BlackArch/blackarch/issues/883

**Comment by brandonriggs** [comment]
Appears to be the same error. However, in my case the error appears only when pacman runs the integrity check on the mitmf package. I can still upgrade if I run pacman -Syu --ignore mitmf.

The fixes suggested in that thread did not correct the issue unfortunately.

**Comment by noptrix** [comment]
please try again. and please tell us the mirror you use.

**Comment by brandonriggs** [comment]
Just tried again after clearing cache and the error message persists. The mirrors used were deadbeef.ninja and mirror.team-cymru.org. I also just tried the digitalpacific AU mirror with the same result. Have not tried refreshing the keys, currently doing that.

It probably doesn't make a difference, but I'm now reproducing this error by installing the mitmf package manually. I've removed the old version to prevent having to do --ignore mitmf on every upgrade.

**Comment by brandonriggs** [comment]
Refreshing the keys did not correct the issue. Has anyone else been able to reproduce this?

**Comment by noptrix** [comment]
please switch mirror to blackarch.org main site temporary. don't use the team cymru, as they are not syncing correctly. choose a non-US based mirror please.

**Comment by no-1imit** [comment]
I have the same problem. what should I do?

**Comment by Edu4rdSHL** [comment]
Read the FAQ. https://blackarch.org/faq.html
