### ISSUE TITLE
Out of date packages

### ISSUE THREAD

**Issue by markzz** [BlackArch/blackarch#961]
Here's a small list after I enabled this repository.

warning: android-ndk: local (r10e-1) is newer than blackarch (r9c-3)
warning: android-sdk: local (24.4.1-1) is newer than blackarch (r24.2-1)
warning: android-sdk-platform-tools: local (r23.0.1-1) is newer than blackarch (r22-1)
warning: package-query: local (1.7-1) is newer than blackarch (1.5-1)
warning: pyqt3: local (3.18.1-14) is newer than blackarch (3.18.1-1)
warning: qscintilla-qt3: local (1.7.1-6) is newer than blackarch (1.7.1-1)
warning: qt3: local (1:3.3.8b-9) is newer than blackarch (3.3.8b-1)
warning: ruby-bundler: local (1.10.6-1) is newer than blackarch (1.10.3-2)
warning: yaourt: local (1.7-1) is newer than blackarch (1.6-2)

**Comment by noptrix** [comment]
thx. will be updated

**Comment by markzz** [comment]
Here's a full list of what I compared with packages on the AUR.  The left side of the file is the blackarch repository and the right side is the AUR.

https://gist.github.com/markzz/d944bed00df3756de5a0

**Comment by markzz** [comment]
Yaourt and package query are updated here, but the repository I'm using is not.  When is it planned to actually update the repository?

**Comment by Sunjustice** [comment]
yes

2015-10-28 5:28 GMT+03:30 Mark Weiman <notifications@github.com>:

**Comment by markzz** [comment]
This isn't a question on whether you will update the repositories (and all mirrors), but on when it will be.

**Comment by noptrix** [comment]
done
