### ISSUE TITLE
blackarch on android, compatible devices?

### ISSUE THREAD

**Issue by robertalrp** [BlackArch/blackarch#970]
Hi,

I have to purchase a smartphone and I like to install Linux on it. I am interested on several distro and I focused on Blach Arch as well. I can't purchase a device with linux installed 'cause I need to spend a voucher on the site of MediaWorld and there isn't:/
I'm aware that some smartphone with Android installed are less "Linux-friendly" than other, coul you suggest me some cheap one (about 150 euro)? Should I exclude windows phone at all?
Thank you.

**Comment by noptrix** [comment]
all armv6h and armv7h devices.
