### ISSUE TITLE
[SOLVED]Unrecognized archive format

### ISSUE THREAD

**Issue by CTXz** [BlackArch/blackarch#974]
Hey, If i try to sync with pacman -Syu or -Syyu I can't get download from the blackarch.db package

Here's the error
```
error : could not open file /var/lib/pacman/sync/blackarch.db: Unrecognized archive format
```
Any help appreciated!

**Comment by CTXz** [comment]
FIXED : Changed mirror to Polish

Could it be that the following German mirrors are down/malfunctioning : 
```
http://blackarch1.curesec.com/blackarch/$repo/os/$arch|Cursec
http://blackarch2.curesec.com/blackarch/$repo/os/$arch
```

**Comment by MoralDEV** [comment]
Either that or use blackarch.org official mirror and re sync

**Comment by noptrix** [comment]
Hi, yes, they are down atm. We will refresh our mirror list asap. Thanks.

**Comment by divercarlos7** [comment]
Hello. I have the same problem, but i don´t know how success 
in:
` ➜  ~ sudo pacman -Ss bettercap`
output:
`error : could not open file /var/lib/pacman/sync/blackarch.db: Unrecognized archive format`

I don´t know what I have to do.
I´m from colombia forgive my english. Any help is welcome.
