### ISSUE TITLE
Problem with installing on top of ArchLinux

### ISSUE THREAD

**Issue by Muller92** [BlackArch/blackarch#978]
![capture](https://cloud.githubusercontent.com/assets/4946336/11460313/5fb4c46e-9703-11e5-9996-de666f635cd7.PNG)
I have some problem with suricata

**Comment by noptrix** [comment]
known issue since today. we are working on it. simply exclude suricata or try --force

**Comment by Muller92** [comment]
I try it but it does not work in my case

**Comment by noptrix** [comment]
--ingore suricata

**Comment by noptrix** [comment]
what did you try? --force or --ignore?

**Comment by Muller92** [comment]
i try --force and it's not work, but --ignore work correctly. thank you
