### ISSUE TITLE
Bettercap issue

### ISSUE THREAD

**Issue by Oweoqi** [BlackArch/blackarch#979]
Got Bettercap going during a pentest and it failed, I'll try to provide more info/investigation later. Installed via pacman -S, what happened when I ran:

{root@blackarch ~}¥ sudo bettercap -X -I wlp2s0
 _          _   _
| |__   ___| |_| |_ ___ _ __ ___ __ _ _ __
| '_ \ / _ \ __| __/ _ \ '__/ __/ _` | '_ \
| |_) |  __/ |_| ||  __/ | | (_| (_| | |_) |
|_.__/ \___|\__|\__\___|_|  \___\__,_| .__/
                                     |_| v1.1.7
http://bettercap.org/

[I] Targeting the whole subnet 192.168.1.0..192.168.1.255 ...
[I] Network discovery thread started.
[I] Searching for alive targets ...
[I] Getting gateway 192.168.1.1 MAC address ...
[I]   Gateway : 192.168.1.1 ( <redacted> )
[I] Starting ARP spoofer ( Full Duplex ) ...
[I] Starting sniffer ...
[I] ARP watcher started ...
[E] uninitialized constant PacketFu::Capture
[E] uninitialized constant Sniffer::Capture
[E] /usr/lib/ruby/gems/2.2.0/gems/bettercap-1.1.7/lib/bettercap/sniffer/sniffer.rb:94:in `setup'
/usr/lib/ruby/gems/2.2.0/gems/bettercap-1.1.7/lib/bettercap/sniffer/sniffer.rb:28:in `start'
/usr/lib/ruby/gems/2.2.0/gems/bettercap-1.1.7/bin/bettercap:259:in `<top (required)>'
/usr/bin/bettercap:23:in `load'
/usr/bin/bettercap:23:in `<main>'
[I] Stopping network discovery thread ...
[I] Stopping ARP spoofer ...
[I] Restoring ARP table of 0 targets ...

**Comment by noptrix** [comment]
thx for reporting. will fix it

**Comment by noptrix** [comment]
uhm, should be fixed. please re-install / upgrade

**Comment by Oweoqi** [comment]
No good, but I just checked the gemspec and they aren't including network_interface. I'll submit a pull upstream
