### ISSUE TITLE
Metasploit not work...

### ISSUE THREAD

**Issue by danillofa** [BlackArch/blackarch#982]
when I try to run the msfupdate, of the following error:

[ blackarch ~ ]# msfupdate 
[*]
[*] Attempting to update the Metasploit Framework...
[*]

/usr/share/metasploit/msfupdate:143:in `block in run!': Cannot determine checkout type: `/usr/share/metasploit' (RuntimeError)
        from /usr/share/metasploit/msfupdate:135:in `chdir'
        from /usr/share/metasploit/msfupdate:135:in `run!'
        from /usr/share/metasploit/msfupdate:292:in `<main>'

how to solve this problem?

**Comment by noptrix** [comment]
on the iso?

**Comment by danillofa** [comment]
installed using the iso blackarchlinux-live-2015.11.24-x86_64.

**Comment by noptrix** [comment]
pacman -S metasploit-msfupdate ? So either you can update on your own using metasploit-msfupdate or you pacman -Syyu every week (we update msf per week)
