### ISSUE TITLE
airspy, bladerf and hackrf udev rules use GROUP="plugdev"

### ISSUE THREAD

**Issue by rbellamy** [BlackArch/blackarch#983]
Installed the `blackarch-wireless` group.

`gnuradio` requires `gnuradio-osmosrdr` requires `airspy`

`airspy`, `bladerf` and `hackrf` all have udev rules that use `GROUP="plugdev"`, yet nowhere is this group created by a package.

The udev rules in this repo don't use the group (e.g. [88-bladerf.rules](../blob/master/packages/bladerf/88-bladerf.rules)).

```
Dec 11 12:13:40 monkey systemd-udevd[443]: specified group 'plugdev' unknown
```

**Comment by noptrix** [comment]
thx for reporting. will be fixed.

**Comment by PedroSFreitas** [comment]
All those tools are on community (Archlinux).
I believe this should be an upstream problem? Of course, if it isn't already fixed.

@rbellamy Do you have any news on this? (since, as I said, they're on Community).
If it's okay, we could close this issue.

**Comment by PedroSFreitas** [comment]
Closing... upstream (Arch Linux).

If anyone think it's a mistake, just reopen it and provide further information. Thanks in advance.
