### ISSUE TITLE
naming conventions of android-sdk conflicts with AUR naming

### ISSUE THREAD

**Issue by mralext20** [BlackArch/blackarch#985]
the AUR package is currently called 24.4.1-1, while the blackarch package has the version r24.4.1-1, causing pacman to think that local is newer than the remote, and warning the user that the versions don't match.

can this be fixed by changing the version from r24.4.1-1 to 24.4.1-1?

example error: 

````warning: android-sdk: local (24.4.1-1) is newer than blackarch (r24.4.1-1)````

**Comment by noptrix** [comment]
yes, we can fix it. thx for reporting.

**Comment by noptrix** [comment]
hello, the release versions are called 'rX.X.X' at android/google. we don't want to change the original naming convention. either remove the AUR package and use ours or simply ignore the 'warning' message. thanks for your understanding
