### ISSUE TITLE
Cannot boot blackarch-netinstall x64 in VirtualBox

### ISSUE THREAD

**Issue by 0xABD** [BlackArch/blackarch#988]
1) Download blackarchlinux-netinst-2015.11.24-x86_64.iso
2) Verify checksum
3) Create a new empty x64 VM in VirtualBox (latest 5.0.10), in VirtualBox settings specify OS:Linux, Arch, x64
4) Boot the new VM with BlackArch ISO in the virtual CDROM
5) The BlackArch boot menu pops up, but there is NO option to boot or install BlackArch, only boot from HDD, memtest, HW info, reboot, halt.
![blackarch20151124](https://cloud.githubusercontent.com/assets/991923/11870118/241883da-a4c5-11e5-900e-faf836e13bed.png)

**Comment by noptrix** [comment]
what arch is your host system? i686 or x86_64?

**Comment by 0xABD** [comment]
The host machine is x64, with all virtualization features supported by CPU & chipset and enabled.
I have also tried setting the VM to use UEFI (which is not a default setting), this helps to boot the image.

**Comment by noptrix** [comment]
so can we close this issue?

**Comment by 0xABD** [comment]
Yes, could you please explain then whether UEFI is a must or no? 
Did not see that UEFI requirement in the docs & have created VMs without UEFI for ages.
