### ISSUE TITLE
Black arch will not live boot or give a install option

### ISSUE THREAD

**Issue by LinuxGuru25** [BlackArch/blackarch#990]
I have used DD to write the iso to a usb when i boot the usb it only gives me a boot existing operarting system option i have tried everything i can think of i can start arch install just fine someone help me out so frustrated right now

**Comment by demogorgonz** [comment]
Make sure that it is bootable.. or that you have selected in bios right boot options..

**Comment by LinuxGuru25** [comment]
I have booted many Linux distributions I don't have uefi secure boot and
I'm really seasoned with Linux and that's what bothers me I even did a Arch
install to check and Arch installed perfectly I want to switch to black
arch I'm trying to get away from Kali Linux so I appreciate your feedback

**Comment by ikstream** [comment]
If you have a working arch setup, why not install black arch on top of it?
Works fine for me.
http://blackarch.org/downloads.html#install-repo

**Comment by noptrix** [comment]
which ISO did you download and on which host-system did you boot (architecture)?

**Comment by LinuxGuru25** [comment]
I used a 32 bit ISO on a 32 bit machine I'm sure I have everything right on my end and I use DD to write the image to USB .it will not give me a boot live or even a install option just boot existing OS

**Comment by noptrix** [comment]
have you tried the newest ISOs 2016.01.10? Also, how did you 'dd'ed?

**Comment by LinuxGuru25** [comment]
I have not tried the 2016 ISO kind of got discouraged and I use sudo dd if=(path to ISO) of=/dev/sdb bs=512

**Comment by noptrix** [comment]
can you please send us more information about your system? also, in general we need more infos, e.g.: logfiles, screenshots, ...

**Comment by LinuxGuru25** [comment]
I can give you the laptop specs its a intel Pentium dual core clocked at 2.0 ghz with a gm45 express chipset 4 gigs of ram 800 mhz clock acer aspire is the model ill have to write the new iso and try to boot it to get screenshots for you.I will get on that asap thanks for the response.

**Comment by noptrix** [comment]
ok. also use: dd if=<iso> of=/dev/sdb bs=512M (you forgot the M=megabytes)

**Comment by LinuxGuru25** [comment]
Oops I usually use 512k I forget to add that in my post sorry

**Comment by LinuxGuru25** [comment]
no luck with new iso same results on two different computers

**Comment by noptrix** [comment]
ok, as we just noticed, this is again the same issue (i686 related only) reported multiple times. we are working on this and we will fix it soon with the new upcoming ISOs.

**Comment by sunilolo** [comment]
I use to have the same problem - boot blackarch.iso from usb --   and i try Rufus  utility and its  work now .. 
Rufus  utility >> https://rufus.akeo.ie/?locale=en_US 
i choose this one Rufus 2.11 (916 KB)
The utility will ask to download  --  ldlinux.sys -- and  -- ldlinux.bss -- and it will do it Automatically
and i use this Image
http://www.mirrorservice.org/sites/blackarch.org/blackarch/iso/blackarchlinux-live-2016.08.31-x86_64.iso
  And this one too
http://www.mirrorservice.org/sites/blackarch.org/blackarch/iso/blackarchlinux-netinst-2016.08.31-i686.iso
the user name is : root  and the password is : blackarch
Goodluck

**Comment by hp040** [comment]
Here in this video you can learn how to make live bootable usb of blackarch linux (HACKING OS) or any other linux in 5 min easily https://youtu.be/OC6fBgmA_zI
