### ISSUE TITLE
missing packages

### ISSUE THREAD

**Issue by yhfudev** [BlackArch/blackarch#991]
The following package files are missing when BlackArch installed in a i686 machine:

ruby-record-0.0.1-2-any.pkg.tar.xz: this package is missing and caused the "jigsaw" can't be installed. Both of the upstream repos for these project were removed, and we can't compile it from source.

sb0x-19.04f40fe-2-any.pkg.tar.xz
sipsak-0.9.6-4-i686.pkg.tar.xz
spectools-2010_04_R1-2-i686.pkg.tar.xz
speedpwn-8.3dd2793-1-i686.pkg.tar.xz
sslcat-1.0-1-i686.pkg.tar.xz
sslsniff-0.8-5-i686.pkg.tar.xz
tcpick-0.2.1-2-i686.pkg.tar.xz
tcpjunk-2.9.03-5-i686.pkg.tar.xz
treasure-6.a91d52b-1-any.pkg.tar.xz
unicornscan-0.4.7-7-i686.pkg.tar.xz
voipong-2.0-1-i686.pkg.tar.xz
xf86-video-qxl-git-r541.cbe70e9-1-i686.pkg.tar.xz
xplico-33.0f6d8bc-2-i686.pkg.tar.xz

**Comment by noptrix** [comment]
hi, thx for reporting. we have removed those packages from i686 since the packages are broken: either not able to compile or not available anymore. please perform a sync: pacman -Syy
