### ISSUE TITLE
Make a html version of http://blackarch.org/guide.pdf

### ISSUE THREAD

**Issue by n0x00** [BlackArch/blackarch#994]
it can be searched properly by search engines then : )

http://blackarch.org/guide.pdf

**Comment by heichblatt** [comment]
[Pandoc](http://pandoc.org/) can create HTML from .tex. When you pipe the generated, unedited HTML into the W3C validator, it throws only 3 errors.

    $ pandoc -s -f latex -t html https://raw.githubusercontent.com/BlackArch/blackarch-guide/master/latex/blackarch-guide-en.tex | curl -H "Content-Type: text/html; charset=utf-8" --data-binary @- https://validator.w3.org/nu/?out=gnu
    :1.1-1.121: error: Almost standards mode doctype. Expected e.g. “<!DOCTYPE html>”.
    :5.3-5.61: error: Bad value “Content-Style-Type” for attribute “http-equiv” on element “meta”.
    :7.10-7.17: error: Element “title” must not be empty.
    :1.122-2.43: info warning: This document appears to be written in English. Consider adding “lang="en"” (or variant) to the “html” start tag.

 Applying the correct CSS, however, may be a bit trickier.
