### ISSUE TITLE
ruby gem conflict for bettercap and ssrf-proxy

### ISSUE THREAD

**Issue by 9M2PJU** [BlackArch/blackarch#995]
usr/lib/ruby/gems/2.2.0/cache/colorize-0.7.7.gem exists in both 'bettercap' and 'ssrf-proxy'

**Comment by auscompgeek** [comment]
Both packages really ought to depend on `ruby-colorize`, which also happens to currently be in the blackarch repo.

**Comment by noptrix** [comment]
9M2PJU, use --force option of pacman
