### ISSUE TITLE
Proxenet compiled with old version of mbedtls

### ISSUE THREAD

**Issue by kurobeats** [BlackArch/blackarch#996]
Not sure if it's an upstream issue, but when trying to launch proxenet, following error occurs:

/usr/share/proxenet/proxenet: error while loading shared libraries: libmbedtls.so.9: cannot open shared object file: No such file or directory

The installed version of libmbedtls is libmbedtls.so.10.

**Comment by noptrix** [comment]
unfortunately proxenet searches for "polarssl" which was replaced by mbedtls. we cannot compile proxenet atm due to missing 'polarssl'... so that means, either we have to wait for updates from proxenet or you could try create a patch.

**Comment by noptrix** [comment]
fixed.
